### ISSUE TITLE
CosmosDBTrigger create a lease container with wrong partition key id

### ISSUE THREAD

**Issue by rafaarcangel** [Azure/azure-functions-dotnet-worker#1002]
**Issue:**
When using the trigger for CosmosDB and using the parameter 'CreateLeaseCollectionIfNotExists' the result is a container on the CosmosDB but with the wrong default partition key.

**What happened**:
The partition key for the new lease container created has '/_partitionKey' as id, but this is wrong because it will be '/id'.
The first time you execute the Az Function, it will run properly.
The next time you execute it, you will receive a failure:
     - _**Azure Function fails to start with "The lease collection, if partitioned, must have partition key equal to id."**_

**What you expected to happen**:
The new lease container must be created with the default partition key => "/id"

**How to reproduce it (as minimally and precisely as possible)**:
- Create a CosmosDB resource on Azure
- Create an AzFunc with CreateLeaseCollectionIfNotExists=true;
- Execute it and see the result on Azure Portal:
![image](https://user-images.githubusercontent.com/19646006/186134106-12f874cc-63ab-4286-a5f9-9d52053048c7.png)
![image](https://user-images.githubusercontent.com/19646006/186134609-f2c69f15-1be3-4627-90f4-77036a213c68.png)

**Source code sample**:
 ```         [Function("CosmosFunction")]
        public Task RunAsync([CosmosDBTrigger(
            "%DatabaseOptions:Database%",
            "%DatabaseOptions:ContainerName%",
            ConnectionStringSetting = "DatabaseOptions:ConnectionString",
            CreateLeaseCollectionIfNotExists = true,
            LeaseCollectionName = "leases",
            LeaseCollectionPrefix = "prefix")] IReadOnlyCollection<Record> input)
```

**Environment**:

- .NET Core version: 6.0
- Azure function worker versions:
     "Microsoft.Azure.Functions.Worker" Version="1.6.0"
    "Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0"
    "Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="3.0.9"
    "Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="5.1.0"
    "Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13"

**Comment by kshyju** [comment]
@ealsur Could you help with this question?

**Comment by ealsur** [comment]
Code reference: 

https://github.com/Azure/azure-webjobs-sdk-extensions/blob/cosmos/v3.x/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs#L220-L230

The Change Feed Processor in the 3.X package works well with collections with `/_partitionKey`, this behavior has been maintained across the 3.X package, it has not changed. The Lease collection is created without defining a Partition Key in that version and if it's a Shared Throughput Database, then we enforce the `/id` (because that's the only way).  The 3.X package uses the V2 SDK.

The error "The lease collection, if partitioned, must have partition key equal to id" is coming from the V3 SDK: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6a38b2d3fec01dc8e78f4cdc2e8c98f82a7a8e8f/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreManagerBuilder.cs#L35

This means that there is a mixup of extension versions. The extension 4.X is the one using the V3 SDK. This would mean you have a mix of 3.X and 4.X extension Functions. Is this the case?

**Comment by ealsur** [comment]
I could not repro the error, I was able to confirm that extension 3.X creates a lease container with `/_partitionKey` but this keeps working across different restarts of said Function, this is a scenario that has always been supported on 3.X extension versions.

I also went ahead and ported the project to use 4.X extension, and the same Function kept working (with the same lease container).

I don't see a scenario where the Trigger would output that error message. The message seems to only be present on the V3 SDK (4.X extension).

**Comment by fabiocav** [comment]
Thank you for the response here, @ealsur 

@rafaarcangel does the information above help? Do you happen to have multiple Function Apps using the same resource? 

If this continues to be an issue, are you able to provide a repro? 

Thanks!

**Comment by rafaarcangel** [comment]
Thanks for your responses. I use it as a part of a bigger flow but only in this particular function. 
I really don't know the behavior under the hood, but the problem persists. 

After reviewing the logic that @ealsur provide to me, I saw that I receive a true condition:
isPartitioned = true; 
isMigratedFixed = false, 
and ... containerProperties.PartitionKey.Paths[0] != "/id".

I'm using the AzFunc on a Kubernetes cluster, with other AzFuncs. 
Another important point (maybe) is that all of them are running as an isolated process:

```
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "FUNCTIONS_EXTENSION_VERSION": "~4",
```

I needed to create the cosmos table through terraform, to have it with the right /id key.
Anyway, it could be good if we can set the partition key on the AzFunc itself with a param 'LeaseCollectionPartitionKey' (with a default value of '/_partitionKey' if you want) to prevent this error.

**Comment by ealsur** [comment]
@rafaarcangel The code you refer to is for the V3 SDK (so I guess you are using extension `4.0.0-preview`). 

This version (4.X) creates the lease container with `/id` if it doesn't exist (https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs#L143). If your lease container is partitioned with `/_partitionKey` then it means it was created by an older extension or something that is using the V2 SDK.

You could potentially have a mix of Function versions (some other deployed Function using a different version) but targeting the same lease container.

**Comment by rafaarcangel** [comment]
Ok,... I'll try to review which version I had.
Thank you all for your support!
