### ISSUE TITLE
Add support for Azure AD authentication for Application Insights

### ISSUE THREAD

**Issue by olandese** [Azure/azure-functions-dotnet-worker#1004]
Please add support to the new feature "Azure AD authentication for Application Insights" (now GA):

https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net

I want to use an User Managed Identity to be able to write logs from an isolated linux function to AI with this feature enabled, I can't see any option to configure this in the Microsoft.Azure.Functions.Worker.ApplicationInsights package.

**Comment by brettsam** [comment]
@AnatoliB / @RohitRanjanMS -- is this something that you are looking into for the host as well? We'll need to collaborate across these two packages.

**Comment by amilochau** [comment]
Do we have any update on this issue? It would be a great improvement to enforce better security in my organization.

**Comment by jviau** [comment]
For the host side, this is being worked of: https://github.com/Azure/azure-webjobs-sdk/pull/2986

For the worker side, using the preview package: https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627 this is supported. As this sits ontop of the existing AppInsights SDK and you can configure it to use AzureAD auth.
