### ISSUE TITLE
[ColdStart] Explore NET7 AOT / Placeholders

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1013]
Try NET7 AOT publishing & measure cold start impact.
Explore placeholder option.

**Comment by fabiocav** [comment]
Work for this is in progress and will span across a few sprints as validation happens.

**Comment by fabiocav** [comment]
Most of the AOT work/validation here has been completed. 

Currently working on placeholder options.

**Comment by fabiocav** [comment]
Investigation here is done. Validation on different approaches is in progress and concrete work items will be opened as needed.
