### ISSUE TITLE
Worker options to opt-in the behavior to get empty entries in payload

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1017]
We [recently updated ](https://github.com/Azure/azure-functions-host/issues/8499)host to include empty entries when sending the message payload to out of process layer when the `IncludeEmptyEntriesInMessagePayload` capability is present. We need to allow users to opt in to this behavior via worker options when they bootstrap the function app.

Something like

    var host = new HostBuilder()
        .ConfigureFunctionsWorkerDefaults(builder =>
        {
        }, options =>
        {
            options.IncludeEmptyEntriesInPayload = true;
        })
        .Build();

- Needs to agree on naming of property.
- Should it be on the root level or should we move it under some other property to be better organized.

**Comment by wesselkranenborg** [comment]
This is the last step to resolve bug #876 and enable us to enable batching again on the eventhub trigger.

**Comment by wesselkranenborg** [comment]
@satvu @kshyju: is there any contribution I can do to speed this up a little bit? If you have any guidance on the two open questions I could look if I can make a contribution for this.
