### ISSUE TITLE
Investigate SDK-type binding support for OOP workers

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1018]
- [x] Proposal for OOP support for sdk-type bindings
- [x] Prototype with Blob storage

**Comment by fabiocav** [comment]
This work has been completed. @liliankasem will be opening additional issues for the work we're tracking for sprint 130

**Comment by SeanFeldman** [comment]
> Proposal for OOP support for sdk-type bindings

Is that a publicly available document?
