### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: The gRPC channel URI 'http://:0' could not be parsed.

### ISSUE THREAD

**Issue by GurdipS5** [Azure/azure-functions-dotnet-worker#1030]
Hi,

I have a function in isolated .NET 6.0 which runs in Kubernetes but gives this error:

Unhandled exception. System.InvalidOperationException: The gRPC channel URI 'http://:0' could not be parsed.

I am trying to fix this, I even set the function configuration in Program.cs but same thing. Is there a way to avoid GRPC support?

**Comment by satvu** [comment]
@GurdipS5 How are you trying to run this? Are you doing `dotnet run` on the FunctionApp.exe? Please provide minimal repro steps.
