### ISSUE TITLE
[BUG] Null reference exception in isolated Function application

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-functions-dotnet-worker#1031]
@torepaulsson commented on [Tue Sep 13 2022](https://github.com/Azure/azure-sdk-for-net/issues/31094)

### Library name and version

Azure.Messaging.ServiceBus, v. 7.10.0.0/omewhere it uses 7.8.0.0

### Describe the bug

I've noticed that my out-of-process Azure Function app fail sometime with a LOT of NullReferenceException that are thrown from `Azure.Mesaging.ServiceBus.ReceiverManager.RenewMessageLockAsync`.

Checking the logs in log analytics I get a long list of exceptions:
![image](https://user-images.githubusercontent.com/10498076/189899837-7a262b21-c029-4c43-81ee-180816a13c04.png)
For some reason the logs also come from the same operationid, this error is *logged around 7600 times*.

My function app use 7.10.0.0 but it seems the version 7.8.0.0 is used somewhere (since that is in the stack trace).

Call stack:
```
System.NullReferenceException:
   at Azure.Messaging.ServiceBus.ReceiverManager+<RenewMessageLockAsync>d__18.MoveNext (Azure.Messaging.ServiceBus, Version=7.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
```

FormattedMessage:
```
Message processing error (Action=RenewLock, EntityPath=<subscription>, Endpoint=<servicebus-endpoint>)
```

At the top of the execution a TaskCanceledException is thrown. I wonder if this has to do with when a instance is being terminated?

### Expected behavior

No NullReferenceException is thrown.

### Actual behavior

NullReferenceException is thrown.

### Reproduction Steps

* Create a out of process function app with a service bus trigger to a topic with subscription.
* Trigger the function app 50 times per second (could vary from 30-60 requests per second).
* See the error (hopefully) occurs, I see it around after 20 minutes.

### Environment

Windows
dotnet6

---

@jsquire commented on [Tue Sep 13 2022](https://github.com/Azure/azure-sdk-for-net/issues/31094#issuecomment-1245362246)

Thank you for your feedback.  Tagging and routing to the team member best able to assist.

---

@JoshLove-msft commented on [Tue Sep 13 2022](https://github.com/Azure/azure-sdk-for-net/issues/31094#issuecomment-1245769871)

@torepaulsson,
This NullReferenceException was an issue in 7.8.0 that was fixed in 7.8.1. Can you include your projects dependencies so we can try to understand where this version is getting pulled in?

---

@JoshLove-msft commented on [Tue Sep 13 2022](https://github.com/Azure/azure-sdk-for-net/issues/31094#issuecomment-1245776978)

I think this may be due to how dependencies work when using isolated functions. I've reached out to the Functions team for more info.

Worst case scenario, we will just need to ship a new version of the isolated worker that depends on the latest extension version where the issue is fixed.

---

@JoshLove-msft commented on [Tue Sep 13 2022](https://github.com/Azure/azure-sdk-for-net/issues/31094#issuecomment-1246139362)

It looks like we will need a new version of the isolated worker to be shipped. I'm transferring this issue over to repo that has the worker project.

**Comment by satvu** [comment]
@torepaulsson What version of worker extension are you using?

**Comment by torepaulsson** [comment]
I use version 1.8.0, I've included a list of the other Microsoft packages below.

```
<PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.4.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.4.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
<PackageReference Include="Microsoft.Extensions.Azure" Version="1.4.0" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.8" />
```

**Comment by fabiocav** [comment]
@JoshLove-msft @torepaulsson the extension has now been published: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ServiceBus

Thanks!
