### ISSUE TITLE
Can't "Test/Run" in portal with .net 6, AF v4, dotnet-isolated 

### ISSUE THREAD

**Issue by ryansan** [Azure/azure-functions-dotnet-worker#1033]
![image](https://user-images.githubusercontent.com/31653675/190421892-17805aa4-afa6-427c-98af-32eaefdb4f2a.png)

This is a function with HTTP trigger. Is running an isolated function through the portal not supported or this a bug?

**Comment by ryansan** [comment]
Also why does it say "Editing .NET 5 Function Apps is not supported in the Azure portal. Use your local development environment to edit this Function App." in the overview pane. I'm using .NET 6. Not trying to edit the function app though the portal, just wondering.

**Comment by kshyju** [comment]
Currently this is a known issue in the portal and we are working on fixing this. You can always test your http triggers using tools like Fiddler or Postman.

For the "_Editing .NET 5 Function Apps is not supported in the Azure portal_" message, It is an informational message. Let me follow up with the portal team to see whether this message is relevant anymore. (cc @cloudmelon)

**Comment by ryansan** [comment]
I see. Can you give a rough estimate for when we can expect a fix for this?

**Comment by kshyju** [comment]
No ETA to share at the moment. We will keep this issue open to track these items and share an update here when we have one. Stay tuned.

**Comment by fabiocav** [comment]
@cloudmelon will follow up with something we can use to track the progress of this work

**Comment by madushans** [comment]
Previously I could manually trigger timer functions from portal as well. After upgrading to net7 (isolated) the tooltip says this is (will be?) only supported for HTTP functions.

![image](https://user-images.githubusercontent.com/2970078/209115679-c0c42d80-15be-4ac6-9d97-aa2561f13f88.png)

Is this just an incorrect tooltip in the portal? or is the support for this scenario being dropped?

I quite liked it since I didn't have to have a separate HTTP function to do the same when I just wanted to one off trigger a timer function.

**Comment by blgorman** [comment]
This is still happening for me for .Net 7 Isolated functions.  You can still trigger the function just fine from the URL using cURL or Postman or just browsing to it, but it's annoying that you can't test it in the portal
![image](https://user-images.githubusercontent.com/785214/214206702-11f94d2a-347a-47e1-ab94-0f80972beff2.png)

**Comment by uchitha** [comment]
Is this the same issue being discussed [here](https://github.com/Azure/azure-functions/issues/2224)

**Comment by blgorman** [comment]
Yes, this seems to be the same issue with just a more user-friendly message
in the tooltip.  I'll check again after the weekend and see if I still see
the error.

Thanks so much for the quick reply!

**Comment by kshyju** [comment]
"Test/Run" works in the portal now. Please let us know if you run into issues.

**Comment by oskarthansen** [comment]
I have a TimerTrigger. When i test it on Azure Portal, clicking "Run", with an empty body and using the master (Host key), it says "404 Not Found"
