### ISSUE TITLE
Implement Cosmos DB rules and converter

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1034]
Expand the existing sdk-type binding prototype to also include hydrating a Cosmos DB client.

- [x] Create input and trigger binding rules in the [webjobs extension for cosmos ](https://github.com/surgupta-msft/azure-sdk-for-net/tree/main/sdk/cosmosdb)
- [x] Write a converter in the [worker extension](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/extensions/Worker.Extensions.CosmosDB/src) to hydrate the cosmos DB client
- [x] Support POCO bindings for the trigger

**Comment by fabiocav** [comment]
Work in progress. Validating the flow and finalizing the trigger implementation.
