### ISSUE TITLE
Implement SDK-type binding prototype using new version of ParameterBindingData

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1035]
Prototype the SDK-type binding feature with this new [ParameterBindingData](https://github.com/Azure/azure-webjobs-sdk/blob/c3c16c0f78c406043bf71da80586da0a7499acab/src/Microsoft.Azure.WebJobs.Host/Bindings/ParameterBindingData.cs) instead of using a property dictionary

```csharp
public class ParameterBindingData
{
    public string Version { get; set; }
    public string ContentType { get; set; }
    public string Source { get; set; }
    public object Content { get; set; }
}
```

**Comment by fabiocav** [comment]
Closing this as the work has been done in the initial prototype
