### ISSUE TITLE
Design a pattern for extensions to advertise the types they support

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1036]
Pattern to allow an extension to let us know what types it supports. 

a) We discussed maybe passing the extensions converter to the analyzer, and having the analyzer look through the convert to see the types supported by a given extension.

b) We discussed adding a new property to the [ExtensionInformationAttribute](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Abstractions/src/ExtensionInformationAttribute.cs), maybe a list, to indicate what types the extension supports

First part of this - https://github.com/Azure/azure-functions-dotnet-worker/issues/1121

**Comment by surgupta-msft** [comment]
Had discussion with @fabiocav and @kshyju about it. I have clarity on the flow and changes need to be done here.

**Comment by fabiocav** [comment]
Initial design completed. @surgupta-msft  to share details here. Will have an issue tracking the implementation linked here as well.

**Comment by surgupta-msft** [comment]
Issue tracking implementation of this design - https://github.com/Azure/azure-functions-dotnet-worker/issues/1144
