### ISSUE TITLE
Always throwing general exception even though i raise custom exception.

### ISSUE THREAD

**Issue by rbaddam09** [Azure/azure-functions-dotnet-worker#1038]
I'm throwing custom exception based on the scenarios but it's always going to general exception in custom middle ware. 
It is always going to default in switch case instead of KeyNotFoundException. is this expected behavior?. Am i missing anything to add?. 
middleware:
namespace WebApi.Middleware
{
    public class ErrorHandlerMiddleware
    {
        private readonly RequestDelegate _next;

        public ErrorHandlerMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            try
            {
                await _next(context);
            }
            catch (Exception error)
            {
                var response = context.Response;
                response.ContentType = "application/json";

                switch(error)
                {
                    case AppException e:
                        // custom application error
                        response.StatusCode = (int)HttpStatusCode.BadRequest;
                        break;
                    case KeyNotFoundException e:
                        // not found error
                        response.StatusCode = (int)HttpStatusCode.NotFound;
                        break;
                    default:
                        // unhandled error
                        response.StatusCode = (int)HttpStatusCode.InternalServerError;
                        break;
                }

                var result = JsonSerializer.Serialize(new { message = error?.Message });
                await response.WriteAsync(result);
            }
        }
    }
}

Exmple Error Service:
namespace WebApi.Services
{
    public class ExampleErrorService
    {
        public void ExampleErrors() {
            // a custom app exception that will return a 400 response
            throw new AppException("Email or password is incorrect");

            // a key not found exception that will return a 404 response
            throw new KeyNotFoundException("Account not found");
        }
    }
}

**Comment by kshyju** [comment]
The code shared here does not look like azure functions code. If you are trying to create a middleware in aspnet core web api and running into issues,  please open an issue in https://github.com/dotnet/aspnetcore repo. Thanks!
