### ISSUE TITLE
[AppInsights] verbose request tracing

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#1040]
I have one more issue to report though. We still see the multiple Trace messages logged for all dependencies (usually one for start request and one for stop)  in addition to the Dependency object in AppInsights. We were hoping the re-introducing the dependencies back in the preview package will eliminate the extra traces. Can you please advise how we can disable them? 
Here is a segment of just one execution : 
![image](https://user-images.githubusercontent.com/1653359/186307377-6f1216c5-ff36-47c5-9f6f-5858bfbd9646.png)

_Originally posted by @LenaVinogradov in https://github.com/Azure/azure-functions-dotnet-worker/issues/998#issuecomment-1225107426_

**Comment by brettsam** [comment]
@LenaVinogradov -- I've created a new issue here to track this. 

Can you share how you've set up your Program.cs in the worker? I don't see these logs anywhere in my samples and they appear to be [coming from .NET](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingScopeHttpMessageHandler.cs#L96). Could you have enabled them somehow?

**Comment by brettsam** [comment]
Oh, are you using the HttpClientFactory? These may be coming from there: https://www.stevejgordon.co.uk/httpclientfactory-asp-net-core-logging

**Comment by fabiocav** [comment]
@brettsam to review and decide whether we need to continue tracking this as an issue.

**Comment by brettsam** [comment]
Closing this out. I'm fairly certain it was a configuration or setup issue as we've not been able to reproduce this.

**Comment by LenaVinogradov** [comment]
Hi @brettsam 
here us what we have in our program: /// <summary>
/// Entry point for the function app
/// </summary>
public class Program
{
	public static async Task Main()
	{
		var host = new HostBuilder()
			.ConfigureFunctionsWorkerDefaults(builder =>
			{
				// preview feature: https://github.com/Azure/azure-functions-dotnet-worker/issues/760#issuecomment-1219925559
				// usage example from their PR: https://github.com/Azure/azure-functions-dotnet-worker/pull/944/files#
				// https://github.com/Azure/azure-functions-dotnet-worker/issues/760#issuecomment-1220951779
				builder.AddApplicationInsights().AddApplicationInsightsLogger();
			})
			.ConfigureOpenApi()
			.ConfigureLogging(logging => logging.AddFilter<ApplicationInsightsLoggerProvider>(null, LogLevel.Information))
			.ConfigureAppConfiguration(builder => Startup.ConfigureAppConfiguration(builder))
			.ConfigureServices(collection => Startup.Configure(collection))
			.Build();

		await host.RunAsync();
	}
}

in addition in  the StartUp we have this : 
	public static void ConfigureServices(
			IServiceCollection services
			)
		{
			services.AddSingleton<ITelemetryInitializer, CoreTelemetryInitializer>();
			services.AddLogging();

			// This will register the HttpClientFactory that will self manage clients
			// Details at: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0
			services.AddHttpClient();

			// This will register the polly extension for retry on all http requests done through the above HttpClients
			// Details at: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly
			services.AddSingleton(GetRetryPolicy());
			// TODO - later: doesn't seem to be required:
			// Pending azure team answering my question here: // https://github.com/Azure/azure-functions-dotnet-worker/issues/760#issuecomment-1220951779
			// services.AddApplicationInsightsTelemetryWorkerService();
			services.AddAzureAppConfiguration();
			services.AddAzureClients(builder =>
			{
				if (IsRunningLocally())
				{
					// Direct connection string when running locally
					// IgnoreException(SecurityException)
					builder.AddConfigurationClient(Environment.GetEnvironmentVariable("appConfigurationConnectionString"));
				}
				else
				{
					// Managed identity in Azure
					builder.AddClient<ConfigurationClient, ConfigurationClientOptions>(options =>
					{
						// IgnoreException(UriFormatException)
						return new ConfigurationClient(new Uri(Environment.GetEnvironmentVariable("appConfigurationEndpoint")!), StartupShared.GetDefaultAzureCredential());
					});
				}
			});

			services.AddScoped<IExecutionContext, ExecutionContext>();
		}
Advise please?

**Comment by brettsam** [comment]
To make sure I understand the question -- are you trying to filter away the highlighted logs above?

If so -- those are coming from usage of the `IHttpClientFactory` and are unrelated to Functions. If you want to filter or remove those logs you'll need to follow their guidance. I found this, for example: https://github.com/aspnet/HttpClientFactory/issues/196#issuecomment-432755765

There's not much we can (or will) do to filter logs coming from other sources. You should have full control over these in your `HostBuilder`.

I was able to reproduce this by calling `AddHttpClient()` and then using an `IHttpClientFactory` from within my Function to make a simple http call. I also verified in a Console app that the logs are unrelated to anything that Functions is doing.

From the looks of it, anything that uses an `IHttpClientFactory` will generate those logs.

**Comment by brettsam** [comment]
@LenaVinogradov -- As I think through this and some of your other questions, I'm realizing there may be a disconnect here between how things work when you add the Application Insights package to the dotnet-isolated worker.

Previously, with in-proc and without the new Application Insights packages, all logs to Application Insights go through the host. All filtering is controlled (ultimately) with host.json.

Now, with this package, we are putting full control of logging to Application Insights from the worker into the worker itself. Logs no longer flow through the host to Application Insights. In other words the flow goes from this:

`worker -> host -> application insights`
to
`worker -> application insights`

As such, host.json will not affect these logs. Those settings are for the *host*.

You need to apply logging filters to the worker code itself as if it's "just a .NET console application" (which it is). Documentation on Application Insights and general .NET logging are what you need to look at. We're trying to give *more* control over logging to the worker, not less. But there has been confusion around this, and I want to make that clear.

I've put together a full sample showing what I mean here with a reduced version of your example above: https://github.com/brettsam/dotnet-isolated-worker-samples/tree/main/ApplicationInsightsFiltering

Please let me know if there's something else here that needs more explaining and I will do it -- this will be helpful for others as well. 

This move to directly interact with Application Insights (and give you direct control over everything) is different than the in-proc setup and can be confusing (especially with the host.json vs worker settings). We're trying best to figure out how to document and navigate this change, but ultimately we feel it gives the developer more control.

**Comment by LenaVinogradov** [comment]
@brettsam  thank you for the example. I am trying to adopt it. Our projects targets .Net6. Your example is for .Net7. 
This call is not resolved:
services.ConfigureFunctionsApplicationInsights();
End of support for .NET7 is closer than for .NET6 (https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?cid=getdotnetsdk)
Is there any recommendation for .NET6 projects or I have to upgrade? 
Thanks!

**Comment by brettsam** [comment]
> BTW, seems like Preview_5 of the package doesn't work with .NET6 at all.

That package is built against NetStandard2.0 so using .net 6 or 7 shouldn't make any difference.

If you're having problems with the version, could you open another issue with exactly what you're seeing? For example, I changed the project file to

```
    <TargetFramework>net6.0</TargetFramework>
```

and re-ran it. Everything seemed to work as expected.

**Comment by LenaVinogradov** [comment]
@brettsam reporting back. All checks out. The example works wonderful. Thank you very much!
(yes, I was able to figure out my issue with .NET 6 , thanks!)
