### ISSUE TITLE
There is no Functions runtime available that matches the version specified in the project.

### ISSUE THREAD

**Issue by HariKrishna598** [Azure/azure-functions-dotnet-worker#1045]
Regarding the closed issue https://github.com/Azure/azure-functions-dotnet-worker/issues/989#issue-1331152766

Note: I didn't get Re-open the issue option so posting as the new issue here.

Using the code sample of .NET 4.8 Framework Azure Functions Project given in this [GitHub Repo](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/NetFxWorker), getting the same error like:

![2022-09-16 21_29_59-KrishNet48FunctionApp - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/88704316/190850828-e0430869-132f-4647-bc2e-7809279af799.png)

Tools I used:
1. VS 2022 Version 17.3.4, 17.4 VS 2022 Build Tools
2. Azure Functions Core Tools V4, .NET 4.8 SDK, 4.8.1 Versions & Runtime
3. Azure Storage Emulator and Azurite both installed.

As said [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/989#issuecomment-1213474260), it needs the VS 2022 17.4 or above for working with dotnet-isolated projects targeting netfx.

**Comment by kshyju** [comment]
Are you using the [**preview** ](https://visualstudio.microsoft.com/vs/preview/)version of VS 2022?

**Comment by HariKrishna598** [comment]
![VSData](https://user-images.githubusercontent.com/88704316/190894798-5a33b2bd-c23d-4667-ba27-b3c5af373bf9.png)


> Are you using the [**preview** ](https://visualstudio.microsoft.com/vs/preview/)version of VS 2022?

**Comment by HariKrishna598** [comment]
![VSData](https://user-images.githubusercontent.com/88704316/190894855-47367023-8512-4e6a-99e3-fbf4c6568fd3.png)


> Are you using the [**preview** ](https://visualstudio.microsoft.com/vs/preview/)version of VS 2022?

**Comment by kshyju** [comment]
That does not look like the [preview ](https://visualstudio.microsoft.com/vs/preview/)version of VS2022. With preview version, you should see something like below when you open the About dialog.

![image](https://user-images.githubusercontent.com/144469/190916069-7212d773-623c-417c-9ee6-28894c02dd82.png)

Please download and install the preview version from here: https://visualstudio.microsoft.com/vs/preview/

**Comment by HariKrishna598** [comment]
![Vs2022174previewerrror](https://user-images.githubusercontent.com/88704316/190953103-c1330544-a944-49c0-8b5f-3bda39156b39.png)

I have tried with the 17.4 2022 Preview version also but getting the same error


> That does not look like the [preview ](https://visualstudio.microsoft.com/vs/preview/)version of VS2022. With preview version, you should see something like below when you open the About dialog.
> 
> ![image](https://user-images.githubusercontent.com/144469/190916069-7212d773-623c-417c-9ee6-28894c02dd82.png)
> 
> Please download and install the preview version from here: https://visualstudio.microsoft.com/vs/preview/

**Comment by cloudmelon** [comment]
What is your .csproj ? did you target your version to .netframework v4 ? ( .net framework isolated template ) ?

**Comment by HariKrishna598** [comment]
Preview package references not worked but the latest worked:

```csharp
Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
```

**Comment by fabiocav** [comment]
@HariKrishna598 that your latest version references are correct. Closing this as answered, but please let us know if you have any additional questions.

Thanks!
