### ISSUE TITLE
Error indexing when use Azure Blob storage input binding

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-functions-dotnet-worker#1046]
My function is

```
[FunctionName("DownloadFIle")]
public async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "files/devices/{deviceNumber}/{fileType}/{fileName}")] HttpRequest request,
    [BlobInput("dev-blobs/{deviceNumber}/{fileType}/{fileName}")] CloudBlockBlob blob,
    string deviceNumber,
    string fileType,
    string fileName)
{
    return new FileStreamResult(await blob.OpenReadAsync(), "application/octet-stream");
}
```
it uses
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="5.0.0" />
```
Error

> [2022-09-17T21:08:22.214Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'DownloadFIle'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'blob' to type CloudBlockBlob. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2022-09-17T21:08:22.256Z] Error indexing method 'DownloadFIle'
[2022-09-17T21:08:22.259Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'DownloadFIle'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'blob' to type CloudBlockBlob. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2022-09-17T21:08:22.260Z] Function 'DownloadFIle' failed indexing and will be disabled.
[2022-09-17T21:08:22.311Z] The 'DownloadFIle' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'DownloadFIle'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'blob' to type CloudBlockBlob. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

[The docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-input?tabs=isolated-process%2Cextensionv5&pivots=programming-language-csharp#usage) says:
> For most blobs, use a Stream or CloudBlockBlob type

I tried `Stream ` - the same result

Before it works as follow - https://stackoverflow.com/a/64391370/4275342

**Comment by kshyju** [comment]
Are you mixing in-proc and [isolated model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide)? The function code you shared looks like it is an in-proc function.  But the package you mentioned (`Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs`) is a package needed for out-of-process/isolated function apps.

For issues with in-proc function apps, please open an issue in https://github.com/Azure/azure-functions-host/issues repo. This repo is for out-of-process/isolated function apps.

**Comment by Marusyk** [comment]
This is the isolated function https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-input?tabs=isolated-process%2Cextensionv5&pivots=programming-language-csharp#usage

**Comment by kshyju** [comment]
> This is the isolated function. 

You are using `FunctionName` attribute which is for in-proc functions. Isolated functions use `Function` attribute.  Also, `HttpRequest` type cannot be used in isolated as a parameter type, instead [HttpRequestData ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata?view=azure-dotnet)type needs to be used to bind to the incoming http request.

I suggest you refer [this sample function](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/FunctionApp/HttpTriggerWithBlobInput/HttpTriggerWithBlobInput.cs) in the repo, which uses a blob input binding for an http trigger function in isolated model.

**Comment by Marusyk** [comment]
Oh, I see, thanks. Could you suggest what should I use instead of `new FileStreamResult(await blob.OpenReadAsync(), "application/octet-stream")`?

**Comment by jviau** [comment]
@Marusyk did this line `response.Body = blob;` you have comment out not work?  Make sure to also remove this line `response.WriteString("Welcome to Azure Functions!");`.

**Comment by Marusyk** [comment]
What about filename and contenttype that was done by `FileStreamResult` 
Only this way?  😕
```
response.Headers.Add("Content-Type", blobProperties.Value.ContentType);
response.Headers.Add("Content-Disposition", $"attachment; filename=curl.yml");
```
`byte[]` - will load all content to the memory 😕
Ok, could you suggest some timelines from your roadmap? Is it public?

**Comment by jviau** [comment]
There isn't a specific issue for this feature, rather it is part of the epic to bring in-process features over: #1008. No specific timeline for this exact binding, but we are actively working on it.

Unfortunately, loading into memory is something we cannot avoid. Even with the stream binding, the response has to go over gRPC back to the host, which will involve reading the stream into memory. This is something we are evaluating, but nothing to share yet on it.

As for the `FileStreamResult` question: yes - you will need to apply the headers yourself. We do not support MVC responses in v4 (_maybe_ in the future).

**Comment by Marusyk** [comment]
Ok, thanks for info and support. I'm going to close the issue for now.
