### ISSUE TITLE
.NET Framework isolated option missing in VS2022 17.4.0 Preview 2

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1047]
When trying to create a new azure functions project, I do not see the ".NET Framework isolated" option in the "Functions worker" dropdown, as shown in this [blog post](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/building-net-serverless-applications-with-isolated-model-in/ba-p/3598425).

![image](https://user-images.githubusercontent.com/144469/191080168-983f74d6-2153-462d-9928-962a6884ae7d.png)

I am using VS 2022 preview (17.4.0, Preview 2.0)

![image](https://user-images.githubusercontent.com/144469/191080389-52efac93-cfff-4514-90ac-7972b6e6ba51.png)

Tools->Options->Azure functions tab tells me the templates I have are up to date.
![image](https://user-images.githubusercontent.com/144469/191080597-d7e20329-cd04-4570-bccb-92d0a139d590.png)

I also ran the "Repair" option from VS installer on my VS preview instance, restarted machine, but did not fix the issue.

4.8 SDK and Targeting packs are installed.
![image](https://user-images.githubusercontent.com/144469/191081392-356b0299-ff92-454e-b419-9ea6a15ac191.png)

**Comment by fabiocav** [comment]
This is a known issue with Preview 2 and we expect the issue to be fixed in Preview 3

**Comment by fabiocav** [comment]
Closing this as there isn't anything actionable tracked.

**Comment by anujgeek** [comment]
Hello, is there a workaround? I installed preview 2, can I go back to preview 1?

**Comment by kshyju** [comment]
@anujgeek You can use the [azure functions core tools ](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools)to create a functions project targeting net48 TFM. Once created using CLI, you can open the .csproj file in [VS 2022 17.4.0 Preview](https://visualstudio.microsoft.com/vs/preview/) 2.x (which is the latest preview version as of toady) and continue working on the function app.

VS2022 17.4 preview 3 will have the fix for creating the project using VS create -> new azure function app dialog. It should be released in the next few weeks. 

Here is the command I used to created a new project targeting net48 TFM. I had version 4.0.4736 of core tools installed.

`func init --worker-runtime dotnet-isolated --target-framework net48`
