### ISSUE TITLE
[AOT] Replace usage of IConfiguration.Bind

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1055]
`IConfiguration.Bind` is not trimmer friendly.

See https://github.com/dotnet/runtime/discussions/59230

We use this method to bind to[ GrpcWorkerStartupOptions](https://github.com/Azure/azure-functions-dotnet-worker/blob/1da3c27d3b24e648a20356fb3180abfcdc7f6cff/src/DotNetWorker.Grpc/GrpcStartupOptions.cs#L7) type, which is to represent the data from the command line arguments sent from host

https://github.com/Azure/azure-functions-dotnet-worker/blob/1da3c27d3b24e648a20356fb3180abfcdc7f6cff/src/DotNetWorker.Grpc/GrpcServiceCollectionExtensions.cs#L92-L96

**Comment by jviau** [comment]
Also relevant: https://github.com/dotnet/runtime/issues/44493

**Comment by kshyju** [comment]
This issue is fixed with #1897
