### ISSUE TITLE
Functions metadata for blob trigger is not matching with in-proc

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1059]
For a blob trigger in a V4 in-proc app, we generate the binding JSON with `path` property. When a blob trigger is created in isolated model, the binding property name is `blobPath` (See sample below).

As per @chiangvincent, this causes scale control to behave incorrectly.

> ICM: 336192878
Vincent Chiang (vchiang) edited at 2022-09-20 13:01:05 PDT 
This appears to be a bug within the functions host SDK. Since the scale controller expects a property called "path," and not "blobPath," the scale controller will not able to create a binding to monitor the function, and will not be able to scale as a result.

#### In-proc function app

    [FunctionName("Function1")]
    public void Run([BlobTrigger("samples-workitems/{name}", Connection = "MyStorageConnStr")]Stream myBlob, 
                               string name, ILogger log)
    {
        log.LogInformation($"C# Blob trigger inproc function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
    }

Relevant packages
```
  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
```

Generated function.json
````
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-4.1.3",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "blobTrigger",
      "connection": "MyStorageConnStr",
      "path": "samples-workitems/{name}",
      "source": "logsAndContainerScan",
      "name": "myBlob"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/FunctionApp1.dll",
  "entryPoint": "FunctionApp1.Function1.Run"
}
````
#### Isolated 
````
[Function("Function1")]
public void Run([BlobTrigger("samples-workitems/{name}", Connection = "MyStorageConnStr")] string myBlob, string name)
{
    _logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {myBlob}");
}
````
Relevant packages
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.0.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
```

Functions.metadata

````
  {
    "name": "Function1",
    "scriptFile": "BlobTriggerTest.dll",
    "entryPoint": "BlobTriggerTest.Function1.Run",
    "language": "dotnet-isolated",
    "properties": {
      "IsCodeless": false
    },
    "bindings": [
      {
        "name": "myBlob",
        "type": "blobTrigger",
        "direction": "In",
        "dataType": "String",
        "blobPath": "samples-workitems/{name}",
        "connection": "MyStorageConnStr"
      }
    ]
  }
````

**Comment by fabiocav** [comment]
The issue comes from the fact that the existing serialization logic simply uses the property name to create the metadata, deriving the name from here: https://github.com/Azure/azure-functions-dotnet-worker/blob/1f7a321d88b2f66f792f3889ba7683d83ff45b92/extensions/Worker.Extensions.Storage.Blobs/src/BlobTriggerAttribute.cs#L31


With the in-proc model, the tooling will apply transformations to some of the extensions:
https://github.com/Azure/azure-functions-vs-build-sdk/blob/main/src/Microsoft.NET.Sdk.Functions.Generator/AttributeExtensions.cs#L198-L203


We need to update our metadata generation logic to look for an extension attribute that takes precedence over the property name when creating the metadata.

**Comment by fabiocav** [comment]
We should also review the other extensions we special case to make sure we don't have other issues.
