### ISSUE TITLE
Investigate dotnet language worker integration tests failures in Functions V3 for 9/21/22

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-dotnet-worker#1060]
Investigate DotNet language worker tests failures in Functions V3 for 9/21/22

Here is the link to the pipeline executions with the test failures:
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=96326&view=ms.vss-test-web.build-test-results-tab

![image](https://user-images.githubusercontent.com/12720858/191633615-940333d4-1074-4b19-a191-4dfc657a328f.png)

**Comment by satvu** [comment]
@Francisco-Gamino and I looked into this - the issue is that we have only one E2E test app that runs only one version of Functions. The v3 pipeline was attempting to test a v4 app.

**Comment by satvu** [comment]
Discussed in design meeting earlier this month - will start implementing it this sprint.
