### ISSUE TITLE
.Net framework 4.8 general availability?

### ISSUE THREAD

**Issue by anujgeek** [Azure/azure-functions-dotnet-worker#1061]
Can you please let us know an estimated timeline on when to expect general availability for .net framework 4.8 support?
https://azure.microsoft.com/en-us/updates/public-preview-azure-functions-net-framework-support-in-the-isolated-worker-model/

**Comment by cloudmelon** [comment]
hi @anujgeek We just announced it today : https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-general-availability-for-azure-functions-v4-net/ba-p/3637605

**Comment by kshyju** [comment]
Closing as answered. Please let us know if you have any questions.
