### ISSUE TITLE
Rename FunctionExecutionContext -> FunctionContext

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#107]
This context is meant to be similar to `HttpContext`. And since `ExecutionContext` already has another meaning, the current name seems confusing. We think that `FunctionContext` makes the most sense.

**Comment by SeanFeldman** [comment]
And there's also [`FunctionInvocation`](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker/Context/FunctionInvocation.cs), which also seems to be related to the execution.
