### ISSUE TITLE
Call out contributions for Code samples - v1 .NET Framework 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1076]
Fabio helped us to create the repo, and you can click on the following link to join the vteam : 
https://repos.opensource.microsoft.com/orgs/Azure/teams/azure-functions-vs-migration

I am putting together some scenarios and will create a GitHub item,  we’ll assign that to the folks on the team to work on some .NET Framework v1 samples ( initiate state )

**Key Migration scenarios**  

o	.NET Framework v1 to .NET 6 /7 
o	.NET Framework v1 to .NET Framework v4 

**List of triggers & bindings** 👍 

Triggers
- [x] #1165
- [x] #1164
- [x] #1167
- [x] #1166

Binding : 
- [x] #1168
- [x] #1169

Feel free to chime in if you have any existing code samples available to contribute ( no need to limit your creativity in this list )

Folder structure proposed by the team ( we could adjust accordingly ): 
Src\
              V1NetFxToV4Net6\
              V1NetFxToV4Net7\
              V1NetFxToV4NetFx\

.NET Isolated samples ( final state ) are here : [https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples]

**Comment by fabiocav** [comment]
Let's use this issue to track the discussion to define the samples and create issues to track each one of them so we can have them assigned to the team.

**Comment by liliankasem** [comment]
@cloudmelon is this epic complete? Can we close?

**Comment by cloudmelon** [comment]
We should close this since we had all samples lined up already !
