### ISSUE TITLE
[Epic] Support SDK-type bindings for out-of-proc workers

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1081]
Epic to track the work to support SDK-type bindings for out-of-proc workers, focusing on dotnet isolated implementation.

Work for this feature can be found under this tag: 

- https://github.com/Azure/azure-functions-dotnet-worker/labels/feature%3A%20SDK%20bindings 

## General

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1018
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1080
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1036
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1194
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1266
- https://github.com/Azure/azure-functions-host/issues/9021
- https://github.com/Azure/azure-functions-host/issues/9022
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1325

#### Bypass deferred binding

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1395
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1418
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1495
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1541

#### Analyzers

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1277
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1144
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1587
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1276

#### Bugs

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1100
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1204
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1362

#### Enhancements 

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1333 
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1674
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1675

#### Blob Storage

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1035
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1156
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1093
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1278
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1324 
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1337
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1329
- https://github.com/Azure/azure-functions-templates/issues/1375

#### Cosmos DB

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1034
- https://github.com/Azure/azure-webjobs-sdk-extensions/issues/800
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1117
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1217
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1259
- https://github.com/Azure/azure-functions-host/issues/9026
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1279
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1265
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1371
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1420
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1410
- https://github.com/Azure/azure-functions-templates/issues/1378

#### Queue

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1422
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1445
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1444
- https://github.com/Azure/azure-functions-templates/issues/1376

#### Tables

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1473 
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1474
- https://github.com/Azure/azure-functions-templates/issues/1377

#### Service Bus

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1536
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1535
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1538
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1561 
- https://github.com/Azure/azure-functions-templates/issues/1379

#### EventGrid

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1564
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1565
- https://github.com/Azure/azure-functions-templates/issues/1380

#### EventHub

- [x] Update and release WebJobs EventHub extension with ParameterBindingData changes
- [x] Implement EventHub worker extension converter
- https://github.com/Azure/azure-functions-templates/issues/1381

**Comment by liliankasem** [comment]
Capturing open PRs here:

- Proto: https://github.com/Azure/azure-functions-language-worker-protobuf/pull/83
- Host: https://github.com/Azure/azure-functions-host/pull/8815
- Blob Extension: https://github.com/Azure/azure-sdk-for-net/pull/31757
- Dotnet Worker: https://github.com/Azure/azure-functions-dotnet-worker/pull/1107
- Dotnet Worker Blob Extension: https://github.com/Azure/azure-functions-dotnet-worker/pull/1108

**Comment by liliankasem** [comment]
Service bus support for ParameterBindingData included in this PR: https://github.com/Azure/azure-sdk-for-net/pull/33682

**Comment by mattchenderson** [comment]
Pubic preview announcement for reference: https://azure.microsoft.com/updates/public-preview-sdk-type-bindings/

**Comment by SeanFeldman** [comment]
I just wanted to high-five the team on the great work done here 👏

**Comment by mattchenderson** [comment]
Closing as we are using milestones for epics now, and most of this work was GA'd already. The remaining items are assigned to https://github.com/Azure/azure-functions-dotnet-worker/milestone/62, which can be used for ongoing tracking.
