### ISSUE TITLE
DotNetWorker function does not consider Diagnostic-Id from servicebus message for end to end tracing in appinsight

### ISSUE THREAD

**Issue by arunbgolabhavinew** [Azure/azure-functions-dotnet-worker#1089]
Hi
We are using dotnet6 isolated function app. Our setup is like this
We have two function apps which are  listening to two different topics subscriptions. (Topic1-Subscription-Function1 and Topic2-Subscription-Function2).
Function 1 receives message and sends another message to Topic2 which triggers Function 2.

In DotNet3.1 (V3)function apps all these processing logs are correlated with one Operation Id. We could search by this id in application insight and get logs from both functions.
Now in dotnet6 isolated functions, logs from each function are in different Operation Id. 
Is it the expected behavior? 
![FunctionEndToEndTracing](https://user-images.githubusercontent.com/48122396/193255768-97607d46-59e0-45cb-92af-3019d2c4e47f.png)

Looks like the **diagnostic-id** which was used to link between calls is missing in dotnet6 Isolated. Also when Function 1  outputs message  to Topic2, message does not contain diagnostic-id message property.
And if we set that property ourself, then also it is not considered. We see the application insight that it is from upstream. This diagnostic id is not propagated as operationId for function execution

Is this not valid anymore for dotnet6 isolated function apps?
https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2

I have included the Microsoft.Azure.Functions.Worker.ApplicationInsights preview version 2
Program.cs

```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(app=>
    app.AddApplicationInsights().AddApplicationInsightsLogger()
    )
    .Build();

host.Run();

```
ProjectFile
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.6.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.7.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

**Comment by brettsam** [comment]
We're looking into this now. Functions does nothing "special" with these ids (i.e. there's no code in the WebJobs or Functions codebase to handle diagnostic-id). It's all done automatically with the ServiceBus and ApplicationInsights tracing capabilities, so we're trying to figure out what pieces of data aren't being handled correctly.

Do you have a small sample of the Function1 code that we can use to repro?
If not, how do you have Function1 sending a message to Function2? Are you using an output binding, or using the SB client directly?

**Comment by arunbgolabhavinew** [comment]
Hi @brettsam , 
 I have tried with both output binding and sbclient. Its same behaviour. It does not add diagnostic-id property.

Here are the sample functions which uses output binding.

Function1
`[Function("SendIsolatedFunction")]
        [ServiceBusOutput("topicB",ServiceBusEntityType.Topic, Connection = "ConnectionString")]
        public async Task<string> Run([ServiceBusTrigger("topicA", "subA", Connection = "ConnectionString")] string mySbMsg, FunctionContext context)
        {
            _logger.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
           
            var message = $"Output message created at {DateTime.Now}";
            return message;
        }
`
Function 2
` [Function("ReceiveFunctionIsolated")]
        public async Task Run([ServiceBusTrigger("topicB", "subA", Connection = "ConnectionString")] string mySbMsg)
        {
            _logger.LogInformation($"Received message: {mySbMsg}");
        }`

Thanks

**Comment by brettsam** [comment]
Everything I've tested does auto-inject Diagnostic-Id from both the worker side and as an output binding -- can you tell me how you're confirming that it's not doing this for you?

I was syncing with @lmolkova and @JoshLove-msft about this. It appears that this is how things work now that you're using the latest Service Bus SDK. You'll see multiple operations all pulled together in the end-to-end transaction UI in the portal.

I am seeing that when using an output binding things don't seem to show up on the End-to-end transaction in App Insights like I'd expect. I'm still trying to figure that out.

But none of this is happening in the worker -- it all takes place in the host with the latest SB extensions (which use the latest SB SDK). See issues like this that tripped up others: https://github.com/Azure/azure-sdk-for-net/issues/27954

**Comment by lmolkova** [comment]
@arunbgolabhavinew thank you for reporting this! As @brettsam mentioned, since you see all three operations on the portal in one view, then the context is propagated. If you expand service bus telemetry, you'd see the `_MS.links` custom dimension - it describes additional relationships between telemetry items. Links are an OpenTelemetry feature that allows connecting unrelated traces.
It's essential to describe batching cases when multiple messages with different contexts are received. But it seems you receive just one message.

We understand it's not ideal and makes it harder to query telemetry. Also, it's a degradation from the previous ServiceBus SDK experience.  I created https://github.com/Azure/azure-sdk-for-net/issues/31771 to track it in Azure SDK repo.

**Comment by arunbgolabhavinew** [comment]
> Everything I've tested does auto-inject Diagnostic-Id from both the worker side and as an output binding -- can you tell me how you're confirming that it's not doing this for you?

@brettsam Sorry. It is setting for me as well now. We have another project where we have not included the **preview** Microsoft.Azure.Functions.Worker.ApplicationInsights and added this code.   `.AddApplicationInsights().AddApplicationInsightsLogger()`.
We thought of adding it when it is made available officially. I got confused for the messages generated by this application. As our main issue is about having single operationId for all executions.
Thanks for clarifying and pointing to the correct people.


> We understand it's not ideal and makes it harder to query telemetry. Also, it's a degradation from the previous ServiceBus SDK experience. I created [Azure/azure-sdk-for-net#31771](https://github.com/Azure/azure-sdk-for-net/issues/31771) to track it in Azure SDK repo.

@lmolkova Yes it would be ideal for us to get the logs generated by both function asociate to same operationId.
We have case where we generate multiple messages from same function app. We need them to be on same operation-id so that we query and get entire flow.
The following exampl
![image](https://user-images.githubusercontent.com/48122396/195556941-962caa90-d2a1-49a0-b39b-445d0c55d3e3.png)

Thanks for creating [https://github.com/Azure/azure-sdk-for-net/issues/31771](url)
We will track this feature.

**Comment by brettsam** [comment]
Thanks for filing this, @arunbgolabhavinew. I learned a lot investigating :-)

Since there's nothing for the worker to do here, I'm going to close it out and you can track the other issue.
