### ISSUE TITLE
DX: MSBuild error "GenerateFunctionMetadata" with Microsoft.NET.Sdk.Functions referenced

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#109]
The readme does not state to remove this, so the MSBuild script could generate a better error when users are attempting to upgrade their projects

**Comment by kshyju** [comment]
We[ recently made changes](https://github.com/Azure/azure-functions-dotnet-worker/pull/841) to throw a more readable build error when the inproc SDK is referenced in an isolated project. Let us know if you still have questions.
