### ISSUE TITLE
Logging calls does not appear in console when running locally in 1.9.0 using ApplicationInsights preview packages

### ISSUE THREAD

**Issue by elsand** [Azure/azure-functions-dotnet-worker#1090]
How to reproduce:
1.  Create a function app using the template for .NET6 Isolated in VS2022
2. Bump `Microsoft.Azure.Functions.Worker` to 1.9.0 and add a reference to `Microsoft.Azure.Functions.Worker.ApplicationInsights` (applies to any 1.0.0-preview version up to 3)
3. Add Application Insights logging in Program.cs:
```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()
            .AddApplicationInsightsLogger();
    })
    .Build();

host.Run();
```
4. Run the function app. The template includes a HTTP trigger function "Function1" (unchanged from template):
```
using System.Collections.Generic;
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace consolelogger
{
    public class Function1
    {
        private readonly ILogger _logger;

        public Function1(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");

            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Welcome to Azure Functions!");

            return response;
        }
    }
}
```
5. Access the HTTP endpoint. Observe that there's no trace of the LogInformation-call in the console:

![image](https://user-images.githubusercontent.com/723303/193268779-b079e7cb-3867-4244-9a60-56c42dd062ec.png)

Downgrading `Microsoft.Azure.Functions.Worker` to 1.8.0 and `Microsoft.Azure.Functions.Worker.ApplicationInsights` to 1.0.0-preview2 works:

![image](https://user-images.githubusercontent.com/723303/193269846-169a54d2-af02-48f2-b22f-b63aee316261.png)

Using `Microsoft.Azure.Functions.Worker` version 1.8.0 and `Microsoft.Azure.Functions.Worker.ApplicationInsights` to 1.0.0-preview3 causes the HTTP request to hang infinitely at `Executing 'Functions.Function1' ...`. (This may be a separate issue.)

Workaround: explicitly adding console logging via the `ConfigureLogging` extension method:
```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var host = new HostBuilder()
    .ConfigureLogging(loggingBuilder =>
    {
        loggingBuilder.AddConsole();
    })
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()
            .AddApplicationInsightsLogger();
    })
    .Build();

host.Run();
```

![image](https://user-images.githubusercontent.com/723303/193270854-0859549a-7a44-4f32-ae43-e6cbe1ad7624.png)

**Comment by olandese** [comment]
I'm having exactly the same problem, adding loggingBuilder.AddConsole() solves it, but I think this is not how it should work

**Comment by MO2k4** [comment]
@elsand is the workaround with pre2? With pre3 it does not work at my end ;-(

**Comment by elsand** [comment]
@MO2k4 It works for me using the latest preview packages at the time of writing (Worker 1.11.0-preview2, Sdk 1.8.0-preview2, Insights 1.0.0-preview). The output is not very readable though, but I suppose one could add a custom formatter. 

But I'm expecting this is considered a bug, these workarounds shouldn't really be necessary.

**Comment by jviau** [comment]
``` CSharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()
            .AddApplicationInsightsLogger();
    })
    .Build();

host.Run();
```

This is by design. Console logger was never added in the code above. I think what you are looking for is `Host.CreateDefaultBuilder().ConfigureFunctionsWorkerDefaults(...)`, **this** call will add ConsoleLogger by default.
