### ISSUE TITLE
Investigate Managed Identity flow for sdk type bindings

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#1093]
This doc - [link](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#common-properties-for-identity-based-connections) explains multiple ways that a Managed Identity can be used with the Function App. Need to investigate if same approaches can be used with sdk-type-bindings changes or if we need any custom handling.

- [x] AppSetting [AzureWebJobsStorage__accountName](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#use-managed-identity-for-azurewebjobsstorage-preview)
- [x] AppSetting [AzureWebJobsStorage__blobServiceUri](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#connecting-to-host-storage-with-an-identity-preview)
- [x] Using TenantId, ClientId, Client Secret - [for local development with user assigned identity](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#local-development-with-identity-based-connections)
- [x] Using TokenCredential and ClientId - only for [portal app](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#common-properties-for-identity-based-connections)

**Comment by fabiocav** [comment]
Adding this to sprint 135 as a stretch goal.
