### ISSUE TITLE
Question: security patching in isolated functions app

### ISSUE THREAD

**Issue by TheCakeMonster** [Azure/azure-functions-dotnet-worker#1094]
Can someone please confirm whether an isolated/out of process .NET 6/7 app would need to be published as self-contained, and therefore is at risk of compromise if it is not redeployed after each patch Tuesday (assuming a security issue is found in the runtime that month?)

It seems likely to me that an isolated/out of process app is running on a version of the runtime that is shipped with the app. That puts the onus on the customer to apply security patches, rather than on the platform. That seems like a retrograde step from a security perspective, for a managed platform.

**Comment by brettsam** [comment]
dotnet-isolated apps do not need to be published as self-contained. 

However, that is an option. If you publish self-contained, then you are correct that you'd need to re-publish yourself with updated packages after fixes are released.

**Comment by TheCakeMonster** [comment]
Thanks for the reply. That's great news that they do not need to be self-contained. I would much prefer to use framework-dependent to get automated patching.
