### ISSUE TITLE
Drop net5.0 support

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1095]
May 10, 2022 is the official end of support date from the .net team.

https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/

We are currently using a bunch of deprecated 5X packages. We can upgrade these to 6X version. 

This closed PR has details:  [Replace deprecated 5.x packages to 6.x](https://github.com/Azure/azure-functions-dotnet-worker/pull/1044)

**Comment by fabiocav** [comment]
This will be part of the broader TFM review for the next major version.

**Comment by kshyju** [comment]
see https://github.com/Azure/azure-functions-dotnet-worker/pull/2666/files#r1723755823

**Comment by fabiocav** [comment]
Closed in favor of #2669
