### ISSUE TITLE
How to get message metadata in isolated Azure functions v4 - Queue Trigger

### ISSUE THREAD

**Issue by gautamsamal** [Azure/azure-functions-dotnet-worker#1105]
I am following on a possible upgrade of azure function runtime from v3 to v4 with dotnet. While doing so, I am testing out the isolated option for the project. However I am unable to get message metadata such as DequeueCount, MessageId etc in the queue trigger.

Previously with in-process option, I used to bind `CloudQueueMessage` but that doesn't seem to work in the isolated mode. Doing so, throws and error - 
```
Cannot convert input parameter 'myQueueItem' to type 'Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage' from type 'System.String'
```

This was my isolated queue function binding
```
[Function("TestApp")]
public void Run([QueueTrigger("sample-queue", Connection = "")] CloudQueueMessage myQueueItem, FunctionContext context)
```

After looking for a while, I think [here][1] it says that, in isolated process we can only bind string. Simple JSON - Object also works.

[![enter image description here][2]][2]

Is there any way to get these message [metadata][3] (members of the `CloudQueueMessage`) in the isolated azure function?
Thanks.

  [1]: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=isolated-process%2Cextensionv2&pivots=programming-language-csharp#usage
  [2]: https://i.stack.imgur.com/Iku29.png
  [3]: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=isolated-process%2Cextensionv2&pivots=programming-language-csharp#message-metadata

**Comment by jviau** [comment]
This feature (rich binding) is not yet available in v4 isolated dotnet. We have #1008 which tracks adding support for these features.
