### ISSUE TITLE
Question: Is there an alternative for Ibinder in NET5/NET6 Isolated-process

### ISSUE THREAD

**Issue by vdboots** [Azure/azure-functions-dotnet-worker#1106]
At the moment we are still using some processes that are required to run in In-process mode because they rely on the IBinder interface. As it seems that this is not supported. Is there an alternative for this?

**Comment by fabiocav** [comment]
Not yet. 

Can you share more information about your scenario? We're actively working on binding improvements and it would be good to track additional details here.

Thanks!

**Comment by vdboots** [comment]
hi,  I would like to use Signal R binding information

```
public SignalRConnectionInfo Negotiate([HttpTrigger(AuthorizationLevel.Anonymous)] HttpRequestData req,
                                               [SignalRConnectionInfoInput(HubName = "Hub", UserId = "{query.userid}")]
                                               SignalRConnectionInfo signalRConnectionInfo)
        {
            
            _logger.LogInformation("Executing negotation.");
            return signalRConnectionInfo;
        }
```

i would like to force the user id from my own function without using any parameters like this

`            var connectionInfo = await binder.BindAsync<SignalRConnectionInfo>(new SignalRConnectionInfoAttribute
            {
                HubName = _hubName,
                UserId  = GetMyUserName(CertificateByteArray,
            });`

**Comment by liliankasem** [comment]
There won't be support for IBinder with the isolated worker. The guidance here is to use the service SDKs instead. 

@Y-Sindo recently updated the [SignalR samples ](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/SignalR/SignalRNegotiationFunctions.cs)and might be able to help answer any further questions.
