### ISSUE TITLE
HttpTrigger with Cancellation is not working 

### ISSUE THREAD

**Issue by mjallaq88** [Azure/azure-functions-dotnet-worker#1112]
I'm testing the sample code that was published on another thread [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/180#issuecomment-797492512). The sample code [here ](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/1.9.0) is to test the new feature of adding "CancellationToken" to the HttpTrigger azure function. My expectation is when I create a "Get" or "Post" request and once the request is initiated and canceled the request., the cancellation token should stop any process and execute the catch block.
The code is not working as expected. Every time I cancel the request I still see the code is running and not being terminated. 

The Sample Function project is "FunctionApp.HttpTriggerWithCancellation". 
![image](https://user-images.githubusercontent.com/44626640/195144396-a94ea0a3-e011-4a8e-a99a-cb44a8320da3.png)

**Comment by liliankasem** [comment]
@mjallaq88 how are you cancelling the function?

**Comment by mjallaq88** [comment]
I’m using postman to create and cancel the request

**Comment by liliankasem** [comment]
Unfortunately, that is not a use case we currently support; the host doesn't handle `HttpContext.RequestAborted` for isolated or in-proc at the moment.

A better example of using cancellation tokens is when processing batch messages with service bus, you can see an example of that with in-proc dotnet [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#cancellation-tokens). I can update the sample to show a supported use case of cancellation for the dotnet-isolated worker.

If this is a feature request you can open an issue in the [host repo](https://github.com/Azure/azure-functions-host/issues/new/choose)

**Comment by HMoen** [comment]
Sample update would be great. Thanks.

**Comment by liliankasem** [comment]
Updated [sample PR](https://github.com/Azure/azure-functions-dotnet-worker/issues/1112#issuecomment-1275387271) is out, should be merged soon. 

Closing issue for now as the use case described here is not supported. Feel free to open a feature request issue in the host for `HttpContext.RequestAborted` support.

**Comment by CasperWSchmidt** [comment]
I've added the feature request [here](https://github.com/Azure/azure-functions-host/issues/8903)
