### ISSUE TITLE
Identify log verbosity in StdError stream

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-dotnet-worker#1116]
Part of https://github.com/Azure/azure-functions-host/issues/8273

As part of the action item for this issue. We need to investigate if we can identify the log level of the log statements sent over to StdError stream.

**Comment by kashimiz** [comment]
This issue is dependent on the design resulting from https://github.com/Azure/azure-functions-host/issues/8273

**Comment by fabiocav** [comment]
Assigning to @soninaren to review and identify whether we still need this issue.
