### ISSUE TITLE
CosmosDB Converter: Support POCO for the input binding

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1117]
This is related to the work that is happening to enable SDK-type binding in out-of-proc workers. The CosmosDB converter and rules have been implemented, related PRs here:

- https://github.com/Azure/azure-functions-dotnet-worker/pull/1109
- https://github.com/Azure/azure-webjobs-sdk-extensions/pull/802

The remaining work that needs to be done is to support POCOs for the cosmos input binding. Currently, the CosmosDB extension returns a single "document" for the input binding, so when users bind to a list e.g. `IList<POCO>`, things are broken. However binding to a single POCO should work today. 

Aim of this story is to implement a way for both list and single POCO bindings to work. This might be a good time to look into using [cardinality](https://github.com/Azure/azure-functions-dotnet-worker/blob/314910297de34be74371077b808b3a72608c7189/sdk/Sdk/FunctionMetadataGenerator.cs#L515-L566).

> Note: we have already implemented trigger POCO support, but this only supports `IList<POCO>`

**Comment by fabiocav** [comment]
Closing this as the scenario should be covered by #1217 . Will open another issue if additional work is identified.
