### ISSUE TITLE
Remove preview suffix for Worker.Extensions.Storage.Tables package

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1118]
It's been 5 months and we haven't heard any issues about `Microsoft.Azure.Functions.Worker.Extensions.Storage.Tables` package. Are we good to remove the **_preview_** version suffix?

https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Tables/1.0.0-preview1

**Comment by jmrtnz94** [comment]
Before they do that it looks like a PackageReference needs to be updated.

![image](https://user-images.githubusercontent.com/8380813/198117968-8ef512e9-57d6-4941-8942-1e329684c2eb.png)

Update to `Microsoft.Azure.WebJobs.Extensions.Tables`.

**Comment by mattchenderson** [comment]
@brettsam let's please treat this with priority. I'll follow up with you.

**Comment by kshyju** [comment]
> Before they do that it looks like a PackageReference needs to be updated.
> 
> ![image](https://user-images.githubusercontent.com/8380813/198117968-8ef512e9-57d6-4941-8942-1e329684c2eb.png)
> 
> Update to `Microsoft.Azure.WebJobs.Extensions.Tables`.

@jmrtnz94 Could you share the steps to reproduce the error you are seeing? I was able to successfully add a reference to Microsoft.Azure.Functions.Worker.Extensions.Storage.Tables package to my .net 6 V4 function app without any build errors. Used VS 2022 17.4.0.

**Comment by kshyju** [comment]
I also verified in Rider 2022.2.3. Works fine for me.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/144469/200686736-0cf642b1-7ac1-4756-876a-e3d32785a70e.png">

@jmrtnz94  If you are still having issues, can you share a minimal repro app, so that we can take a look ? Link to a GitHub repo would be great.

**Comment by jmrtnz94** [comment]
I'm still having the same issue.

REPO: https://github.com/jmrtnz94/function-table-storage-issue
Application: https://github.com/jmrtnz94/function-table-storage-issue/tree/main/TableStorageIssueIsolated

I believe its something with the TableOutput binding attribute, cause when I remove it from my Function it builds successfully.
https://github.com/jmrtnz94/function-table-storage-issue/blob/main/TableStorageIssueIsolated/CreateTask.cs#L20

If you are unable to reproduce with my repo, please disregard my comment.

**Comment by mattchenderson** [comment]
@kshyju I can show you an active repro

**Comment by madelinegordon** [comment]
Released [https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Tables/1.0.0-preview1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Tables/1.0.0-preview1) - looking to validate before releasing the GA tomorrow!

**Comment by madelinegordon** [comment]
Have the GA version released now. https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Tables/1.0.0

**Comment by marcelgrilo** [comment]
Why this new version dont store multiple row items?

In the old version Microsoft.Azure.Functions.Worker.Extensions.Storage  4.0.4 i had a return type of MyObject[] or IEnumerable<MyObject> and the function created multiple rows in the output talbe, 

now, it returns me an error
System.Private.CoreLib: Exception while executing function: Functions.TimeTriggerTest. Microsoft.Azure.WebJobs.Extensions.Tables: '' is not a valid value for a partition key or row key.
