### ISSUE TITLE
Avoid buffer overrun on empt-valued HTTP properties by enabling "UseNullableValueDictionaryForHttp" capability

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#112]
Read more here: https://github.com/Azure/azure-functions-host/wiki/Out-of-Proc-Worker-Capabilities#usenullablevaluedictionaryforhttp

**Comment by fabiocav** [comment]
Had this working, but we need to update the types with an up-to-date proto file. Creating an issue to track.
