### ISSUE TITLE
Add support for bindings to provide information about input converters

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1121]
Add support for bindings to provide input converter information to be used. This allows binding authors(extension authors) to specify one or more converters to be used when doing input conversion for that binding entry.

Initial plans for the implementation:

As part of this change, we plan to expose a new interface `IConverterProvider`

```
/// <summary>
/// Provides information about what converters to be used.
/// </summary>
public interface IConverterProvider
{
    /// <summary>
    /// Gets an <see cref="IEnumerable{T}"/> of <see cref="Type"/> instances representing the converters to be used.
    /// </summary>
    public IList<Type> ConverterTypes { get; }
}
```
Here is an example binding which implements this interface and specifying `MyFooConverter` as the converter type to be used for this binding.

```
public class FooTriggerBinding : TriggerBindingAttribute, IConverterProvider
{
    public IList<Type> ConverterTypes => new[] { typeof(MyFooConverter) };

    // Other properties relevant to the binding.
}
```

The `ConverterTypes` property is an ordered collection. So the binding authors can define multiple converters in the order they want.

```
public IList<Type> ConverterTypes =>
    new[]
    {
        typeof(MyPrimaryConverter),
        typeof(MyBackupConverter)
    };
```

If the function parameter has an Input converter specifically defined(see sample below), that will be used and converters defined on the binding level will not be used.

```
[Function("products")]
public HttpResponseData Run(
                 [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData req,
                 [InputConverter(typeof(MyCustomConverter))] ProductViewModel productvm)
{
   ....    
}

```

**Comment by SeanFeldman** [comment]
I was just wondering, since this is something that will be released in the future, would it be possible to support C# 11 generic interfaces so that

```C#
[InputConverter(typeof(MyCustomConverter))] ProductViewModel productvm
```

would become

```C#
[InputConverter<MyCustomConverter>] ProductViewModel productvm
```

**Comment by jviau** [comment]
For completeness of the design discussion, have we considered this alternative: instead of introducing the new contract, let the binding attribute implement `IInputConverter` itself and we will test for that contract and use it if present.
