### ISSUE TITLE
Microsoft.Azure.Functions.Worker.ApplicationInsights missing `operation name` for child activities

### ISSUE THREAD

**Issue by wkoeter** [Azure/azure-functions-dotnet-worker#1124]
When starting a new activity within the activity provided by the `FunctionActivitySource`, the activity does land in application insights, but child activities lose the `operation_Name` property (other relevant properties related to `trace context` are correctly filled in).

packages used:
```xml
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.11.0-preview2" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview3" />
```

_Edit_: Maybe it is not in the scope of this package to manage it? Should we create our own listener that does a start/stop operation on a `TelemetryClient` with the `Name` field in the `Tags` filled in ourselves?

**Comment by jviau** [comment]
I think there may be some work for us to do here. If I am remembering correctly, `operation_Name` is typically the `name` of the most immediate parent `RequestTelemetry`, and child `DependencyTelemetry` pick that up. But I think it requires us to use explicit AppInsights APIs to start the outer operation, and not just `AcitivtySource`. We will take a look at this. In the meantime, you may be able to work-around this yourself via listening to the activity start/stop events and calling the appropriate AppInsights API to set this context/name.

**Comment by wkoeter** [comment]
Alright, will do that. Thanks.

**Comment by jviau** [comment]
@wkoeter, can you try out the preview app insights package? https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview4#versions-body-tab

**Comment by jviau** [comment]
I looked into this, `operation_Name` will still be `null`. However, you can add your own `ITelemetryInitializer` and set `telemetry.Context.Operation.Name` with a value of your choosing, which will populate `operation_Name`.

We will consider setting this value at a later date when we revisit our telemetry schema.

**Comment by wkoeter** [comment]
Ok thanks for checking. We are adding it ourselves and will keep doing so until no longer needed.

**Comment by jviau** [comment]
Closing this for now as we will evaluate adding operation_Name at a later date.

**Comment by andrw** [comment]
@jviau is there something we can track? Closing this feels like it's put in an icebox, and this seems like a really fundamental platform value.

**Comment by the-rule** [comment]
We are also experiencing the same issue which is crucial in my opinion and is more like a bug since the default functions logging supports custom log entries connected to operation_Name. @jviau could we reopen or link an issue?

**Comment by jviau** [comment]
We will capture this work as part of OTel efforts https://github.com/Azure/azure-functions-host/issues/9273. OTel will support (and improve upon) Application Insights through the Azure Monitor exporter.

**Comment by carl-underwood** [comment]
Am I right in thinking this is still not supported by default? I see https://github.com/Azure/azure-functions-host/issues/9273 is closed and I'm using the following package versions:
```xml
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" />
```
