### ISSUE TITLE
Application Insights distributed logging and Storage queues

### ISSUE THREAD

**Issue by wkoeter** [Azure/azure-functions-dotnet-worker#1126]
Question: 

I'm wondering if W3C distributed logging is going to be enabled using Azure Storage Queues.
My HTTP function receives the `traceparent` header just fine and uses this in the `FunctionContext.TraceContext` property. These values are applied to A.I. Requests and Traces perfectly.

That HTTP function sends a queue message to a different function (using an `Azure.Storage.Queues.QueueClient`). As stated, the HTTP function contains a valid `TraceContext`. On the receiving side (Queue triggered function) however, a new `operationId` is created and nothing can be correlated anymore.

I'm now using a workaround where I extract the `traceparent` from a custom property in the message body using a custom middleware and applying that to instantiate a new `Activity`. But the initial queue request logging remains uncorrelatable.

**Comment by wkoeter** [comment]
Great, thanks for the explanation and the efforts. We will be looking forward to outcomes of the evaluation of this scenario.

**Comment by jviau** [comment]
Closing this as it is ultimately external to us.

In a related note: we are working on improving distributed tracing. No promises on if it will cover exactly what you want with storage queues, as that will require effort from the Azure storage SDK team as well (which is external to us.)
