### ISSUE TITLE
Tooling feed update

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1134]
Feed changes are still required,  but to “description”, not to anything else. If you want to remove Isolated, simply remove Isolated from that string,
add Standard Terms Support ( STS ), this should be in place of LTS or Preview. For Isolated versions, Isolated should always be listed first. See below.
 
We use the displayInfo.targetFramework property to determine if we need to append the v1 or v4 to the item (we only append if displayInfo/targetFramework == “.NET Framework”

Note for the 1.13.x release, you’ll need to add the description property to the netframework variant for Standard Support since it doesn’t currently have that property.

<img width="532" alt="Screen Shot 2022-10-20 at 10 23 54 AM" src="https://user-images.githubusercontent.com/4621560/197016983-1e6e881c-e72f-460c-af2c-c4c7b86ed170.png">

Description automatically generated
 
Becomes
 
<img width="679" alt="Screen Shot 2022-10-20 at 10 24 19 AM" src="https://user-images.githubusercontent.com/4621560/197017051-bbdce538-2b83-4f35-bbaa-29c1dae08dd8.png">

Description automatically generated

**Comment by kshyju** [comment]
We need an update [here](https://github.com/Azure/azure-functions-tooling-feed/blob/main/cli-feed-v4.json#L10119)

**Comment by phenning** [comment]
confirming: "Standard Support" as added will result in the proper substitution in the Visual Studio UI for other languages. "(Standard Support)" is what would be shown in the UI. Alternatively, we also support "Standard Term Support" or "STS" in the description, both of these values would also be changed to "(Standard Support)" in the UI.

**Comment by phenning** [comment]
Also, everything else you said there @cloudmelon is 100% the current implementation in 17.4 GA and beyond

**Comment by cloudmelon** [comment]
Checked with VS side and tested the STS has been added now.
