### ISSUE TITLE
Isolated function not working in Azure (NET7 RC2)

### ISSUE THREAD

**Issue by demyte** [Azure/azure-functions-dotnet-worker#1142]
Hi,

I have built a simple net7 isolated function and cannot get it to work in Azure.

This is a link to a repository that shows the issue: https://github.com/demyte/repro-azure-functions-net7-issue-02

Based on what the log is saying, it looks like NET7 RC2 is not available as a runtime in the isolated image yet?

It seems if I flag it as "Ready To Run" using the additional project file directives:

```
<PublishReadyToRun>true</PublishReadyToRun>
<RuntimeIdentifier>win-x86</RuntimeIdentifier>
```

It works, but this is not the way I want to run my functions.

Will NET7 RC2 be available on the isolated functions runtime in Azure soon?

**Comment by satvu** [comment]
Closing as net7 support has been GA
