### ISSUE TITLE
Remove preview tag for stack api .NET 7

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1143]
Remove preview tag for stack api .NET 7

Change from .NET 7 (non-LTS) (Preview)
to : .NET 7 (non-LTS)

Can you send a PR for the same here and I can take care of the rest - https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks

Thanks

**Comment by kamyker** [comment]
Still in preview, linux net7 app doesn't even work.

**Comment by cloudmelon** [comment]
> Still in preview, linux net7 app doesn't even work.

Hi @kamyker , would you let me know what is your use case ? Which version of .NET 7 that you were using ? ( e.g. previews or RC1 ? ) to which region ? Would appreciate your further details. Thanks :)

cc @kshyju

**Comment by kamyker** [comment]
> > Still in preview, linux net7 app doesn't even work.
> 
> Hi @kamyker , would you let me know what is your use case ? Which version of .NET 7 that you were using ? ( e.g. previews or RC1 ? ) to which region ? Would appreciate your further details. Thanks :)
> 
> cc @kshyju

Hi cloud, Net7 RC2, US West 1.

**Comment by fabiocav** [comment]
Closing as completed.
