### ISSUE TITLE
WriteAsJsonAsync dosen't writes when instance is JObject 

### ISSUE THREAD

**Issue by yugyesh** [Azure/azure-functions-dotnet-worker#1149]
- When writing any JObject as a HttpResponseData, **the response shows keys however the values are presented as empty array.**
```
 var response = req.CreateResponse();
JObject message = new JObject();
message.Add("Error", "messager");
await response.WriteAsJsonAsync(instance: message, statusCode: HttpStatusCode.Forbidden);
return response;
```
- The response looks like this
```
{
    "Error": []
}
```

- It responses okay when instance is of type JsonObject

**Comment by jviau** [comment]
@yugyesh Functions dotnet isolated uses System.Text.Json - `JObject` is from Newtonsoft.Json, so it is not serializable by STJ. You need to either use `JsonObject` as you already discovered, or you can configure [WorkerOptions.Serializer](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Hosting/WorkerOptions.cs#L20) to be a Newtonsoft.Json converter. However, this will have far reaching impact and change _all_ serialization to Newtonsoft.Json. STJ is the recommended serializer and is replacing Newtonsoft all over, so I recommend going with the `JsonObject` route.
