### ISSUE TITLE
Ensure collection support works for blob storage input bindings

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1156]
With the introduction of deferred binding via using ParameterBindingData/ModelBindingData to enable SDK-type bindings such as BlobClient in the worker, we need to make sure we also support the collection scenario. Meaning, we should be able to bind to `IEnumerable<BlobClient> blobs`.

Example:

```csharp
public static class BlobFunction_EnumerateBlobs_BlobClient
{
    [FunctionName("BlobFunction")]
    public static void Run(
        [BlobTrigger("sample-container/sample-blob")] Stream blobStream,
        [Blob("sample-container")] IEnumerable<BlobClient> blobs,
        ILogger logger)
    {
        logger.LogInformation("Blobs within container:");
        foreach (BlobClient blob in blobs)
        {
            logger.LogInformation(blob.Name);
        }
    }
}
```

Investigate if this works out of the box with the blob converter we have in place today. If this use case is not working, update the converter and other necessary code paths to enable this scenario

#### Notes

- This is how we handle [cardinality in the function metadata generator ](https://github.com/Azure/azure-functions-dotnet-worker/blob/6bb0845c3f9c3e5d9feb4a1bc3848de4c2afa1fe/sdk/Sdk/FunctionMetadataGenerator.cs#L524-L563) and might be useful to be aware of.

- This is the [blob converter](https://github.com/Azure/azure-functions-dotnet-worker/pull/1108) where we should be able to handle the collection case

**Comment by surgupta-msft** [comment]
Update:

Changes done in feature branches -
1. Blob Extensions - [sdk-bindings/collection-support](https://github.com/surgupta-msft/azure-sdk-for-net/pull/1)
2. Host - [sdk-bindings/collection-support-host](https://github.com/Azure/azure-functions-host/tree/sdk-bindings/collection-support-host)
3. Dotnet Worker - [sdk-bindings/collection-support](https://github.com/Azure/azure-functions-dotnet-worker/tree/sdk-bindings/collection-support)
4. Protobuf - [FunctionRpc.proto](https://github.com/Azure/azure-functions-host/blob/sdk-bindings/collection-support-host/src/WebJobs.Script.Grpc/azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto)

Pending -
1. Investigate on FunctionMetadataGenerator assigning the cardinality to Many for `IEnumerable<>` scenarios.
2. Investigate on Host mapping the `type` correctly for Array type - [Here](https://github.com/Azure/azure-functions-host/blob/b7a7b6ba38d6e81cc5784f7f2bde5e82f8839bf0/src/WebJobs.Script/Binding/GeneralScriptBindingProvider.cs#L128).
3. Starting PR by adding tests and code cleanup.

**Comment by fabiocav** [comment]
Work here is close to completion. Moving to sprint 135 so we can iterate on PRs

**Comment by surgupta-msft** [comment]
Closing this issue. Open PRs will be tracked through Epic - https://github.com/Azure/azure-functions-dotnet-worker/issues/1081
