### ISSUE TITLE
SignalROutput not working locally

### ISSUE THREAD

**Issue by gregbrant2** [Azure/azure-functions-dotnet-worker#1157]
I have a Function App using the `dotnet-isolated` model and I get an error when I try to return a `SignalRMessageAction` from a function with a `SignalROutput` binding.

I've taken an example from [this samples file](https://github.com/Azure/azure-functions-dotnet-worker/blob/b42a2a57eb1be1e7741219f0a091e3408d30bdf5/samples/Extensions/SignalR/SignalROutputBindingFunctions.cs) and simplified it slightly:

```
        [Function("SendToUser")]
        [SignalROutput(HubName = "serverless", ConnectionStringSetting = "AzureSignalRConnectionString")]
        public static SignalRMessageAction SendToUser([HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req)
        {
            return new SignalRMessageAction("newMessage")
            {
                UserId = "userToSend",
            };
        }
```
`"AzureSignalRConnectionString"` is in my local.settings.json

```
{
    "IsEncrypted": false,
    "Host": {
        "LocalHttpPort": 7099,
        "CORS": "http://localhost:4792",
        "CORSCredentials": true
    },
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",

    "AzureSignalRConnectionString": "Endpoint=https://xxxx.service.signalr.net;AccessKey=YYYY=;Version=1.0;",
  }
}
```

Project file is setup like 
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>

```

When I POST to that endpoint I get the following error message in the console.

> System.Private.CoreLib: Exception while executing function: Functions.UpdatesAvailableFunction. Microsoft.Azure.WebJobs.Extensions.SignalRService: Unable to convert JObject to valid output binding type, check parameters.

I'm using Functions tooling v4:

> Azure Functions Core Tools
> Core Tools Version:       4.0.4865 Commit hash: N/A  (64-bit)
> Function Runtime Version: 4.12.2.19454

in VS 2022 (17.3.5)

NuGets I'm using are
Microsoft.Azure.Functions.Worker 1.10.0
Microsoft.Azure.Functions.Worker.Sdk   1.7.0
Microsoft.Azure.Functions.Worker.Extensions.SignalRService 1.7.0

**Comment by kshyju** [comment]
@Y-Sindo Could you take a look please?

**Comment by Y-Sindo** [comment]
Confirmed it as a bug, will fix it in the next release.

**Comment by liliankasem** [comment]
@Y-Sindo was this bug fixed?

**Comment by Y-Sindo** [comment]
The latest release, version 1.10.0, has resolved the bug. However, there is still an issue (#1709) that prevents its usage on .NET 7. The issue is currently awaiting a fix from the dotnet isolated worker runtime.

**Comment by liliankasem** [comment]
@Y-Sindo thanks for the update - we're working to resolve 1709 soon!

**Comment by jviau** [comment]
@gregbrant2 can you verify if your issue still exists with [SignalR/1.12.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.SignalRService/1.12.0)?
