### ISSUE TITLE
Add Az CLI functionapp create for .NET 5 

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-dotnet-worker#116]

**Comment by fabiocav** [comment]
We should have an issue in the Azure CLI repo to track this.

**Comment by gzuber** [comment]
PR for stacks changes: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/26
Expecting to have AZ CLI PR soon

**Comment by gzuber** [comment]
AZ CLI PR: https://github.com/Azure/azure-cli/pull/17066

**Comment by ankitkumarr** [comment]
Thanks Graham! Closing as completed.
