### ISSUE TITLE
Generate function metadata for functions from dependent assemblies

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-dotnet-worker#1160]
# Overview

There is currently a gap with function metadata generator and the existing `function.metadata` approach with functions from dependent assemblies. The `function.metadata` approach will include functions from referenced projects/assemblies, whereas the source generator will not. To achieve behavior parity between the two methods, we need to generate function metadata for referenced assemblies as well. We do not want to mix host-provided metadata from `function.metadata` and worker-provided metadata from the generated provider. As such, we will need to also include metadata for referenced assemblies in the generated approach.

# Requirements:

1. Function metadata is generated for functions from dependent assemblies that **do not** have their own "default" function metadata provider (see default vs auxiliary provider below).
2. This metadata is registered along with the metadata from the current assembly.

## Default vs Auxiliary Provider

Part of this work will require identifying the difference between a "default" provider and an "auxiliary" provider.

### Default Provider

- Expected to provide function metadata for all of the "traditional" functions in this assembly.
- Can include metadata for other assemblies as well.
- A given assembly should be covered by a maximum of 1 default provider.
    - `DefaultFunctionMetadataProvider` is a "default" provider which covers _all_ assemblies referenced by the project.
    - `GeneratedFunctionMetadataProvider` is a "default" provider which covers the current assembly (and after this work, referenced assemblies _which are not themselves covered by a "default" provider_).
    - Customers may be able to define their own "default" provider.
- We could have an analyzer which warns when an assembly has more than 1 default provider.
- See if we can do any runtime validation. However, this may not be possible as we are unsure what assemblies a default provider covers.

### Auxiliary provider

- An assembly can have any number of auxiliary providers.
- These are expected to provide function metadata in _addition_ to the "default" provider. As in, auxiliary providers _should not_ provide metadata for 'traditional' functions.

# Concerns

Ideally this work will be part of the existing source generator. However, I am unsure if we can walk referenced assemblies as part of a source generator. If this is not possible, we can go with an MSBuild task which generates and includes a .cs file at build time. This generated file from MSBuild can still be incorporated into the source generated file by making the type "partial" and combining the logic of the two together.

**Comment by satvu** [comment]
Progress update: we are going with roslyn source-generators, but will have to refactor to use symbols only (no access to syntax trees in dependent assemblies).

**Comment by mnelsonwhite** [comment]
Should the fix seen in https://github.com/Azure/azure-functions-dotnet-worker/pull/1896 also apply to `FunctionExecutorGenerator`?
