### ISSUE TITLE
Model binding in Http triggers

### ISSUE THREAD

**Issue by rtellez91** [Azure/azure-functions-dotnet-worker#1172]
Hi!

I wonder if there is any way to make the HttpTrigger to automatically bind a model. With in process it was possible, but with this new way I wasn't able to.

I also had a Custom Binding for binding a specific model class, but now it seems that I need to do a lot of stuff for making it work again.

So the work around for now is manually call the extension method `req.ReadFromJsonAsync` if I need to bind from the request body and do something like this `NameValueCollection query = System.Web.HttpUtility.ParseQueryString(req.Url.Query);` if I want to get the query params and manually create my query objects.

So, does anybody here knows about a library or something that can be used in order to create custom bindings without having to create nuget packages like stated here https://blog.maartenballiauw.be/post/2021/06/01/custom-bindings-with-azure-functions-dotnet-isolated-worker.html?

Thanks!

**Comment by fabiocav** [comment]
Flagging this for assignment as we should support this scenario with HTTP.

**Comment by fabiocav** [comment]
Support for this as been added for both, the standard HTTP model (`HttpRequestData` based) and for the ASP.NET Core Integration. Documentation for the latter is available [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cfunctionsv2&pivots=programming-language-csharp#payload). The `FromBodyAttribute` works for both models.
