### ISSUE TITLE
Isolated Worker project won't run after upgrading to .NET 7

### ISSUE THREAD

**Issue by ProgrammerAl** [Azure/azure-functions-dotnet-worker#1181]
I have a Linux consumption-based Azure Functions Isolated project that does not start in Azure after upgrading it from .NET 6 to 7. It works locally, but once it's deployed to Azure I only receive 502 Bad Gateway responses. And no matter how many requests I send, Application Insights says no requests have been received. It's hard to diagnose because I don't get anything out of the system, no log messages or anything else.

The project is deployed with a zip package and the `WEBSITE_RUN_FROM_PACKAGE` config value points to my zip. And I think that's where the problem is. My CI/CD pipeline deploys the zip file, but when I publish from Visual Studio the deployment no longer uses the Run from Package feature, the `WEBSITE_RUN_FROM_PACKAGE` config value is gone, and the .NET 7 version it deployed works.

After reverting back to .NET 6 and re-deploying with my CI/CD pipeline, the project works again.

The changes I made to migrate to .NET 7:
  - Upgrade .NET version in csproj files
  - Update the `linuxFxVersion` config value from `DOTNET-ISOLATED|6.0` to `DOTNET-ISOLATED|7.0`

Any chance I may have missed a step upgrading? Or is this a known issue?

Response Body for every request:
```html
<html>

<head>
	<title> Server Error </title>
</head>

<body>
	<font color=\"#aa0000\">
		<h2>Server Error.</h2>
	</font>

	There was an unexpected error in the request processing.
</body>

</html>
```

**Comment by MarcoMedrano** [comment]
I have the same issue, it is fixed temporally by:
windows: `az functionapp config set --net-framework-version v7.0 -g groupName -n functionName`
linux: `az functionapp config set --linux-fx-version 'DOTNET-ISOLATED"|"7' -g groupName -n functionName`

But after some minutes, same issue. Apparently, new Windows instances use .net 6 instead of 7 and Linux .net framework 4.

**Comment by fabiocav** [comment]
@ProgrammerAl could you please share the application details so we can take a closer look at the issue?

**Comment by ProgrammerAl** [comment]
@fabiocav What kind of details are you looking for? This is a proprietary application, so I don't have an open source version I can share with you. And it'll take some time to create a minimal version of this application that reproduces this issue.

**Comment by fabiocav** [comment]
@ProgrammerAl just the application name so we can look at the resource logs and configuration. No need to share any code.

**Comment by ProgrammerAl** [comment]
@fabiocav Ah sorry, that makes a lot more sense. I just re-created my entire Azure infrastructure a few minutes ago with my CI/CD pipeline and the Azure Function App is named `services-monitors-funcs97c05cae`

**Comment by MarcoMedrano** [comment]
@fabiocav I have these functions if it is of any help:

facs-stg-BootService
facs-stg-UsersService
facs-stg-ProductService
facs-stg-FilesService
facs-stg-BolSiatService

![image](https://user-images.githubusercontent.com/2736856/202568202-ef7f43b0-e038-462c-a24e-61ad894846e1.png)

I notice that the first function is working fine, the others not matter how many times I set them to dotnet 7,  after some minutes or when they scale up, they fail.

**Comment by ProgrammerAl** [comment]
@fabiocav I made a mistake earlier today and accidentally deleted the instance of Azure Functions I mentioned in my previous reply. The new instance name is `services-monitors-funcs65ac36a7`

**Comment by kshyju** [comment]
@ProgrammerAl  I took a look at your app(services-monitors-funcs65ac36a7) and I see that the `LinuxFxVersion` value for this app is set as `dotnet-isolated|6.0` (today and on Nov17th). Is there a specific reason for you to have this Appsettings entry? Could you try deleting this appsetting, save and deploy your app again?

**Comment by ProgrammerAl** [comment]
@kshyju the `linuxFxVersion` AppSetting is there because this is an isolated linux app that deploys from a zip package. I was following the documentation that says this setting is required for zip package deployment (in the Note section here: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#net-isolated-worker-process-project )

I tried removing the `linuxFxVersion` setting, and it made no change. I added it back just to test, and that also made no change. 

Something I'm a little confused about though, is you said the `linuxFxVersion` config value was set to `dotnet-isolated|6.0`, but when I checked, it was definitely set to `dotnet-isolated|7.0`. Not sure why they're different between what we both see. 

If it helps you search, I have a few other Linux based Isolated Azure functions that also deploy with zip packages that are also having this same problem. They are `public-funcsd648833d` and `games-management-funcs0f513812`.

**Comment by kshyju** [comment]
> I tried removing the `linuxFxVersion` setting, and it made no change. I added it back just to test, and that also made no change.

Thanks @ProgrammerAl Just to confirm. Did you redeploy after removing this app setting?

**Comment by CooperLink** [comment]
Hi Al, 

I took a look at some of your apps.  I think I know what might be occurring here. It appears that you are setting an AppSetting <LinuxFxVersion>.  However, LinuxFxVersion is a Site Configuration not an AppSetting and it cannot be set from the portal.  

Could you please remove the AppSetting and update the `LinuxFxVersion` to "DOTNET-ISOLATED|7.0"?  You can use the command provided below from the guide here : https://learn.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal#manual-version-updates-on-linux


`az functionapp config set --name <FUNCTION_APP> \
--resource-group <RESOURCE_GROUP> \
--linux-fx-version <LINUX_FX_VERSION>`

**Comment by CooperLink** [comment]
@MarcoMedrano I took a look at your application as well.  It appears that your LinuxFxVersion is inavlid. Could you please use this detector to check out your apps and update them to "DOTNET-ISOLATED|7.0" where necessary? 

Detector : https://applens.trafficmanager.net/subscriptions/4628154d-03ee-4ccf-98df-0487b01f5e48/resourceGroups/facs-stg/providers/Microsoft.Web/sites/facs-stg-ProductService/detectors/functionlinuxplaceholder?startTime=2022-12-05T17:46&endTime=2022-12-06T17:30
Valid LinuxFxVersion docs : https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#linuxfxversion

**Comment by ProgrammerAl** [comment]
@CooperLink @kshyju 
Yep, that solved the issue for me. To sum up, the problem was caused by my misunderstanding of this config setting. I had wrongly assumed the `LinuxFxVersion` was an App Setting, which it is not. My guess as to why it worked when I was using .NET 6 is because .NET 6 is the default value, and me creating the `LinuxFxVersion` setting did nothing. Thank you so much for helping me figure that out.
