### ISSUE TITLE
Boolean check instead of string check 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1184]
I have seen a few reports of this error : MSB4113Specified condition "$(SelfContained)" evaluates to "" instead of a boolean. .nuget\packages\

http://microsoft.azure](https://t.co/dtzB51fs7d).functions.worker.sdk\1.7.0\build\

http://Microsoft.Azure](https://t.co/T5HtGGDmoo).Functions.Worker.Sdk.targets113

https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

**References** :

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/sdk/Sdk/Targets/Microsoft.Azure.Functions.Worker.Sdk.targets#L113

https://twitter.com/davidpine7/status/1592379008628707328

**Comment by fabiocav** [comment]
The ask here is to change the places where we're evaluating `SelfContained`, assuming it is a `bool` to perform a check against `true`/`false` instead.

```
"'$(SelfContained)' == 'true'"
```

**Comment by mattchenderson** [comment]
This seems to have been addressed by https://github.com/Azure/azure-functions-dotnet-worker/pull/2347.
