### ISSUE TITLE
There is no Functions runtime available that matches the version specified in the project. 

### ISSUE THREAD

**Issue by Ofer-Gal** [Azure/azure-functions-dotnet-worker#1193]
I am testing the sample from https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Net7Worker in VS2022 Version 17.4.1
When I try to debug locally, I get the message 
![image](https://user-images.githubusercontent.com/5054931/203596080-b3bcc8a8-e742-4f1e-a112-0b3541c7163d.png)

I already installed 3 packages:
winget install Microsoft.DotNet.SDK.7
winget install Microsoft.DotNet.Runtime.7
winget install Microsoft.DotNet.AspNetCore.7

What else is missing?
Thank you

**Comment by kshyju** [comment]
I suspect your visual studio instance failed to refresh the azure functions tools automatically. You can manually do this refresh by following the instructions [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/989#issuecomment-1283018013). Let us know if that solves your problem.

**Comment by Ofer-Gal** [comment]
All good now
