### ISSUE TITLE
Throughput calculation for sdk type bindings

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#1194]
Setup scenarios and run tests to evaluate throughput changes with sdk type bindings.

Related broader issue - https://github.com/Azure/azure-functions-host/issues/8618

**Comment by surgupta-msft** [comment]
Completed initial setup and able to run experiments with New and Old sdk.

**Comment by fabiocav** [comment]
Closing this as completed.
