### ISSUE TITLE
[TestServer] Isolated and Integration Testing 

### ISSUE THREAD

**Issue by bhugot** [Azure/azure-functions-dotnet-worker#1196]
Hello, 
In order to do integration testing with our Azure Function we use some code like this as we are in in-Process (not isolated) mode :
```
 var host = new HostBuilder()
            .ConfigureWebHost(web => web.UseTestServer().Configure(_ => { }))
            .ConfigureWebJobs(c =>
            { 
              // some specific configuration
            }).Build();
await host.StartAsync();
var jobs = host.Services.GetRequiredService<IJobHost>();
```
and from jobs we use CallAsync to execute a function.

It would be great to be able to do some thing close to this or even simpler for Isolated function. 
I m not sure where the change could be done but from what I see it could be done with a custom IWorker Implementation or by using testserver for grpc part.

**Comment by SeanFeldman** [comment]
I'm confused, @bhugot. Isn't Isolated and Out of Process the same SDK?

**Comment by bhugot** [comment]
Yes sorry forgot to change it. I fixed original message

**Comment by brettsam** [comment]
Some of this work was started about a year ago but was put on hold for various reasons -- we'll discuss bringing this back into active development. 

https://github.com/Azure/azure-functions-dotnet-worker/issues/281

**Comment by brettsam** [comment]
We've just re-introduced the original issue into our planning for next Sprint. I'm going to close this one in favor of the older one. Thank you for bringing this back up.
