### ISSUE TITLE
Is it possible to load Functions from dependencies?

### ISSUE THREAD

**Issue by gregbrant2** [Azure/azure-functions-dotnet-worker#1199]
[This blog post ](https://www.ericksegaar.com/2021/01/19/discover-precompiled-function-apps/)suggests it is possible to load functions from dependencies using `<FunctionsInDependencies>true</FunctionsInDependencies>` in the csproj fie, is this still true using Microsoft.Azure.Functions.Worker.Sdk v1.7.0 and isolated-process model?

**Comment by jviau** [comment]
Yes, this is still possible. You can verify this by checking the `functions.metadata` file in your build output. You should see the functions from your referenced assemblies there.
