### ISSUE TITLE
how to remove the built in  RenderOAuth2Redirect etc endpoints?

### ISSUE THREAD

**Issue by drew-fc** [Azure/azure-functions-dotnet-worker#1202]
when changing from in-proc to isolated, I noticed these new endpoints are auto generated.
How can I remove them?

RenderOAuth2Redirect
RenderOpenApiDocument, etc...

**Comment by kshyju** [comment]
Those route names looks like the one generated when you add [OpenAPI support](https://devkimchi.com/2021/08/13/azure-functions-openapi-on-net5/) to your function app. 

Do you have a package reference to `Microsoft.Azure.Functions.Worker.Extensions.OpenApi` package in your .csproj file? If you remove that package reference entry, those routes will be removed. If that does not work, can you please share your .csproj content?

**Comment by drew-fc** [comment]
thanks @kshyju ,

I did have that, but removing it did not fix the issue.

Here's my CSPROJ:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" Version="6.0.6" />
    <PackageReference Include="JWT" Version="9.0.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview3" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
  
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.1" />
  

<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />

<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="7.0.0" />

<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.25.0" />

    <PackageReference Include="PlayFabAllSDK" Version="1.140.221024" />
    <PackageReference Include="PlayFabCloudScriptPlugin" Version="1.53.190627-alpha" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.0" />
        
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Properties\serviceDependencies.local.json.user" />
  </ItemGroup>

</Project>
`
