### ISSUE TITLE
Updating from Microsoft.Azure.Functions.Worker.Sdk 1.3.0 to 1.7.0 produces code analysis DLLS in the build output, thus increasing output size by more than 5MB

### ISSUE THREAD

**Issue by pxmonti** [Azure/azure-functions-dotnet-worker#1210]
Hello I am developing a project that implements an Azure function. I was previously using version 1.3.0 of the Microsoft.Azure.Functions.Worker.Sdk package and recently updated to 1.7.0. Since I've updated to 1.7.0, the build output now include the Code Analysis DLLs for more than 5MB extra build size. This was not happening with 1.3.0.
Since code analysis DLLs are mainly useful during project development and not at project publishing, I wanted to know if there's a way to exclude those DLLs when publishing the project with 'dotnet publish'.
Thanks in advance for the support.

**Comment by fabiocav** [comment]
@pxmonti thank you for flagging this. We had a fix for this issue landing soon and will close this issue once that is merged.

**Comment by satvu** [comment]
Changes were included in #1191 and the SDK 1.9.0 release [here](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.9.0) should fix this.
