### ISSUE TITLE
LogMetric usage results in unresolvable ambiguous reference

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-dotnet-worker#1215]
Consider the following usage:
```csharp
                    _log.LogMetric("IngestionTime", timer.ElapsedMilliseconds);
```

In the isolated worker, this results in an unresolvable ambiguous reference compilation error:

```
Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.Logging.LoggerExtensions.LogMetric(Microsoft.Extensions.Logging.ILogger, string, double, System.Collections.Generic.IDictionary<string, object>)' and 'Microsoft.Extensions.Logging.ILoggerExtensions.LogMetric(Microsoft.Extensions.Logging.ILogger, string, double, System.Collections.Generic.IDictionary<string, object>?)
```

Note the conflicting syntaxes differ only by usage of the nullable operator (`?`) which makes this an unresolvable problem as `IDictionary<string, object>` is assignable to null itself.

I'm not sure where in the dependency path we're picking up a newly-defined extension, but this needs to be solved so Metrics can be used by Azure Functions in the new Isolated programming model. **This error does not happen in the in-proc version of Functions v4**

Here are my referenced nuget pkgs & versions:
![image](https://user-images.githubusercontent.com/20270743/206268394-507db557-0784-4075-9ec1-1e32c6bd160d.png)

**Comment by zuhaerzim** [comment]
Is there any resolution for this? Wondering because I have run into the same issue.

**Comment by brandonh-msft** [comment]
> Is there any resolution for this? Wondering because I have run into the same issue.

my resolution at the moment is to revert back to the in-proc model until this is resolved as Metrics are an integral part of our logging

**Comment by julienFlexsoft** [comment]
I have the same issue when switching from .NET 6 In-Process to .NET 7 Isolated Process.

**Comment by vortex2143** [comment]
I had the same issue. Helpful was for me removing the reference for `<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.36" />`.

**Comment by SamBWagner** [comment]
I'm having the same issue. Did any of you find a solution?

**Comment by brandonh-msft** [comment]
> I'm having the same issue. Did any of you find a solution?

I've not assessed the latest bits as in-proc continues to work fine for us. Am waiting on the team to reply/fix before I go through the effort

**Comment by petteroo** [comment]
I had the same Issue when changing from .Net 6 in process to .Net 7 isolated. For me it was the same issue as @vortex2143 my reference came from the package Microsoft.Azure.Functions.Extensions that itself was referencing Microsoft.Azure.WebJobs v. 3.0.18.

**Comment by varunagarwal111** [comment]
I am also having the same issue. Any update on this please? Are you working on this guys? Any timeline?

**Comment by duncanworthy** [comment]
Extension methods are just a special type of static method in a static class, and can always be called as a normal static method by passing the `@this` object as the first parameter, so in the OP's example, you can simply change from
`_log.LogMetric("IngestionTime", timer.ElapsedMilliseconds);`
to
`LoggerExtensions.LogMetric(_log, "IngestionTime", timer.ElapsedMilliseconds);`
in order to resolve the ambiguous call.

**Comment by dominicusmento** [comment]
> Extension methods are just a special type of static method in a static class, and can always be called as a normal static method by passing the `@this` object as the first parameter, so in the OP's example, you can simply change from `_log.LogMetric("IngestionTime", timer.ElapsedMilliseconds);` to `LoggerExtensions.LogMetric(_log, "IngestionTime", timer.ElapsedMilliseconds);` in order to resolve the ambiguous call.

This doesn't solve the problem:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7549001/6849aecf-02cf-4b04-906e-76e8ddcca62f)

However I solved this by referencing the ILoggerExtensions class, which is similar, but exists only in Microsoft.Extensions.Logging so thanks for the idea: 
**`ILoggerExtensions.LogMetric(_log, "IngestionTime", timer.ElapsedMilliseconds);`**

**Comment by brettsam** [comment]
This is part of the issue with extension methods. If two referenced assemblies have the same extension method name, they'll conflict. 

To get around this, you should be able to call `ILoggerExtensions.LogMetric(...)` directly as noted above.

However, `ILoggerExtensions` is a very common class name. It's entirely possible that another packages brings in their own `ILoggerExtensions.LogMetric(...)` method. We should have named our class something more unique than `ILoggerExtensions` to avoid this -- so you could at least directly call it more easily if you had a conflict with the extension method. The solution to this is something provided by nuget and .net -- `extern alias`: https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases

However! The better solution here is to move to using our [newer-style Application Insights support](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#application-insights) and writing logs directly without using this wrapper method at all. This will allow you to emit metrics using a `TelemetryClient` without having to "wrap" them via `LogMetric()` and have the host emit them for you.

I'm going to keep this around to fix in our next major version, but for now I think there are enough workarounds to unblock everyone.
