### ISSUE TITLE
Ensure collection support works for cosmosDB input bindings

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1217]
With the introduction of deferred binding via using ParameterBindingData/ModelBindingData to enable SDK-type bindings such as CosmosContainer in the worker, we need to make sure we also support the collection scenario. 

As part of this work, we need to ensure support for `IEnumerable<POCO>`.  Currently, the CosmosDB extension returns a single "document" for the input binding, so when users bind to a list e.g. IList<POCO>, things are broken. However binding to a single POCO should work today.

Aim of this story is to implement a way for both list and single POCO and client bindings to work. This might be a good time to look into using [cardinality](https://github.com/Azure/azure-functions-dotnet-worker/blob/314910297de34be74371077b808b3a72608c7189/sdk/Sdk/FunctionMetadataGenerator.cs#L515-L566).

**Comment by fabiocav** [comment]
Related to #1204 and #1156

**Comment by fabiocav** [comment]
Additional validation is required here to check whether recent changes have addressed this issue.

Moving to 137 for validation

**Comment by liliankasem** [comment]
Implemented in https://github.com/Azure/azure-functions-dotnet-worker/pull/1109
