### ISSUE TITLE
Http[Request/Response]Data contract classes design discussion

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-functions-dotnet-worker#122]
**Preface:** As the title notes, this is probably more of a discussion than an issue, but it doesn't look like discussions are enabled on this repo yet... which is understandable since [it's only just recently (i.e. 3 days ago) gone into public beta](https://github.blog/changelog/2020-12-08-github-discussions-now-available-as-a-public-beta/). 😊

In looking at the samples and what immediately jumped out at me as someone who utilizes HTTP triggered functions the majority of the time is the introduction of two new data contract classes to represent the request and response: `HttpRequestData` and `HttpResponseData`.

First, I would like to ask that we could have some kind of short explanation of why these classes were introduced. I believe it's because the SDK does not want to pin itself to a specific version of `System.Net.Http`, is that correct? If so, would you care to expand on why you think it's a bad idea to tie a specific _extension_ to another dependency? Frankly, I think it would be a big mistake to force new types on .NET developers in the context of an Azure Function when in so many other contexts `System.Net.Http` is what we all use and which itself has an extension ecosystem built around it.

Second, if it comes down to decoupling, well then I have concerns about the design of these contracts. For example, the `Body` being a `string`: this is dangerous for performance on multiple levels. First and most basic, even if I actually do want to return a `string`... I shouldn't have to build a whole contiguous `string` like that. Second, if I don't want to return a `string` and want to return binary data... what option do I have now? I would have to return base-64 encoded bodies and that's just, well, not a good idea from an HTTP perspective and could completely box out some standard HTTP scenarios like file downloads or serving images. I would also suggest that the `Headers` property being defined as the concrete type `Dictionary<string, string>` and always allocated even if not used is a terrible idea from a performance perspective. Anyway, we can split off and go into deeper on into this in separate issues once we have the core discussion established, but the point is that so much of this is already well thought out, designed and implemented into the existing `System.Net.Http` type system and I think it's a mistake to eschew that for an _extension_ where I'm very much opting in to using HTTP in the first place.

**Comment by fabiocav** [comment]
Transferred the issue to the worker repo so we can continue updating here. The first wave of changes towards the design shared above is in PR right now. Still in draft, as it is being iterated on.
