### ISSUE TITLE
.NET 7 throughput test coverage 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1223]
For GA'd language versions, we want to monitor the performance on a regular basis. We do this by adding apps to our perf infra and then making sure the numbers start appearing on the dashboard. 

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-the-net-7-for-azure-functions-isolated-worker-process/ba-p/3671398

**Comment by fabiocav** [comment]
Closing stale item.
