### ISSUE TITLE
SendGridOutput compile error

### ISSUE THREAD

**Issue by natelaff** [Azure/azure-functions-dotnet-worker#1225]
In an Isolated function (.NET 7), if I add Microsoft.Azure.Functions.Worker.Extensions.SendGrid 3.0.2 then create a function which uses SendGridOutput, I get a compile error where it's looking for WorkerExtensions.cs in my private devops feed.

1>C:\Users\nate\AppData\Local\Temp\suvfc1hh.gnw\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source [devops feed here].

```
    public class Function
    {
        private readonly ILogger _logger;

        public Function(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function>();
        }

        [Function("Function")]
        [SendGridOutput(ApiKey = "SendGrid:Key", To = "{EmailTo}", From = "{EmailFrom}")]
        public void Run([ServiceBusTrigger("mytopic", "mysubscription", Connection = "")] string mySbMsg)
        {
            _logger.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
        }
    }
```

**Comment by fabiocav** [comment]
@natelaff can you confirm this is in a restricted environment where your build is restoring from the private feed only, with no access to public NuGet? 

At build time, the project will need to restore the package https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SendGrid , so if that is available in your private feed, your build should succeed.

**Comment by natelaff** [comment]
Hi @fabiocav 

It restores that package just fine, as well as all other packages, it just is looking for that source file for whatever reason?

**Comment by natelaff** [comment]
@fabiocav

Also, i noticed you mentioned Microsoft.Azure.WebJobs.Extensions.SendGrid.

This is an isolated function app (.NET 7) not in-process, so I'm using Microsoft.Azure.Functions.Worker.Extensions.SendGrid .

**Comment by kshyju** [comment]
@natelaff Microsoft.Azure.Functions.Worker.Extensions.SendGrid package has an[ internal dependency](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.SendGrid/src/Properties/AssemblyInfo.cs#L6) on Microsoft.Azure.WebJobs.Extensions.SendGrid. So we should ensure that this package is also accessible in your environment.

**Comment by natelaff** [comment]
@kshyju ah, yes that does fix it! That seems like an odd dependency to need to bring in.

**Comment by fabiocav** [comment]
Thanks for the confirmation, @natelaff. For clarity, that package is what actually provides the binding implementation that is registered with, and used by, the host.

Closing as resolved/answered, but let us know if you need any additional information.
