### ISSUE TITLE
Switching to dotnet-isolated functions .on NET 6 Resulting in 100% Memory and CPU Usage under heavy load.

### ISSUE THREAD

**Issue by Gevil** [Azure/azure-functions-dotnet-worker#1228]
Greetings,

We recently tried to move to dotnet-isolated functions from our V4 .NET 6 functions.

We load tested our functions extensively and managed to get very nice throughput numbers on our TEST environments scaled to prod instance counts.

We are using mainly HTTP and Service bus triggers (both single message and batched triggers)

When we reached our PROD environment we see the RAM and CPU usage stable for a few minutes when swapping in the new instances of the isolated functions, but after a few minutes running on 3 instances of P1V2 we see the RAM usage climb to 100% on all 3 instances also maxing out the CPU usage and then the functions are stuck almost completely.

HTTP triggers are timing out taking longer than 100 seconds to respond. 
Service bus triggers are also slower to process.

We then rolled back to using in process functions so the exact same code base running and it works perfectly fine.

Any idea what could be causing the new isolated functions to cause such a thing ?

Worth noting that while load testing we were also hitting the SB triggers and Http Triggers with more than 5K messages and requests a minute and we did not see this same behavior, but whenever we tried to deploy this to PROD it starts to max out the App Service and dies.

We also tried scaling to a higher SKU like P2V2 that seemed to be able to handle the load fine for a while but then that also maxed out on RAM usage.

We do not have any memory leaks in our code as the same code is running on non isolated just fine.

I suspect something with the IsBatched=true SB triggers might be causing something.

**Comment by fabiocav** [comment]
@Gevil this may be tricky to investigate using a GH issue.

Would you be able to open a support incident with Azure Support? They would be able to provide guidance on how to collect a memory dump that would help us identify exactly what is happening in your environment.

**Comment by Gevil** [comment]
Looks like we managed to isolate the issue to a code path that was not part of an issue with functions, but ef core 7 instead.
Query execution behavior changed leading to rising memory usage.

Closing the issues now.
