### ISSUE TITLE
upgrade references and framework to natively compile/use dotnet 6

### ISSUE THREAD

**Issue by bobbyangers** [Azure/azure-functions-dotnet-worker#1229]
Support for dotnet6 isolated.

Compile against recent (non-obsolete) `dotnet5`, `dotnetcoreapp3.1`

Upgrade to use more recent references.

**Comment by fabiocav** [comment]
@bobbyangers the library does support .NET 6/7. The targets using a lower version here only limit the set of APIs available to the SDK, but not the application.

We're also unable to drop support for TFM within a given major version of the library. Targets will be updated in the next major release of our packages.

If this is causing problems, can you share more information here?

We also have a change in PR to update all of our test and samples targets: https://github.com/Azure/azure-functions-dotnet-worker/pull/1203

**Comment by bobbyangers** [comment]
@fabiocav although it does compile, it does not take advantage of the .net6 (or .net7) and linked to older and unsupported frameworks.

I do understand that you don't want to change within a minor release, maybe it's time to release a major version that leverage the framework/library of .NET 6 (LTS) and .NET 7;  and drop support for `netcoreapp3.1` and `net5.0` which are no longer supported.

**Comment by bobbyangers** [comment]
> 
> We also have a change in PR to update all of our test and samples targets: #1203

I'll wait for this to push through and revisit my proposal.   Looking at that PR (#1203), mine new PR will be much smaller :-)

**Comment by bobbyangers** [comment]
@fabiocav Please refer to this project as an example;
REF: [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http)

They compile against:  `net462`, `netstandard2.0`, `net6.0`, `net7.0`;  not because they are incompatible, but because the different versions have different base.  Therefore it's better to multi-target and test against each.
