### ISSUE TITLE
In Dockerfile for Azure Functions isolated .NET 7, why are two versions of runtime (6.0) and SDK (7.0) used?

### ISSUE THREAD

**Issue by kristofferjalen** [Azure/azure-functions-dotnet-worker#1231]
In Visual Studio (version 17.4.3), creating a **.NET 7.0 Functions App with Isolated worker process** and **Docker enabled** gives me below `Dockerfile` template.

For what reason are two different versions of the runtime (6.0) and the SDK (7.0) used?

Isolated worker process obviously [supports .NET 7.0][1].

```dockerfile
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/runtime:6.0 as runtime6.0
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
# Copy .NET Core 6.0 runtime from the 6.0 image
COPY --from=runtime6.0 /usr/share/dotnet/host /usr/share/dotnet/host
COPY --from=runtime6.0 /usr/share/dotnet/shared /usr/share/dotnet/shared
WORKDIR /src
COPY ["FunctionApp1/FunctionApp1.csproj", "FunctionApp1/"]
RUN dotnet restore "FunctionApp1/FunctionApp1.csproj"
COPY . .
WORKDIR "/src/FunctionApp1"
RUN dotnet build "FunctionApp1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FunctionApp1.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
```

  [1]: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#supported-versions

**Comment by fabiocav** [comment]
@CooperLink aren't the images using a self-contained build of the host? If so, the .NET 6 runtime wouldn't be needed here.

FYI @kshyju

**Comment by kshyju** [comment]
Followed up with @ncarlsonMSFT, who will provide an update on the fix/ETA.

**Comment by NCarlsonMSFT** [comment]
@kristofferjalen When support was initially added for isolated .NET 7, the projects required the .NET 6 runtime to build. I've verified that the latest NuGets no longer require this so we can update the scaffolder to drop the extra runtime (I've added that to our backlog). If you are using the latest NuGets you should be able to remove the lines referencing runtime6.0.

**Bonus note:** the .NET 6 runtime is only being added to the image used for building, so this should have no impact on your production image either way; but removing it will speed up your build.
