### ISSUE TITLE
AppInsights logs dependencies only wouthout APPLICATIONINSIGHTS_CONNECTION_STRING in local.settings.json

### ISSUE THREAD

**Issue by krzyszkowski** [Azure/azure-functions-dotnet-worker#1243]
Hi,

I'm trying to configure App Insights with APPLICATIONINSIGHTS_CONNECTION_STRING setup in code :

  ```
public class Program
    {
        const string AiConnectionString = "AI_CONNECTION_STRING_HERE"; // in real it would be retrieved from ACC

        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults((workerApplication) =>
                {
                    workerApplication.AddApplicationInsights(o => o.ConnectionString = AiConnectionString);
                    workerApplication.AddApplicationInsightsLogger();
                })
                .Build();

            host.Run();
        }
    }
```
Issue :

- Works if APPLICATIONINSIGHTS_CONNECTION_STRING provided in local.settings.json
- When APPLICATIONINSIGHTS_CONNECTION_STRING added in code, **only dependencies are logged**

Sample repo -> [Link](https://github.com/krzyszkowski/WorkerAiSampleApp)

Steps to reproduce :

1. Add valid app insights connection string to variable AiConnectionString in Program.cs
2. Run app
3. POST/GET `http://localhost:7071/api/HttpFunction`
4. Check App Insights : there are no customMetrics and traces

**Comment by fabiocav** [comment]
Thanks @krzyszkowski . The issue you're describing is a result of how the responsibility for some of the logs going into AI are divided between the host and the worker today.  

When the connection string is defined in code only, the host does not see that information, and all AI logging it does will be disabled (this includes binding communication with underlying services, function dispatching information, etc.).

To make sure we clearly understand your scenario, can you clarify what you mean by `ACC` above? Asking because a few options would be applicable here :)

Adding @brettsam for comments, but today, the environment variable will be required (defined in App Settings for a deployed site, so local.settings.json wouldn't actually be present there) for this to behave as expected.

**Comment by krzyszkowski** [comment]
Hello @fabiocav , thanks for your clarifications, reading your reply I got enlighted (`the environment variable will be required`) and managed to have it working. As `AAC `I ment Azure App Configuration.

I reordered program.cs to this order-> ConfigureAppConfiguration then ConfigureServices and ConfigureFunctionsWorkerDefaults last, result is something like :

```
public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration(builder =>
                {
                    var tempConfig = builder.Build();
                    builder.AddAzureAppConfiguration(options =>
                    options.Connect(new Uri("https://SOMETHING.azconfig.io"), new DefaultAzureCredential()));
                })
                .ConfigureServices(services =>
                {
                    services.AddAzureAppConfiguration();
                    services.AddApplicationInsightsTelemetryWorkerService();
                    var sp = services.BuildServiceProvider();
                    var telemetryConfiguration = sp.GetService<TelemetryConfiguration>();
                    var serverTelemetryChannel = new ServerTelemetryChannel
                    {
                        EndpointAddress = telemetryConfiguration.TelemetryChannel.EndpointAddress
                    };
                    serverTelemetryChannel.Initialize(telemetryConfiguration);
                    telemetryConfiguration.TelemetryChannel = serverTelemetryChannel;

                    var loggerConfig = new LoggerConfiguration()
                                                                .MinimumLevel.Information()
                                                                .MinimumLevel.Override("Microsoft", LogEventLevel.Error);

                    loggerConfig.WriteTo.ApplicationInsights(telemetryConfiguration, TelemetryConverter.Traces);
                })
                .ConfigureFunctionsWorkerDefaults(app =>
                {
                    app.UseAzureAppConfiguration();
                    app.AddApplicationInsights();
                    app.AddApplicationInsightsLogger();
                })
                .Build();

            host.Run();
        }
```
Note: configure url to AAC in config (no hardcode as above) also required calling   `.ConfigureAppConfiguration(builder =>  builder .AddEnvironmentVariables();` because ConfigureFunctionsWorkerDefaults  is called later.
