### ISSUE TITLE
Function Service Bus trigger not firing

### ISSUE THREAD

**Issue by slabarque** [Azure/azure-functions-dotnet-worker#1244]
Hi

I have a function app with a service bus trigger. During testing the trigger was firing correctly when placing messages on the service bus subscription and checking the function app log stream. Now the application is running in a production environment where messages get placed on the bus once a day. However the function app is not getting triggered by these messages and they remain queued. I see the same behavior on our dev and acceptance environments. When I open the function app on the Azure portal to take a look it suddenly starts processing all of the messages. It's like the function app is sleeping until I wake it up by looking at it...
Some details:
Function app runtime:v4
Operating system: Windows
Hosting plan: Consumption
netcore version: 6
location: eastus
![image](https://user-images.githubusercontent.com/2572680/208412443-bef4b177-4bd2-4a2e-ad92-8216f6181e4f.png)
![image](https://user-images.githubusercontent.com/2572680/208412517-cee8b9c7-5a1f-4164-b806-e4a0a647037e.png)
![image](https://user-images.githubusercontent.com/2572680/208412582-c98811b6-81b0-49f9-bfff-a45279e869cb.png)
![image](https://user-images.githubusercontent.com/2572680/208413208-67f4004a-6096-493b-bf0b-0483baea247d.png)
![image](https://user-images.githubusercontent.com/2572680/208412734-e30f662a-d559-4ea1-b98e-0cdd2ca76cfb.png)

**Comment by SeanFeldman** [comment]
You're using In-Process SDK. This repository is for Isolated Worker SDK.

**Comment by slabarque** [comment]
Ok, I'll move it over to
https://github.com/Azure/Azure-Functions/issues
