### ISSUE TITLE
eventhubtrigger messages parameters in dotnet-isolated is passed as string[], breaking scenarios requiring byte[]

### ISSUE THREAD

**Issue by tomerrt** [Azure/azure-functions-dotnet-worker#1256]
Per [sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/EventHubs/EventHubsTriggerMetadata.cs#L25) messages are now passed as string[] instead of byte[].

If data is sent to the eventhub in custom compressed binary format, the encoding to string breaks parsing it as bytes[] and decompressing it.

The same worked in the in-process model when the messages were passed to the functions as byte[].

**Comment by fabiocav** [comment]
@tomerrt I would expect this to work today. Have you tried changing your parameter to `byte[]` ? If so, can you share the issue you found with that?

If that isn't working, it is indeed a defect. We'll investigate this, but if you have more details, that would help with the investigation on our side. 

Thanks!

**Comment by fabiocav** [comment]
Still working on scenario validation and defining what the sample would look like. Moving to sprint 139 to reflect the ongoing work.

**Comment by madelinegordon** [comment]
Hi @tomerrt , I have validated that this scenario works when a message is passed as `byte[]` for non-batched scenarios, or `IEnumerable<byte[]>` for batched scenarios. See samples below: 

batched:
``` csharp
[Function("EventHubsTriggerMetadata-Parameters")]
public static void UsingParameters([EventHubTrigger("dest", Connection = "conn")] IEnumerable<byte[]> bytes)
{
    var message = Encoding.ASCII.GetString(bytes.First()) ;
}
```

not batched:
``` csharp
[Function("EventHubsTriggerMetadata-Parameters")]
public static void UsingParameters([EventHubTrigger("func-samples-eh", Connection = "EventHubConnectionAppSettingListen", IsBatched = false)] byte[] bytes)
{
    var message = Encoding.ASCII.GetString(bytes) ;
}
```


If you have any additional questions please let us know, thanks!

**Comment by tomerrt** [comment]
Tried it, the bytes parameter is null using the Azure Function Core Tools.

**Comment by kshyju** [comment]
@tomerrt Would you be able to share a minimal repro of your issue with us? A link to a GH repo would be great.
