### ISSUE TITLE
GA plan for Microsoft.Azure.Functions.Worker.ApplicationInsights

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#1263]
There are several outstanding work items needed before the Microsoft.Azure.Functions.Worker.ApplicationInsights nuget package can be declared generally available (GA).

We'll be resolving any related App Insights issues here and making sure there is a central place to bring up issues that we can add to this list. Once the package is GA, we'll close this and handle new issues as we would any other package.

### To fix the issue with App Insights logs missing from Console logging in Core Tools:
- [ ] Allow worker packages to specify capabilities (#1183)
- [ ] Host release that includes App Insights PR (https://github.com/Azure/azure-functions-host/pull/8965) must be in production
- [x] #1264

### OpenTelemetry support (on worker only):
- [x] #1358
- [x] #1359

### Documentation:
- [ ] Explain the split between worker and host logging. Especially how configuration is managed for each (https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627)

**Comment by jacobjmarks** [comment]
Might I also suggest that the [Net7Worker](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Net7Worker) sample be updated to include proper Application Insights configuration when available? I have recently been on the rollercoaster (#1182) that is AI configuration for .NET 7 Isolated Workers and at this point I'm very much interested in some _official_ documented solutions.

**Comment by fgheysels** [comment]
Is there already any progress or news regarding the General Availability of this package ?
The latest release of this (preview) package is already 5 months old.  Is this project still alive ?

**Comment by Shumigaj** [comment]
Functions with HttpTrigger don't work with `Microsoft.Azure.Functions.Worker 1.8.0` and `Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-preview3` packages. The problem is solved by updating `Microsoft.Azure.Functions.Worker` to `1.10.0` version

**Comment by stijnmoreels** [comment]
> Functions with HttpTrigger don't work with `Microsoft.Azure.Functions.Worker 1.8.0` and `Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-preview3` packages. The problem is solved by updating `Microsoft.Azure.Functions.Worker` to `1.10.0` version

How does custom telemetry then work, as there is no more `TelemetryClient` registered in the dependency container?

**Comment by stijnmoreels** [comment]
@Shumigaj any update on this?

**Comment by Shumigaj** [comment]
My functions doesn't work at all with `Microsoft.Azure.Functions.Worker 1.8.0` and `Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-preview3` packages. I couldn't make any requests to it on my local machine until I just updated `Microsoft.Azure.Functions.Worker` to `1.10.0` version, after that update everything works as expected. I wanted to mention this side effect with the version because it seems that there is no limitation for the version of the `Microsoft.Azure.Functions.Worker` package in the `Microsoft.Azure.Functions.Worker.ApplicationInsights` package.

**Comment by stijnmoreels** [comment]
> My functions doesn't work at all with `Microsoft.Azure.Functions.Worker 1.8.0` and `Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-preview3` packages. I couldn't make any requests to it on my local machine until I just updated `Microsoft.Azure.Functions.Worker` to `1.10.0` version, after that update everything works as expected. I wanted to mention this side effect with the version because it seems that there is no limitation for the version of the `Microsoft.Azure.Functions.Worker` package in the `Microsoft.Azure.Functions.Worker.ApplicationInsights` package.

Yes, ok, but how does custom telemetry work with this? As it is the preview package that registers the `TelemetryClient`.

**Comment by stijnmoreels** [comment]
Could you please provide some feedback on how to do custom telemetry in isolated Azure Functions, without using the `Microsoft.Azure.Functions.Worker.ApplicationInsights` package?
As no `TelemetryClient` or `TelemetryConfiguration` is registered in the application services.

@Shumigaj 
FYI @fgheysels @pim-simons

**Comment by Shumigaj** [comment]
It is possible, just use `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights.WorkerService` packages. Dependencies can be registered by `AddApplicationInsightsTelemetryWorkerService` method. But, there are drawbacks of this approach (e.g. operation id won't be populated)

**Comment by ChrisProlls** [comment]
Any news about this ?
Will the `previewXX` packages prevents us from upgrading our Function to .NET 8 in the future ?

**Comment by stijnmoreels** [comment]
> But, there are drawbacks of this approach (e.g. operation id won't be populated)

Then it is rather pointless to use this approach when there's no service-to-service/transactional correlation available; feels like an incomplete workaround.

The preview package is still the best solution, here.

**Comment by renjums** [comment]
I see the package is available as stable in Nuget. https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0 

Is this thread still open ?

**Comment by mattchenderson** [comment]
We wanted to wait for the [Azure Update](https://azure.microsoft.com/en-us/updates/generally-available-application-insights-integration-for-the-azure-functions-net-worker/). But yes, now closeable.

**Comment by p-m-j** [comment]
There's a note on [This page](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2)

> When custom application logs are sent directly, the host no longer be emits them, and host.json no longer controls their behavior

To what extent is this true?

Without additional values in host.json I get duplicate entries for worker process log messages i.e.

One with customDimensions.Category = 'Host.Function.Console'
And the other with customDimensions.CategoryName = Fully qualified name of my function
