### ISSUE TITLE
Configure not called in class derived from WorkerExtensionStartup

### ISSUE THREAD

**Issue by ruwentos** [Azure/azure-functions-dotnet-worker#1270]
I have the same problem as described in https://github.com/Azure/azure-functions-dotnet-worker/issues/818

From the conversations and [here](https://github-wiki-see.page/m/Azure/azure-functions-dotnet-worker/wiki/Extension-startup-hook) I see there is a solution.

I created a class like this:

```
[assembly: WorkerExtensionStartup(typeof(WorkerStartup))]
namespace Rebalance_AF
{
    public class WorkerStartup : WorkerExtensionStartup
    {
        public override void Configure(IFunctionsWorkerApplicationBuilder applicationBuilder)
        {
            var serviceProvider = applicationBuilder.Services.BuildServiceProvider();
            var configuration = serviceProvider.GetRequiredService<IConfiguration>();

            InitializeServiceBusAsync(configuration).Wait();
        }

        private async Task InitializeServiceBusAsync(IConfiguration configuration)
        {
            var azureServiceBusClientFactory = new AzureServiceBusClientFactory();
            var serviceBusClientFactory = new ServiceBusClientFactory(azureServiceBusClientFactory);

            var requestTopic = configuration["RequestTopic"];
            var requestSubscription = configuration["RequestSubscription"];
            var responseTopic = configuration["ResponseTopic"];

            var serviceBusConnection = configuration["ServiceBusConnection"];
            await serviceBusClientFactory.CreateTopicSubscriptionIfNotExistAsync(serviceBusConnection, requestTopic, requestSubscription);
            await serviceBusClientFactory.CreateTopicIfNotExistAsync(serviceBusConnection, responseTopic);
        }
    }
}
```

Unfortunately the Configure function gets never called.
What do I miss here?

I use a 'dotnet-isolated' implementation with the latest available stable packages (no previews). 

Thanks in advance

S.

**Comment by kshyju** [comment]
From the [wiki page](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Extension-startup-hook)

> _The dotnet-isolated worker programming model supports the ability for **worker extensions to participate in the startup** routine of the function application, thus enabling extension authors to register additional services relevant to the extension._

This hook is meant for [worker extensions](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/extensions), not for your isolated function app startup.

If you prefer to do some checks and create service bus topic, if not exist,  I suggest you do that as part of your deployment pipeline. So the resources your function app will be created before the function app starts up.

Hope that helps. Let us know if you still have questions.

**Comment by ruwentos** [comment]
Thank you for your answer. I understand.
Although I must notice that this [wiki page](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Extension-startup-hook) is highly misleading. Factual it says what I did.

Are there any plans to fix this inconvenience in the near future?

**Comment by kshyju** [comment]
> Thank you for your answer. I understand. Although I must notice that this [wiki page](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Extension-startup-hook) is highly misleading. Factual it says what I did.
> 
> Are there any plans to fix this inconvenience in the near future?

@ruwentos Would you mind pointing out specific part of the wiki which is confusing and if you have a proposed draft of the more clear version of the text, please share that. Thank you!
