### ISSUE TITLE
Analyzer to check if a blob container is not binding to an iterable type parameter

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#1276]
Create an analyzer for the scenario where a function app has a Blob input binding to a container but parameter is of string type (and not array type). I have shared the error we get currently. However, ideally we can have an Analyzer giving compile time error if a Blob Container does not bind to an array type - ex:  `IEnumerable<string>`

Function -

```csharp
  [FunctionName("Function1")]
  public async Task<HttpResponseMessage> Run(
      [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestMessage req,
      [Blob("blob-container", FileAccess.Read, Connection = "AzureWebJobsStorage")] string blob,
      ILogger log)
  {
      log.LogInformation($"C# Blob trigger function Processed blob {blob}");
      var response = req.CreateResponse(HttpStatusCode.OK);
      return response;
  }
```

Csproj -

```csharp
<TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.14.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
```

Error -

![image](https://user-images.githubusercontent.com/16623184/213024082-c7bda907-4f24-4a1c-9a83-ce68d446d28e.png)

Correct Function should be -

```csharp
  [FunctionName("Function1")]
  public async Task<HttpResponseMessage> Run(
      [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestMessage req,
      [Blob("blob-container", FileAccess.Read, Connection = "AzureWebJobsStorage")] IEnumerable<string> blobs,
      ILogger log)
```

Related -

1. [FunctionMetadataGenerator](https://github.com/Azure/azure-functions-dotnet-worker/blob/7b0860ade7ec3ac362e3e80cfe16fb36d67afac1/sdk/Sdk/FunctionMetadataGenerator.cs#L561) has a check for iterable type but it would be good to have an analyzer as well.

**Comment by gpikmddk** [comment]
Hello,

the unfortunate behavior in this case is when someone uses variables.
I.e. in our scenario after upgrading, we see bunch of analyzer errors, just because we use something like
BlobInput("%XXXXXXXBlobName%"...). 
In the settings %XXXXXXXBlobName% maps to "SomeContainer/SomeBlob" so it works fine.

Of course we can now split the variables into two, but this is a lot of work for us.
We can also use #pragma warning disable AZFW0011

Regards
