### ISSUE TITLE
Why am I able to use EventGridEvent in isolated Azure Functions?

### ISSUE THREAD

**Issue by elias-rod** [Azure/azure-functions-dotnet-worker#1285]
I'm able to execute an EventGrid triggered Azure Function in isolated mode using EventGridEvent such as:

```
[Function(nameof(PocEventGridTriggerAsync))]
public static async Task PocEventGridTriggerAsync(
    [EventGridTrigger] EventGridEvent eventGridEvent,
    FunctionContext executionContext)
```

But in the official documentation it gives [an example](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=isolated-process%2Cextensionv3&pivots=programming-language-csharp#example) and also [states](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#:%7E:text=Because%20.NET%20isolated%20projects,old%20class%20objects%20(POCOs).) that:

_Because .NET isolated projects run in a separate worker process, bindings can't take advantage of rich binding classes, such as ICollector, IAsyncCollector, and CloudBlockBlob. There's also no direct support for types inherited from underlying service SDKs, such as DocumentClient and BrokeredMessage. Instead, bindings rely on strings, arrays, and serializable types, such as plain old class objects (POCOs)._

Am I missing something?

**Comment by fabiocav** [comment]
@elias-rod in this case, `EventGridEvent` is simply treated as a POCO and the event payload is deserialized, so that type is supported.

Closing this as answered but please let us know if you have any additional questions.
