### ISSUE TITLE
How can an `ITelemetryInitializer` access the `Identities` of the current `HttpRequestData`?

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-functions-dotnet-worker#1288]
Hello, in ASP.NetCore, in order to enrich the telemetry with some information about the current caller, one can inject the `IHttpContextAccessor` in the telemetry initializer contructor.

Is there a similar helper in the world of azure function/isolated worker?

**Comment by fabiocav** [comment]
We're flagging https://github.com/Azure/azure-functions-dotnet-worker/issues/950 for discussion, so will close this in favor of that issue, but please let us know if you have any additional questions.
