### ISSUE TITLE
.NET Framework - Azure portal Stack API validation

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1290]
.NET Framework - Azure portal enabled but we need an E2E validation to ensure it's customer ready : 

- [ ] 1. Azure portal Creation flow ( .NET Framework  )
- [ ] 2. VS Publish to the function app 
- [ ] 3. Portal Monitoring 

I tested it's working for me on all 3 scenarios

**Comment by fabiocav** [comment]
@cloudmelon has context on the flow to enable the feature for testing.

**Comment by fabiocav** [comment]
Closing this as completed.
