### ISSUE TITLE
Example how to connect to BlobContainer using isolated function

### ISSUE THREAD

**Issue by pmeems** [Azure/azure-functions-dotnet-worker#1291]
I'm currently migrating my .NET6 in-proc functions to .NET7 isolated functions.
Most functions are working except for my HttpTrigger function.
This function will return a pdf-file from the blob storage, but before requesting the blob I need to validate the input filename (basically making it upper-case, because the blobs are all upper-case).

With the in-proc version, I used a binding to the BlobClientContainer:
`[Blob("%BlobContainerName%")] BlobContainerClient blobContainerClient` and then I could upload and download the needed file.
But this is not allowed in the isolated function eg BlobInput, because I need to add the full path:
`[BlobInput("%BlobContainerName%/{foo}.txt", Connection = "AzureWebJobsStorage")] string myBlob`

It would be nice if a sample would be added to showcase how to manipulate the blobpath in a HttpTrigger before fetching it.

**Comment by fabiocav** [comment]
We're nearing the public preview of the SDK type binding feature tracked by https://github.com/Azure/azure-functions-dotnet-worker/issues/1081, which will provide parity with the model you had in-proc. If this is something you can wait for, you wouldn't need to modify your code to handle this scenario.

**Comment by pmeems** [comment]
Thanks for letting me know. We already stopped converting to an Isolated function because it is so much work. We're sticking with .NET6 In-Proc for now.
So we will wait for the updated SDK and try again.
