### ISSUE TITLE
Application Insight in isolated Function app

### ISSUE THREAD

**Issue by MianNajmi** [Azure/azure-functions-dotnet-worker#1293]
I am facing issue in moving my function app code from in process to isolated process. Here is my application insight code which i am using in my startup.cs. i am not using APPINSIGHTS_INSTRUMENTATIONKEY configuration.

class Startup : FunctionsStartup
{
public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
{
    builder.ConfigurationBuilder.AddApplicationInsightsSettings(applicationInsightsInstrumentationConectionstring);
 }
public override void Configure(IFunctionsHostBuilder builder)
{
    builder.Services.AddApplicationInsightsTelemetry();

}
}
Now i want to move it to program.cs for function app isolated process. i have tried different ways but it is not writing logs to application insight.

**Comment by MianNajmi** [comment]
.ConfigureServices(services =>
                {

                   services.AddApplicationInsightsTelemetryWorkerService(opt =>
                    {
                        opt.ConnectionString = applicationInsightsConectionString;
                        opt.DependencyCollectionOptions.EnableLegacyCorrelationHeadersInjection = true;
                    });


                })

**Comment by jviau** [comment]
@MianNajmi we have a preview package for using app insights in the dotnet isolated worker. See https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627
