### ISSUE TITLE
EventHubTrigger cannot insert "_" character in parameter

### ISSUE THREAD

**Issue by Giampli** [Azure/azure-functions-dotnet-worker#1296]
I tried to upgrade a FunctionApp from nertcore 2 function version 3 to .net 6 function version 4.
I noticed that every EventHubTrigger was not working after the upgrade. This was the function definition:

```
[FunctionName("name")]
public static async Task Run
(
    [EventHubTrigger("events", Connection = "Hub")] string msg,
    [Queue("events", Connection = "Storage")] QueueClient output_err,
    [EventHub("events2", Connection = "Hub")] IAsyncCollector<Obj> output_queue,
    ILogger log
)
{
}
```
There was no error but the application refused to intercept any event.
After some tinkering i notice that adding a trigger on a different EventHub without parameter will make the function Run usable again, here's an example:

```
[FunctionName("foo")]
public static async Task Bar ([EventHubTrigger("events2", Connection = "Hub")] string msg)
{
}        

[FunctionName("name")]
public static async Task Run
(
    [EventHubTrigger("events", Connection = "Hub")] string msg,
    [Queue("events", Connection = "Storage")] QueueClient output_err,
    [EventHub("events2", Connection = "Hub")] IAsyncCollector<Obj> output_queue,
    ILogger log
)
{
}
```

I continued working on it and after a while i found a way to resolve it: remove any "_" character from the parameter with an attribute. Everything started working again. Here's an example:

```
[FunctionName("name")]
public static async Task Run
(
    [EventHubTrigger("events", Connection = "Hub")] string msg,
    [Queue("events", Connection = "Storage")] QueueClient outputErr,
    [EventHub("events2", Connection = "Hub")] IAsyncCollector<Obj> outputQueue,
    ILogger log
)
{
}
```

**Comment by kshyju** [comment]
FYI: The code you shared above does not look like isolated function code. `FunctionName` attribute and `IAsyncCollector` type are used in the in-proc model.

https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences
