### ISSUE TITLE
Cosmos db extension version 4.0.0 missing few public types

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1297]
Latest cosmos db worker package is missing a few public types exposed by the web-jobs version.

1. ICosmosDBSerializerFactory

**Comment by ealsur** [comment]
StartFromTime is the wrong type, it should be a string. Reference: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs#L123

**Comment by kshyju** [comment]
Closing as `ICosmosDBSerializerFactory` is something we cannot support from the worker extension side today. Fixing the incorrect type in 1298
