### ISSUE TITLE
Functions v4 isolated - Application Insights dependency tracking cannot be disabled / sampling not working

### ISSUE THREAD

**Issue by Done3319** [Azure/azure-functions-dotnet-worker#1304]
Application Insights on v4 isolated functions works great after setting it up as described [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1317230604)

The only issue I'm facing is that it seems to be impossible to disable dependency tracking. Sampling options on dependency tracking seem to be ignored as well.

Removing .AddApplicationInsights() from the .ConfigureFunctionsWorkerDefaults seems to be the only way how to stop it (but has some other impact, in particular breaks logging).

host.json / appsetting.json:

```
{
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond": 0.1,
        "excludedTypes": "Exception;Trace"
      },
      "enableDependencyTracking": false,
      "logLevel": {
        "default": "Warning",
        "Azure": "Warning",
        "Function": "Warning",
        "Host": "Information",
        "Microsoft": "Warning"
      }
:
:
```

**Comment by brettsam** [comment]
The settings above are for the *host* -- you're able to fully control every aspect of App Insights from the *worker* by configuring the options however you'd like:

```csharp
funcBuilder
    .AddApplicationInsights(appInsightsOptions =>
    {
        appInsightsOptions.EnableDependencyTrackingTelemetryModule = false;
    });

```

**Comment by Done3319** [comment]
> The settings above are for the _host_ -- you're able to fully control every aspect of App Insights from the _worker_ by configuring the options however you'd like:
> 
> ```cs
> funcBuilder
>     .AddApplicationInsights(appInsightsOptions =>
>     {
>         appInsightsOptions.EnableDependencyTrackingTelemetryModule = false;
>     });
> ```

Already tried this - it is ignored as well.

My appsettings.json in general works fine for any other **worker** setting. Explicitly added it by

```cs
.ConfigureAppConfiguration(c =>
    c.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
```

Basically everything that has to do with DependencyTracking seems to be ignored. All other settings apply as expected.

**Comment by brettsam** [comment]
Do you have an example of a Dependency that is showing up that you want to disable? We're just passing those options to the App Insights SDK so I want to see if there's some gap there.

**Comment by Done3319** [comment]
Sure, here we go:

![ai_detracking02](https://user-images.githubusercontent.com/83369160/216150798-8051807a-3e6d-4697-8e35-fe9741cd3078.png)

This is the usage statistics of Application Insights with the changes on the configuration:

![ai_detracking01](https://user-images.githubusercontent.com/83369160/216150988-9d0f5eda-a6f3-4643-ab7d-42454e138b30.png)

(Just let me know in case you prefer a support case or you need a correlation ID)

**Comment by brettsam** [comment]
I just tested this myself and it seemed to prevent DependencyTracking from the worker as expected...

Can you share the `sdkVersion` of that Dependency telemetry above?

And also can you share what you've got in your Program.cs for wiring this up?

**Comment by Done3319** [comment]
SDK version in the above log entry:
`sdkVersion xxxxx-netiso: 1.0.0.0`

Nuget:
Microsoft.Azure.Functions.Worker.Sdk 1.7.0
Microsoft.Azure.Functions.Worker 1.10.0
Microsoft.Azure.Functions.Worker.ApplicationInsights 1.1.0-preview3

Program.cs:
```cs
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace xx
{
    public class Program
    {
        public static Task Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults(builder =>
                {
                        builder
                        //.AddApplicationInsights(o => { o.EnableDependencyTrackingTelemetryModule = false; })
                        .AddApplicationInsightsLogger();

                })
                .ConfigureAppConfiguration(c =>
                {
                    c.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
                    c.AddJsonFile("local.settings.json", optional: true, reloadOnChange: true);
                    c.AddEnvironmentVariables();
                    c.Build();
                })
                .ConfigureServices((buildercontext, services) =>
                {
                    services.AddScoped<TableService>();
                    services.AddScoped<BlobService>();
                    services.Configure<LoggerFilterOptions>(options =>
                    {
                        LoggerFilterRule toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName
                            == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");

                        if (toRemove is not null)
                        {
                            options.Rules.Remove(toRemove);
                        }
                    });
                    
                }).ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                })
                .Build();

            return host.RunAsync();
        }
    }
}
```

**Comment by brettsam** [comment]
Ultimately, we're calling `AddApplicationInsightsTelemetryWorkerService()` with your options. Everything else happens inside the App Insights SDK.

https://github.com/Azure/azure-functions-dotnet-worker/blob/651e9adbf599cbe469b6569df2213ce33ca1f85e/src/DotNetWorker.ApplicationInsights/FunctionsApplicationInsightsExtensions.cs#L29-L32

The way App Insights turns off DependencyTracking is by either skipping the setup here:
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L374

Or disposing that module during startup here:
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Implementation/TelemetryConfigurationOptionsSetup.cs#L171-L175

It does look like settings from IConfiguration could influence this as well -- which is the difference between our repros.
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L240-L241

Some debugging thoughts:
- Can you try removing your different config setups to see if one of those could be influencing the behavior?
- Can you paste a (redacted) appsettings.json and local.settings.json here for me to test? I am set up to step right into that code to see why something may not be working.
- You can try running something like this -- see if something somewhere is flipping that setting on you:

```csharp
.ConfigureServices(services =>
{
    services.PostConfigure<ApplicationInsightsServiceOptions>(o =>
    {
        // set breakpoint and check value of o.EnableDependencyTrackingTelemetryModule
    });
})
```

**Comment by Done3319** [comment]
Followed your advice and started the troubleshooting steps you mentioned. At the end it turned out that there was an old reference to Microsoft.Extensions.Logging.ApplicationInsights version 2.22.0-beta1 in the project. After removing this, the dependency logging works as expected now.

There are still some dependencies logged ("Invoke" of type "Azure.Functions"), but this acceptable.

Many thanks for your great help on this, @brettsam!

**Comment by brettsam** [comment]
Glad you got it figured out!
