### ISSUE TITLE
TableOutput fails with Microsoft.Azure.WebJobs.Extensions.Tables: '' is not a valid value for a partition key or row key.

### ISSUE THREAD

**Issue by PBeckerr** [Azure/azure-functions-dotnet-worker#1305]
**.NET6**

Projectes uses
```
<PackageReference Include="Azure.Data.Tables" Version="12.7.1" />       
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.0.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Tables" Version="1.0.0" />
```

```
public class MemberInventorySave : Azure.Data.Tables.ITableEntity
{
    public string MemberInventoryJson { get; set; }

    public Guid TenantId { get; set; }
    public Guid MemberInventoryYearlySetupId { get; set; }
    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }
}

public class HTTP_CreateNewMemberInventorySave :  BaseFunction
{
    [Function("HTTP_CreateNewMemberInventorySave")]
    [TableOutput("MemberInventory", Connection = "AzureWebJobsStorage")]
    public static async Task<MemberInventorySave> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "association/{tenantid:guid}/analytics/memberinventory/save")] HttpRequestData req,
        FunctionContext executionContext, string tenantid)
    {
        var body = await req.GetModelAsync<MemberInventory>();
        var memberInventorySave = new MemberInventorySave
        {
            PartitionKey = body.MemberInventoryYearlySetupId.GetValueOrDefault().ToString(),
            RowKey = Guid.NewGuid().ToString(),
            MemberInventoryJson = JsonConvert.SerializeObject(body, GlobalDefaults.JsonSerializerSettings),
            MemberInventoryYearlySetupId = body.MemberInventoryYearlySetupId.GetValueOrDefault(),
            TenantId = Guid.Parse(tenantid),
        };
        return memberInventorySave;
    }

    public HTTP_CreateNewMemberInventorySave(IMediator mediator, IMapper mapper) : base(mediator, mapper)
    {
    }
}
```

Functions fails with `System.Private.CoreLib: Exception while executing function: Functions.HTTP_CreateNewMemberInventorySave. Microsoft.Azure.WebJobs.Extensions.Tables: '' is not a valid value for a partition key or row key.`

Row/PartionKey are not empty
![image](https://user-images.githubusercontent.com/13576643/215833327-bb071067-e0d7-4e51-8e0c-f264f98ecc93.png)

**Comment by fabiocav** [comment]
@kshyju has been looking at this and, although we have a valid repro with the .NET worker, we need to take a closer look at the behavior with the other OOP languages to see if there's a difference.

In the meantime, the issue https://github.com/Azure/azure-sdk-for-net/issues/33902 was also opened in the extension repo for investigation.

**Comment by marcelmedina** [comment]
+1 same issue with me

**Comment by kshyju** [comment]
@gavin-aguiar is validating this behavior in python out-of-process function apps & will share an update here. Thanks Gavin.

**Comment by gavin-aguiar** [comment]
Python function fails with the same error.

![image](https://user-images.githubusercontent.com/80794152/218883585-6cbfc957-6600-4558-9c14-d54fb9117a15.png)


Table extension: 
\<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Tables" Version="1.0.0" \>

**Comment by fabiocav** [comment]
Closing this in favor of https://github.com/Azure/azure-sdk-for-net/issues/33902
