### ISSUE TITLE
Is it supported to add custom ITelemetryInitializers in Isolated Azure Func(v4)?

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-functions-dotnet-worker#1312]
Adding telemetry initializers into isolated v4 AZF doesn't seem to work:

```csharp
            IHostBuilder host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(services =>{
                    services.AddSingleton<ITelemetryInitializer, MyInit>();  // MyInit doesn't seem work
                });
            IHost app = host.Build();
            app.Run();
```
What is the correct way to register ITelemetryInitializers for all Azure Function Telemetries? Or is it not supported? How about it in ClassLib mode?

**Comment by brettsam** [comment]
This is supported if you're using the preview of the isolated worker App Insights support: https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627.

However, note that logs emitted by Functions include those from two processes: the Functions host and the isolated worker. And any customizations added to the worker will only apply to the worker and not to those logs emitted by the host.

**Comment by xiaomi7732** [comment]
Hey @brettsam, thanks for pointing me in the right direction. I don't fully understand logs emitted by the workers or by the host.  I tried the package, and here's what I saw:

```csharp
        [Function("Func1")]
        public HttpResponseData Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
        {
            using (IOperationHolder<RequestTelemetry> operation = _telemetryClient.StartOperation<RequestTelemetry>("Func1Request"))
            {
                try
                {
                    // Warning will be sent to application insights.
                    _logger.LogWarning("This is a warning!");

                    // Other code
                }
                catch
                {
                    operation.Telemetry.Success = false;
                    throw;
                }
            }
        }
```

Do I understand the situation correctly?

1. The telemetry for the Function named `Func1` would not have any telemetry initializer (emitted by host?), right?
2. The telemetry for the manually authored operation of FuncRequest will have the telemetry initializers applied - worker?
3. The warning out of ILogger would have the telemetry initializers applied - worker,

**Comment by nulltoken** [comment]
@xiaomi7732 https://github.com/Azure/azure-functions-dotnet-worker/issues/1292#issuecomment-1419473909 might provide additional insights

**Comment by fabiocav** [comment]
@brettsam moving this to sprint 141, but please feel free to change if not appropriate.

**Comment by jviau** [comment]
@xiaomi7732 in your sample, that is all code in the _worker_ process - so yes your telemetry initializer will apply to those items. However, in dotnet isolated there is another process, the "host" process, which also emits telemetry items. The host process is what controls the lifetime of your worker and dispatches function invocations to it. It is telemetry items coming from the **host** process which your telemetry initializers will **not** affect.

You will need to follow @brettsam's link for sample code on how to setup AppInsights on the worker.

> The telemetry for the Function named Func1 would not have any telemetry initializer (emitted by host?), right?

This is fairly broad. But yes, there will be several telemetry items which apply to `Func1` which originate from the host, and so the initializer does not apply.

> The telemetry for the manually authored operation of FuncRequest will have the telemetry initializers applied - worker?

Correct

> The warning out of ILogger would have the telemetry initializers applied - worker,

Correct

**Comment by xiaomi7732** [comment]
That makes sense. Thank you.
