### ISSUE TITLE
Cannot remove Function1 Endpoint

### ISSUE THREAD

**Issue by markjamesm** [Azure/azure-functions-dotnet-worker#1314]
I have created two Azure Isolated Process .NET 7 HttpTrigger functions, CreateSalesforceAccount() and CreateSalesforceLead():

<img width="706" alt="AzEndpoints" src="https://user-images.githubusercontent.com/20845425/217089480-f85a3b4e-09fb-4e1c-b675-9cf8964a1f60.png">

Both endpoints are working as expected. However, when I build the project, the following functions are listed:

`Functions:

        CreatesalesforceAccount: [POST] http://localhost:7180/api/CreatesalesforceAccount

        CreatesalesforceLead: [POST] http://localhost:7180/api/CreatesalesforceLead

        Function1: [GET,POST] http://localhost:7180/api/Function1`
        
I want to remove Function1, but nowhere is Function1 defined in my codebase (I tried searching the entire solution). When I initially created the project, I selected Azure Function from the Visual Studio templates list. The boilerplate code container a Function1, but I renamed it. Building the project afterwards, I saw both the Function1 endpoint as well as my new name (instead of just the new name). 

Attempting to remove one of the functions works, but Function1 remains:

`Functions:

        CreatesalesforceLead: [POST] http://localhost:7180/api/CreatesalesforceLead

        Function1: [GET,POST] http://localhost:7180/api/Function1`

**Comment by fabiocav** [comment]
@markjamesm interesting. We have not seen this reported before, so we'd love to take a look at your project if that is something you can share in a repo.

Have you tried completely cleaning the build output and rebuilding to see if the issue persists?

Thanks!

**Comment by markjamesm** [comment]
@fabiocav cleaning the build output and rebuilding resolved the issue, Function1 no longer appears as an endpoint. Thank you for the solution, I'm closing the issue now.
