### ISSUE TITLE
StartupHook is preventing launching of child .NET processes

### ISSUE THREAD

**Issue by NCarlsonMSFT** [Azure/azure-functions-dotnet-worker#1318]
Similar to the issue with Hot Reload (https://github.com/dotnet/runtime/issues/58000) when [StarHostAction](https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs) in the Azure Functions CLI sets DOTNET_STARTUP_HOOKS it should be cleared in [StartupHook](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/StartupHook.cs) to prevent all child processes from inheriting the environment variable and failing to run.

This is currently blocking the ability to use the [VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocredential?view=azure-dotnet) from [Azure.Identity](https://www.nuget.org/packages/Azure.Identity) in some scenarios as it relies on starting a child process.

**Comment by fabiocav** [comment]
Thanks @NCarlsonMSFT . This is reasonable and we'll have this reviewed. 

In the meantime, you can workaround the issue by clearing that startup hook reference in debugging scenarios (or always, if you always want to suppress that behavior)

**Comment by jsheetzmt** [comment]
Also interested in this as we are trying to use VisualStudioCredential for AAD authentication with isolated functions + Docker containers

**Comment by NCarlsonMSFT** [comment]
@jsheetzmt: I've updated my sample to include an Isolated Azure function with a work-around for this bug: https://github.com/NCarlsonMSFT/VisualStudioCredentialExample/blob/master/FunctionAppIsolated/Program.cs

**Comment by jsheetzmt** [comment]
Thanks @NCarlsonMSFT, that did the trick :)

**Comment by fabiocav** [comment]
Adding context to the issue on the file that would need to be modified to handle this: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/StartupHook.cs
