### ISSUE TITLE
Multiple transitive security vulnerabilities

### ISSUE THREAD

**Issue by bteamsoftware** [Azure/azure-functions-dotnet-worker#1321]
**Describe the issue**
One project I am working on for a client has recently undergone penetration testing. One result of this pen testing revealed several microservices have security vulnerabilities due to transitive NuGet packages. This is easy to verify using a simple CLI command.

**To Reproduce**
1. Checkout the source from the repo
2. Build the solution
3. Execute the following command line from the local directory : dotnet list package --vulnerable --include-transitive --source https://api.nuget.org/v3/index.json
4. The dotnet CLI will output a list of transitive NuGet packages that have security vulnerabilities.

**Expected behavior**
The result of the dotnet CLI command should result in zero security vulnerabilities

**Screenshots**
![Screenshot 2023-02-07 143109](https://user-images.githubusercontent.com/50671522/217358434-a78b8789-ecd0-4f27-b46f-ed65037a2767.png)

![Screenshot 2023-02-07 143132](https://user-images.githubusercontent.com/50671522/217358483-4130d15f-ab71-40f2-878d-92c3155424f9.png)

![Screenshot 2023-02-07 143154](https://user-images.githubusercontent.com/50671522/217358507-159c5c6b-6aec-494f-9d30-4e8086a12a2c.png)

**Comment by surgupta-msft** [comment]
@mattchenderson I reran the repro steps mentioned above and still see those vulnerabilities in output. Do you know whom can we reach out for this?

**Comment by fabiocav** [comment]
Removing security related report.

All issues have been addressed. For guidance on how to report similar issues in the future, please see https://github.com/Azure/azure-functions-dotnet-worker/security/policy

Thank you.
