### ISSUE TITLE
[SourceGen] Cleanup diagnostic descriptors 

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1323]
Cleanup FunctionMetadata generation related diagnostic descriptors and add more tests similar to [this startup extension test](https://github.com/Azure/azure-functions-dotnet-worker/blob/172a1101b5f5940b2a479907c08c8da3c33a496d/test/Sdk.Generator.Tests/ExtensionStartupRunnerGeneratorTests.cs#L170). 

Diagnostic descriptor messages are currently lengthy and difficult to test. 

Items:

- [ ] Clean up source gen descriptors
- [ ] Re-enable `MultipleOutputOnMethodFails` test

**Comment by fabiocav** [comment]
@liliankasem / @satvu have the context on this issue.
