### ISSUE TITLE
Middleware-scoped service dependency issue

### ISSUE THREAD

**Issue by siddhario** [Azure/azure-functions-dotnet-worker#1327]
@fabiocav @brettsam 

I can confirm that this [issue ](https://github.com/Azure/azure-functions-host/issues/5098) is present in v4 (dotnet-isolated) worker,
and as mentioned already [here](https://github.com/Azure/azure-functions-host/issues/5098#issuecomment-554398405),
it occurs in cold start scenarios.

TargetFramework: net6.0
AzureFunctionsVersion: v4
Microsoft.Azure.Functions.Worker  version: 1.6.0

Scenario:

1.  Service is added as scoped service in function Startup 
  ```
        public static void Configure(IServiceCollection service)
        {  
            service.AddScoped<IScopedService, ScopedServiceImpl>();  
        }
  ```

3.  In the middleware, service is explicitly, per-request, resolved in the Invoke method:
 
   ```
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            _scopedService = context.InstanceServices.GetRequiredService<IScopedService>();
           /*
           */configuring the instance properties based on request headers values
           */         
        } 
   ```

4.  Service is later resolved as constructor dependency:
   ```
       public SomeClass(IScopedService scopedService)
       {
          //in some occurrences, scopedService instance properties are not configured, 
          //as if new instance was used instead of the one configured in the middleware.
       }
   ```

We were able to reproduce the issue by running automated API tests.
For example, issue occurs on the first invocation in the morning and each subsequent request is processed correctly.

Is this potentially resolved in the newer versions of Microsoft.Azure.Functions.Worker ?

P.S.

In one occurrence of this issue, scoped service is injected directly into Azure Function, in other is injected into other scoped service.

**Comment by kshyju** [comment]
@siddhario What is the lifetime of `SomeClass`? Is it registered as a singleton?

**Comment by siddhario** [comment]
In one occurrance of this issue, that class is registered as scoped, in other, it is injected directly into Azure Function.
It is used in many other places in the project, but singleton instances are avoided in general.

**Comment by kshyju** [comment]
> In one occurrance of this issue, that class is registered as scoped, in other, it is injected directly into Azure Function. It is used in many other places in the project, but singleton instances are avoided in general.

Could you update the original post to include that information. That will help future readers. Thanks!

**Comment by siddhario** [comment]
This code sample addresses the case. The only difference was in the version Microsoft.Azure.Functions.Worker (1.6.0<>1.10.0).
We tried with updating the package to the latest, but it didn't help.
In addition, we were able to reproduce issue only in Azure environment, not in debug mode.

**Comment by kshyju** [comment]
@siddhario Can you share a minimal repro with us (you can fork the repo I shared above as needed) so that we can take a closer look ?

**Comment by siddhario** [comment]
@kshyju 
Eventually, I reproduced the issue in debug mode.
Exact scenario includes sending multiple requests at the same time. 
I introduced instance GUID identifiers similar to your code samples and logged them in both middleware and the function.

I.E. 6 requests were sent:
The logs showed that in all 6 invocations, instances had the same identifier in the middleware.
Inside the function, in 1 invocation that exact instance was used, in remaining 5, new instances were created (not processed in the middleware).

Then I took sample scoped service and middleware you provided and added them to the project.
Logs then showed that new instance were created on each middleware invocation and used accordingly inside the function.

Comparing the implementations, I noticed that there was a difference in our middleware:
Instead of declaring scoped service in the Invoke method,

```
 public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
 { 
     var scopedService = context.InstanceServices.GetRequiredService<IIdentityProvider>(); 
     ....
 }
```

service was declared as the field in the middleware:

```
public class MyMiddleware : IFunctionsWorkerMiddleware
{
     private IScopedService _scopedService;

     public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
     {
         _scopedService = context.InstanceServices.GetRequiredService<IScopedService>();
          ...
     } 
}
```

After aligning this code to the sample one, no issue was present.

**Comment by kshyju** [comment]
Awesome ✨. Feel free to reach out if you run into issues again with the isolated model.

**Comment by Misiu** [comment]
@kshyju is this documented somewhere? It should be as I saw multiple issues with the DI.
I noticed this PR: https://github.com/MicrosoftDocs/azure-docs/pull/88827 but it got closed because:

> We are in the process of revising and expanding our DI guidance for isolated worker process. I'll make sure we get this info into the updated article. We're tracking this work internally [here](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60036).

I had an issue when using typed HttpClient inside Middleware and Function (in Middleware I was calling external service to "log in" the user and set cookies so that in function I always get that HttpClient with cookies already set).
My workaround, for now, is setting cookies as FunctionContext.Items and then getting them in function invocation and setting them to the new HttpClient.

I'll try to modify my code with the changes you suggested and hopefully, this will remove the problem.

**Comment by Misiu** [comment]
Sadly this approach isn't working when using with typed HTTP client.
I'm adding the client using:
```
services
    .AddHttpClient<ITestClient, TestClient>()
    .SetHandlerLifetime(TimeSpan.FromMinutes(5))
    .AddPolicyHandler(GetRetryPolicy());
```

and then getting it inside my middleware and my function using:
```
var testClient = context.InstanceServices.GetRequiredService<ITestClient>();
```
