### ISSUE TITLE
[SDK Binding - Blob] Improve error logging when deserialization fails for POCO scenarios

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1329]
If you bind to a POCO i.e.

`[BlobInput("book-container", IsBatched = true)] Book[] books)`

The format of the blob needs to be json, for example:

book.json -> `{ "id": "1", "name": "mybook" }`

If you don't do that and use a blob with string content, the deserialization will fail with an error that looks like this:

```log
Executed 'Functions.BlobInputBookArrayFunction' (Failed, Id=501b3023-ee56-41f4-a99d-332bba664544, Duration=66ms)

[2023-02-09T21:45:01.210Z] System.Private.CoreLib: Exception while executing function: Functions.BlobInputBookArrayFunction. System.Private.CoreLib: Result: Failure

[2023-02-09T21:45:01.210Z] Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobInputBookArrayFunction': Cannot convert input parameter 'books' to type 'SampleApp.Book[]' from type 

'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcCollectionModelBindingData'. Error:System.Text.Json.JsonException: 'h' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```

We should consider improving the logging here. This exception is currently caught in our try-catch so this would be a good place to display a better error message:

https://github.com/Azure/azure-functions-dotnet-worker/blob/f6cf04adfcac6af3c822d1e950cc071594373db5/extensions/Worker.Extensions.Storage.Blobs/src/BlobStorageConverter.cs#L87-L103

**Comment by fabiocav** [comment]
Flagging to investigate what, if any, enhancements we can make to this.

**Comment by fabiocav** [comment]
Assigning to sprint 148 for validation

**Comment by aishwaryabh** [comment]
This error still repros, so I'll create a fix for displaying a better display message.
