### ISSUE TITLE
Complete and abandon manually service bus messages in isolated worker process

### ISSUE THREAD

**Issue by NicolayDV** [Azure/azure-functions-dotnet-worker#1332]
I'm currently working on a project that has .NET 6 with a durable function in-process with a Service Bus Trigger and I'm migrating it to .NET 7. To be able to achieve that I also need to migrate the function to isolated worker process.

I'm facing now the issue that I cannot complete or abandon manually the messages of the Service Bus and it's a must for me. I saw that there's an epic to bring some in-process features to isolated ([https://github.com/Azure/azure-functions-dotnet-worker/issues/1008](https://github.com/Azure/azure-functions-dotnet-worker/issues/1008)) but I cannot see the specific item to complete or abandon the messages manual. Any update to when this feature will be available?

_I think can bypass now the issue by throwing an exception to dead-letter the message and re-send again the message to the queue to simulate a retry. But it would be nice to have those features._

**Comment by SeanFeldman** [comment]
This is already discussed in https://github.com/Azure/azure-functions-dotnet-worker/issues/293

**Comment by NicolayDV** [comment]
Thanks! Didn't see that.
