### ISSUE TITLE
[Blob] Design for enabling inference of collection binding without the IsBatched property

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-dotnet-worker#1333]
**Using blob extension as an example:**

We should explore if we can remove the need for the explicit `IsBatched` value in `BlobInputAttribute` and instead infer it on some set of defined rules. This may be possible by both considering the target parameter type as well is if the described blob is a file or not. We will need to explore how this affects binding metadata sent to/from the host.

Examples

| Is File? | Target Type | Result |
| - | - | - |
| true | `IEnumerable<T>`, `Array<T>` | deserialize single file into target type, Behavior of deserialization depends on how the configured serializer performs collection deserialization. |
| true | `T` (not an enumerable or array) | deserialize single file into target type. |
| true | `string`, `Stream`, `byte[]` | blob contents. The check for `byte[]` will need to take precedence over the array check above. |
| true | `BlobClient` | provide `BlobClient` for described blob |
| true | `IEnumerable<BlobClient>` / `Array<BlobClient>` | enumerable/array with single client |
| true | `BlobContainerClient` | error (need to verify this) |
| true | `IEnumerable<BlobContainerClient>` / `Array<BlobContainerClient>` | error (need to verify this) |
| false| `IEnumerable<T>`, `Array<T>` | deserialize single file into target type, Behavior of deserialization depends on how the configured serializer performs collection deserialization. |
| false | `T` (not an enumerable or array) | error |
| false | `string`, `Stream`, `byte[]` | error |
| false | `BlobClient` | provide `BlobClient` for indicated blob (`IsFile` will be `false` - this does work today). |
| false | `IEnumerable<BlobClient>` / `Array<BlobClient>` | enumerable/array with a `BlobClient` per child. |
| false | `BlobContainerClient` | provide `BlobContainerClient` for the indicated blob. |
| false | `IEnumerable<BlobContainerClient>` / `Array<BlobContainerClient>` | enumerable / array with single `BlobContainerClient`. Or error? There is never a case this would yield more than 1. |

**Comment by liliankasem** [comment]
@mattchenderson I'll answer what I know and leave the rest for @jviau :)

> Is it the case that we'd just be removing the need for explicit `isBatched` on the scenarios where it's a container (Is File = false)? For the customer experience with input bindings, it seems redundant. Is there any scenario where I would add isBatched=true in a single blob case?

My understanding is that we are trying to have some parity with in-proc here and remove the need for explicitly setting `IsBatched` where it is possible to do so, and where it makes the most sense. I'm not sure I follow on why you think it is redundant for input bindings? It would be nice to be able to bind to IEnumerable<T> without having to set the IsBatched property, even for input bindings.

I don't think there is a real use case for setting IsBatched for a single blob, but if someone where to bind to a collection i.e.

`[BlobInput("container/blob")] BlobClient[]`

We should infer IsBatched = true, and return an array containing on item.

> Similarly, what would it mean to set isBatched=false in the collection type cases?

This wouldn't be possible, if you are binding to a collection, IsBatched will be true and cannot be false. If a user does provide IsBatched = false intensionally - I would say we fail this with a meaningful error message.

> What does the host need to do differently? It is processing `Path` as well, so it knows if it needs to hand off ParameterBindingData related to a container or related to a single blob. The worker can take container info and map it to `BlobContainerClient` or to any of the collection types.

I'm not sure yet, this is the part we are trying to figure out  (what changes need to happen to enable this)

> Today, `BlobContainerClient` unfortunately requires the file path, as per #1337. I don't think it's wrong to allow, since you're just binding to a broader context (first bullet above), but the _requirement_ certainly needs to go away.

Yeah Aishwaraya and I looked into 1337 a bit today and it looks like the Blob WebJobs extension already has something in place for when the target type is a container (if container, blob name is not required in the path). We just need to figure out the changes we need to make to take advantage of that. We essentially need to pass `isContainerBinding = true` [here](https://github.com/Azure/azure-sdk-for-net/blob/f9bb57eec632f15fd3e93ce26c007794214d8ea4/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/Config/BlobsExtensionConfigProvider.cs#L221-L225) and I'm not sure yet how we do that without some explicit property.

> Where things definitely break down is when you try to move to a narrower context (again for input bindings specifically):
> 
> * Config to get input for a container -> any non-collection single-blob type ( `BlobClient`, `T`, `string`, `Stream`, `byte[]`) feels invalid to me. I don't understand the statement in the original table that says this works today. Maybe I'm missing something. What blob is the type pointed at? This should be an error state.

Do you mean this binding like this?

`[BlobInput("container")] string`

IIRC this does not work today, you can an error saying "must be in the format 'container/blob'"

I've started an [internal design document ](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/OOPWorkers/DotnetIsolated/InferIsBatched.md&version=GBmaster&line=1&_a=preview)for this if you'd like to review and see if it helps answer any other questions.

**Comment by jviau** [comment]
> I don't understand the statement in the original table that says this works today.

It has been a bit since I wrote this, but I _think_ I meant it works with the Azure SDK, not necessarily with our bindings. So, you can get a `BlobClient` for a container.

@liliankasem covered this fairly well. The idea/goal behind this issue is that we _should_ have enough information to infer the correct value of `IsBatched` without the customer ever needing to set it. Between what the SDK reports is at the path described by the binding (is it a file or not?) and what the target type is, we should have everything we need to perform the correct `IsBatched` behavior.

As for the larger discussion of allowing single-value collections anywhere: I am slightly in favor of disallowing _some_ of them, like when trying to bind `IEnumerable<BlobClient>` for a single file or `IEnumerable<BlobContainerClient>` for a container. However, `IEnumerable<T>` for a single file is not the same. This is just an extension of `T` - it means the _contents_ of that file are to be deserialized as a collection. We won't have any special handling here, we will rely on the configured `ObjectSerializer` to deserialize into that collection.

> Config to get input for single file -> BlobContainerClient is fine, if likely not the most useful

So something like `MyFunction([BlobInput("myContainer/myBlob.txt")] BlobContainerClient container)` and `container` will point to `myContainer`? Yes, this is 100% _technically_ possible, and we could have it as well defined behavior. But is it _good_ behavior? You could argue this falls into a form of argument validation. Is it better to fail and let the user know what they are doing doesn't exactly make sense? I am not saying we _have_ to fail, we could go with allowing this. But we shouldn't include something just because it is doable, it should also make sense.

**Comment by liliankasem** [comment]
Just to confirm `MyFunction([BlobInput("myContainer/myBlob.txt")] BlobContainerClient container)` is working today because it's the only we can allow binding to `BlobContainerClient` without 1337. I agree with Jacob here about argument validation - just because we can it doesn't meant we should. It makes more sense for the binding to not require or allow a blobName since it is redundant

**Comment by mattchenderson** [comment]
I wasn't as clear as I could have been, but I think we're all in agreement on that front. My leaning is toward the full denial case (right column of the table I made), which may swing too far. The ObjectSerializer point is a good one that I may need to reason about a bit more, but I think it's still navigable.

`IEnumerable<T>` is distinct from `T: IEnumerable<Foo>` to me, at least in concept. `T` represents the content, but the structure of the input - how many such contents - is something that we can know without inspection of the type. If that can inform the deserialization strategy, then it seems like we should be largely ok. That's the larger point I was trying to make. Config sets the mode for you, no additional inference needed, and that can hopefully inform the cardinality heading into the actual serialization.

When an error is reported could be different across the scenarios. Maybe we can't tell at analyzer time (even an env var binding expression for `Path` creates a problem there), but at runtime the `ObjectSerializer` for the content might just need to fall over. It might be interesting to break out a table of those cases with custom collection types, etc. and capture that end-to-end.

I am still struggling with the notion of a BlobClient not pointing at a blob. I can find no evidence for it. If you have a pointer to an example, that would be clarifying.

**Comment by jviau** [comment]
> I am still struggling with the notion of a BlobClient not pointing at a blob. I can find no evidence for it. If you have a pointer to an example, that would be clarifying.

Tried to find an example, but I have found I was hallucinating the whole thing. A while ago I could have sworn I found that you could navigate virtual file system structures in a container, and there was a property `bool IsFile` on `BlobClient` to tell you if it was a virtual directory, or an actual blob.

You _can_ do this with blobs SDK, just not via `BlobClient`. It is `BlobContainerClient` `GetBlobs` and `GetBlobsByHierarchy`.

**Comment by fabiocav** [comment]
Draft design being reviewed. Moving to 149. 


Implementation items will be opened once review is complete.

**Comment by liliankasem** [comment]
Design for blob complete and implementation in-progress. Design still open for other extensions such as service bus/eventgrid/eventhub. Will close this issue once a decision has been made on those
