### ISSUE TITLE
[SDK Binding - Blob] Binding to BlobContainerClient should not require you to provide a blob path

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1337]
When binding to `BlobContainerClient` as an input binding, you still need to provide a blob name in the input binding i.e.  `BlobInput("input-container/sample1.txt"`

```csharp
[Function(nameof(BlobContainerClientInputFunction))]
public async Task<HttpResponseData> BlobContainerClientInputFunction(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
    [BlobInput("input-container/sample1.txt")] BlobContainerClient client)
```
	
But since we are binding to a container, it doesn't make sense to have to provide a blob name in the binding; instead I would expect that you could bind to just the container like this:

```csharp
[Function(nameof(BlobContainerClientInputFunction))]
public async Task<HttpResponseData> BlobContainerClientInputFunction(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
    [BlobInput("input-container")] BlobContainerClient client)
```

This does not work today and you get the following error message:

`Invalid blob path specified : 'input-container'. Blob identifiers must be in the format 'container/blob'`

> Note: this is different to a blob trigger which lets you bind to just the container, and it is not the same as IsBatched which also lets you bind to only a container but expects a collection binding i.e. BlobContainerClient[] which does not make sense for this scenario

### Proposed Change

1. On the WebJobs extension side we relax the rules to allow input binding with just the container name
2. On the worker side we will have more checks in place to make sure customers do not bind a string/byte[] or anything other than a BlobContainerClient to a container path

**Comment by fabiocav** [comment]
Assigning to @liliankasem for additional context on the change we'll be proposing to the blob extension.

**Comment by aishwaryabh** [comment]
The Blob WebJobs extensions has a property called `isContainerBinding` for determining if the passed in input can be parsed correctly. We basically need to pass in `isContainerBinding = true` [here](https://github.com/Azure/azure-sdk-for-net/blob/f9bb57eec632f15fd3e93ce26c007794214d8ea4/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/Config/BlobsExtensionConfigProvider.cs#L221-L225), and as of today there is no way to do this other than adding a new attribute.
