### ISSUE TITLE
Start-up and configuration doc and code sample improvements

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1339]
Our public documentation offers [a guide for running C# Azure Functions in an isolated worker process](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide).  And we're closing the gaps and tracked some in-progress changes on [Differences between in-process and isolated worker process .NET Azure Functions](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-in-process-differences). 

Start-up and configuration doc and code sample improvements

**Comment by fabiocav** [comment]
@cloudmelon can you please provide more context on the work required?
