### ISSUE TITLE
Expose "trigger_metadata" (binding data)

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#134]
Part of this work includes an E2E HTTP test (`HttpTriggerBindingDataTests`) that will check to verify that binding data has been passed to the function. The function will fail if it doesn't see the properties it expects.

**Comment by fabiocav** [comment]
Comments in the review: https://apiview.dev/Assemblies/Review/af54138c8aa0459c8e91df73dfa71e98

**Comment by brettsam** [comment]
Fixed with #241
