### ISSUE TITLE
Dependency injection doc and code sample improvements

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1340]
Our public documentation offers [a guide for running C# Azure Functions in an isolated worker process](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide).  And we're closing the gaps and tracked some in-progress changes on [Differences between in-process and isolated worker process .NET Azure Functions](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-in-process-differences). 

This item tracks the dependency injection documentation improvements. 

This work is also related to a list of issues on Azure Docs [here](https://github.com/MicrosoftDocs/azure-docs/issues?q=%2215368d1c-b22e-7eb2-413f-cc0d41d2b909%22+is%3Aopen)

**Comment by fabiocav** [comment]
@cloudmelon can you please provide more context on the work required?

**Comment by cloudmelon** [comment]
> @cloudmelon can you please provide more context on the work required?

Provided :)

**Comment by fabiocav** [comment]
The request here is to have someone work with @cloudmelon to review the items she has referenced above and create issues tracking the improvements we want to make to the docs.

**Comment by mattchenderson** [comment]
Closing as some improvements have been made to this topic since this was opened.
