### ISSUE TITLE
HTTP trigger:

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1342]
Our public documentation offers [a guide for running C# Azure Functions in an isolated worker process](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide).  And we're closing the gaps and tracked some in-progress changes on [Differences between in-process and isolated worker process .NET Azure Functions](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-in-process-differences). 

This item is aiming to track the HTTP trigger doc improvements and samples to guide customers.

**Comment by fabiocav** [comment]
Followed up with @cloudmelon . Closing this as there are no concrete HTTP items we're tracking for documentation outside of the ones tied to the HTTP model enhancements we're currently working on.
