### ISSUE TITLE
SDK Type binging documentation - For blob storage existing doc here, and worker binding samples are here

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1344]
Our public documentation offers [a guide for running C# Azure Functions in an isolated worker process](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide).  And we're closing the gaps and tracked some in-progress changes on [Differences between in-process and isolated worker process .NET Azure Functions](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-in-process-differences). 

This item is aiming to track the SDK type binding doc improvements and samples to guide customers.

Adding service limits : https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits

**Comment by fabiocav** [comment]
@cloudmelon can you please provide more information here?

**Comment by cloudmelon** [comment]
Adding service limits : https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits

**Comment by fabiocav** [comment]
Discussed with @cloudmelon , closing this and we'll have other issues opened to track/document service limits.
