### ISSUE TITLE
Not detecting job function when starting the project

### ISSUE THREAD

**Issue by IAMManuel** [Azure/azure-functions-dotnet-worker#1348]
I have an issue where whenever I try to run a function project, it never finds the job function on start. I try to create a new empty project to demonstrate this issue. 

I got this warning message when starting the project: 
` No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for
 the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
`

The project is pretty much from the most basic function.

![image](https://user-images.githubusercontent.com/2425292/218800128-7bca242e-b347-4912-bfda-33b211ce4e61.png)

And the Program.cs
![image](https://user-images.githubusercontent.com/2425292/218800193-b651ee3e-9073-4e94-af07-db7a715e8851.png)

While using `--verbose`, I got no more information to help me debug this issue. I'm running the project on .net7.

**Comment by IAMManuel** [comment]
Sorry for the images.

I deleted the bin and obj folder, still not working.

Here are the content of the `functions.metadata` file :

```
[
  {
    "name": "timer test",
    "scriptFile": "Company.FunctionApp3.dll",
    "entryPoint": "Company.FunctionApp3.TimerTest.Run",
    "language": "dotnet-isolated",
    "properties": {
      "IsCodeless": false
    },
    "bindings": [
      {
        "name": "myTimer",
        "type": "timerTrigger",
        "direction": "In",
        "schedule": "0 */5 * * * *"
      }
    ]
  }
]
```

**Comment by kshyju** [comment]
@IAMManuel Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.
