### ISSUE TITLE
.Net 7 isolated Runtime Issue - Could not load file or assembly Microsoft.Extensions.Configuration, Version=7.0.0.0

### ISSUE THREAD

**Issue by kieseldlds** [Azure/azure-functions-dotnet-worker#1350]
.Net 7 function running isolated. Project file listed below along with screenshots of the function configuration in the Azure portal. I have tried non-beta and beta versions of all packages. 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Platforms>x64</Platforms>
    <Nullable>disable</Nullable>
	  <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>
	<PropertyGroup>
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.15.0-beta.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.13.0-beta.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.13.0-beta.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.12.0-preview1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.9.0-preview1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gossner.Services\Gossner.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

<img width="765" alt="image" src="https://user-images.githubusercontent.com/93405393/218912888-9f50f172-cd74-450d-a4de-d1b0d922e23b.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/93405393/218912993-3389ac85-6747-4433-a577-934ffce1056c.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/93405393/218913267-886f2a21-10fc-4151-bed2-7977f0edcfb6.png">

**Comment by kshyju** [comment]
Do you see the same error when running your app locally?

**Comment by kieseldlds** [comment]
App runs and functions as expected when running locally.

Dennis Kiesel
Systems Architect : ICS

Phone: 801.317.8596
Email: ***@***.***

[SAP PC Seal]

From: Shyju Krishnankutty ***@***.***>
Sent: Tuesday, February 14, 2023 7:49 PM
To: Azure/azure-functions-dotnet-worker ***@***.***>
Cc: Dennis Kiesel ***@***.***>; Author ***@***.***>
Subject: [Ext:] Re: [Azure/azure-functions-dotnet-worker] .Net 7 isolated Runtime Issue - Could not load file or assembly Microsoft.Extensions.Configuration, Version=7.0.0.0 (Issue #1350)

[External Email]

Do you see the same error when running your app locally?

-

**Comment by fabiocav** [comment]
@kieseldlds can you please share the contents of the `extensions.json` file in your build output?

Can you also share your app name so we can take a closer look at the logs here?

Thanks!

**Comment by kieseldlds** [comment]
We have had to revert back to .Net 6 as this issue was holding up production code being released. I apologize for not being able to get you more details. When we get the change to move to .Net 7 again and we see this issue, I will follow up.

Dennis Kiesel
Systems Architect : ICS

Phone: 801.317.8596
Email: ***@***.***

[SAP PC Seal]

From: Fabio Cavalcante ***@***.***>
Sent: Wednesday, February 15, 2023 12:44 PM
To: Azure/azure-functions-dotnet-worker ***@***.***>
Cc: Dennis Kiesel ***@***.***>; Mention ***@***.***>
Subject: [Ext:] Re: [Azure/azure-functions-dotnet-worker] .Net 7 isolated Runtime Issue - Could not load file or assembly Microsoft.Extensions.Configuration, Version=7.0.0.0 (Issue #1350)

[External Email]

@kieseldlds<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkieseldlds&data=05%7C01%7Cdennis.kiesel%40byupathway.org%7Cb8c5d92cdca24312fc6a08db0f8cf98b%7C61e6eeb35fd74aaaae3c61e8deb09b79%7C0%7C0%7C638120870397655228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Oez%2BzRaBoijTq%2BkgIn%2BlKp1qt4DYGxXVfU7%2FtbI%2FWro%3D&reserved=0> can you please share the contents of the extensions.json file in your build output?

Can you also share your app name so we can take a closer look at the logs here?

Thanks!

-
