### ISSUE TITLE
Option to disable RabbitMQ certificate validation

### ISSUE THREAD

**Issue by ysbakker** [Azure/azure-functions-dotnet-worker#1351]
Can the `DisableCertificateValidation` option that is present in the `Microsoft.Azure.WebJobs.Extensions.RabbitMQ` be added to this library?

See https://github.com/Azure/azure-functions-rabbitmq-extension#c-attributes

**Comment by fabiocav** [comment]
@JatinSanghvi is this something you can assist with?

**Comment by JatinSanghvi** [comment]
Adding @lpapudippu and @v-shenoy. I am no longer working on the RabbitMQ extension.
