### ISSUE TITLE
Enhance EventHub samples to include multiple binding scenarios

### ISSUE THREAD

**Issue by madelinegordon** [Azure/azure-functions-dotnet-worker#1354]
There was a recent issue filed (#1256) in which a customer used the EventHub samples as an example to change their parameter from EventData[] to byte[], and was having trouble making it work. 

We want to add samples for both batched and non-batched scenarios, detailed [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/1256#issuecomment-1414693442).

**Comment by fabiocav** [comment]
PR is out, currently blocked on validation.

**Comment by liliankasem** [comment]
We've added new samples
