### ISSUE TITLE
[SDK Binding - Blob] Output binding does not work with trigger binding using an SDK-type

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1362]
Using an output binding with a trigger bindings whilst binding to an SDK-type (stream/blobClient etc.) leads to an error.

```c#
        [Function(nameof(BlobTriggerStreamTest))]
        [BlobOutput("test-output-stream-dotnet-isolated/output.txt")]
        public async Task<string> BlobTriggerStreamTest(
            [BlobTrigger("test-trigger-stream-dotnet-isolated")] Stream stream,
            FunctionContext context)
        {
            using var blobStreamReader = new StreamReader(stream);
            string content = await blobStreamReader.ReadToEndAsync();
            _logger.LogInformation(".NET Blob trigger function processed a blob.\n Content: " + content);
            return content;
        }
```

Error:

`The 'BlobTriggerStreamTest' function is in error: Value cannot be null. (Parameter 'input').`

**Comment by lohithgn** [comment]
Add on to this - i just wanted to bind to BlobClient type with the BlobTrigger. I followed the instruction provided here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#trigger---usage
The instruction is:
_Preview types require use of [Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs 5.1.0-preview1 or later](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs/5.1.0-preview1), [Microsoft.Azure.Functions.Worker 1.12.1-preview1 or later](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.12.1-preview1), and [Microsoft.Azure.Functions.Worker.Sdk 1.9.0-preview1 or later](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.9.0-preview1)._
I created a VS > New Project > Azure Function & selected .NET 7 Isolated model. I updated the said packages. Host fails to start after this with the below error:
A host error has occurred during startup operation '3af44f08-b762-45d5-afe5-2de4c176501b'.
Microsoft.Azure.WebJobs.Extensions.Storage.Blobs: Could not load type 'Microsoft.Azure.WebJobs.ParameterBindingData' from assembly 'Microsoft.Azure.WebJobs, Version=3.0.34.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Value cannot be null. (Parameter 'provider')

**Comment by liliankasem** [comment]
@lohithgn Which version of core tools are you using? 

`When developing on your local machine, you will need [Azure Functions Core Tools version 4.0.5000 or later](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local).`
