### ISSUE TITLE
Can I access extensions.http.routePrefix at runtime?

### ISSUE THREAD

**Issue by martinjt** [Azure/azure-functions-dotnet-worker#1366]
Is there anyway to access to the routePrefix set in `host.json` at the runtime?

```json
{
    "version": "2.0",
    "extensions": {
      "http": {
        "routePrefix": ""
      }
    }
}
```

I'm trying to establish the actual route of a HttpTrigger function, which I can't do without the `routePrefix` as the method's route attribute doesn't include it.

**Comment by martinjt** [comment]
Nevermind, you can close this, apparently the Route attribute is dynamically updated, so it's valid even when `routePrefix` is set.

**Comment by fabiocav** [comment]
@martinjt this information is not made available to the worker today. The simplest way to get this information, today, would be to read the host.json file and get that information directly.

**Comment by fabiocav** [comment]
Another option is to define the route prefix as an app setting/environment variable (i.e., `AzureFunctionsJobHost__extensions_http_routePrefix`), and this would be automatically used by the host (no need to define that in `host.json`) and automatically added as a configuration value in the worker, accessible through `IConfiguration`

**Comment by lmolkova** [comment]
I might miss some Functions context, but Isn't it something that ASP.NET Core instrumentation should populate along with `http.route` ?

**Comment by martinjt** [comment]
This is specific to functions.

The wider host takes a config that will essentially add a base path to all routes. If you don't supply it, it adds `/api/` to what the client would call.

`http.route` is what I want to populate with the route template from the function, so it get `/company/{companyId:int}`, and not `/company/123` which is `http.route` vs `http.url`

When the function has been selected, we can get the attributes and find the route, but that doesn't take into account if someone has passed a `routePrefix` to the runtime.

**Comment by lmolkova** [comment]
I believe with this recent change https://github.com/open-telemetry/opentelemetry-specification/pull/3164 introduced in OTel [HTTP spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) `http.route` should have it captured.

Once Functions support OTel, I assume it should be possible to update `http.route` Activity tag to include the prefix.

**Comment by martinjt** [comment]
This is purely "how do we get the prefix", the attribute is there, we can use it... but I can't get access to the prefix in order to add it to the attrivute.

**Comment by lmolkova** [comment]
I mean functions can populate the attribute once they support OTel and adopt conventions, but today yes, no way.

**Comment by martinjt** [comment]
To be clear, I'm not asking for it on an Activity. I'm asking where it exists so that the Runtime can have access to it outside the worker host.

**Comment by fabiocav** [comment]
Reviewing open items and this is still a gap.

@martinjt are the options I've shared above viable workarounds in the meantime?

**Comment by martinjt** [comment]
I haven't looked at this recently, however, this wasn't viable at the time. I could look into why though.

**Comment by jviau** [comment]
@martinjt were you able to see if the proposed workarounds from @fabiocav work for you? Reading from `host.json` manually or using an appsetting.
