### ISSUE TITLE
[Source Gen] Epic tracking GA items for source-generated FunctionMetadata

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#1373]
Epic to track work to GA source-generation of FunctionMetadata. Items can be found under the label: https://github.com/Azure/azure-functions-dotnet-worker/labels/source-metadata-generator.

**General**
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1161
- https://github.com/Azure/azure-functions-dotnet-worker/pull/1356

**Bugs**
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1299
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1372

**Cleanup Items**
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1189
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1323

**Next**
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1160
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1158
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1185
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1381
- https://github.com/Azure/azure-functions-dotnet-worker/issues/1050

**Comment by mattchenderson** [comment]
Closing in favor of: https://github.com/Azure/azure-functions-dotnet-worker/milestone/65
