### ISSUE TITLE
Breakpoints not hit when debugging .Net 7 Isolated Process Functions

### ISSUE THREAD

**Issue by Jordantmcfar** [Azure/azure-functions-dotnet-worker#1407]
I am attempting to debug a service bus trigger with breakpoints set within the handling function. It appears the Debugger attaches to the external process but no breakpoints are hit. I would also note that the external process window closes when I stop debugging.

Visual Studio Version:
![image](https://user-images.githubusercontent.com/48570965/223865793-410f6b9e-ad06-40f8-894a-e69800f38052.png)

Attached Process:
![image](https://user-images.githubusercontent.com/48570965/223865838-7b243ebb-c95c-41fb-b53c-7f40ce46bb16.png)

External Process Continuing to run without hitting breakpoints:
![image](https://user-images.githubusercontent.com/48570965/223865868-c22328ab-e0b2-4633-9de8-eb53b17d9e10.png)

Could I please get some help with this?

**Comment by kshyju** [comment]
Are you sure that your service bus trigger is invoked/ Is there a new SB message in the queue/topic to be processed?

Can you try to add a new Timer triggered function and put a breakpoint in that and see if that works?

**Comment by kshyju** [comment]
You are doing F5 debugging in Visual studio. correct? It should work.

Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.
