### ISSUE TITLE
[BlobTrigger Binding] Durable isolated function with BlobClient binding

### ISSUE THREAD

**Issue by mohammedtabish0** [Azure/azure-functions-dotnet-worker#1412]
[In Local Environment]
BlobTrigger not working with parameters for function app as follows : -

`
public void Run([BlobTrigger("%BlobStorageBasePath%/{name}", Connection = "BlobStorageConnection")] BlobClient client, [DurableClient] DurableTaskClient durableClientContext)
{var temp = client.OpenRead();
}
`

After file upload on the container the function app is **not getting triggered** and getting error :- 
`The 'BlobTriggerBulkIngestion' function is in error: Value cannot be null. (Parameter 'input').`

If I make this function app change parameter and not include durableTaskClient this works fine function gets triggered and able to get blob client-
`public void Run([BlobTrigger("%BlobStorageBasePath%/{name}", Connection = "BlobStorageConnection")] BlobClient client)
{
var temp = client.OpenRead();
 }`

Unable to find any sample here for the same :- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview

Below are the package versions and library versions used

- .net version :7 
- isolated durable functions
- Azure functions core tools version :- 4.0.5030
- "Microsoft.Azure.Functions.Worker" Version="1.12.1-preview1"
- "Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.0-rc.1" ||  Version="1.0.0" // for both versions
- "Microsoft.Azure.Functions.Worker.Sdk" Version="1.9.0-preview1
- "Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.1.0-preview1"

**Comment by fabiocav** [comment]
Thank you for reporting this. We'll investigate and provide an update here.

**Comment by wldevries** [comment]
I have the same problem. How is the investigation going, do you need more information?

**Comment by liliankasem** [comment]
@mohammedtabish0 & @wldevries I attempted to repro this issue with the latest bits and I'm not seeing any problems. 

Here is the result from my attempt to repro; function is executing as expected:

![Screenshot 2023-06-30 at 12 07 05 PM](https://github.com/Azure/azure-functions-dotnet-worker/assets/2198905/91a2c6f8-3523-491d-b03c-6e20ef1a4538)

Can you try this again with all the latest preview packages:

```csharp
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.15.0-preview1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.11.0-preview1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="5.1.1-preview2" />
  </ItemGroup>
```

Core tools: 4.0.5198

If you still experience issues with the latest preview packages, please share a minimal repro project for me to look at. Thanks!

**Comment by pragya247** [comment]
@liliankasem Have you used specific (isolated or in-process) durable functions here? In my current implementation I am using .Net 7 Isolated Durable Functions. I also updated the packages to the latest versions shown below:
   ```
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="1.18.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.12.0" OutputItemType="Analyzer" />
    <PackageVersion Include="Microsoft.DurableTask.Generators" Version="1.0.0-preview.1" OutputItemType="Analyzer" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk.Analyzers" Version="1.1.2" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.1.2" />
```
But I am still getting the exception: 
```
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ABC': Cannot convert input parameter 'blobClient' to type 'Azure.Storage.Blobs.BlobClient' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. Error:System.Text.Json.JsonException: 'R' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```

**Comment by liliankasem** [comment]
Yes, I was using a .Net 7 isolated function - it would be ideal if you shared an exact minimal code repro to look at if there are still concerns. 

As for package versions, you cannot use Storage version 5.1.2 with Worker 1.18.0 and SDK 1.12.0  and use a BlobClient - the feature that brings in the BlobClient support is still in the exact versions I shared above as this is still in preview:

```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.15.0-preview1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.11.0-preview1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="5.1.1-preview2" />
```

Storage.Blobs GA should be version 6.0.0 (coming out this week), that is compatible with the latest stable worker, so once the stable blob package is out, you can use: 

```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.18.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.12.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.0.0" />
```
