### ISSUE TITLE
Using AKS Workload Identity with CosmosDBTrigger?

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-functions-dotnet-worker#1423]
We have AKS clusters deployed with workload identity enabled and we are trying to use identity based connection string for one of our CosmosDBTrigger enabled function (isolated v4). But not able to figure out how to configure the same as its throwing exception like "_The requested identity has not been assigned to this resource_". I can see that the workload identity is configured as the environment variables are all set up correctly it seems. Tried to add the below config but getting the above mentioned exception.

```csharp
- name: CosmosConnectionString__accountEndpoint
   value: {{ .Values.cosmosConnectionStringAccountEndpoint }}
 - name: CosmosConnectionString__credential
   value: managedidentity
- name: CosmosConnectionString__clientId
   value: {{ .Values.managedIdentityClientId }}
```

The above 'CosmosConnectionString__clientId' has the same value as the workload identity id. Tried by only specifying 'CosmosConnectionString__accountEndpoint' instead of all 3 environment variables but that fails too with exception like '_Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request_'. To note, the workload identity works fine as our api apps are using the same configuration, only function app is not able to pick this up it seems. Below are all the environment variables configured for the pod.

![image](https://user-images.githubusercontent.com/28987981/226234255-01bcbdea-041c-43ef-bad2-219ec54cebae.png)

![image](https://user-images.githubusercontent.com/28987981/226241808-2fec8ab7-377f-4319-8780-7f628e9b900f.png)

This is working if we go back to use the old pod identity route. So question is is there any documentation on how to use CosmosDBTrigger with AKS workload identity?

Packages used in function app:
```
<PackageVersion Include="Azure.Identity" Version="1.9.0-beta.2" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="1.10.1" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.0.1" />
```

**Comment by sanjaydebnath** [comment]
Any update here? @satvu

**Comment by tom-scott** [comment]
+1 on this issue. Is there any update on this issue?

I think it may be caused by a outdated reference of `DefaultAzureCredential` so that it doesn't include `WorkloadIdentityCredential` class. This package reference resolves back to a out of date `Azure.Identity` package which I think does include the updated credential: https://github.com/Azure/azure-functions-dotnet-worker/blob/5afdc0ea94004af9bff29b3be408543cac788c1f/extensions/Worker.Extensions.CosmosDB/src/Worker.Extensions.CosmosDB.csproj#L19C33-L19C33

**Comment by tchuan** [comment]
@sanjaydebnath I have faced the same issue, have your found a way to use workload identity for cosmosdb trigger?

**Comment by liliankasem** [comment]
I think @tom-scott is right, the current extension uses an old version of `Microsoft.Extensions.Azure` which doesn't have support for `WorkloadIdentityCredential` - this was introduced in version 1.7.0:

- https://github.com/Azure/azure-sdk-for-net/releases/tag/Microsoft.Extensions.Azure_1.7.0

Hopefully the work to be done here is trivial: update package reference and validate with testing.

**Comment by liliankasem** [comment]
It looks like this was already addressed last week ([PR](https://github.com/Azure/azure-functions-dotnet-worker/pull/2378)) and was released:

- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.CosmosDB/4.8.0

The latest Cosmos package should have `WorkloadIdentityCredential` - can you confirm? If it's still broken the issue might be something else and we will need to further investigate.

**Comment by tom-scott** [comment]
> It looks like this was already addressed last week ([PR](https://github.com/Azure/azure-functions-dotnet-worker/pull/2378)) and was released:
> 
> * https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.CosmosDB/4.8.0
> 
> The latest Cosmos package should have `WorkloadIdentityCredential` - can you confirm? If it's still broken the issue might be something else and we will need to further investigate.

Thank you @liliankasem - I will test it out and update this issue!

**Comment by tom-scott** [comment]
> > It looks like this was already addressed last week ([PR](https://github.com/Azure/azure-functions-dotnet-worker/pull/2378)) and was released:
> > 
> > * https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.CosmosDB/4.8.0
> > 
> > The latest Cosmos package should have `WorkloadIdentityCredential` - can you confirm? If it's still broken the issue might be something else and we will need to further investigate.
> 
> Thank you @liliankasem - I will test it out and update this issue!

Can confirm this is now working as expected @liliankasem. Just upgraded a function and can see events being picked up from the trigger! I think this can be resolved now 👍

**Comment by liliankasem** [comment]
Great! Thanks for confirming :) Will resolve this issue.
