### ISSUE TITLE
Add SendGrid extension

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#143]

**Comment by kinetiq** [comment]
@fabiocav  @brettsam Could I have an update on this one please?

Having trouble interpreting the labels swapping off and on - I am pretty sure fabiocav mentioned in a different issue that  SendGrid was in, but I am not seeing it anywhere. Please advise if there's a workaround, etc.

**Comment by fabiocav** [comment]
Moving this to sprint 104 as it was missed in triage.
