### ISSUE TITLE
Adding ApplicationInsights to a .net 7 worker function fails 

### ISSUE THREAD

**Issue by cconner100** [Azure/azure-functions-dotnet-worker#1440]
I am trying to add application insights to my Isolated worker function, I have looked up all the issues revolving this but dont see anyone having the same issue as i am.

The exception i am getting is
System.MethodAccessException: 'Attempt by method 'Microsoft.Azure.Functions.Worker.FunctionsApplicationInsightsExtensions.AddCommonServices(Microsoft.Azure.Functions.Worker.IFunctionsWorkerApplicationBuilder)' to access method 'System.Func`2<System.__Canon,System.__Canon>..ctor(System.Object, IntPtr)' failed.'

my code in startup is as follows

static async Task Main(string[] args)
    {
        var host = new HostBuilder()
            .ConfigureAppConfiguration(builder =>
            {
                var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
                Console.WriteLine($"Using environment {env}");

                _ = builder.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
                if (env != null)
                {
                    _ = builder.AddJsonFile($"appsettings.{env}.json", false, true);
                }
                else
                {
                    Console.WriteLine("********** GET HELP THE ENVIRONMENT WAS NOT SET THIS IS BAD ********************");
                }

                _ = builder.AddEnvironmentVariables();
                builder.AddAzureKeyVault(GetKeyVaultEndpoint(), new DefaultAzureCredential());
            })
            .ConfigureFunctionsWorkerDefaults(b =>
            {
                b.AddApplicationInsights()
                 .AddApplicationInsightsLogger();
            })
            .ConfigureServices((ctx, s) =>
            {

                //
                // Add Logging, if debug add in console logging
                s.AddLogging((loggingBuilder) => loggingBuilder
#if DEBUG
                .AddDebug()
                .AddConsole()
                .SetMinimumLevel(LogLevel.Debug)
#else
                .SetMinimumLevel(LogLevel.Trace)
#endif
                .AddSimpleConsole(options =>
                {
                    options.IncludeScopes = true;
                    options.SingleLine = true;
                    options.TimestampFormat = "HH:mm:ss ";
                }));

                _ = s.Configure<AppConfiguration>(ctx.Configuration.GetSection("AppConfiguration"));
                _ = s.Configure<IdentityServerConfiguration>(ctx.Configuration.GetSection("Authentication:IdentityServer"));

                _ = s.AddScoped<ZtRepositorySession>();
                _ = s.AddScoped<ZtCurrentUser>();

                _ = s.AddSingleton(_ => ctx.Configuration);

                // Add http services
                Backend.HttpConfiguration.ConfigureHttpCients(s, ctx.Configuration);

                ServiceProvider = s.BuildServiceProvider();
                ZtServiceProvider = new ZtServiceProvider(ServiceProvider);
                ServiceFactory = new ServiceFactory(ZtServiceProvider);

                //
                // Configure Redis Cache
                //
                _ = s.AddStackExchangeRedisCache(options =>
                {
                    options.Configuration = ctx.Configuration["AppConfiguration:ConnectionStrings:Redis"];
                    options.InstanceName = "ZiiDMSInstance";
                });
            })
            .Build();

        InitializeUser();
        await host.RunAsync();

    }

If i remove the AddApplicationInsights the system seems to work correctly.

I am using the following nuget packages
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
    <PackageReference Include="Azure.Identity" Version="1.8.2" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Xml" Version="2.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk.Analyzers" Version="1.1.2" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.13.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights" Version="1.0.0-preview4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />

I have also tried to use host.Run and host.RunAsync both with the same results.

Help :)

**Comment by kshyju** [comment]
@cconner100 Can you share the absolute minimum code (startup code / code in main method) to reproduce this issue. The code shared in the previous post is huge. Wondering whether we can trim it down to what actually causes the issue.

**Comment by bvmeer** [comment]
I have the same issue:

```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()  --> this lines
            .AddApplicationInsightsLogger();
    })
```
    
Issue occurs when I add a reference package Microsoft.Azure.Functions.Worker version 1.13. When I switch back to version 1.10 it works fine.

**Comment by kshyju** [comment]
What version of [Microsoft.Azure.Functions.Worker.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview4) package were you using with worker 1.13.0? Was it the latest? (1.0.0-preview4)

**Comment by bvmeer** [comment]
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.13.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview4" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />	  
	
I used 1.0.0-preview3, i tryed with 1.0.0-preview4 the error is:

```
System.MethodAccessException
  HResult=0x80131510
  Message=Attempt by method 'Microsoft.Azure.Functions.Worker.FunctionsApplicationInsightsExtensions.AddCommonServices(Microsoft.Azure.Functions.Worker.IFunctionsWorkerApplicationBuilder)' to access method 'System.Func`2<System.__Canon,System.__Canon>..ctor(System.Object, IntPtr)' failed.
  Source=Microsoft.Azure.Functions.Worker.ApplicationInsights
  StackTrace:
   at Microsoft.Azure.Functions.Worker.FunctionsApplicationInsightsExtensions.AddCommonServices(IFunctionsWorkerApplicationBuilder builder)
   at Microsoft.Azure.Functions.Worker.FunctionsApplicationInsightsExtensions.AddApplicationInsights(IFunctionsWorkerApplicationBuilder builder, Action`1 configureOptions)
   at Program.<>c.<<Main>$>b__0_0(IFunctionsWorkerApplicationBuilder builder) in \Program.cs:line 17
   at Microsoft.Extensions.Hosting.WorkerHostBuilderExtensions.<>c__DisplayClass3_0.<ConfigureFunctionsWorkerDefaults>b__0(HostBuilderContext context, IFunctionsWorkerApplicationBuilder b)
   at Microsoft.Extensions.Hosting.WorkerHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureFunctionsWorkerDefaults>b__2(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<<Main>$>d__0.MoveNext() in \Program.cs:line 14
   at Program.<Main>(String[] args)
```
After switching the sdk package (Microsoft.Azure.Functions.Worker.Sdk) to preview 1.9.0-preview2 it starts without exception.

**Comment by purkayasta** [comment]
Same exception for me as well.

```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.13.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview3" />
```

**Comment by brettsam** [comment]
Please move to `1.0.0-preview4`... it should run on all of the latest Worker bits.

**Comment by dguerin** [comment]
> 

Thanks - worked for me too.

**Comment by dguerin** [comment]
> Please move to `1.0.0-preview4`... it should run on all of the latest Worker bits.

Thanks - worked for me too.
