### ISSUE TITLE
kafka output trigger always expect some value 

### ISSUE THREAD

**Issue by Alpesh1984909090** [Azure/azure-functions-dotnet-worker#1441]
Kafka output trigger always expects some value if no values passed it throwing below error 

 Microsoft.Azure.WebJobs.Extensions.Kafka: Message value was not defined.

there are some business scenario on which will define whether to publish the message or not. So, if there is no value Or value = null, it's throwing this error.

**Comment by kshyju** [comment]
@jainharsh98 @raorugan Can you help with this?

**Comment by jainharsh98** [comment]
@Alpesh1984909090 Currently passing the value as null is not supported. Adding the [code link](https://github.com/Azure/azure-functions-kafka-extension/blob/025ed00ef3474c6bd9ef757f388e7b9a7bc13476/src/Microsoft.Azure.WebJobs.Extensions.Kafka/Output/KafkaProducer.cs#L145) for reference. 
Can you please add an issue [here](https://github.com/Azure/azure-functions-kafka-extension) for tracking of the feature request.

**Comment by fabiocav** [comment]
Closing this as answered, but please let us know if you have any additional questions.
