### ISSUE TITLE
🐛 Function Host crashes when trying to check the RetryCount or MaxRetryCount values. 

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-functions-dotnet-worker#1443]
👋🏻 G'Day A.F. team 🚀 

I'm getting a `NullReferenceException` when I'm trying to check the values of the `RetryCount` and/or `MaxRetryCount`.

![image](https://user-images.githubusercontent.com/899878/228734374-4f81a74a-5979-4cf8-af98-39b4bac49d98.png)

Here's a repo about what / how I did it:

- File -> new -> Azure Functions -> NET 6 -> basically all the default's. It's a queue trigger, also
- Update all nugets, except the secrets one cause i'm still on NET 6.
- Replace the `program.cs` with the following code below
- Add a message to the queue.

NOTE: I'm using azurite-in-a-container. Not sure if that makes any difference -> the message is _correctly_ popped from the (Azurite) storage service. That's not the problem.

Ok - the code:

```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace FunctionApp4
{
    public class Function1
    {
        private readonly ILogger _logger;

        public Function1(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public void Run(
            [QueueTrigger("myqueue-items", Connection = "azuriteLocalStorage")] string myQueueItem,
            FunctionContext context)
        {
            try
            {
                throw new Exception("Something bad has happened.");
            }
            catch (Exception exception)
            {
                _logger.LogWarning("Failed to process message. Reason: {exceptionMessage}", exception.Message);

                if (context.RetryContext.RetryCount >= context.RetryContext.MaxRetryCount)
                {
                    // We've tried 5 times (which is the default number of times to retry, before this
                    // will get auto-moved into the poison queue)
                    _logger.LogError("Failed to handle message too many times. Auto-moving to poison queue.");
                }

                // Re-Throw so the Azure Function framework can handle this error and then auto-move it to a poison queue.
                throw;
            }
        }
    }
}
```

Ok - so here's a visual description of what I'm trying to do:

![image](https://user-images.githubusercontent.com/899878/228735581-fa3481de-831f-4c58-8f81-f1c4cd0b279c.png)

- 📧 Post a random message to the queue.
- 💥 Trigger fires off - blam! 
- 😿 Now just throw an exception like something bad happened in my logic
- 👀 Check how many times this message has errored. Here, we might do some _other_ logic like send an email/post a slack message saying something isn't working.
- 🔥 Host crashes with an NRE. 💀 

I've really simplified _our_ logic down to those steps above to get a simple repo for you all.

I'm guessing -> this isn't suppose to happen?

**Comment by kshyju** [comment]
@PureKrome 👋

See https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries Did you configure retry settings in host.json?

Here is an example of configuring retry settings in host.json.

```json
{
  "version": "2.0",
  "retry": {
    "maxRetryCount": 3,
    "strategy": "fixedDelay",
    "delayInterval": "00:00:15"
  }
}
```
With this the `RetryContext` property of `FunctionContext` will be properly populated.

![image](https://user-images.githubusercontent.com/144469/228899382-94ba305d-809e-4bcb-942b-aa8114dbb6ee.png)

**Comment by PureKrome** [comment]
👋🏻 Hi @kshyju - thanks heaps for looking into this report... really really appreciate it.

This was done with the stock standard -> FILE -> NEW -> Azure Functions (in latest Visual Studio). So I didn't _manually_ set/change anything in the `host.json`.

I'm not in the office today to test this out. But if that does fix the crash .. then the issue is that the Out Of the Box experience isn't right and/all / there's no default values set?

**Comment by PureKrome** [comment]
@kshyju sorry for the slow reply.

I've been looking into this problem today (at work again).

First -> are there any docs on this?

```
{
  "version": "2.0",
  "retry": {
    "maxRetryCount": 3,
    "strategy": "fixedDelay",
    "delayInterval": "00:00:15"
  }
}
```

I was looking at [these MSDN docs on hosts.json](https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json) and couldn't see anything? The reason I'm asking is why is this `retry` a setting in the root of this `hosts.json` and not part of the `extensions` ... like the queue extension?

here's my _current_ `hosts.json` file (for example):

```
{
    "version": "2.0",

    "extensions": {
        "queues": {
            "visibilityTimeout": "00:01:00",
            "batchSize": 1
        }
    }
}
```

That is mainly for dev settings. I'm not committing the above changes, for example.

Secondly -> why would we have to set this value _manually_ via the `hosts.json` ? Shouldn't there be some safe default value?

**Comment by jviau** [comment]
I believe this was addressed in #1476

**Comment by PureKrome** [comment]
This is great news! Thanks team! I'll leave this issue open _until_ the changes have made it up to production. 

Is there an ETA / planned build when these changes will be available in prod?

**Comment by jviau** [comment]
Resolving as this has been checked in (we resolve issues when work is checked in)

**Comment by PureKrome** [comment]
Note: currently part of this release: https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/storage-extension-5.1.1-preview1
