### ISSUE TITLE
[Enhanced HTTP] Avoid sending unnecessary invocation results over gRPC

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#1446]
To skip over binding logic [like this](https://github.com/Azure/azure-functions-host/blob/942b79c93aa29bd73fd545a2a53d5f0a11648aa9/src/WebJobs.Script/Binding/Http/HttpBinding.cs#LL40) in the host and improve performance, invocation results sent across the gRPC pipeline need to be altered to remove results already being sent in the aspnet pipeline.

**Comment by fabiocav** [comment]
Closing as duplicate of host 9343
