### ISSUE TITLE
How to configure logging in dotnet-isolated?

### ISSUE THREAD

**Issue by Markz878** [Azure/azure-functions-dotnet-worker#1447]
There seems to be a bug related to logging in a dotnet-isolated function.
I have a .NET 7 C# function that uses EF Core for database operations.

I would like the logging to work like this:
- Log my own ILogger messages at Information level
- Log everything else (including EF Core) at Warning level

No matter what settings I try to use for EF 
(options.LogTo(Console.WriteLine, LogLevel.Warning); or host.json "logLevel": { "Microsoft.EntityFrameworkCore": "Warning" })
EF always logs at the same level as the function.

In .NET 6 in-process the logging works like this out of the box.

How should the .NET 7 version be configured?

**Comment by jviau** [comment]
Functions worker uses `ILogger`, so the same concepts for AspNetCore and dotnet console apps applies here. This article can get you started: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0

As for changes to `host.json` not applying, that is `host.json` is only for the _host_ process. What you need to do is configure the _worker_ process. Issue #1182 has some discussion on configuring Worker logging.

**Comment by Markz878** [comment]
Okay so the trick was to create appsettings.json similar as in AspNetCore and stick this code after the ConfigureFunctionsWorkerDefaults function. Hopefully this will be added to the template by default in .NET 8, thanks.
```
    .ConfigureAppConfiguration((context, config) =>
    {
        config.AddJsonFile("appsettings.json");
    })
    .ConfigureLogging((hostingContext, logging) =>
    {
        logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
    })
```
