### ISSUE TITLE
Detailed release notes

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#1449]
It would be better if the Functions team would provide a detailed list of the items that go into each release.
For example, Microsoft.Azure.Functions.Worker.Sdk 1.9.0 release had the following [entry](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.9.0):

> **What's Changed**
> - Source generated version of function metadata provider (not enabled by default).
> - Source generated version of function executor (not enabled by default).
> - Several bug fixes and reliability enhancements.

No links to the issues or PRs. Several bug fixes - no details of what bugs were addressed.

One option is to keep CHANGELOG.md up-to-date
For example:  
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/CHANGELOG.md
- https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md

**Comment by fabiocav** [comment]
Thanks, @SeanFeldman . We have a similar process in the host and will leave this open to track the improvements here as well.

**Comment by fabiocav** [comment]
@SeanFeldman there have been improvements made to this process. Closing this as resolved, but please let us know if you notice any issues.
