### ISSUE TITLE
Running custom code before Functions App shuts down

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#1450]
I'm looking for a way to invoke custom code in the grace period, just before an isolated functions app is signalled that it's about to be shut down. Ideally, I'd love to see something similar to ASP.NET Core's `IHostApplicationLifetime` with its `ApplicationStarted.Register()`, `ApplicationStopping.Register()`, and `ApplicationStopped.Register()` callbacks. Is this or something similar is possible with the Isolated SDK?

**Comment by jviau** [comment]
`IHostApplicationLifetime` should exist in the functions worker as well. It is not aspnetcore specific, but from `Microsoft.Extensions.Hosting`. Have you tried using that?

**Comment by SeanFeldman** [comment]
I'm unsure how to tie `IHostApplicationLifetime` to the Functions SDK.
I tried adding a custom type that's injected with `IHostApplicationLifetime` and registering that type in the container. But then how would that type be instantiated only once for the Functions App, @jviau?

**Comment by SeanFeldman** [comment]
I think a better option would be `IHostedService` as it supports asynchronous `StartAsync` and `StopAsync`. The latter could used to execute the code upon the host stopping. I think. The class implementing `IHostedService` would be registered with `IServiceCollection.AddHostedService()`. And I can see `StartAsync` invoked when the Functions App starts but I can't figure out how to trigger a shutdown to see `StopAsync` called.

**Comment by SeanFeldman** [comment]
@jviau, in my local environment, I had to change
```
var host = new HostBuilder()
    .ConfigureServices(services =>
    {
        services.AddHostedService<CustomHostedService>();
    })
    .Build();

host.Run();
```

to

```
var host = new HostBuilder()
    .ConfigureServices(services =>
    {
        services.AddHostedService<CustomHostedService>();
    })
    .Build();

var cts = new CancellationTokenSource(TimeSpan.FromSeconds(7));
host.RunAsync(cts.Token);
```

to get the cancellation token and for the `IHostedService.StopAsync` to execute. But I'm concerned as I'm unsure how to tie it to the Functions runtime provided cancellation token instead of a manually created cancellation token. Is that exposed somehow? Or am I going in the wrong direction? Thank you.

**Comment by jviau** [comment]
@SeanFeldman your hosted service would work - no need to use a cancellation token. `StopAsync` will be called when the shutdown signal comes in. If you are using debug sessions to verify this, use Ctrl+C with the terminal focused to shut down and **not** stop debugging.

Alternatively, it could be as simple as:

``` CSharp
var host = new HostBuilder()
    .ConfigureServices(services =>
    {
        services.AddHostedService<CustomHostedService>();
    })
    .Build();

await host.RunAsync();

Console.WriteLine("Handle shutdown here");
```

Keep in mind you only have a small window of time during "graceful" shutdown before the host will forcibly terminate the worker process.

**Comment by SeanFeldman** [comment]
Excellent. It would be great to see some of this also reflected in the documentation at some point. Thank you for helping on this one.
