### ISSUE TITLE
Revert changes from 1258

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1451]
The changes made to support #1216 is not really needed as we always need the metadata loader extension entry in the extensions.json. Without this, if customer is not enabling the "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED" setting, functions will not be loaded. @brettsam knows the details.

We should revert #1258

**Comment by kshyju** [comment]
Good bot.

**Comment by mattchenderson** [comment]
Flagging this one as needing some additional discussion.

**Comment by kshyju** [comment]
This is not valid. closing.
