### ISSUE TITLE
EventHub Trigger has same operationId for each call

### ISSUE THREAD

**Issue by MO2k4** [Azure/azure-functions-dotnet-worker#1452]
Hi there 👋

i currently found out that the Application Insights operationId is the same for all calls regarding the event hub trigger.

Can i change/configure this from my end or is this a bug? For http endpoints, every call receives a new operationId.

Best regards
Martin

**Comment by jviau** [comment]
Have you tried the latest AppInsights preview package? https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview4
