### ISSUE TITLE
Compilation against .NET5

### ISSUE THREAD

**Issue by rangers-bnc** [Azure/azure-functions-dotnet-worker#1455]
I cannot use this because my company prohibits me from using .NET 5 assemblies because of the the security related issues with that version of the framework.

Any plans to produce an updated version ?

Also, it's an unsupported version of the .NET framework.

```
// Microsoft.Azure.Functions.Worker.dll
// Microsoft.Azure.Functions.Worker, Version=1.13.0.0, Culture=neutral, PublicKeyToken=551316b6919f366c

[assembly: TargetFramework(".NETCoreApp,Version=v5.0", FrameworkDisplayName = ".NET 5.0")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("This library enables you to create an Azure Functions .NET Worker, adding support for the isolated, out-of-process execution model.")]
[assembly: AssemblyFileVersion("1.13.0.0")]
```

**Comment by jviau** [comment]
@rangers-bnc .NET 6 and 7 are supported, you ultimately control the TFM in your .csproj file. Just set `<TargetFramework>net6.0</TargetFramework>`.

When you target .net6.0 yourself, all base class libraries loaded will also be .net6.0, so even if our projects say `<TargetFramework>net5.0</TargetFramework>` they will ultimately be binding to .net6.0 at runtime, and thus all the security fixes are brought in.

**Comment by jviau** [comment]
> Many project support .net5, .net6, net7.0; there is a good reason for that.

The reasoning for this is either they want access to new features from the later releases, or they do it for consistency and _their own benefit_. In the dotnet repo cases, I would say they do this for consistency and to dogfood their own changes. There is no requirement for a library to support later runtimes unless they need features from that runtime. In fact, it is recommended for libraries to reference the lowest possible runtime possible that meets your feature needs - this lets you reach the broadest set of customers possible. In our case, the function app you write - your .csproj - is what controls the runtime. Our libraries being built against net5.0 **will not bring in net5,0 runtime unless you also target net5.0**.

> Plus the compiler issueing OWASP warnings that the project references and uses .NET 5.0 assemblies.

Which project does that warn about?

Take a look at the net7 worker sample: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Net7Worker/Net7Worker.csproj - this project targets .net7 - so at runtime .net7 will be used, regardless of what the dependencies are declare.

**Comment by bobbyangers** [comment]
Then how to explain this?

```
9>
9>C:\Users\Robert\.nuget\packages\system.diagnostics.diagnosticsource\7.0.0\buildTransitive\netcoreapp2.0\System.Diagnostics.DiagnosticSource.targets(4,5): warning : System.Diagnostics.DiagnosticSource 7.0.0 doesn't support net5.0 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
9>    1 Warning(s)
9>    0 Error(s)
9>
```

**Comment by bobbyangers** [comment]
```
    <TargetFrameworks>netstandard2.0;net5.0;net6.0;net7.0</TargetFrameworks>
```

```
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
  </ItemGroup>

```

**Comment by jviau** [comment]
@bobbyangers `Microsoft.Extensions.Hosting/5.0.0` is not equal to `.net5.0` - it just happens the dotnet team versions them together. You _can_ have `Microsoft.Extensions.Hosting/5.0.0` in .net7, and you can also have `Microsoft.Extensions.Hosting/7.0.0` on .net5. They are not bound together.

You are free to pin to a higher version of that package yourself in your csproj by adding:

```xml
<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
```

**Comment by jviau** [comment]
> This happens simply compiling this project.
> 
> ```
> 1>    Target NETStandardCompatError_System_Diagnostics_DiagnosticSource_net6_0:
> 1>        C:\Users\Robert\.nuget\packages\system.diagnostics.diagnosticsource\7.0.0\buildTransitive\netcoreapp2.0\System.Diagnostics.DiagnosticSource.targets(4,5): warning : System.Diagnostics.DiagnosticSource 7.0.0 doesn't support net5.0 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
> 1>    Done building target "NETStandardCompatError_System_Diagnostics_DiagnosticSource_net6_0" in project "DotNetWorker.Core.csproj".
> 2>Build started 2023-05-03 4:17:17 PM.
> ```

This discussion is about end users' dependency on .net5.0, which is not the same as what our own project builds with. Yes, we have dependencies on .net5.0 that raise warnings on build of our own project. But this is **not** transitive to customers (potentially unless they also target net5.0).

As for what Checkmarx flags, I don't know - I do not use it. It is odd for it to flag a transitive dependency to that platform, as the platform is determined by the final projects TFM - not what package references were built against. Also remember that `Microsoft.Extensions.*` is **not** the platform or runtime. These are NuGet packages shipped separately from the .net runtime.

**Comment by bobbyangers** [comment]
> > This happens simply compiling this project.
> 
> > 
> 
> > ```
> 
> > 1>    Target NETStandardCompatError_System_Diagnostics_DiagnosticSource_net6_0:
> 
> > 1>        C:\Users\Robert\.nuget\packages\system.diagnostics.diagnosticsource\7.0.0\buildTransitive\netcoreapp2.0\System.Diagnostics.DiagnosticSource.targets(4,5): warning : System.Diagnostics.DiagnosticSource 7.0.0 doesn't support net5.0 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
> 
> > 1>    Done building target "NETStandardCompatError_System_Diagnostics_DiagnosticSource_net6_0" in project "DotNetWorker.Core.csproj".
> 
> > 2>Build started 2023-05-03 4:17:17 PM.
> 
> > ```
> 
> 
> 
> This discussion is about end users' dependency on .net5.0, which is not the same as what our own project builds with. Yes, we have dependencies on .net5.0 that raise warnings on build of our own project. But this is **not** transitive to customers (potentially unless they also target net5.0).
> 
> 
> 
> As for what Checkmarx flags, I don't know - I do not use it. It is odd for it to flag a transitive dependency to that platform, as the platform is determined by the final projects TFM - not what package references were built against. Also remember that `Microsoft.Extensions.*` is **not** the platform or runtime. These are NuGet packages shipped separately from the .net runtime.

@jviau At the end of the day, I do understand that the runtime itself doesn'nt end up at calling project.  The problem is referencing dll that are old, compiled against older runtime, doean't garanty compatibility.   

To ensure that your package is compatible with more recent version you need compile against them and test them.  I mean, newer version are not only "api" compatible, you also need to exercise the new functionalieties those more recent packages.

**Comment by jviau** [comment]
Closing this. The original question / concern has been addressed. We will eventually be moving off of .NET5 as it is out of support, but that will be tracked separately.
