### ISSUE TITLE
How to get operationid in a http triggered isolated function?

### ISSUE THREAD

**Issue by Cheng811** [Azure/azure-functions-dotnet-worker#1463]
Previously we use Activity.Current.RootId to get operationid for request&dependency telemetry of application insights. In isolated function, the Activity.Current.RootId is null as mentioned in the [issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/914). So is there some other way for user to get the operationid?

**Comment by satvu** [comment]
An update was posted last week in the issue you linked - please use that thread for questions/updates related to `Activity.Current.RootId`. Closing in favor of #914.
