### ISSUE TITLE
Input and output binding doesn't work with Custom Type in isolated worker

### ISSUE THREAD

**Issue by ASHIQUEMD** [Azure/azure-functions-dotnet-worker#1472]
We are creating support for [Isolated worker (out of proc) in Dapr Extension for Azure functions](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/tree/out-of-proc-support-2/src/Microsoft.Azure.Functions.Worker.Extensions.Dapr). We already have [InProcess support for Dapr Extension](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/tree/out-of-proc-support-2/src/Microsoft.Azure.WebJobs.Extensions.Dapr) and it seems to work fine with custom type. However, I am facing issues with OutOfProc support in Dapr Extension with Input and Output bindings.
 
**Input Binding:**
I have created [a sample function](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/out-of-proc-support-2/samples/dotnet-isolated-azurefunction/InputBinding/DaprStateInputBindingUserDefinedType.cs), which uses input binding to read the data, and I am expecting it to return Custom Type (POCO model), which is valid type for the data I am expecting from input binding. But It gives me below error.

**“Exception while executing function: Functions.DaprStateInputBindingUserDefinedType. Microsoft.Azure.WebJobs.Script: ScriptBinding type System.Byte[] is not supported.”**

**Output Binding:**
I have created [a sample for out binding](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/out-of-proc-support-2/samples/dotnet-isolated-azurefunction/OuputBinding/DaprStateOutputBindingUserDefinedType.cs), which uses custom type data, however i[t always uses Byte[] converter](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/08f72aa3a1a3035baa926e0dca7051121a2df6ce/src/Microsoft.Azure.WebJobs.Extensions.Dapr/DaprExtensionConfigProvider.cs#L197-L200) instead of [object converter](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/08f72aa3a1a3035baa926e0dca7051121a2df6ce/src/Microsoft.Azure.WebJobs.Extensions.Dapr/DaprExtensionConfigProvider.cs#L224-L227) and this is a problem for us. Similar example for [InProcess Azure Functions output binding sample ](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/out-of-proc-support-2/samples/dotnet-azurefunction/DaprStateOutputBindingUserDefinedType.cs)works as expected. So, not sure, what is causing this problem, where [byte[] converter](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/08f72aa3a1a3035baa926e0dca7051121a2df6ce/src/Microsoft.Azure.WebJobs.Extensions.Dapr/DaprExtensionConfigProvider.cs#L197-L200) is used instead of [object converter](https://github.com/ASHIQUEMD/azure-functions-dapr-extension/blob/08f72aa3a1a3035baa926e0dca7051121a2df6ce/src/Microsoft.Azure.WebJobs.Extensions.Dapr/DaprExtensionConfigProvider.cs#L224-L227).

**Comment by fabiocav** [comment]
@ASHIQUEMD some the issues mentioned above are related to the core extension supporting the out-of-proc model (beyond .NET Isolated), and it would be good to iterate on that first before focusing on .NET Isolated. Those will be requirements for integrations with all out-of-proc stacks.

**Comment by liliankasem** [comment]
@ASHIQUEMD was this ever addressed?

**Comment by mattchenderson** [comment]
@ASHIQUEMD Is this item still valid?
