### ISSUE TITLE
Security vulnerabilities in azure function build folder

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-functions-dotnet-worker#1477]
Hi All,

We are running isolated azure function app inside AKS cluster & recently we were flagged by an internal audit process where it was found that we are using a vulnerable nuget package of 'Azure.Storage.Queues' version '12.8.0' (https://www.nuget.org/packages/Azure.Storage.Queues/12.8.0). While debugging we found that this is coming from 'function.deps.json' which is auto generated while building the function app in locally/ado in debug/release mode.

Below is the simple function app csproj that uses a storage queue trigger function for demonstration. Once the function app is build if we go to the drop folder we can see that the vulnerable nuget package is pulled by function runtime it seems (as shown in below image).

```csharp
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.16.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.14.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.14.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.13.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.9.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.6.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/28987981/232705357-8b3b1398-942a-49e7-a5d8-33bf925236f5.png)
![image](https://user-images.githubusercontent.com/28987981/232705645-1d7f2736-8f64-47a3-92ef-6fc4b1f23468.png)

How can this be resolved? Any pointer is appreciated, thanks!

**Comment by mattchenderson** [comment]
This item is out of date. Packages were all updated to newer versions, and this should no longer be a concern.

As an aside, the https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage package includes both blobs and queues. We recommend instead referencing the two packages separately:
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs/
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues/

**Comment by fabiocav** [comment]
Deleting security related issue.

All issues should be addressed.
