### ISSUE TITLE
Extensions are not registered in the host if referencing local Microsoft.Azure.WebJobs.Extensions.* package

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-dotnet-worker#1479]
I'm trying to reference a local `Microsoft.Azure.WebJobs.Extensions.SignalRService` version by updating the version to a new version here. 

https://github.com/Azure/azure-functions-dotnet-worker/blob/59cd1cb1357a71504153cb450e7dc3ac945be2e4/extensions/Worker.Extensions.SignalRService/src/Properties/AssemblyInfo.cs#L6 

Then I add the in-process extension package to my local Nuget source with:
```
nuget add .Microsoft.Azure.WebJobs.Extensions.SignalRService.1.11.0-alpha.20230419.1.nupkg -source C:\Users\***\.nuget\packages  
```

Then in an isolated function app, add a project reference to the isolated extension `Microsoft.Azure.Functions.Worker.Extensions.SignalRService`. When I build the isolated function app, there is no error. I guess the restore is successful because if I don't add the in-process extension package to local Nuget source, it would fail to find the specific version. However, when I run the function app, I get the following errors:
```
[2023-04-19T08:34:24.786Z] The 'Broadcast' function is in error: The binding type(s) 'signalREndpoints, signalRNegotiation, signalRTrigger, signalR' are not registered. Please ensure the type is correct and the binding extension is installed.
[2023-04-19T08:34:24.788Z] The 'JoinGroup' function is in error: The binding type(s) 'signalRTrigger, signalR' are not registered. Please ensure the type is correct and the binding extension is installed.
[2023-04-19T08:34:24.789Z] The 'JoinUserToGroup' function is in error: The binding type(s) 'signalRTrigger, signalR' are not registered. Please ensure the type is correct and the binding extension is installed.
```

I'd like to know what're the proper steps to using a local in-process extension version? It'd be better if we had a contribution guide.

**Comment by jviau** [comment]
What is the contents of your `extensions.json` file when you build your function app? If SignalR is listed there, can you verify the appropriate assemblies are also in the `.azurefunctions` folder?

**Comment by Y-Sindo** [comment]
Do you mean the `extensions.file` in `bin\output` directory? The SignalR is not listed there. Here is the content:
```json
{
  "extensions": [
    {
      "name": "Startup",
      "typeName": "Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.Startup, Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=551316b6919f366c",
      "hintPath": "./.azurefunctions/Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.dll"
    }
  ]
}
```

And another interesting thing is, in the `.azurefunctions` folder, the assemblies referenced by `Microsoft.Azure.WebJobs.Extensions.SignalRService` are already there, but `Microsoft.Azure.WebJobs.Extensions.SignalRService` itself is not there.

**Comment by Y-Sindo** [comment]
@jviau I have uploaded a project https://github.com/Y-Sindo/azure-functions-dotnet-worker/tree/repro to reproduce the problem.  https://github.com/Azure/azure-functions-dotnet-worker/commit/20fe0b8bdc049a569d587e57a6083a402eded9ac is the code update I made.

**Repro steps:**
1. Add the customized in-process extension to local Nuget cache. In the root path of the repo, execute `nuget add Microsoft.Azure.WebJobs.Extensions.SignalRService.1.11.0-alpha.20230419.1.nupkg -source [your-nuget-cache-path]`
2. Run the function app `samples/FunctionApp` , and you will see the error logs as follows:
```
[2023-04-20T06:29:42.602Z] The 'SignalRTrigger2' function is in error: The binding type(s) 'signalRTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

**Comment by jviau** [comment]
This file is what controls host extension discovery & loading. Without SignalR there it is never loaded, triggers never registered, and thus your errors. Extensions get added to that file as part of build - the packages described by `ExtensionInformationAttribute` are added to a temporary csproj, restore/build is ran on it, then we scan the restored assemblies for marker types to indicate it has at least some triggers and needs to be added to the extensions file. Since this is not happening, either (1) SignalR is failing to restore at all, or (2) the marker types are now gone from the local SignalRService package you authored.

When you downgrade to the older version, does SignalR extension show up in `extensions.file`?

**Comment by Y-Sindo** [comment]
I believe the restore is successful because I can see the logs in the Visual Studio build output as follows:
```
1>Determining projects to restore...
1>Restored C:\Users\xxx\AppData\Local\Temp\iqilq20m.prh\WorkerExtensions.csproj (in 1.63 sec).
1>WorkerExtensions -> C:\Users\xxx\AppData\Local\Temp\iqilq20m.prh\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
1>Done building project "DotnetIsolated-ClassBased.csproj".
```

And I can see SignalRService package is in the `WorkerExtensions.csproj` as follows.

```csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Configuration>Release</Configuration>
        <AssemblyName>Microsoft.Azure.Functions.Worker.Extensions</AssemblyName>
        <RootNamespace>Microsoft.Azure.Functions.Worker.Extensions</RootNamespace>
        <MajorMinorProductVersion>1.0</MajorMinorProductVersion>
        <Version>$(MajorMinorProductVersion).0</Version>
        <AssemblyVersion>$(MajorMinorProductVersion).0.0</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NETCore.Targets" Version="3.0.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Blobs" Version="5.1.0-beta.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.0.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.8.0-alpha.20230421.1" />

    </ItemGroup>
</Project>
```

I have also checked out the local source code used to build the SignalRService package to version 1.8.0, equivalent to the [version currently used by isolated worker extension](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.SignalRService/src/Properties/AssemblyInfo.cs#L6). But SignalR extension is still missing in `extensions.json`. 

Here are the steps that I build local SignalR package:
1. In `azure-sdk-for-net` repo, execute `git checkout tags/Microsoft.Azure.WebJobs.Extensions.SignalRService_1.8.0` 
2. Go to folder `sdk\signalr\Microsoft.Azure.WebJobs.Extensions.SignalRService`  and get the nuget package with `dotnet pack src\Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj -o artifacts`
3. Add the package to local NuGet cache: `nuget add .\artifacts\Microsoft.Azure.WebJobs.Extensions.SignalRService.1.8.0-alpha.20230421.1.nupkg -source C:\Users\xxx\.nuget\packages\`

Am I packing the package in the wrong way?

**Comment by Y-Sindo** [comment]
@jviau If you could not reproduce the issue, please let me know.

**Comment by Y-Sindo** [comment]
Finally, I have found that it was due to the SignalR package is a pre-release version and by default not picked up by NuGet.  I added `<SkipDevBuildNumber>true</SkipDevBuildNumber>` in the SignalR package to remove the pre-release prefix to make it work.
