### ISSUE TITLE
Slow initialization since upgrading Microsoft.Azure.Functions.Worker and Microsoft.Azure.Functions.Worker.Sdk

### ISSUE THREAD

**Issue by whitwa** [Azure/azure-functions-dotnet-worker#1484]
Hi there,

I have recently upgraded Microsoft.Azure.Functions.Worker from 1.10.1 to 1.13.0 and Microsoft.Azure.Functions.Worker.Sdk from 1.7.0 to 1.9.0.

I have a C# .NET 7 HTTP trigger function (isolated) running in Azure (Windows). Since performing the upgrades, the time it takes between the following messages has increased substantially. This first example is using the latest versions (6 second gap):

**2023-04-20 10:56:04.007
Executing 'Functions.SosBusinessCentralCustomerSync' (Reason='This function was programmatically called via the host APIs.', Id=0c4e2d85-f8d9-4fca-9ba7-6177d1be5154)
Information

2023-04-20 10:56:10.310
In CustomerSync
Information**

The next example is with the previous versions (nominal gap):

**2023-04-20 11:06:51.138
Executing 'Functions.SosBusinessCentralCustomerSync' (Reason='This function was programmatically called via the host APIs.', Id=d7c27ce0-04a9-488c-b6cc-21b992863f61)
Information

2023-04-20 11:06:51.405
In CustomerSync
Information**

Note that logging the "In CustomerSync" message is the first thing that my function code does.

Please can you advise as I have had to rollback to the previous versions for the time being.

Regards,
Andrew

**Comment by brettsam** [comment]
This is with every invocation, or just the first? Can you provide us a sample app that shows the issue?

**Comment by kshyju** [comment]
@whitwa Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by fabiocav** [comment]
@whitwa we've identified the issue and will have a fix out soon. Thanks for reporting this here.

**Comment by fabiocav** [comment]
The update has been released in https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.14.1 (or https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Grpc/1.10.1 if explicitly referencing the gRPC package).

Thanks again for reporting!

**Comment by whitwa** [comment]
@fabiocav - thank you very much! I can confirm that using the latest packages has resolved the issue for me.
