### ISSUE TITLE
Azure Event Hub retry does not working on isolated .Net 7

### ISSUE THREAD

**Issue by kenpi04** [Azure/azure-functions-dotnet-worker#1488]
I am facing issues with the retry option on the EventHubTrigger.  The isolated .net 7 function does not work when I have set the clientRetryOptions on the host.json. So my question are:
1. Is isolated .NET 7 not supporting the clientRetryOptions for EventHubTrigger?
2. How to set up retry if it does not support?
3. I have tried to use the old setting for the retry by adding the below setting in host.json. The retry is working correctly. but I got a warning it will be removed soon. When this option is removed?, is it effective to EventHubTrigger?
````
   "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 3,
    "delayInterval": "00:00:03"
  }
````

.Net 7
Functions v5
Isolated Functions worker

Dependencies

"Microsoft.Azure.Functions.Worker" Version="1.13.0" 
"Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.3.0" 
"Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" 
"Microsoft.Azure.WebJobs.Core" Version="3.0.36" 

host.json
`````
{
  "version": "2.0", 
  "extensions": {
    "eventHubs": {
       "maxEventBatchSize": 2,
      "batchCheckpointFrequency": 1,
      "prefetchCount": 300,
      "initialOffsetOptions": {
        "type": "fromStart",
        "enqueuedTimeUtc": ""
      },
      "clientRetryOptions": {
        "maxDelay": "00:00:05",
        "maxRetries": 3,
        "mode": "exponential",
        "tryTimeout": "00:00:15"
      }
    }
  }

}
`````

**Comment by satvu** [comment]
@kenpi04 Could you upgrade to the latest SDK version (1.9.0) and the latest EventHubs extension version (5.3.0)? On these versions (and higher) you can use retry policy attributes like in [this example](https://github.com/Azure/azure-functions-dotnet-worker/blob/4c2b2daaa0e30fb8e9a542e846691d644bdce533/samples/Extensions/EventHubs/EventHubsTriggerMetadata.cs#L14).

**Comment by kenpi04** [comment]
Hi @satvu  thanks so much for your feedback, I have tried upgrade the library , so now it is working properly and the warning message has been removed.
So does the **clientRetryOptions** does not work in isolated right?
``
 "clientRetryOptions": {
        "maxDelay": "00:00:05",
        "maxRetries": 3,
        "mode": "exponential",
        "tryTimeout": "00:00:15"
   }
``
