### ISSUE TITLE
Headers not being set correctly when InvocationResult is set manually

### ISSUE THREAD

**Issue by PatrickRatzow** [Azure/azure-functions-dotnet-worker#1490]
#### Description
I'm working on some caching middleware for an isolated worker project running Azure Functions v3 and .NET 5.0. I tested and the bug also occurs on Azure Functions v4.

I set the InvocationResult of the FunctionContext manually in some middleware that acts as a caching layer, however the headers are not behaving as I expect them to. Details & example project provided below

#### Repro steps

Provide the steps required to reproduce the problem:

1. Download & run the GitHub repo listed in Related Information
2. Run the IsolatedApp project
3. Send a HTTP request to the Cache function
4. Inspect the response

#### Expected behavior

Provide a description of the expected behavior.

- Header "X-Text-Type" should be "json"

#### Actual behavior

Provide a description of the actual behavior observed.

- Header "X-Text-Type" is "System.String[]"

#### Known workarounds

Provide a description of any known workarounds.

None as far as I know for now.

#### Related information 

Provide any related information 

- NET 5.0 with Azure Functions v3 isolated worker used
- Core Tools Version: 3.0.4899 (64-bit)
- Function Runtime Version: 3.17.0.0
- Project with the bug reproducible in: https://github.com/PatrickRatzow/azure-functions-header-bug

**Comment by kshyju** [comment]
Thank you for sharing the minimal repro. 👍

As of today, you need to use the `HttpResponse` instance created by the `CreateResponse` extension method on `HttpRequestData` when overriding the response in your middleware. The below code should work.

```csharp
public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
{
    var cachedResponse = new CachedResponse(
        "[1,2,3]",
        new Dictionary<string, IEnumerable<string>>
        {
            { "Content-Type", new List<string>() { "application/json" } }
        },
        HttpStatusCode.OK
    );

    var httpRequest = await context.GetHttpRequestDataAsync();

    var httpResponse = httpRequest.CreateResponse(cachedResponse.StatusCode);
    httpResponse.WriteString(cachedResponse.Body);
    httpResponse.Headers = new HttpHeadersCollection(cachedResponse.Headers);

    context.GetInvocationResult().Value = httpResponse;
}
```

##### Why it did not work for your approach:
The code path which produces the data wrapping the invocation result relies on the http response type to be of `GrpcHttpResponseData` type. 

https://github.com/Azure/azure-functions-dotnet-worker/blob/11ae12b306ee3512d8a7d1c28510ea840acc8066/src/DotNetWorker.Grpc/RpcExtensions.cs#L81-L84

When you are subclassing the `HttpResponseData` and use that to set the invocation result, it executes a different code path. We will discuss with the team to see this is something we need to support in the future. Until then, please use the solution shared above.
