### ISSUE TITLE
Correct Way to Override host.json Logging Configuration for Application Insights

### ISSUE THREAD

**Issue by BrandonSchreck** [Azure/azure-functions-dotnet-worker#1491]
We recently identified that several of our .NET 6 Isolated Process Azure Functions were not logging dependencies in Application Insights the same way our NodeJs Azure Functions were. 

After some research, I found [this pull request - #944](https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627) with steps to resolve this issue by utilizing `Microsoft.Azure.Functions.Worker.ApplicationInsights v1.0.0-preview4`. After migrating from `Microsoft.ApplicationInsights.WorkerService` I am now seeing the associated dependencies as with our NodeJs Azure Functions. 

I've purposely left our host.json to use the default logging levels (Warning):

host.json
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
```

What I am wanting to accomplish is to update the Functions Configuration in the Azure Portal (or via PowerShell) by setting the logging level to Information and be able to see those logged Information messages in the Application Insights trace table. 

However, setting either `AzureFunctionsJobHost__logging__logLevel__default` or `AzureFunctionsJobHost__logging__logLevel__Function.{{FunctionName}}` to Information doesn't seem to capture these logged messages. I double checked and verified that the Application Insights Connection String/Instrumentation Keys matched between the Azure Functions and the Application Insights instance. I also tried restarting the Azure Functions without any luck.

I am able to watch the Log Stream and see the Information/Trace logs being written out correctly.

Could someone provide the correct steps/settings to be able to ad-hoc increase the log level to capture additional logs?

**Comment by jviau** [comment]
`host.json` only affects the host process - not the worker process.

Take a look at #1182 for some steps on how to work with AppInsights logging in the worker.

**Comment by BrandonSchreck** [comment]
> Changing environment variables will not dynamically update configuration, and externally changing environment variables of a running process is not recommended/doable.

Is that not what [this article](https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json#override-hostjson-values) is referring to?
