### ISSUE TITLE
Distributed Tracing between different Azure Function Instances

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-dotnet-worker#1492]
Hi @brettsam,

I want to express my gratitude for your outstanding work on the ApplicationInsights integration.

Currently, we are utilizing the latest versions of Microsoft.Azure.Functions.Worker 1.13.0 and Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-preview4.

Our team is investigating different possibilities for implementing distributed tracing between various external components that we own. These external components may consist of other dedicated Azure Functions that share the same Application Insights instance.

One of our use cases involves writing to a Queue to trigger specific processes. We were wondering if you have any recommendations on how we can enhance the queue message to include trace contexts of the parent?

Alternatively, if this isn't feasible, do you have any suggestions for linking operations carried out from the client or backend with the Azure Function operations, including queue messages?

Thank you for your insights,

Best regards,

Patrick

**Comment by brettsam** [comment]
Most distributed tracing should "just work" today. Functions will pass the parent id along to the worker, which will then set it on the Activity.Current and App Insights will use that for correlation.

However, Azure Storage Queues do not have any built-in mechanism for tracking parent ids today.

I chatted with @lmolkova about this yesterday -- she's said she can take up the task of putting together a sample that shows how this can be done.

**Comment by plamber** [comment]
Thank you @brettsam and @lmolkova. 

An example would help a lot

**Comment by RobARichardson** [comment]
> Most distributed tracing should "just work" today. Functions will pass the parent id along to the worker, which will then set it on the Activity.Current and App Insights will use that for correlation.

Is this true for Durable Functions because I can't seem to get it working in the same way that it works for In-Process Durable Functions.

**Comment by joproulx** [comment]
I have the same behavior as described @RobARichardson. Could you please confirm if distributed tracing should work for Durable Functions?  

@brettsam I am trying to step in the code and I cannot see where the Activity.Current is set as you mentioned in your previous comment. Could you direct me to the place where this should be accomplished please?

**Comment by jviau** [comment]
Durable functions distributed tracing is a different solution than functions. @RobARichardson I see you already have an issue on the DF extension repo: https://github.com/Azure/azure-functions-durable-extension/issues/2662 - please continue to use that issue there.

@plamber, as @brettsam said we should have `Activity.Current` hydrated in the worker today. Is it not working for you?

We are also looking to improve this experience with our OTel efforts: https://github.com/Azure/azure-functions-host/issues/9273

**Comment by jviau** [comment]
Re-reading this issue, your specific ask is regarding Azure Storage queues. Unfortunately, the C# Azure Storage queues SDK does not flow trace context. So, we are unable to correlate the action which enqueued the message back to the function that processed it.

https://github.com/Azure/azure-functions-dotnet-worker/issues/1126
