### ISSUE TITLE
The SignalR triggered function return value not working

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-dotnet-worker#1496]
The SignalR `Microsoft.Azure.WebJobs.Host.Triggers.ITriggerData.ReturnValueProvider.SetValueAsync(object value, CancellationToken cancellationToken)`  is always invoked with parameter `value=null` for isolated worker. This means the return value of SignalR triggered function without output binding annotated is not working at all. However, it works in the in-process model and the isolated process model of `HTTP` trigger. 

```cs
[Function("Broadcast")]
public async Task<NewMessage> Broadcast(
[SignalRTrigger(nameof(Functions), "messages", "broadcast", "message")] SignalRInvocationContext invocationContext, string message)
{
    return new NewMessage(invocationContext, "this is returned from function");
}
```

The [Worker.Extensions.Http](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/extensions/Worker.Extensions.Http)` trigger is quite simple that has nothing to do with the return value handling. Need more investigation on what makes the difference. Any insight would be appreciated.

**Comment by fabiocav** [comment]
@Y-Sindo has this been validated for the other OOP languages as well? 

The first step here would be to validate that your return value is being assigned as expected and defined in the metadata with the appropriate `$return` name.

Is the example above all we'd need in order to repro your issue? If possible, having that in a repo we can simply clone would make this process easier.

Thanks!

**Comment by Y-Sindo** [comment]
@fabiocav  The node worker also doesn't work. It seems like a common problem in isolated workers. However, I don't know how to declare the `$return` name to make it the return value of a trigger instead of an output binding. I have tried as follows but the functions cannot even start normally.
```json
{
  "disabled": false,
  "bindings": [
    {
      "type": "signalRTrigger",
      "name": "invocation",
      "hubName": "SignalRTest",
      "category": "messages",
      "event": "SendMessage",
      "parameterNames": ["message"],
      "direction": "in"
    },
    {
      "type": "signalRTrigger",
      "name": "$return",
      "hubName": "SignalRTest",
      "category": "messages",
      "event": "SendMessage",
      "parameterNames": ["message"],
      "direction": "out"
    }
  ]
}
```


> The first step here would be to validate that your return value is being assigned as expected and defined in the metadata with the appropriate $return name.

I'm not sure what the `return` value is.  Is the `$return` name used as follows?  The `functions.metadata` seems like the `functions.json` in node worker, but in my understanding, we don't need `functions.json` in dotnet isolated worker. Or is it something our extensions developer needs to declare somewhere? https://github.com/Azure/azure-functions-dotnet-worker/blob/1c9b7e09cac6f7b0b803e39585fe9175924bc608/test/SdkE2ETests/Contents/functions.metadata#L22-L26

**Comment by Y-Sindo** [comment]
I have added a repo to repro the issue. The reproducing steps are a little bit complicated. Please see https://github.com/Y-Sindo/DotnetIsolated-SignalRTrigger/blob/main/README.md for details. Thanks.

**Comment by Y-Sindo** [comment]
@faviocav Could you provide more detailed information about how to define the return value in the metadata in C# isolated model?
> The first step here would be to validate that your return value is being assigned as expected and defined in the metadata with the appropriate $return name.

**Comment by Furrman** [comment]
Hi @mattchenderson @jviau @aishwaryabh I see this issue was raised in 2023 and still it is not resolved. I wanted to get more attention to this bug, because .NET8 enforce to use Azure Functions in isolated mode and this one is a blocker for my team. Is it possible to get someone allocated to this ticket and provide some estimated release date of fix? Thanks

**Comment by Y-Sindo** [comment]
@fabiocav Now I've managed to find out a way to support return value handling in host-process. When I was trying to verify it for C# isolated worker locally with the following steps, the local SignalR webjobs extensions nuget package restoration failed silently without any error messages during the build of the function app. When the function app ran, I saw that the "signalr" extensions were not registered. 

Here're the repro steps:
1. Pack the local SignalR webjobs extensions into a nuget pacakge with a stable version , and install it to local nuget store with `nuget init C:\Source\azure-sdk-for-net\artifacts\packages\ 'C:\users\<username>\.nuget\packages\'`  . 
2. Update the local SignalR worker extensions' reference to webjobs extensions.
3. Refer to the local SignalR worker extensions in a sample project such as https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/DotnetIsolated-BidirectionChat . 

I remember previously this method worked, but not it doesn't. Can we have a guidance on how to test our locally built worker extensions project?

**Comment by waqarzafar** [comment]
The fixes have been applied to .NET6 package: Microsoft.Azure.WebJobs.Extensions.SignalRService whereas the same issue exists in .NET8 version of this package: Microsoft.Azure.Functions.Worker.Extensions.SignalRService. Please kindly confirm when will the fix be propagated to this library for .NET8 applications
