### ISSUE TITLE
Azure dotnet-isolated durable function Vnet integration throws: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR'

### ISSUE THREAD

**Issue by Ushimaster** [Azure/azure-functions-dotnet-worker#1500]
Context:

1. **.NET7**, 
2. Azure App Service Plan on Linux
3. Azure durable function: 1 orchestrator client, 1 orchestrator and 2 activities
4. Orchestrator client read/write data from/to **Azure Storage table**
5. Function integrated into **VNet**
6. Storage table inside same **VNet**
7. Connection between function and storage account via **user managed identity**

The function does not even start.

Without VNet integration, all components work as expected but VNet is a requirement.

![image](https://user-images.githubusercontent.com/7912808/235196575-ab95043c-599b-4b02-9b63-7c731eb9b538.png)

**Comment by fabiocav** [comment]
@Ushimaster as this is likely related to VNET configuration, do you have the ability to engage support to take a closer look at VNET configuration and potential issues with that?

**Comment by Ushimaster** [comment]
Hello @fabiocav,

Well, I haven't contacted support. What I did in another "experiment" was to use an **in-process durable function** with the same **VNet, user managed identity and storage account** configuration that I have for the isolated one and run without any issue, so I don't think it's a VNet related issue.

**dotnet-isolated** is the requirement.

Thanks!

**Comment by ceekaay** [comment]
Same error ... is there a fix/workaround?

**Comment by SymbioticKilla** [comment]
Same issue here.
There is also good documented case on stackoverflow
https://stackoverflow.com/questions/74075905/http2connectionexception-http-2-error-code-protocol-error-0x1-error-when

**Comment by ceekaay** [comment]
These lines of code were the problem

` .ConfigureAppConfiguration((context, builder) =>
                {
                    builder.
                    AddEnvironmentVariables();
                })
`

I could solve the problem by **removing** ".AddEnvironmentVariables()". It is not required to load the environment variables in Azure.

**Comment by kshyju** [comment]
Closing this as #1547 will improve this behavior.
