### ISSUE TITLE
Azure function v4 using .NET 7 throws error Grpc.Core: Error loading native library

### ISSUE THREAD

**Issue by Yogeswaran66** [Azure/azure-functions-dotnet-worker#1522]
Machine - MacBook Pro M2
OS - macOS Ventura 13.0

.NET 7 azure function v4 throws the error on launch as below

Grpc.Core: Error loading native library. Not found in any of the possible locations: /Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/libgrpc_csharp_ext.arm64.dylib,/Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,/Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib.

The same function works fine on Windows machine.

**Comment by jviau** [comment]
This is a known issue with Durable extension and that Grpc.Core has no native support for MacOS.

See https://github.com/microsoft/durabletask-dotnet/issues/148 for a workaround
