### ISSUE TITLE
ServiceBusTrigger Still Performing Host Retries

### ISSUE THREAD

**Issue by phil000** [Azure/azure-functions-dotnet-worker#1523]
We are using the ServiceBusTrigger in C#.

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.7.0
Microsoft.Azure.Functions.Worker 1.13.0

I was under the impression that worker retries would be stopped, but it appears they have not?

_"The retry policy support in the runtime for triggers other than Timer and Event Hubs is being removed after this feature becomes generally available (GA). Preview retry policy support for all triggers other than Timer and Event Hubs will be removed in October 2022."_

When an exception occurs there are still exactly 5 retries performed. There appears to be no way to control this or turn it off as we have set host.json but it is ignored:

```"retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 0,
    "delayInterval": "00:00:01"
}
````

This is not the same thing as the subscriptions maxDequeueCount, as these retries are **also** performed separately.

How do we turn off host retries for ServiceBusTrigger as they fulfill no useful function.

![image](https://user-images.githubusercontent.com/9067236/236949037-b50d3d71-08c9-4a69-9a04-819d638ca566.png)

**Comment by satvu** [comment]
Guidance for configuring retries for different extensions can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries), and we would not expect `host.json` to configure retry policies for a Service Bus function.

The behavior you're seeing is definitely strange - do you have a minimal repro of your function? And what version of the functions runtime are you on (4.x)?

**Comment by phil000** [comment]
Thank you. We are familiar with how to configure retries. The thing is we don't want the runtime performing any retries.

Microsoft have stated that automatic retries for most of the triggers was being removed, as it is inherent in the trigger architecture.

_"The retry policy support in the runtime for triggers other than Timer and Event Hubs is being removed after this feature becomes generally available (GA). Preview retry policy support for all triggers other than Timer and Event Hubs will be removed in October 2022."_

We would not expect any retries performed by the Functions runtime. 

It is difficult to know why the retries are occurring so quickly as the message lock duration on the subscription is **5 minutes**. So we would expect in the event of exceptions the message would be retried in ... 5 minutes.

As you can see there are 5 retries all within a few milliseconds of each other.

Yes we are using:
FUNCTIONS_EXTENSION_VERSION: ~4
FUNCTIONS_WORKER_RUNTIME: dotnet-isolated

Microsoft.Azure.Functions.Worker 1.14.1
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.7.0

I will provide a minimal repo after testing the minimal repo produces the same issue.

**Comment by phil000** [comment]
**My Repo:**

```
namespace ServiceBusRepoFunction;

public class OrganisationDataSyncRepoFunction
{

	[Function("OrganisationDataSyncRepoFunction")]
	public void Run([ServiceBusTrigger("organisation-change-notification-dev", "repo-subscription")] string message, int deliveryCount, string messageId)
	{
		System.Threading.Thread.Sleep(100);
		long ticks = System.Diagnostics.Stopwatch.GetTimestamp();
		throw new Exception($"MessageId: {messageId}, DeliveryCount {deliveryCount}, Now: {DateTime.UtcNow:O}, Timestamp: {ticks}");
	}
}
```

Here is the setup.
I have a topic and subscription. The subscription has a retry count of 12, and a message lock duration of 5 minutes.
I put 1 single message into the topic and get 60 exceptions logged into App Insights all within a few seconds of each other.

From the logging though it appears the issue may be with the App Insights integration and logging, as all of the exceptions are logged at different "Event times" according to app insights, but all contain exactly the same exception message.

**OUTPUT:**

Result: Function 'OrganisationDataSyncRepoFunction', Invocation id '1c651e02-e39d-4869-a076-0f5a8c47e9d1': An exception was thrown by the invocation.
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 1, Now: 2023-06-08T00:10:08.9634721Z, Timestamp: 4500124478129
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 1, Now: 2023-06-08T00:10:08.9634721Z, Timestamp: 4500124478129
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 1, Now: 2023-06-08T00:10:08.9634721Z, Timestamp: 4500124478129
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 1, Now: 2023-06-08T00:10:08.9634721Z, Timestamp: 4500124478129
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 1, Now: 2023-06-08T00:10:08.9634721Z, Timestamp: 4500124478129

Result: Function 'OrganisationDataSyncRepoFunction', Invocation id '6d0707eb-2e25-49d5-87aa-9d81c5db75c1': An exception was thrown by the invocation.
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 2, Now: 2023-06-08T00:10:09.6880080Z, Timestamp: 4500131722971
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 2, Now: 2023-06-08T00:10:09.6880080Z, Timestamp: 4500131722971
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 2, Now: 2023-06-08T00:10:09.6880080Z, Timestamp: 4500131722971
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 2, Now: 2023-06-08T00:10:09.6880080Z, Timestamp: 4500131722971
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 2, Now: 2023-06-08T00:10:09.6880080Z, Timestamp: 4500131722971

Result: Function 'OrganisationDataSyncRepoFunction', Invocation id 'a934bb0f-dcfc-4956-bee1-0257c1a2b183': An exception was thrown by the invocation.
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 3, Now: 2023-06-08T00:10:10.6669955Z, Timestamp: 4500141512219
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 3, Now: 2023-06-08T00:10:10.6669955Z, Timestamp: 4500141512219
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 3, Now: 2023-06-08T00:10:10.6669955Z, Timestamp: 4500141512219
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 3, Now: 2023-06-08T00:10:10.6669955Z, Timestamp: 4500141512219
Exception: System.Exception: MessageId: 19c7995f-e437-4cc3-81db-0f91b4033b67, DeliveryCount 3, Now: 2023-06-08T00:10:10.6669955Z, Timestamp: 4500141512219

ETC

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9067236/86360e3c-c530-4025-8e8c-c69cfe0d16bf)

**Comment by phil000** [comment]
Single function invocation details. Exactly the same exception message logged multiple times but at different event times.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9067236/12788270-d40f-482f-a89f-07c63be7e27d)
