### ISSUE TITLE
Enhance Service Bus binding to enable calling service APIs

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#1538]
Issue to track enhancements to the Service Bus binding to enable use of SDK APIs from the .NET Worker binding targets.

**Comment by SeanFeldman** [comment]
With #1535 wrapping up, I can't wait to see this issue worked on, and finally have future parity to be able to be able to use Isolated Worker SDK across the board 🤞

**Comment by SeanFeldman** [comment]
🍾 when it's on NuGet
