### ISSUE TITLE
Doesn't work the option to disable W3C tracing

### ISSUE THREAD

**Issue by xin9le** [Azure/azure-functions-dotnet-worker#1573]
# Summary
The option to disable W3C tracing headers specified in *host.json* is not functioning as intended.

```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "httpAutoCollectionOptions": {
                "enableW3CDistributedTracing": false
            }
        }
    }
}
```

While it works correctly in the InProc model, as expected, it no longer has an effect on the worker side in the Isolated model. This is because host.json only affects the host side. Unfortunately, to my knowledge, there is no way to disable this configuration on the worker side.

# A simple case study

For example, when creating a flow using Azure Functions + ServiceBus as described below, the E2E transaction of Application Insights becomes chained, rendering it practically unusable (see the attached diagram).

1. Launch `HttpTrigger` (A).
1. Place the message into `ServiceBus Queue` (B).
1. Monitor B and trigger `ServiceBusTrigger` (C).
1. Re-enqueue the message from C to B.
    - Continue the recursive loop of `ServiceBusTrigger` until the condition is met.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/4776688/5aabe0b3-dee1-49f5-bc04-7389f6380085)

I understand that this requirement is a rare case, but it is indeed a fact that the option to apply settings to the worker side is no longer available in the Isolated model. I would greatly appreciate any possible improvements in this matter.

**Comment by fabiocav** [comment]
@xin9le can you share your worker bootstrapping code (or a simple repro showing how you have Application Insights setup)? I'm assuming you're using the [Application Insights](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview4) package here, can you confirm?

**Comment by fabiocav** [comment]
@brettsam / @jviau for any additional comments, if needed.

**Comment by xin9le** [comment]
@fabiocav 
A sample application which I created for above case study is attached. The implementation is a little dirty because it is a sample, but it is not long code and I think you will understand it well enough.

- [SampleApp.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/11902889/SampleApp.zip)

As you can see sample app, `Microsoft.Azure.Functions.Worker.ApplicationInsights v1.0.0-preview4` is used.

**Comment by xin9le** [comment]
Following code is one of the workaround I found. This may be a more appropriate approach than using `enableW3CDistributedTracing`.

```cs
var previous = Activity.Current;
try
{
    var client = new ServiceBusClient();
    var sender = client.CreateSender(queueName);
    Activity.Current = null;  // disable W3C tracing
    await sender.SendMessagesAsync(message);
}
finally
{
    Activity.Current = previous;  // resume W3C tracing
}
```

However, it's true that `enableW3CDistributedTracing` doesn't exhibit the same behavior as InProc model.

**Comment by jviau** [comment]
@xin9le the shared configuration you are using applies to the host process only. Worker process you need to configure distributed tracing separately, which is done directly through application insights SDK APIs.
