### ISSUE TITLE
Blocking issue with ASP.NET Core integration

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#1583]
> > Seems to be working now 🤷
> 
> Glad to know. Did you make any changes from your side to make it work? Would you mind sharing? Thanks!

I had to remove the `FunctionContext`. Which I think is related to this locking thing here.

> Looks like there's some sort of blocking issue ![image](https://user-images.githubusercontent.com/2263196/241691225-b741a6dc-d366-42b9-af38-f5c74b4aa15f.png)

Anyway `FunctionContext` was only used to access the logger instance, which I am now injecting into the constructor.

_Originally posted by @thushanperera95 in https://github.com/Azure/azure-functions-dotnet-worker/issues/1387#issuecomment-1570525309_

**Comment by fabiocav** [comment]
@thushanperera95 would you be able to share details on the code you've changed so we can have a repro to take a closer look at the issue? 

Thank you!

**Comment by thushanperera95** [comment]
I made a couple of changes:
1. Removed the `FunctionContext` from the HTTP trigger function.
2. Removed the addition of user secrets in the app builder.

``` c#
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

var builder = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureAppConfiguration(configuration => { configuration.AddUserSecrets<Program>(true); })
    .Build();

builder.Run();
```

However it seems to all work now even with those changes added back in! 
We haven't made any changes to the ARM template that's deployed to Azure, so not sure what happened.

**Comment by fabiocav** [comment]
@thushanperera95 would you be able to share a small repro so we can investigate the original issue.
