### ISSUE TITLE
FunctionsInDependencies using net7.0 isolated

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-functions-dotnet-worker#1608]
According to https://github.com/Azure/azure-functions-dotnet-worker/issues/1199 it should still be possible to use `<FunctionsInDependencies>` in .net isolated mode.

I am however trying this, without success. The `functions.metadata` build output file keeps ending up with an empty array, and when executing the function app no functions are found.

Is this functionality still possible in .net7.0?

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		
		<!-- Make sure functions of referenced assemblies get generated as well. -->
		<FunctionsInDependencies>true</FunctionsInDependencies>

		<!-- Handle azure functions missing assembly https://github.com/Azure/azure-functions-host/issues/5894 -->
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>

...
```

**Comment by devagarwal007** [comment]
Hey @NickSevens, Did you find any workaround to this? I am also facing the same issue.

**Comment by NickSevens** [comment]
@devagarwal007 I haven't, no :( still facing the same

**Comment by jviau** [comment]
With worker indexing, functions in dependencies should be detected and generated. Can you try with the latest SDK and see if it now works?

**Comment by niravdesaicricket** [comment]
I am using `<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.5" />` and still facing the same issue with isolated worker model and .net8.0.
