### ISSUE TITLE
"Value cannot be null. (Parameter 'uriString')." error with RabbitMQ extension in isolated mode

### ISSUE THREAD

**Issue by josealbertocoronado** [Azure/azure-functions-dotnet-worker#1620]
Hi.
Since I migrated my function to isolated mode my RabbitMQ triggers don't work anymore when running it locally. I always get the error described in the title.
I've tried with the different overloads of the method, always same result. 
Example 1:
With connection string:
`    [Function("MyRabbitMQTrigger")]
    public void Run(
    [RabbitMQTrigger(
        "myQueue",
        ConnectionStringSetting = "amqp://guest:guest@localhost:5672")] string inputEvent)
    {
        // My code
    }`

Example 2:
`    [Function("MyRabbitMQTrigger")]
    public static void Run(
    [RabbitMQTrigger(
        "localhost",
        "guest",
        "guest",
        5672,
        "myQueue")] string inputEvent)
    {
        // My code
    }`

Same result in both cases:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/132665924/81dd1f51-bd15-4572-a43d-5148677c4ea2)

Is there an issue or maybe I'm doing something wrong? Worth mentioning it used to work smoothly with web jobs.

**Comment by kshyju** [comment]
The value of `ConnectionStringSetting` should be an appsetting key where the value of that entry is the actual connection string.

For your local setting, you can add that entry to your local.settings.json file, under the "Values" portion of the JSON.

See the example under the "Samples" directory in the repo.

https://github.com/Azure/azure-functions-dotnet-worker/blob/5d49e0f358f53b8a9ed107aab78f41df8b6d20fe/samples/Extensions/RabbitMQ/RabbitMQFunction.cs#L14

**Comment by josealbertocoronado** [comment]
Hi.
I had tried taking the value from the settings too. And the reason it didn't work is because I was wrapping it with `%`, like this:
`[Function("MyRabbitMQTrigger")] public void Run( [RabbitMQTrigger( "%queueNameSetting%", ConnectionStringSetting = "%connectionStringSetting%")] string inputEvent) `

Interestingly, I need the `%` for the queue name setting but not for the connection string one.
That's a bit confusing tbh.

But anyway, working now. Thanks for that.
Cheers.

**Comment by kshyju** [comment]
Glad you got it working. Please let us know if you run into any other issues. Cheers :)
