### ISSUE TITLE
App Insights telemetry role name not correct after slot swap

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#1634]
App Insights relies on two mechanisms to keep the role name correct: the `WEBSITE_HOSTNAME` env var and the `WAS-DEFAULT-HOSTNAME` header that App Service sends with every request. The header is important because during a slot swap, the host name can change... thus changing the role name on telemetry.

However, in the Functions worker, this does not work. The header is never received (as HTTP isn't truly HTTP -- and most triggers are not HTTP anyway). Then, the fallback to WEBSITE_HOSTNAME ends up being incorrect and you end up with a prod site reporting its role name as "staging" (or something).

In Functions/WebJobs we've had logic here for many years that creates the role name based on `WEBSITE_SITE_NAME` and `WEBSITE_SLOT_NAME`. This has worked for us very reliably, so we'll move to that.

It may be worth the host sending this along during initialization -- but notes in the WebJobs code seem to indicate that these values can change, so we'd need to ensure that is not true before we rely on them that way.

WebJobs initializer: 
- https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsRoleEnvironmentTelmetryInitializer.cs

References to App Insights initializers:
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/Web/Web/AzureAppServiceRoleNameFromHostNameHeaderInitializer.cs
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/WindowsServer/WindowsServer/AzureWebAppRoleEnvironmentTelemetryInitializer.cs

**Comment by agrawalamit31** [comment]
@brettsam and @jviau  - We are facing this issue in each deployment. We need to restart our Azure function in Production as a temporary fix.
Is there any timeline you can suggest to fix this issue?

**Comment by agrawalamit31** [comment]
@brettsam - what changes we need to do at our end so that correct role name should log in App Insight telemetry via Azure function production slot?

**Comment by leozin** [comment]
@agrawalamit31 I guess the package wasn't published to NuGet yet.

**Comment by agrawalamit31** [comment]
@leozin , @fabiocav and @brettsam  - Can you please confirm the package name and version which has fix for this bug ?
