### ISSUE TITLE
[HttpTrigger] AspNetCoreIntegration 302 Redirect Not Working

### ISSUE THREAD

**Issue by sccrgoalie1** [Azure/azure-functions-dotnet-worker#1635]
I recently upgraded my project to try the preview of the AspNetCoreIntegration package.  Once I enabled this a simple redirect no longer works.

One that package is installed, this no longer works.  The page just stays at the function url.
```
 var response = req.CreateResponse(System.Net.HttpStatusCode.Redirect);
            response.Headers.Add("Location", "http://localhost:4200");
            return response;
````

Switching to the Asp.Net Core syntax produces the same result.
```
return new RedirectResult("http://localhost:4200");
```

```
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.11.0-preview1" OutputItemType="Analyzer" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.15.0-preview1" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.0.0-preview1" />
```

**Comment by fabiocav** [comment]
@sccrgoalie1 flagging this for investigation. Can you share more details about the behavior you're seeing?

Thanks for trying this out and providing feedback!

**Comment by sccrgoalie1** [comment]
The browser url does not change it stays as the function app url.  Using the network tab I can see the browser is trying to load the redirect page, but it hasn't actually performed the redirect.

**Comment by fabiocav** [comment]
@sccrgoalie1 can you confirm you've updated your code to use `HttpRequest` as opposed to `HttpRequestData`? Based on what you have above, doesn't look like that is the case.

**Comment by fabiocav** [comment]
Can you please share the entire function code? Thanks!

**Comment by sccrgoalie1** [comment]
> Can you please share the entire function code? Thanks!

I just updated to the latest preview2 and it's still occuring.  Here's the code and result.

```
using System.Net;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace TestRedirectFunction
{
    public class Function1
    {
        private readonly ILogger _logger;

        public Function1(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequest req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");

            return new RedirectResult("https://www.microsoft.com");
        }
    }
}
```

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2366790/a13c983b-7f65-4deb-b7fe-a37708b55fda)

**Comment by mattchenderson** [comment]
This should be addressed by https://github.com/Azure/azure-functions-host/pull/9412

It will be out with Host 4.25.0.
