### ISSUE TITLE
.net 8 preview support in isolated process

### ISSUE THREAD

**Issue by parmarnishant** [Azure/azure-functions-dotnet-worker#1641]
Hi,

I get the below error after changing TargetFramework to net8.0.
I am using Visual Studio 17.7.0 Preview 1.0.

-- Invalid combination of TargetFramework and AzureFunctionsVersion is set.
Also the .net 8 options is missing in the new project template.

**Comment by kshyju** [comment]
@parmarnishant .NET 8 (preview) support is not available yet, but will be coming out shortly. We will share an announcement when it is ready. I will also post an update to this issue. Thanks!

What .net8 features are you excited to try with azure functions?

**Comment by parmarnishant** [comment]
Hi @kshyju 

Thanks for the update.
I initially require Timer, Http and Queue triggers.
We will be using isolated mode.

Do we have estimated time frame when this will be available, so I can plan the work accordingly and not want to avoid alternatives if its coming sooner.

**Comment by kshyju** [comment]
Closing as answered.
