### ISSUE TITLE
Isolated Function Test Server like WebApplicationFactory(Microsoft.AspNetCore.Mvc.Testing) for .NET 6 Web Apps?

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/azure-functions-dotnet-worker#1642]
Do we have any test server like we have WebApplicationFactory(Microsoft.AspNetCore.Mvc.Testing) for .NET 6 Web Apps?

Is there any way we can invoke Program file from Unit Tests like we do for .NET 6 Web Apps

            var application = new WebApplicationFactory<Program>();

**Comment by satvu** [comment]
This is something we've been tracking and you can follow for updates here: https://github.com/Azure/azure-functions-dotnet-worker/issues/281. We are unable to prioritize this work item at the moment, but this is a feature we plan to have.

Closing in favor of main issue.
