### ISSUE TITLE
Remove enhanced http example from FunctionApp sample

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#1657]
Following merge of ASP.NET integration features into main, we need to remove the [ASP.NET example](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/FunctionApp/HttpProxyTrigger) from FunctionApp which uses the non-ASP.NET model for isolated. 

The ASP.NET integration example should be added to a new sample app dedicated to ASP.NET Integration samples.

**Comment by SeanFeldman** [comment]
@satvu, are you referring to this sample? https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/Http/HttpFunction.cs

If yes, I'd suggest not removing but rather adding. The "original" HTTP model for Isolated Worker SDK has been long enough in the wild as a supported model. Removing the sample is not necessarily good if it's still supported. But, adding a note to guide developers to prefer a new model would be welcomed.

"Original" and "new" are really not ideal. We need to come up with better names 🙂 Something like "ASP.NET compliant" and "non ASP.NET compliant". Mouthful but less ambiguous.

**Comment by satvu** [comment]
@SeanFeldman Not that sample - I meant this one: https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/FunctionApp/HttpProxyTrigger. Let me reword/edit the original description, I see where the confusion is coming from :) I want to remove the _ASP.NET integration example_ from the function app sample that is _not ASP.NET compliant_. 

We were using it in the feature branch for testing/validation and took those changes over to main, but working on cleanup now. We are now moving forward to create a separate, dedicated sample app for ASP.NET scenarios in this folder: https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples. 

Ack on the better names - I like your suggestion.
