### ISSUE TITLE
Blazor Static Web App: There is no Functions runtime available that matches the version specified in the project - VS2022 - .NET7

### ISSUE THREAD

**Issue by mrctito** [Azure/azure-functions-dotnet-worker#1678]
I created a Blazor Static App project following Microsoft's step-by-step guide from a GitHub repository, but I'm encountering this error:

<img width="749" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/809686/d00b9d0b-6e1b-491a-97e7-a43077d7bb7d">

I am using Visual Studio Community 2022 fully updated.

If I update the packages below, the error disappears, but the application stops running.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/809686/0f7e8365-ba22-4118-87cd-20c5298b0a29)

I appreciate any help in advance.

**Comment by fabiocav** [comment]
@mrctito do you have the project in repo we can look at? Are you targeting .NET 8?

**Comment by mrctito** [comment]
Hi @fabiocav, I have just added you to the repo.

Please let me know if you need some additional info.

Thank you!

**Comment by kshyju** [comment]
@mrctito Are you still experiencing this error, If so, could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great. Thanks!
