### ISSUE TITLE
Cannot download file on dotnet-isolated

### ISSUE THREAD

**Issue by SzymonSel** [Azure/azure-functions-dotnet-worker#1679]
We have a number of Azure function running with .net 6 running `In-Process` and successfuly returning file content. Recently we've been trying out Azure Functions with .NET 7`in an isolated worker process. Sadly the same source code doesn't return the file, but instead the raw content as below:
```
{
  "Version": "1.1",
  "Content": {
    "Headers": [
      {
        "Key": "Content-Type",
        "Value": [
          "text/plain"
        ]
      },
      {
        "Key": "Content-Disposition",
        "Value": [
          "attachment; filename=example.txt"
        ]
      }
    ]
  },
  "StatusCode": 200,
  "ReasonPhrase": "OK",
  "Headers": [],
  "TrailingHeaders": [],
  "RequestMessage": null,
  "IsSuccessStatusCode": true
}
```

We've tried to explicitly add the content disposition, but to no avail.

```
[Function("myFunction")]
public static  async Task<HttpResponseMessage>Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{           
    string csv = "Hey";

    byte[] filebytes = Encoding.UTF8.GetBytes(csv);

    var response = new HttpResponseMessage(HttpStatusCode.OK);
    response.Content = new ByteArrayContent(filebytes);
    response.Content.Headers.ContentType = 
        new MediaTypeHeaderValue("text/plain");
        response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment")
        {
            FileName = "example.txt" 
        };
    return response;
}
```

**Comment by jviau** [comment]
@brettsam, @satvu, @fabiocav 

Is this a known limitation / behavior of HTTP in out of proc? Will it be addressed by the AspNetCore proxying work?

**Comment by SzymonSel** [comment]
Any progress or eta on this? Best

**Comment by caisback** [comment]
Ttry this;

```
var response = req.CreateResponse(HttpStatusCode.OK);
response.Headers.Add("Content-Type", "application/octet-stream");
response.Headers.Add("Content-Disposition", $"attachment; filename=\"{fileName}\"");
response.Headers.Add("Access-Control-Expose-Headers", "Content-Disposition");
await response.WriteBytesAsync(fileData);

```

**Comment by mattchenderson** [comment]
Closing this item as stale; this should have been resolved with [ASP.NET Core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration), and there is a [sample for this scenario](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/AspNetIntegration/FileDownload.cs). If there is still any issue with this, please reopen the issue.
