### ISSUE TITLE
Cannot add telemetry processor, telemetry processor is never called

### ISSUE THREAD

**Issue by leidegre** [Azure/azure-functions-dotnet-worker#1693]
I'm using the Microsoft.Azure.Functions.Worker.ApplicationInsights.1.0.0-preview4 NuGet package to add application insights to my isolated worker and it works but I'm also getting telemetry that I really don't care about.

My setup looks something like this but despite all that I've tried I never get the telemetry processors to actually be called.

```cs
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder => {
      // https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627
      builder
          .AddApplicationInsights()
          .AddApplicationInsightsLogger();
    })
    .ConfigureServices(services => {
#if DEBUG
      services.AddApplicationInsightsTelemetryProcessor<IgnoreMangoHookRouter>();
      services.Configure<TelemetryConfiguration>(telemetryConfiguration => {
        telemetryConfiguration.TelemetryProcessorChainBuilder.Use(processor => {
          return processor; // breakpoint never hit
        });
      });
#endif
      Tessin.Payments.Host.Startup.Configure(services);
    })
    .ConfigureLogging((ctx, logging) => {
      logging.AddFilter("Microsoft.EntityFrameworkCore", LogLevel.Warning); // Workaround for category overrides from Azure Functions
    })
    .Build();

#if DEBUG
// the timer trigger run at startup is unreliable...
var cts = new CancellationTokenSource();
var hookRouter = new Tessin.Payments.Host.MangoHookRouter(host.Services);
hookRouter.Run(cts.Token);
#endif

host.Run();

// shutting down
#if DEBUG
cts.Cancel();
#endif

#if DEBUG
class IgnoreMangoHookRouter : ITelemetryProcessor {
  public void Process(ITelemetry item) {
    throw new NotImplementedException(); // breakpoint never hit
  }
}
#endif
```

**Comment by leidegre** [comment]
I've pushed my repo here https://github.com/leidegre/experiments-app-insights-worker

It's very similar to the code above but not exactly the same though. I'm seeing the exact same problem.

Dug around the source of the `AddApplicationInsights` extension and eventually found this

```cs
services.AddSingleton<ITelemetryInitializer, AzureWebAppRoleEnvironmentTelemetryInitializer>();
AddCommonInitializers(services);
AddCommonTelemetryModules(services);
AddTelemetryChannel(services);
services.TryAddSingleton<IConfigureOptions<ApplicationInsightsServiceOptions>, DefaultApplicationInsightsServiceConfigureOptions>();
AddDefaultApplicationIdProvider(services);
AddTelemetryConfigAndClient(services);
AddApplicationInsightsLoggerProvider(services);
```

So, looked into `AddCommonTelemetryModules`

```
services.AddSingletonIfNotExists<ITelemetryModule, DiagnosticsTelemetryModule>();
services.AddSingleton<ITelemetryModule, AppServicesHeartbeatTelemetryModule>();
services.AddSingleton<ITelemetryModule, AzureInstanceMetadataTelemetryModule>();
services.AddSingleton<ITelemetryModule, PerformanceCollectorModule>();
services.AddSingleton<ITelemetryModule, QuickPulseTelemetryModule>();
AddAndConfigureDependencyTracking(services);
services.AddSingleton<ITelemetryModule, EventCounterCollectionModule>();
```

But when I try to use `services.AddSingleton<ITelemetryModule, ...>()` I don't get anything to happen. How can that be?

**Comment by leidegre** [comment]
Another thing that I just noticed when I looked at the telemetry from my actual app and repo (while they are using the same NuGet packages)

The telemetry for my app has the SDK version set to `azurefunctions-netiso: 1.0.0-preview4+11ae12b306ee3512d8a7d1c285` while the telemetry from my repo has the SDK version set to `azurefunctions: 4.21.1.20667` which makes me think they aren't even doing the same things and my repo isn't catching the HTTP requests that poll youtube.

**Comment by leidegre** [comment]
Okay, so telemetry processor don't work but at least I found the cause of the the missing telemetry dependency issue.

This version doesn't work. I don't know what was changed between `1.14.0` and `1.14.1` but it broke `Microsoft.Azure.Functions.Worker.ApplicationInsights-1.0.0-preview4` functionality.

```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.14.1" />
```

**Comment by jviau** [comment]
@leidegre you are missing the constructor for your `ITelemetryProcessor`. You must have a constructor that takes in `ITelemetryProcessor`:

``` CSharp
class Processor : ITelemetryProcessor
    {
        private readonly ITelemetryProcessor _next;

        public Processor(ITelemetryProcessor next)
        {
            _next = next;
        }

        public void Process(ITelemetry item)
        {
            throw new System.NotImplementedException();
        }
    }
```
