### ISSUE TITLE
InvocationId and LogLevel Missing from customDimensions

### ISSUE THREAD

**Issue by edionu97** [Azure/azure-functions-dotnet-worker#1706]
Hello, we recently updated from an older version of **Microsoft.Azure.Functions.Worker.*** to the latest avaible version

- Microsoft.Azure.Functions.Worker 1.16.0
- Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.11.0
- Microsoft.Azure.Functions.Worker.Sdk 1.11.0

After the update, for some reason, the **_InvocationId_** and the **_LogLevel_** values are missing from the **customDimensions** and because of this, most part of our logs are not displayed in the **Azure Function's Monitor** section:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/36416157/12120311-d40e-4243-b2d0-1f66540cc34e)

The query which is generaterd when clicking the option _**Run query in Application Insighs**_  from the azure function invocation is added below and, as expected, displays the same result as in the image above:

```
union traces
| union exceptions
| where timestamp > ago(30d)
| where operation_Id == 'op_id_value_here'
| where customDimensions['InvocationId'] == 'invocation_id_value_here'
| order by timestamp asc
| project
    timestamp,
    message = iff(message != '', message, iff(innermostMessage != '', innermostMessage, customDimensions.['prop__{OriginalFormat}'])),
    logLevel = customDimensions.['LogLevel']
```

What we've noticed is that if we're removing the `customDimensions['InvocationId'] == 'invocation_id_value_here'` filter, we obtain all the information which is logged by the function (as before updating to latest worker.* version).
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/36416157/d17fd455-b13c-45e4-bf6a-d4b6400c4bd4)

What worth mentioning is that for the logs which appear in the **_Monitor blade_** (for a particular invocation) we have in **_customDimensions_** object both the _**InvocationId**_ and **_LogLevel_** properties, as shown in the image below:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/36416157/488e4d5e-19d7-4167-846e-a5ed507246ec)

But for the logs which are not displayed in  the **_Monitor blade_** we do not have those properties, and instead of **_InvocationId_** property we have _**AzureFunctions_InvocationId**_ (which has the same value as InvocationId):
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/36416157/ad203a12-fc5f-4450-887d-c09ece3fefc6)

**Comment by fabiocav** [comment]
Flagging for AI GA review.

**Comment by brettsam** [comment]
It's not clear how you're writing out the logs from your function -- or whether you're using the latest [worker ApplicationInsights preview package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights)?

Those `ApplicatonInsights_InvocationId` values come from the worker's logger scope, so I would think that means you are writing directly to App Insights from your worker?

**Comment by brettsam** [comment]
I decided not to include LogLevel as there's not much value there. LogLevel maps to the severityLevel in App Insights already.
