### ISSUE TITLE
Operation Id missing in Azure porta;

### ISSUE THREAD

**Issue by nksubramanian** [Azure/azure-functions-dotnet-worker#1710]
I have created a console application .net 7 and I am able to log from my local environment to the azure portal. However, the operation_id in Azure portal is missing . Could you help?
![opid](https://github.com/Azure/azure-functions-dotnet-worker/assets/79507423/d1f3e989-99e6-4480-a042-e98aa54b14c8)

**Comment by kshyju** [comment]
@nksubramanian When you deploy & run the function app in azure, Is everything working as expected?

**Comment by nksubramanian** [comment]
@kshyju  i have not tried deploying. But this is a console app asp.net core . I will try deploying and let you know. Are there situations where logs can be present without operation id ? There's another strange behaviour, sometimes I get operation Id and sometimes without operation Id.

**Comment by jviau** [comment]
@nksubramanian is this a function app? If so, can you include more details about your app and provide a minimal repro?
