### ISSUE TITLE
QueueOutput in TimerTrigger does not work

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-dotnet-worker#1711]
Hi,
I noticed that the TimerTrigger doesn't trigger a QueueOutput when working in a .NET isolated C# project. This capability was working fine in a previous release. Here are the dependencies we have installed:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.1.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.1.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.11.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.16.0" />
```

Here's some pseudo code to simulate the error:

```
[Function("reminder")]
[QueueOutput("mail-queue")]
public async Task<List<NotificationItem>> RunAsync([TimerTrigger("0 0 0 * * *")] ScheduleInfo myTimer)
{
    List<NotificationItem> items = new List<NotificationItem>();
   items .Add(new NotificationItem());
   return items ;
}

[Function("queue")]
public async Task RunAsync([QueueTrigger("mail-queue")] NotificationItem notificationItem, ILogger log)
{
    ....
}
```

We are using dependency injection for both functions.

We are able to trigger the `mail-queue` without any issues by using an HTTP trigger and an output binding definition like this one:

```
public class MailNotificationResponse
{
    [QueueOutput("mail-queue")]
    public List<NotificationItem> Notifications { get; set; } = new List<NotificationItem>();

    public HttpResponseData HttpResponse { get; set; }
}
```

Based on our analysis, we believe this is a bug. We appreciate your help in resolving this issue.

Thank you,
Patrick

**Comment by kshyju** [comment]
@plamber Do you have the storage connection for the queue output binding setup correctly? How and where? I was able to verify it works (Timer was firing as expected and writing to the queue) with the version of packages you shared.

I see your timer trigger is set to be executed at 12:00 AM everyday. I changed to that every 15 seconds for my quick validation.
```csharp
public class TimerFunction
{
    private readonly ILogger _logger;

    public TimerFunction(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<TimerFunction>();
    }

    [Function("reminder")]
    [QueueOutput("mail-queue", Connection = "MyCon")]
    public async Task<List<NotificationItem>> RunAsync([TimerTrigger("*/15 * * * * *")] MyInfo myTimer)
    {
        _logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        await Task.Delay(200); // Simulating some delay.
        List<NotificationItem> items = new List<NotificationItem>
        {
            new NotificationItem() { Title = $"Foo-{DateTime.Now}" }
        };

        return items;
    }
}
```

My local.settings.json content where I specified the connection string value:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "MyCon": "MyStorageConnectionStringHere"
  }
}
```
and finally the relevant part of my .csproj which lists the package references I used.

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.16.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="5.1.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.11.0" />
  </ItemGroup>
```

I also noticed you were trying to use `ILogger` as a parameter in the QueueTrigger function. That will not work in isolated model. You should be able to do constructor injection as shown above.

**Comment by plamber** [comment]
Hi @kshyju,
thank you for your feedback. I found the issue on our end.

We tried to call the Timer trigger from an HTTP trigger during development just by calling the function. The binding will not be considered in such a situation.

What is the best way to call a timer trigger from code on local development and ensure that the output bindings are being processed? I found this technique https://learn.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http but it seems to be related to a hosted Azure function.

Thank you for your help,
Patrick

**Comment by kshyju** [comment]
> We tried to call the Timer trigger from an HTTP trigger during development

How are you doing this? How can an http trigger invoke the timer trigger? Could you elaborate on this? @plamber

**Comment by plamber** [comment]
Hi @kshyju,

During a development session, it can be beneficial to invoke a timetrigger without modifying the cronjob. To achieve this, we typically create HTTP functions that developers can use to proactively trigger the timertrigger.

If the timertrigger doesn't have any output bindings, the function execution works smoothly. Everything runs as expected, and there are no side effects. However, when the timertrigger has output bindings, the capabilities of these output bindings are not taken into account.

I'm curious to know if it's possible for a software developer to initiate a timertrigger through an HTTP call, similar to what can be done on Azure.

Thank you for your feedback.

Best regards,
Patrick

**Comment by kshyju** [comment]
> I'm curious to know if it's possible for a software developer to initiate a timertrigger through an HTTP call, similar to what can be done on Azure.

Tagging @mattchenderson to provide his insights.

**Comment by kshyju** [comment]
@plamber You should be able to execute the timer trigger by calling the http endpoint as mentioned in "[Manually run a non HTTP-triggered function](https://learn.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http)" in your local environment as well. When running it locally, you do not need to provide function key in the request.

Follow the instructions in the documentation linked above and let us know if you run into issues.

**Comment by plamber** [comment]
Thank you @kshyju,
Not sure why I missed it. I was able to perform the activities on a queue.

Closing the issue

br,
Patrick
