### ISSUE TITLE
Durable Functions Isolated Worker Sample?

### ISSUE THREAD

**Issue by danielniccoli** [Azure/azure-functions-dotnet-worker#1729]
Would it be possible to also provide a simple example for a Azure Durable Function using the isolated worked, where the actual call to the Graph API is made from an activity. These samples exist for non-durable Azure Functions, but they're difficult to transfer to the Durable functions for beginners.

**Comment by jviau** [comment]
I don't know if this fits in this repository. It may fit better with the durable extension: https://github.com/Azure/azure-functions-durable-extension

**Comment by danielniccoli** [comment]
> I don't know if this fits in this repository. It may fit better with the durable extension: https://github.com/Azure/azure-functions-durable-extension

Maybe. Honestly, the repo fragmentation is nothing but confusing. I decided to not use C# due to the lack of documentation.

I'll also save @bhagyshricompany some work and close this before he does anyway.
