### ISSUE TITLE
Default logger with context of Function name

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-dotnet-worker#175]
Seems repetative that so many functions will have this pattern:

```cs
[Function("FunctionName")]
        public async Task<HttpResponseData> CreatePostAsync(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "post")] HttpRequestData req,
            FunctionContext context)
        {
            var logger = context.GetLogger("FunctionName");
```

I think `context` would know at this point what the Function Name is?  Can the default `context.GetLogger()` just default to returning an ILogger with the `context.FunctionDefinition.Metadata.Name`
(not a P0, but would be a nice to have)

**Comment by fabiocav** [comment]
Yes, that can be done.
