### ISSUE TITLE
Unexpected "Unable to cancel invocation" warning log

### ISSUE THREAD

**Issue by nickljones** [Azure/azure-functions-dotnet-worker#1753]
We are intermittently seeing a log warnings like `Unable to cancel invocation "86454ddc-c376-4ee8-992b-90f2992e8490"` without an associated exception. These are being raised from this line of code:

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Grpc/Handlers/InvocationHandler.cs#L148

I may be missing something, but that looks where it is being raised is part of the normal expected successful flow, so I am surprised a warning is being raised in this case, particularly since the method then returns `true` to indicate success.

**Comment by liliankasem** [comment]
Thanks for catching this, we should not be logging "unable to cancel" here. I've opened a PR to address this
