### ISSUE TITLE
Publish command to local machine or portal failed with error below ( as I am trying to generate function.json file)

### ISSUE THREAD

**Issue by Basel78** [Azure/azure-functions-dotnet-worker#1754]
Hi,
I am trying to get function.json file generated for dotnet-isolated csharp azure function as I need it in terraform templaet to create az function in azure app,, hence I wanted to publish az function wit SB binding running locally without a issue, but it keep getting failed with below error,,,

Unable to move file "C:\Users\****\AppData\Local\Temp\d1pk0t2s.ab0\publishout\Microsoft.AspNetCore.Mvc.Abstractions.dll" to "C:\Users\****\AppData\Local\Temp\d1pk0t2s.ab0\publishout\bin\Microsoft.AspNetCore.Mvc.Abstractions.dll". Cannot create a file when that file already exists.

how we can solve this issue?

can you please redirect me to clear article about function.json format for service bus binding!

**Comment by kshyju** [comment]
Can you try clearing your `AppData\Local\temp` folder content and see that resolves the problem for you? If you are using VS IDE, Did you try the "Clean/Clean solution" option before trying to build/publish?
