### ISSUE TITLE
Http Template needs a piece of reading the body

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-dotnet-worker#176]
I think it's super nice that our v2 / v3 templates include the `StreamReader` so folks know how to read the body. I think something similar would be beneficial here:

https://github.com/Azure/azure-functions-templates/blob/400eda3c9c00bcbb913ab82e6e10afe5e6e45290/Functions.Templates/Templates/HttpTrigger-CSharp/HttpTriggerCSharp.cs#L24

**Comment by fabiocav** [comment]
The scenario you've shared above is reading as a `string`, is that covered by the `ReadAsString[Async]` methods? Is the goal to show how to read a `Stream`?

**Comment by jeffhollan** [comment]
Oh that's great too! I didn't even notice that (which also makes me think this is good to just have in default template).  

I just think since a ton of folks will read the body, makes sense to add a sample of how best to read.  Esp. with things like Async where we see time and time again people can screw up.  I think the template we have today is a good example:

- Read body as a string
- Serialize string into dynamic

Both useful patterns to just make sure people do it the 'right' way

**Comment by fabiocav** [comment]
We should update the templates to use the methods we've exposed, which is actually a lot simpler than using the `StreamReader`.

For your second scenario, are you referring to the request or response? If the request, are you talking about reading the body payload and deserialize into an object?

We also have methods on the response to write the content and will be expanding both, request and responses, with new ones (e.g. `ReadFromJsonAs<T>`, etc.)

**Comment by jeffhollan** [comment]
Ah cool - yes I meant deserializing the request.  In short I think the vast majority of folks will use an HTTP trigger to send some JSON, so the easier we can make the template to show them how to get the JSON values, the better.  Sounds like this could become a near single line with new SDKs.  Let's add that to the template

**Comment by fabiocav** [comment]
Yeah! That's the goal; to make those scenarios dead simple with friendly APIs. 

We were blocking on the "configurable serializer" support before we could add the JSON APIs, but now that it's there, we can implement them and you can choose which serialization stack you want to use (e.g. System.Text.Json, JSON.NET)

**Comment by jeffhollan** [comment]
Great as long as we are aligned to add “retrieving a json value or null” into the template like we do today - I’ll leave it up to you all on what’s the best pattern to highlight there

**Comment by josmithua** [comment]
> Yeah! That's the goal; to make those scenarios dead simple with friendly APIs.
> 
> We were blocking on the "configurable serializer" support before we could add the JSON APIs, but now that it's there, we can implement them and you can choose which serialization stack you want to use (e.g. System.Text.Json, JSON.NET)

@fabiocav Quick question which I didn't want to post a new issue for... What's the correct way to set a different default ObjectSerializer, such as `NewtonsoftJsonObjectSerializer` in the host builder?

**Comment by kshyju** [comment]
> > Yeah! That's the goal; to make those scenarios dead simple with friendly APIs.
> > We were blocking on the "configurable serializer" support before we could add the JSON APIs, but now that it's there, we can implement them and you can choose which serialization stack you want to use (e.g. System.Text.Json, JSON.NET)
> 
> @fabiocav Quick question which I didn't want to post a new issue for... What's the correct way to set a different default ObjectSerializer, such as `NewtonsoftJsonObjectSerializer` in the host builder?

@josmithua Please refer [this sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Configuration/Program.cs#L15). Let us know if you run into issues with that.

**Comment by brettsam** [comment]
Agree that we should make the in-proc template match the isolated template as near as possible:

- in-proc: https://github.com/Azure/azure-functions-templates/blob/400eda3c9c00bcbb913ab82e6e10afe5e6e45290/Functions.Templates/Templates/HttpTrigger-CSharp/HttpTriggerCSharp.cs#L24
- isolated: https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/HttpTrigger-CSharp-Isolated/HttpTriggerCSharp.cs

**Comment by mattchenderson** [comment]
Asserting this as no longer necessary with the templates using ASP.NET Core integration by default for new TFMs.
