### ISSUE TITLE
Performance degradation and 429 errors

### ISSUE THREAD

**Issue by MishaD87** [Azure/azure-functions-dotnet-worker#177]
Hello
I just updated my Azure functions to .net5 worker and published it to Azure (Consumption plan).
I noticed huge performance degradation and I started getting 429 errors pretty a lot.
I partially solved a problem by adding this into my host.json and by decreasing an amount of requests from clients to Azure functions, but the problem still exists. And it also increased a price multiple times on Consumption plan.
    "maxOutstandingRequests": 400,
      "maxConcurrentRequests": 400,
      "dynamicThrottlesEnabled": true

Can you please advice what can I do?
- Amount of functions calls decreased (I did it in order make it work at least somehow)
![image](https://user-images.githubusercontent.com/36815881/108973151-16d20780-7695-11eb-8802-bb5829b38f08.png)
- Amount of connections increased a lot
![image](https://user-images.githubusercontent.com/36815881/108973497-74665400-7695-11eb-9ef6-7e060f4d21f9.png)
- Response time increased a lot
![image](https://user-images.githubusercontent.com/36815881/108974464-8b597600-7696-11eb-94be-33668c8d0e34.png)
- Amount of Function execution units increased around 100 times (from 5b per hour to 500 b)
![image](https://user-images.githubusercontent.com/36815881/108978393-97473700-769a-11eb-8751-cfdb9630605a.png)

**Comment by fabiocav** [comment]
@brettsam FYI. Relevant to the perf test scenarios we've discussed.

**Comment by brettsam** [comment]
@MishaD87 -- is it possible for you to share a sample app that shows this? Also, if you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

Thanks for reporting this!

**Comment by MishaD87** [comment]
Below there is a typical function that was called
Inside highlighted methods there is the following logic (everything is async):
- DI container initialization with not too many services (Castle Windsor)
- 3-5 calls to database using NHibernate (database is on SQL server located on the same Resource group with Azure function)
- 1 call to Azure key vault (located on the same Resource group)
![image](https://user-images.githubusercontent.com/36815881/109833304-35666e80-7c52-11eb-96bd-fa8a612bd6a4.png)

There are 2 different functions like this that were called the following way (Sometimes I also call other functions, but this happens several times per day in total):
1) Around 120 clients located on different places in the world
2) Each client was making periodically 3 calls (1 call to Function1 every 5 minutes, 1 call to Function1 every 1 minute and 1 call to Function2 every 5 minutes).
3) It was possible that the same client could make all 3 calls at the same time (every call is managed in separate thread)
So total amount is around 10K calls per hour (3 per second) 
4) In the beginning it was possible that all 120 clients could make first 3 calls almost at the same time. I though that this can be a problem and added "await Task.Delay(_random.Next(0-120 seconds)" on startup of every client. But this did not help


Before migration to .Net 5 average response time was 1 seconds (with 3 API call per second rate)
After migration average response time became 120 seconds (with 3 API call per second rate)
After I reduced API calls rate to 1 call every 8 seconds (current setup) - I am getting this picture with average response time (on average 2-8 seconds, with big spikes sometimes)
![image](https://user-images.githubusercontent.com/36815881/109837214-ff2aee00-7c55-11eb-8946-9c538f6ce582.png)


I sent you function name privately. Note that currently I removed all not important calls and decreased frequency of main call. So now every client calls just 1 function every 15 minutes.

Let me know if this information is enough for you

**Comment by fabiocav** [comment]
This description helped. The function information will be helpful, but I believe I understand what’s causing this. Will have a PR shortly

**Comment by vtremb** [comment]
@fabiocav Do you have any update on this issue? It's affecting our migration to NET 5.

**Comment by fabiocav** [comment]
Closing stale issue. This should be resolved.
