### ISSUE TITLE
Error starting when deployed to Azure Function App

### ISSUE THREAD

**Issue by aaronzhongg** [Azure/azure-functions-dotnet-worker#178]
I have a timer triggered function app running on Azure which seems to have a problem starting.

Some other points to note:
- WEBSITE_RUN_FROM_PACKAGE = 1
- FUNCTIONS_WORKER_RUNTIME = dotnet-isolated
- "Azure Functions runtime is unreachable"
- Trigger column is empty

![image](https://user-images.githubusercontent.com/14045995/108128600-de20b400-7111-11eb-9920-39b2406e7a5b.png)

```
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:java
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:node
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:powershell
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Initializing Warmup Extension.
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Initializing Host. OperationId: '0f237d85-99ac-4790-8735-9e7dc9cd05b1'.
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Host initialization: ConsecutiveErrors=0, StartupCount=3, OperationId=0f237d85-99ac-4790-8735-9e7dc9cd05b1
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
ApplicationInsightsLoggerOptions { "SamplingSettings": { "EvaluationInterval": "00:00:15", "InitialSamplingPercentage": 100.0, "MaxSamplingPercentage": 100.0, "MaxTelemetryItemsPerSecond": 20.0, "MinSamplingPercentage": 0.1, "MovingAverageRatio": 0.25, "SamplingPercentageDecreaseTimeout": "00:02:00", "SamplingPercentageIncreaseTimeout": "00:15:00" }, "SamplingExcludedTypes": null, "SamplingIncludedTypes": null, "SnapshotConfiguration": null, "EnablePerformanceCountersCollection": true, "HttpAutoCollectionOptions": { "EnableHttpTriggerExtendedInfoCollection": true, "EnableW3CDistributedTracing": true, "EnableResponseHeaderInjection": true }, "LiveMetricsInitializationDelay": "00:00:15", "EnableLiveMetrics": true, "EnableDependencyTracking": true, "DependencyTrackingOptions": null }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
LoggerFilterOptions { "MinLevel": "None", "Rules": [ { "ProviderName": null, "CategoryName": null, "LogLevel": null, "Filter": "<AddFilter>b__0" }, { "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider", "CategoryName": null, "LogLevel": "None", "Filter": null }, { "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider", "CategoryName": null, "LogLevel": null, "Filter": "<AddFilter>b__0" }, { "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider", "CategoryName": null, "LogLevel": "Trace", "Filter": null } ] }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
LoggerFilterOptions { "MinLevel": "None", "Rules": [ { "ProviderName": null, "CategoryName": null, "LogLevel": null, "Filter": "<AddFilter>b__0" }, { "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider", "CategoryName": null, "LogLevel": "None", "Filter": null }, { "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider", "CategoryName": null, "LogLevel": null, "Filter": "<AddFilter>b__0" }, { "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider", "CategoryName": null, "LogLevel": "Trace", "Filter": null } ] }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FunctionResultAggregatorOptions { "BatchSize": 1000, "FlushTimeout": "00:00:30", "IsEnabled": true }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
SingletonOptions { "LockPeriod": "00:00:15", "ListenerLockPeriod": "00:01:00", "LockAcquisitionTimeout": "10675199.02:48:05.4775807", "LockAcquisitionPollingInterval": "00:00:05", "ListenerLockRecoveryPollingInterval": "00:01:00" }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
BlobsOptions { "MaxDegreeOfParallelism": 8 }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
QueuesOptions { "BatchSize": 16, "NewBatchThreshold": 8, "MaxPollingInterval": "00:01:00", "MaxDequeueCount": 5, "VisibilityTimeout": "00:00:00" }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
HttpOptions { "DynamicThrottlesEnabled": true, "MaxConcurrentRequests": 100, "MaxOutstandingRequests": 200, "RoutePrefix": "api" }
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Starting JobHost
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Starting Host (HostId=<omitted>, InstanceId=be22fb9b-73fb-41d7-bdc7-0aba6d6e5687, Version=3.0.15371.0, ProcessId=1748, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~3)
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Loading functions metadata
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:java
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:node
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:powershell
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
1 functions loaded
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Generating 1 job function(s)
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Found the following functions: Host.Functions.<omitted>
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Initializing function HTTP routes No HTTP routes mapped
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Host initialized (68ms)
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Executing 'Functions.<omitted>' (Reason='Timer fired at 2021-02-16T22:06:52.6641724+00:00', Id=5a92a194-de30-4c3d-828f-49001b460935)
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2021-02-16T21:05:00.0000000+00:00
Severity level: Information
2/17/2021, 11:06:52 AM - TRACE
Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover
Severity level: Error
```

**Comment by louisoftokyo** [comment]
Getting the same issue - TimerTriggers not working with the same symptoms as above. I'm also getting the following output when I publish from the command line, seemingly saying that it can't find my trigger:

```
Getting site publishing info...
Creating archive for current directory...
Uploading 13.91 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Functions in myfunctionapplication:
    UpdateData - [No Trigger Found]
```

It works as expected when run locally.

**Comment by bryandh** [comment]
I am getting the same issue but with an HttpTrigger. I published the SampleApp from this repo, without any changes, to my newly created Azure Function App and *all* functions and therefore all trigger types appear as `[No Trigger Found]` in the terminal response. The triggers also show up as blank just like @aaronzhongg is experiencing in the Azure Portal.

My Azure Function App's Configuration looks like this:
```
AzureWebJobsStorage = DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX;EndpointSuffix=core.windows.net
FUNCTIONS_EXTENSION_VERSION = ~3
FUNCTIONS_WORKER_RUNTIME = dotnet-isolated
WEBSITE_RUN_FROM_PACKAGE = 1
```

**Comment by bryandh** [comment]
Some screenshots of my publish process and Azure environment to further illustrate the problem I'm experiencing:

_Config in Azure:_
<img width="680" alt="Screenshot 2021-03-11 at 13 01 49" src="https://user-images.githubusercontent.com/11500592/110784665-3dce3300-826a-11eb-8a90-f38fa5be1fa6.png">

_Publish to Azure Function App result:_
`func azure functionapp publish temp-net50-function-app`

<img width="373" alt="Screenshot 2021-03-11 at 13 00 49" src="https://user-images.githubusercontent.com/11500592/110784701-47f03180-826a-11eb-9291-5cdeb3a80577.png">

_Azure Function App functions listing:_
Note that the 'Azure Functions runtime is unreachable' and the Trigger column completely empty as the triggers don't seem to be recognized.

<img width="617" alt="Screenshot 2021-03-11 at 13 02 14" src="https://user-images.githubusercontent.com/11500592/110784725-4fafd600-826a-11eb-95ce-9baa0d454696.png">

**Comment by louisoftokyo** [comment]
@bryandh @aaronzhongg Has anyone managed to solve this?

**Comment by Devy-Devly** [comment]
For me, the "No Trigger Found" message is just a red herring - I get the same message when I deploy.
But the TimerTrigger works fine in Azure regardless.

Can even turn on Application Insights now and get logger information.

Am using:

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <nullable>enable</nullable>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
...
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.6.0" />
    <PackageReference Include="Lamar.Microsoft.DependencyInjection" Version="5.0.3" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.1" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />

public async Task Run([TimerTrigger("%Schedule%")] TimerInfo myTimer, FunctionContext context)
...

Hope this helps,
Devy.

**Comment by ankitkumarr** [comment]
The most recent Functions Runtime release takes care of the Portal issues as well as the issue with "No trigger Found" on deployment to Windows. All of the issues highlighted here should now be addressed. Thank you for you patience.

Please let us know if you continue to see any of these issues.

**Comment by ljtill** [comment]
@ankitkumarr - Experiencing this issue but with Linux (Consumption) functions.
Let me know if there is any specific logs, you'd like me to share.
