### ISSUE TITLE
.NET 7 isolated Azure Function (v4) runs from visual studio deploy, but not from zip-deploy

### ISSUE THREAD

**Issue by trevorbye** [Azure/azure-functions-dotnet-worker#1780]
As title says, I have a .net 7 isolated function that I was having trouble getting to run when building/zip deploying from a powershell script, so I tried to deploy it from visual studio and it worked fine, so I'm thinking there is something wrong in either the build or deploy script, and I'm not sure how to figure out the diff in what exactly the VS deploy is doing differently. 

This solution has two projects, a .net7 web application, and the .net7 isolated function, which has a project reference to the web application. The powershell script is building the entire solution with `dotnet publish -c Release -r linux-64 --sc -v q` and it's compressing/deploying the azure function by doing:

```powershell
Compress-Archive -Path <az-function-project-root>/bin/Release/.net7.0/linux-x64/publish/* -DestinationPath $workerArtifactPath -Force

Publish-AzWebApp -ResourceGroupName $rg -Name $worker -ArchivePath $workerArtifactPath -Force
```

The deploy itself is successful and doesn't return any errors. Examining the /wwwroot shows all the same files as the other functionapp (the one that is working) created via the VS deploy. I've also set the `linuxFxVersion` to `DOTNET-ISOLATED|7.0` on the zip deploy app using `az functionapp config set --name <func-name> --resource-group <rg-name> --linux-fx-version "DOTNET-ISOLATED|7.0"`, and have confirmed it is set correctly and matches the other function app by running `az functionapp config show ...name, rg... --query 'linuxFxVersion'`. I've also set the config var `WEBSITE_RUN_FROM_PACKAGE=1` on the non-working function app, although the VS deploy doesn't have this config var at all.

So it seems like it deploys successfully and is "running", but something isn't working correctly. The main issue is when you go to Azure and open the "Functions" tab on the left blade, the function is not picked up here at all, but the function app deployed from VS does show the single function name (it is a single QueueTrigger function) and it runs as expected. If I open **Log Stream** for the non working version, it does get a host lock lease, and shows "1 function found, 0 functions loaded", and then just logs CPU telemetry but never gets triggered by a queue message.

I assume there must be something incorrect in either the build script or compress/deploy script, but I'm not sure what the VS "publish" is doing differently, especially since there are no actual errors during any of this. I can provide the verbose build output from the VS publish action if that helps, or any other details. Both function apps are using the exact same app service plan which is elastic premium EP1, so this doesn't seem related to the issue where consumption plan functions will not show the function name in the "Functions" blade (which is irrelevant since it doesn't trigger anyway).

**Comment by brettsam** [comment]
`Compress-Archive` doesn't work, especially on Linux. I believe it's due to the way it stores file paths internally (`\` vs `/`).  The docs also mention that it ignores folders that begin with `.`, which Functions uses with `.azurefunctions`.

The docs recommend using the .NET API directly: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.3#description

And this is the API that the VS build task uses: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/sdk/Sdk/Tasks/ZipDeploy/CreateZipFileTask.cs#L59

**Comment by paulbatum** [comment]
There are fixes in version 1.2.3 of the `Microsoft.PowerShell.Archive` module see:
https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/62

In my case, I did: 
```
Install-Module -Name Microsoft.PowerShell.Archive -Force -Scope CurrentUser
```

The specifics of the best way to update might depend on your environment. After the install, I used Get-Command to confirm that I was using the newer version:

```
PS D:\code\functions-isolated-projects> Get-Command Compress-Archive

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Compress-Archive                                   1.2.5      Microsoft.PowerShell.Archive
```

I was then able to confirm that updating to version 1.2.5 solved the problem by testing the unzip in WSL.

**Comment by paulbatum** [comment]
Will also note that while using Publish-AzWebApp technically can work in your scenario, it is not one the official deployment methods for Azure Functions covered in the documentation:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies?tabs=windows#deployment-methods

If your script is not running in the context of a pipeline (there are links on that page for scenarios such as Azure Pipelines and GitHub Actions), then scripting usage of Azure Functions Core Tools would be applicable. There is content about that here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Cportal%2Cv2%2Cbash&pivots=programming-language-csharp#publish

Specifically it links to the core tools publish command which is documented here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-core-tools-reference?tabs=v2#func-azure-functionapp-publish

**Comment by trevorbye** [comment]
@brettsam @paulbatum thanks guys, I think this might actually be related to some weird bugs I just found in the web app deployment so I'm just going to redo the whole deploy script

**Comment by trevorbye** [comment]
@paulbatum I think this is an issue of clarity and discoverability in the docs. If you look at this how-to [Zip deployment for Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/deployment-zip-push) this makes no mention of using the Core Tools to deploy, and actually suggests `Publish-AzWebapp` as an option (also shows AZ CLI and REST deploy), so depending which doc you find, this will be an official deploy method, unintentional or not. I'll note that I also tried a manual zip (not using powershell's Compress-Archive) and tried all 3 options in this doc and still had the same issues I described.

this article is the #1 result on google if you search for "azure functions how to zip deploy", and it's #2 if you leave out "zip" and only search "azure functions how to deploy". I know those concept and ref docs you linked seem to be the source of truth, but those do not show up in google very well. 

I'm happy to submit a docs issue or PR, because I think this article should  list **Deploy with Core Tools** as the first and preferred option, to be consistent with the other documentation. My question is which of the other methods (AZ CLI, REST, Publish-AzWebapp) should be in here? I don't see those mentioned elsewhere in the documentation, should this how-to **only** show Core Tools or would you want to leave these alternate options in, but just highlight Core Tools as the preferred/official option?
