### ISSUE TITLE
Azure SignalR Integration IAsyncCollector equivalent?

### ISSUE THREAD

**Issue by sccrgoalie1** [Azure/azure-functions-dotnet-worker#179]
We use the SignalR integration with Azure Functions using the IAsyncCollector output binding

```
[FunctionName("SendMessage")]
public static Task SendMessage(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")]object message,
    [SignalR(HubName = "chat")]IAsyncCollector<SignalRMessage> signalRMessages)
{
    return signalRMessages.AddAsync(
        new SignalRMessage
        {
            // the message will only be sent to these user IDs
            UserId = "userId1",
            Target = "newMessage",
            Arguments = new [] { message }
        });
}
```

In attempting to migrate over I tried changing the AsyncCollector over to OutputBinding<SignalRMessage>, but using this only the last message added is actually sent.  Is there a way to send multiple messages as the process is running?

```
[FunctionName("SendMessage")]
public static Task SendMessage(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")]object message,
    [SignalR(HubName = "chat")]OutputBinding<SignalRMessage> signalRMessages)
{
    return signalRMessages.AddAsync(
        new SignalRMessage
        {
            // the message will only be sent to these user IDs
            UserId = "userId1",
            Target = "newMessage",
            Arguments = new [] { message }
        });
}
```

**Comment by RaphaelYoshiga** [comment]
I think I am in need of the same functionality, my scenario is to give multiple messages while the function is executed, not just when the function is finished. Is this available in the extensions package?

I will be trying to get an instance of the Hub manually so I have full access to broadcast the messages.

**Comment by fabiocav** [comment]
@RaphaelYoshiga if your requirement is to return multiple messages (not send them in real time/as the function executes), you can return an `IEnumerable<SignalRMessage>` and they should all be processed **when the function completes**.

**Comment by fabiocav** [comment]
Closing as answered. Please let us know if you have any additional questions.
