### ISSUE TITLE
Unresponsive Function with Microsoft.Azure.Functions.Worker.ApplicationInsights preview 5

### ISSUE THREAD

**Issue by ursaciuc-adrian** [Azure/azure-functions-dotnet-worker#1791]
Hello!

Today, I attempted to integrate Microsoft.Azure.Functions.Worker.ApplicationInsights (preview 5) into my solution, in addition to the existing Microsoft.ApplicationInsights.WorkerService (version 2.21.0) in my v4 function using .NET 7.

However, upon adding the Microsoft.Azure.Functions.Worker.ApplicationInsights package without any other changes, the function becomes unresponsive. The only log I receive is that the function was triggered ("Executing 'Functions...' (Reason=...)", but no further execution occurs. I even tried setting a breakpoint in the controller, but it doesn't get hit.

I attempted to resolve the issue by adding the required configuration services.ConfigureFunctionsApplicationInsights();, but it did not help.

I found that downgrading to version 4 or 3 of Microsoft.ApplicationInsights.WorkerService makes the function responsive again. Nevertheless, I would like to utilize the new package and configuration approach.

Am I missing something in my setup, or is there an issue with the preview package? Any assistance would be appreciated.

[Company.FunctionApp2.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/12191938/Company.FunctionApp2.zip)

**Comment by ursaciuc-adrian** [comment]
After upgrading "Microsoft.Azure.Functions.Worker" to version 1.18.0 and "Microsoft.Azure.Functions.Worker.Sdk" to 1.13.0, I have successfully resolved the problem. 
I am unsure if this should still be considered an issue related to backward compatibility. 
If you think there are no more concerns, please don't hesitate to close this ticket.

**Comment by Markz878** [comment]
Same here, in "Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview4" I had this code:
```
    .ConfigureFunctionsWorkerDefaults((context, app) =>
    {
        app.AddApplicationInsights().AddApplicationInsightsLogger();
    })
```
but when I upgrade to preview 5, that extension method is no longer there.

**Comment by ursaciuc-adrian** [comment]
@Markz878 

That setup method has been removed, and I understand that it's common for changes to occur, particularly with preview packages. 
The sole documentation I could locate for configuring the new version is only available on their nuget page.
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights

For me, it only worked after also upgrading the Worker and Worker.Sdk to the latest version.

**Comment by brettsam** [comment]
1.0.0-preview5 introduced a new pattern for wiring up Application Insights with the Functions worker. We're trying to make it clear that there's not a *ton* of special stuff going on behind-the-scenes and that you have full control over the logging, initializers, processors, etc, when using Application Insights with the worker. To do that, we pulled away the registration from the `IFunctionsWorkerApplicationBuilder` and now have the custom services wired up alongside the "normal" Application Insights registration.

However... even though we added a readme (which also shows up in Nuget), we did not explicitly create a Github Release. I've done that now: https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/application-insights-1.0.0-preview5. 

The official docs have also been updated: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights

Also, even though it's not directly related, I walked through a sample that a customer was struggling with here (it includes a full sample with lots of comments): https://github.com/Azure/azure-functions-dotnet-worker/issues/1040#issuecomment-1644791863

If there's any other places that you'd recommend we advertise this breaking change, please let me know and  I can do that.

**Comment by brettsam** [comment]
I don't think there's any actual issues here once the confusion around preview5 is resolved. But feel free to re-open if that's not the case.

And if there's additional confusion around wire-up or APIs we've exposed, please file a new issue with a new description.
