### ISSUE TITLE
Using ClaimTypeList & IdToken in SignalRConnectionInfoInput (isolated-process functions)

### ISSUE THREAD

**Issue by msirkovsky-moodys** [Azure/azure-functions-dotnet-worker#1792]
Hi, 

is there any documentation or example of how to use [ClaimTypeList](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.signalrservice.negotiationbaseattribute.claimtypelist?view=azure-dotnet#microsoft-azure-webjobs-extensions-signalrservice-negotiationbaseattribute-claimtypelist) & [IdToken ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.signalrservice.negotiationbaseattribute.idtoken?view=azure-dotnet#microsoft-azure-webjobs-extensions-signalrservice-negotiationbaseattribute-idtoken) from [SignalRConnectionInfoAttribute](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.signalrservice.signalrconnectioninfoattribute?view=azure-dotnet) in isolated worker process functions?

I want to add claims from my JWT token to the SignalR access token that is generated when the negotiate function is called. 

The code to illustrate my intentions:
```C#
public string Negotiate(
        [HttpTrigger(AuthorizationLevel.Function)] HttpRequestData req,
        [SignalRConnectionInfoInput(HubName = "hubName", UserId = "{headers.user}", 
        ClaimTypeList = new []{"scope"}, 
        IdToken = ???
        )] string connectionInfo)
    {
        return connectionInfo;
    }
```

Thanks.

**Comment by Y-Sindo** [comment]
Hi @msirkovsky-moodys , the `IdToken` is usually a [binding expression](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns) which refers to your JWT token, such as `{headers.Authentication}` .
We will improve our doc to address the issue.

**Comment by Y-Sindo** [comment]
The doc [SignalR input binding attributes](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=isolated-process&pivots=programming-language-csharp#attributes) has been updated.
