### ISSUE TITLE
warning NETS DK1198: A publish profile with the name <NAME> was not found in the project.

### ISSUE THREAD

**Issue by SkyBully** [Azure/azure-functions-dotnet-worker#1798]
Hello,

I have created an isolated-process azure function (target net48). 
I have unexpected warning: _"C:\AzureFunction\FunctionApp1\FunctionAppIsolated\FunctionAppIsolated.csproj" (default target) (1) ->
"C:\Users\admin.a\AppData\Local\Temp\fzfxfjgo.dhl\WorkerExtensions.csproj" (Publish target) (3:7) ->
(PrepareForPublish target) ->
  C:\Program Files\dotnet\sdk\7.0.306\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(124,5): warning NETS
DK1198: A publish profile with the name 'WebProfile' was not found in the project. Set the PublishProfile property to a
 valid file name. [C:\Users\admin.a\AppData\Local\Temp\fzfxfjgo.dhl\WorkerExtensions.csproj]_ 

When I run command: **msbuild FunctionAppIsolated.csproj /p:DeployOnBuild=true /p:PublishProfile=WebProfile /p:Configuration=Release**

How I can fix that warning ?

I did it according with the  https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-7.0#folder-publish-example

Visual Studio 2022 Version 17.6.5 
MSBuild version 17.6.3+07e294721

FunctionAppIsolated.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <UserSecretsId>****</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.2.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.0.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.14.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.10.0" />
    <PackageReference Include="Microsoft.Configuration.ConfigurationBuilders.UserSecrets" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
```

FunctionAppIsolated/Properties/PublishProfiles/WebProfile.pubxml:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<WebPublishMethod>FileSystem</WebPublishMethod>
		<PublishProvider>FileSystem</PublishProvider>
		<LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
		<LastUsedPlatform>Any CPU</LastUsedPlatform>
		<SiteUrlToLaunchAfterPublish />
		<LaunchSiteAfterPublish>False</LaunchSiteAfterPublish>
		<ExcludeApp_Data>False</ExcludeApp_Data>
		<PublishFramework>net48</PublishFramework>
		<publishUrl>bin\Release\Publish</publishUrl>
		<DeleteExistingFiles>False</DeleteExistingFiles>
	</PropertyGroup>
</Project>
```
I add zip of the simple project that replicate that issue. 
[FunctionApp1.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/12229684/FunctionApp1.zip)

**Comment by jviau** [comment]
This appears to be an issue with properties supplied via arguments are passed to the inner build. In this case, `/p:PublishProfile=WebProfile` being passed to the inner build causes issues. We will need to remove this global property for the inner build, but need to verify that won't cause other issues.

@SkyBully to work around this for now, you can supply the publish profile directly in your csproj. Something like:

``` CSharp
<PropertyGroup>
  <PublishProfile Condition="'$(PublishWebProfile)' == 'true'">WebProfile</PublishProfile>
</PropertyGroup>
```

Then change your command args `/p:PublishProfile=WebProfile` --> `/p:PublishWebProfile=true`

**Comment by ordinaryorange** [comment]
I hit this too but could not get the above to work. 
The following Azure function core tools command did work however
`func azure functionapp publish <APP_NAME>`

**Comment by codeputer** [comment]
I'm fighting this for the past couple days to deploy C# NET8 program which was working, until I added another function.  For some reason, I think the Zip file deploys, but then stops there.  The publish records as successful, but issues this warning

C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(204,5): warning NETSDK1198: A publish profile with the name 'C:\Users\Richard\source\repos\PhxBiz\GFSConnectApp\GFSFunctions\Properties\PublishProfiles\gfssbtriggerfunc-dev - Zip Deploy.pubxml' was not found in the project. Set the PublishProfile property to a valid file name. [C:\Users\Richard\AppData\Local\Temp\qkweiyvt.p4x\WorkerExtensions.csproj]

as this is NOT a web project, but a EXE deployed for Azure Functions using .Net8 in isolation mode.  Any help would be appreciated as this is blocking a production deployment that needs to occur

**Comment by jviau** [comment]
This will be addressed by our upcoming SDK refactor.

**Comment by codeputer** [comment]
> This will be addressed by our upcoming SDK refactor.

Awesome, but I've been working non-stop to get this deployed, and not having any luck.  Is there a work around?  I tried what was mentioned previously, but have had no joy.

**Comment by Aspyryan** [comment]
@codeputer Did you end up finding a workaround?

**Comment by jviau** [comment]
This has been addressed in the recent SDK preview: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0-preview1

**Comment by andriysavin** [comment]
I'm using [Version="1.17.2](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.2) and still observing this issue.

**Comment by StanislavUhimenko** [comment]
"http://example.com"
