### ISSUE TITLE
Define behavior when using rich types in a function

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#18]
Rich types like `CloudBlockBlob`, etc, don't work when used in the worker. We need to define how to handle this so it's not a runtime exception.

**Comment by fabiocav** [comment]
The work here would be to leverage the existing indexing/converter probing logic to identify the types and provide a compilation error with an Analyzer (similar to what we had in WebJobs)

**Comment by brettsam** [comment]
Sdk type support handles this now...
