### ISSUE TITLE
Not able to view Serilogs in Azure Function Dev Monitor

### ISSUE THREAD

**Issue by raghavrawat98** [Azure/azure-functions-dotnet-worker#1801]
Hello,

I was trying to implement Serilogs for Azure Functions .NET 7 Isolated Worker Process mode.
I noticed that once I deployed my functionApp, I was not able to see my logs in Azure Function> Developer> Monitor. 
When I saw Application insights, I was able to see my logs, just that logs are not showing in the function monitor. 

Can anyone tell me what am I missing?
I was not able to find my specific problem.

Output from my function monitor
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/49871652/ceeedc01-37db-4334-bf46-1526a32fe937)

Output from Local Console
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/49871652/8e8a80ac-35cb-482a-843b-43bd1c44a31c)

Output of Application insights:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/49871652/cd1c8dbb-bbb0-414a-b00e-d1dd940b7c9c)

Below is my host.json
```
{
  "version": "2.0",
  //"logging": {
  //  "applicationInsights": {
  //    "samplingSettings": {
  //      "isEnabled": true,
  //      "excludedTypes": "Request"
  //    }
  //  }
  //},
  "logging": {
    "logLevel": {
      "default": "Information"
    }
  }

}
```

My Program,cs
```
using Microsoft.Extensions.Hosting;
using SerilogFunctionApp;
using Serilog;


Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Console()
    .WriteTo.Debug()
    .CreateLogger();

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(worker => worker.UseMiddleware<Middleware>())
    .Build();

host.Run();
```

**Comment by jviau** [comment]
We don't explicitly support serilog and I am not familiar with. However, the log streaming (monitor tab) is driven by application insights, can you verify if your logs show up on your application insights instance?

Looking at your `program.cs`, I don't see any code integrating serilog with `Microsoft.Extensions.Logging`. I think you may need to use this package: https://github.com/serilog/serilog-extensions-hosting/
