### ISSUE TITLE
Azure Function isolated System.Net.Http/4.3.0 vulnerability

### ISSUE THREAD

**Issue by sdevadas-wooliesx** [Azure/azure-functions-dotnet-worker#1802]
System.Net.Http/4.3.0 has been identified as a high vulnerability.

When building the application using azure function isolated, there is System.Net.Http/4.3.0 in .azurefunctions/function.deps.json

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/134692175/ee341670-0c5c-48e5-a41d-1baf8714fded)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/134692175/e33028a2-6ed4-48c1-b0a5-6ac74dc4eca2)

**Comment by jviau** [comment]
@sdevadas-wooliesx the file in question you are pointing at are dependencies for the functions host extensions (not for your worker app). Many of these dependencies versions here, including System.Net.Http, will actually be controlled by the functions host. In this case, System.Net.Http **4.3.4** will actually be used at runtime.

[This file](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/runtimeassemblies.json) describes how the functions host will resolve extension assemblies. Essentially, if the resolution mode for an assembly is **not** private, then the host will override the requested version with its own. In which case, it will most likely be up to date.

**Comment by sdevadas-wooliesx** [comment]
@jviau The issue is it is picking as vulnerability using Trivy scanner. 

If the host function is having the issue, should it be upgraded in the function worker?

If I add a newer version of the hosting function would the hosting dependency show/use the latest http ?

**Comment by jviau** [comment]
> If the host function is having the issue, should it be upgraded in the function worker?

This isn't a straight-forward dependency by the worker. The functions worker SDK has an inner build which collects functions host extensions and assemblies. This is what your scan is picking up. These files are not directly used by the worker app. Instead, they are loaded by the functions host. For this specific assembly, even though the build has 4.3.0 in that folder, the host will actually ignore it and load 4.3.4 (which will already be packaged up with the host).

At best, you can try writing a post-build step which removes that assembly and verify your app still runs without issues. I _think_ removing the file should work, as the host is loading its own copy anyways (which is 4.3.4).

**Comment by jviau** [comment]
Fixing in: https://github.com/Azure/azure-functions-vs-build-sdk/pull/625

**Comment by fabiocav** [comment]
Removing security related report.

All issues have been addressed. For guidance on how to report similar issues in the future, please see https://github.com/Azure/azure-functions-dotnet-worker/security/policy

Thank you.
