### ISSUE TITLE
Binding custom model in Azure HttpTrigger Isolated Function

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/azure-functions-dotnet-worker#1803]
Hi,
Is it possible to use custom model along with HttpRequestData in Azure Http Trigger Isolated function with get and post methods?
I tried a custom DTO SessionToken as below but it is always null.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/92055761/671fc680-8efb-4b22-a2ce-5751488efb30)

**Comment by mattchenderson** [comment]
We're planning an update soon which should enable support. Just to clarify, in your example, you'd want to have something like

```csharp
public async Task<SessionDocresult> Run( [ <http trigger attribute> ] HttpRequestData request, SessionToken token)
```

Is that correct?

**Comment by ranjeetkpGit** [comment]
> We're planning an update soon which should enable support. Just to clarify, in your example, you'd want to have something like
> 
> ```cs
> public async Task<SessionDocresult> Run( [ <http trigger attribute> ] HttpRequestData request, SessionToken token)
> ```
> 
> Is that correct?

Yes Matthew, Its correct. SessionToken is a custom class. 
At present its two step process.
1. Get Body content from HttpRequestData (Stream)
2.  Deserialize it to required types

**Comment by JeroenvdBurg** [comment]
#1712

**Comment by fabiocav** [comment]
Closing this as resolved as the feature has been released. 

Here's a link to the documentation: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cfunctionsv2&pivots=programming-language-csharp#usage


Please let us know if you have any questions or problems.
