### ISSUE TITLE
Timer trigger template fails with null ref with frequent timer

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-dotnet-worker#1807]
Steps to reproduce:
1. Open VS 2022 and create a new .NET 6 isolated function app project
2. Select timer trigger
3. Change the schedule to be every 5 seconds e.g. */5 * * * * *"
4. Run the app

Expected result - the timer runs successfully

Actual result - null ref accessing the timer schedule:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/10663/aa911f0d-28c1-4f45-8b1e-728a769df89e)

**Comment by mathewc** [comment]
For in-proc, the TimerInfo object passed in by the extension will have a null ScheduleStatus property (see xml doc [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/2ca41057bb8a7752cfb4e311c287a65eb8fedfc5/src/WebJobs.Extensions/Extensions/Timers/TimerInfo.cs#L42)). Basically when UseMonitor is explicitly set to false, or defaults to false based on the frequency of the timer interval (as in this case), ScheduleStatus will be null.

So this template needs to be updated to only log the status conditionally, or perhaps just remove the logging entirely like in the minimal in-proc template [here](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/TimerTrigger-CSharp/TimerTriggerCSharp.cs).

**Comment by surgupta-msft** [comment]
Closing issue. Fix has been merged.
