### ISSUE TITLE
Updates to upgrade assistant (SDK types)

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1813]
Update the "upgrade assistant" so that it works with the new SDK binding feature to enable smoother migration from in-proc to out-of-proc

**Comment by mattchenderson** [comment]
Specifically, there we need to update a bunch of package versions that Upgrade Assistant moves the project to. It looks like the Event Hubs extension can land on 4.3.0 for example, which is rather old and certainly doesn't have the SDK type support.

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/503322

**Comment by aishwaryabh** [comment]
PR has been merged
