### ISSUE TITLE
FunctionMetadataProvider emits incorrect binding `name` property value for async functions

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1817]
The source generated FunctionMetadataProvider emits incorrect binding `name` property value for async functions.

#### Repro steps:

1) Create a new function app with http trigger.

```csharp
[Function("Run")]
public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
{
    throw new NotImplementedException();
}
```

2) Set the msbuild prop `<FunctionsEnableWorkerIndexing>True</FunctionsEnableWorkerIndexing>`

3) Build the code. Our source generator will create `GeneratedFunctionMetadataProvider` class with `GetFunctionMetadataAsync` as below.

```csharp
public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
{
    var metadataList = new List<IFunctionMetadata>();
    var Function0RawBindings = new List<string>();
    Function0RawBindings.Add(@"{""name"":""req"",""type"":""HttpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""get""]}");
    Function0RawBindings.Add(@"{""name"":""$return"",""type"":""http"",""direction"":""Out""}");

    var Function0 = new DefaultFunctionMetadata
    {
        Language = "dotnet-isolated",
        Name = "Run",
        EntryPoint = "FunctionApp96.Function1.Run",
        RawBindings = Function0RawBindings,
        ScriptFile = "FunctionApp96.dll"
    };
    metadataList.Add(Function0);

    return Task.FromResult(metadataList.ToImmutableArray());
}
```
4) Now change the method to async

```csharp
[Function("Run")]
public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
{
    throw new NotImplementedException();
}
```

The generated code has incorrect value for the "name" property of the second raw binding entry. Instead of "$return", the generated value is "Result". 

```csharp
public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
{
    var metadataList = new List<IFunctionMetadata>();
    var Function0RawBindings = new List<string>();
    Function0RawBindings.Add(@"{""name"":""req"",""type"":""HttpTrigger"",""direction"":""In"",""authLevel"":""Function"",""methods"":[""get""]}");
    Function0RawBindings.Add(@"{""name"":""Result"",""type"":""http"",""direction"":""Out""}");

    var Function0 = new DefaultFunctionMetadata
    {
        Language = "dotnet-isolated",
        Name = "Run",
        EntryPoint = "FunctionApp96.Function1.Run",
        RawBindings = Function0RawBindings,
        ScriptFile = "FunctionApp96.dll"
    };
    metadataList.Add(Function0);

    return Task.FromResult(metadataList.ToImmutableArray());
}
```

Because of this incorrect value, function invocation ends up throwing the below exception (because it ends up [picking the wrong OutputBindingsInfo](https://github.com/Azure/azure-functions-dotnet-worker/blob/c7b97955caf827493d223020887c2ce4c4ad539e/src/DotNetWorker.Core/OutputBindings/DefaultOutputBindingsInfoProvider.cs#L21-L25))

> Result: Failure Exception: System.InvalidOperationException: Could not find expected property 'Result' in type Microsoft.Azure.Functions.Worker.GrpcHttpResponseData    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.GetPropertyValue(Type baseType, String propertyName, Object instance) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 52    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.AddResultToOutputBindings(IDictionary`2 outputBindings, Object result) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 39    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.BindOutputInContext(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 26    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.AddOutputBindings(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 25    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 15    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88 Stack:    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.GetPropertyValue(Type baseType, String propertyName, Object instance) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 52    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.AddResultToOutputBindings(IDictionary`2 outputBindings, Object result) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 39    at Microsoft.Azure.Functions.Worker.OutputBindings.PropertyOutputBindingsInfo.BindOutputInContext(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\PropertyOutputBindingsInfo.cs:line 26    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.AddOutputBindings(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 25    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 15    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88

**Comment by cathei** [comment]
Heads up that this happens with current version, when you use `ValueTask<HttpResponseData>`, but not when you use `Task<HttpResponseData>`.
