### ISSUE TITLE
Local debugging does not work with FunctionsEnableWorkerIndexing

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1818]
Visual studio F5 debugging does not work when .csproj has `<FunctionsEnableWorkerIndexing>True</FunctionsEnableWorkerIndexing>`.

The console window will open. but it does not print anything (like the discovered functions in the app etc..)

**Comment by andrii-riabchun** [comment]
I am experiencing a similar behavior. 
After starting debugging with F5, the console window opens and hangs. Meanwhile, Visual Studio hangs and displays "Launching local Functions process..." modal.

After a minute, there are messages in the console:
```
A debugger was not attached within the expected time limit. The process will continue without a debugger.
Worker process started and initialized.
```
After these messages, the normal output (function metadata) is displayed.
But despite a `debugger was not attached' message, debugging in Visual Studio works for me.

My environment:
Visual Studio 17.6.6
Azure Functions and Web Job Tools 17.6.326.62524
Core Tools Version:  4.0.5198
Function Runtime Version: 4.21.1.20667
