### ISSUE TITLE
Access to incoming AzureServiceBusReceivedMessage from middleware

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#1824]
I need to access the incoming `AzureServiceBusReceivedMessage` from middleware. Is that possible?

**Comment by liliankasem** [comment]
Yes this should be possible. Assigning to @fabiocav as he mentioned he could write up a sample for this if needed

**Comment by SeanFeldman** [comment]
@fabiocav is there a PR I could take a peek at?

**Comment by SeanFeldman** [comment]
Anyone? 🙂

**Comment by SeanFeldman** [comment]
@fabiocav, is this something you can point me to or it requires anything additional to be put together?

**Comment by fabiocav** [comment]
@SeanFeldman I'm putting a quick example together, but did run into an issue I need to work through. Will post an update here as soon as I have this working.

**Comment by SeanFeldman** [comment]
@fabiocav
<img src="https://y.yarn.co/7b03abfe-3ce0-41a2-bfd6-d40dd04f2eec_text.gif"/>

**Comment by ChristopheCE** [comment]
Something like this worked for me:

`BindingMetadata meta = context.FunctionDefinition.InputBindings.FirstOrDefault(b => b.Key.Equals("message")).Value;
var input = await context.BindInputAsync<ServiceBusReceivedMessage>(meta);
var message = input.Value;`

(Replace "message" with how you called the ServiceBusReceivedMessage object in your function's header)

**Comment by SeanFeldman** [comment]
@ChristopheCE, I've tried that code, and it didn't work for me. `context.FunctionDefinition.InputBindings` doesn't seem to have the value for the `message` that's always a `null` after input is bound. I've used the latest versions
- `Microsoft.Azure.Functions.Worker` 1.19.0
- `Microsoft.Azure.Functions.Worker.Sdk` 1.15.0
- `Microsoft.Azure.Functions.Worker.Extensions.ServiceBus` 5.13.0

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1309622/33a5c32e-8460-4e29-b6a0-96c27f96e0a6)

Also, when I plug a custom middleware that includes the snippet, the function gets a `null` for `message` as well. What versions of the packages are you using?

**Comment by ChristopheCE** [comment]
@SeanFeldman I'm using the same package versions. I was indeed also using this as middleware, but I guess the info you receive depends on on what moment you try to get it (I'm also no export on this code). I'm using this for add error handling logic via middleware. Here is my full code:

```
public class SomeMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        try
        {
            await next(context);
        }
        catch (Exception e)
        {
            BindingMetadata meta = context.FunctionDefinition.InputBindings.FirstOrDefault(b => b.Key.Equals("message")).Value;
            var input = await context.BindInputAsync<ServiceBusReceivedMessage>(meta);
            var message = input.Value;
            Console.WriteLine(message);
        }
    }
}
```

I also tried moving the input binding before calling `await next(context);`, but than indeed the message is empty.

**Comment by SeanFeldman** [comment]
I suspect what's happening is that the `message` is not materialized until the function is running. So the snippet you've shared is working because the function had a chance to run first, which is OK for error handling. But if you need to filter out messages, this approach will not work.

@fabiocav, any chance you could share [your example](https://github.com/Azure/azure-functions-dotnet-worker/issues/1824#issuecomment-1700333201)?

**Comment by SeanFeldman** [comment]
@ChristopheCE, one modification to your snippet - querying binding by the trigger type rather than parameter name

```
BindingMetadata meta = context.FunctionDefinition.InputBindings.FirstOrDefault(b => b.Value.Type == "serviceBusTrigger").Value;
```

While this is OK to handle an exception, no ability to access a message in the middleware before it's passed to a function is a real blocker for me. 😞

**Comment by jcastellanos-amh** [comment]
Is it possible to access ServiceBusMessageActions too?

**Comment by SeanFeldman** [comment]
> Is it possible to access ServiceBusMessageActions too?

I don't think so. It's only available to the called function.

**Comment by SeanFeldman** [comment]
For failed message it's working, see https://github.com/Azure/azure-functions-dotnet-worker/issues/1824#issuecomment-1750260618

**Comment by Archomeda** [comment]
I just stumbled upon this limitation. I would love to be able to access the body of the service bus message **before** it's passed onto the function. This way I can set up some scopes in a generic way based on common properties in the message bodies.

As a side note, I also noticed in the BindingContext.BindingData property that there is a Content item. I had hoped that this would contain the message content, but this seems to be "{}" instead :(

**Comment by SeanFeldman** [comment]
With the .NET 8 milestone behind (congratulations 🎉), are there any updates on this one or what to realistically expect?

**Comment by rvbaast** [comment]
I would like to upvote this request ;-).  
Not only `AzureServiceBusReceivedMessage `, but `ServiceBusMessageActions `as well.

@jcastellanos-amh [suggestion ](https://github.com/Azure/azure-functions-dotnet-worker/issues/1824#issuecomment-1785960034) does not seem to work for when I try to deadletter a message from the middleware.

**Comment by SeanFeldman** [comment]
Confirmed as working with `Microsoft.Azure.Functions.Worker` 1.21.0

**Comment by rvbaast** [comment]
Yes indeed, my test also succeeds with  `Microsoft.Azure.Functions.Worker 1.21.0`

**Comment by fabiocav** [comment]
Sharing the sample we've shared with @SeanFeldman . We'll clean that up and bring it into the repo: https://github.com/fabiocav/MiddlewareBinding

**Comment by Nehmiabm** [comment]
I've a slightly different case.  All of my Azure Functions use strongly typed input bindings (I'm not binding using 'ServiceBusReceivedMessage') and I would like to access the original 'ServiceBusReceivedMessage' message in a middleware but that doesn't seem to be possible. It appears that `context.BindInputAsync<T>` requires the specific input binding type but I want my middleware to be able to access the original received message across all functions without hard coding the specific input binding type as the middleware can be used to configure various functions using different input binding types. Has anyone run into similar challenges?

**Comment by nordvall** [comment]
@Nehmiabm your scenario seems to be the same as I reported in #2157. Feel free to come over and promote that one! :-)

**Comment by extrmi** [comment]
This one is a bit pain. As you can only use the BindInputAsync<T> with the actual type, otherwise we get the "Cannot cast" exception, i was able to get the message payload using a bit of reflection. It's not pretty, but it works

` internal class ServiceBusMiddleware : IFunctionsWorkerMiddleware
    {
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            var bindingMetadata = context.FunctionDefinition.InputBindings.Values.First();
            var parameter = context.FunctionDefinition.Parameters.First(p => p.Name == bindingMetadata.Name);
            var method = typeof(FunctionContextBindingFeatureExtensions)
                .GetMethod(nameof(FunctionContextBindingFeatureExtensions.BindInputAsync))?
            .MakeGenericMethod(parameter.Type);

            dynamic valueTask = method.Invoke(null, [context, bindingMetadata]);

            var inputBindingData = await valueTask;

            object value = inputBindingData.Value;

            var valueAsJson = JsonSerializer.Serialize(value);
        }
    }`
