### ISSUE TITLE
[FSharp] Options not configured with new extension versions that use WorkerExtensionStartup

### ISSUE THREAD

**Issue by anielii** [Azure/azure-functions-dotnet-worker#1826]
# Summary

After updating **Microsoft.Azure.Functions.Worker.Sdk** from **1.11.0** to **1.14.0**, functions written in F# started throwing exceptions about parameter binding. This affects at least the CosmosDB and Blob bindings. Most likely the problem is related to other bindings as well. The message is always in the form

Error converting 1 input parameters for Function '\<func name>': Cannot convert input parameter '\<name of the input>' to type \<any provided type> from type **'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'ConnectionName')**.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16141138/7c063826-ce21-4589-8e26-31a7eb26cb12)

This problem does not occur with functions written in C#.

# Steps to reproduce
- [Use this repo](https://github.com/anielii/azure-functions-dotnet-worker-issue/tree/master)
- Downgrade **Microsoft.Azure.Functions.Worker.Sdk** to **1.11.0** to check that the project works fine with the older version.

**Comment by liliankasem** [comment]
Thanks for providing a great repro project; we'll look into it

**Comment by anielii** [comment]
Thank you for your quick response. I confirm the solution works as expected for Blob and Cosmos bindings.

Would it be possible to update the documentation to include the above information so that other F# developers are aware?

**Comment by liliankasem** [comment]
@anielii thanks for confirming! I'll keep the issue open until this is documented + the extension class is implemented.

**Comment by fabiocav** [comment]
Moving this to sprint 154, but it would be good to either have issues tracking the documentation and templates work, or to have those items tracked here.

**Comment by liliankasem** [comment]
Packages have been released for Blob and Tables, with guidance on usage:

- [x] https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/tables-extension-1.2.1
- [x] https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/storage-extension-6.2.0
- [ ] TODO: Release CosmosDB

There is a PR open to update the templates:

- [ ] https://github.com/Azure/azure-functions-templates/pull/1445

@mattchenderson and I are working to updates docs as well.

**Comment by liliankasem** [comment]
Only remaining work here is documentation which will be tracked by: https://github.com/Azure/azure-functions-dotnet-worker/issues/1899
