### ISSUE TITLE
8x Performance degradation after updating Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights package

### ISSUE THREAD

**Issue by rodolfograve** [Azure/azure-functions-dotnet-worker#1827]
Our system has experienced a huge (8x) performance degradation after what seemed like a minor upgrade. See the details about the versions below.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/47207840-35ad-403d-86e9-78c91a1efb36)

We have already confirmed that reverting these packages solves the issue.

All functions are affected, but the simplest one is a HTTP trigger that reads several blobs from Azure Storage. It went from taking less than 15s to more than 90s (peaking at 112s). The red box contains all the requests with the latest version of the packages. Below is before the deployment and the first one is after reverting the changes.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/4d3352b5-95be-43c2-b59f-50a218477086)

We will try to isolate a specific package now, but this is just to make everyone else aware that this happened to us and to hopefully get some advice from the team.

I did notice that the https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights has been released just a few hours ago and is listed as "0 downloads". That's going to be my main suspect.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/428e61fa-5ca0-4f11-af63-aad685eb2009)

**Comment by mattchenderson** [comment]
Thanks for flagging. We'll investigate on our side as well.

**Comment by brettsam** [comment]
What does your Program.cs look like? What kind of trigger is this?

Going from the App Insights `preview4` -> `1.0.0`, you would have hit the [breaking changes in `preview5`](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/application-insights-1.0.0-preview5) that I assume you had to refactor around?

However, any errors there should have just thrown exceptions on startup (or not even compiled).

**Comment by brettsam** [comment]
I just saw your edit above that this is an http trigger. 

Also, if you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

**Comment by rodolfograve** [comment]
Yes, I had to change my DI configuration according to the documentation.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/f378af82-bcaf-488f-babb-8db529b1a387)

As you said, it wouldn't compile. Also, the integration with App Insights seems to work. Otherwise I think there wouldn't have been any logs:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/e88e43c7-045c-4d79-8d41-fc646897c83d)

The Function name is included in the screenshot :-) 

> carbon//dashboard-GetDashboardItems

I can confirm that after updating almost every other package (see below), the issue does not occur, which points strongly towards AppInsights. I will keep updating one by one and deploying and post an update here.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/ab216a32-1737-4cbe-abe7-3cca1c03969f)

Thanks for looking into it!

**Comment by rodolfograve** [comment]
Confirmed... I updated every other package, one by one. The execution time remained roughly the same.

As soon as I:

1. Updated Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights from 1.0.0-preview4 to 1.0.0, and
2. Installed Microsoft.ApplicationInsights.WorkerService 2.21.0

the time blew up.

I did notice something interesting: after updating and installing the packages mentioned above, this package was left behind:

Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights 1.0.0-preview4.

It looked like a duplicate, so I uninstalled it. The function executed OK, and the execution time was roughly halved (which I found suspicious). May be a clue. Still not a solution as it leaves me with a 4x performance degradation.

In any case, it's definitely this package.

We make a lot of calls inside this request (about 2 thousand small Azure Blob Storage downloads), and I know that a lot of telemetry is sent to AppInsights. This might explain why a simple test doesn't replicate my issue.

Let me know if there's anything else I can do to help you find the cause and a solution.

**Comment by brettsam** [comment]
Thanks for the details... let me try setting up a repro that does a bunch of storage operations and see if I can reproduce this.

I assume you're using the Azure.Storage.Blobs package to do the downloading?

**Comment by rodolfograve** [comment]
Yes, correct. What I would vanilla usage of Azure.Storage.Blobs.

Can provide some sample code tomorrow if that helps.

**Comment by brettsam** [comment]
Yes, sample code would help. Let me share what I've tried. I created a really simple app with code like this:

```csharp
[Function("Function1")]
public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
{
    _logger.LogInformation("Starting dotnet-isolated function");

    for (int i = 0; i < 10000; i++)
    {
        var downloadResult = await BlobClient.DownloadContentAsync();
        var content = downloadResult.Value.Content.ToString();
    }

    _logger.LogInformation("Finished dotnet-isolated function");

    var response = req.CreateResponse(HttpStatusCode.OK);
    response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

    response.WriteString("Welcome to Azure Functions!");

    return response;
}
```

When I delete everything AppInsights-related and run , it's around 44-48ish seconds (varies around there).
When I turn all AppInsights-related stuff back on, it gets slower, but only to around 50-54ish seconds. 

It's definitely not a 4x increase like you're seeing.

If you're able to provide any (trimmed-down, if necessary) sample code that repros this, that would help immensely.

Thanks for helping out here.

**Comment by rodolfograve** [comment]
This is a slightly modified version of the code. I just removed some application specific names and hard-coded a couple of values instead of getting them from configuration.

```
    public record Result(IReadOnlyCollection<string> ItemsJson);

    public async Task<Result> GetResult()
    {
        var blobServiceClient = new BlobServiceClient(Configuration.StorageAccountConnectionString);
        const string blobContainerName = "some-name";
        var blobContainerClient = blobServiceClient.GetBlobContainerClient(blobContainerName);
        var itemsJson = new ConcurrentBag<string>();
        Timestamp? lastSourceUpdateTimestamp = null;
        if (await blobContainerClient.ExistsAsync())
        {
            var path = "some-path";

            Logger.LogInformation("BlobContainer '{BlobContainer}' exists. Looking for blobs inside path '{Path}'", blobContainerName, path);
            var itemBlobs = blobContainerClient.GetBlobs(prefix: path);

            var tasks = new List<Task>();

            async Task GetBlobContent(BlobClient blobClient)
            {
                var blobDownloadResult = await blobClient.DownloadContentAsync();
                var blobContent = blobDownloadResult.Value.Content.ToString();
                itemsJson.Add(blobContent);
            }

            foreach (var itemBlob in itemBlobs)
            {
                var itemBlobClient = blobContainerClient.GetBlobClient(itemBlob.Name);
                tasks.Add(GetBlobContent(itemBlobClient));
                var blobTimestamp = itemBlob.Properties.LastModified ?? itemBlob.Properties.CreatedOn;
                if (blobTimestamp is not null && (lastSourceUpdateTimestamp is null || lastSourceUpdateTimestamp.DateTimeOffset < blobTimestamp))
                {
                    lastSourceUpdateTimestamp = new Timestamp(blobTimestamp.Value);
                }
            }
            await tasks.ExecuteInBatches(15);
        }
        else
        {
            Logger.LogWarning("BlobContainer '{BlobContainer}' not found for '{Type}'", blobContainerName, GetType().Name);
        }
        var result = new Result(itemsJson);
        return result;
    }
```

This is the ExecuteInBatches extension method:

```
    public static async Task ExecuteInBatches(this IEnumerable<Task> tasks, int batchSize = 4)
    {
        var currentBatch = new List<Task>();
        foreach (var task in tasks)
        {
            if (currentBatch.Count >= batchSize)
            {
                await Task.WhenAll(currentBatch);
                currentBatch.Clear();
            }
            currentBatch.Add(task);
        }

        if (currentBatch.Count > 0)
        {
            await Task.WhenAll(currentBatch);
            currentBatch.Clear();
        }
    }
```

I really can't see anything there that should be affected by AppInsights, but please, do give it a go.

Something that I think is also relevant is the configuration of the Functions. I know there are some settings there that are related to how AppInsights is integrated and I suspect it's harder for you to consider/test every possible migration path for Functions that have been running for a while and their settings updated along the way.

Here are all the "system" settings:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/5d72c232-bbcc-4d9a-bfd9-5ba19e6b9ca1)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/cc788b64-6709-4cd1-9f24-baad6397e4b9)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/301cb66d-4bc3-4ab4-9934-a4ce5a211e73)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/798e09cf-e1ad-4715-9d0c-323d341fdb48)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/36085092-5cae-49f6-819a-dad0afc979fe)

**Comment by brettsam** [comment]
@rodolfograve -- I've been trying to reproduce this all day without any luck. I can certainly see that your app is spiking to near 100% CPU when you've added the package, then it's only hitting around 70% without it. And I can see the significant response time differences. But I've not been able to reproduce this difference with what I've been trying. I've also looked through all the code changes from preview4 -> 1.0.0 and nothing is jumping out at me as particularly alarming in this package...

Would you be able to reach out to me over email (my Microsoft contact info is in my github bio) and we can see if we can get more details that way? Then I can update this thread with the findings.

**Comment by rodolfograve** [comment]
Still unsuccessful reproducing the issue in a toy project, but I can confirm that the issue is introduced in preview5.

Upgrading Microsoft.Azure.Functions.Worker.ApplicationInsights from preview4 to preview5 is enough to start experiencing the performance hit.

**Comment by brettsam** [comment]
@rodolfograve and I have been investigating this and the issue appears to be related to Application Insights itself, not the new Functions package. Even without referencing or calling the Functions-specific code, the issue occurs. We've not yet been able to isolate the scenario, but for now, I think we can conclude it's not related to preview5 or 1.0.0.

It may be related to how the service registration changed and how/where this was happening in this project's code. We're going to continue debugging this and try to find the culprit, but wanted to let anyone else that may be following this issue know that there does not appear to be a fundamental performance degradation that's coming directly from these new packages.

**Comment by rodolfograve** [comment]
A quick update here to say that after updating Microsoft.Azure.Functions.Worker.Sdk from 1.14.1 to 1.15.0 the issue still persists.

As part of my work with @brettsam I have determined that:

1. Upgrading Microsoft.Azure.Functions.Worker.ApplicationInsights to 1.0.0
2. Calling services.AddApplicationInsightsTelemetryWorkerService()
3. Not calling services.ConfigureFunctionsApplicationInsights()

Does not cause the issue. The services.ConfigureFunctionsApplicationInsights() call is required for the performance degradation to kick in (obviously not a solution because AppInsight integration doesn't work without it)... but a clue.

@brettsam, I'll send you some new information privately.

**Comment by rodolfograve** [comment]
These are the ApplicationInsightsDebug logs:

1. [Without services.ConfigureFunctionsApplicationInsights()](https://github.com/Azure/azure-functions-dotnet-worker/files/12866715/RodolfoGrave-AppInsightsDebugLogs-Without-ConfigureFunctionsApplicationInsights-VERBOSE-20231010-105718.dotnet.exe.7060.log)
2. [With services.ConfigureFunctionsApplicationInsights()](https://github.com/Azure/azure-functions-dotnet-worker/files/12866716/RodolfoGrave-AppInsightsDebugLogs-With-ConfigureFunctionsApplicationInsights-VERBOSE-20231010-105319.dotnet.exe.6072.log)

The files are different but I can't spot anything that gives me a clue about could be going on. The AppInsights loading/initialization seems to take 4x longer with the call, but that's only from 20m to 1s, which doesn't explain the increase in the function's execution time from 2s to 8s or more.

**Comment by rodolfograve** [comment]
The latest changes/improvements to our code seem to have made the issue disappear. To be clear, the issue is still there but seems to occur under very specific circumstances which no longer apply to us.

The main change we have made is to drastically reduce the number of calls made to Azure Storage from thousands to one.
