### ISSUE TITLE
Allow simpler testing with ConfigureFunctionsWorker

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#183]
Currently, Functions worker is configured with `UseFunctionExecutionMiddleware()` to provide the necessary infrastructure for triggers and output bindings. I'd like to be able to test my functions w/o running the full middleware when using the [container DI based Functions](https://github.com/Azure/azure-functions-dotnet-worker-preview/blob/main/FunctionApp/Function5/Function5.cs). This will allow simpler testing scenarios that do not require Functions runtime to be installed and bootstrapped.

**Comment by fabiocav** [comment]
Wanted to provide an update on this issue.

It's a bit lower priority compared to some of the other work happening at the moment (particularly V4 and .NET 6.0), but we had a discussion on this and @brettsam is working through some prototypes and design (timer permitting). We might be able to share some of that in an issue so we can get some feedback on the experience as well.

**Comment by jviau** [comment]
Closing in favor of #281
