### ISSUE TITLE
Microsoft.Azure.Functions.Worker.ApplicationInsights GA Released? 

### ISSUE THREAD

**Issue by renjums** [Azure/azure-functions-dotnet-worker#1830]
I see a stable release for Microsoft.Azure.Functions.Worker.ApplicationInsights package in Nuget. 

--prerelease mentioned in README !!!

https://github.com/Azure/azure-functions-dotnet-worker/blob/79779b64a15265bb3976ac11297c510df44f1b50/src/DotNetWorker.ApplicationInsights/README.md?plain=1#L13C61-L13C61

**Comment by SeanFeldman** [comment]
The stable package was **just** released. The documentation didn't have a chance to catch up yet.
<img width="629" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/1309622/2b24c801-3a1f-4692-bf87-e28992a85c65"> 

@renjums, slow your horses 🙂

**Comment by mattchenderson** [comment]
I've got PRs out for the readme and for the Microsoft Learn docs to fix this.
