### ISSUE TITLE
dotnet isolated function is still throwing RPC exceptions even after EnableUserCodeException=true

### ISSUE THREAD

**Issue by inishantmishra** [Azure/azure-functions-dotnet-worker#1833]
Even after enabling the EnableUserCodeException = true in dotnet isolated Azure function, I am still receiving RPC exceptions with no call stack.
I thought after implementing this change, if l throw some custom exception in my code and if I handle it and log it, I will get my custom exception in appInsights but it is not happening, I am still getting RPC exceptions with no call stack.

Let me know what am I missing? Why am I still receiving RPC exceptions?

I am using
dotnet-isolated
~4
.net 7 Isolated Azure function

@fabiocav @liliankasem @madelinegordon

**Comment by liliankasem** [comment]
Can you provide a minimal code repro project for the team to investigate?

**Comment by inishantmishra** [comment]
This is program.cs
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/0fb43ce1-796a-43aa-976a-5a2fedc2a336)


This is my service bus test function. Here to replicate the scenario, I am throwing the NonCriticalException which gets caught and we are simply logging as warning with Ilogger. But when we go and check over AppInsight, it is still coming as RPC exception and still no call stack.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/5b8a85f2-ece3-4843-97b6-9d7ba3c9ea2d)

**Comment by liliankasem** [comment]
@inishantmishra - thank you, do you mind turning this into a small project in a GH repo that you can share? (this is what I mean by minimal repro project) I'm looking to run through the code and debug with the worker and host, screenshots don't help with that. Making sure to include things like the host.json config etc. is also really helpful to this - thanks!

In the meantime @RohitRanjanMS, I know you helped with this feature a bit - does anything stand out to you in the screenshots above?

**Comment by RohitRanjanMS** [comment]
Hi @inishantmishra , what's the sdk version in the log that you see in the AI? Also, can you please remove service.AddLogging and test this behavior?

**Comment by inishantmishra** [comment]
@RohitRanjanMS 
SDK Version is coming correctly.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/17c1c8ea-9af5-4e3b-ba88-103b26c8b9a1)

If I remove the following snippet, how will I be able to log on AppIngishts?
services.AddLogging(builder =>
        {
            builder.AddApplicationInsights();
        });

**Comment by RohitRanjanMS** [comment]
Hi @inishantmishra , please use the AI integration instrumented by us. https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights

```
 var host = new HostBuilder()
       .ConfigureFunctionsWorkerDefaults(builder => { }, option =>
       {
           option.EnableUserCodeException = true;
       })         
       .ConfigureAppConfiguration(config => config
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("local.settings.json", optional: true)
                    .AddJsonFile("appsettings.json", optional: false)
                    .AddEnvironmentVariables())
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        services.Configure<LoggerFilterOptions>(options =>
        {
            // The Application Insights SDK adds a default logging filter that instructs ILogger to capture only Warning and more severe logs. Application Insights requires an explicit override.
            // Log levels can also be configured using appsettings.json. For more information, see https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs
            LoggerFilterRule toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
            if (toRemove is not null)
            {
                options.Rules.Remove(toRemove);
            }
        });
        var serviceProvider = services.BuildServiceProvider();

        var configuration = serviceProvider.GetRequiredService<IConfiguration>();

        services.AddHttpClient();
    })
    .Build();
await host.RunAsync();
```
<img width="398" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/90008725/15b58382-fd9e-4d16-9692-e33cc82b7024">

**Comment by inishantmishra** [comment]
Hi @RohitRanjanMS,
It worked. thanks. Can you let me know if I remove the default log level, then from where will it pick the level?
My guess is from app setting over which I have defined like this
 "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
  
  Also, will the host also log the same level which i have defined above on AI.
  
 What does the Function Monitor section indicate? Will it have user code exceptions and logs or something else?
 Where does host logs will be?

**Comment by inishantmishra** [comment]
@RohitRanjanMS 
Post implementation what you have mentioned, 
I noticed, I am getting following errors
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/daa8f2b2-c86c-48c1-ae93-ce6b92aa308d)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/dd98da81-0288-43cf-bf1e-2e9058a2941a)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/f4cdb75d-aa23-467d-a053-72fc6b0e5677)

![Uploading image.png…]()

**Comment by MrChandanSingh** [comment]
Hi Team,

I am facing the similar issue after migrating from .Net 6 to 8.0. It is look like orchestrator is not waiting for activity function to complete activity then go for another activity. but it is not happening .
`Exception while executing function: Functions.CreateLoadOfferOrchestrator Result: Failure
Exception: System.InvalidOperationException: An ExecutionStarted event is required.
   at DurableTask.Core.OrchestrationRuntimeState.GetExecutionStartedEventOrThrow() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 210
   at Microsoft.DurableTask.Worker.Grpc.GrpcOrchestrationRunner.LoadAndRun(String encodedOrchestratorRequest, ITaskOrchestrator implementation, IServiceProvider services)
   at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 58
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at DurableTask.Core.OrchestrationRuntimeState.GetExecutionStartedEventOrThrow() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 210
   at Microsoft.DurableTask.Worker.Grpc.GrpcOrchestrationRunner.LoadAndRun(String encodedOrchestratorRequest, ITaskOrchestrator implementation, IServiceProvider services)
   at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 58
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88 `
`var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
     .ConfigureAppConfiguration((context, builder) =>
     {
         builder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
         builder.AddEnvironmentVariables();
     })
    .ConfigureServices((Context, Services) =>
    {
        Services.AddApplicationInsightsTelemetryWorkerService();
        Services.ConfigureFunctionsApplicationInsights();
        Services.AddDataAccessDependencies();
        Services.AddHttpClient<SamsaraClient>(SamsaraConstants.SamsaraClient, options =>
        {
            options.DefaultRequestHeaders.Accept.Clear();
        });
        Services.AddHttpClient<ArcGisClient>(ArcGisConstants.ArcGisClient, options =>
        {
            options.DefaultRequestHeaders.Accept.Clear();
        });
        Services.ConfigureCacheAsTransientDependency(Context.Configuration);
        Services.AddHttpContextAccessor();
        Services.AddApiContextAccessor();
        Services.RespositoryDependency();
        Services.ServiceDependency();
        Services.AddNotificationDependencies();
        Services.AddAzureSmsDependencies();
    })
    .Build();

host.Run();
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/19989564/aa775a56-2213-4220-81ce-f010a847a8fc)
`
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/19989564/e5a3b06c-c216-445c-8a7d-cd3c674b36ce)

**Comment by davidmrdavid** [comment]
Hi @MrChandanSingh: Please create a new issue in the Durable Functions repo here: https://github.com/Azure/azure-functions-durable-extension . The Durable team should be able to assist from there.

**Comment by MrChandanSingh** [comment]
> Hi @MrChandanSingh: Please create a new issue in the Durable Functions repo here: https://github.com/Azure/azure-functions-durable-extension . The Durable team should be able to assist from there.

@davidmrdavid done
