### ISSUE TITLE
Upgrade Assistant from Host V1 misses EventHubs packages

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1836]
`<PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="2.2.0" />` was all you needed for both Service Bus and Event Hubs in Host V1. Upgrade Assistant will convert this into `<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />`, but it is missing the additionally necessary reference to https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs.

In both cases, the latest stable versions should be used. That is an older version of the worker Service Bus extension, behind by a major version.

**Comment by mattchenderson** [comment]
Actually, it's perhaps worth noting that the "Trigger types" list during the "Select components to upgrade" phase doesn't show `EventHubTrigger` at all. I'm not sure if that's related to this issue or would need to be spun off as its own thing.

**Comment by aishwaryabh** [comment]
PR for this: https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/498438

**Comment by aishwaryabh** [comment]
PR has been merged in
