### ISSUE TITLE
Upgrade Assistant from Host V1 does not handle WebHookType

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1837]
Host V1 HttpTriggers had a `WebHookType` property that would define some behaviors. For example, `[HttpTrigger(WebHookType = "github")]HttpRequestMessage req`.

Upgrade Assistant currently does not touch these, and will leave them in the new HttpTrigger attribute, causing a build error. This should be addressed somehow. The behavior of the old property is described [in our documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cin-process%2Cfunctionsv2&pivots=programming-language-csharp#webhook-type). Likely, the right thing to do here is to convert this to a standard HttpTrigger and add some handling which captures the logic that these modes represented. MIddleware may be a good fit.

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DevDiv/_git/UpgradeAssistant/pullrequest/499386

**Comment by aishwaryabh** [comment]
PR has been merged in
