### ISSUE TITLE
Upgrade Assistant should set up ASP.NET Core integration

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1838]
Once ASP.NET Core integration is GA, we should add it to Upgrade Assistant to ensure that anyone coming in with any of the combinations of types in an in-proc project is able to continue using those types.

Upgrade Assistant doesn't support a new project target of .NET Framework, so it should always be valid to use ASP.NET Core integration, and converted apps needn't be introduced to `HttpRequestData`/`HttpResponseData`.

The current behavior does swap `HttpRequestMessage` for `HttpRequestData` (and similar for responses) without touching function code related to it. I think in those cases it may be appropriate to instead swap to `HttpRequest`, etc. If we start making broader changes to the function body itself, that may need further interrogation, but that should be tracked separately.

**Comment by aishwaryabh** [comment]
PR for this issue: https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/497324

**Comment by aishwaryabh** [comment]
PR has been merged in!
