### ISSUE TITLE
Upgrade Assistant does not parse FileAccess for Blobs / AccessRights for Service Bus

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1839]
In-process blob input and outputs use an `Access` property, which is largely how the two are distinguished. These properties are not present in the worker. However, Upgrade Assistant currently leaves them in place, which causes a build issue at the end. Further, it will make both into an input binding.

This example starting state:
```csharp
        [Blob("test-samples-output/{name}-output.txt", FileAccess.Write, Connection = "blobconn")] TextWriter myBlobOut,
        [Blob("test-samples-input/sample1.txt", FileAccess.Read, Connection = "blobconn")] string myBlob,
```

... currently becomes:

```csharp
        [BlobInput("test-samples-output/{name}-output.txt", FileAccess.Write, Connection = "blobconn")] TextWriter myBlobOut,
        [BlobInput("test-samples-input/sample1.txt", FileAccess.Read, Connection = "blobconn")] string myBlob,
```

There might be a more general issue to highlight there that would affect other extensions as well.

Service Bus in Host V1 also has an `Access` property which is also preserved incorrectly, though there's no input/output disambiguation. It also appears on the trigger, which is not the case for blobs.

CC @gabesmsft

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/501588?path=/src

**Comment by aishwaryabh** [comment]
PR for service bus access rights issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/504858

**Comment by aishwaryabh** [comment]
Both PRs have been merged in
