### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by ngg** [Azure/azure-functions-dotnet-worker#184]
Currently the preview of Microsoft.Azure.Functions.Worker only targets net5.0.
Is there a plan to support netcoreapp3.1 or netstandard2.0/2.1?

We'd like to be able to update our functions to this new out-of-process mode, but we won't be able to use .NET 5 as it is not an LTS version (EOL is too soon). It would be great if we wouldn't have to wait until .NET 6 is released.

**Comment by fabiocav** [comment]
@ngg closing this as it is a stale issue and no longer applicable, but please let us know if you need anything else here.
