### ISSUE TITLE
Upgrade Assistant does not convert Durable Functions types

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1840]
`IDurableOrchestrationContext`, etc. are left as they are and not converted to the newer equivalents. It also seems like the `using Microsoft.Azure.WebJobs.Extensions.DurableTask;` will be dropped without replacement, though there does seem to be a mapping of the package references that is at least occuring:

From:
```xml
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.9.3" />
```
To:
```xml
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
```

cc @gabesmsft

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/503889

**Comment by aishwaryabh** [comment]
PR has been merged
