### ISSUE TITLE
dotnet-isolated: a dependency item is written to AI on each function invocation even though enableDependencyTrackingTelemetryModule is false

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#1845]
I have a dotnet-isolated function with AI logging added via:

```
            .ConfigureServices(s =>
            {
                s.AddApplicationInsightsTelemetryWorkerService();
                s.ConfigureFunctionsApplicationInsights();
            })

```

in appsettings.json i have this:

```
    "applicationInsights": {
        "enableDependencyTrackingTelemetryModule": false
    },
```

On each function invocation i get this item in ApplicationInsights:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/580460/0e445900-8a80-4906-9bae-6d3b91384e2f)

This is really annoying since this function is a EventHubsTrigger which gets called really-really frequently. So we get lots of unnecessary data in AI that we have to pay for. Any idea how to disable these?

**Comment by dmytro-gokun** [comment]
I found that some people reported similar behavior in the past (with type of 'Azure.Functions' instead of 'InProc' which could be because of worker version), e.g.: https://github.com/Azure/azure-functions-dotnet-worker/issues/1304#issuecomment-1416077143. I was not able to find a work around though

**Comment by jviau** [comment]
`enableDependencyTrackingTelemetryModule` is for AppInsights `DependencyTackingTelemetryModule`. It has nothing to do with our own [telemetry module](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.ApplicationInsights/FunctionsTelemetryModule.cs). If you do not want these telemetry items you can add an `ITelemetryProcessor` and filter out our `DependencyTelemetry` (you can test by the existence of the property `faas.execution`).

At the time we have no plans for adding a specific setting to configure this behavior directly.

**Comment by dmytro-gokun** [comment]
@jviau Thanks for explanation. This makes sense, though i would say little bit of configurability/documentation around this behavior would not hurt :). But it is what it is. Thanks
