### ISSUE TITLE
Is TimeTrigger supported?

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#185]
Getting this error:

```
The 'XXX' function is in error: Can't figure out which ctor to call.
```

**Comment by dmytro-gokun** [comment]
@fabiocav Thanks for the update.

> Functions runs on App Service (consumption and dedicated/app service plans).

Please check the screenshot above. When using Consumption App Service Plan you do NOT have "Stack settings" under "Configuration" -> "General settings". That is the problem and that's why I asked if I needed to enable something on the portal so see that. I've now re-read the article at the link you've posted and I do not see anything like that. It just claims that .NET 5 should be available already. And it is, but only when using a dedicated App Service Plan. So, i'm still left in the limbo here. I am willing to give this preview one more try, but I cannot since all our functions use Consumption Plan. Any advice?

**Comment by sccrgoalie1** [comment]
I'm having trouble getting my TimerTriggers working on Azure as well.  I have a service bus trigger that works fine, but the timers aren't firing.  We are running on the premium plan, so don't have an explicit option to change to .NET 5, but if that was the problem wouldn't the service bus trigger fail as well?

I just updated to preview 5 today hoping that would work, but no such luck.

**Comment by dmytro-gokun** [comment]
@fabiocav Any chance you can help with this issue. Or is it's just we should accept that this out of process thing does not work with Consumption Plans and wait for .NET 6 (or 7?). I'm totally confused.

**Comment by sccrgoalie1** [comment]
I got it working after I found this error.  In the past this setting had always been there in the portal, but was missing.  I set the AzureWebJobsStorage configuration setting and then it started working.

![image](https://user-images.githubusercontent.com/2366790/110948433-f5b11e00-8306-11eb-8616-56e025a72b25.png)

**Comment by brettsam** [comment]
@sccrgoalie1 -- do you know how you created your app? Missing that storage setting would cause some issues so we should try to prevent it wherever we can.

**Comment by sccrgoalie1** [comment]
> @sccrgoalie1 -- do you know how you created your app? Missing that storage setting would cause some issues so we should try to prevent it wherever we can.

I believe I added a slot in the Azure portal and then deployed as described in the readme

**Comment by fabiocav** [comment]
Closing this issue as it looks like all questions/issues have been addressed. 

If there are any remaining questions, please feel free to open a new issue.

Thank you, all!
