### ISSUE TITLE
Unable to return non-standard (e.g. >= 512) HTTP status codes 

### ISSUE THREAD

**Issue by jpdillingham** [Azure/azure-functions-dotnet-worker#1852]
I have a use case that lends itself to using user-defined HTTP status codes, particularly those at or above 512, which are unassigned per [the IANA registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml).  I haven't found anything in the public API that allows me to create [HttpResponseData](https://github.com/Azure/azure-functions-dotnet-worker/blob/38e27120dab17da1b909486301b23899b24610d5/src/DotNetWorker.Core/Http/HttpResponseData.cs) with an integer instead of a member of `HttpStatusCode` (which is impossible given the design of this class)

Am I missing something, or is this unsupported?  And if unsupported, is there rationale that isn't obvious?

**Comment by jviau** [comment]
@jpdillingham you can accomplish this by casting:

``` CSharp
request.CreateResponse((HttpStatusCode)513);
```

Enums are just facades over `int` in C#
