### ISSUE TITLE
Correct Way To "Negotiate" SignalR Serverless

### ISSUE THREAD

**Issue by SimonOrdo6** [Azure/azure-functions-dotnet-worker#1854]
We're attempting to migrate from serverless SignalR in-proc Azure functions to .NET 7 Isolated.  We have a signed JWToken that we fetch from the server for SignalR connection initialization via `accessTokenFactory` like so:

`
const connection = new signalR.HubConnectionBuilder()withUrl('http://localhost:7071/api', 
{ accessTokenFactory: () => "aJwtTokenViaAjaxThatIncludesClaimsAndUserId" })
 .build();
`

In the In-proc model, we handle the Negotiate method something like this:

```
[FunctionName("negotiate")]
        public static IActionResult NegotiatBinding(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
            IBinder binder)
        {
            if (req.Headers.ContainsKey(AUTH_HEADER_NAME) && 
               req.Headers[AUTH_HEADER_NAME].ToString().StartsWith(BEARER_PREFIX))
            {
                var token = req.Headers["Authorization"].ToString().Substring(BEARER_PREFIX.Length);
              
                // extract userId and claims from token
                var userId = "userIdExctractedFromToken"; // decoding and validation method
                var connectionInfo = binder.Bind<SignalRConnectionInfo>(new SignalRConnectionInfoAttribute{
                HubName = "messages", 
                ClaimTypeList = new[] {"Claim1", "Claim2"}
                IdToken = token,
                UserId = userId
                
                });
  
                // connectionInfo contains an access key token with a name identifier claim set to the authenticated user
                return (ActionResult) new OkObjectResult(connectionInfo);
            }
            else
            {
                return (ActionResult) new BadRequestObjectResult("No access token submitted.");
            }
        }
```

Note that we are validating and decoding the JWToken that we supplied to the SignalR client to ensure it wasn't tampered with before we add the claims to the SignalRConnectionInfo.  Note also that the SignalR client appears to add the "BEARER" prefix to the JWToken we supplied, so we manually strip it out for decoding.

In the Isolated process model, the Negotiate function looks like this:

```
        [Function("negotiate")]
        public async Task<HttpResponseData> Negotiate([HttpTrigger(AuthorizationLevel.Anonymous)] HttpRequestData req,
                [SignalRConnectionInfoInput(HubName = "editorsession", ConnectionStringSetting = "SignalRConnection", UserId = "???", IdToken = "{headers.Authorization}", ClaimTypeList = new[] { "Claim1", "Claim2" })] Microsoft.Azure.Functions.Worker.SignalRConnectionInfo connectionInfo)
        {
            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "application/json");
            response.WriteString(connectionInfo.ToString());
            return response;
        }

```

- This throws an error of "malformed token", maybe because of the "BEARER" prefix that the SignalR client prepends that I have no way of stripping out (without the benefit of `IBinder`, which isn't available for Isolated functions).  
- Even if that did work, how can I validate my supplied JWToken's signature before adding the claims from that token to the SIgnalR connection info?  Obviously I can't just trust what the client sends.
- How can I extract my user's name for `SignalRConnectionInfo .UserId`, if it's embedded in the JWToken? I don't just want to pass it from the client, since it's not tamper proof. What's the point of passing an authentication token from the client if we can't validate it? I feel like I'm missing something obvious. 

Both `IBinder`  and `ServerlessHub` subclassing for Isolated function models provide ways to handle these issues, but I haven't found anything for Isolated function models.

The [docs](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences) suggest that if runtime resolved parameters are needed that, instead of imperative bindings, we should consider using the service SDKs directly,  which in this case appears to be 'Microsoft.Azure.SignalR.Management'.  I believe the relevant code would like this:

`var negotiationResponse = await serviceHubContext.NegotiateAsync(new (){UserId = "<Your User Id>"});`

That, however, seems to require first creating a 'HubContext', which seems like the wrong thing to do in this scenario - admittedly because I'm not confident in how or if that would interact with the underlying messaging or networking.   Do I need to ditch SignalR function triggers and bindings entirely and just roll a "manual" serverless integration, if I need this feature?

@Y-Sindo , 

Thank you in advance.

**Comment by Y-Sindo** [comment]
[SimonOrdo6](https://github.com/SimonOrdo6) We'll be able to meet your requirements in the upcoming release once we've resolved the #1709 issue. You'll then be able to use `ServerlessHub`, a new feature that we've introduced in the latest release. This integrates the service SDK and offers a better programming experience, with a class-based model similar to that used in in-proc SignalR extensions

**Comment by SimonOrdo6** [comment]
Thank you @Y-Sindo .

Do you have any visibility on potential timing?  Are we looking at weeks, months, etc before `ServerLessHub` functionality comes to Isolated function model?  Trying to determine if we need to implement a hack or defer the work until this is resolved.

Thanks in advance!

**Comment by Y-Sindo** [comment]
@SimonOrdo6 Apologies for the delayed response. It seems that resolving this issue may require the collaboration of multiple teams. In my opinion, it would be best to calculate the time required in terms of months.

**Comment by liliankasem** [comment]
@Y-Sindo - are there any updates on this?

**Comment by Y-Sindo** [comment]
Hi @SimonOrdo6, please use the latest SignalR extensions for dotnet isolated model and see the sample code here to achieve your requirement:
https://github.com/aspnet/AzureSignalR-samples/blob/main/samples/DotnetIsolated-ClassBased/Functions.cs#L34-L44
