### ISSUE TITLE
Is ServiceBusTrigger supported at all?

### ISSUE THREAD

**Issue by Mithras** [Azure/azure-functions-dotnet-worker#186]
```
[FunctionName("ServiceBusTest")]
public static async Task ServiceBusTest(
    [ServiceBusTrigger("qwerty", Connection = "MyConnectionString")] string message)
{ }
```
throws "Microsoft Azure WebJobs SDK ServiceBus connection string 'MyConnectionString' is missing or empty." before Main() is called so I have no way of providing a connections string.

**Comment by Mithras** [comment]
@fabiocav I just want a way to do something similar to .ConfigureAppConfiguration(...) for the host. I can probably survive with App Service Key Vault references for now but what if I need to do something that is not KeyVault? Is it possible to define my own Reference implementation similar to KeyVault like "@MyOwn.NotKeyVault(...)"? That would be a real solution as I would be able to build that reference implementation for whatever .NET the host uses.

**Comment by chris-oswald** [comment]
@fabiocav I also want to be able to access the app configuration values from Azure during bootstrap.  It sounds like this isn't in scope for GA (must use local.setting.json), which I'm not really excited about.  I'm just using the consumption plan, not premium or app service.

**Comment by fabiocav** [comment]
For configuration values used by the triggers, that's where there's a limitation. For configuration within the context of your app, you should have the ability to do that just as you would with other .NET apps.

**Comment by chris-oswald** [comment]
This may or may not be obvious to others, so I'll post this just in case.  If you use the "Application Settings" under the configuration tab in the azure portal (functions) you can put the connection string there and abstract it from your code.  I would like this to be in key vault for consistency, but it's at least an acceptable workaround for my use case.

This has allowed me to get a working version of Service Bus trigger working

**Comment by fabiocav** [comment]
Key Vault is supported as a source of app settings configuration.

Please see https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references for information

**Comment by phekmat** [comment]
> 
> 
> Key Vault is supported as a source of app settings configuration.
> 
> Please see https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references for information

Note that if you go this route *and* you're using Key Vault via a config builder, you should avoid loading secrets with the same name. 

If the referenced secret in app configuration drifts (e.g. a new version is added to the vault), the function runtime will error on consumption plans because the trigger changed (at least for the in-process worker: https://github.com/Azure/azure-functions-host/issues/7210)

**Comment by fabiocav** [comment]
@phekmat indeed that is the behavior of the configuration system and order of registration matter here. That said, configuration does follow the order of precedence described in the feature documentation, where last one wins.

**Comment by jamyc** [comment]
> For triggers, this won't be supported at GA. The alternative here is to use App Service Key Vault references in the meantime (https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references)

@fabiocav I'm really looking forward to using `builder.AddAzureKeyVault(...)` and then referencing a secret in e.g. an EventHubTrigger. As I understand from your comment, this is currently not supported. Is this a feature that's being considered? If so, do you have any idea where this fits in the roadmap.

**Comment by Mithras** [comment]
For us Key Vault references is a good enough solution that at least unblocked us
We still have to wrap functions in `#if !DEBUG` like this
![image](https://user-images.githubusercontent.com/2098029/126004675-65c9535f-4c48-401c-9c04-9fedaf16c05f.png)
though because devs can't use Key Vault references locally and we have to copy-paste the secret to local.settings.json and then remove `#if !DEBUG` in order to run ServiceBus trigger functions locally.
I believe I was promised at least User Secrets support in some other issue in order to mitigate the pain of not being able to use secrets from KeyVault locally.

**Comment by Hipster74** [comment]
Any news regarding this? 

Creating a dotnetisolated .NET 5.0 azure function with a ServiceBusTrigger, is it still true that I can't reference my local user-secrets store when filling in the connectionstring? 

When running in Azure, KeyVault reference is good, but for running locally on my devmachine I want to reference the local connectionstring that I have set in user-secrets.

**Comment by ianmccaul** [comment]
I agree, seems like quite the step back. Can't use app config either. To run locally this is a real problem.

**Comment by ryantuffney-shell** [comment]
Any update on this ?

**Comment by michielvoo** [comment]
As a workaround I have set `AzureWebJobsServiceBus` in `properties/launchSettings.json` and added that file to `.gitignore`. This file does not need to be published (e.g. `<CopyToPublishDirectory>never</CopyToPublishDirectory>`). When running locally this is shown in the console:

> Skipping 'AzureWebJobsServiceBus' from local settings as it's already defined in current environment variables.

So I've set the value in local.settings.json to `"secretLaunchSetting"` as a reminder that the value can be found elsewhere.

**Comment by jviau** [comment]
Unfortunately, the config gap is a limitation of the system we will not be addressing any time soon. The host needs to know about all these config values _without loading any customer assemblies or running the worker at all_. All of the asks here are around providing config values to the host via code and custom config sources. This will just not be possible as it is a core requirement for us to monitor triggers without loading or running any customer code.

Going to close this for now. If we decide to revisit this later we can circle back.
