### ISSUE TITLE
Package Reference crashes Azure Function

### ISSUE THREAD

**Issue by flxgrds** [Azure/azure-functions-dotnet-worker#1862]
Hello,

Situation:
I have a isolated Azure Functions App. This app runs locally. I have Triggers from WebPubSub and HttpTriggers. I do not havve an CosmosDB-Triggers oder Bindings yet. 

Change:
I add Microsoft.Azure.Functions.Worker.Extensions.CosmosDB in Version 4.x.x to my Project.

Symptoms:
When i request an HttpTrigger the correct functions is reached but no response is given. When i delete the package from the project everything works fine again.

**Comment by kshyju** [comment]
@flxgrds 
Just to confirm - Are you saying everything working as expected locally, but it does not work when your app is deployed to azure? Did you check the application insight logs? Anything interesting logged there to give you some leads?

**Comment by kshyju** [comment]
If you are experiencing this issue locally as well, Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by kshyju** [comment]
@JialinXin Could you please take a look? I realized the Microsoft.Azure.Functions.Worker.Extensions.WebPubSub extension in not in this repo.

**Comment by JialinXin** [comment]
@kshyju OK, let me check.

**Comment by JialinXin** [comment]
@flxgrds It seems related to the `Microsoft.Azure.Functions.Worker` package version. Update to any version later than 1.8.0 works. 

@kshyju Do you aware there's any changes related?

**Comment by JialinXin** [comment]
Update to a latest worker package version can fix this issue. So please update to `Microsoft.Azure.Functions.Worker` to latest 1.19.0.

**Comment by kshyju** [comment]
Closing as answered. We recommend using the latest stable version of all packages.
