### ISSUE TITLE
WorkerExtensions.csproj does not use the repo's NuGet.config due to being in temp dir

### ISSUE THREAD

**Issue by dfederm** [Azure/azure-functions-dotnet-worker#1863]
It appears that WorkerExtensions.csproj is generated under the temp dir and is attempted to be restored at build time. Because it's in the temp dir, it will not pick up the repo's NuGet.config and so will try to restore from nuget.org by default. This causes problems if either there is a firewall to the public internet, or if there are packages in use which are not on nuget.org.

If this temp project much be generated, it should be under the `$(IntermediateOutputPath)` instead. This has added benefits of not placing files outside the repo entirely which makes a "git clean" unproductive and slowly fills the disk over time.

**Comment by jviau** [comment]
This change has already been made, but is not released yet: https://github.com/Azure/azure-functions-dotnet-worker/pull/1749

We intend to make further changes before releasing.

**Comment by kemmis** [comment]
Has this fix been release yet?

**Comment by jviau** [comment]
Not to nuget.org yet, but a build is available here for testing:
https://dev.azure.com/azfunc/Azure%20Functions/_artifacts/feed/AzureFunctionsTempStaging/NuGet/Microsoft.Azure.Functions.Worker.Sdk/overview/1.16.0-preview2

**Comment by TLaborde** [comment]
Using the preview2, the issue is only partially fixed. Instead of 5 called to nuget, only 2 happens:
```
##[error]C:\Users\AzDevOps\AppData\Local\Temp\4uf5sbqs.0le\WorkerExtensions.csproj(0,0): Error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\Users\AzDevOps\AppData\Local\Temp\4uf5sbqs.0le\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
##[error]C:\Users\AzDevOps\AppData\Local\Temp\4uf5sbqs.0le\WorkerExtensions.csproj(0,0): Error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\Users\AzDevOps\AppData\Local\Temp\4uf5sbqs.0le\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
```

**Comment by slaneyrw** [comment]
There may be further issues here, in that Directory.Build.props and Directory.Build.targets can also affect the resultant sources.
Your PR referenced above explicitly blocks this.

We use the RestoreAdditionalProjectSources element to conditionally add more sources.

If the goal is to avoid extra code assets from being included, maybe consider adding build properties that can be evaluated in our props and targets to avoid bringing in code assets.  As long as this is well documented we can control this.

**Comment by jviau** [comment]
@slaneyrw not including directory.build.targets is intentional as we want to tightly control the properties and values of this generated project. Allowing these additional targets to implicitly flow in will make our inner build too susceptible to accidental breaks due to those targets/props. This will be a headache for customers as changing TFM, output directory, etc can lead to breaks that will be very hard to understand.

The refactored targets do pass in the parents nuget restore sources explicitly to the inner build, I'll verify if this includes `RestoreAdditionalProjectSources`

**Comment by jviau** [comment]
@slaneyrw I believe the SDK changes in PR right now will include `RestoreAdditionalProjectSources`, I am passing `$(_OutputSources)` to the inner-build, which is what the nuget targets calculate as the combination of all input nuget restore sources for the current project.
