### ISSUE TITLE
Will binding to http route elements from the HTTP trigger be supported?

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-functions-dotnet-worker#187]
Before, [parts of a url could be bound to](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#using-route-parameters), which could then be used in other bindings.

E.g. you could take a part of the HTTP trigger url, and use that for a binding to a storage item.

Or see [this sample](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=csharp#http-trigger-look-up-id-from-route-data-c).

Will this still be possible?

**Comment by kshyju** [comment]
@hansmbakker This should be working. Here is a quick sample for your reference.

```
[Function("GetItemsFromBlob")]
public HttpResponseData Run(
     [HttpTrigger(AuthorizationLevel.Function, "get", Route ="items/{itemId}")] HttpRequestData req,
     [BlobInput("samples-workitems/{ItemId}.txt", Connection = "MyStorageConnString")] string blob
    )
{
    var response = req.CreateResponse(HttpStatusCode.OK);
    response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

    response.WriteString($"Blob content: {blob}");

    return response;
}
```

This sample is reading the itemId value from the http request URL and use that for getting the blob input entry. For example if you issue a request like `/api/items/foo`, "foo" will be bound to the ItemId segment of the route and the blob input binding will try to get the "foo.txt" file from the "sample-workitems" container.

Let us know if you run into any issues.
