### ISSUE TITLE
Upgrade assistant converting HTTP types in function body

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1871]
Upgrade Assistant should not be changing types for objects that are defined within user code. Today, if you run upgrade assistant with code like the following...

```csharp
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "someurl")
            {
                Content = new StringContent("foo")
            };
```

... you will have it converted to using `HttpRequestData`, though it's still attempting to use the `HttpRequestMessage` constructor, so it gets a build error....

```csharp
            HttpRequestData request = new HttpRequestData(HttpMethod.Post, "someurl")
            {
                Content = new StringContent("foo")
            };
```

Upgrade Assistant should not touch that type.

This may be obviated by https://github.com/Azure/azure-functions-dotnet-worker/issues/1838 since with that, we wouldn't be introducing HttpRequestData where it wasn't previously. But there might be a more general pattern here. Even with that, a user-defined `HttpRequestMessage` should stay as-is.

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/504090

**Comment by aishwaryabh** [comment]
PR has been merged in
