### ISSUE TITLE
Upgrade Assistant missing return type attributes when coming from in-process model

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#1872]
In-process model functions could specify an output binding using the following format: `[return: ServiceBus("queueName", Connection = "connectionName")]`

Upgrade Assistant seems to be leaving this as-is, rather than converting it to the isolated worker model's equivalent: `[ServiceBusOutput("queueName", Connection = "connectionName")]`

These examples are for Service Bus specifically, but this would apply to all extensions.

**Comment by aishwaryabh** [comment]
PR for issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/UpgradeAssistant/pullrequest/503561

**Comment by fabiocav** [comment]
Review currently in progress. Moving to sprint 157

**Comment by aishwaryabh** [comment]
PR has been merged in
