### ISSUE TITLE
throughput dashboard updates for .NET 8

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#1875]
Issue tracking required changes/updates to make sure the throughput data is flowing as expected.

**Comment by fabiocav** [comment]
Changes being made in: https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests

**Comment by satvu** [comment]
Throughput testing repo is [here](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests).

Throughput should be tested with ASP.NET integration.

**Comment by satvu** [comment]
Test apps have been tested locally and are waiting on PR approval to merge ([PR1](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequest/367), [PR2](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequest/366)) - both .NET 7 and .NET 8 apps are being introduced with ASP.NET Core integration. 

Upon final approval, terraform scripts to deploy and test the apps will be finalized.

**Comment by satvu** [comment]
Apps merged and zip files stored - waiting on terraform changes to be reviewed ([PR1](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequest/368), [PR2](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequest/369)). Investigating validation pipeline issues as well.

**Comment by satvu** [comment]
All apps created and added to dashboard except for Net8 on Windows. Net7 on Linux and Windows is up, and so is Net8 on Linux.

**Comment by satvu** [comment]
Waiting on last PR to add net8 tests to dashboard ([here](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequest/415)).

**Comment by satvu** [comment]
Closing as completed.
