### ISSUE TITLE
Source generated metadata provider Enum serialization is not consistent with the default provider

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#1876]
The source generated metadata provider correctly handles Enum constructor arguments, but not named arguments. 

For constructor arguments, the generator correctly checks the symbol type and has the following to handle Enums:

https://github.com/Azure/azure-functions-dotnet-worker/blob/790ebfd74be20abf22618d88c85169c4128d2719/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.Parser.cs#L689-L702

This results in the Enum's symbol name being used (which is consistent with what the default generator uses).

When the Enum is used in a named argument, as in `EventGrid` source in the following snippet:

``` csharp
 public async Task Run([BlobTrigger("samples-workitems/{name}", Connection = "TestStorage", Source = BlobTriggerSource.EventGrid)] Stream stream, string name)
```

That will go down the path of evaluating the named argument value, here:

https://github.com/Azure/azure-functions-dotnet-worker/blob/790ebfd74be20abf22618d88c85169c4128d2719/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.Parser.cs#L629

We need to ensure named arguments are handled the same way as constructor arguments, and make sure we have a test covering the enum scenarios.

**Comment by kshyju** [comment]
Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.
