### ISSUE TITLE
Custom Trigger/Binding Serialization in Isolated worker

### ISSUE THREAD

**Issue by jponcedeleon-kr** [Azure/azure-functions-dotnet-worker#1891]
Not sure if this belongs here or in the Functions Host repo.
This applies to v4 Isolated Worker Functions

Languages: C#

In our organization, we have developed a Custom Trigger/Output Bindings extension for one of the major message brokers that don't currently have support for Azure Functions out of the box, that allows us to use the functions to send/receive to their queues/topics. We have being using this extension successfully for the last couple of years.

One of the major features of the extension is to deserialize/serialize the payload base on custom types provided by the function's method signature. We currently support sending/receiving ```string```, ```byte[]``` and ```POCO``` classes. The extension provides JSON serialization by default, but it's replaceable by implementing an interface and registering the instance with DI. We have cases where serialization is AVRO, for example.

In the hosted model, everything works as expected, because the serializer that's registered with the custom trigger is in the same process, and has access to the runtime type specified by the function signature. In the Isolated model, this is not the case since the custom trigger would run on the host and the function signature would be on another process.
We would like for the custom trigger to support the Isolated model, but we've found no way to go forward with this, the trigger in the host only receives either a byte[] or a JSON serialized representation of the object.

For reference I'm including a pseudo-code snippet of how a function signature would look, the ```Message``` class is defined in the extension, ```CustomPoco``` is defined in the Isolated Functions project:

```
[Function("FunctionName")]
[CustomBindingOutput]
public Message<CustomPoco> MyFunctionName([CustomTrigger(Queue = "my-queue")] CustomPoco payload)
{
  ...
  return new Message<CustomPoco>("destination-topic-or-queue", payload);
}
```

The extension uses whichever serializer is registered in the DI container with interfaces like this: 
```
public interface IInputSerializer
{
  T ReadObject<T>(byte[] input);
}
```
and
```
public interface IOutputSerializer
{
  byte[] WriteObject<T>(T input);	
}
```

That allows us to provide a default serializer but also let the consumer register their own if needed. We also access other properties of the ```Message``` class for headers, etc.

I would like to understand what would be the path forward to support this type of scenario for developing custom extensions, for either triggers and output bindings.

**Comment by jviau** [comment]
@jponcedeleon-kr this looks like it can be accomplished by implementing an `IInputConverter` and adding an attribute for it on your `CustomTriggerAttribute`. You will have full control of binding the input payload to the parameter in your `IInputConverter` implementation.

``` CSharp
[InputConverter(typeof(CustomerInputConverter))]
[ConverterFallbackBehavior(ConverterFallbackBehavior.Default)]
public class CustomTriggerAttribute : TriggerBindingAttribute
{
}
```

**Comment by jviau** [comment]
@jponcedeleon-kr are you using a binding output or is this just the return value of the function you want to have custom serialization for?

If it is the former, the general advice for dotnet isolated is to favor using an _input binding_ which is a complex type that will perform your output binding. IE: for blob, we would have an input binding for the `BlobClient` and then the function can perform output by writing to that client.

If it is the later, you can customer return serialization one of two ways:

1. Customize `JsonSerializerOptions` for your expected return type. 
2. Insert a middleware which reads the existing function invocation result and updates it. Here is an example: https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs#L37

**Comment by jponcedeleon-kr** [comment]
Let me see if I can explain better, I understand it's difficult without examples, bear with me.

We do have a custom extension for the functions **hosted** model that implements input/output trigger/bindings for a message broker, similar to the ServiceBus extension. 
In that model, for sending messages to the broker (output) we can use the IAsyncCollector interface or the function's return value, they both call into the AddAsync implementation method of the binding. In that method is where serialization is done, and the consumer doesn't need to worry about serialization inside the function call, and can be customized depending on what's registered in DI with a specific interface.  
In the hosted model this is possible because the extension is loaded into the same process as the host, and thus it has access to the runtime type provided in the function's method signature.

We are in the process of trying to support the Isolated model, there's no IAsyncCollector anymore, and the pattern is to use the return value to send the message to the broker. We would like to also have the ability to serialize there in the extension, so the consumer wouldn't need to worry about that, just provide (return) an instance of its own custom POCO class, like we do in the hosted model. 

The example in my first post is trying to show that the function returns an instance of a POCO class, that would need to be serialized by the extension before sending the message to the broker's queue. It would be nice to have a mechanism similar to the ```InputConverter```, but for output, with a matching interface to IInputConverter, that gets invoked after the function returns and before the output is sent to the host process. In the example above, the returned instance of ```CustomPoco``` would need to be serialized by the extension.

The functions middleware doesn't seem the right place to hook up and do any type of transformation, but I'm going to look into that to see if that's a plausible solution.

Thanks for all the help, appreciated.

**Comment by jviau** [comment]
@jponcedeleon-kr I understand the scenario, and the routes I suggested are still what I recommend, but I can expand upon it:

1. _All_ function return values are already being serialized by `WorkerOptions.Serializer` before being sent to the host, so you can customize serialization there. By default it uses System.Text.Json, and you can customize it by `IServiceCollection.Configure<JsonSerializationOptions>(o => ...)`
2. `IAsyncCollector` is not present because routing complex output through the host is inefficient. Instead, you would consider where the final destination of this output is to be and provide an `InputBinding` which is a type of your own design that has the `AddAsync` methods on it. Then instead of sending to the host at all you can just send it to its final destination. This is assuming the final destination is something accessible from the worker.

**Comment by extrmi** [comment]
> [@jponcedeleon-kr](https://github.com/jponcedeleon-kr) I understand the scenario, and the routes I suggested are still what I recommend, but I can expand upon it:
> 
> 1. _All_ function return values are already being serialized by `WorkerOptions.Serializer` before being sent to the host, so you can customize serialization there. By default it uses System.Text.Json, and you can customize it by `IServiceCollection.Configure<JsonSerializationOptions>(o => ...)`
> 2. `IAsyncCollector` is not present because routing complex output through the host is inefficient. _**Instead, you would consider where the final destination of this output is to be and provide an `InputBinding` which is a type of your own design that has the `AddAsync` methods on it. Then instead of sending to the host at all you can just send it to its final destination. This is assuming the final destination is something accessible from the worker.**_

Hi @jviau, im also looking for ways to customizing the output, specifically i need to add headers/properties to the EventData being sent to EventHub. This is not possible with [EventHubOutput]

Could you provide an example on how to create a complex InputBinding where data are sent to destination with AddAsync()?
