### ISSUE TITLE
FromBodyAttribute string enum conversion

### ISSUE THREAD

**Issue by Bouke** [Azure/azure-functions-dotnet-worker#1903]
Currently `FromBodyAttribute` deserialises `enum`s from their integer value. Using the string name causes an exception: ` System.Text.Json.JsonException: The JSON value could not be converted to ...`. However in a public API I don't want to expose the internal integer representation, but use the string name instead. How can I achieve this?

**Comment by Bouke** [comment]
The json serializer can be configured like this:

```cs
.ConfigureFunctionsWorkerDefaults(config =>
                                 {
                                     config.Services.Configure<JsonSerializerOptions>(options =>
                                     {
                                         options.Converters.Add(new JsonStringEnumConverter());
                                     });
                                 })
```

**Comment by jviau** [comment]
That is one of the ways to accomplish this. If you control the type being serialized, you can use an attribute on the enum property like so:

``` CSharp
public class MyClass
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public MyEnum Value { get; set; }
}
```

**Comment by jviau** [comment]
Closing as resolved.
