### ISSUE TITLE
Evaluate removing the fallback command line argument reading code(HOST, PORT)

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#1908]
Evaluate removing the fallback command line argument reading code for grpc worker startup options.
#1897 added support for using the new arguments (the one with "functions-" prefix). Since dotnet worker package release is not tied to a host version release, we cannot remove the fallback code now. But perhaps after a couple of host releases, we could consider removing the fallback.

**Comment by jviau** [comment]
I think this would be a behavior breaking change and fall under next major version

**Comment by fabiocav** [comment]
Completed in #2693
