### ISSUE TITLE
Dependency on System.Text.Encodings.Web 5.0.1 which has CVE

### ISSUE THREAD

**Issue by ScottMathieson** [Azure/azure-functions-dotnet-worker#1914]
I am unable to use the SDK in my work as when including it as a package reference it is blocked from building the WorkerExtensions.csproj as it has a dependency on packages with CVEs:

System.Text.Encodings.Web 5.0.1

and a transitive dependency on 

System.Drawing.Common 4.7.0

Both of these packages appear to have high severity CVEs and so our static analysis scanner blocks them from being accessed.

**Comment by ScottMathieson** [comment]
Sorry should have said this is building for NET 6 on Linux

**Comment by Gooozeee** [comment]
If you are able to upgrade System.Text.Encodings.Web to 6.0.0 and System.Drawing.Common to 7.0.0 it is compatible and no longer has this vulnerability.

**Comment by mattchenderson** [comment]
This seems related to https://github.com/Azure/azure-functions-dotnet-worker/issues/2115

**Comment by fabiocav** [comment]
Removing security related report.

All issues have been addressed. For guidance on how to report similar issues in the future, please see https://github.com/Azure/azure-functions-dotnet-worker/security/policy

Thank you.
