### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus >= 5.12.0 Messages no longer receiving from ServiceBusTrigger

### ISSUE THREAD

**Issue by boylec** [Azure/azure-functions-dotnet-worker#1915]
This is for a dotnet-isolated Azure function app for functions with a [ServiceBusTrigger(...)] binding.

We recently tried upgrading to the Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.13.0 package.

Our queue messages stopped consuming - they just sit in the queue.

We rolled back to 5.12.0 and the problem persisted.

Once we rolled back to 5.11.0 our messages started processing again from the queue.

There are no exceptions or anything. We do see the following message splurge 30 or 40 times in rapid succession in the console logs every so often when we're on version 5.12.0+.

REDACTEDQUEUENAME-f057e87b-90c3-4b9c-a6ee-aa913cc81195-Receiver: ReceiveBatchAsync start. MessageCount = 1
REDACTEDQUEUENAME-f057e87b-90c3-4b9c-a6ee-aa913cc81195-Receiver: ReceiveBatchAsync done. Received '0' messages. LockTokens = 

We use the following attribute binding:

```c#
    [Function("RedactedFunctionName")]
    public async Task Run(
      [ServiceBusTrigger(
        "%ServiceBus:QueueName:QueueNameSetting%",
        Connection = "ServiceBusConnection")
      ] string queueMessage
    )
    {
      // consuming code
    }
```

Things we've tried:
* Explicitly set IsBatched = true
  * Tried this with ServiceBusReceivedMessage[] queueMessages parameter
  * Tried this with string[] queueMessages parameter
* Explicitly set IsBatched = false
  * Tried this with ServiceBusReceivedMessage queueMessage parameter
  * Tried this with string queueMessage parameter

No change in behavior regardless of which permutation of the above we tried.

**Comment by SeanFeldman** [comment]
5.13.0 works with the scenario you've outlined. I'd try to see if the entity name is coming through correctly (` "%ServiceBus:QueueName:QueueNameSetting%"`) by replacing it with a simpler expression, w/o semicolon delimiter.

**Comment by boylec** [comment]
Hey Sean thanks for the quick response.

This is a setting which is resolved from our local.settings.json file and comes through fine.

I want to emphasize: When we are on 5.11.0 things work. *The only change* from that point is going to 5.12.0 (or 5.13.0), after which queue messages stop processing

**Comment by SeanFeldman** [comment]
Ah, I didn't read carefully; in your original description, you showed the trigger is getting triggered. So, it's not the entity path/name. Is there a chance you could try with a different, new entity? I want to see if it's an entity-related issue or not.

**Comment by SeanFeldman** [comment]
Also, if you try receiving your message as `ServiceBusMessage queueMessage`, would it change anything?

**Comment by boylec** [comment]
By entity do you mean a different function?

By default our queue message is merely a string, I've tried ServiceBusReceivedMessage just to see if it had an effect.

I'll try ServiceBusMessage right now.

**Comment by boylec** [comment]
Looks like same behavior with the ServiceBusMessage model.

Although, I did notice the following log message which was not posted in the original post.

```bash
[2023-09-19T18:45:27.919Z] Executing 'Functions.RedactedFunctionName' (Reason='(null)', Id=4f3dd786-bcdf-4757-a0b7-22f3594afba1)
[2023-09-19T18:45:27.919Z] Trigger Details: MessageId: 8B5EA16249CD46D20240A30D96577B752B7B5E17A4D922D3B850293A15C81D04, SequenceNumber: 6263, DeliveryCount: 1, EnqueuedTimeUtc: 2023-09-19T18:45:27.9700000+00:00, LockedUntilUtc: 2023-09-19T18:46:27.9700000+00:00, SessionId: (null)
```

So I take this to mean that it starts attempting to execute the function. However, I never see a corresponding "Executed 'Functions.RedactedFunctionName ..." log. (nor does by debugger break inside the function.)

Seems to be hung up in the model binding phase somehow/somewhere.

**Comment by SeanFeldman** [comment]
> By entity do you mean a different function?

Different queue or topic+ subscription

**Comment by boylec** [comment]
> > By entity do you mean a different function?
> 
> Different queue or topic+ subscription

Ah got it.

I did not mention this in the original post either: this is happening across 2 different queues.

**Comment by boylec** [comment]
Cracked the code.

I made the following package update which resolved the issue.

Microsoft.Azure.Functions.Worker 1.8.0 -> 1.19.0

**Comment by boylec** [comment]
Okay. I thought I cracked the code - seemed to fix things in local development but once I deployed to Azure the issue was not resolved.

Going to further troubleshoot.

**Comment by codeputer** [comment]
I'm having the same issue, but I'm on 1.21 of the Microsoft.Azure.Functions.Worker.  I know I have the configuration setup, as I injected IConfiguration, and the name resolves just fine.... so.... where is the code that resolves the % signatures and sets the property correctly in the ServiceBusAttribute
