### ISSUE TITLE
Function triggers doesn't support Azure app configuration integration

### ISSUE THREAD

**Issue by MohammedAbrar** [Azure/azure-functions-dotnet-worker#1926]
When function trigger value is held in Azure app configuration, function doesn't start and throws error.

**Comment by liliankasem** [comment]
Can you share a code example of what you mean?

**Comment by victormarante** [comment]
The function trigger needs to know certain fields prior to application start (and as some values are loaded AFTER the application starts, there are do not exist when the trigger asks for them). See more in the below comment:

https://github.com/Azure/azure-functions-dotnet-worker/issues/1884#issuecomment-1709052953

**Comment by MohammedAbrar** [comment]
> Can you share a code example of what you mean?

[Function(nameof(ServiceBusReceivedMessageBatchFunction))]
public void ServiceBusReceivedMessageBatchFunction(
    [ServiceBusTrigger("%App:QueueName%", Connection = "App__fullyQualifiedNamespace", IsBatched = true)] ServiceBusReceivedMessage[] messages)

App configuration has values for both keys below.
App:fullyQualifiedNamespace, App:QueueName.

App configuration connection is injected during start up.

Note: In proc, i didn't face any issue but when moving to isolated it's not picking values for trigger but within function it is able to get values from Azure app configuration

**Comment by MohammedAbrar** [comment]
@victormarante @liliankasem

**Comment by victormarante** [comment]
> @victormarante @liliankasem 

Read the issue I linked above. It explains what the problem is with App Configuration service explicitly, and how to work around it.

**Comment by MohammedAbrar** [comment]
Thanks @victormarante. It worked.
