### ISSUE TITLE
Errors thrown during function load does not propogate

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#193]
If an error is thrown during function load, for somewhere here -- https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker/Definition/DefaultFunctionDefinitionFactory.cs#L34, it wasn't getting caught or logged by anything.

Maybe that's because we create an unobserved Task here, and inside that nothing (handler or the function broker) catches exceptions for load requests -- https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker/DefaultFunctionsHostClient.cs#L34

**Comment by brettsam** [comment]
Closed in #245
