### ISSUE TITLE
Trigger not working when ConfigureFunctionsWorkerDefaults() is registered in Asp.Net Core Integration app

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#1947]
Trigger not working as expected when `ConfigureFunctionsWorkerDefaults()` is registered in Asp.Net Core Integration app. Also, evaluate if we need analyzer for this scenario.

#### Repro steps and behavior seen

1. Register `ConfigureFunctionsWorkerDefaults()` in Asp.NetCore app. [Sample for reference](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/AspNetIntegration/Program.cs)

```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureFunctionsWebApplication()
    .Build();
```

2. On invoking [SimpletHttpTrigger](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/AspNetIntegration/SimpleHttpTrigger/SimpleHttpTrigger.cs) a few times, noticed either of below behaviors -
    - Trigger worked without any error but did not show the output log line: _Welcome to Azure Functions!_
    - Trigger did not work and failed with Timeout exception.

#### Expected behavior

Trigger should work successfully emitting the expected output log: _Welcome to Azure Functions!_

#### Additional notes from offline discussion

- This could be happening because of the issue with redundant calls to our configure methods since `ConfigureFunctionsWebApplication()` is a superset of `ConfigureFunctionsWorkerDefaults()`.
- We can try to fix the redundant calls issue and based on that decide if we need an Analyzer that errors out if `ConfigureFunctionsWorkerDefaults()` is registered with an AspNet app.

**Comment by ktriple** [comment]
I also encounter issues with this while running .NET 8 isolated. After some testing I found:

Case 1: Endless loop until timeout
```
 var host = new HostBuilder()
     .ConfigureFunctionsWebApplication()
     .ConfigureFunctionsWorkerDefaults()
```

Case 2: 200 OK, but without response body
```
 var host = new HostBuilder()
     .ConfigureFunctionsWebApplication()
     .ConfigureFunctionsWorkerDefaults()
```

Using either of them solo fixes it and therefor I'm not sure if they are supposed to be used together.. but it's a scenario we currently have.

**Comment by XHunter74** [comment]
Also, I have the same behavior.

**Comment by LaurentBonnot** [comment]
Question, is it possible to benefits of the ASP.NET Core integration **and** also to be able to inject custom middleware? For example `builder.UseMiddleware<CustomMiddleware>()`. is there another alternative?

**Comment by XHunter74** [comment]
Yes, it is possible, as it turns out, you just need to:

.ConfigureFunctionsWebApplication(workerApplication =>
{
    workerApplication.UseWhen<CorsHttpHeaderMiddleware>(context =>
    {
        return context.FunctionDefinition.InputBindings.Values
                     .First(a => a.Type.EndsWith("Trigger")).Type == "httpTrigger";
    });
})

**Comment by wouter-b** [comment]
Because `ConfigureFunctionsWebApplication` allready calls `ConfigureFunctionsWorkerDefaults`

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsHostBuilderExtensions.cs#L52

**Comment by Rujith** [comment]
> I also encounter issues with this while running .NET 8 isolated. After some testing I found:
> 
> Case 1: Endless loop until timeout
> 
> ```
>  var host = new HostBuilder()
>      .ConfigureFunctionsWebApplication()
>      .ConfigureFunctionsWorkerDefaults()
> ```
> 
> Case 2: 200 OK, but without response body
> 
> ```
>  var host = new HostBuilder()
>      .ConfigureFunctionsWorkerDefaults()
>      .ConfigureFunctionsWebApplication() 
> ```
> 
> Using either of them solo fixes it and therefor I'm not sure if they are supposed to be used together.. but it's a scenario we currently have.

I think you are only supposed to use either of them, not both. Have a look the docs [here](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#http-trigger)

**Comment by mattchenderson** [comment]
Hi all - yes, confirming that we generally expect only one of these to be used, and I'd default to using `ConfigureFunctionsWebApplication` to get the performance benefits that come with ASP.NET Core integration, unless you are targeting .NET Framework 4.8.

**Comment by christianroll** [comment]
Any news on this issue?? I realized that if I have a http trigger and a servicebus trigger in the same function app it get conflicts by just using `.ConfigureFunctionsWebApplication()`, only the http trigger works for the servicebus trigger I get an expcetion of: `An exception was thrown by the invocation.
[2024-09-03T12:44:27.345Z] Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'`

If I try to use both I get same result of ktriple comment:

> I also encounter issues with this while running .NET 8 isolated. After some testing I found:
> 
> Case 1: Endless loop until timeout
> 
> ```
>  var host = new HostBuilder()
>      .ConfigureFunctionsWebApplication()
>      .ConfigureFunctionsWorkerDefaults()
> ```
> 
> Case 2: 200 OK, but without response body
> 
> ```
>  var host = new HostBuilder()
>      .ConfigureFunctionsWorkerDefaults()
>      .ConfigureFunctionsWebApplication() 
> ```
> 
> Using either of them solo fixes it and therefor I'm not sure if they are supposed to be used together.. but it's a scenario we currently have.

**Comment by mattchenderson** [comment]
This has been addressed with the 2.x versions of Microsoft.Azure.Functions.Worker and Microsoft.Azure.Functions.Worker.Sdk. This will also be addressed for the 1.x versions in our next release.
