### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Sdk 1.15.0: issue with a RootNamespace containing a hyphen

### ISSUE THREAD

**Issue by talinas** [Azure/azure-functions-dotnet-worker#1957]
### Issue
I bumped `Microsoft.Azure.Functions.Worker.Sdk to 1.15.0` and my project build started to fail with the error below (I'm using MSBuild version 17.8.0-preview-23418-03+0125fc9fb for .NET, but same appears to be happening with LTS MSBuild versions as well). 

```
\test-function\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs(6,58): error CS0118: 'test' is a namespace but is used like a type [\test-function\test-function.csproj]
\test-function\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs(6,63): error CS0103: The name 'function' does not exist in the current context [\test-function\test-function.csproj]
```
After initial investigation it appears that the problem occurs due to the fact my `RootNamespace` contains a hyphen (test-function). Initially I didn't have `RootNamespace` element in my csproj set explicitly, however it appears that it defaults to the csproj file name without extension (test-function.csproj).
**Note**: in my case the issue happens only if I have the following Nuget package reference: `Microsoft.Azure.Functions.Worker.Extensions.Storage` (tested with latest 6.2.0)

### Workarounds
1. Downgrading `Microsoft.Azure.Functions.Worker.Sdk to 1.14.x`
2. Updating RootNamespace to not have a hyphen (i.e. explicitly adding `<RootNamespace>test_function</RootNamespace>`)
3. Removing `Microsoft.Azure.Functions.Worker.Extensions.Storage`

None of the workarounds are ideal, therefore I'd like to ask for your help investigating this further. 

To reproduce the issue, here is an empty Azure Functions project attached:
[test-function.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/12869353/test-function.zip)

**Comment by kshyju** [comment]
@talinas

As per the [specs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#143-namespace-declarations), namespaces cannot have `-` in it. 

You are seeing the issue because your `RootNamespace` has `-` in it and the auto generated types are defined in a namespace which is same as the `RootNamespace` value by default. You can override this behavior by explicitly specifying another valid namespace name in the `FunctionsGeneratedCodeNamespace` property. See #1930 for details.

Just add `<FunctionsGeneratedCodeNamespace >TestFunction</FunctionsGeneratedCodeNamespace>` to your csproj file and that should solve your problem.

Let us know if you still run into issues.

**Comment by talinas** [comment]
@kshyju - Thanks for the reply. Using `FunctionsGeneratedCodeNamespace `does fix the issue as well. However, while closing the issue, I'll still leave a note that it will impact all csproj owners having the hyphen in their csproj name and not overriding auto populated types with a valid namespace as described above. So, IMHO this should be handled by the package owners instead, especially considering it worked well with the previous versions of the package.

**Comment by kshyju** [comment]
@talinas Thank you for the feedback. We will consider making that improvement you suggested in a future version of the package.

**Comment by petarvucetin** [comment]
Same Issue with namespace containing period e.g. SomeProject.Manager 

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/179653/75a957f6-89d2-4835-ad74-e44dadf89e1d)
