### ISSUE TITLE
AppInsights with Entra Authentication does not work.

### ISSUE THREAD

**Issue by stas-sultanov** [Azure/azure-functions-dotnet-worker#1959]
Greetings,
I build an application with .NET v7.0, that hosts on Azure Function with dynamic App Service Plan.
I want to utilize [Microsoft Entra Authentication for AppInsights](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net)

Project definition as follows: (not relevant elements are omitted)
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.0" />
	</ItemGroup>
</Project>
```

Initialization code:
```C#
_ = services.Configure<TelemetryConfiguration>
(
	config => config.SetAzureTokenCredential(credential)
);

var connectionString = configuration.GetValue<String>(Key_Azure_ApplicationInsights_ConnectionString);

var options = new ApplicationInsightsServiceOptions()
{
	ConnectionString = connectionString
};

_ = services.AddApplicationInsightsTelemetryWorkerService(options);

_ = services.ConfigureFunctionsApplicationInsights();
```

"FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"

test code
```C#
Logger.LogCritical("test from App: critical");
```

In the output window I see the following:
Application Insights Telemetry: 
```json
{
	"name": "AppTraces",
	"time": "2023-10-12T11:43:13.1028690Z",
	"iKey": "00000000-0000-0000-0000-000000000000",
	"tags": {
		"ai.application.ver": "1.0.0.0",
		"ai.cloud.roleInstance": "STAS-L",
		"ai.operation.id": "de4082ce19bdb20ddf3f6182c6878360",
		"ai.operation.parentId": "dcfa7e15396612e9",
		"ai.internal.sdkVersion": "azurefunctions-netiso: 1.0.0+27a47c658eb1cc5639625909311c7673334",
		"ai.internal.nodeName": "localhost:7071"
	},
	"data": {
		"baseType": "MessageData",
		"baseData": {
			"ver": 2,
			"message": "it's a critical test",
			"severityLevel": "Critical",
			"properties": {
				"SpanId": "dcfa7e15396612e9",
				"TraceId": "de4082ce19bdb20ddf3f6182c6878360",
				"AzureFunctions_FunctionName": "Functions_Message",
				"CategoryName": "Teams.Bot.Functions",
				"InvocationId": "5dc8641a-d2ee-4702-ac2b-71616c93767c",
				"OriginalFormat": "it's a critical test",
				"DeveloperMode": "true",
				"AzureFunctions_InvocationId": "5dc8641a-d2ee-4702-ac2b-71616c93767c",
				"ParentId": "21836fb57055798e"
			}
		}
	}
}
```
There are no authentication or authorizations errors no exceptions at all.
However, I see nothing in AppInsights instance.

If only I change connection string to include right InstrumentationKey and remove ```C# config => config.SetAzureTokenCredential(credential)```

everything starts to work, and I see telemetry in AppInsights instance.

**Comment by brettsam** [comment]
Are you sure you're getting the credential correctly?

Functions shouldn't be impacting this. The call to `ConfigureFunctionsApplicationInsights()` adds a couple of services for processing telemetry and that's about it. All of the auth layer is pure Application Insights.

What happens if you remove the `_ = services.ConfigureFunctionsApplicationInsights();` and just write a log message as a test? Does that make it?

If you're seeing the same issue after that, we should transfer this to the App Insights repo (I can do that) and see if they can help.

**Comment by stas-sultanov** [comment]
Greetings.

I am 100% sure that I am getting credentials right. 
I have tried with asp.net application and result is the same.

There are no errors in output and no breakpoints being hit.

In output window I see that data has been collected by app Insights and sent, however there is nothing in App Insights. 


@brettsam 
Could you please transfer the issue to App Insights repo?
