### ISSUE TITLE
SendGridOutput not pulling ApiKey from AppConfiguration with tie to Key Vault

### ISSUE THREAD

**Issue by civbaron** [Azure/azure-functions-dotnet-worker#1964]
I have setup an app configuration that is used via multiple function apps. It has a value that is tied to a key vault secret. I have confirmed that calling the configuration in the same function call does pull back the valid send grid api key, but when the SendGridOutput tries it doesn't get a value back.

Here is my function code 
`public class TestFunctionWorking
{
    private readonly ILogger<TestFunctionWorking> log;
    private readonly IConfiguration config;

    public TestFunctionWorking(ILogger<TestFunctionWorking> logger, IConfiguration configuration) 
    {
        log = logger;
        config = configuration;
    }

    [Function("TestFunctionWorking")]
    [SendGridOutput(ApiKey = "SendGrid:ApiKey")]
    public async Task<string> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequestData req)
    {
        var messages = new List<SendGridMessage>();

        var vms = new List<string>()
        {
            "TEST1",
            "TEST2"
        };

        foreach (var vm in vms)
        {
            var message = new SendGridMessage();
            message.AddTos(new List<EmailAddress>()
            {
                new EmailAddress("Jonathan_Simon@cargill.com")
            });

            message.SetFrom(new EmailAddress("noreply@cargilldigitalsolutions.com", "Do Not Reply"));
            message.SetSubject($"VM {vm} has not been started since");
            message.AddContents(new List<Content>()
            {
                new Content("text/html", $@"
                                            <body>
                                                <p>{vm} was last started by</p>
                                                <p>If you no longer need this vm please have who created the vm delete it</p>
                                                <p>Thank you, <br>The CloudOps Team</p>
                                            </body>
                                        ")
            });

            log.LogInformation($"Adding email to collection");
            messages.Add(message);
        }
        var messageJson = Newtonsoft.Json.JsonConvert.SerializeObject(messages);

        var apiKey = config.GetValue<string>("SendGrid:ApiKey");
        return messageJson;
    }
}`

This is my program.cs file
`var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureAppConfiguration(configuration =>
    {
        var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions()
        {
            //Cantina
            TenantId = "{tenantid}",
            //Unity
            //TenantId = "efde23eb-b188-40dd-b6af-50147ebc19ad",
            ExcludeInteractiveBrowserCredential = false,
            ExcludeAzureCliCredential = true,
            ExcludeAzurePowerShellCredential = true,
            ExcludeEnvironmentCredential = true,
            ExcludeManagedIdentityCredential = true,
            ExcludeSharedTokenCacheCredential = true,
            ExcludeVisualStudioCodeCredential = true,
            ExcludeVisualStudioCredential = true
        });
        var appConfigName = Environment.GetEnvironmentVariable("APPCONFIGURATIONNAME");
        configuration.AddAzureAppConfiguration(options =>
                options.Connect(new Uri($"https://{appConfigName}.azconfig.io"), credentials)
                    .ConfigureKeyVault(options =>
                        options.SetCredential(credentials))
                    .ConfigureRefresh(options =>
                        options.Register("Sentinel", true)
                            .SetCacheExpiration(new TimeSpan(0, 0, 30))));
    })
    .Build();

host.Run();`

This is an isolated process function app.

**Comment by kshyju** [comment]
Are you seeing this issue when running in azure or locally? The `SendGrid:ApiKey` app settings should be available to the functions runtime. Do you have it set as an app setting in the azure portal or local.settings.json (for local development)?

**Comment by civbaron** [comment]
Sorry didn't know someone had responded to this till now.
It is a value residing in an azure app configuration, which the function has access. 

If I run it locally with the value in the local.settings.json it will work, but if I leave it to pull the value from the azure app configuration it fails.  I have created a work around by declaring a sendgrid client and passing it through DI but would prefer to go the route of the attribute.
