### ISSUE TITLE
ASP.NET Core customizing serialisation

### ISSUE THREAD

**Issue by Zaragor** [Azure/azure-functions-dotnet-worker#1979]
Problem: When returning an object from an isolated function app running under ASP.NET Core bindings, I'd like to be able to customize the serialization of the object via dependency injection. 

For function apps running under the default bindings, this can be done by changing either JsonSerializerOptions or WorkerOptions as per [this example](https://github.com/Azure/azure-functions-dotnet-worker/blob/ec518944144a4bccdc5ea1e0695d9d6b582bc084/samples/Configuration/Program.cs). For ASP.NET core apps, this can be done with the [AddJsonOptions](https://github.com/dotnet/aspnetcore/blob/v3.0.0/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreMvcBuilderExtensions.cs#L51) extension method. I cannot figure out any way to change the options for serialization for the ASP.NET Core function app.

Reproduction: Here is a function trying to return a property with fields. I'd like to know how to get the TestFunctionApp to serialize the fields in the response. [https://github.com/Zaragor/AspNetCoreSerialization](https://github.com/Zaragor/AspNetCoreSerialization)

**Comment by Zaragor** [comment]
I'm also seeing a possibly related issue with WCF SOAP connectors (don't ask). After updating from dotnet to dotnet-isolated and using the ASP.NET Core bindings, the xml serialization for SOAP calls is now wrapping strings in a <string> tag in the soap header which breaks compatibility. Strangely, the body serialization hasn't changed, just the header.

I've pasted the two different payloads sent by the same connected service, before and after. Any idea how I can fix this?

Before:
```
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
	<s:Header>
		<a:Action s:mustUnderstand="1">
			http://www.ultipro.com/services/employeeperson/IEmployeePerson/GetPersonByEmployeeIdentifier</a:Action>
		<a:MessageID>{MESSAGEID}</a:MessageID>
		<a:ReplyTo>
			<a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
		</a:ReplyTo>
		<a:To s:mustUnderstand="1">https://service5.ultipro.com/services/EmployeePerson</a:To>
		<ClientAccessKey a:IsReferenceParameter="true"
			xmlns="http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey">{{ACCESSKEY}}</ClientAccessKey>
		<UltiProToken a:IsReferenceParameter="true"
			xmlns="http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken">
			{{ACCESSTOKEN}}</UltiProToken>
	</s:Header>
	<s:Body>
		{{BODY}}
	</s:Body>
</s:Envelope>
```

After:
```
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
    <s:Header>
        <a:Action s:mustUnderstand="1">
            http://www.ultipro.com/services/employeeperson/IEmployeePerson/GetPersonByEmployeeIdentifier</a:Action>
        <a:MessageID>{{MESSAGEID}}</a:MessageID>
        <a:ReplyTo>
            <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
        </a:ReplyTo>
        <a:To s:mustUnderstand="1">https://service5.ultipro.com/services/EmployeePerson</a:To>
        <ClientAccessKey a:IsReferenceParameter="true"
            xmlns="http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey"
            xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <string i:type="b:string" xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays"
                xmlns:b="http://www.w3.org/2001/XMLSchema">{{CLIENTKEY}}</string>
        </ClientAccessKey>
        <UltiProToken a:IsReferenceParameter="true"
            xmlns="http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken"
            xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <string i:type="b:string" xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays"
                xmlns:b="http://www.w3.org/2001/XMLSchema">{{ACCESSTOKEN}}</string>
        </UltiProToken>
    </s:Header>
    <s:Body>
        {{BODY}}
</s:Envelope>
```

**Comment by aishwaryabh** [comment]
Have you tried specifiying JsonSerializerOptions like stated in this issue: https://stackoverflow.com/questions/74427826/specifying-jsonserializeroptions-in-net-6-isolated-azure-function

**Comment by Zaragor** [comment]
> Have you tried specifiying JsonSerializerOptions like stated in this issue: https://stackoverflow.com/questions/74427826/specifying-jsonserializeroptions-in-net-6-isolated-azure-function

Unfortunately that doesn't work for function apps using `ConfigureFunctionsWebApplication`, only for ConfigureFunctionWorkerDefaults. The linked repo has a very simple reproduction that tries specifying JsonSerializerOptions when using `ConfigureFunctionsWebApplication`, and it doesn't work.

**Comment by Dresel** [comment]
Have you tried

`.ConfigureFunctionsWebApplication(o => o.Services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions***))`

**Comment by Zaragor** [comment]
> Have you tried
> 
> `.ConfigureFunctionsWebApplication(o => o.Services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions***))`

Thanks, that works! At least on my example repo. 

My only concern is the `ConfigureFunctionsWebApplication` calls [UseAspNetCoreIntegration](https://github.com/Azure/azure-functions-dotnet-worker/blob/e68f66084a6c32aa5622cb19afcf791724494d2f/extensions/Worker.Extensions.Http.AspNetCore/src/WorkerBuilderExtensions.cs#L23) which adds some stuff around setting HttpContext in the FunctionContext. I'll test myself, but do you know if this is this something that I'll also need to add in to get it working fully featured?

**Comment by bzuidgeest** [comment]
> Have you tried
> 
> `.ConfigureFunctionsWebApplication(o => o.Services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions***))`

I changed it to functionsWorkerApplicationBuilder.Services.AddMvcCore().AddJsonOptions(options => options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

This avoids adding some unneeded "junk" that AddControllers adds, seems to work, but I'm not sure how either function might impact my functions. Maybe there is an even cleaner way?

**Comment by aishwaryabh** [comment]
Another thing you could try is:

```
.ConfigureServices(services =>
{
   services.Configure<JsonSerializerOptions>(options =>
   {
  ...
   }
}
```

**Comment by bzuidgeest** [comment]
You can just set the options like below. But do be carefull, there are two different JsonOptions classes. There is Microsoft.AspNetCore.Http.Json.JsonOptions and there is Microsoft.AspNetCore.Mvc.JsonOptions.

JsonResult which works with IActionResultExecutor uses Microsoft.AspNetCore.Mvc.JsonOptions.

So this will work:

        services.Configure<Microsoft.AspNetCore.Mvc.JsonOptions>(options =>
        {
            options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
            options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
        });

But this won't:

        services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(options =>
        {
            options.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
            options.SerializerOptions.PropertyNameCaseInsensitive = true;
       });

This cost me hours. Wish microsoft didn't reuse classnames so blatently

**Comment by aishwaryabh** [comment]
Closing this issue since workaround has been provided

**Comment by Duranom** [comment]
The solution of @bzuidgeest needs to be documented as it is not uncommon to see the question how to get it done for things like adding `JsonStringEnumConverter`.

Also both need to be added depending on the feature you are using in isolated azure function, as it can differ depending on how you defined your function.
Also you will still need to define on the safe side.
```C#
builder.Services.Configure<JsonSerializerOptions>(jsonSerializerOptions =>
        {
        options.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
        options.SerializerOptions.PropertyNameCaseInsensitive = true;
        });
```
