### ISSUE TITLE
Default HTTP template has invalid "Content" response header

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-dotnet-worker#198]
### Issue
This is a fit-and-finish issue. The C# code in the HTTP template constructs a "Content" response header that looks like it's supposed to be a Content-Type response header:

```csharp
var response = req.CreateResponse(HttpStatusCode.OK);
response.Headers.Add("Content", "Content - Type: text / html; charset = utf - 8");
```

This code is not producing a valid HTTP response header. I assume this is a bug.

### Expected
I expect the code is actually supposed to look like this (correct header name, no extra whitespace, etc.):

```csharp
var response = req.CreateResponse(HttpStatusCode.OK);
response.Headers.Add("Content-Type", "text/html; charset=utf-8");
```

Event better if it can be "text/plain" instead of "text/html" since we're returning a plaintext string and not HTML.

```csharp
var response = req.CreateResponse(HttpStatusCode.OK);
response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
```

### Repro steps:
1. Use `func new` to create an HTTP trigger
2. Look at the generated code

**Comment by fabiocav** [comment]
Thanks! Opened: https://github.com/Azure/azure-functions-templates/pull/1027

**Comment by mhoeger** [comment]
Fixed with fabio's pr above
