### ISSUE TITLE
HTTP triggers do not prevent you from using HttpRequest/Response[Message]

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-dotnet-worker#199]
### Issue

This is an **error-handling issue** that I expect to be common for anyone trying to migrate existing HTTP triggers from .NET to .NET-isolated. I'm aware that the correct way to write HTTP triggered functions is to use `HttpRequestData` and `HttpResponseData` (and I'll avoid getting into that debate here).

If I write an HTTP trigger function that takes `HttpRequestMessage` and returns `HttpResponseMessage`, I get no warning in the dev experience that this in an invalid scenario. Instead, the function still tries to execute. The `HttpRequestMessage` parameter is uninitialized (null) and HttpResponseMessage results are serialized at raw JSON objects. I assume `HttpRequest` and `HttpResponse` have similar problems, but I didn't try those types.

### Expected
I would expect that I get either a compiler warning/error or get a runtime exception indicating that I'm using an invalid binding type. This would help me get back on the right track immediately. Otherwise I have to debug the problem and then look at documentation (or StackOverflow) to realize that I've made a mistake.

**Comment by kshyju** [comment]
https://github.com/Azure/azure-functions-dotnet-worker/issues/257 will track this work.

**Comment by surgupta-msft** [comment]
Closing. Tracking issue #257
