### ISSUE TITLE
`FunctionsEnableExecutorSourceGen` introduces build errors if project, namespace, and function class share the same name

### ISSUE THREAD

**Issue by DL444** [Azure/azure-functions-dotnet-worker#1990]
## Summary
If the name of a function class is the same with the namespace **AND** the project it resides in, enabling `FunctionsEnableExecutorSourceGen` will generate the following build error in generated source code:
> The type name 'Name' does not exist in the type 'Name'

## Minimal reproducible sample
In a project named `FunctionCodeGen`:
```cs
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;

namespace FunctionCodeGen
{
    public class FunctionCodeGen
    {
        [Function("FunctionCodeGen")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req) => req.CreateResponse(HttpStatusCode.OK);
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FunctionsEnableExecutorSourceGen>True</FunctionsEnableExecutorSourceGen>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

## Analysis
The generated code causing error is:
```cs
namespace FunctionCodeGen
{
    // ...
    internal class DirectFunctionExecutor : IFunctionExecutor
    {
        // ...
        public async ValueTask ExecuteAsync(FunctionContext context)
        {
            // ...
            var i = _functionActivator.CreateInstance(instanceType, context) as FunctionCodeGen.FunctionCodeGen; // This line causes error
            // ...
        }
        // ...
    }
    // ...
}
```

The namespace for the generated class is determined by the project name. When project name and the namespace for the function class are the same, the generated class and the function class reside in the same namespace. If additionally the function class has the same name with the containing namespace, then the compiler interprets the generated `as FunctionCodeGen.FunctionCodeGen` as referencing a nested type called `FunctionCodeGen` within type `FunctionCodeGen`, which does not exist.

Renaming the project will change the namespace for the generated class, so the compiler will be able to tell that `as FunctionCodeGen.FunctionCodeGen` references a class called `FunctionCodeGen` in another namespace `FunctionCodeGen`, and the code compiles. Renaming either the namespace or the function class will change `as FunctionCodeGen.FunctionCodeGen` to something like `as FunctionCodeGenNamespace.FunctionCodeGenClass`, and the compiler will be able to tell the first token is a namespace and the second one is a class, avoiding the problem.

#### Mitigation

To mitigate the issue, add the below entry to your `.csproj` file.

```xml
<PropertyGroup>
  <FunctionsGeneratedCodeNamespace >YourProjectNamespace</FunctionsGeneratedCodeNamespace>
</PropertyGroup>
```

**Comment by DL444** [comment]
I believe applying a similar fix with #1816 could probably solve the issue.

**Comment by kshyju** [comment]
@DL444 Thanks for reporting. Would you be open to submit a PR with fix?

**Comment by kshyju** [comment]
You can use our tests for this generator to validate the change (The PR should also include a new test covering the change). See the existing tests here. https://github.com/Azure/azure-functions-dotnet-worker/blob/a70ead9e497c990d6c29b920f7ed1c3044f6c2f7/test/Sdk.Generator.Tests/FunctionExecutor/FunctionExecutorGeneratorTests.cs#L175 

Another way to e2e validate is to publish the `Microsoft.Azure.Functions.Worker.Sdk` nuget package (and it's [dependencies](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk#dependencies-body-tab)) locally with your change and consume that in your repro function app. If using visual studio IDEA, you can right click on the project and select "Pack" to get the package or run `dotnet pack` on the projects using dotnet cli.

**Comment by DL444** [comment]
@kshyju Thanks a lot. Actually, I just figured it out myself, and using fully qualified name does indeed work. I'll try to run the full E2E test suite to ensure there's no regression at run time.
