### ISSUE TITLE
Read CloudEvent extension attributes in middleware?

### ISSUE THREAD

**Issue by stevendarby** [Azure/azure-functions-dotnet-worker#1994]
I would like to write middleware for `[EventGridTrigger]` functions that receive a `CloudEvent`. In the middleware I'd like to read an extension attribute and do something with that. However the only way I seem to be able to get anything about the incoming `CloudEvent` is via `context.BindingContext.BindingData`, and this only contains the `data` property of the CloudEvent and no other properties or extension attributes.

Is there a way to do this that I'm missing? Example of something I was hoping to be able to do:

```C#
 var host = new HostBuilder()
     .ConfigureFunctionsWorkerDefaults(builder =>
     {
         builder.UseMiddleware((context, next) =>
         {
             if (context.FunctionDefinition.InputBindings["cloudEvent"].Type == "eventGridTrigger")
             {
                 Console.WriteLine($"myExtensionAttribute: {context.BindingContext.BindingData["myExtensionAttribute"]}");
             }

             return next();
         });
     })
     .Build();

 await host.RunAsync();
```

**Comment by stevendarby** [comment]
@kshyju that is perfect, thank you

**Comment by kshyju** [comment]
Closing as answered. Please feel free to open an issue if you are running into problems using the dotnet-isolated model.

**Comment by stevendarby** [comment]
Just wanted to add/suggest - why is this an extension method instead of first class. I am now trying to mock the FunctionContext in a unit test and the fact it's an extension means a lot more needs to mocked. Any guidance on this appreciated. Thanks.
