### ISSUE TITLE
application insights configuration could not send request metric

### ISSUE THREAD

**Issue by CCC598** [Azure/azure-functions-dotnet-worker#1998]
If I use Configuration to configure Application Insights, Application Insights only send dependencies but don't send request.
 
Program.cs

````csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureAppConfiguration((context, config) =>
    {
        config.AddApplicationInsightsSettings("<application-insights-connection-string>");
    })
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();

        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();
````

PackageReference
````xml
  <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.0" />
````

My Timer Function
````csharp
  public class TimerFunction
  {
      private readonly ILogger _logger;

      public TimerFunction(ILoggerFactory loggerFactory)
      {
          _logger = loggerFactory.CreateLogger<TimerFunction>();
      }

      [Function("TimerFunction")]
      public void Run([TimerTrigger("*/20 * * * * *")] TimerInfo timerInfo)
      {
          _logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
      }
  }
````

Application Insights Live Metrics
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/38395086/c08ae1e0-5dac-406e-a572-810b9ee87434)

Application Insights 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/38395086/f160b758-41b6-4f0c-87f9-d1a7774eee10)

BUT If I use local.settings.json (environment variables)  `APPLICATIONINSIGHTS_CONNECTION_STRING` configure , application insights can send request

````json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "<application-insights-connection-string>"
  }
}
````

Application Insights Live Metrics
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/38395086/f54604e5-d8a0-4087-b3f2-3216885e0439)

Application Insights 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/38395086/1ac3edb9-d757-4f7a-9342-3cebf3257427)

I have some reasons could not use environment variables and want to know why this is happening. I have previous used host mode function and can use configuration.

**Comment by brettsam** [comment]
The Request comes from the Functions host, not the worker, and the host requires the App Setting. The worker will send (almost) all other Telemetry, but the Request starts and ends with the host, so that's where it's written.

This may change in the future as we move more of the logging responsibilities to the workers, but for now, the App Setting is required in order for the full flow to get logged.
