### ISSUE TITLE
Incorrect function invocation if function names differing only by casing exist and `FunctionsEnableExecutorSourceGen` is enabled

### ISSUE THREAD

**Issue by DL444** [Azure/azure-functions-dotnet-worker#2003]
## Summary

If two function methods with names that only differ by casing exist in one class and `FunctionsEnableExecutorSourceGen` is enabled, source-generated function executor invokes both functions at runtime and produces results for the last when either one is triggered. 

## Minimal reproducible sample

*FunctionCodeGen.cs*

```cs
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace Functions
{
    public class FunctionCodeGen
    {
        [Function("FunctionA")]
        public HttpResponseData Hello([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
        {
            req.FunctionContext.GetLogger("Test").LogInformation("Hello executed.");
            HttpResponseData response = req.CreateResponse(HttpStatusCode.OK);
            response.WriteString("Hello!");
            return response;
        }

        [Function("FunctionB")]
        public HttpResponseData HELLO([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
        {
            req.FunctionContext.GetLogger("Test").LogInformation("HELLO executed.");
            HttpResponseData response = req.CreateResponse(HttpStatusCode.OK);
            response.WriteString("HELLO!");
            return response;
        }
    }
}
```

*FunctionCodeGen.csproj*

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FunctionsEnableExecutorSourceGen>True</FunctionsEnableExecutorSourceGen>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk.Generators" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

Triggering either `FunctionA` or `FunctionB` will produce two log entries, one for `Hello()` and another for `HELLO()`. HTTP response is for the one defined last, other results are overwritten.

Having method names that only differ in casing surely isn't recommended or common in practice, but it is valid C#. I believe it's important to get valid scenarios correct. Furthermore, the behavior is correct if `FunctionsEnableExecutorSourceGen` is not used.

## Analysis

The generated executor code uses case-insensitive comparions of method signatures to decide which function to invoke:

```cs
if (string.Equals(context.FunctionDefinition.EntryPoint, "Functions.FunctionCodeGen.Hello", StringComparison.OrdinalIgnoreCase))
{
    var instanceType = types["Functions.FunctionCodeGen"];
    var i = _functionActivator.CreateInstance(instanceType, context) as Functions.FunctionCodeGen;
    context.GetInvocationResult().Value = i.Hello((global::Microsoft.Azure.Functions.Worker.Http.HttpRequestData)inputArguments[0]);
}
if (string.Equals(context.FunctionDefinition.EntryPoint, "Functions.FunctionCodeGen.HELLO", StringComparison.OrdinalIgnoreCase))
{
    var instanceType = types["Functions.FunctionCodeGen"];
    var i = _functionActivator.CreateInstance(instanceType, context) as Functions.FunctionCodeGen;
    context.GetInvocationResult().Value = i.HELLO((global::Microsoft.Azure.Functions.Worker.Http.HttpRequestData)inputArguments[0]);
}
```

The use of case-insensitive equality check and if-if branching instead of if-elseif results in two cases both true and executed. `context.GetInvocationResult().Value` is being overwritten to be the result from the last defined method. Changing the code gen to use case-sensitive ordinal comparison will fix the problem.

Additionally, code generation can be tweaked to use if-elseif branching since I don't believe multiple matches would be possible anymore (function overloading is not allowed). This can lead to a marginal performance improvement since remaining branches wouldn't have to be evaluated anymore.

There can be specific reasons for this design that I'm not aware of. If this is the case, please let me know. Otherwise, I'm willing to contribute a fix.

**Comment by kshyju** [comment]
Good finding @DL444 Yea, It's indeed a bug. The fix should include both changes, making the check case sensitive and using `else if` or `return` inside the if blocks. I think `if... else if` might cause better branch prediction (yet to be measured). So let's take that route.

Feel free to send a PR with the fix If you are interested. If not, the team will get to it eventually.
