### ISSUE TITLE
[FEATURE REQ] Please add method RenewMessageLockAsync to ServiceBusMessageActions (isolated worker process model)

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-functions-dotnet-worker#2018]
**Library name**
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus

**Please describe the feature.**
Greetings,

Please add the 'RenewMessageLockAsync' to the 'ServiceBusMessageActions' class of the 'Microsoft.Azure.Functions.Worker.Extensions.ServiceBus' library, as was requested in [feature request](https://github.com/Azure/azure-sdk-for-net/issues/26402), in the Azure Function IsolatedProcess libraries to the ServiceBusMessageActions class.

This prevents us from migrating from '[In-process model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide)' to the  'isolated worker process model'.

Thanks in advance!

Note: **Similar to [feature request](https://github.com/Azure/azure-sdk-for-net/issues/26402) which is in a similar library, but is part of the InProcess Azure Function libraries**

The [In-process model class](https://github.com/Azure/azure-sdk-for-net/blob/77f6b1550f083ed2a373a16931708ac3e31ddae7/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/ServiceBusMessageActions.cs#L16) vs the [isolated worker process model class](https://github.com/Azure/azure-functions-dotnet-worker/blob/bef360980a5f26c2ec6b2bd2977c3ca4a715d066/extensions/Worker.Extensions.ServiceBus/src/ServiceBusMessageActions.cs#L20).

**Comment by liliankasem** [comment]
@JoshLove-msft @mattchenderson for awareness

**Comment by StannieV** [comment]
@liliankasem @JoshLove-msft @mattchenderson Any update on this topic?

**Comment by ciacco85** [comment]
Any update on this? Thanks

**Comment by kbehboodi** [comment]
Any update on this guys?

**Comment by mvatict** [comment]
This is a problem in our solution as well. Is there any update to report?

**Comment by dziadkiewicz** [comment]
Experiencing the same issue and would greatly appreciate this feature being implemented.

**Comment by sdworx-kennydv** [comment]
Same issue here, Its blocking us to migrate to .net 8 as the isolated model seems to be the way forward.

**Comment by fabiocav** [comment]
Wanted to provide an update on this. This has been reviewed and it's a valid request, but it is not yet assigned and we don't have an ETA on implementation at the moment.

We'll keep this updated when we have more to share.

**Comment by fabiocav** [comment]
Also, if folks flagging this as a requirement could please share more details about your scenario (how/why you're using `RenewMessageLockAsync` in your function code), what would help us track them and prioritize the work. 

In most cases, the host will ensure this is done and the lock is not lost, so we're tracking the scenarios where this is still required.

**Comment by sdworx-kennydv** [comment]
When we did some performance testing we saw it did happen locks were expiring so we added a precautionary check and renewed the lock if it was too close to expiration. As a workaround we lowered our prefetech count and will use the abandon-method to release the messages.

**Comment by StannieV** [comment]
> Also, if folks flagging this as a requirement could please share more details about your scenario (how/why you're using `RenewMessageLockAsync` in your function code), what would help us track them and prioritize the work.

@fabiocav Do you know if this change was prioritized already? We would like to know if we need to start considering implementing a work-a-round. This is an impediment for us to migrate to .Net 8 which is due to '12 November 2024' and we have over 200 Azure functions to migrate to the isolated model and then to .Net 8.

**Comment by arkiaconsulting** [comment]
One use case is: In case the message handling does not end up as expected, I want to retry the message later (with some jitter in order for the other messages not being retried at the exact same time.
I may also want to have different message renewal delay, depending of the business issue that occurred.

**Comment by jcageman** [comment]
> Also, if folks flagging this as a requirement could please share more details about your scenario (how/why you're using `RenewMessageLockAsync` in your function code), what would help us track them and prioritize the work.
> 
> In most cases, the host will ensure this is done and the lock is not lost, so we're tracking the scenarios where this is still required.

we have long running functions that should remain running, hence we need to be able to extend the lock for the duration of the request.

**Comment by StannieV** [comment]
So, apparently the 'RenewMessageLockAsync' is added to the code in version [5.16.1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.16.1) of the package 'Microsoft.Azure.WebJobs.Extensions.ServiceBus'. (See: [github](https://github.com/Azure/azure-functions-dotnet-worker/commit/be0b8b3704aee18915c5162ed8a5fb64423706ba#diff-80f9574dfb3f9c0427556d6e1356b21a9e38a99e1b53db9c18807122562fee54))

**Comment by bforget163** [comment]
> So, apparently the 'RenewMessageLockAsync' is added to the code in version [5.16.1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.16.1) of the package 'Microsoft.Azure.WebJobs.Extensions.ServiceBus'. (See: [github](https://github.com/Azure/azure-functions-dotnet-worker/commit/be0b8b3704aee18915c5162ed8a5fb64423706ba#diff-80f9574dfb3f9c0427556d6e1356b21a9e38a99e1b53db9c18807122562fee54))

Do you know when will the changes be include to package 'Microsoft.Azure.Functions.Worker.Extensions.ServiceBus'?
@fabiocav
