### ISSUE TITLE
HttpRequestData does not support "chunked" POST request payloads from HttpClient - PostAsJsonAsync

### ISSUE THREAD

**Issue by dylanhouston7** [Azure/azure-functions-dotnet-worker#2019]
Hi,

Thanks for your time in looking into this. I work for a Fortune 500 company that is a client of Microsoft. I noticed this when debugging issues yesterday and thought it would be helpful to communicate this so that it can hopefully get fixed. 

Dylan 

# Current behavior

When POSTing to an HTTP Triggered .NET 7 Isolated Function from an `HttpClient` in another .NET 7 Isolated Function, I am noticing inconsistent behavior between POSTing with `PostAsync` vs `PostAsJsonAsync`.

- POSTing with `PostAsync` works. The `HttpRequestData` object in the receiving function is able to retrieve the payload. 

- POSTing with `PostAsJsonAsync` DOES NOT work. The `HttpRequestData` object in the receiving function is NOT able to retrieve the payload. 

# Expected behavior

I'd expect `HttpRequestData` to support request body payloads sent via both the `PostAsync` and `PostAsJsonAsync` methods.

# Other notes

Based on my research yesterday, I *think* this is due to `PostAsJsonAsync` sending the request body as "chunked", and `PostAsync` NOT sending the request body as "chunked".

https://stackoverflow.com/questions/67533477/c-sharp-httpclient-postasjsonasync-adds-a-strange-character-to-the-body
https://stackoverflow.com/questions/70344134/http-post-to-net-isolated-azure-function-body-empty-most-of-the-time

# Repro steps

1. Implement a simple .NET 7 Isolated Functions HTTP endpoint that receives a payload, using `HttpRequestData` to represent the request.

Instantiate a HTTP Client from that method. Send the payload received to another .NET 7 Isolated Functions HTTP endpoint using both methods detailed above.

2. Implement an HTTP Triggered .NET 7 Isolated Function endpoint, using `HttpRequestData` to represent the request POSTed in step 1.Read the content as a string and write/log the payload.

3. Observe the inconsistency in behavior. The payload gets logged as expected for the `PostAsync` case, and an empty string is logged for the `PostAsJsonAsync` case.

## Example client code (step 1)
```
[OpenApiOperation(operationId: "TestSendingPayload", tags: new[] { "Dylan" }, Description = "Send some things", Visibility = OpenApiVisibilityType.Important)]
    [OpenApiRequestBody(contentType: "application/json", bodyType: typeof(DylanPayload))]
    [Function("TestSendingPayload")]
    public async Task<HttpResponseData> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "test")] HttpRequestData requestData)
    {
        var requestContent = (await requestData.ReadAsStringAsync())?.Trim() ?? string.Empty;

        var uri = new Uri("api/dylan-receiver", UriKind.Relative);

        var serializeOptions = new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
        };

        // Method 1 - Receiving function DOES read payload correctly
        using var httpContent = new StringContent(requestContent, Encoding.UTF8, "application/json");
        var response = await _httpClient.PostAsync(uri, httpContent, CancellationToken.None).ConfigureAwait(false);

        // Method 2 - Receiving function DOES NOT read payload correctly
        var dylan = JsonConvert.DeserializeObject<DylanPayload>(requestContent, _serializerSettings);
        var response2 = await _httpClient.PostAsJsonAsync(uri, dylan, CancellationToken.None).ConfigureAwait(false);

        return HttpResponseData.CreateResponse(requestData);
    }
```

## Example "receiving" code (step 2)
```
        [Function("DylanReceiver")]
        [OpenApiOperation(operationId: "DylanReceiver", tags: new[] { "Dylan" }, Description = "Receive the payload", Visibility = OpenApiVisibilityType.Important)]
        [OpenApiRequestBody(contentType: "application/json", bodyType: typeof(DylanPayload))]
        public async Task<HttpResponseData> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "dylan-receiver")] HttpRequestData requestData)
        {
            var requestContent = (await requestData.ReadAsStringAsync())?.Trim() ?? string.Empty;

            // requestContent is EMPTY for content posted by _httpClient.PostAsJsonAsync() , and PRESENT for content posted by _httpClient.PostAsync()
            _logger.LogInformation("DylanReceiver: Received request payload: {requestContent}", requestContent);

            return requestData.CreateResponse(HttpStatusCode.Accepted);
        }
```

**Comment by kshyju** [comment]
Thanks for creating the issue with relevant information from your investigation.

The HttpRequestData model does not support streaming, but the new "Aspnet core integration" model does. So, If you want to get chunked data support, consider using the [AspNet core integration feature](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration).

**Comment by dylanhouston7** [comment]
> Thanks for creating the issue with relevant information from your investigation.
> 
> The HttpRequestData model does not support streaming, but the new "Aspnet core integration" model does. So, If you want to get chunked data support, consider using the [AspNet core integration feature](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration).

Thanks for the reply.

We switched our ASP.NET Core In-Process Functions to run in .NET Isolated HTTP Triggered Functions specifically to:
1) Save money with the "consumption plan" in Azure
2) Be able to use custom authentication middleware

It looks like with the ASP.NET core integration model, middleware is not supported?

Right now, we have an implementation with `HttpRequestData` and we ran into significant integration issues with a client caller as a result of the "chunked" payload that they were sending us. It's unfortunate that the client had to be made aware of implementation details regarding how to send an HTTP payload.

 At a minimum, this shortcoming should be documented somewhere.

**Comment by kshyju** [comment]
You can still write functions [middleware](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#middleware) in your function app. Are you experiencing issues with that? Can you be more specific about what is not working?
