### ISSUE TITLE
Function App does not start after update to 1.16.0

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#2029]
Error:

> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Comment by kshyju** [comment]
Hi @dmytro-gokun Thanks for reporting. I am not able to repro this issue when I tried to run from Visual studio. Are you running it from visual studio? Do you know what version of core tools are you using? Is it the latest? 

Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by martinhenrysson** [comment]
I had the same issue using func start. Downgrading Microsoft.Azure.Functions.Worker.Sdk to 1.15.1 solved it.

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

**Comment by dmytro-gokun** [comment]
@kshyju I was doing "func start". And updating core tools from 4.0.5274 to 4.0.5441 (latest) solved the problem. Thanks for your help!

**Comment by sanjaydebnath** [comment]
Why this is closed? We have the same issue while running function apps inside AKS after upgrading this minor version of sdk nuget. Is downgrading the only solution? @dmytro-gokun

**Comment by dmytro-gokun** [comment]
@sanjaydebnath I've closed it because my issue was solved by upgrading core tools

**Comment by zawasp** [comment]
Not for me. Using latest core tools and 1.16.1. Downgrading to 1.15.1 solves this.
<img width="1897" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/2464830/5e05a060-59c9-4dd8-ba36-e38828f41e88">
Please reopen.
