### ISSUE TITLE
AZFW0012 compiler error when using FixedDelayRetry with a TimerTrigger

### ISSUE THREAD

**Issue by martinstenhoff** [Azure/azure-functions-dotnet-worker#2039]
When upgrading `Microsoft.Azure.Functions.Worker.Sdk` from 1.14.1 to 1.16.0 we now get a AZFW0012 compiler error on this:
``` CSharp
[Function("MyFunction")]
[FixedDelayRetry(5, "00:00:10")]
public async Task Run([TimerTrigger("0 */5 * * * *")] TimerInfo timerInfo, FunctionContext context)
```
[AZFW0012](https://dotnet-worker-rules.azurewebsites.net/rules?ruleid=AZFW0012) Invalid use of a retry attribute. Check that the attribute is used on a trigger that supports function-level retry.

Is the documentation incorrect/outdated here? [Retry examples](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cisolated-process&pivots=programming-language-csharp):

<blockquote>
 Isolated worker model

 ``` CSharp
 [Function(nameof(TimerFunction))]
 [FixedDelayRetry(5, "00:00:10")]
 public static void Run([TimerTrigger("0 */5 * * * *")] TimerInfo timerInfo, FunctionContext context)
 {
     var logger = context.GetLogger(nameof(TimerFunction));
     logger.LogInformation($"Function Ran. Next timer schedule = {timerInfo.ScheduleStatus.Next}");
}
```
</blockquote>

We're using:
```
Microsoft.Azure.Functions.Worker.Sdk 1.16.0
Microsoft.Azure.Functions.Worker.Extensions.Timer 4.2.0
```

**Comment by destects** [comment]
I am also verifiably having the exact same issue, with the exact same situation of going from 1.14.1 to 1.16.0 

I believe the `Microsoft.Azure.fucntions.Worker.Sdk.Analyzers` `1.2.1` specifically is at fault here.

Something that's also interesting is the `AZFW0012` rule doesn't show in the list of rules for the analyzer, but it is sourced from it. 

the specific version of the analyzers is pinned for sdk 1.16.0, so the only work around I found as of right now, was to target sdk 1.15 instead.

**Comment by kshyju** [comment]
@martinstenhoff Could you please upgrade your [Microsoft.Azure.Functions.Worker.Extensions.Timer ](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Timer/4.3.0)reference to the latest 4.3.0 ? That should fix the issue.

**Comment by SeanFeldman** [comment]
Is retry policy working with Service Bus trigger? I thought that was unsupported at some point.

**Comment by kshyju** [comment]
@rbipin Function level retry policy is not supported for service bus. 

The error you received also includes a [link to a page](https://dotnet-worker-rules.azurewebsites.net/rules?ruleid=AZFW0012) which explains what this error means and you can find a list of triggers that support function-level retry from that page.

> A list of triggers that support function-level retry can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries).

Hope this helps. Let us know if you still have questions.

**Comment by rbipin** [comment]
thank you! @kshyju and @SeanFeldman this was helpful

**Comment by kshyju** [comment]
@satvu FYI - Perhaps we can consider an analyzer for this?

**Comment by rbipin** [comment]
@kshyju do you mean the analyzer recommending not to use the retry attribute?

**Comment by mattfrear** [comment]
> @rbipin Function level retry policy is not supported for service bus.
> 
> The error you received also includes a [link to a page](https://dotnet-worker-rules.azurewebsites.net/rules?ruleid=AZFW0012) which explains what this error means and you can find a list of triggers that support function-level retry from that page.
> 
> > A list of triggers that support function-level retry can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries).
> 
> Hope this helps. Let us know if you still have questions.

I found my way here because I'm trying to use FixedDelayRetry with ServiceBusTrigger.

The table you've linked to says:
Trigger/binding: Service Bus
Retry source: "[Binding extension](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger)"

Which doesn't shed any light on how to do a retry with a ServiceBusTrigger.

My use case is I would like to retry a message in my topic subscription one time only, 5 mins in the future. `[FixedDelayRetry(1, "00:05:00")]`


If I can't use FixedDelayRetry, then I fear I may have to rearchitect my topic to be a queue, and [post a copy of the message back to the queue with a future ScheduledEnqueueTimeUtc](https://stackoverflow.com/a/67118639/32598) as @SeanFeldman suggested a few years ago.
