### ISSUE TITLE
Azure function v4 using .NET 7 throws error Grpc.Core: Error loading native library

### ISSUE THREAD

**Issue by Yogeswaran66** [Azure/azure-functions-dotnet-worker#2042]
Machine - MacBook Pro M2
OS - macOS Ventura  13.0

.NET 7 azure function v4 throws the error on launch as below

Grpc.Core: Error loading native library. Not found in any of the possible locations: /Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/libgrpc_csharp_ext.arm64.dylib,/Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,/Users/[username]/Documents/Codes/AzureFuncProj/AzureFuncProj/bin/Debug/net7.0/.azurefunctions/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib.

The same function works fine on Windows machine.

**Comment by PTLozano** [comment]
Same issue here.

MacBook Pro M2
Sonoma 14.2

**Comment by qingxi** [comment]
> Same issue here.
> 
> MacBook Pro M2 Sonoma 14.2

I've found the solution to fix this issue and share you [Run-azure-functions-in-vscode-with-x86_64-on-Mac-M2](https://ordinary-meeting-3ea.notion.site/Run-azure-functions-in-vscode-with-x86_64-on-Mac-M2-cdd5e77319ef445ab1df3dc98063443c )

**Comment by liliankasem** [comment]
We will be using the following issues to track a fix for this problem:

- https://github.com/Azure/azure-functions-durable-extension/issues/2392
- https://github.com/microsoft/durabletask-dotnet/issues/148

Closing as dupe.
