### ISSUE TITLE
Discovery of triggers in "referenced" assemblies no longer works

### ISSUE THREAD

**Issue by Bitguru72** [Azure/azure-functions-dotnet-worker#2049]
From version 1.16.0 (and in 1.16.1) any trigger defined in a "referenced" assembly is no longer discovered and registered. 

The trigger http endpoints inside Microsoft.Azure.Functions.Worker.Extensions.OpenApi no longer appears and are not callable. I have similar internal projects where we have internal timer functions in our referenced assemblies, and they also fail to register with version 1.16.0 and 1.16.1.

If I roll back to 1.15.1, the openapi and my own timers, reappear.

Check this issue for a "repro" description: https://github.com/Azure/azure-functions-openapi-extension/issues/625

**Comment by NFMynster** [comment]
Can confirm rollback to 1.15.1 works with the OpenAPI extension.

With 1.16.x 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/5054730/c35b9148-0887-4dcf-b57c-38e29775d7f0)

With 1.15.1
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/5054730/a0d339e0-23f3-4ead-b0ac-b9334ed01470)

**Comment by fabiocav** [comment]
Thank you for reporting this, @Bitguru72 .

We'll take a closer look here, but in the meantime, setting the project property `FunctionsAutoRegisterGeneratedMetadataProvider` to false should help with the latest version. Can you please validate? Thanks!

**Comment by Bitguru72** [comment]
@fabiocav No, setting that in the csproj had no effect. However, adding   <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>
does restore functionality!

**Comment by mathiasi** [comment]
I believe the bug I just created (before noticing this bug report) might be related: #2051

**Comment by kshyju** [comment]
This is a [known issue](2052) at the moment. We will release a new version of the package with the fix shortly. Until then you can mitigate this issue by adding the below entry to your `.csproj` file.

```xml
<PropertyGroup>
  <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>
</PropertyGroup>
```

**Comment by MO2k4** [comment]
I see almost the same issue, but for me no triggers are found at all, not even the ones in the assembly itself. I can confirm that the workaround mentioned by @kshyju fixes this

**Comment by kshyju** [comment]
@Bitguru72 Fix for this issue is present in the following release:

[Microsoft.Azure.Functions.Worker.Sdk 1.16.2](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.16.2)

Please upgrade to `Microsoft.Azure.Functions.Worker.Sdk` [version 1.16.2 ](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2)and that should fix this issue.

**Comment by Bitguru72** [comment]
> @Bitguru72 Fix for this issue is present in the following release:
> 
> [Microsoft.Azure.Functions.Worker.Sdk 1.16.2](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.16.2)
> 
> Please upgrade to `Microsoft.Azure.Functions.Worker.Sdk` [version 1.16.2 ](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2)and that should fix this issue.

Yep, works like a charm! Thanks for the speedy response and subsequent fix! 👍 :-)
