### ISSUE TITLE
Do output bindings do automatic bulk transactions?

### ISSUE THREAD

**Issue by joshbinney** [Azure/azure-functions-dotnet-worker#2050]
When using table output binding and returning an array of results, does the output get sent in bulk transactions or one by one? Trying to optimize transaction costs, so weighing up using output binding or client injection manually.

Cheers

**Comment by aishwaryabh** [comment]
Hi can you specify what you mean by bulk transaction versus one by one? We currently bind to an array of `T[]`, where each entry represents one entity.

**Comment by joshbinney** [comment]
Hey, single or bulk as in, when supplied with an array of T, will the
entries be written to storage one at a time or in a bulk transaction like
you would if you manually wrote to storage with the azure library.

**Comment by aishwaryabh** [comment]
Oh I see. It would be one at a time from my understanding. You could use batching to have it run in a bulk transaction

**Comment by joshbinney** [comment]
Thanks. It might a nice feature to have automatic batching if there is
multiple results from the function to improve performance and runtime
costs.

Can we please get this note added to the documentation so others know that
there isn't batching?

**Comment by aishwaryabh** [comment]
Sure I can add this is an issue in our backlog
