### ISSUE TITLE
[BUG] Functions living in namespace with "." appears to be ignored in latest worker-package

### ISSUE THREAD

**Issue by mathiasi** [Azure/azure-functions-dotnet-worker#2051]
I have created a test project here to reproduce: https://github.com/mathiasi/FunctionBug 
It consist of three projects: One "Main" project and two library projects "DoesWork" and "Does.Not.Work".
The Main project references both library projects. 
In the initial commit ( https://github.com/mathiasi/FunctionBug/commit/f70de34af30811e80978b5f572c4934fe4cecd5a ) using
```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
```
All Functions are loaded:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2315801/42e216d6-c6cd-4c70-b300-9e3fa479053d)

However in this commit ( https://github.com/mathiasi/FunctionBug/commit/125ec5f8976d9b7af7043a5a7c97f0dd2fd09daa ) using 
```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.1" />
```
the Function that lives in a namespace containing "." is suddenly missing:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2315801/2b8b45af-6106-4f43-a74e-83d0e165bd36)

**Comment by kshyju** [comment]
This is a [known issue](2052) at the moment. We will release a new version of the package with the fix shortly. Until then you can mitigate this issue by adding the below entry to your `.csproj` file.

```xml
<PropertyGroup>
  <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>
</PropertyGroup>
```

**Comment by kshyju** [comment]
Update: Fix for this issue is present in the following release:

[Microsoft.Azure.Functions.Worker.Sdk 1.16.2](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.16.2)

Please upgrade to `Microsoft.Azure.Functions.Worker.Sdk` [version 1.16.2 ](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2)and that should fix this issue.
