### ISSUE TITLE
Handle nested assemblies when probing for functions from referenced assemblies

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#2052]
The issue happens when using `Microsoft.Azure.Functions.Worker.Sdk` package version 1.16.0 or 1.16.1

When functions are defined in nested namespaces, the code to detect functions from external assembly fails. 

Inside `GetDependentAssemblyFunctions` method, when it is nested namespaces, ` if (m is INamedTypeSymbol namedType)` returns `false` and we don't process that namespace member (in this case the child namespace) further.

https://github.com/Azure/azure-functions-dotnet-worker/blob/bef360980a5f26c2ec6b2bd2977c3ca4a715d066/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.cs#L100-L107

To repro with our tests, change `namespace DependentAssemblyWithFunctions` at [line 7](https://github.com/Azure/azure-functions-dotnet-worker/blob/bef360980a5f26c2ec6b2bd2977c3ca4a715d066/test/DependentAssemblyWithFunctions/DependencyFunction.cs#L7) to ` namespace MyCompany.MyApp.DependentAssemblyWithFunctions` and run the `FunctionInDependentAssemblyTest` test.

https://github.com/Azure/azure-functions-dotnet-worker/blob/bef360980a5f26c2ec6b2bd2977c3ca4a715d066/test/DependentAssemblyWithFunctions/DependencyFunction.cs#L7-L17

#### Mitigation

You can fix this issue by adding the below entry to your `.csproj` file

```
<PropertyGroup>
  <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>
</PropertyGroup>
```

**Comment by kshyju** [comment]
Fix for this issue is present in the following release:

[Microsoft.Azure.Functions.Worker.Sdk 1.16.2](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.16.2)

Please upgrade to `Microsoft.Azure.Functions.Worker.Sdk` [version 1.16.2 ](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2)and that should fix this issue.

**Comment by ChristopherL-STCU** [comment]
This is very surprising and is a breaking change. Will this be the behavior going forward?
