### ISSUE TITLE
.NET 7 Isolated: Logs missing from Application Insights / Log Analytics

### ISSUE THREAD

**Issue by rodolfograve** [Azure/azure-functions-dotnet-worker#2059]
Hello.

We are running an isolated Function using the latest packages. This is the list of relevant packages:

1. Microsoft.ApplicationInsights.WorkerService v2.21.0
2. Microsoft.Azure.Functions.Extensions v1.1.0
3. Microsoft.Azure.Functions.Worker v1.20.0
4. Microsoft.Azure.Functions.Worker.ApplicationInsights v1.1.0
5. Microsoft.Azure.Functions.Worker.Sdk v1.16.1
6. Microsoft.Extensions.Logging v7.0.0
7. Microsoft.Extensions.Logging.Abstractions v7.0.1
8. Microsoft.Extensions.Logging.Configuration v7.0.0

Dependency injection configuration looks like this:
```
builder.ConfigureFunctionsWorkerDefaults();
builder.ConfigureServices(services =>
{
   services.AddApplicationInsightsTelemetryWorkerService();
   services.ConfigureFunctionsApplicationInsights();
})
```

The host.json looks like this:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {

      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request;Exception;Trace"
      }
    },
    "logLevel": {
      "default": "Information",
      "Function": "Information",
      "Host.Aggregator": "Information",
      "Host.Results": "Information"
    }
  },
  "extensions": {
    "http": {
      "hsts": {
        "isEnabled": true
      },
      "customHeaders": {
        "X-Content-Type-Options": "nosniff"
      }
    }
  }
}
```

However, logs generated from my code using Logger.LogInformation do not show up. Logs generated with Logger.LogWarning do show up.

There is a lot of disperse information out there about logging in Azure Functions:

1. [Here](https://learn.microsoft.com/en-us/azure/azure-functions/analyze-telemetry-data) it is assumed that everything just works, i.e. logs will show up in App Insights.
2. [Here](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights) there is mention of some more advanced configuration, but I couldn't figure out how it applies to my use case (which I hope is a common, simple use case). There is also a huge "Important" warning which I think applies to my use case, but I couldn't find any mention on what to do about it. See image 1 below.
3. [Here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs) it mentions the configuration for ILogger logs from App Insights, but the JSON schema does not match the one in host.json. In host.json there doesn't seem to be possible to include the "LogLevel" property inside "logging.applicationInsights" (see Image 2 below)

Image 1
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/37560e06-b248-464b-8681-0bc7995d8339)

Image 2
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/041be514-ec43-47a4-bd44-9397a7b21cc5)

I couldn't find any complete examples.

Could someone please point me to an example of how to configure an Isolate Azure Function so that any Logger.LogInformation shows up in AppInsights and Log Analytics (where Logger is an ILogger obtained via Dependency Injection).

P.S. I already checked that nothing is getting sampled away:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/107422/2028dc3e-4ffc-4cb4-b29e-7dbea16c91cb)

I also checked that the log entries show up in the "Log stream" of the function on the Azure Portal.

**Comment by gabrielweyer** [comment]
I think you're looking for this [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights):

> However, by default, the Application Insights SDK adds a logging filter that instructs the logger to capture only warnings and more severe logs. If you want to disable this behavior, remove the filter rule as part of service configuration:

```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .ConfigureLogging(logging =>
    {
        logging.Services.Configure<LoggerFilterOptions>(options =>
        {
            LoggerFilterRule defaultRule = options.Rules.FirstOrDefault(rule => rule.ProviderName
                == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
            if (defaultRule is not null)
            {
                options.Rules.Remove(defaultRule);
            }
        });
    })
    .Build();

host.Run();
```

**Comment by rodolfograve** [comment]
Thank you, @gabrielweyer. This worked.

This seems like a quite fragile way of doing things, involving:

1. A magic string, which I replaced with `rule.ProviderName == typeof(Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider).FullName`
2. A hidden dependency not only on the classes of a separate package that evolves independently, but also on what that other code does at runtime.

I hope the Functions team finds a better way to wrap this up without exposing their dependency on the AppInsights SDK... perhaps a settings in their WorkerOptions?

**Comment by Krumelur** [comment]
I tried above solution and still don't get anything below "warning". I debugged and noticed that there isn't a single rule (`options.Rules` is NULL), therefore there's nothing to be removed. Ideas?

**Comment by joeyeng** [comment]
> > I tried above solution and still don't get anything below "warning". I debugged and noticed that there isn't a single rule (`options.Rules` is NULL), therefore there's nothing to be removed. Ideas?
> 
> I had a similar issue, and once I moved the ConfigureLogging to the end of the chain, it started working, maybe check that?

This makes this issue even more ridiculous

**Comment by progmars** [comment]
This is so convoluted. 

It's good and understandable that AppInsights adds Warning level as default because we don't want it to spam too much.
However, the fact that we need to mess with AppInsights' internal filters to be able to add our own information messages for our own categories to App Insights is just ugly.

And what would be the consequences of removing that filter? Would we start seeing more internal .net core logging information than we want? Then what is the proper way to keep all the default log levels as Warnings (as it should be) and have our own logging configured by categories?
