### ISSUE TITLE
Startup with nested namespaces still broken

### ISSUE THREAD

**Issue by MO2k4** [Azure/azure-functions-dotnet-worker#2062]
I am still seeing errors with the latest release of the sdk v.1.16.2

here is a minimal repro, it starts when i add the OpenApi package

[Minimal Repro](https://github.com/MO2k4/MinimalRepro.Trigger.In.Nested.Namespaces)

Is there a way to get more output when the startup fails? I tried to reproduce this and even the reproduction is flaky, sometimes the service starts and sometimes it does not.

After another few attempts i noticed, that it is working when running as release, while running in debug it isnt starting 👎

**Comment by MO2k4** [comment]
I am working on a mac with Rider, both using the latest version, func core tools are 4.0.5455, since i am also seeing this issue in a docker build, i added this to my repro repo

```
warn: Host.Startup[0]
      No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      HttpOptions
      {
        "DynamicThrottlesEnabled": false,
        "EnableChunkedRequestBinding": false,
        "MaxConcurrentRequests": -1,
        "MaxOutstandingRequests": -1,
        "RoutePrefix": "api"
      }
info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]
      Initializing function HTTP routes
      No HTTP routes mapped
      
info: Host.Startup[412]
      Host initialized (69ms)
info: Host.Startup[413]
      Host started (82ms)
info: Host.Startup[0]
      Job host started
```

**Comment by kshyju** [comment]
Pulled your repro again and ran in rider (on windows) after adding a `local.settings.json` with below content

```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}
```
It is correctly detecting the functions from open api extension for me.  When you test, are you seeing the same core tools version in the rider terminal, as what I have below?

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/05ec4532-d890-49fb-9dfd-f72c70d0e7bb)

For your docker repro, can you add the below environment variable to your container and see that resolves your issue?

name: `AzureWebJobsFeatureFlags`
value: `EnableWorkerIndexing`

**Comment by MO2k4** [comment]
Hey @kshyju 

Version wise it looks the same for me, maybe its because i am working on an arm platform instead of an intel?

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/453360/7bc334ef-e25c-40ca-8f80-b1a92b38e33b)

and after adding the env to my docker container i see the function, but they are still returning 404 when calling them

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/453360/1e01e734-cded-4c3e-a5e7-8681b7460711)

and when calling the swagger endpoint i receive this exception

```
      Function 'RenderSwaggerDocument', Invocation id 'e2931646-dd61-464c-811e-dd5d7090b6c9': An exception was thrown by the invocation.
      Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Function 'RenderSwaggerDocument', Invocation id 'e2931646-dd61-464c-811e-dd5d7090b6c9': An exception was thrown by the invocation.
      Exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
         at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
      Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
         at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
         at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
         at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
```

when running without the additional feature flag, i can open the endpoints for swagger now and there is no error, but when calling my own endpoint i receive 404 and there is nothing in the logs as well 🤷‍♂️

if i add

```xml
        <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>
```

to the project i can start the debug session locally and call the endpoint

**Comment by fabiocav** [comment]
@MO2k4 I have moved the latest comment to a new issue (#2048) as that is a bit different than the original problem we were dealing with. We'll continue to follow up there.
