### ISSUE TITLE
"No job functions found" after nuget update

### ISSUE THREAD

**Issue by bexxx** [Azure/azure-functions-dotnet-worker#2063]
We run our v4 Azure function isolated on usually latest nuget dependencies on ubuntu.
With the last two updates our functions stop being healthy (we cross checked by just reverting nuget and it works again).

Exception is: Host.Startup[0]
2023-11-14T17:51:14.278218153Z       No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

Is there anything I can fetch in addition to help diagnosing the issue? 

The updates are:
works:
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />

does not work:
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" />

If it helps, I can try to see if 
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.1" />
works.

**Comment by nerdybeast** [comment]
I'm experiencing this as well, bumping this library to version `1.16.x` gives me that error. If I back down to version `1.15.1` everything seems to work just fine.

I'm on .Net 6, Azure Function v4

**Comment by kshyju** [comment]
Looks like you are using an older version of core tools. Are you running using visual studio? What is the core tools version you are seeing when running the app? Can you make sure you have the latest core tools for your local environment?

**Comment by sanjaydebnath** [comment]
> Looks like you are using an older version of core tools. Are you running using visual studio? What is the core tools version you are seeing when running the app? Can you make sure you have the latest core tools for your local environment?

@kshyju How to solve this for isolated function running in AKS (not local development). We are using latest `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0` image.

**Comment by kshyju** [comment]
@sanjaydebnath When did you build your images using the tag you mentioned above? Can you check what version of host you have inside your container? Can you try tot rebuild your image again to see that is pulling the latest version of host for you?

**Comment by bexxx** [comment]
We use .net 7 and build on ADO
The image has following properties:
Status: Downloaded newer image for mcr.microsoft.com/azure-functions/dotnet-isolated:4
mcr.microsoft.com/azure-functions/dotnet-isolated:4
/usr/bin/docker inspect mcr.microsoft.com/azure-functions/dotnet-isolated:4
[
    {
        "Id": "sha256:6ef09f0cbbf4b4890c490c1e0a334c1ce04d70a4014b6ca312f868933e532d14",
        "RepoTags": [
            "mcr.microsoft.com/azure-functions/dotnet-isolated:4"
        ],
        "RepoDigests": [
            "mcr.microsoft.com/azure-functions/dotnet-isolated@sha256:c67e4bf4b264a579f3eff56c2b56be6e4473a150a995191c0a292b5c190a5d53"
        ],
(this is the output from the failing deployment).

**Comment by David-Mulder-at-VLK** [comment]
We are also experiencing this. Net 7 function (on Windows in Azure), after updating 
Microsoft.Azure.Functions.Worker" Version="1.19.0"  to 1.20.0
Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.4" to 1.1.0
the Application Insights logs show 

> Loading functions metadata
> Reading functions metadata (Custom)
> 1 functions found (Custom)
> 0 functions loaded

If I compare my deployed ZIP's I see one difference that might explain the not loading of the functions:
In the worker.config.json file the workerIndexing value has changed from false to true.
I hope this helps in pinpointing the issue.

**Comment by David-Mulder-at-VLK** [comment]
Hmm. After testing different configurations, it actually looks like the issue is with a package I did not list above.
I also updated
Microsoft.Azure.Functions.Worker.Sdk Version="1.15.1" to 1.16.2.
After also reverting that change, the functions were loaded again

**Comment by bexxx** [comment]
I switched to a different docker image (dotnet-isolated:4-dotnet-isolated7.0) and it also did not help at all.

**Comment by kshyju** [comment]
@bexxx @David-Mulder-at-VLK While we investigate the issue on Linux, you can set the below enviornment variable to your container which will fix the issue for you. Sorry for the inconvenience.

name: `AzureWebJobsFeatureFlags`
value: `EnableWorkerIndexing`

**Comment by ludwhe** [comment]
I have encountered this issue also when deploying to Azure China Cloud, where no functions could be found after an update from 1.15.1 to 1.16.1 although they could be found in Azure Global with the same runtime as shown in Azure Portal and the same configuration.

**Comment by nerdybeast** [comment]
> Looks like you are using an older version of core tools. Are you running using visual studio? What is the core tools version you are seeing when running the app? Can you make sure you have the latest core tools for your local environment?

@kshyju I am simply using the latest version of Visual Studio 2022 Preview (17.9.0 Preview 1.0)

**Comment by cr3wdayt5p** [comment]
I can confirm that `1.6.2` results in `0 functions loaded` on Azure (but works locally). Reverting to `1.5.1` solves the issue.

Azure Functions:
 - Linux
 - Stack: `DOTNET-ISOLATED|7.0`
 - Runtime version: `4.27.5.5`

**Comment by Rtalos** [comment]
Chiming in on this, dont know if it helps but this is our scenario.

- dotnet-isolated
- net6
- windows

Running functions locally from VS works, no issues, in both 1.15.1 and 1.16.x.

Deploying to Azure EU West with version 1.16.x gives us the issue of "no functions found". We can also see this in the log (no idea if it helps)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/19684631/2b9d9d45-81df-4e24-8ca4-d88cbe3d444b)

**Comment by fabiocav** [comment]
@Rtalos if this is running on Windows (when deployed), it doesn't seem related to the original issue. Can you please open a separate issue so we can track there? Thank you!

**Comment by fabiocav** [comment]
> I can confirm that `1.6.2` results in `0 functions loaded` on Azure (but works locally). Reverting to `1.5.1` solves the issue.
> 
> Azure Functions:
> 
> * Linux
> * Stack: `DOTNET-ISOLATED|7.0`
> * Runtime version: `4.27.5.5`

@cr3wdayt5p are you seeing this issue when deployed (hosted in either Consumption, EP or dedicated)? If so, can you please open a separate issue with the details so we can take a closer look? This wouldn't be related to the original issue.

**Comment by cr3wdayt5p** [comment]
> @cr3wdayt5p are you seeing this issue when deployed (hosted in either Consumption, EP or dedicated)? If so, can you please open a separate issue with the details so we can take a closer look? This wouldn't be related to the original issue.

@fabiocav Yes, it is only an issue when deployed to Azure (works fine locally).

Our Function App hosting details:
- App Service plan
- Linux
- PremiumV3

I do think that all of our issues are related to a bug in `1.6.x` since we all have issue with this version despite different deploy methods in Azure (Windows and Linux and containerized or not). Wouldn't it be better to just rename this issue to something like:
"`Worker.Sdk` version `1.6.x` breaks deploy to Azure (`0 functions loaded`)"

**Comment by nerdybeast** [comment]
> > @cr3wdayt5p are you seeing this issue when deployed (hosted in either Consumption, EP or dedicated)? If so, can you please open a separate issue with the details so we can take a closer look? This wouldn't be related to the original issue.
> 
> @fabiocav Yes, it is only an issue when deployed to Azure (works fine locally).
> 
> Our Function App hosting details:
> 
> * App Service plan
> * Linux
> * PremiumV3
> 
> I do think that all of our issues are related to a bug in `1.6.x` since we all have issue with this version despite different deploy methods in Azure (Windows and Linux and containerized or not). Wouldn't it be better to just rename this issue to something like: "`Worker.Sdk` version `1.6.x` breaks deploy to Azure (`0 functions loaded`)"

@cr3wdayt5p well it's not just when deployed to Azure. `1.16.x` breaks me locally (I'm on Windows)
![Screenshot_124](https://github.com/Azure/azure-functions-dotnet-worker/assets/15707802/de0ffdc0-80db-411e-99d1-0a314d9b3d91)

**Comment by kshyju** [comment]
Thanks for your patience. During our investigation we found that an app setting was missing in the following images.

1. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0
2. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0
3. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0

The images were updated and published as of today with the fix. So If you rebuild your image using the above ones, the issue should be resolved for anyone who experienced the "_No job functions found_" on Linux platform. 

Sorry for the inconvenience this has caused. We will take steps to prevent this from happening in the future.

**Comment by bexxx** [comment]
I can verify next week Tue. Maybe other confirm this earlier.

There was a change on image tags too. :4 to :4-dotnet-isolated7.0. Where can I check to get future announcements? This slipped our attention.

**Comment by aressler38** [comment]
> Thanks for your patience. During our investigation we found that an app setting was missing in the following images.
> 
> 1. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0
> 2. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0
> 3. mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0
> 
> The images were updated and published as of today with the fix. So If you rebuild your image using the above ones, the issue should be resolved for anyone who experienced the "_No job functions found_" on Linux platform.
> 
> Sorry for the inconvenience this has caused. We will take steps to prevent this from happening in the future.

I am seeing this on app service environment. Please confirm if those images are included in the fix. Specifically, I am questioning this one:

**mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0-appservice-stage5**

**Comment by fabiocav** [comment]
@aressler38 are you explicitly using this image? If rebuilt, it should now have the proper configuration to ensure this works as expected. Can you please validate?

**Comment by fabiocav** [comment]
@bexxx please let us know when you have a chance to validate this again, but we do expect this to be resolved with the latest set of images.

@nerdybeast can you please open a separate issue with the details of what you're seeing, also sharing information about the environment information (e.g., we need to know the version of Core Tools being used)? 

Your issue, though with the same gesture, has a different root cause than the original problem for this issue and would be more efficient to track that separately.

**Comment by aressler38** [comment]
> @aressler38 are you explicitly using this image? If so, can you please drop the `-appservice-stage5` image if using a custom image?

No, it's not a custom build. I have a function app running on a Linux isolated app service plan within an app service environment v3. I don't have control (that I know of) over the choice of image. I can say that rolling `Microsoft.Azure.Functions.Worker.Sdk` back to `1.15.*` does solve the problem.

**Comment by bexxx** [comment]
> @bexxx please let us know when you have a chance to validate this again, but we do expect this to be resolved with the latest set of images.

Works for me now.

**Comment by bexxx** [comment]
Issue resolved

**Comment by frasermclean** [comment]
I have just stumbled across this thread. Was wracking my brains trying to get a Windows consumption plan function app working. 0 functions kept getting detected. Changing `Microsoft.Azure.Functions.Worker.Sdk` back to `1.15.1` seemed to make the functions get detected under the Azure Portal.

**Comment by pasha-top** [comment]
For windows and Visual Studio you need to uninstall all Azure Functions Core Tools and also remove from %Local%\%AppData%\ Then VS  automatically  install the latest version.

**Comment by haiplk** [comment]
Hello everyone, Is the issue has been fixed now?

I got the similar issues that seems related to this.
- The function works correctly on local docker: 1 function found - 1 function loaded
![image](https://github.com/user-attachments/assets/ba24651d-2e41-4a71-a3d6-00d53e68e696)

- But it cannot work with the same docker image on Azure Function: 1 function found - 0 function loaded
![image](https://github.com/user-attachments/assets/e8661893-095b-4f5e-8a01-1f32d8a2f516)


My Azure Function is BlobTrigger and build with based image mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0

Here is my packages (Already using Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1 as above suggestion)
```
 <PackageReference Include="Azure.Storage.Blobs" Version="12.21.2" />
 <PackageReference Include="Azure.Storage.Files.Shares" Version="12.19.1" />
 <PackageReference Include="Azure.Storage.Queues" Version="12.19.1" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.6.0" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
 <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
 <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.3.0" />
 <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.5" />
 <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
 <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
```

Do you guys have any idea or work arround on it

**Comment by zevolution** [comment]
> Hello everyone, is this issue has been fixed now?
> 
> I got the similar issues that seems related to this.
> 
> * The function works correctly on local docker: 1 function found - 1 function loaded
>   ![image](https://github.com/user-attachments/assets/ba24651d-2e41-4a71-a3d6-00d53e68e696)
> * But it cannot work with the same docker image on Azure Function: 1 function found - 0 function loaded
>   ![image](https://github.com/user-attachments/assets/3569ecdb-5f65-4913-8730-c257d0e15a12)
> 
> My Azure Function is BlobTrigger and build with based image mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0
> 
> Here is my packages (Already using Microsoft.Azure.Functions.Worker.Sdk 1.15.1 as above suggestion, the latest version 1.17 had the same issue)
> 
> ```
>  <PackageReference Include="Azure.Storage.Blobs" Version="12.21.2" />
>  <PackageReference Include="Azure.Storage.Files.Shares" Version="12.19.1" />
>  <PackageReference Include="Azure.Storage.Queues" Version="12.19.1" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.6.0" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.1" />
>  <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
>  <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.3.0" />
>  <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.5" />
>  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
>  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
> ```
> 
> Do you guys have any idea or work arround on it

@haiplk Did you solve this issue?

**Comment by haiplk** [comment]
Hi @zevolution 
Upgrading an Azure Function to the Premium tier can resolve that issue.
 The Free tier has some limitations, but it doesn't throw any errors.

**Comment by zevolution** [comment]
Thanks bro @haiplk 

I got this problem with a new function yesterday that persisted until recently, in one of my last attempts a few minutes ago I used the same versions of another function that was already working in another project:

`Stack`: .NET
`.NET Version`: .NET 8 Isolated
`Platform`: 32 bit
`FunctionVersion`: ~4
`WEBSITE_RUN_FROM_PACKAGE`: 1
```
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.6" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.3" />
```
