### ISSUE TITLE
Support for .Net Aspire?

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2066]
As the title says, is there any plan to support .Net Aspire?

**Comment by mattchenderson** [comment]
Yes! We don't have anything concrete to share at the moment, but it is definitely our intent to have things integrated there.

**Comment by MatthewSteeples** [comment]
Duplicate (although this one came first) of #2090

**Comment by mattchenderson** [comment]
Closing as duplicate
