### ISSUE TITLE
ASP.NET Core integration with ConfigureFunctionsWebApplication overwrite host url in the bindings of request (HttpRequestData)

### ISSUE THREAD

**Issue by Schulungkubanetis** [Azure/azure-functions-dotnet-worker#2071]
There is a problem to use the request url of HttpRequestData when using the ConfigureFunctionsWebApplication extension method.
Therefore the openapi integration https://github.com/Azure/azure-functions-openapi-extension is not working because the asp integration overwrite the url of HttpRequestData.
Is it possible to change the integration to a proper mapping so the primary values come from the binding and not form the default values of the asp integration itself?

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/60917262/03c94873-3cd1-4f94-ab8b-43ab6a21d34b)

**Comment by y2k4life** [comment]
My solution was to configure OpenAPI using the port  information found in launchSettings.json.

In your case `http://localhost:7194/api/`

[Overriding Base URLs](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#overriding-base-urls)
[Advanced Configuration in General](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-out-of-proc.md#advanced-configuration-in-general)

``` c#
.
.
.
    .ConfigureServices(services =>
    {
        services.AddSingleton<IOpenApiConfigurationOptions>(_ =>
        {
            var options = new OpenApiConfigurationOptions()
            {
                Servers = new List<OpenApiServer>()
                    {
                        new OpenApiServer() { Url = "http://localhost:7141/api/" }
                    }
            };

            return options;
        });
    
    })
.
.
.
```

**Comment by Schulungkubanetis** [comment]
> launchSettings

Good to know that there is a workarround. But I hope this is properly solved in the future.

**Comment by fabiocav** [comment]
@Schulungkubanetis should this me move to/tracked in the OpenAPI extension repo?

Thanks!

**Comment by Schulungkubanetis** [comment]
> @Schulungkubanetis should this me move to/tracked in the OpenAPI extension repo?
> 
> Thanks!

My undestanding ist that the url from the host which comes normaly with https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Grpc/Http/GrpcHttpRequestData.cs is overwrite with https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/HttpDataModel/AspNetCoreHttpRequestData.cs which get the url in AspNetCoreHttpRequestDataFeature from the generated httpcontext which is not equal.
If the difference between HttpRequestData:GrpcHttpRequestData.Url and HttpRequestData:AspNetCoreHttpRequestData.Url is intentionally and the AspNetCoreHttpRequestData.Url should be different from the host url than yes? 
I'am not sure how it can be used because AspNetCoreHttpRequestData.Url is every time localhost not only local but also deployed.

**Comment by fabiocav** [comment]
@Schulungkubanetis thank you for the additional details. This is a little clearer now. Will take a look at this in the coming sprint.

**Comment by fabiocav** [comment]
Thank you all. We have clarity on the issue here and will have an update to address this behavior as soon as possible.
