### ISSUE TITLE
Only one output binding is supported when using a binding assigned to '$return'

### ISSUE THREAD

**Issue by derodevil** [Azure/azure-functions-dotnet-worker#2073]
Updating to the latest version 1.16.2 causes error 
`System.InvalidOperationException: Only one output binding is supported when using a binding assigned to '$return'. Found a total of 2 bindings. For more information: https://aka.ms/dotnet-worker-poco-binding`

I need to downgrade to version 1.15.1 to make it work again.

**Comment by kshyju** [comment]
@derodevil Could you share how your output bindings are setup?

**Comment by derodevil** [comment]
```
[Function("broadcast")]
[SignalROutput(HubName = "brick_broadcaster", ConnectionStringSetting = "signalrConnection")]
public SignalRMessageAction Broadcast([HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req, FunctionContext functionContext)
{
    using var bodyReader = new StreamReader(req.Body);
    return new SignalRMessageAction("brick")
    {
        Arguments = new[] { bodyReader.ReadToEnd() },
    };
}
```

**Comment by jrmegatron** [comment]
I am facing the same issue when using a ServiceBusOutput in a http trigger function when I upgraded to 1.16.2. Downgrading to 1.15.1 has it working again.

**Comment by HSven1611** [comment]
Downgrade to 1.15.1 solves for now.

You can use this to block nuget from trying to update each time.

```xml
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="[1.15.1]" />
```

**Comment by jrmegatron** [comment]
@satvu has this bug been resolved? If so, which package version can we try now?

**Comment by jacksorjacksor** [comment]
I just upgraded to Version 1.16.4 and this issue was resolved:

`<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />`
