### ISSUE TITLE
Using Multiple Output Bindings with ASP.NET Core Integration

### ISSUE THREAD

**Issue by markheath** [Azure/azure-functions-dotnet-worker#2079]
I was trying to combine [multiple output bindings](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#multiple-output-bindings) with [ASP.NET Core Integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration).

Here's the type I'm returning from my HTTP triggered function:

```cs
public class NewOrderOutput
{
    public IActionResult? HttpResponse { get; set;}
    [QueueOutput("orders")]
    public OrderMessage? OrderMessage { get; set; }
    [CosmosDBOutput("db", "orders", Connection = "CosmosDB", CreateIfNotExists = false)]
    public OrderDocument? OrderDocument { get; set; } 
}
```

And here's using it
```cs
[Function(nameof(NewOrder))]
public async Task<NewOrderOutput> NewOrder(
    [HttpTrigger(AuthorizationLevel.Anonymous, "POST")] HttpRequest req, 
    [FromBody] OrderWebhook order)
{

    var response = new ContentResult()
    {
        Content = $"New order received for {order.ProductName} x {order.Quantity}"
    };

    var message = new OrderMessage() /// ...
    var doc = new OrderDocument()  //...
    return new NewOrderOutput() { OrderMessage = message, HttpResponse = response, OrderDocument = doc  };
}
```

When I call the function, I get no body in the HTTP response. However, if I change this up to use `HttpRequestData` and `HttpResponseData` it all works fine.

Should this feature work with `IActionResult`, or am I doing something wrong?

**Comment by jt2** [comment]
I have the same problem/question.

**Comment by HARVS1789UK-VAIIE** [comment]
I am also struggling with the exact same issue. I've scoured the documentation but keep going round in circles between the same 4-5 articles, all of which cover these topics in isolation but provide no examples of them being used together

**Comment by HARVS1789UK-VAIIE** [comment]
@markheath and @jt2 - I've not been able to answer the specific question posed above of:

> Should this feature work with IActionResult

(though I certainly have some well backed assumptions now, as below) 

However, I have found an alternative approach that satisfies the underlying desire to return multiple outputs, including a well formed HTTP Response for the client, from a 'ASP.NET Core Integration' based function.

It seems to me like the `IActionResult` approach only works when it is the only return value from your function e.g.:

```c
[Function(nameof(ActionResultTest))]
public IActionResult ActionResultTest(
    [HttpTrigger(
        AuthorizationLevel.Anonymous, 
        "get", 
        Route = "test/{success:bool}"
    )]
    HttpRequest req,
    bool success
) {
    return (success)
        ? new OkObjectResult("Request processed successfully")
        : new BadRequestObjectResult("Request processing failed");
}
```

Calls to this work as expected with the relevant HTTP status code and string based body being returned:

![Screenshot 2024-01-16 at 11 46 26](https://github.com/Azure/azure-functions-dotnet-worker/assets/126493958/97f5b203-90e3-4028-ba0e-7769b79c84c6)

It seems that the only way to return a correctly formed HTTP response to the client when attempting to specify multiple outputs, is for your custom response object to have a `public HttpResponse HttpResponse` property (from my tests, as well as the data type `HttpResponse` being important, the property name must **also** be `HttpResponse`).

It's now my suspicion that a property with this exact type and name is explicitly searched for/has special meaning in a custom return object, though to my knowledge, that's not mentioned or documented anywhere in the Microsoft documentation I have read.

When using 'ASP.NET Core Integration', with a `HttpRequest` [payload](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-csharp#payload) as opposed to a `HttpRequestData` payload (which has the handy `req.CreateResponse(HttpStatusCode.OK);` method) creating/accessing a `HttpResponse` object isn't quite as easy (especially given HttpResponse is a sealed abstract class, so cannot be created via `HttpResponse res = new HttpResponse()`) but an empty instance can be accessed from the inbound `HttpRequest` input, updated and returned via your custom return object as below:

```c
[Function(nameof(HttpResponseTest))]
  public async Task<MultiResponse> HttpResponseTest(
      [HttpTrigger(
          AuthorizationLevel.Anonymous, 
          "get", 
          Route = "test/{success:bool}"
      )]
      HttpRequest req,
      bool success
  ) {
      HttpResponse response = req.HttpContext.Response;
      string message = String.Empty;
      if (success)
      {
          message = "Request processed successfully";
          response.StatusCode = 200;
          await response.WriteAsync(message);
          return new MultiResponse() {
              Messages = new string[] { message },
              HttpResponse = response
          };
      }
      else
      {
          message = "Request processing failed";
          response.StatusCode = 400;
          await response.WriteAsync(message);
          return new MultiResponse() {
              HttpResponse = response
          };
      }
  }

public class MultiResponse
{
    [QueueOutput("my-queue", Connection = "AzureWebJobsStorage")]
    public string[]? Messages { get; set; }

    public HttpResponse HttpResponse { get; set; }
} 
```

Note: there is also the `response.WriteAsJsonAsync<T>(myObj);` based option if you want to write something more sophisticated than a simple string to the response body (like a serialised/JSON representation of a C# class/object)

This approach is allowing me to bind to multiple outputs (queue storage, table storage etc) and return a sensible HTTP response object to my requesting client, with a suitable status code and body, whilst still benefiting from the 'ASP.NET Core Integration' approach.

**Comment by satvu** [comment]
@markheath @jt2 @HARVS1789UK-VAIIE what package versions are you using for the ASP.NET Integration extension, the worker, and the worker sdk?

**Comment by jt2** [comment]
> what package versions are you using for the ASP.NET Integration extension, the worker, and the worker sdk?
I've moved on had to use another solution. Therefore cannot give a good answer. I used the latest package/sdk available in December and followed the documentation.

**Comment by DHowett** [comment]
I am also seeing this issue, and I am using:

Http.AspNetCore Extension: 1.2.0
Worker: 1.20.1
Worker SDK: 1.16.4

They were the latest available last week when I started .NET 8
isolated conversion on this project.

**Comment by abratv** [comment]
spending hours due normal isolated get mixed up with aspnet core integration.... and finding this issue that multiple output still not working properly in aspnet core integration....

**Comment by abratv** [comment]
The code @HARVS1789UK-VAIIE should be in documentation, thanks its finally working

**Comment by bgribaudo** [comment]
This bit me today, as well.

**Comment by dggmez** [comment]
Seems like a fix was already merged. Is there a way to know when the next release is going to be made? I would prefer to avoid having to write something similar to what @HARVS1789UK-VAIIE had to write just to delete it in a few days.

**Comment by satvu** [comment]
@dggmez the fix has been released - please upgrade to the following packages:

Microsoft.Azure.Functions.Worker.Sdk 1.17.3-preview2
Microsoft.Azure.Functions.Worker.Extensions.Http 3.2.0
Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore 1.3.0

**Comment by dggmez** [comment]
@satvu It didn't work. I'm getting this error:

>Generator 'FunctionMetadataProviderGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Comment by satvu** [comment]
@dggmez Do you have a minimal repro that you can share a GH link to? Which SDK version did you have prior to this upgrade? A minimal repro function app would be most helpful - please also keep the same extension versions (servicebus, other) in the repro and I can investigate.

**Comment by dggmez** [comment]
@satvu We decided to just ban multiple output bindings, return an `IActionResult` and use the Azure Service Bus SDK directly to send the message just like you would do in an ASP.NET Core app.

**Comment by HARVS1789UK-VAIIE** [comment]
With the noted packaged updated to the specified versions (or newer) and the addition of the `[HttpResult]` attribute referenced in the updated [docs for multiple output bindings](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#multiple-output-bindings) I was able to get the expected functionality from my 'custom return type' object in the form of both:

```
[HttpResult]
public HttpResponse Response { get; }
```

and

```
[HttpResult]
public IActionResult Response { get; }
```

Many thanks @satvu
