### ISSUE TITLE
.NET Aspire support

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#2090]
Opening an issue to track the work required to enable Azure Functions support for .NET Aspire.

Issues will be assigned to the [.NET Aspire milestone](https://github.com/Azure/azure-functions-dotnet-worker/milestone/66)

**Comment by IEvangelist** [comment]
Hi friends, with the official release of .NET Aspire (going GA today), I wanted to ask about this issue as I'd love for support to use Azure Functions with .NET Aspire... 🤓

**Comment by mattchenderson** [comment]
Closing this tracking item as this is now available as a public preview. See https://learn.microsoft.com/azure/azure-functions/dotnet-isolated-process-guides#net-aspire-preview and https://learn.microsoft.com/en-us/dotnet/aspire/serverless/functions for details.
