### ISSUE TITLE
Unable to target or run NET 8.0 when creating functions in VS2022 or via CLI

### ISSUE THREAD

**Issue by denious** [Azure/azure-functions-dotnet-worker#2091]
.NET SDK: 8.0.100
Core Tools Version: 4.0.5085
Function Runtime Version: 4.16.4.20366
VS2022 Version: 17.8.1

When following directions from MSFT documentation and running:
`func init LocalFunctionProj --worker-runtime dotnet-isolated --target-framework net8.0`

The following error is displayed:
- Unable to parse target framework net8.0. Valid options are "net48", "net6.0", and "net7.0"

In VS2022, there is no NET 8 option when creating a new Functions project:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7120854/041d71b4-f2c4-4350-bcb7-1900781c8ecd)

When attempting to run a function specified as `<TargetFramework>net8.0</TargetFramework>`, the following error is given:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7120854/d3bf99ce-2a53-4987-ad90-509daac7f815)

**Comment by kshyju** [comment]
@denious Normally, VS will automatically update the azure functions tools. Could you double check this in **Tools-> Options-> Projects and Solutions-> Azure Functions-> Check for updates**

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/a2d37e7d-eb95-4e16-9d37-089de8c07dc0)

**Comment by denious** [comment]
@kshyju That was it, thank you!

I had no idea that option even existed, weird that installing the latest SDKs and tooling via the documented methods didn't pick things up.
