### ISSUE TITLE
Isolated functions with .NET 8 - SignalR extension throws warning CS8785

### ISSUE THREAD

**Issue by Msirkovsky** [Azure/azure-functions-dotnet-worker#2100]
After upgrading our application to .NET 8, I started receiving the following error:

```
CSC : warning CS8785: Generator 'FunctionMetadataProviderGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'TypedConstant is an array. Use Values property.'.
```

**Steps to reproduce:**

- using Visual Studio 17.8.1
- create a new Function app targeting .NET 8 Isolated
- add the SignalR extension + a simple Negotiate method 

```
[Function("negotiate")]
public string Negotiate([HttpTrigger(AuthorizationLevel.Function)] HttpRequestData req, [SignalRConnectionInfoInput(HubName = "TestFunctions", UserId = "{headers.user}",
            IdToken = "{headers.token}",
            ClaimTypeList = new []{"user_id"})] string connectionInfo
    )
    {
        return connectionInfo;
    }
```
Minimal repo:
https://github.com/Msirkovsky/signalR-net8-issue-CS8785

**Comment by satvu** [comment]
While we investigate, you can mitigate the issue by adding the property `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>`.

**Comment by christianhelle** [comment]
> While we investigate, you can mitigate the issue by adding the property `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>`.

@satvu Are there any negative side effects of setting `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>` ? I ran into the same problem with triggers for Timer, Storage Queues, and ServiceBus Topics

**Comment by christianhelle** [comment]
> @christianhelle Setting it to false means that some cold start performance optimizations will not take place (see [docs](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#performance-optimizations)), but this should have no other impact (same behavior/performance as previous SDKs).

Thanks for clarifying @satvu

> Can you share a minimal repro of the code causing errors for you and the error that you are getting? And could you also share the versions of the Timer, Storage, and ServiceBus extension packages you are using?

Sure, the Functions project file looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

The build error was pretty much the same as the one in the description of this issue, except that instead of an `InvalidOperationException` I got a `NullReferenceException`

**Comment by satvu** [comment]
@christianhelle The NRE is likely a result of the timer extension package - upgrading to 4.3.0 should resolve it. If not, please open a new issue to track this separately. Thanks!

**Comment by satvu** [comment]
Original error is [thrown from Roslyn](https://github.com/dotnet/roslyn/blob/6acaa7b7c0efea8ea292ca26888c0346fbf8b0c1/src/Compilers/Core/Portable/Symbols/TypedConstant.cs#L99) when iterating over the named arguments of attributes [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/4089705f849bbd67be41f0e2fdd7777f379eff83/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.Parser.cs#L596) in our own stack. Retrieving named arguments using `attributeData.NamedArguments` will throw this error if an array is present. 

[Here](https://github.com/dotnet/docfx/pull/2602/files) is an example of a potential workaround implemented by the dotnet team.

**Comment by satvu** [comment]
SDK version 1.17.3-preview2 has been released with this fix.
