### ISSUE TITLE
Support for ServiceBusSessionMessageActions

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#2102]
As part of SDK parity with In-Process, the support for `ServiceBusMessageActions` was added.
What's the plan for supporting `ServiceBusSessionMessageActions`?

**Comment by SeanFeldman** [comment]
Never mind. I'm blind 😀

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/ServiceBusSessionMessageActions.cs

**Comment by SamVanhoutte** [comment]
We are migrating a solution from in process to Isolated Worker and stumbled upon this issue, indeed.
We are leveraging session state and I also noticed the `ServiceBusSessionMessageActions `was missing

**Comment by liliankasem** [comment]
tagging @JoshLove-msft in cases he has some info on this

cc @fabiocav

**Comment by SamVanhoutte** [comment]
Any update on this one, @JoshLove-msft or @fabiocav ?

**Comment by christoner** [comment]
My team’s migration from in-process to isolated worker is also blocked as we can find no equivalent to `ServiceBusSessionMessageActions.ReleaseSession()`.  

We required this to ensure the maximum number of concurrent receive requests quota was not exceeded.  It is unclear if this is no longer required or an unintentional omission.

**Comment by SamVanhoutte** [comment]
The silence on this is not really helping ....

**Comment by H-Finch-404** [comment]
We also need this class to manipulate SessionState in an isolated worker

**Comment by gorillapower** [comment]
We also hit a blocker with this, are there plans to include it in the future? Are there any work arounds?

**Comment by SamVanhoutte** [comment]
@JoshLove-msft @fabiocav @liliankasem 

Any updates on this, please?  Almost three months now

**Comment by fabiocav** [comment]
Apologies for the delayed response here. 

We're working with the broader team and will provide updates here once we have more information.

**Comment by SamVanhoutte** [comment]
Thanks for the heads up , is there ANY broader timing we can consider?  As I'm now block in the migration to isolated worker (and have an issue with the previous runtime)

**Comment by fabiocav** [comment]
No concrete timeline at point. We will start breaking this issue down into different ones tracking more granular features as this is combining a few different things. As those things may land at different times, that would make it easier to keep folks updated and track progress.

**Comment by SamVanhoutte** [comment]
And mean while , we're getting notifications that we should migrate away from the in-process functions.  This is not making my team happy

**Comment by H-Finch-404** [comment]
> And mean while , we're getting notifications that we should migrate away from the in-process functions. This is not making my team happy

Exactly my thoughts. You can't force customers to move to a new version of a service when seemingly standard features of a component that interacts with ServiceBus are not yet implemented and have no ETA...

**Comment by gorillapower** [comment]
> And mean while , we're getting notifications that we should migrate away from the in-process functions. This is not making my team happy

Im afraid we share the same sentiment

**Comment by jacekkulis** [comment]
What a pity

**Comment by fabiocav** [comment]
I completely understand the frustration. Apologies for the conflicting messages. 

Since my last response, we've been working to prioritize these capabilities and the initial work will start in the current sprint/iteration. We still don't have a concrete ETA, but we'll be sharing progress and updating the extension with the capabilities as the work is completed.

I'll share the different issues once we have those defined (didn't want to wait for that before responding here).

@SamVanhoutte / @H-Finch-404 /  @gorillapower , something I want to clarify is that you can continue to use the in-proc model, which will soon have .NET 8 support, in the meantime. We have some information that might be help better understand the plans [here](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-march-2024-roadmap-update/ba-p/4097744). We wanted to make sure customers had time to comfortably migrate between models, and in-proc will continue to be supported until the EOL date of November 10th, 2026.

I hope this information is helpful. We'll be working to deliver on these blocking gaps as quickly as we can. Thank you for your patience!

**Comment by H-Finch-404** [comment]
@fabiocav Any updates or more precise ETA for this functionality? It has been half a year since this issue was reported.

**Comment by gorillapower** [comment]
Unfortunately, the solution for now seems to be use .NET 6 until these features make there way into, and hopefully in parity with, the isolated worker model. 

There's too much thats unsupported for isolated workers at the moment, ie) durable functions/entities.

**Comment by aishwaryabh** [comment]
Version 5.19.0 of the service bus worker extension is now available[ here](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ServiceBus) which supports `ServiceBusSessionMessageActions`! Thank you for your patience while we've been developing this.

**Comment by Archomeda** [comment]
@aishwaryabh Cool! I got a question however.
How should I clear a session after I'm done with it? The ServiceBus SDK allows (and actually recommends) to call `SetSessionStateAsync(null)`, and it was also possible to call with `null` in the in-process SDK. But the isolated extension SDK doesn't like me using `null` for this method.

**Comment by aishwaryabh** [comment]
Could you use[ `ReleaseSession` ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebussessionmessageactions.releasesession?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebussessionmessageactions-releasesession) to clear the session? Or do you specifically need to set the session state to null?

**Comment by H-Finch-404** [comment]
> Could you use[ `ReleaseSession` ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebussessionmessageactions.releasesession?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebussessionmessageactions-releasesession) to clear the session? Or do you specifically need to set the session state to null?

Releasing the session (= releasing lock) has nothing to do with clearing/removing session state.

**Comment by Archomeda** [comment]
@aishwaryabh As @H-Finch-404 mentioned, `ReleaseSession` is only meant for releasing the lock, and not clearing the state.

**Comment by arkiaconsulting** [comment]
@aishwaryabh Thanks for your work ! Any chance to get the `DeadLetterMessageAsync` soon as in the in-process model ?

**Comment by aishwaryabh** [comment]
I see. Since the scope of this issue is fulfilled, can you open a new issue with these additional feature requests? This will be easier to track on my end rather than responding to this issue, and I'll triage them on our backlog and pick up these items soon.

**Comment by christianroll** [comment]
I'm experiencing the same mentioned by @AnnejanBarelds . Migrating to isolated worker in net8.0 using the library `ServiceBusMessageActions` doesn't work properly. I need to use `DeadLetterMessageAsync` but raises the following exception: 

```
Exception while executing function: Functions.MessageBus_HandleSplashContractedCampaigns Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'.
```

Migrating without usage of ServiceBusMessageActions is fine, the servicebus trigger works  but has this limitation of not being able to use deadLetterMessageAsync...

**Comment by Kumar-Akshay** [comment]
Any chance to get the DeadLetterMessageAsync soon or any ETA for out-process model? @aishwaryabh

**Comment by nick-loader** [comment]
@aishwaryabh @fabiocav  as mentioned above `ServiceBusSessionMessageActions` is still missing implementations for `DeadLetterMessageAsync` and `CompleteMessageAsync`. Can you advise when these will be added?

**Comment by akakaule** [comment]
Any updates on this issue. Does not seem it's fully implemented yet.

**Comment by akakaule** [comment]
Also created https://github.com/Azure/azure-functions-dotnet-worker/issues/3150 with support for `ServiceBusReceiveActions `
