### ISSUE TITLE
`Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues` doesn't use `Workload Identity`

### ISSUE THREAD

**Issue by AlexPykavy** [Azure/azure-functions-dotnet-worker#2105]
We host Azure Functions isolated in AKS and have recently migrated from AAD Pod Identity to Workload Identity. However, after this change the function couldn't access Storage Account Queue with the following error:
```
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[1]
      DefaultAzureCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 5fd4e2bb-c30f-4a08-b831-b52e53499d1c
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[1]
      EnvironmentCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 5fd4e2bb-c30f-4a08-b831-b52e53499d1c
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[3]
      EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 5fd4e2bb-c30f-4a08-b831-b52e53499d1c Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[1]
      ManagedIdentityCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 5fd4e2bb-c30f-4a08-b831-b52e53499d1c
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[4]
      Probing IMDS endpoint for availability. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
←[40m←[32minfo←[39m←[22m←[49m: Azure.Identity[5]
      IMDS endpoint is available. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
←[40m←[32minfo←[39m←[22m←[49m: Azure.Core[1]
      Request [5fd4e2bb-c30f-4a08-b831-b52e53499d1c] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED&client_id=REDACTED
      Metadata:REDACTED
      x-ms-client-request-id:5fd4e2bb-c30f-4a08-b831-b52e53499d1c
      x-ms-return-client-request-id:true
      User-Agent:azsdk-net-Identity/1.4.0,(.NET 6.0.25; Linux 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023)
      client assembly: Azure.Identity
←[40m←[37mdbug←[39m←[22m←[49m: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Adding jobhost language worker channel for runtime: dotnet-isolated. workerId:1547cb39-27de-4f71-b670-e7867e9f747b
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Worker process started and initialized.
←[40m←[1m←[33mwarn←[39m←[22m←[49m: Azure.Core[8]
      Error response [5fd4e2bb-c30f-4a08-b831-b52e53499d1c] 404 Not Found (80.6s)
      X-Content-Type-Options:REDACTED
      Date:Wed, 29 Nov 2023 07:01:20 GMT
      Content-Type:text/plain; charset=utf-8
      Content-Length:275

←[40m←[1m←[33mwarn←[39m←[22m←[49m: Azure.Core[7]
      Response [5fd4e2bb-c30f-4a08-b831-b52e53499d1c] took 80.6s
```

As you can see it uses `User-Agent:azsdk-net-Identity/1.4.0,(.NET 6.0.25; Linux 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023)` and after some digging I have probably found why. The reason for this is that the `Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues` [references `Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.0`](https://github.com/Azure/azure-functions-dotnet-worker/blob/1808ec77becf834bb0a36ce09ab4ee182386e938/extensions/Worker.Extensions.Storage.Queues/src/Properties/AssemblyInfo.cs#L7C34-L7C92), which in turn references `Microsoft.Extensions.Azure 1.1.1`, which in turn references `Azure.Identity 1.4.0` which doesn't support Workload Identity.

**Comment by AlexPykavy** [comment]
It looks like upgrading `Microsoft.Azure.WebJobs.Extensions.Storage.Queues` to `5.1.3` helped despite the fact that it references `Azure.Identity 1.7.0` while the documentation [states that it has to be `Azure.Identity 1.9.0`](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#azure-identity-client-libraries)

**Comment by AlexPykavy** [comment]
One more finding: the token acquiring from the Azure Function succeeded because according to the logs, the `DefaultAzureCrential` pipeline successfully stopped at `ClientAssertionCredential` which was used by `TokenExchangeManagedIdentitySource`.

**Comment by soninaren** [comment]
The identity package has been upgraded now. In host as well as the storage extension.
