### ISSUE TITLE
Upgrading Microsoft.Azure.Functions.Worker.Sdk from 1.15.0 to 1.16.2 breaks my runtime: No job functions found

### ISSUE THREAD

**Issue by ticedev-1972** [Azure/azure-functions-dotnet-worker#2107]
### Discussed in https://github.com/Azure/azure-functions-dotnet-worker/discussions/2106

<div type='discussions-op-text'>

<sup>Originally posted by **ticedev-1972** November 29, 2023</sup>
Running in debug on my dev machine with

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

Results with 1.15.0 I get:

[2023-11-29T11:00:01.005Z] Loading functions metadata
[2023-11-29T11:00:01.012Z] Reading functions metadata (Host)
[2023-11-29T11:00:01.020Z] 0 functions found (Host)
[2023-11-29T11:00:01.059Z] Reading functions metadata (Custom)
[2023-11-29T11:00:01.174Z] 2 functions found (Custom)
[2023-11-29T11:00:01.192Z] 5 functions loaded

...but with 1.16.2 I get:

[2023-11-29T10:55:59.472Z] Loading functions metadata
[2023-11-29T10:55:59.475Z] Reading functions metadata (Host)
[2023-11-29T10:55:59.479Z] 0 functions found (Host)
[2023-11-29T10:55:59.481Z] Reading functions metadata (Custom)
[2023-11-29T10:55:59.482Z] 1 functions found (Custom)
[2023-11-29T10:55:59.485Z] 0 functions loaded
[2023-11-29T10:55:59.512Z] Generating 0 job function(s)
[2023-11-29T10:55:59.547Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

I tried up/downgrading several times. Results are very persistent. Is there anything else I need to do ?

this is my main:

    public static async Task Main()
    {
        var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults(builder =>
            {
                builder
                    .AddApplicationInsights()
                    .AddApplicationInsightsLogger();
            })
            .ConfigureAppConfiguration((hostContext, config) =>
            {
                config.AddJsonFile("host.json");
                config.AddEnvironmentVariables();
                config.Build();
            })
            .ConfigureServices(
                (hostContext, services) =>
                {
                    services.AddTransient((s) => { return hostContext.Configuration; });
                    services.AddTransient<IAppConfiguration, AppConfiguration>();
                    services.AddTransient<IBlobStorageRepository, BlobStorageRepository>();
                    services.AddTransient<IBlobStorageClientFactory, BlobStorageClientFactory>();
                    services.AddTransient<IDocumentFilter, CustomDocumentFilter>();
                })
            .Build();

        var loggerFactory = host.Services.GetService<ILoggerFactory>()!;
        CustomDocumentFilter.Logger = loggerFactory.CreateLogger<CustomDocumentFilter>();

        await host.RunAsync();
    }

And this is my function handler signature:

    [Function(nameof(RequestHandler))]
    [OpenApiOperation(
        operationId: nameof(RequestHandler),
        Summary = "Get data generically",
        Description = "Get data generically",
        Visibility = OpenApiVisibilityType.Important)]
    [OpenApiResponseWithBody(
        statusCode: HttpStatusCode.NotFound,
        contentType: FunctionConstants.JsonContentType,
        bodyType: typeof(ProblemDetails),
        Summary = "No data found",
        Description = "Data could not be found")]
    [OpenApiResponseWithBody(
        statusCode: HttpStatusCode.InternalServerError,
        contentType: FunctionConstants.JsonContentType,
        bodyType: typeof(ProblemDetails),
        Summary = "Error while retrieving the data",
        Description = "Error while attempting to retrieve the data")]
    public HttpResponseData Handle(
        [HttpTrigger(AuthorizationLevel.Function, "get", Route = "{name}")]
        HttpRequestData request,
        string name)
    {
        var response = request.CreateResponse();
        response.Headers.Add("Content-Type", "application/json");
... etc ...

</div>

**Comment by kshyju** [comment]
@ticedev-1972 Are you seeing the issue when running locally as well? Or just when deployed to azure? What SKU/platform are you deploying? Have you tried the mitigation mentioned [here ](https://github.com/Azure/azure-functions-dotnet-worker/issues/2070#issuecomment-1816945300)?

**Comment by morrisonbrett** [comment]
Sorry, but I have to say it's pretty irresponsible to introduce a breaking runtime like this. Build a better testing suite on Azure to prevent this from happening in the future, please.

**Comment by ticedev-1972** [comment]
My findings are local. My app isn't unfinished and I haven't deployed it yet.

**Comment by ticedev-1972** [comment]
> @ticedev-1972 Are you seeing the issue when running locally as well? Or just when deployed to azure? What SKU/platform are you deploying? Have you tried the mitigation mentioned [here ](https://github.com/Azure/azure-functions-dotnet-worker/issues/2070#issuecomment-1816945300)?

Using that appsetting Name: AzureWebJobsFeatureFlags Value: EnableWorkerIndexing did not help. Still the same error...

**Comment by kshyju** [comment]
@ticedev-1972 I am unable to repro your issue when tried with the code you shared above. Could you please share a **_minimal repro_** of this issue so that we can take a closer look? A link to a GitHub repo would be great. Thank you!

**Comment by kshyju** [comment]
@morrisonbrett Appreciate your feedback! Our aim is to provide the best experience for azure functions developers. If you've encountered the "No job functions found" issue, we're eager to address it. Please create a new issue, including specific details about your problem and a minimal repro if feasible. Your cooperation helps us investigate and resolve the issue promptly. Thank you for your understanding!

**Comment by ticedev-1972** [comment]
> @morrisonbrett Appreciate your feedback! Our aim is to provide the best experience for azure functions developers. If you've encountered the "No job functions found" issue, we're eager to address it. Please create a new issue, including specific details about your problem and a minimal repro if feasible. Your cooperation helps us investigate and resolve the issue promptly. Thank you for your understanding!

**Comment by ticedev-1972** [comment]
Sorry, accidently closed the issue... reopening now. 
@kshyju I'll try to get you a repro, but it may take some time. My code is by no means public, so I have to isolate the problematic part from the rest.

**Comment by joshcomley** [comment]
Having the same issue here, hosting v4 .NET 7 functions in IIS with the latest Azure Functions runtime

**Comment by morrisonbrett** [comment]
> @morrisonbrett Appreciate your feedback! Our aim is to provide the best experience for azure functions developers. If you've encountered the "No job functions found" issue, we're eager to address it. Please create a new issue, including specific details about your problem and a minimal repro if feasible. Your cooperation helps us investigate and resolve the issue promptly. Thank you for your understanding!

Yes, I encountered the same 'No job functions found'. Adding the feature flag AzureWebJobsFeatureFlags/EnableWorkerIndexing alleviated it.

Repo is not that big if you want to clone and deploy yourself in an Azure test harness to try and repro, go for it: https://github.com/TrueVote/TrueVote.Bot

**Comment by morrisonbrett** [comment]
Throughout my career, I've always been one to upgrade all package libraries and dependencies and set an example for teams. I've managed to adopt the aggressive method. Most of the time it works out for the better - new features, performance improvements, bug fixes, security fixes, but _sometimes_, there's a regression, and those times make you question yourself and your approach. This is one of those times.

**Comment by kshyju** [comment]
> > @morrisonbrett Appreciate your feedback! Our aim is to provide the best experience for azure functions developers. If you've encountered the "No job functions found" issue, we're eager to address it. Please create a new issue, including specific details about your problem and a minimal repro if feasible. Your cooperation helps us investigate and resolve the issue promptly. Thank you for your understanding!
> 
> Yes, I encountered the same 'No job functions found'. Adding the feature flag AzureWebJobsFeatureFlags/EnableWorkerIndexing alleviated it.
> 
> Repo is not that big if you want to clone and deploy yourself in an Azure test harness to try and repro, go for it: https://github.com/TrueVote/TrueVote.Bot

@morrisonbrett I forked the app you shared above and was able to run it locally using Visual studio without any issues.
The only additional thing I had to do was to add a `local.settings.json` file to the project where I could define the service bus connection string and the queue name.

<img width="890" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/f63e3b51-75cc-4715-a231-5a502d702877">

If you are still experiencing issues, please open a new GH issue with relevant details specific to your issue and a repro app where we can reproduce the error and we are happy to take a look. Thanks for understanding.

**Comment by morrisonbrett** [comment]
> > > @morrisonbrett Appreciate your feedback! Our aim is to provide the best experience for azure functions developers. If you've encountered the "No job functions found" issue, we're eager to address it. Please create a new issue, including specific details about your problem and a minimal repro if feasible. Your cooperation helps us investigate and resolve the issue promptly. Thank you for your understanding!
> > 
> > 
> > Yes, I encountered the same 'No job functions found'. Adding the feature flag AzureWebJobsFeatureFlags/EnableWorkerIndexing alleviated it.
> > Repo is not that big if you want to clone and deploy yourself in an Azure test harness to try and repro, go for it: https://github.com/TrueVote/TrueVote.Bot
> 
> @morrisonbrett I forked the app you shared above and was able to run it locally using Visual studio without any issues. The only additional thing I had to do was to add a `local.settings.json` file to the project where I could define the service bus connection string and the queue name.
> 
> <img alt="image" width="890" src="https://private-user-images.githubusercontent.com/144469/287091173-f63e3b51-75cc-4715-a231-5a502d702877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODQ5NTAsIm5iZiI6MTcwMTM4NDY1MCwicGF0aCI6Ii8xNDQ0NjkvMjg3MDkxMTczLWY2M2UzYjUxLTc1Y2MtNDcxNS1hMjMxLTVhNTAyZDcwMjg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQyMjUwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzUwMzk5YThiZWIxMGI3Yzk0OGYwODgxZDQ2ZGMxMDdhNjQ0OTU3MWMzYTg0NTFmOWM5OTI0MTIyMjRmNzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.diJuLYbeFl_TH1ekaDdf7OVkULIMIH8csgi0qBIxvP8">
> If you are still experiencing issues, please open a new GH issue with relevant details specific to your issue and a repro app where we can reproduce the error and we are happy to take a look. Thanks for understanding.

Yep, runs great locally. On Azure, however, it fails without the feature flag setting added.

**Comment by kshyju** [comment]
@ticedev-1972 No worries. If you can create a minimal repro app and share the link to your GH repo, I am happy to validate that on my side. Thanks!

**Comment by ticedev-1972** [comment]
Ok, found a spare hour ;-) Here it is:
https://github.com/ticedev-1972/Repro

First see the project run, then reproduce the failure...

- get, build, run & validate it works like this:
- browse to http://localhost:7068/api/whatever_we_want
- receive:
{
    "Name": "whatever_we_want"
}

Now the repro:

- update package Microsoft.Azure.Functions.Worker.Sdk to 1.16.3 (yesterday it was 1.16.2, but it still fails)
- run and it will build fine but crash with two distinct symptoms:
1. no Functions found in the console runner
2. A visual studio popup message saying: "Failed to launch functions process ..."

**Comment by kshyju** [comment]
@ticedev-1972 Thank you! I downloaded your project and was able to run it locally without any issues.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/0c505267-2550-475d-996f-829573a09acf)

The only additional thing I did was to add a minimal local.settings.json file and updated it's properties so that it gets copied to the output folder.

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
  }
}
```

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/caf8bcdf-998d-4ed1-8f3f-d9e446d8d055)

Can you check your core tools version is latest (It should be printed at the top of the debug terminal window). Mine looked like below.

> Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

If you do not see the latest version of core tools, can you make sure you explicitly download them using the steps mentioned [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/2091#issuecomment-1824814196)
