### ISSUE TITLE
Isolated Model - HttpTrigger not executed after migration to isolated/dotent8

### ISSUE THREAD

**Issue by middiu** [Azure/azure-functions-dotnet-worker#2113]
Hello there, 

I have an Azure Function with >50 Http functions developed with dotnet6 and in-process model, all the functions work fine, they have been in PROD for more than a year and everything works fine.

Now we finally decided to move to dotnet8 and Isolated Model. We followed all the steps mentioned in the [offical migration guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8), and now we are able to build and run the Az Func project, but none of the Http function is really working.

In the console we see that all Functions listed with the right routing and url:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/428032/66b3079f-3788-4d1a-8877-8e53569ab344)

All we see now in the logs when we try to call an HTTP GET API is this:
````
For detailed output, run func with --verbose flag.
[2023-11-30T22:26:13.564Z] Host lock lease acquired by instance ID '0000000000000000000000000F02CE3B'.
[2023-11-30T22:26:31.428Z] Executing 'Functions.VerticalsAPI' (Reason='This function was programmatically called via the host APIs.', Id=10be3d94-e6d5-42f8-88b1-75759a8a9366)

````

So **VerticalsAPI** is executed, but nothing happens after that, not exceptions or any other message.
Also, browser keeps waiting for a response.

What I noticed using VS debugger is that not even the Class costructure is being called, maybe some problem with dependency injections?

Is there anything you can suggest? any specific logging setting that could help us in troubleshooting or any clue?

Thanks and Regards

**Comment by middiu** [comment]
One more info:

I create a brand new HTTP Function in the same project, didn't change the default code at all but the problem is still the same:

````
public class MigrationTest
{
    private readonly ILogger _logger;

    public MigrationTest(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<MigrationTest>();
    }

    [Function("MigrationTest")]
    public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
    {
        _logger.LogInformation("C# HTTP trigger function processed a request.");

        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

        response.WriteString("Welcome to Azure Functions!");

        return response;
    }
}
````


![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/428032/6abdcf87-d05d-4af4-8c37-2d167df17406)

**Comment by kshyju** [comment]
@middiu Do you have the functions defined inside the same project/assembly as your function project? Or are they in another assembly which you are referencing in your function app project?

**Comment by middiu** [comment]
> @middiu Do you have the functions defined inside the same project/assembly as your function project? Or are they in another assembly which you are referencing in your function app project?

in the same project
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/428032/6fab2253-a4d5-40f1-a4fc-9721c55b3f52)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/428032/28f2e379-6075-4e44-af60-535532c62a6a)

**Comment by kshyju** [comment]
Based on the code you shared, It should work. Can you please compare your project to [this minimal .NET8 function app](https://github.com/kshyju/MoreDotnetIsolatedSamples/tree/master/Net8SimpleHttpTrigger)? That should give you some ideas about what is missing. Let us know what you find.

**Comment by middiu** [comment]
Found the issues:

my host.json was containing some comment like:
````
"logLevel": {
		"Host.Results": "Information", //https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2
		"Host.Aggregator": "Information", //https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2
		"Function": "Trace", //https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2
		"Microsoft": "Error",
		"Default": "Error"
}
````

and it seems that dotnet8 doesn't it like anymore? As said, the same host.json file is perfectly working with dotnet6.
Once I fixed that I started seeing the logs and fix any other code related issue, and now the function apps are working fine.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/428032/9a6f900f-844f-4346-ae5f-5b174be8c19b)

**Comment by kshyju** [comment]
The stack trace where the error is being thrown is from STJ. You need to check STJ docs page to see whether that behavior changed in .NET8.

Glad your issue is resolved. Closing this issue. Thank you!

**Comment by kolexinfos** [comment]
I am having exactly the same issue as on this thread did not want to open another thread so people who have this can leverage the information shared here in one place.

So I have **.Net6 InProcess** Azure Function that I upgraded to **.Net8 Isolated** after updating all the packages as advised here in the [Migration Guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8#upgrade-your-function-app-in-azure), the project builds successfully and when I run all the Functions are listed as running.

![Screenshot 2024-02-13 190553](https://github.com/Azure/azure-functions-dotnet-worker/assets/1893821/7a814f16-dce6-4d38-8057-9bb90fb2bbfa)


When I run locally all Functions start and TimerTrigger shows it is being triggered but does nothing(breakpoints do not get hit), when I call the HttpTriggers from Postman it runs for a while and then returns 500 and in console shows the below.

When deploy to Azure the functions warmup task throws the below error and some other functions throw similar error and others do not run at all.

> Exception while executing function: Functions.warmup The invocation request with id 'f0e519af-df7e-4598-9e66-b73a163a7850' was canceled before the request was sent to the worker. A task was canceled.

**Comment by perfectphase** [comment]
I've had the same problem, in my case I tracked it down to bad config in my host.json.  For me I had some old configuration for service bus triggers, taking that out allowed the HttpTrigers to run again.
