### ISSUE TITLE
Broken WorkerExtensionStartupCodeExecutor generation when FunctionsApp referenced by XUnit test project.

### ISSUE THREAD

**Issue by lukehanlon** [Azure/azure-functions-dotnet-worker#2114]
When referencing a function app by an XUnit test project (may happen in other ways as well) the namespace does not get generated correctly. The error shows up against the test project. This happens on the latest version of https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.3

I would share my solution but its proprietary so I can't, rolling back to the immediate previous version (1.16.2) fixed the issue for me, should be easy enough to work out what caused this..

Below is what was generated.

[assembly: WorkerExtensionStartupCodeExecutorInfo(typeof(.WorkerExtensionStartupCodeExecutor))]

namespace 
{
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkerExtensionStartupCodeExecutor : WorkerExtensionStartup
    {
        /// <summary>

**Comment by Hubert-Rybak** [comment]
Looks like namespaceValue is null here:

https://github.com/Azure/azure-functions-dotnet-worker/blob/5ff83ce0fdf244536cea093686540b424dbfc1ea/sdk/Sdk.Generators/ExtensionStartupRunnerGenerator.cs#L94-L98

https://github.com/Azure/azure-functions-dotnet-worker/blob/5ff83ce0fdf244536cea093686540b424dbfc1ea/sdk/Sdk.Generators/FunctionsUtil.cs#L81-L89

"Constants.BuildProperties.GeneratedCodeNamespace" is not found in GeneratorExecutionContext

**Comment by RobARichardson** [comment]
Having the same issue with an NUnit Test Project as well.

**Comment by mattchenderson** [comment]
Hi all - can we get a few additional details on the repro setup? It would be good to know what namespaces are used in which project, how they differ, etc. Can we also get confirmation of the project relationships (how referenced) and project settings, such as .NET version, etc.?

**Comment by Pieeer1** [comment]
> Hi all - can we get a few additional details on the repro setup? It would be good to know what namespaces are used in which project, how they differ, etc. Can we also get confirmation of the project relationships (how referenced) and project settings, such as .NET version, root namespace, etc.?

Not the OP, but having the same issue. My projects are structured as: 

Function App with my functions with the following namespace: 

namespace Project.Functions;

then a Xunit project that references it, with a namespace:

Project.Tests.Functions;

**Comment by kshyju** [comment]
Thanks for the feedback. We were able to reproduce the issue and will investigate this. I will share an update here as we make progress. Until then please use 1.16.2 to mitigate the issue. Thank you for your understanding and cooperation.

**Comment by kshyju** [comment]
We Identified the root cause of the issue. This was an old issue which is uncovered in 1.16.3. Our source generator is being executed in the context of the test project and it fails to produce the correct code due to lack of certain msbuild properties.

While we are working on getting a fix out, you can mitigate the issue by adding the below code snippet  inside the `Project` element of your `.csproj` file.

```xml
<PropertyGroup>
  <FunctionsGeneratedCodeNamespace>GiveAnyValueYouWantToGiveHere</FunctionsGeneratedCodeNamespace>
</PropertyGroup>
<ItemGroup>
  <CompilerVisibleProperty Include="FunctionsGeneratedCodeNamespace" />
</ItemGroup>
```
Ideally it should not run in the context of the test functions. That is the fix we are making and hoping to have this fix out early next week.

**Comment by jviau** [comment]
@lukehanlon you can work around this by add `PrivateAssets="all"` to the SDK package reference

``` XML
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="..." PrivateAssets="all" />
```

**Comment by kshyju** [comment]
@lukehanlon We have released a new version of the Microsoft.Azure.Functions.Worker.Sdk which fixes this issue. Could you please upgrade to that version?

https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.4-preview1

**Comment by jimmystridh** [comment]
> @lukehanlon We have released a new version of the Microsoft.Azure.Functions.Worker.Sdk which fixes this issue. Could you please upgrade to that version?
> 
> [nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.4-preview1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.4-preview1)

this solved the issue for me
