### ISSUE TITLE
.NET 8 Function project template has critical vulnerability out of the box

### ISSUE THREAD

**Issue by CamiloTerevinto** [Azure/azure-functions-dotnet-worker#2115]
The .NET 8 project template has a dependency on System.Drawing.Common version 4.7.0 which has a critical vulnerability assigned: https://github.com/advisories/GHSA-rxg9-xrhp-64gj

This can be fixed by updating dependencies to versions of .NET >= 6.0, which transitively remove the reference the the vulnerable version. 

From what I could see:

1. System.Drawing.Common 4.7.0 is referenced by System.Windows.Extensions 4.7.0.
2. System.Windows.Extensions 4.7.0 is referenced by System.Security.Permissions 4.7.0
3. System.Security.Permissions 4.7.0 is referenced by System.Configuration.ConfigurationManager 4.7.0
4. System.Configuration.ConfigurationManager 4.7.0 is referenced by System.Diagnostics.PerformanceCounter 4.7.0
5. System.Diagnostics.PerformanceCounter 4.7.0 is referenced by Microsoft.ApplicationInsights.PerfCounterCollector 2.21.0
6. Microsoft.ApplicationInsights.PerfCounterCollector 2.21.0 is referenced by Microsoft.Azure.Functions.Worker.ApplicationInsights 1.1.0
7. Microsoft.Azure.Functions.Worker.ApplicationInsights comes installed by default

Can we either obtain a new version of `Microsoft.Azure.Functions.Worker.ApplicationInsights` or update the project template to explicitly depend on newer versions of `System.Diagnostics.PerformanceCounter`? 

Users shouldn't have to remember to manually update transitive dependencies with critical vulnerabilities.

**Comment by CamiloTerevinto** [comment]
For users: just manually installing `System.Diagnostics.PerformanceCounter` version 6.0.0 or later is enough to remove the vulnerable dependency.

**Comment by fabiocav** [comment]
Thank you for reporting, @CamiloTerevinto . We'll have this updated, released and templates changed.

**Comment by fabiocav** [comment]
Removing security related report.

All issues have been addressed. For guidance on how to report similar issues in the future, please see https://github.com/Azure/azure-functions-dotnet-worker/security/policy

Thank you.
