### ISSUE TITLE
Is ASP.NET Core integration supported with Microsoft.Azure.Functions.Worker.Extensions.OpenApi ? 

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2117]
It's a duplicate of https://github.com/Azure/azure-functions-openapi-extension/issues/628, but that project seems to be no longer mantained, and could not find any relevant documentation on this topic.

So as the title says,  is the ASP.NET Core integration using `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` nuget in .Net 8 worker supported with `Microsoft.Azure.Functions.Worker.Extensions.OpenApi` package?

Thanks

**Comment by satvu** [comment]
This should be supported with the latest version of `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` (>= `1.2.0`) which resolved a forwarder header bug affecting integration with OpenApi. 

We have not validated these two packages on our end very recently, but we are not aware of any other new issues currently.

**Comment by davidpetric** [comment]
> This should be supported with the latest version of `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` (>= `1.2.0`) which resolved a forwarder header bug affecting integration with OpenApi.
> 
> We have not validated these two packages on our end very recently, but we are not aware of any other new issues currently.

The issue indeed did go away when I updated to the latest Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore
