### ISSUE TITLE
Support for testing http triggers with Microsoft.AspNetCore.Mvc.Testing

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2120]
Hi,

Now that there is `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore` package is there any plans to support testing  `HttpTrigger`s using the  `Microsoft.AspNetCore.Mvc.Testing`  NuGet and `WebApplicationFactory<>` ?

**Comment by fabiocav** [comment]
Hey @davidpetric the integration still leverages the Functions programming model and the plan is to introduce a test framework, similar to `Microsoft.AspNetCore.Mvc.Testing`, but compatible with the trigger/binding model in Functions. 

We have an issue tracking this here #281 , so I'll close this one in favor of that, but let us know if you have any questions or concerns.
