### ISSUE TITLE
Enhance in-process to isolated migration guide to mention that extensions/bindings are not supported to be configured from sources

### ISSUE THREAD

**Issue by gmanvel** [Azure/azure-functions-dotnet-worker#2123]
Following [in-process to isolated migration guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8#upgrade-your-function-app-in-azure) I changed our Azure function to isolated mode, but was facing the issue described in #1437.
It would be nice to update the migration guide to mention that bindings configured from other sources (Azure App Configuration/Key Vault) are not supported and need to be changed as part of a migration.

**Comment by mattchenderson** [comment]
A callout has been added to all of our migration guides and the isolated worker model guide itself. Thank you for providing this feedback!
