### ISSUE TITLE
Unable to load Function, a function with the id already exists.

### ISSUE THREAD

**Issue by smoothstill** [Azure/azure-functions-dotnet-worker#2124]
I have a queue trigger function that receives events from a queue storage, and the function execution sometimes fails with an error message:

```Result: Failure Exception: System.InvalidOperationException: Unable to load Function '[Function name]'. A function with the id '[Function id]' name already exists. at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62 at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269```

Basically I have a system topic that is subscribed to "BlobCreated" events in a blob container, which sends the events to the queue storage and those events are then handled by the queue trigger function.

After I upload items to the blob container (100 or less at a time), the function works fine for a while until this error starts occurring. What could possibly cause this error and what does it mean exactly?

I am using these package versions:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.3" />
`````

host.json:
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    },
    "extensions": {
        "queues": {
            "batchSize": 2,
            "newBatchThreshold": 1,
            "maxDequeueCount": 1,
            "messageEncoding": "base64"
        }
    }
}
```

Program.cs (with business logic removed):

```
using Microsoft.Extensions.Azure;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((services) =>
    {
		... services here
    })
    .Build();

host.Run();
```

Function looks like this:
```
[Function("HandleData")]
public async Task Run([QueueTrigger("data-queue")] BlobEvent input)
{
    ...handle data
}
```

There are no other functions in the Function App

**Comment by kshyju** [comment]
@OneThatWalks See https://github.com/Azure/azure-functions-dotnet-worker/issues/2114#issuecomment-1840088691

**Comment by OneThatWalks** [comment]
@kshyju That worked!

**Comment by OneThatWalks** [comment]
Now I can say with 1.16.4 preview release I get the above error in Azure

```
Result: Failure Exception: System.InvalidOperationException: Unable to load Function '[Removed]'. A function with the id '3303995438' name already exists. at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62 at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269 Stack: at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62 at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
```

**Comment by kshyju** [comment]
@smoothstill Can you share your function app name and region and I can take a closer look at what is going on.

**Comment by kshyju** [comment]
> I can share one if needed

Yes please. Thank you!

**Comment by OneThatWalks** [comment]
alarmprocessorbluepillargeneraldev2eastus in East US

**Comment by smoothstill** [comment]
> @smoothstill Can you share your function app name and region and I can take a closer look at what is going on.

omavoima-meterdata-integrations-staging, North Europe

**Comment by vishalvatsal** [comment]
Having same issue. Except the trigger is Service bus queue

`Exception while executing function: Functions.negotiate Result: Failure
Exception: System.InvalidOperationException: Unable to load Function 'negotiate'. A function with the id '1361790475' name already exists.
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
Stack:    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269 `
   
   
  `<ItemGroup>
		<PackageReference Include="Correlate" Version="5.2.0" />
		<PackageReference Include="Correlate.AspNetCore" Version="5.2.0" />
		<PackageReference Include="Correlate.DependencyInjection" Version="5.2.0" />
		<PackageReference Include="IdentityModel" Version="6.2.0" />
		<PackageReference Include="MassTransit.WebJobs.ServiceBus" Version="8.1.2" />

		<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventGrid" Version="3.4.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.14.1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.3" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.1.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Seq.Extensions.Logging" Version="6.1.0" />
	</ItemGroup>`

**Comment by jackbatzner** [comment]
I am experiencing this locally after upgrading our services to 1.16.* and later. I can get things to work correctly if I disable the worker indexing, `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>` .

Would really love to upgrade to the latest packages and take advantage of the worker indexing and placeholder benefits. Let me know what information I can provide!

**Comment by Strandfelt** [comment]
Any updates on this? We are seeing this really often. Quite frustrating to have an environment this unstable with .NET 8.

**Comment by demiliani** [comment]
This is happening also in .NET 7:
<img width="1023" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/33155438/39e526cf-09b6-4b90-b0d8-4fbbfc4b016f">

**Comment by jackbatzner** [comment]
Any update on this @fabiocav ? This is blocking our teams from migrating to the latest SDK version and consuming the performance improvements.

**Comment by smackodale** [comment]
We are experiencing the same issue. We have just upgraded from .NET 6 (in-process) to .NET 8 (isolated) and we are experiencing the issue of `Unable to load Function 'FUNCTION_NAME'. A function with the id '123' name already exists`
When the function app is restarted it works for a period but then starts to fail with the above message. This is across all of our triggers on all functions on the App:
* Timer
* Service Bus
* HTTP

Adding `<FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>` does resolve the issue however this seems more like a work around then a fix.

**Comment by jackbatzner** [comment]
> Adding <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing> does resolve the issue however this seems more like a work around then a fix.

Second this statement @smackodale. Is there any progress on this item?

**Comment by fabiocav** [comment]
@soninaren is actively investigating this. We'll share more information here once that becomes available.

**Comment by sabbiryan** [comment]
Having the same issue after deployment, where locally it's perfectly works fine. In my case this is the following error details.

Result: Failure Exception: System.InvalidOperationException: Unable to load Function 'FnDevopsSyncProjectWorkItems'. A function with the id '2023509007' name already exists. at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62 at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269 Stack: at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62 at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269

**Comment by Strandfelt** [comment]
Seeing this issue again for a .NET 8 isolated function in West Europe

```
Exception while executing function: Functions.REDACTED Result: Failure
Exception: System.InvalidOperationException: Unable to load Function 'REDACTED'. A function with the id '2444048646' name already exists.
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
Stack:    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269 
```

**Comment by preetiduhan** [comment]
we are using .net 8 and seeing below error.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/18114323/0bf7a39c-ca1f-4a18-8d21-2b3a6c0c6583)

Although as workaround we downgrading azure functions worker sdk to 1.15.1 and it resolved the issue.

**Comment by mtopolski** [comment]
I can repro this on demand injecting a singleton that takes a few seconds instantiate. Without the expensive DI I don't see this issue. @preetiduhan I only wish I had seen your comment sooner, this workaround is working for me and I am deeply grateful. Better 3 hours deep into chasing ghosts than never.

**Comment by kshyju** [comment]
@preetiduhan / @mtopolski  This fix for this issue is available from host version 4.33.0 onwards. What version of core tools/host runtime are you seeing the issue with?

**Comment by kolexinfos** [comment]
I am running latest Azure Function Core Tools locally 4.0.5611 and I am still seeing this issue.

**Comment by luisgmgouveia** [comment]
Core Tools Version: 4.0.5611 
Function Runtime Version: 4.31.1.22191

I'm using .NET 8 in the Isolated Model and I can also reproduce it locally with a rather basic setup.

Any news? It's been almost half a year since this bug was initially reported.

**Comment by luisgmgouveia** [comment]
I believe @kshyju provided the answer to this problem. He says it would be fixed by installing the host version 4.33.0.

I'm using 4.31.1, and I was hoping that by installing the latest Core Tools Version (4.0.5611) I'd get the latest host version (which by the way it is 4.33.2 now: [Azure Functions Host Versions](https://github.com/Azure/azure-functions-host/releases)

Unfortunately that's not the case. Even though I have the latest Core Tools Version, when I launch my .NET 8 Isolated Process, Http Triggered Azure Function, I still see the old 4.31.1 host runtime:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/57350126/0e3b43d5-02ce-47d0-a8d2-a68aeadc5234)

I believe the problem is that the Azure Functions Core Tools were released a month ago:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/57350126/595a34b0-62ba-4be2-94f9-a9f7f3dc7e2e)
[Azure-Functions-Core-Tools](https://www.npmjs.com/package/azure-functions-core-tools?activeTab=readme)

And by that time, the host runtime latest version was indeed the one I have (4.31.1):
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/57350126/1d476b88-18c7-4900-ba86-121e5452ce37)
[Azure Functions Host Releases](https://github.com/Azure/azure-functions-host/releases)

**What can I do to make the Azure Functions Core Tools use the latest host version before its next release?**

I tried the following without luck:
- [Pinning to a specific version](https://learn.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal&pivots=platform-linux#manual-version-updates-on-linux)

PS: By the way, it seems the Core Tools were already updated to the latest version (4.33.2):
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/57350126/55f479e5-02b5-4db3-896a-7c3552db06aa)
[azure-functions-core-tools - PR 3646](https://github.com/Azure/azure-functions-core-tools/pull/3646)


but the latest release still dates from a month ago...

**Comment by geidans** [comment]
My version is "Function Runtime Version: 4.34.1.22669" and I still have the same issue. Functions are on v4 isolated and .net 8.0. Starting from a CLI "func start".

**Comment by imranshams** [comment]
> My version is "Function Runtime Version: 4.34.1.22669" and I still have the same issue. Functions are on v4 isolated and .net 8.0. Starting from a CLI "func start".

Same issue as well

**Comment by EvenC-tw** [comment]
Any updates?

**Comment by GrantVicich** [comment]
Any updates?

**Comment by PixelatedCaptain** [comment]
having this exact issue as well. the below version and runtime version are the latest stable at the time of writing this. Do we have any update on this or a work around that actually works? Even if it means less auto implemented logging or what not.

Core Tools Version:       4.0.7030 Commit hash: N/A +bb4c949899cd5659d6bfe8b92cc923453a2e8f88 (64-bit)
Function Runtime Version: 4.1037.0.23568

**Comment by ckarcz** [comment]
if you have 
```
var host = builder.Build();
await host.RunAsync();
```

try to change it to
```
var host = builder.Build();

host.Run();
```

that oddly worked for me after comparing two different function projects. one that had the issue and one that did not...

**Comment by vitaliiopticom** [comment]
I'm facing the same issue with service bus trigger and timer trigger.

```
Azure Functions Core Tools
Core Tools Version:       4.0.6610 Commit hash: N/A +0d55b5d7efe83d85d2b5c6e0b0a9c1b213e96256 (64-bit)
Function Runtime Version: 4.1036.1.23224
```

```
Microsoft.Azure.Functions.Worker (2.0)
Microsoft.Azure.Functions.Worker.Extensions.Timer (4.3.1)
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus (5.23)
```

```
[2025-06-30T21:29:00.008Z] Executed 'Functions.LeadUnlockerTimerJob' (Failed, Id=71f26efb-3ed6-4a96-8e1f-697edb7301aa, Duration=3ms)
[2025-06-30T21:29:00.008Z] System.Private.CoreLib: Exception while executing function: Functions.LeadUnlockerTimerJob. System.Private.CoreLib: Result: Failure
[2025-06-30T21:29:00.008Z] Exception: System.InvalidOperationException: Unable to load Function 'LeadUnlockerTimerJob'. A function with the id '181265722' name already exists.
[2025-06-30T21:29:00.008Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
[2025-06-30T21:29:00.008Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2025-06-30T21:29:00.008Z] Stack:    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
[2025-06-30T21:29:00.008Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.

```

**Comment by PixelatedCaptain** [comment]
I ended up giving up on the Azure Functions Core Tools..... I just started working against Azure DB.....but then I also found that even my Azure DB on consumption tier with 100,000 free vCore compute seconds that there is a base level of compute used daily without any user interaction.... Once your free seconds are used up, if you choose to go beyond.... the base bill will be $10/day, yet Microsoft makes it sound like you wont pay anything if its not used by you... Which seems to be a lie... so now I am setting up an azure relay and working against an on-prem DB  and will get my function apps to communicate to On-prem using Hybrid connections within an App Service....Thanks for the clear as mud billing transparency Microsoft!
________________________________

**Comment by KBAtMicrosoft** [comment]
I'm still seeing this issue myself.

Using .NET8, Isolated Worker model, Azure Runtime version 4.1041.200.25360

**Comment by KasunKoswattha** [comment]
Why is this issue closed without a fix? I'm seeing this issue with .Net10

**Comment by tonykalok** [comment]
same case as @KasunKoswattha, keeps prompting errors, frustrating

**Comment by joshfry-rix** [comment]
Facing this issue with .NET 10, but it just randomly occurred when running locally. I was already using `host.Run()`, I've added `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>` to my csproj in hopes of not encountering it again.

**Comment by emragins** [comment]
I don't notice this as a comment, so putting it here for future people, possibly future-me:

This happened to me locally when I was hosting the function and running integration tests against it.  The integration tests re-built the function project triggering hot reloads -> Error about duplicate function.

Moving "Contracts" to a third shared assembly fixed it.
