### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Sdk 1.16.x  - Warning CS8785	Generator 'FunctionMetadataProviderGenerator' failed to generate source

### ISSUE THREAD

**Issue by skmonirul248** [Azure/azure-functions-dotnet-worker#2137]
```
Warning	CS8785	Generator 'FunctionMetadataProviderGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'	MyFunctions1 	C:\Users\xx\source\repos\MyFunctions1\MyFunctions1\MyFunctions1.csproj	1

```

**Comment by satvu** [comment]
Hi @skmonirul248 can you provide a minimal repro of your issue? What triggers and/or bindings are used in your app? What extension packages and versions are you using?

**Comment by kshyju** [comment]
@skmonirul248 Thanks for sharing your package references. Could you try using the latest version of [Microsoft.Azure.Functions.Worker.Sdk](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/) package? 

Also, unrelated - You do not need to explicitly add a package reference to `Microsoft.Azure.Functions.Worker.Grpc` package. It is a dependency of `Microsoft.Azure.Functions.Worker`.

**Comment by satvu** [comment]
Some of the extensions also need to be bumped up as they are lagging behind. I suggest checking all of them, but the ones that definitely need to be bumped as they may be leading to errors are:

- Timer to 4.3.0 (latest)
- ServiceBus to >= 5.10.0 (latest is 5.15)
