### ISSUE TITLE
Breaking Changes in Microsoft.Azure.Functions.Worker.Sdk >= v1.16.0 - No job functions found

### ISSUE THREAD

**Issue by jkdmyrs** [Azure/azure-functions-dotnet-worker#2143]
Not sure if this is an issue with this nuget or Visual Studio...

After upgrading `Microsoft.Azure.Functions.Worker.Sdk` from `v1.15.1` to `v1.16.x`, Azure Functions no longer run in Visual Studio. I receive a "No job functions found" error.

This issue appears to only impact running the functions locally within VS. When the functions are deployed to Azure, they run successfully.

Visual Studio Version: `17.8.3`
.net SDK Version: `7.0.109`

Screenshot from `v1.15.1`:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/22627705/757e7869-9a7c-4edf-9caf-01e1a0a4090e)

Screenshot from `v1.16.0` and up:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/22627705/edfba559-b9ed-4679-9c99-79385300a666)

**Comment by jkdmyrs** [comment]
Please let me know if there is any additional information I can provide.

**Comment by jkdmyrs** [comment]
I will report back in a few days. Thanks.

**Comment by brunomoura-dev** [comment]
This problem still persists even in version 1.16.4.
Any updates on this?

**Comment by brunomoura-dev** [comment]
One more observation point. On Mac it works normally. This error has been appearing on Linux and Windows.

**Comment by satvu** [comment]
@brunomoura-dev Thanks for the additional info - is the workaround not fixing your scenario? What core-tools version are you using?

**Comment by jkdmyrs** [comment]
Can we reopen this? It's the holidays and I have not had time to create a reproduction or try workarounds.

**Comment by brunomoura-dev** [comment]
@satvu eu estou trabalhando com a versão 1.15.1, realizei o downgrade, pois de fato, não funcionou!

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/28134010/e3232ba9-cbf7-4889-b977-2b60f85e9535)

**Comment by jkdmyrs** [comment]
@satvu - things are working on my end now, even though I've made no changes to the code/local.settings.json, etc. 

My assumption is that the Azure Function Core Tools got updated alongside Visual Studio at some point, and that fixed things.

Anyone still having issues, try upgrading VisualStudio/Azure Function Core Tools and see if that helps.

**Comment by laazik** [comment]
having exact same issue (with latest visual studio 17.8.3), works with the actual func runtime, but debugging just does not work on visual studio and I'd be really curious to understand where the func tools of VS could be individually upgraded.

**Comment by mattchenderson** [comment]
Reopening. This should be resolved at this point, but agreed that the bot was overly aggressive here, and this should be explicitly confirmed for completion.

**Comment by jviau** [comment]
@brunomoura-dev I think you have a package authoring error in your csproj. Remove this package: `Microsoft.Azure.Functions.Extensions`

I think you can also remove `Microsoft.NETCore.Platforms`, but not exactly sure what that package does.

**Comment by jviau** [comment]
@mattchenderson what explicit confirmation are we wanting before closing this? Multiple individuals have reported being fixed after updating func core tools, so I think this may have been a mismatch between host and worker as we switched over to worker indexing.

**Comment by fabiocav** [comment]
Closing as it is reasonable to expect the issue has been resolved.

If you're running into a similar problem, please open an new issue and we'll investigate.
