### ISSUE TITLE
Breaking changes in Microsoft.Azure.Functions.Worker.Sdk 1.16.3+

### ISSUE THREAD

**Issue by etheone** [Azure/azure-functions-dotnet-worker#2146]
Build fails due to code generated by FunctionExecutorGenerator when functions inherits from abstract class with generic type parameters.

This works when using ``` Microsoft.Azure.Functions.Worker.Sdk ``` version ``` 1.16.2 ``` lower.

Repro here: https://github.com/etheone/abstract-functions-sample.

**Comment by etheone** [comment]
Either of the following additions to microsoft\azure-functions-dotnet-worker\sdk\Sdk.Generators\Extensions\IMethodSymbolExtensions.cs alone solves the problem in my case but having both might be a better idea.

Before line 24:
```
 if (methodSymbol.IsAbstract)
 {
     return FunctionMethodVisibility.NotPublic;
 }
```

Line 28:
```
if (containingType.DeclaredAccessibility != Accessibility.Public || containingType.IsGenericType)
```

**Comment by kshyju** [comment]
Does your app works when you go back to an older version (ex: 1.16.2 or 1.15.1), Not just build error, but when you run your app, does it work as expected?

**Comment by etheone** [comment]
I'm pretty sure it did work at one point. Unfortunately I don't have that specific version as I was experimenting a while ago. I can see if I can find the time to put it together again.

Obivously the abstract class is not the actual functions. The idea is to keep it in a nuget and use it in multiple services to quickly get up and running with crud functionality.

```
public class FooFunctions : CrudFunctions<FooCreate, Foo>
{
}
```

I updated my repro to reflect how it would look in reality. Even though I can't show an e2e invocation at this time I did expect this to work. I'd expect the functions in the abstract class to be ignore and just be discovered in an inherited class.

**Comment by kshyju** [comment]
Thanks for updating your repro. That helps understand what you were trying to do.
I see you are using Worker.Sdk version `1.11.0` in the repro. When I try to run your repro it still fails during function invocation. Are you able to tell me what version of Worker.Sdk was working fine for you?

I do not think this use case was ever working. But I have been wrong before. So let me know what version worked for you and then we can determine there was a regression introduced after that version. Thanks!
