### ISSUE TITLE
Recommendation for working with large Blobs via bindings?

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-dotnet-worker#215]
If I define my triggering blob as a Stream, the blob gets triggered but the data appears to be null. Then if I declare a BlobOutput and try to return the Stream object, it never gets written to the destination blob container. Assuming Stream is considered a rich binding, is there an alternative we will recommend for declaratively outputting large blobs in .NET 5 Functions?

Here are further details if needed.
The destination container exists in the same storage account, and no exception or error occurs.

Sample code snippet:
```
[Function("BlobTrigger1")]
[BlobOutput("destinationcontainer2/{name}", Connection = "AzureWebJobsStorage")]
public static Stream Run([BlobTrigger("test-samples2/{name}", Connection = "AzureWebJobsStorage")] Stream myBlob)
{
   return myBlob;
}
```

If I define my triggering blob as a string, and otherwise use the same code, the triggered blob gets written to the destination container.

The complete code is posted at the following locations in my GitHub repo:
- [Non-working Stream-based Function](https://github.com/gabesmsft/functionsnet5testing/blob/master/FunctionsNet5/BlobTrigger1.cs)
- [Working string-based Function](https://github.com/gabesmsft/functionsnet5testing/blob/master/FunctionsNet5/BlobTrigger2.cs)

**Comment by fabiocav** [comment]
Thank you, @gabesmsft 

The approach here is to use a `byte[]` for input and output. We're considering `Stream` support but that would be misleading as the entire stream would need to be read to memory, buffered and passed in and out. This is due to limitations with the OOP model, which does to support streamed requests and responses today.

**Comment by fabiocav** [comment]
To add, the goal is to eventually support proper streaming between the two, allowing for this to be properly surfaced

**Comment by gabesmsft** [comment]
Thanks @fabiocav , that makes sense. Byte[] isn't idle since the entire blob contents get loaded into memory, but glad there is the goal to eventually support streaming when using the OOP model.

**Comment by fabiocav** [comment]
Yeah, those are current OOP limitations and not specific to .NET (all OOP workers have the same behavior). We're intentionally keeping `Stream` out at this point so users are not confused when they realize that the entire stream is read/loaded, which would happen out output as well.
