### ISSUE TITLE
How do you disable a collection of trigger types when running in CI?

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2150]
Hi,

We are running the Azure Functions in the pipeline to generate an OpenApi/Swagger JSON spec which we import into APIM.

The problem is we have different trigger types: ServiceBus, EventGrid, etc, which try to make real connections to the network,

How can we disable let's say all ServiceBus or EventGrid triggers when running in CI?

**Comment by jviau** [comment]
I can't immediately think of a way to do this dynamically, but it could be done structurally. You could split your HTTP triggers into one class library, and then all others into a separate class library. Then have 2 function apps: one is your real prod app which references both class libraries. The 2nd is for CI only which only references the HTTP triggers library.
