### ISSUE TITLE
Function Failed Indexing - Unable to resolve value from configuration

### ISSUE THREAD

**Issue by mecombem** [Azure/azure-functions-dotnet-worker#2151]
Azure Functions Worker Runtime: **dotnet8-isolated**
Azure Functions Version:  **2.0**

Applicable Nuget packages
```xml
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="7.0.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.5.0" />
```

### Issue Description
I am trying to source configuration from Azure App Configuration and use the values in my CosmosDbTrigger parameters. I am using the isolated worker, coming from in-process. This used to work but now that I am using the isolated worker, the function fails indexing. It does not seem to see the values from App Configuration. 

App Configuration  added as a provider in using .ConfigureAppConfiguration
```c#
    var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureAppConfiguration(configBuilder =>
    {
        //connection variable omitted for brevity and security
        configBuilder.AddAzureAppConfiguration(connection);
    })
```

The in-process code used something like this but was in a Startup.cs file in the 

```c#
    public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
    {
        var config = builder.ConfigurationBuilder
            .AddEnvironmentVariables()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true);
        config.AddAzureAppConfiguration(connection);
        _config = config.Build();
    }
```

Sample function
```c#
[Function(nameof(SampleFunction))]
public async Task SampleFunctionAsync([CosmosDBTrigger(
    databaseName: $"%{Constants.CosmosDatabaseEnvName}%",
    containerName: $"%{Constants.SampleContainerNameEnvName}%",
    Connection = $"{Constants.CosmosConnectionEnvName}",
    LeaseContainerName = "leases",
    CreateLeaseContainerIfNotExists = true)] IReadOnlyList<JObject> documents
  )
```
...

### Expected Results
I am expecting that the string values in the static constants class will resolve to the key/value pair in Azure App Configuration. So, for example, 

```c#
public static class Constants
{
    public const string CosmosDatabaseEnvName = "my_cosmos_database"
}
```

Then in Azure App Configuration 

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/47511489/24f155a5-59ab-4f2e-973b-00e7d79417fc)

so that **the-acutal-database-name** would be used as the parameter value for **databaseName** and so on.

### Actual Results
*Actual function and variable names omitted/redacted
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/47511489/7ed15664-ad90-4aba-a141-72a48c71540d)

Any guidance or help you can provide would be greatly appreciated.

**Comment by mecombem** [comment]
I should note that I've been able to get the value if I add in the key/value pair in the Values section of my local.settings.json, simulating app settings. So, pulling from configuration using the enclosing % does work, just not from the Azure App Configuration config provider.

**Comment by clouddna-au** [comment]
Any idea how to use normal appsettngs.json? I am using this as this is what we used for prev .net 6 in-process functions but its not picking up configuration when running .net isolated process function v4

` .ConfigureAppConfiguration((hostContext, configApp) =>
 {
     configApp.AddJsonFile("appsettings.json", optional: true);
     configApp.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);
 })
  .ConfigureFunctionsWorkerDefaults()
   `

And then timer function

` [Function("SyncNoticesCron")]
 public async Task SyncNoticesCron(
 [TimerTrigger("%CronConfiguration:SyncNotices%")] TimerInfo timerInfo,
 [DurableClient] DurableTaskClient starter)`

**Comment by jviau** [comment]
The configuration you have pulled from Azure AppConfiguration is only available to the _worker_ process. It is not available to the functions runtime and thus we cannot resolve that value. You need to provide configuration either via `local.settings.json` for local development or via App Settings (these can be resolved from KeyVault). https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli

We have no plans to support Azure AppConfiguration this way with dotnet isolated as there is a hard technical limitation: there are multiple components which need to know those config values **without ever running your worker**, and the example you have has only the worker knowing how to retrieve those values from Azure AppConfiguration service.

**Comment by denis-susan** [comment]
Is there any way to provide those configurations or alternatives on how to configure the tinetrigger so we can use the appconfig resource? or is this a hard no?

**Comment by VenkatSappidi** [comment]
Is there any alternative way to read from Appconfiguration?
