### ISSUE TITLE
Alternative to source-code generation

### ISSUE THREAD

**Issue by Emeka-MSFT** [Azure/azure-functions-dotnet-worker#2160]
This is in reference to https://github.com/Azure/azure-functions-dotnet-worker/pull/830

Question:
Is there an alternative to using this source-code-generator + dynamic runtime loading of this generated assembly?
This source code generation feature is costing us months of investigation, each time we update certain dependencies.
(This makes azure functions unsuitable as a platform -- at this point, we need a PhD to properly use it correctly/reliably.)

**DETAILS:**
Since the introduction of this source-code generation, building azure functions projects has been very painful, e.g. building via azure-devops (ADO). Normal compile time validations have now been replaced with mysterious runtime failures. 

Specifically, when we build using ado governed pipelines (which has rosalyn analyziers), source code generation is not performed. The azure function projects successfully completes. However, after deploying this build, it fails in obscure ways -- often due to data serialization rules.

Why introduce this source code generation process?
Couldn't a simple `AzFn.Register(myFunction);` be sufficient for this?

Side Note:
Why the complexity? This is unmaintainable. Source code generation, coupled with dynamic code loading, trades simple&deterministic compile-time analysis for complex&non-deterministic runtime-analysis. Why?

**Comment by kshyju** [comment]
@Emeka-MSFT 

As mentioned in the linked PR, the extension startup hook is meant to be used by extension authors. This feature allows them to include their extension specific startup code when the function app starts up. For this to work, extension authors need to implement a certain base class and add a certain assembly attribute. This feature is not meant to be used by normal azure function customers/developers as they won't be writing extensions. 

> Since the introduction of this source-code generation, building azure functions projects has been very painful, e.g. building via azure-devops (ADO). Normal compile time validations have now been replaced with **mysterious runtime failures**.
> Specifically, when we build using ado governed pipelines (which has rosalyn analyziers), source code generation is not performed. The azure function projects successfully completes. However, after deploying this build, **it fails in obscure ways -- often due to data serialization rules.**

Can you share more specific information about what errors you are seeing?

**Comment by jviau** [comment]
> Specifically, when we build using ado governed pipelines (which has rosalyn analyziers), source code generation is not performed.

Can this be raised with the governed pipelines owners to have them resolve source gen not being ran?
