### ISSUE TITLE
SDK-generated code interferes with code coverage results

### ISSUE THREAD

**Issue by CNBoland** [Azure/azure-functions-dotnet-worker#2162]
Code generated by Microsoft.Azure.Functions.Worker.Sdk (e.g. [DirectFunctionExecutor](https://github.com/Azure/azure-functions-dotnet-worker/blob/c47ab817f415f4e0609f17b3a96632d8dcc08279/sdk/Sdk.Generators/FunctionExecutor/FunctionExecutorGenerator.Emitter.cs#L37C32-L37C32)) is decorated with [[CompilerGenerated]](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.compilergeneratedattribute). Such code will commonly be included in code coverage result because excluding [CompilerGenerated] by attribute excludes `async` code as well, which is where much of our application's business logic resides. A better approach is to use [[GeneratedCode]](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute) instead (or in addition to, as with [[EditorBrowsable]](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute)). Code generator tools, such as [NSwag](https://github.com/RicoSuter/NSwag/blob/28b9400497a796b6217dcee6f122ba1eb2a7bc97/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L2C7-L2C7), use this approach.

As a workaround, we are configuring `FunctionsGeneratedCodeNamespace` build property, then excluding the namespace in code coverage configuration:

_Project.csproj:_
```
<PropertyGroup>
  <FunctionsGeneratedCodeNamespace>FunctionsGeneratedCode</FunctionsGeneratedCodeNamespace>
</PropertyGroup>

```

_CodeCoverage.runsettings:_
```
<DataCollector friendlyName="XPlat code coverage">
  <Configuration>
    <Exclude>[*]FunctionsGeneratedCode.*</Exclude>
    <ExcludeByAttribute>GeneratedCode</ExcludeByAttribute>
  </Configuration>
</DataCollector>
```

These are the classes I see and how they are currently decorated:

- `DirectFunctionExecutor` (has both `CompilerGenerated` and `EditorBrowsable` attributes)
- `FunctionExecutorAutoStartup` (has only `EditorBrowsable` attribute)
- `FunctionExecutorHostBuilderExtensions` (has no attributes)
- `FunctionMetadataProviderAutoStartup` (has only `EditorBrowsable` attribute)
- `GeneratedFunctionMetadataProvider` (has both `CompilerGenerated` and `EditorBrowsable` attributes)
- `WorkerExtensionStartupCodeExecutor` (has both `CompilerGenerated` and `EditorBrowsable` attributes)
- `WorkerHostBuilderFunctionMetadataProviderExtension` (has no attributes)

I believe that adding [GeneratedCode] attribute to SDK-generated code would solve the coverage inclusion problem elegantly and have little or no impact to existing projects.

**Comment by CNBoland** [comment]
Closing this issue. The generated classes no longer show up in code coverage result. Below are the Azure Functions package references in use:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
  </ItemGroup>
```

**Comment by CNBoland** [comment]
I spoke too soon. While the generated code no longer appears in code coverage run locally on my machine, it still appears in code coverage run on our Azure DevOps server (screen shots below). Our DevOps server uses an older version of [ReportGenerator](https://github.com/danielpalme/ReportGenerator/releases/tag/v4.8.13) that may account for the difference, but my original proposal still stands as an approach to properly decorating code generated by an SDK versus that generated by a compiler. My apologies for the confusion here.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2934065/4ea7929a-4069-47bb-87fc-3f0601c211b7)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2934065/a107ab39-58b8-4d28-9aa9-12ee7867580b)
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2934065/a9f78114-3e7d-49cd-98b4-8a9952379c7c)

**Comment by JavierBuffa** [comment]
Is there an update on this? this lowers a lot of the code coverage percentage even when only WorkerHostBuilderFunctionMetadataProviderExtension is not covered (or ignored)

**Comment by calloncampbell** [comment]
I'm also running into this issue and can't seem to exclude the classes generated.

**Comment by ja-iris** [comment]
Here is what we ended up with as our UnitTest.runsettings.
Excluded microsoft.azure.functions.worker.core.dll and the individual file names:
`<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="Code Coverage"
						   enabled="true"
						   uri="datacollector://Microsoft/CodeCoverage/2.0"
						   assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
				<Configuration>
					<CodeCoverage>
						<ModulePaths>
							<Exclude>
								<ModulePath>.*\.Tests\.dll</ModulePath>
								<ModulePath>.*microsoft\.azure\.functions\.worker\.core\.dll</ModulePath>
							</Exclude>
						</ModulePaths>
            <Functions>
              <Exclude>
                				
				<Function>.*\.Generated\..*</Function>
				<Function>.FunctionExecutor.</Function>
				<Function>.FunctionMetadata.</Function>
              </Exclude>
            </Functions>
            <Attributes>
              <Exclude>
                <Attribute>^System.Diagnostics.DebuggerHiddenAttribute$</Attribute>
                <Attribute>^System.Diagnostics.DebuggerNonUserCodeAttribute$</Attribute>
                <Attribute>^System.Runtime.CompilerServices.CompilerGeneratedAttribute$</Attribute>
                <Attribute>^System.CodeDom.Compiler.GeneratedCodeAttribute$</Attribute>
                <Attribute>^System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute$</Attribute>
                <Attribute>^System.Text.RegularExpressions.GeneratedRegexAttribute$</Attribute>				
              </Exclude>
            </Attributes>
					</CodeCoverage>
				</Configuration>
			</DataCollector>
		</DataCollectors>
	</DataCollectionRunSettings>
</RunSettings>
`

**Comment by calloncampbell** [comment]
@ja-iris I replaced my config with your config in my runsettings file but I see see code coverage for this.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/4095080/f4c3fb85-d9f2-45ec-be12-7477cef2f215)

**Comment by ja-iris** [comment]
I can't remember if you had to choose the file with Test, Configure Run Settings to make it get used?

**Comment by calloncampbell** [comment]
Yes I have a runsettings file and if I make other changes it takes affect, but wont take affect for the functions SDK stuff.

I ended up refactoring my app and moved all the logic out to a library so that I can exclude the function app entirely when running my tests and coverage report. 

I hope this is something the Functions Team can resolve in the future.

**Comment by LouAtAvanade** [comment]
Adding this to my .csproj files removed the uncovered code from analysis.

```<Project Sdk="Microsoft.NET.Sdk">   
  <PropertyGroup>   
       <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>   
      <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>   
  ...
  </PropertyGroup>
...
</Project>
```

My .runsetting file looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="Code Coverage" enabled="true" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
				<Configuration>
					<CodeCoverage>
                        <CompanyNames>
                            <Exclude>
                                <CompanyName>.*microsoft.*</CompanyName>
                            </Exclude>
                        </CompanyNames>
                        <Sources>
                            <Exclude>
                                <Source>.*\\[^\\]*\.g.cs</Source>
                            </Exclude>
                        </Sources>
					</CodeCoverage>
				</Configuration>
			</DataCollector>
		</DataCollectors>
	</DataCollectionRunSettings>
</RunSettings>
```

Obviously, [having introduced a regex](https://xkcd.com/1171/)

**Comment by Gobikannan** [comment]
Hi - is there any update on this ticket?

I tried above workaround (runsetting file) but no luck..

Anyone else had any other workaround for this please?

Thanks,
Gobi

**Comment by TomasLiutvinas** [comment]
At the moment what works for our pipelines is file filters in reportgenerator
`reportgenerator -reports:CoverageResults\*\*cobertura.xml -targetdir:coveragereport -filefilters:"+*;-*Microsoft.Azure.Functions.Worker.Sdk*"`
Haven't found a way to exclude them using .runsettings

**Comment by ak149** [comment]
Hi, 
We are still facing the issue. Have tried all the workaround and suggested solutions but nothing is working for us. Any kind of help will be highly appreciated. My solution is very big so the number of these autogenerated files is very large which is reducing my code coverage by a lot. 
@jviau @fabiocav

**Comment by kalprajkakani** [comment]
> Hi, We are still facing the issue. Have tried all the workaround and suggested solutions but nothing is working for us. Any kind of help will be highly appreciated. My solution is very big so the number of these autogenerated files is very large which is reducing my code coverage by a lot. [@jviau](https://github.com/jviau) [@fabiocav](https://github.com/fabiocav)

```
  <PropertyGroup>   
       <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>   
      <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>   
  </PropertyGroup>
```

this will disable source generator.

**Comment by ak149** [comment]
> > Hi, We are still facing the issue. Have tried all the workaround and suggested solutions but nothing is working for us. Any kind of help will be highly appreciated. My solution is very big so the number of these autogenerated files is very large which is reducing my code coverage by a lot. [@jviau](https://github.com/jviau) [@fabiocav](https://github.com/fabiocav)
> 
> ```
>   <PropertyGroup>   
>        <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>   
>       <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>   
>   </PropertyGroup>
> ```
> 
> this will disable source generator.


Hi @kalprajkakani , thanks for the suggestion. This worked for us in improving the code coverage, but I am just wondering are there any repercussions/regressions of disabling the source generator.

**Comment by ghorsey** [comment]
For those using coverlet and .net core. The following worked for me:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="XPlat code coverage">
				<Configuration>
					<Include>[D365.*]*</Include>
					<ExcludeByAttribute>Obsolete,GeneratedCodeAttribute</ExcludeByAttribute>
					<ExcludeByFile>**/*.g.cs</ExcludeByFile>
					<SkipAutoProps>true</SkipAutoProps>
				</Configuration>
			</DataCollector>
		</DataCollectors>
	</DataCollectionRunSettings>
</RunSettings>
```
