### ISSUE TITLE
Azure Function silently fails publishing code

### ISSUE THREAD

**Issue by codeputer** [Azure/azure-functions-dotnet-worker#2163]
As found and resolved here:
https://github.com/Azure/azure-functions-dotnet-worker/pull/2161

I need to deploy an Azure Function to resolve a production issue.  I followed the workaround stated in the PR, but no joy in actually deploying the code to Azure.  Not sure when this resolution is going to make it to my desktop, and I Urgently need to deploy.

**Comment by jviau** [comment]
@codeputer what issue are you encountering? Is it the `Microsoft.AspNetCore.Routing/7.0.0` load failure issue?
