### ISSUE TITLE
Multiple Issues of FunctionTimeOut in TimerTriggered dotnet isolated function  -- Urgent

### ISSUE THREAD

**Issue by inishantmishra** [Azure/azure-functions-dotnet-worker#2168]
Hi,

I have 2 functionapp which has timer triggered function and servicebus triggered function. 

TimerTriggered function lets say scheduled to run at 5AM UTC but sometimes it doesn't run and over appinsights i cant even see the complete logs why it got timedout as it seems it never actually triggered my code. Because, in my code, the first line is of logging a trace saying- Job is executing at this time and when it completes it will log the trace again that it completed. But it never logs these traces. It just logs 
Severity level: Information, Message: Executing 'Functions.MyScheduler' (Reason='Timer fired at 2023-12-25T05:00:00.7264025+00:00', Id=6dee4e46-9043-44ee-a3b7-e76fc1c97086)
that's it nothing else and after 1 hour as i have functiontime out mention is of 1 hour then after 1 hour it just timedout.

Please help what should I do, it seems every day i have to come online and need to monitor manually whether it ran or not or should i restart. After restart it works fine.

Packages used are-
` 	  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.12.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.2.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.0" />
	  <PackageReference Include="Azure.Messaging.EventGrid" Version="4.17.0" />
	  <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
	  <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
	  <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.21.0" />`
	  

	  
	  Also, please note usually we are receiving FunctionTimedout and sometimes we receive (but this is rare)-
	  Microsoft.AspNetCore.Connections.ConnectionAbortedException    
	  Exception encountered while listening to EventStream. The HTTP/2 connection faulted.
	  
	  Usually we receive this error
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/12464390/ef9d05cb-3b6c-466d-8787-3443ee237401)

We are using .net 7 isolated function. We are on Dedicated AppService Plan with Always On.

Please find the link for the minimum repo-	 [Link for Repo](https://github.com/inishantmishra/TestDotNetIsolatedFunctionApp/blob/master/TimerTriggeredFunction.cs)

Full Exception-

`Full Exception :
 Microsoft.Azure.WebJobs.Host.FunctionTimeoutException 
 /Timeout value of 01:05:00 was exceeded by function
 /Functions.MyScheduler
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryHandleTimeoutAsync(Task invokeTask,CancellationToken shutdownToken,Boolean throwOnTimeout,CancellationToken timeoutToken,TimeSpan timeoutInterval,IFunctionInstance instance,Action onTimeout) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /663
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /571
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /527
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /306
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /352
   
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   
async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) 
D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs 
 /108`
 
 
 Host.json is
 
 {
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      },
      "enableLiveMetricsFilters": true
    }
  },
  "extensions": {
    "serviceBus": {
      "sessionIdleTimeout": "00:00:01",
      "maxAutoLockRenewalDuration": "01:05:00"
    }
  },
  "functionTimeout": "01:05:00"
}
 

Please help me with what could be the issue. We are facing this repeatedly.

@brettsam @kshyju @satvu @fabiocav

**Comment by inishantmishra** [comment]
Can I get anyone's attention here? I also upgraded the packages for servicebus triggered one still faced the issue.

**Comment by SeanFeldman** [comment]
The issue is labelled for triage.
If urgent, open a support case.

**Comment by kshyju** [comment]
> Timeout value of 01:05:00 was exceeded by function Functions.MyScheduler

Does your "MyScheduler" takes more than 65 minutes to finish execution? If so, the error you are seeing is by design.

Is it possible that the code inside your "MyScheduler" goes into some infinite loop or so where it never finishes execution of the function?

**Comment by inishantmishra** [comment]
No My scheduler just checks the DB and gets the data and dispatch to event grid.

Actually when we see the AppInsights, we cant even see the trace of our code that function is even executing. 

You can see the repo not a single LogInfo is logged.

**Comment by kshyju** [comment]
@inishantmishra I was able to download your repro app and run it locally and on azure without any issues. I can see the logging entries are present in my AI resource.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/fb1fe698-305f-4338-9d06-fa016cdbede6)

The only additional thing I had to do was to define the 3 app settings used by the application code, in the azure environment (**_Settings -> Environment variables_**)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/144469/f39adf26-a336-44c3-8a58-678a75e3069f)

**Comment by inishantmishra** [comment]
Hi @kshyju 

I agree with you and am not sayign that it not always logs over appinsights or always give the exceptions. I am saying i am facing this issue at every 2-3 days and i am not able to understand why. I have raised another similar issue related to servicebus triggered function but it has different concern.

https://github.com/Azure/azure-functions-dotnet-worker/issues/2169

**Comment by kshyju** [comment]
If you are seeing this as an intermittent issue when running on azure, please open a support ticket so that the team can take a closer look at the state of your app. Thanks!

**Comment by inishantmishra** [comment]
Hi @kshyju 

I had already raised this issue as support case. But still would like your feedback and help too. It happens at every 2 days.
Support engineers say define timeout only which we have defined already. There is nothing concrete from their side and we are still stuck with these issues from more than 2 weeks.

**Comment by SeanFeldman** [comment]
@inishantmishra can you reproduce it in lower environments?

**Comment by inishantmishra** [comment]
@SeanFeldman Over the lower environments we see this but very rare. I can see 1 instance in Dev but 3 such instances like this on Stage.

**Comment by kshyju** [comment]
>  It happens at every 2 days.

It might be hard to find the root cause with the information provided in the GH issue. Please work with the support team as they can dig deeper into your app and provide more solid leads. I also recommend exploring the ["diagnostics" tool in portal](https://learn.microsoft.com/en-us/azure/app-service/overview-diagnostics) to see it provides any hints for you.

**Comment by inishantmishra** [comment]
I already did these diagnosis but nothing found any concrete.

**Comment by kshyju** [comment]
@inishantmishra 

We appreciate your efforts in bringing this issue to our attention. However, based on the information available from the GitHub issue, it seems not immediately actionable. To resolve this matter thoroughly, we recommend conducting a more in-depth investigation specific to your application. You've taken the right step by opening a support ticket, and our support team is ready to assist you. Please collaborate with them to delve deeper into the issue. Thank you for your understanding and cooperation.


For future issues, please open a new GitHub issue with detailed information. Your proactive reporting is invaluable for platform enhancement. Thank you for your ongoing support.
