### ISSUE TITLE
workaround for getting rich metadata?

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-dotnet-worker#217]
For example, for [Blob Trigger metadata](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#metadata) has BlobProperties properties. 
Have not been able to figure out how to get these properties.
If I define a POCO with these properties and pass it into the Function method signature with an object named properties and then try to read these properties in the Function, the Function throws an exception due to the object being null.

In case needed, [here is the sample Function](https://github.com/gabesmsft/functionsnet5testing/blob/master/FunctionsNet5/BlobTrigger3.cs) I tried getting nested metadata with.

**Comment by fabiocav** [comment]
binding data will flow, allowing you to bind to the specific elements. That information will also be present in the `FunctionContext` instance provided to the function
