### ISSUE TITLE
User-Agent header value is returned incorrectly when reading from HttpRequestData

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#2175]
The `User-Agent` header value is typically a string with space in it.

When accessing`User-Agent`  header from `HttpRequestData`, it returns an incorrect value. Instead of returning one string entry with the full string value (with spaces), It splits the ua string by `" "` and returns the results of that.

```csharp
[Function("Function1")]
public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
{
    req.Headers.TryGetValues("User-Agent", out var uaValues);

    var response = req.CreateResponse(HttpStatusCode.OK);
    await response.WriteAsJsonAsync(uaValues);

    return response;
}
```

Output

```json
[
    "Mozilla/5.0",
    "(Windows NT 10.0; Win64; x64)",
    "AppleWebKit/537.36",
    "(KHTML, like Gecko)",
    "Chrome/120.0.0.0",
    "Safari/537.36",
    "Edg/120.0.0.0"
]
```

If you try to do the same with `HttpRequest`, it returns the correct output.

```csharp
[Function("Function2")]
public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
{
    var uaValues = req.Headers["User-Agent"];

    return new OkObjectResult(uaValues);
}
```

Output
```json
[
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
]
```

**Comment by fabiocav** [comment]
Validate the behavior with `HttpRequestData` with and without the ASP.NET Core integration enabled.

**Comment by aishwaryabh** [comment]
I just repro'ed this scenario both with and without ASP .NET Core integration enabled

**Comment by aishwaryabh** [comment]
We investigated this issue and concluded that this behavior with the delimiter being a new line while using `HttpResponseData` is expected through design, as this behavior is able to be repro'ed using pure .NET APIs.
