### ISSUE TITLE
Azure Functions project template references out-of-support packages

### ISSUE THREAD

**Issue by ericstj** [Azure/azure-functions-dotnet-worker#2176]
When I do "File -> New Project -> Azure Functions" and select a target framework I expect to get project that references the "best" version of packages for that framework.

However I notice the following problems:
`Microsoft.Azure.Functions.Worker` references `Microsoft.Extensions.Hosting`: `5.0.0` - now out of support.
`Microsoft.Azure.Functions.Worker.ApplicationInsights` references `Microsoft.ApplicationInsights.PerfCounterCollector` references `Microsoft.Extensions.Caching.Memory`: `1.0.0` which is the very first version of this package from the .NETCore 1.0 release, long out of support.
`Microsoft.Azure.Functions.Worker.Grpc` references `Grpc.Net.ClientFactory` references `Microsoft.Extensions.Http`: `3.0.3` which is also out of support.

While it's fine for packages or libraries to reference older versions of packages - applications should not.  They should reference the latest to ensure they're running on supported and patched dependencies.

Since AzureFunctions provides an application template here it needs to ensure it's starting folks off on a supported and up-to-date set of dependencies.  This should either be done in the templates themselves or in the packages.

**Comment by mattchenderson** [comment]
Closing as this was addressed through templates updates that have gone out since this item was opened.
