### ISSUE TITLE
 Synchronous operations are disallowed error with AspNetCore integration when using HttpResponseDataExtensions.WriteString

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#2184]
##### Repro steps:
1. Create a new net8 isolated app with one http trigger.
2. Add a reference to the [Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore NuGet package, version 1.0.0 or later](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/) to your project.

3. Update startup code

```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .Build();

host.Run();
```

Update the HttpTrigger function class to have below 3 functions

```csharp
[Function("Foo")]
public HttpResponseData Foo([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{
    var response = req.CreateResponse(HttpStatusCode.OK);
    response.WriteString("Welcome to Azure Functions!");

    return response;
}

[Function("Foo2")]
public async Task<HttpResponseData> Foo2([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{
    var response = req.CreateResponse(HttpStatusCode.OK);
    await response.WriteStringAsync("Welcome to Azure Functions!");

    return response;
}

[Function("Bar")]
public IActionResult Bar([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequest req)
{
    return new OkObjectResult($"Welcome to Azure Functions, {req.Query["name"]}!");
}
```
Run the app and execute all functions. "Bar" and "Foo2" will work. "Foo" will fail with below exception.

> System.InvalidOperationException
  HResult=0x80131509
  Message=Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Azure.Functions.Worker.Http.HttpResponseDataExtensions.WriteString(HttpResponseData response, String value, Encoding encoding)
   at FunctionApp207.Function1.Foo(HttpRequestData req) in C:\Dev\Temp\FunctionApp207\Function1.cs:line 17

Packages used

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.1.0" />
  </ItemGroup>
```

**Comment by jviau** [comment]
Synchronous IO is disallowed by default in kestrel:

https://stackoverflow.com/questions/47735133/asp-net-core-synchronous-operations-are-disallowed-call-writeasync-or-set-all

``` CSharp
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

**Comment by fabiocav** [comment]
After discussion, here are some of the ideas on what we should do instead of enabling synchronous IO:

- Update all templates to make sure we're using async patterns when working with `HttpRequestData`
- Create an analyzer that will provide compile time validation and code suggestion to fix/prevent the issue
- Add this information to the migration guides (including highlighting the fact that ASP.NET Core behaviors apply when using the integration)

**Comment by fabiocav** [comment]
Assigning to the next spring to decompose this into different issues we can track.

**Comment by kshyju** [comment]
Opened https://github.com/Azure/azure-functions-dotnet-worker/issues/2286 and https://github.com/Azure/azure-functions-templates/issues/1509
