### ISSUE TITLE
source generators not working with azure functions anymore

### ISSUE THREAD

**Issue by lilpaul** [Azure/azure-functions-dotnet-worker#2186]
Hey guys

We recently migrated to .net8 and in our codebase we are using a source generator to create some azure functions, specifically for event grid trigger functions, but I'm fairly sure this issue will happen for any source generated azure function. It seems like there is a new generated class in the net 8 azure functions apps - DirectFunctionExecutor.

We are assuming this generated class is there for speed optimizations instead of using reflection to discover what azure functions exist in a functions project. Unfortunately it doesn't seem to include any classes that are created from source generators and only functions that are manually added to the project. I'm sure you can appreciate the bind this puts us in.

Is there something we are missing WRT configuration or csproj options to ensure that the generated DirectFunctionExecutor includes generated classes?

Currently we only see one option as a workaround and that is to change our source generator to not use the ISourceGenerator interface and [Generator] annotation, but to actually create a set of .cs files into the other projects source directory and edit the csproj file. Which just seems like we are heading down the wrong path overall.

Please advise.
Many thanks.
Paul

**Comment by jviau** [comment]
@lilpaul unfortunately we cannot include generated functions in `DirectFunctionExecutor` as the order of source gen is not controllable, so we cannot consume source gen code within a source generator ourselves. The solution would be to disable our source generators and we will fallback to a reflection approach.

``` xml
<FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>
<FunctionsEnableMetadataSourceGen>false</FunctionsEnableMetadataSourceGen>
```

**Comment by lilpaul** [comment]
Thanks for that, I tried them, and the <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen> did seem to stop the DirectFunctionExecutor from being generated, however the <FunctionsEnableMetadataSourceGen>false</FunctionsEnableMetadataSourceGen> did not prevent the metadata provider from being generated, which it seems is what the functions host was using for discovery.

I googled a bit more using FunctionsEnableExecutorSourceGen and the generated class names and stumbled across this post:
https://github.com/Azure/azure-functions-dotnet-worker/issues/1058 which mentioned this setting 'FunctionsEnableWorkerIndexing', and I tried that with false and it seemed to stop the metadata provider being generated, which has resolved my problem.

Thanks so much for the assist, I don't think I would have found the above csproj options without it.

**Comment by danielmarbach** [comment]
FYI There appears to be a bug in how the target files reads those settings. I have raised an issue and a fix https://github.com/Azure/azure-functions-dotnet-worker/issues/2209

**Comment by specialforest** [comment]
> Add this to your csproj:
> 
> ```
> <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>
> <FunctionsEnableMetadataSourceGen>false</FunctionsEnableMetadataSourceGen>
> ```

Should this be added to https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8 ?
