### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore v1.2.0 references non existing package as dependency

### ISSUE THREAD

**Issue by Spongie** [Azure/azure-functions-dotnet-worker#2193]
The v1.2.0 version of the Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore package has Microsoft.Azure.Functions.Worker ( >= 1.20.1) as a dependency

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2790876/8852d257-6a98-4775-bbbd-0f3d9a8340ad)

However checking nuget Microsoft.Azure.Functions.Worker has 1.20.0 as it's latest version.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2790876/a274da3c-3e9a-42b9-a72a-e5b386b3232b)

So when trying to install the update we get the following error
```
NU1102: Unable to find package Microsoft.Azure.Functions.Worker with version (>= 1.20.1)
  - Found 36 version(s) in nuget.org [ Nearest version: 1.20.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
 ```

**Comment by satvu** [comment]
Closing as 1.20.1 has been released on [nuget](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.20.1).
