### ISSUE TITLE
Unable to add Azure AD B2C PKCE authentication & swagger http trigger for Azure Function .net 8 isolated worker process

### ISSUE THREAD

**Issue by prohith14** [Azure/azure-functions-dotnet-worker#2203]
I Have created a new project from scratch with .net8 Isolated worker process for authentications tried using middleware in program.cs
using services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme) and for swagger   .ConfigureOpenApi() using

`using Aura.Infrastructure.Azure;
using Aura.Telemetry.Func.Middlewares;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Serilog;

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.ApplicationInsights(TelemetryConverter.Traces)
    .CreateLogger();
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder.UseMiddleware<ExceptionMiddleware>();
        builder.UseNewtonsoftJson();
    })
    .ConfigureOpenApi()
    .ConfigureServices((context, services) =>
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(AuthorizationConst.AzureB2CPKCE, options =>
            {
                options.Authority = $"https://auradevtestb2c.b2clogin.com/004a0ad1-4423-4202-922a-1ed934ec03f0/B2C_1_Aura_Sign_In_Dev/v2.0";
                options.Audience = "9e75ab5e-83f8-456d-9325-6173de5262c1";
            });
        services.AddLogging(logging =>
        {
            logging.ClearProviders();
            logging.AddSerilog(Log.Logger);
        });
    })
    .Build();

host.Run();`

And in simple http trigger function.cs

`using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;

namespace Aura.Telemetry.Func;

public class Telemetry
{
    private readonly ILogger<Telemetry> _logger;

    public Telemetry(ILogger<Telemetry> logger)
    {
        _logger = logger;
    }

    [Authorize]
    [OpenApiOperation(operationId: "greeting", tags: new[] { "greeting" }, Summary = "Greetings", Description = "This shows a welcome message.", Visibility = OpenApiVisibilityType.Important)]
    [OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
    [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Summary = "The response", Description = "This returns the response")]
    [Function("Telemetry")]
    public Task<HttpResponseData> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "telemetry")]
        HttpRequestData req)
    {
        _logger.LogInformation("Post request executed");
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
        ////response.WriteString($"Welcome to Azure Functions! {telemetryInput.Count}");
        return Task.FromResult(response);
    }
}`

I have been struggling for a while can someone please help here

**Comment by kshyju** [comment]
@prohith14 Can you elaborate on your expected behavior?
