### ISSUE TITLE
ServiceBusTrigger - Cannot bind the connection and queue to a configuration coming from a keyvault

### ISSUE THREAD

**Issue by arnaudleclerc** [Azure/azure-functions-dotnet-worker#2206]
Hi,

I am currently trying to implement a ServiceBusTrigger using a connection and a queue name coming from a key vault on an azure function running on isolated mode. 

The trigger allows us to achieve Identity Based connection where the `Connection` property of the trigger is the fully qualified name of the service bus instance (formatted as`ServiceBusName:fullyQualifiedName`) and where the queue can be a configuration key like `%QueueName%`. 

For security reasons, those information are stored on a key vault. I was able to bring this to work with the in-process mode by adding the key vault onto the configuration sources at startup, and the trigger identifies the configuration keys as being part of the configuration. Everything works fine here.

```
public static IConfigurationBuilder AddKeyvaultConfiguration(this IConfigurationBuilder builder)
{
    return builder.AddAzureKeyVault(
        new Azure.Security.KeyVault.Secrets.SecretClient(new Uri(Environment.GetEnvironmentVariable("KeyvaultUri")), new DefaultAzureCredential()),
        new FunctionsKeyvaultSecretManager());
}
```

```
namespace Function_Inprocess
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
        }

        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            builder.ConfigurationBuilder.AddKeyvaultConfiguration();
        }
    }
}
```

```
[FunctionName("Function")]
public void Run([ServiceBusTrigger("%ServiceBusInprocessQueue%", Connection = "ServiceBusNamespace")]string myQueueItem, ILogger log)
{
    log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
}
```

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9578038/ebf6e7c9-90ef-452f-90b7-b7980c6e84b9)

I cannot make it run with the isolated process. I am able to add the key vault onto the configuration sources, either using `ConfigureHostConfiguration` or `ConfigurationAppConfiguration` but the trigger does not recognize the keys.

```
using Functions.KeyVault;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureHostConfiguration(builder => builder.AddKeyvaultConfiguration())
    .Build();

host.Run();
```

```
public class Function
{
    private readonly ILogger<Function> _logger;

    public Function(ILogger<Function> logger)
    {
        _logger = logger;
    }

    [Function(nameof(Function))]
    public void Run([ServiceBusTrigger("%ServiceBusIsolatedQueue%", Connection = "ServiceBusNamespace")] ServiceBusReceivedMessage message)
    {
        _logger.LogInformation("Message ID: {id}", message.MessageId);
        _logger.LogInformation("Message Body: {body}", message.Body);
        _logger.LogInformation("Message Content-Type: {contentType}", message.ContentType);
    }
}
```

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9578038/c278195a-97ca-4e77-a546-4f1bec6bc911)

I created a repro of this on [this repository](https://github.com/arnaudleclerc/keyvaultconfiguredsvcbustrigger)

Is that a case which should be supported or am I simply missing something ?

Alternative exists like adding keyvault references onto the appsettings of the function, but this is something I sadly cannot use for compliance reasons.

Thanks!

**Comment by imranmomin** [comment]
I have the similar issue, where I'm trying to read configuration from `appsettings.json` and it still not able to find the values

**Comment by yannickboy15** [comment]
We're experiencing the same issue at the moment, which makes it a show stopper before we're releasing our complete infrastructure to PROD. As of now the workaround is to add the ServiceBusConnection to our appsettings in our Azure Functions, but it's obviously not ideal as we are managing everything through Keyvault.
