### ISSUE TITLE
Single output binding example in doc missing the output binding attribute

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-dotnet-worker#221]
In the MS doc, the [Output Bindings](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#output-bindings) example for a single output binding is currently missing the Output binding attribute:

```
public static string Run([QueueTrigger("functionstesting2")] Book myQueueItem,
        FunctionContext context)
    {
        var logger = context.GetLogger("QueueFunction");
        logger.LogInformation($"Book name = {myQueueItem.Name}");

        // Queue Output
        return "queue message";
    }
}
```
If we add these lines to the top of the code, it should suffice:
```
[Function("QueueFunction")]
[QueueOutput("functionstesting2")]
```

**Comment by ggailey777** [comment]
Thanks @gabesmsft for pointing this out. We're pulling code examples directly from this repo, and the registration got off a bit on some of them. The linked PR fixes this issue.

**Comment by ggailey777** [comment]
You should see this update publish by ~3pm PST today. Thanks again!

**Comment by fabiocav** [comment]
Closed as resolved. Thanks for reporting this!
