### ISSUE TITLE
Unable to `publish` a NET8 Functions App with ReadyToRun on the command line

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/azure-functions-dotnet-worker#2212]
Please see https://github.com/MatthewSteeples/ReadyToRun8/actions/runs/7508999929/job/20445457605 for repro

From what I can work out, the SDK generates a csproj file to do something with the Extensions that are referenced. This csproj (generated in `ExtensionsCsprojGenerator`) is a NET6 project. If you set ReadyToRun as a command line parameter it's not able to build this project, presumably because everything else that it's building is NET8.

There's a workaround to set the ReadyToRun as part of the csproj rather than pass it in as command line, but I don't know what consequences that has (because it means that whatever the Extensions csproj output is used for won't have R2R enabled on it).

**Comment by MatthewSteeples** [comment]
Related [Developer Community Feedback](https://developercommunity.visualstudio.com/t/Publishing-NET-7-Azure-Functions-projec/10533051?sort=newest)

**Comment by jviau** [comment]
@MatthewSteeples what property are you setting in your csproj exactly? Is it `ReadyToRun` or `PublishReadyToRun`? The issue when using the command line param is it is a global property which propagates to the inner build. This PR included changes to suppress these known problematic global props from the inner build. Wondering if this is already solved or if a new prop will need to be added.

**Comment by MatthewSteeples** [comment]
@jviau Thanks for the reply. At this point my repro only sets it via the command line. Did you mean to link to a PR?

The reason that I've raised this is because the first two things that I tried both resulted in failed builds:
1. Setting via command line - build fails
2. Setting via environment variable in the build - build fails
3. Setting via a property in the csproj - build succeeds

My concern with using option 3 is that while _my_ projects are compiled as ReadyToRun, this extensions project is (presumably) not compiled with that setting. I don't know whether that's an issue or not though (as I'm not sure what this project does).

**Comment by jviau** [comment]
@MatthewSteeples yeah I understand the 3 scenarios: 1 & 2 are 'global properties' which propagate to the inner build. The functions SDK needs to suppress these from propagating. I just want to know the exact property you are setting in your csproj to verify what I need to suppress.

**Comment by MatthewSteeples** [comment]
The property as it appears in the csproj file is `PublishReadyToRun`

**Comment by jviau** [comment]
@MatthewSteeples great thank you. This is addressed by #1946 and will be in the next SDK release (aiming for Monday 1/19).

**Comment by jviau** [comment]
Fix released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0-preview1
