### ISSUE TITLE
NegotiateAsync result of ServerlessHub serializes unwanted properties

### ISSUE THREAD

**Issue by Dresel** [Azure/azure-functions-dotnet-worker#2213]
`ServerlessHub` provides a [NegotiateAsync](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.SignalRService/src/Hubs/ServerlessHub.cs#L69) function which returns the serialized result of `ServiceHubContext.NegotiateAsync`. This is [intended](https://github.com/aspnet/AzureSignalR-samples/blob/af330990c169aecc27572e0bba3af4e6d57bb588/samples/DotnetIsolated-ClassBased/Functions.cs) to be used like the following code:

```csharp
[Function("negotiate")]
public async Task<HttpResponseData> Negotiate([HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req)
{
    _logger.LogInformation("C# HTTP trigger function processed a request.");

    var negotiateResponse = await NegotiateAsync(new() { UserId = req.Headers.GetValues("userId").FirstOrDefault() });
    var response = req.CreateResponse();
    response.WriteBytes(negotiateResponse.ToArray());
    return response;
}
```

The serialized `NegotiationResponse` contains properties which will lead to client failures (like the ConnectionId set to null). Converting the result to a `SignalRConnectionInfo` should fix this problem.

**Comment by alextse** [comment]
Mismatch from documentation https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config

**Comment by Y-Sindo** [comment]
> Mismatch from documentation [learn.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config)

The document was for C# in-process model only. Now I have added C# isolated-worker process to the doc.

**Comment by RiSchone** [comment]
I am still seeing a problem.  I am creating an Isolated worker model as noted in the section Class-based model of the documentation.  I am using the asrs-emulator.  The emulator is running and the code below shows the program.cs file. 

using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using SafeUTFunctionApp;

var host = new HostBuilder().ConfigureFunctionsWorkerDefaults(b => b.Services.AddServerlessHub<Functions>()).Build();

var builder = FunctionsApplication.CreateBuilder(args);
builder.ConfigureFunctionsWebApplication();
builder.Build().Run();

When client calls  

var negotiateResponse = await NegotiateAsync(new() { UserId = req.Headers.GetValues("userId").FirstOrDefault() });

I receive the following error. 

"System.InvalidOperationException: 'The serverlesshub Functions is not registered correctly using services.AddServerlessHub().'"

**Comment by Y-Sindo** [comment]
@RiSchone You are mixing two ways to creating and starting functions host.

You're registering the serverless hub to host instance named `host` via the following code,
```cs
var host = new HostBuilder().ConfigureFunctionsWorkerDefaults(b => b.Services.AddServerlessHub()).Build();
```

but the actual host started by you is the following host:

```cs
var builder = FunctionsApplication.CreateBuilder(args);
builder.ConfigureFunctionsWebApplication();
builder.Build().Run();
```

If you choose the `IHostApplicationBuilder` way, you should register the serverless hub like this:
```cs
var builder = FunctionsApplication.CreateBuilder(args);

builder.Services
    .AddServerlessHub();

var host = builder.Build();
```

For more information about the two methods to creating and starting the functions host, see https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Cwindows#start-up-and-configuration
