### ISSUE TITLE
How to set custom JsonSerializerOptions for HttpResponseDataExtensions.WriteAsJsonAsync?

### ISSUE THREAD

**Issue by doggy8088** [Azure/azure-functions-dotnet-worker#2218]
Is there any sample code for using custom JsonSerializerOptions when calling HttpResponseDataExtensions.WriteAsJsonAsync() method?

**Comment by liliankasem** [comment]
`HttpResponseDataExtensions` uses the serializer set in worker options:

https://github.com/Azure/azure-functions-dotnet-worker/blob/de334081abb1038c14e84153f11214ad7bf037cb/src/DotNetWorker.Core/Http/HttpResponseDataExtensions.cs#L297-L301

You can configure the serializer in your Program.cs, there is a sample of that here:

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Configuration/Program.cs
