### ISSUE TITLE
Easy auth stopped injecting claims principal after migration to in-process model and .NET 8

### ISSUE THREAD

**Issue by DannyBoyIT** [Azure/azure-functions-dotnet-worker#2226]
I have migrated my Azure functions from .NET 6 and in-process model to .NET 8 and isolated process. 
I am using Easy auth in Azure which previously injected a claims principal object into each function when the 
`ClaimsPrincipal claimsPrincipal` was present in the in-parameters of the method without any extra configuration needed in the function.

Now this object is instead null. 
I have also tried to check if the principal is injected somewhere else, like the `HttpRequest` or the `HttpRequestData` object but the identities there are also null.

Anybody else having the same problem or have found a solution?

**Comment by Elyseum** [comment]
ClaimsPrincipal being null is expected according to https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-csharp#working-with-client-identities, which states

> The authenticated user is available via [HTTP Headers](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#access-user-claims-in-app-code).

Implying you should decode it yourself when using isolated processes (see link on how to do that).

In search for an OOTB solution, I found https://learn.microsoft.com/en-gb/answers/questions/1526148/httptrigger-function-access-to-user-and-claims-for which states

> In case of isolated model, req.Identities returns ClaimsIdentity collection ([HttpRequestData.Identities](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata.identities?view=azure-dotnet#microsoft-azure-functions-worker-http-httprequestdata-identities)) with few limitations.

But for my case (ADB2C / AAD) it does not seem to work. I get back an enumerable with a single value, but that value is not provided with the authentication details I expected (it seems to be default object instance):

```
[
  {
    AuthenticationType: null,
    IsAuthenticated: false,
    Actor: null,
    BootstrapContext: null,
    Claims: [],
    Label: null,
    Name: null,
    NameClaimType: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name',
    RoleClaimType: 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'
  }
]
```

**Comment by Bobetti** [comment]
5 months passed and still no info what to do with this?

**Comment by shapea** [comment]
I can confirm the same issue as here:

> I have migrated my Azure functions from .NET 6 and in-process model to .NET 8 and isolated process. I am using Easy auth in Azure which previously injected a claims principal object into each function when the `ClaimsPrincipal claimsPrincipal` was present in the in-parameters of the method without any extra configuration needed in the function.
> 
> Now this object is instead null. I have also tried to check if the principal is injected somewhere else, like the `HttpRequest` or the `HttpRequestData` object but the identities there are also null.
> 
> Anybody else having the same problem or have found a solution?

When our Azure Function ran in .NET 6.0 isolated worker, the User ClaimsPrincipal was being populated after passing through EasyAuth. However, after migration to .NET 8.0 isolated worker, while nothing has changed it appears the User is now empty/unset.

What's unclear here is whether this is a change in the Azure Function host setup or in EasyAuth itself. Would need one of the experts for the project to explain the reason for the changes here.

**Comment by Bobetti** [comment]
After talking to the support, turns out, that Azure functions which are inside Azure Static App, which was my case, are not supporting .net8 yet. Only standalone functions support it. That's why I was experiencing such a behavior and rolled back all my changes back to .net6

**Comment by surgupta-msft** [comment]
In Isolated, there is no binding that will bind to `ClaimsPrincipal`, so adding that to the function method will not take that as an input. To inspect credentials, use the identities in the request data or inspect the HttpContext associated with the request when using the ASP.NET Core integration.

@shapea Please create another issue as your scenario is for migration from .Net6 isolated to .Net8 isolated while the issue is for in-proc to isolated migration. A minimal repro or steps would be very helpful to investigate the issue.

**Comment by stevenveerbeek** [comment]
@surgupta-msft I'm using ASP.NET Core integration and tried getting the claims principal via HttpRequest.HttpContext.User (I assume this is what you meant by inspecting the HttpContext), but I'm getting an empty identity back (same as what @Elyseum reports with HttpRequestData.Identities), whereas before migrating to isolated worker I'd get actual identity data through a ClaimsPrincipal parameter added to the method for my HTTP-triggered function.

Am I doing something wrong or did this functionality just get lost in the transition to the isolated worker model?

**Comment by sec** [comment]
According to https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities that's expected - there is sample code how to parse this by hand, I would expect something built into the framework that could do this, not writing extra code and middleware for something that was working fine before, but at least it's something.
