### ISSUE TITLE
ILogger Scope information overwriting message property

### ISSUE THREAD

**Issue by YanBrunet** [Azure/azure-functions-dotnet-worker#2229]
Edit:
I am using Application Insights.

When creating a scope using a formatted string, the arguments are added to the custom properties but the message overwrites the OriginalFormat of the LogMessage.

``` CS
public class MyClass(ILogger<MyClass> Logger)
{
    [Function("TestLogs")]
    public IActionResult TestLogs(
[HttpTrigger(AuthorizationLevel.Function, "post", Route = "test-logs")]
        HttpRequest req,
CancellationToken token = default)
    {
        string processName = "MyProcessName";
        Guid id = Guid.NewGuid();

        KeyValuePair<string, object>[] scopeValues = [
            new ("Id", id ),
            new( "Process", processName),
        ];
        using (var scope = Logger.BeginScope(scopeValues))
        {
            Logger.LogInformation("My log {SomeValue}", "ScopeKeys only.");
        }

        using (var scope2 = Logger.BeginScope("Executing {Process} : {Id}", processName, id ))
        {
            Logger.LogInformation("My log {SomeValue}", "Scope with formatted text.");
        }
       
        return new OkResult();
    }
}
```

The first log entry will work as expected, adding the keys to the custom properties.

``` JSON
{
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "My log ScopeKeys only.",
      "severityLevel": "Information",
      "properties": {
        "Id": "65b6e9e1-ec41-4b27-bf5c-cd7dac8e95c7",
        "InvocationId": "372d62af-e449-4e48-bce3-35d0b8dfde7f",
        "AzureFunctions_FunctionName": "TestLogs",
        "DeveloperMode": "true",
        "Process": "MyProcessName",
        "AzureFunctions_InvocationId": "372d62af-e449-4e48-bce3-35d0b8dfde7f",
        "SomeValue": "ScopeKeys only.",
        "OriginalFormat": "My log {SomeValue}",
        "CategoryName": "MyClass"
      }
    }
  }
}
```

The second log entry will also add the keys to the custom properties, but the `OriginalFormat` property will be overwritten by the scope format string.

``` JSON
{
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "My log Scope with formatted text.",
      "severityLevel": "Information",
      "properties": {
        "Id": "65b6e9e1-ec41-4b27-bf5c-cd7dac8e95c7",
        "InvocationId": "372d62af-e449-4e48-bce3-35d0b8dfde7f",
        "AzureFunctions_FunctionName": "TestLogs",
        "DeveloperMode": "true",
        "Process": "MyProcessName",
        "AzureFunctions_InvocationId": "372d62af-e449-4e48-bce3-35d0b8dfde7f",
        "SomeValue": "Scope with formatted text.",
        "OriginalFormat": "Executing {Process} : {Id}",
        "CategoryName": "MyClass"
      }
    }
  }
}
```

I would expect the `OriginalFormat` to have the same value in both situation : `My log {SomeValue}`

**Comment by jviau** [comment]
@YanBrunet what logger provider are you having the issue with? Are you using application insights? Something else? `ILogger` is just an abstraction over many ILogger providers. We only own a single `ILoggerProvider`, which is active only when _not_ using application insights and does not support log properties anyways. If the issue lies with our `ILoggerProvider` implementation, we can look into it. If it is a different provider, you will need to engage with the owner of that provider.

**Comment by YanBrunet** [comment]
Sorry for the confusion, some information was lost during the many rewrites.

I am using Application Insights.

**Comment by jviau** [comment]
@YanBrunet thanks. We do not own the app insights logger, you will need to raise this issue with their team: https://github.com/microsoft/ApplicationInsights-dotnet

Going to close this issue as it is external to us.

**Comment by YanBrunet** [comment]
Thanks.
Actually, in this repo, it redirects to [https://github.com/Azure/azure-functions-host]() for issues within Function apps.

**Comment by jviau** [comment]
That would apply to in-proc apps as we have our own SDK for it. For out of proc apps, you are expected to use their SDK for it directly: https://www.nuget.org/packages/Microsoft.ApplicationInsights.WorkerService
