### ISSUE TITLE
Unable to get Trace logs from worker

### ISSUE THREAD

**Issue by NARESHARADHYULA** [Azure/azure-functions-dotnet-worker#2235]
we are migrating .net 6 in process http trigger to isolated worker.
we are facing issues with traces not getting logged.
below is the host.json file
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      },
      "enableLiveMetricsFilters": true
    },
    "logLevel": {
      "Function": "Information",
      "Host.Results": "Trace",
      "Host.Aggregator": "Warning",
      "Function.FutureProspect": "Information",
      "FunctionWithTraceLog.Bl": "Trace",
      "Default": "Warning"
    }
  }
}

below is the program.cs file

               var host = new HostBuilder()
                .ConfigureFunctionsWebApplication((worker) =>
                {
                    worker.Services.ConfigureFunctionsApplicationInsights();
                })
                .ConfigureAppConfiguration((HostBuilderContext hostContext, IConfigurationBuilder builder) =>
                {
                    // Add custom configuration sources
                })
                .ConfigureServices((HostBuilderContext hostContext, IServiceCollection services) =>
                {
                       services.AddApplicationInsightsTelemetryWorkerService();
                       services.ConfigureFunctionsApplicationInsights();
                        services.Configure<LoggerFilterOptions>(options =>
                    {
                        var toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName
                            == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
                        if (toRemove is not null)
                        {
                            options.Rules.Remove(toRemove);
                        }
                    });

                    services
                    .AddScoped<IBusinessLogic>(c => new BusinessLogic(
                       c.GetRequiredService<ILogger<BusinessLogic>>()));

                })
                .Build();

            host.Run();
        }
    below is the worker code from which traces are not logged.
    
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/d1f81ca9-e445-4243-915f-4a5ef84635a4)
        
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/85bf2002-2526-4fb9-9f5a-6029e8353731)
        
 with the same host.json file we can get traces logged in in process functions.
 can you help us in resolving this?
 below is the github repo link it can be easily reproduced.
 https://github.com/NARESHARADHYULA/FunctionWithTraceLog/tree/master

**Comment by jviau** [comment]
`host.json` only applies to the host process, not to the worker process. You will need to add your own `appsettings.json` or other config source, add it to your config builder, and configure your logging there.

**Comment by NARESHARADHYULA** [comment]
Not sure if it has something to do with this
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/3afa26ee-e598-4c90-bed6-e18f9a34f350)

some of the logs are ignored
**Ignoring RpcLog from invocation '' because there is no matching ScriptInvocationContext.**

**Comment by brettsam** [comment]
Note that I wasn't able to see your repo -- I get a 404 when I try to look.

First -- can you check App Insights? Are your logs going there as expected? If so, we can narrow this down to just the Core Tools filtering differently. I suspect that everything is in App Insights like you'd expect.

A side note -- I've answered a few of these questions before here (but it's probably impossible to find; I'll work to get this into proper "FAQ" docs): https://github.com/Azure/azure-functions-host/issues/7452#issuecomment-1749373454. See the section on some of the caveats (notably that host.json does *not* affect the worker).

The best advice is to think of the worker as its own Console exe and use the normal .NET Configuration system to enable the logging you want there. You've done this with the "appsettings.json" approach already.  

For example, what if you do this -- do they show up?

```json
{
  "WorkerLogging": {
    "LogLevel": {
      "Default": "Trace"
    }
  }
} 
```

It's entirely possible that some of the logs are getting dropped in the Core Tools only but they do show up in App Insights. One of the reasons we changed the design of logging was due to limitations like this. There may even be another bug that is fixed in 4.30 (not yet released) that can help with out-of-order logs coming from the worker, which may be what you're seeing.

However, those are *only* for the local Core Tools experience; I suspect App Insights logs would look correct.

**Comment by NARESHARADHYULA** [comment]
@brettsam 
First thing 
i have made the git repo https://github.com/NARESHARADHYULA/FunctionWithTraceLog public now you can access the code

**coming to the suggestion of deploying to azure func app**
I have deployed func app and still can't find the trace logs 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/f5979ad7-23de-45ed-a056-866fe572654d)

but one thing I have noticed is 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/a3c1d6db-41f3-4bde-a554-77dae302460e)

11:59:53.788	Trace	Severity level: Information, Message: Request starting HTTP/1.1 POST http://localhost:50602/api/FutureProspect?code=FxUU6RrSwCxt1xmsSP_bqphw8Zj8sWhI2EIkPcu12z7EAzFuFdBXWQ== application/json 11
11:59:53.788	Trace	Severity level: Information, Message: Executing endpoint 'FutureProspect'
11:59:53.789	Trace	Severity level: Information, Message: C# HTTP trigger function processed a request.
11:59:53.789	Trace	Severity level: Information, Message: trace is enabled in function :False
11:59:53.789	Trace	Severity level: Information, Message: logging info in function
11:59:53.789	Trace	Severity level: Warning, Message: logging warning in function
11:59:53.789	Trace	Severity level: Error, Message: logging error in function
11:59:53.789	Trace	Severity level: Critical, Message: logging critical in function
11:59:53.789	Trace	Severity level: Information, Message: Command handler executing at: 2/19/2024 6:29:53 AM

even though the **type** is **Trace** the Severity level still starts from **Information** something to look at that may be?

**Comment by brettsam** [comment]
Now that I can see the project, I was able to see the problem -- you're not deploying `appsettings.json` to your output directory so the logging settings aren't working.

Once I did that, everything worked:

In Core Tools:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1089915/91c20d0f-5e2b-4e99-9ed7-d5315dd5414a)

In App Insights:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1089915/156801c9-8cd6-4b9b-83e6-eb1cddd0ac19)

**Comment by NARESHARADHYULA** [comment]
@brettsam 
thanks for the Reply as said we can see  Traces logged in appinsights.

**Comment by NARESHARADHYULA** [comment]
@brettsam 
is there a way where we can use IQueueProcessorFactory in an isolated worker function?
basicaly for a queue trigger function we want to set TTL for poison queue messages to infinite
in In-Process we have IQueueProcessorFactory  coming from **Microsoft.Azure.WebJobs.Host.Queues**
but in isolated process we cant use this based on the documentation 

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/9034604/33b32193-a1c7-47e8-b9c3-4d255bf4a591)

**Comment by brettsam** [comment]
No -- isolated applications cannot override services like in-process applications can. If you'd like that setting exposed (which means every language could take advantage), I'd recommend filing a feature request in that repo: https://github.com/Azure/azure-sdk-for-net/issues/new?assignees=&labels=&projects=&template=02_feature_request.yml&title=%5BFEATURE+REQ%5D.

Be sure to enter `Microsoft.Azure.WebJobs.Extensions.Storage.Queues` as the library name.
