### ISSUE TITLE
Add extension dependency validation step to CI

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-dotnet-worker#2237]
We ensure we are keeping our published extensions up to date with the latest available webjobs extensions, we will add a validation step to our CI.

# Requirements

At a high level, we need to get a `project.assets.json` for the inner-build `WorkerExtensions.csproj` on disk as part of our CI build so that component governance will scan it for vulnerabilities. We also need to consider transitive dependency resolution hiding a vulnerable package - as such, we should have a project.assets.json _per_ extension package in this repo.

# Design

We will add some automation ran as part of CI that will generate a function app csproj per extension in this repo, and then will build those extensions (can use a `dirs.proj` to glob and build them all in one step)

- The generate csproj will reference only a single worker extension via `ProjectReference` (we want this to turn green when the fix is checked in, and not have to wait until package is published)
- Will reference Worker SDK and core projects via `ProjectReference`

The primary candidate for this csproj generation is an MSBuild target which will generate and validate the WebJobs dependencies all part of a regular build.

**Comment by satvu** [comment]
Update: Discussed with @jviau and we are going to test another design that may be simpler. Overview:

- Use the test apps folder to create an app with project references to the extensions
- Make sure CI is run against the test apps folder

**Comment by fabiocav** [comment]
PR out. Changes currently being validated.
