### ISSUE TITLE
Function - timerinfo scheduledStatus.Last

### ISSUE THREAD

**Issue by coredev123** [Azure/azure-functions-dotnet-worker#2243]
I have a function which runs daily and aims to update items out of the database more than one year old.  For performance reasons, I have the function looking for items each day when it runs, between today - 1 year and timeInfo.ScheduledStatus.Last - 1 year, i.e. it only picks up those entries that fall within the window since the last job run

My problem is, I have tweaked the logic and need the job on next run to pick up all entries in the database more than 1 year old, i.e. ignore the scheduled status.Last.  Is there a way I can clear this value in Azure or will I have to make a temporary code change?

**Comment by kshyju** [comment]
> I have tweaked the logic and need the job on next run to pick up all entries in the database more than 1 year old, i.e. ignore the scheduled status.Last. Is there a way I can clear this value in Azure or will I have to make a temporary code change?

Hi @coredev123 Can you elaborate what your ask here is? Are you asking whether your logic (inside your function method) needs to be updated? There is no way for us to answer that question since we have no idea what your code does.

**Comment by coredev123** [comment]
Sorry @kshyju , I'm hoping to not have to update the function logic and instead manually (or in some way) clear the scheduledStatus.Last.  I'm wondering if a history of these runs are held somewhere in Azure that I could delete so the next time my function runs, when the code checks timerInfo.scheduledStatus.Last, it gets no results, despite the job running the previous night

**Comment by kshyju** [comment]
Yes, that state is stored somewhere. But It is not recommended to update that (the state which runtime relies on) from the customer code. That might cause unexpected behavior for your app.

You could consider keeping your own state management to track this data and update it as needed.
