### ISSUE TITLE
Function never completes when removing applicationInsights in host.json

### ISSUE THREAD

**Issue by mumurug-MSFT** [Azure/azure-functions-dotnet-worker#2250]
### Description

I have created an Azure Function in Visual Studio with default template and made changes for ASP.NET core integration as described in doc: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration. 

If I comment out `applicationInsights` in `host.JSON`, then Azure functions stuck in executing and never completes. `applicationInsights` is not mandatory as per my understanding from https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights and appears to be a bug.

**Output:**
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/95652148/36b56112-ec07-46fd-8518-8b9cdf55ffec)

Core Tools Version:       4.0.5504 
Function Runtime Version: 4.28.3.21820

### Steps to reproduce

Create a new Azure Function in Visual Studio (default template) and make changes as below:

**host.json**

``` json
{
  "version": "2.0",

  "logging": {
    //"applicationInsights": {
    //  "samplingSettings": {
    //    "isEnabled": true,
    //    "excludedTypes": "Request"
    //  },
    //  "enableLiveMetricsFilters": true
    //}
  }
}
```

**Program.cs**

``` csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
	.ConfigureFunctionsWebApplication()
	.ConfigureServices(services =>
	{
		//services.AddApplicationInsightsTelemetryWorkerService();
		//services.ConfigureFunctionsApplicationInsights();
	})
	.Build();

host.Run();
```

**Function1.cs**

``` csharp
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public class Function1
    {
        //private readonly ILogger<Function1> _logger;

        //public Function1(ILogger<Function1> logger)
        //{
        //    _logger = logger;
        //}

        [Function("Function1")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
        {
            //_logger.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult("Welcome to Azure Functions!");
        }
    }
}
```

**Output:**
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/95652148/d9dd9bde-1acf-438c-85d0-e025f2f31d32)

The issue was submitted based on discussion: https://learn.microsoft.com/en-us/answers/questions/1517505/azure-function-requires-applicationinsight-logging

[brokenfunction.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/14114409/brokenfunction.zip)

**Comment by mattchenderson** [comment]
@mumurug-MSFT Does this reproduce if you remove the section instead of adding comments in JSON? Comments in JSON are generally not safe.
