### ISSUE TITLE
The HttpContext should be directly injectable into an HttpTrigger function

### ISSUE THREAD

**Issue by 0xced** [Azure/azure-functions-dotnet-worker#2259]
### Description

When using the Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore integration, the 
[HttpContext](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext) should be directly injectable into an HTTP trigger function.

I know it can be accessed through the `GetHttpContext` extension method on the `FunctionContext` but I think the developer experience could be improved.

The [documentation](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration) gives this example:

```csharp
[Function("HttpFunction")]
public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequest req)
{
    return new OkObjectResult($"Welcome to Azure Functions, {req.Query["name"]}!");
}
```

When seeing that `HttpRequest` can be directly injected one could reasonably expect the same for the `HttpContext` but as of [version 1.2.1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/1.2.1) the injected `HttpContext` is `null`.

**Comment by kshyju** [comment]
`HttpRequest` has an `HttpContext` property. If function authors want to use HttpContext, they shall read from that property.

```csharp
[Function("Function1")]
public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequest req)
{
    HttpContext httpContext = req.HttpContext;
    return new OkObjectResult("Welcome to Azure Functions!");
}
```

Is that not enough?

**Comment by 0xced** [comment]
The [RequestDelgate](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.requestdelegate) is at the heart of ASP.NET Core. Even though it's a _request_ delegate its argument is an HttpContext. This sets some expectations in my opinion.

The HttpContext can indeed be accessed from the request or from the `FunctionContext` as mentioned in my original post. I still think that's not enough and that it's fair to expect it to be available directly in the function argument from a developer's perspective.

To me the question is why do you want the HttpContext **not** to be available directly? Inside an HTTP trigger and with the ASP.NET Core integration package it's inherently present, just not directly accessible. Do you see this as a maintenance burden?

**Comment by fabiocav** [comment]
> I still think that's not enough and that it's fair to expect it to be available directly in the function argument

Can you expand on why you don't believe that is sufficient? Would also be good to understand the expectation. The closer thing to compare the function to would be an ASP.NET Core action, and the behavior there is consistent.

> Do you see this as a maintenance burden?

Any public API/behavior is. This includes regression tests, scenario validation, documentation, etc. Framework alignment is also a concern.

**Comment by 0xced** [comment]
> Can you expand on why you don't believe that is sufficient? Would also be good to understand the expectation.

I though I just did. 😆 Maybe @SeanFeldman (who upvoted this issue) can also chime in and try to explain better than me?

> The closer thing to compare the function to would be an ASP.NET Core action.

When you say ASP.NET Core action, are you talking about _public methods on a controller, except those with the NonAction attribute_ as defined in the [documentation](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-8.0#action-definition)? If that's what you meant then it's a pretty strong argument in favor of having the HttpContext, which is [exposed on the controller](https://github.com/dotnet/aspnetcore/blob/v8.0.6/src/Mvc/Mvc.Core/src/ControllerBase.cs#L35-L48) along with the HttpRequest and the HttpResponse!

**Comment by fabiocav** [comment]
@0xced the model exposed by controllers is not analogous to what is being proposed here and the PR and does not rely on the binding pipeline.

For a justification, I don't think we have a clear articulation of why what is currently in place isn't sufficient and the experience improvement. So after discussing this with the team, we've decided to close this as _not planned_, at least for now.

Thanks for the discussion and collaboration here, though! Very much appreciated!
