### ISSUE TITLE
Unable to update Azure Functions to latest (and fixed version) 4.3.0

### ISSUE THREAD

**Issue by milen-denev** [Azure/azure-functions-dotnet-worker#2260]
### Description

I am stuck at runtime version 4.28.4.4. I am not sure who's responsibility is this but I am reporting this issue here. Also delete and re creating Azure Functions App doesn't help either.

### Steps to reproduce

N/A

**Comment by kshyju** [comment]
The deployment of 4.3.0 has not been completed. You do not need to take any explicit action to get that version (or any newer version of functions runtime), They will be automatically upgraded for you. Keep in mind that, creating a release on GH repo is one of the very first steps of deployment. It takes several days for the deployment & validations to be done. 

If you are experiencing an issue with host runtime, please open an issue in the [host repo](https://github.com/Azure/azure-functions-host).
