### ISSUE TITLE
Make Application Insights work Managed Identity authentication

### ISSUE THREAD

**Issue by Markz878** [Azure/azure-functions-dotnet-worker#2262]
### Description

Application Insights has now the possibility to use Managed Identity authentication (called disabling local authentication).
But Azure Function Application Insights packages "Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" and "Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" don't work with it. Or at least I can't get them to work by setting the "Monitoring Metrics Publisher" rbac role to my function app identity. When I enable "Local authentication" in Application Insights, the logs start working again.

Please add this feature to Azure Functions, or point to some documentation that describes how to make this work.

**Comment by mattchenderson** [comment]
This should be addressed by https://github.com/Azure/azure-functions-dotnet-worker/pull/2217

**Comment by Markz878** [comment]
I found out that I have to add this line to the config code:         
```
builder.Services.Configure<TelemetryConfiguration>(c => c.SetAzureTokenCredential(new ManagedIdentityCredential()));
```
Now it works.
