### ISSUE TITLE
EnableUserCodeException with AspNet Core Integration - ConfigureFunctionsWebApplication

### ISSUE THREAD

**Issue by middiu** [Azure/azure-functions-dotnet-worker#2268]
### Description

Hello there, 

reading the Isolated Function App [documentation ](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#logging)it seems we can enable User Code Exception using the code

````
.ConfigureFunctionsWorkerDefaults(builder => {}, options =>
    {
        options.EnableUserCodeException = true;
    })
````

In our case we are using ConfigureFunctionsWebApplication because of AspNet Core Integration, and I don't see any way to set EnableUserCodeException to true.
I don't see any method overload that allow me to do so.

I also tried to combine ConfigureFunctionsWorkerDefaults and ConfigureFunctionsWebApplication (which I know already is not correct anyway) but I could not find a working solution.

Any suggestions/feedback/reccomendation or code snippet?

Thanks and Regards

### Steps to reproduce

use ConfigureFunctionsWebApplication in your Program.cs and try to find an overload that allow to set EnableUserCodeException = true;

**Comment by j-mok** [comment]
These options follow the regular options pattern, so you can configure them like that:
```
.ConfigureServices(services =>
{
    services.Configure<WorkerOptions>(options =>
    {
        options.EnableUserCodeException = true;
    });
}
```

**Comment by satvu** [comment]
Closing as answered

**Comment by mygithubsanthiya** [comment]
Hi team,
We converted Orchestrator Durable functions into isolated worker model .net 8. We are getting the below exception Invoke TimeOut exception as the below screenshot says. 
Program.cs
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        services.Configure<WorkerOptions>(options =>
        {
            options.EnableUserCodeException = true;
        });
        services.Configure<LoggerFilterOptions>(options =>
        {
            // The Application Insights SDK adds a default logging filter that instructs ILogger to capture only Warning and more severe logs. Application Insights requires an explicit override.
            // Log levels can also be configured using appsettings.json. For more information, see https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs
            LoggerFilterRule toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
            if (toRemove is not null)
            {
                options.Rules.Remove(toRemove);
            }
        });
    })
    .Build();

await host.RunAsync();
![image](https://github.com/user-attachments/assets/047bc874-16d9-450b-9983-c46cb836aee2)

How to resolve the issue

**Comment by mygithubsanthiya** [comment]
Hi middiu,

how can we EnableUserCodeException for the Asp Net core integration. Because we are getting TimeOut Exception and Rpc Exception after we converted Durable functions into Isolated worker model. Any guidance please.

**Comment by mygithubsanthiya** [comment]
> Hi middiu,
> 
> how can we EnableUserCodeException for the Asp Net core integration. Because we are getting TimeOut Exception and Rpc Exception after we converted Durable functions into Isolated worker model. Any guidance please.

**Comment by peterno** [comment]
@mygithubsanthiya and others.
The timeout issues in .net 8 isolated are tracked in this issue: https://github.com/Azure/azure-functions-dotnet-worker/issues/2610
