### ISSUE TITLE
Azure function attribute in interfaces...

### ISSUE THREAD

**Issue by bzuidgeest** [Azure/azure-functions-dotnet-worker#2283]
### Description

I was trying to put the attributes for the azure functions in an interface, but I discovered the framework doesn't support this. It tries to instantiate the interface. 
The reason I was hoping this would be allowed was that this way I can provide just the interface to programmers, let them implement the logic, without having to think about al the azure function trappings. If the interface is auto generated I might prevent a lot of types and errors that way. With the correct devops policies in place they would not be able to edit the attributes.
It should be technically possible for the framework that when it finds attributes in interfaces to look for an implementation of that interface and instantiate that. 
Maybe this is considered abuse of the idea of interfaces, but the idea seemed practical to me. 

An example from the interface:
```
  public interface IFrontEndProvider
  {
      [Function("GetGrades")]
      public Task<IActionResult> GetGrades([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "{Backend}/GetGrades")] HttpRequest req, string backend, string username);
}
```
implementing class
```
 public async Task<IActionResult> GetGrades(HttpRequest req, string backend, string username)
 {
    
     return new OkObjectResult(10);
 
 }
```

**Comment by fabiocav** [comment]
@bzuidgeest can you please share more information about the use case you're trying to enable? In the example above, all implementations would share the same function name (one of the issues), but I would like to better understand the problem you're trying to solve so we can discuss whether this would be the right solution.
