### ISSUE TITLE
Version 1.17.0 breaks solution builds using no-incremental

### ISSUE THREAD

**Issue by skystedt** [Azure/azure-functions-dotnet-worker#2284]
### Description

Building a solution with flag `--no-incremental` while having a test project referencing a functions project will result in the build failing with
`MSB3030: Could not copy the file "obj\Debug\net8.0\extensions.json" because it was not found.`

Using Microsoft.Azure.Functions.Worker.Sdk 1.16.4 => works
Using Microsoft.Azure.Functions.Worker.Sdk 1.17.0 => does not work

Building without any flags => works
Building with `--no-incremental` => does not work.

Building each individual project => works
Building the solution => does not work

### Steps to reproduce

1. Create a solution with a new functions project
   - Functions worker: .NET 8.0 Isolated
   - Function: Empty
2. Add a xunit test project
3. Add a project reference in the test project targeting the functions project
4. Use `Microsoft.Azure.Functions.Worker.Sdk` `1.17.0`
5. build with: `dotnet build --no-incremental solution.sln`

**Comment by jeromekol** [comment]
same issue here

**Comment by kshyju** [comment]
Thanks for reporting the issue @skystedt . We released a new version of Microsoft.Azure.Functions.Worker.Sdk package which includes a fix for this issue. Could you please upgrade to that version? 

https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.2

**Comment by skystedt** [comment]
The new version solves the issue.
Thanks!

**Comment by robmaas** [comment]
@kshyju This was working in `1.17.2` but is broken again in versions `1.17.3` and `1.17.4`.

**Comment by pregress** [comment]
`1.18` also broken. Similar issue as: https://github.com/Azure/azure-functions-dotnet-worker/issues/2722

Would be nice If they would finally create a test case for this instead of just breaking every possible build.

**Comment by robmaas** [comment]
Still broken in `2.0.0`

**Comment by pregress** [comment]
> Still broken in `2.0.0`

Following pull request should fix it: https://github.com/Azure/azure-functions-dotnet-worker/pull/2763

**Comment by jmaczan** [comment]
Is there any known workaround for `2.0.0`, where it is still broken?

**Comment by pregress** [comment]
> Is there any known workaround for `2.0.0`, where it is still broken?

You can pass `-m:1` to your dotnet publish / dotnet build

https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#switches

**Comment by jmaczan** [comment]
@pregress Thank you!
