### ISSUE TITLE
Be able to disable Invoke Telemetry

### ISSUE THREAD

**Issue by ChoOo7** [Azure/azure-functions-dotnet-worker#2296]
### Description

Hello

We are using c# isolated azure function
Our application insight is full of Invoke dependency, initiated by this code
https://github.com/Azure/azure-functions-dotnet-worker/blob/d47013f54dee5eefb43edbd2e9612d73a6beb53a/src/DotNetWorker.Core/Diagnostics/FunctionActivitySourceFactory.cs#L12

We didn't found a way to disable it

Can you help us please ? 

Thanks

**Comment by tchuan** [comment]
We have similar issue. There is a health check endpoint based on http trigger, function log is disabled in host.json via Function.HealthCheckTrigger = Warning, but there are lots of Invoke logs still showing in AppInsights.

**Comment by jeromekol** [comment]
I found this github repo that has an example implementation to disable that invoke log: https://github.com/RohitRanjanMS/ApplicationInsightsDemo/blob/main/Isolated/IsolatedApplicationInsightsDemo/CustomTelemetryProcessor.cs

worked for me

**Comment by aishwaryabh** [comment]
Closing issue since workaround has been shared

**Comment by ChoOo7** [comment]
Hello

Indeed its working, thanks

We are doing some strage stuff on our side, and we can't use
AddApplicationInsightsTelemetryProcessor

because of

Erreur	CS0121	L'appel est ambigu entre les méthodes ou propriétés suivantes : 'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)' et 'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)'	XX.Http.Core.AzureFunction	C:\code\XX\deployed\azure-function\Sociabble.Http.Core.AzureFunction\Program.cs	60	Actif


So we are doing

services.AddSingleton((Func<IServiceProvider, ITelemetryProcessorFactory>)((IServiceProvider serviceProvider) => new CopiedTelemetryProcessorFactory(serviceProvider, typeof(ApplicationInsightsFilterProcessor))));



Where CopiedTelemetryProcessorFactory is a copy and past of the one of the lib

using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.ApplicationInsights.WorkerService;
using Microsoft.Extensions.DependencyInjection;

namespace XX.Http.Core.AzureFunction;
public class CopiedTelemetryProcessorFactory: ITelemetryProcessorFactory
{
    private readonly IServiceProvider serviceProvider;
    private readonly Type telemetryProcessorType;

    /// <summary>
    /// Initializes a new instance of the <see cref="TelemetryProcessorFactory"/> class.
    /// </summary>
    /// <param name="serviceProvider">The service provider.</param>
    /// <param name="telemetryProcessorType">The type of telemetry processor to create.</param>
    public SociabbleTelemetryProcessorFactory(IServiceProvider serviceProvider, Type telemetryProcessorType)
    {
        this.serviceProvider = serviceProvider;
        this.telemetryProcessorType = telemetryProcessorType;
    }

    /// <inheritdoc />
    public ITelemetryProcessor Create(ITelemetryProcessor next)
    {
        return (ITelemetryProcessor)ActivatorUtilities.CreateInstance(this.serviceProvider, this.telemetryProcessorType, next);
    }
}


If it's can help someone

**Comment by RobTF** [comment]
The workaround spams exceptions.

![image](https://github.com/user-attachments/assets/32ad2071-106f-45f7-a000-b3dc6b645134)
