### ISSUE TITLE
Isolated-worker Azure Function in .NET 8 unable to use Newtonsoft.Json for objects with enums?

### ISSUE THREAD

**Issue by kwaksaewon** [Azure/azure-functions-dotnet-worker#2304]
### Description

Hi all, I'm trying to migrate from .NET Core 3.1, Azure Function V3, Cosmos DB SDK V2 to use isolated-worker process .NET 8, Azure Function V4, Cosmos DB SDK V3. I'm having trouble running CosmosDBTrigger if the object I want to deserialize to contains an enum property that uses Newtonsoft.Json's `StringEnumConverter`.

### Background:
This is the Example Azure Function:
```
[FunctionName("FunctionName"))]
public void Run(
    [CosmosDBTrigger(
    databaseName: "main",
    collectionName: "settings", ...)]
IReadOnlyList<ExampleClass> input, ILogger log)
{
...
// content of the azure function
}
```

ExampleClass contains a definition like this, with a string property and an enum property that uses Newtonsoft.Json's `StringEnumConverter`
```
public class ExampleClass
{
    public string Id { get; set; }

    [JsonConverter(typeof(StringEnumConverter), true)]
    public ColorType ColorType { get; set; }
}
```
and the ColorType has enum definitions like these:

```
public enum ColorType 
{
    Red,
    Green,
}
```
-------
### Problem: 
Although I've configured my Program.cs to use the [UseNewtonsoftJson configuration](https://github.com/Azure/azure-functions-dotnet-worker/blob/16a995deb65b44873cd3a56b5e6d4d3c22d64b7d/samples/Configuration/Program.cs#L58C124-L58C124), the content of the azure function is not invoked. However, if I change the ColorType to use `System.Text.Json`'s `JsonStringEnumConverter`, the content of the azure function is invoked. I even added Newtonsoft.Json's `StringEnumConverter()` to `settings.Converters`, in my copied code from [UseNewtonsoftJson configuration](https://github.com/Azure/azure-functions-dotnet-worker/blob/16a995deb65b44873cd3a56b5e6d4d3c22d64b7d/samples/Configuration/Program.cs#L58C124-L58C124). Is there anything I'm overlooking?

```
public static IFunctionsWorkerApplicationBuilder UseNewtonsoftJson(this IFunctionsWorkerApplicationBuilder builder)
{
    builder.Services.Configure<WorkerOptions>(workerOptions =>
    {
        var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
        settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
        settings.NullValueHandling = NullValueHandling.Ignore;
        settings.Converters.Add(new StringEnumConverter()); // I added this to my copied code, still doesn't work
        workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);

    });

    return builder;
}

```

**Comment by spplante** [comment]
I also can't figure out how to make it use Newtonsoft as default. I followed the exact documentation and simply nothing happens.

**Comment by liliankasem** [comment]
@kwaksaewon - in your Program.cs, are you using `ConfigureFunctionsWebApplication`? If so, it looks like there is a bug that we are using the following issue to track:

- https://github.com/Azure/azure-functions-dotnet-worker/issues/2403

**Comment by kwaksaewon** [comment]
> @kwaksaewon - in your Program.cs, are you using `ConfigureFunctionsWebApplication`? If so, it looks like there is a bug that we are using the following issue to track:
> 
> * [Unable to use Newtonsoft as default serializer #2403](https://github.com/Azure/azure-functions-dotnet-worker/issues/2403)

Yeah

**Comment by liliankasem** [comment]
Thanks for confirming! I will close this as a dupe and we can use #2403 to track the resolution of this issue.
