### ISSUE TITLE
Bug in Microsoft.Azure.Functions.Worker.Sdk 1.17.0: function from dependencies are not loaded

### ISSUE THREAD

**Issue by GergelyGlasz** [Azure/azure-functions-dotnet-worker#2306]
### Description

Having 2 function projects with the following setup:
1. without function and function configuration files (*.json), Program.cs exists and a project reference to the 2nd project
2. complete function app with function and configuration

Starting the 1st project, the functions from the 2nd project are not found/loaded. To load the functions from the 2nd project, the 1st project must have an implemented function.

Downgrading the NuGet to the version **1.16.4** solves the problem: the functions are loaded from the 2nd project without workarounds or any configuration in the 1st project.

### Steps to reproduce

The issue can be reproduced with the solution: [FunctionAppNet8](https://github.com/GergelyGlasz/FunctionAppNet8)
Ongoing discussion can also be found here: [StackOverflow](https://stackoverflow.com/questions/78067439/net-8-function-app-doesnt-load-functions-from-dependencies)

**Comment by kshyju** [comment]
[Microsoft.Azure.Functions.Worker.Sdk 1.17.1](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.17.1) was released earlier today which includes a fix for this issue.

Please update your function app to consume Microsoft.Azure.Functions.Worker.Sdk package 1.17.1.
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.1

If you encounter any further issues with the .NET isolated model, please let us know. Thanks for your patience.

**Comment by GergelyGlasz** [comment]
I updated to the new **1.17.1** version, but the issue is just partially solved:
- **TimerTrigger** functions from the project reference are loaded and started
- **QueueTrigger** functions from the project reference are loaded but cannot be started
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/131148843/31cade72-86ac-41d4-8502-b28ca39fd7aa)
I updated my example repo here: [FunctionApp Net8](https://github.com/GergelyGlasz/FunctionAppNet8)

I currently have a workaround for the QueueTrigger: I can add a dummy/empty QueueTrigger in the "main/startup" project. With the help of this, all the other QueueTrigger functions are started without any issues from the project references as well.
