### ISSUE TITLE
Message loss when using Microsoft.Azure.Functions.Worker.Extensions.EventHubs

### ISSUE THREAD

**Issue by simonvandermeer** [Azure/azure-functions-dotnet-worker#2311]
### Description

We have noticed we're sporadically losing messages in our event hub subscription components. It seems to be related to periods when the function runtime is throwing transient errors or restarting or scaling.

I think this might have to do with `Microsoft.Azure.Functions.Worker.Extensions.EventHubs` referencing a version of `Microsoft.Azure.WebJobs.Extensions.EventHubs` containing a race condition. See [https://github.com/Azure/azure-sdk-for-net/issues/41784](https://github.com/Azure/azure-sdk-for-net/issues/41784) for context. This issue was fixed in version `6.1.0` of `Microsoft.Azure.WebJobs.Extensions.EventHubs`.

### Steps to reproduce

Don't have a repro as it seems to be happening sporadically.

**Comment by satvu** [comment]
6.2.0 Released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs
