### ISSUE TITLE
[Docs] Add docs for new HTTP output binding

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#2323]
Docs update needed for changes in #2322 prior/alongside the official release of those changes.

**Comment by mattchenderson** [comment]
This will need:

- Update to HTTP example in multi-output reference
- Update to the HTTP trigger reference
- Update to the HTTP output reference

**Comment by fabiocav** [comment]
Flagging a dependency on releasing the work done in #2322

**Comment by fabiocav** [comment]
Done.
