### ISSUE TITLE
Middleware is not consistently writing the response when using ASP.Net Core Integration

### ISSUE THREAD

**Issue by dougq-PureGym** [Azure/azure-functions-dotnet-worker#2325]
### Description

I have written some authentication middleware for an Azure Function App using the Isolated Process model with ASP.NET Core integration. On failure to authenticate I am returning a 401 with the following code

```
var req = await context.GetHttpRequestDataAsync();

var res = req.CreateResponse(HttpStatusCode.Unauthorized);

var invocationResult = context.GetInvocationResult();

invocationResult.Value = res;
```

This works fine locally, but when deployed to Azure, it is only working intermittently. Sometimes the function will return a 401 response, but sometimes it will return a 200. At no point is the function itself being invoked.  Some things I have noticed

- Switching off the ASP.NET Core integration (using ConfigureFunctionsWorkerDefaults and removing the reference to Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore) fixes the problem
- I can set the 401 response either by assigning the HttpResonseData to invocationResult.Value, or by setting it in the HttpContext returned by context.GetHttpContext(), but both methods exhibit the same problem
- When the function is first deployed, it consistently returns a 401, but after being called repeatedly we start seeing 200s. The likelihood of a 200 seems to increase over time.
- Logging has confirmed that the MIddleware is being called successfully and the code above is being run to completion.

Here is the minimum reproduction repository https://github.com/dougq-PureGym/AzFuncHttpRewrite

I am using the latest version of app packages and .Net 8.

### Steps to reproduce

- Enable ASP.Net integration in an Azure Function APP
- Create an implementation of IFunctionsWorkerMiddleware which sets the HTTP Response by assigning to invocationResult.Value
- Add the Middleware to ConfigureFunctionsWebApplication

**Comment by satvu** [comment]
Hi @dougq-PureGym can you also share your function app privately using [these instructions](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately/5c568a803f217d0b0f6adc15e2f82c1d56b05c8d)? We would like to observe the reported behavior in production to aid investigation.

**Comment by dougq-PureGym** [comment]
Thanks for the response, the Execution Time is 2024-03-06T10:24:29Z, ID is f9f61248-1c85-4da2-938a-ebfedb5f0bac, region is UK South.

Please note, this is not a production app, the error was found in QA so not deployed to production. This is just the minimal reproduction repo I supplied earlier.

One thing we have noticed during testing is that the problem can vary a lot over time. Sometimes 200s are relatively rare, maybe 5% of responses, other times they are over 50%.

Thanks

**Comment by dougq-PureGym** [comment]
On further investigation it appears that this is not Middleware related. We are seeing intermittent 200 responses no matter how we construct the Response, whether in Middleware or in the Function itself. This appears to be a duplicate of this issue - https://github.com/Azure/azure-functions-dotnet-worker/issues/2215 although we are seeing the problem a lot more often that is mentioned in that report

**Comment by satvu** [comment]
Thanks for the follow up @dougq-PureGym - we will continue investigating.

**Comment by jamesmcroft** [comment]
@satvu @dougq-PureGym I've also been having a look into this to try and diagnose the issue.

It appears that something is happening in the processing of the response as part of the invocation result based on the Function declaration.

In my initial experimenting, if you throw an exception instead, e.g. an `UnauthorizedAccessException`, you will consistently see a failure in the request as a 500 response. However this isn't ideal if you want to control the response code. 

[On a fork of the provided sample](https://github.com/jamesmcroft/AzFuncHttpRewrite/tree/testing), I have also experimented with alternative approaches and appear to no longer see the 200 status code.

Firstly, I attempted to write a JSON response into the middleware when setting the value of `GetInvocationResult` which reduced the frequency of the 200.

I then moved on to swapping from `IActionResult` to `Task<HttpResponseData>` in the response type for the Function, as well as swapping the request body parameter from `HttpRequest` to `HttpRequestData` and this seemed to remove the issue entirely in my testing.

I cannot confirm what is necessarily causing this at this stage and why the change appears to resolve the issue but I will also continue to investigate.

**Comment by lnhzd** [comment]
We are hitting the same issue without using invocationResult:

 var httpContext = context.GetHttpContext();
 await httpContext.ForbidAsync();
 return;

Expecting 403 but roughly got 1 or 2 (empty) 200 responses out of 20 requests sent.

**Comment by lnhzd** [comment]
> @satvu @dougq-PureGym I've also been having a look into this to try and diagnose the issue.
> 
> It appears that something is happening in the processing of the response as part of the invocation result based on the Function declaration.
> 
> In my initial experimenting, if you throw an exception instead, e.g. an `UnauthorizedAccessException`, you will consistently see a failure in the request as a 500 response. However this isn't ideal if you want to control the response code.
> 
> [On a fork of the provided sample](https://github.com/jamesmcroft/AzFuncHttpRewrite/tree/testing), I have also experimented with alternative approaches and appear to no longer see the 200 status code.
> 
> Firstly, I attempted to write a JSON response into the middleware when setting the value of `GetInvocationResult` which reduced the frequency of the 200.
> 
> I then moved on to swapping from `IActionResult` to `Task<HttpResponseData>` in the response type for the Function, as well as swapping the request body parameter from `HttpRequest` to `HttpRequestData` and this seemed to remove the issue entirely in my testing.
> 
> I cannot confirm what is necessarily causing this at this stage and why the change appears to resolve the issue but I will also continue to investigate.

Tried this approach, unfortunately still seeing intermittent 200 from my side.

`                //var req = await context.GetHttpRequestDataAsync();
                //var res = req.CreateResponse(HttpStatusCode.Unauthorized);
                //await res.WriteAsJsonAsync(new { Status = "Unauthorized", Message = "Unauthorized access." }, res.StatusCode);
                //context.GetInvocationResult().Value = res;`

**Comment by satvu** [comment]
> On further investigation it appears that this is not Middleware related. We are seeing intermittent 200 responses no matter how we construct the Response, whether in Middleware or in the Function itself. This appears to be a duplicate of this issue - #2215 although we are seeing the problem a lot more often that is mentioned in that report

Closing this in favor of #2215 as we believe it's the same root issue - @lnhzd please follow the other issue for updates.
