### ISSUE TITLE
SignalR extensions 1.13.0 Could not load file or assembly 'Microsoft.Extensions.Options, Version=7.0.0.0,

### ISSUE THREAD

**Issue by the-programmer** [Azure/azure-functions-dotnet-worker#2333]
### Description

Currently I have the feeling that both 1.12.0 and 1.13.0 still have the issue as described in #1709

For the analysis that was done in that specific issue I don't have the skills but here is what I found.
When using version 1.13.0 the function app generates an Exception `Exception while executing function: Function <--- Could not load file or assembly 'Microsoft.Extensions.Options, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.` I tried adding `Microsoft.Extensions.Options` to the packakes list (Both 7.0.0.0 and the latest), however that failed.
Using version 1.12.0 also results in `Exception while executing function: Function <--- Could not load file or assembly 'Microsoft.Extensions.Options, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

Only if I use 1.7.0 is this issue resolved.

### Steps to reproduce

Note: I didn't test this exact setup but I think the environment should be clear.

- Create a new a new Function App with Runtime .NET 8 (LTS) isolated worker model on windows.
- Install the nuget Microsoft.Azure.Functions.Worker.Extensions.SignalRService
- Create a function that returns a single object that, in turn contains multiple outputs
- Publish the function to Azure
- Trigger the function and in the Live metrics an exception is generated

In this project I use the following function definition:
```C#
[Function("AFunction")]
public Response Run(
    [CosmosDBTrigger(databaseName: "Database",
                     containerName: "InContainer",
                     Connection = "CosmosDbConnectionString",
                     LeaseContainerName = "Leases")] IReadOnlyList<Document> documents)
{
    var documents = new List<OutputDocuments>();
    var actions = new List<SignalRMessageAction>();

    //Some code to fill the documents and the actions

    return new Response()
    {
        OutputDocuments = documents,
        Actions = actions,
    };
}
```
The `Response` class contains something similar to this
```C#
    public class Response
    {
        [CosmosDBOutput(databaseName: "Database", containerName: "OutContainer", Connection = "CosmosDbConnectionString")]
        public IReadOnlyList<OutputDocuments>? OutputDocuments { get; set; }

        [SignalROutput(ConnectionStringSetting = "AzureSignalRConnectionString", HubName = "TestHub")]
        public IReadOnlyList<SignalRMessageAction>? Actions { get; set; }
    }
```

### Comments
While debugging, I noticed that the exception only occurs after the `Run` method returned.

**Comment by Y-Sindo** [comment]
Could you please update packages "Microsoft.Azure.Functions.Worker" and "Microsoft.Azure.Functions.Worker.Sdk" to the latest version and have a retry? If it's still not working, please provide a minimal reproducible project.

**Comment by the-programmer** [comment]
As requested I just tried with all the latest versions for all the packages.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/3088971/bdd05213-5306-4ced-ac00-076fe894718e)

This time it seems to be working ok.
