### ISSUE TITLE
Inject class-based SignalR ServerlessHub to other Azure Function classes

### ISSUE THREAD

**Issue by Zaratusa** [Azure/azure-functions-dotnet-worker#2337]
### Description

Hi,

I'm using the class-based SignalR `ServerlessHub`, which I added via `AddServerlessHub` to my services. I want to send messages through the hub from other Azure Functions so I don't have to add all functions to the hub, but my custom ServerlessHub `PubSubHub` can't be injected into any other classes. Is there a work-around for it?

### Steps to reproduce

Create a derived class from `ServerlessHub<IClientProxy>` and inject your custom hub class into any other Azure Function class.

**Comment by Y-Sindo** [comment]
As a workaround, you can inject `IServiceProvider` into your function classes, and uses `ActivatorUtilities.CreateInstance<ServerlessHubOfT>(ServiceProvider)` to create an instance of the derived class from `ServerlessHub<T>`, then access the members of it.

**Comment by satvu** [comment]
Closing as answered.
