### ISSUE TITLE
In SDK, load attributes to generate metadata

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#234]
Our SDK avoids needing to instantiate any types, but this can make it more difficult for us to give binding extension authors better support for attributes.

See note here: https://github.com/Azure/azure-functions-dotnet-worker/blob/1c613b0faad836ec53edbd37d58309dec39b1197/sdk/Sdk/CustomAttributeExtensions.cs#L18

**Comment by fabiocav** [comment]
Closing stale issues.
