### ISSUE TITLE
HttpTrigger Model Binding gives null v1.17.2

### ISSUE THREAD

**Issue by MrAntix** [Azure/azure-functions-dotnet-worker#2345]
### Description

I am getting a null when binding using ```[HttpTrigger(...)] MyModel model``` 

However, if I use ```[HttpTrigger(...)] HttpRequest request```  I can deserialize the body in to my model

Using a custom type from [Docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-csharp#payload)

### Steps to reproduce

- Create a Functions Worke App with a HttpTrigger Function using 1.17.2 SDK
- Create a model and use as an argument type with the trigger attribute
- Call the function over http
- Breakpoint shows that the model is null

```c#
public sealed record MyModel(int Id);

[Function(nameof(IncomingAsync))]
public static async Task<IActionResult> IncomingAsync(
    [HttpTrigger(
        AuthorizationLevel.Anonymous,
        WebRequestMethods.Http.Post,
        Route = ROUTES.INCOMING)] MyModel model)
{
...
}
```

**Comment by satvu** [comment]
Hi @MrAntix, does the following work?

```
public sealed record MyModel(int Id);

[Function(nameof(IncomingAsync))]
public static async Task<IActionResult> IncomingAsync(
    [HttpTrigger(
        AuthorizationLevel.Anonymous,
        WebRequestMethods.Http.Post,
        Route = ROUTES.INCOMING)] HttpRequest req, [FromBody] MyModel model)
{
...
}
```

Note the use of the `[FromBody]` attribute - there are additional requirements outlined [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-csharp#payload) for using this attribute.

**Comment by MrAntix** [comment]
Hi @satvu 

No that's null too.
See here https://github.com/MrAntix/sandbox-http-trigger-custom-type

**Comment by satvu** [comment]
Closing as answered.

**Comment by MrAntix** [comment]
Hi @satvu 

I didn't ask a question about how I could do this another way, I raised a bug.
Closing this won't get it fixed.

The docs say

"The trigger input type is declared as one of the following types:"
"A custom type | When the body of the request is JSON, the runtime will try to parse it to set the object properties."

Doing this give a null.

Please review
