### ISSUE TITLE
Upgrade to version 1.16.0 generates error CS0246

### ISSUE THREAD

**Issue by duthieg** [Azure/azure-functions-dotnet-worker#2353]
### Description

After upgrading to any version greater than 1.15.1 I get build error  CS0246 on any azure functions that have generic type arguments

Example:
Error CS0246	The type or namespace name 'TModelCreate' could not be found (are you missing a using directive or an assembly reference?) - GeneratedFunctionExecutor.g.cs

In the generated **GeneratedFunctionExecutor.g.cs** file, the  **_functionActivator.CreateInstance** method throws this error on any method that has generic type arguments

VS:2022
TargetFramework: net8.0

Works as expected if I downgrade to version 1.15.1

### Steps to reproduce

Check out/download this Github project: **https://github.com/etheone/abstract-functions-sample**, build it in VS2022 to see it build successfully. Then update Microsoft.Azure.Functions.Worker.Sdk to any version greater than 1.15.1 (currently it's version 1.11.0) and build it again to see a large number of CS0246 errors in GeneratedFunctionExecutor.g.cs. This isn't one of my projects, but it perfectly demonstrates the problem.

**Comment by kshyju** [comment]
This use case is not currently supported. Even with 1.11.0 (your repro app), it will fail at runtime when trying to execute the function. Is that not what you are seeing?

**Comment by duthieg** [comment]
Thanks for your response. I didn't know that isolated/integrated functions didn't support generic type arguments. I hadn't yet got as far as running the function. When I wrote "Works as expected if I downgrade to version 1.15.1", that was misleading, apologies for that. What I meant was it compiled as expected.  Since it's unsupported, I shall stop and this issue can be closed/resolved
