### ISSUE TITLE
Cannot read ASPNETCORE_ENVIRONMENT while migrating with .net8

### ISSUE THREAD

**Issue by IAMManuel** [Azure/azure-functions-dotnet-worker#2359]
Since the .net7 version will not be supported in May, we started upgrading our working solution to .net 8. We did follow the [documentation ](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows) thoroughly

We did switch `ConfigureFunctionsWorkerDefaults` to `ConfigureFunctionsWebApplication` and change the solution to an AspNetCore integration. It works fine as is when testing it locally. But when we deploy it, we always have issue when the program try to read the good `appsettings.json` file.

The application in production runs on a Linux environment while for testing locally, it's on a Windows environment.

**Comment by kshyju** [comment]
@IAMManuel You have not shared your bootstrapping code, so it is hard to say what is missing. 

Make sure you are calling `SetBasePath(Directory.GetCurrentDirectory())` on `IConfigurationBuilder`. Without, that, the files are not properly located in Linux env.  [Here](https://github.com/kshyju/MoreDotnetIsolatedSamples/tree/master/AspNetWithDocker) is a working  minimal app with docker support where appsettings.json is added as a config source. Please refer that.
