### ISSUE TITLE
Logs sometimes going missing in isolated worker

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [Azure/azure-functions-dotnet-worker#2368]
### Description

I have migrated a .NET 6 in-process function app to a .NET 8 isolated app, following the migration guide at https://learn.microsoft.com/en-au/azure/azure-functions/migrate-dotnet-to-isolated-model.

Like many others, I have had issues with logging.

My current setup looks like:

```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();

        // other DI
    })
    .ConfigureLogging(logging =>
    {
        // try to force Information logs for our name spaces
        logging.AddFilter("Orchestration.FnApp", LogLevel.Information);
        logging.AddFilter("Orchestration.Core", LogLevel.Information);

        // try to force Information logs for our name spaces
        logging.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("Orchestration.FnApp", LogLevel.Information);
        logging.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("Orchestration.Core", LogLevel.Information);
    })
    .Build();
```

With the logging filters used to override ApplicationInsights dropping all logs below warning (I think only the second filter is required). We only want our code logging at Information level, so this should be ok.

The package versions are:
```
    <PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.3.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.2.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
```

I now have 2 issues outstanding, one of which is a big problem, one a nice to have.

The big issue is that sometimes logs just don't turn up in Application Insights. For example, I have a timer function which looks similar to below, where the first thing it does is log the time:
```csharp
public class TimerFunction
{
    private readonly ILogger<TimerFunction> _logger;

    public TimerFunction(ILogger<TimerFunction> logger)
    {
        _logger = logger;
    }

    [Function("TimerFunction")]
    public async Task RunTimerFunction([TimerTrigger("0 */15 * * * *")] TimerInfo myTimer)
    {
        var scheduleTime = RoundToNearest(DateTime.UtcNow, TimeSpan.FromMinutes(15));
        _logger.LogWarning("Schedule time: {scheduleTime}", scheduleTime);

       // rest of code
    }
}
```

Sometime we see the log:

<img width="1165" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/754824/e00cc3ae-dfe7-42a5-9a47-e92ddaa872b0">

Sometimes we don't:

<img width="1183" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/754824/bc72b43e-7442-4f9e-aa49-2eb532f47162">

There doesn't seem to be any pattern to this. As far as I can see, this should be logging regardless of any Application Insights settings since it is at the Warning level.

This was also mentioned here: https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1372630620, but didn't seem to get followed up.

The second, nice to have issue is the missing log level or Type, seen in the screenshots above. This was mentioned here:
https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1332902091

With the solution here: https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1347216293 was to use a ITelemetryInitializer. A clear example of this would be useful!

### Steps to reproduce

Run the app as described above on .NET 8 isolated.

**Comment by jeffw-wherethebitsroam** [comment]
@winterlimelight our function seems to be executing fine. We just get no logs about 50% of the time. Our function is running on Linux, so no eventlog.xml. I can't see any evidence of crashing in any of the available logs, but it is not obvious where to look.

**Comment by jeffw-wherethebitsroam** [comment]
To illustrate the problem, here are the log counts for the last 4 hours using the query:

```
traces
| where timestamp > ago(4h)
| where operation_Name =~ 'TimerFunction' or customDimensions['AzureFunctions_FunctionName'] =~ "TimerFunction"
| order by timestamp asc
| summarize min(timestamp), count() by tostring(customDimensions['InvocationId'])
```

Where host logs appear to use `operation_Name` and worker logs use `customDimensions['AzureFunctions_FunctionName']`.

| InvocationId | Timestamp | Count |
| -------------|------------|-------|
a920e7b2-9db6-487f-a454-0d722fbc9699 | 03/04/2024, 2:29:59.998 pm | 49
21f7a510-e1a2-41f9-a639-0ea73a42cac3 | 03/04/2024, 2:14:59.999 pm | 2
a2af64d5-4948-472c-8ec0-46d2c2ec1adf | 03/04/2024, 2:00:00.005 pm | 49
b7bf0cf7-1c3b-4552-8538-bf9b39a79853 | 03/04/2024, 1:44:59.998 pm | 49
3550dac3-fb17-4982-b43d-6618e6b44740 | 03/04/2024, 1:30:00.003 pm | 49
8542bf15-984d-4d3d-827e-e7d4874ba65f | 03/04/2024, 1:15:00.001 pm | 2
2ddd30bf-7fac-4f12-8359-31cc6e80081d | 03/04/2024, 1:00:00.003 pm | 49
5b613622-9ce3-4b93-90df-bc6aa20a5b4a | 03/04/2024, 12:44:59.997 pm | 2
24350fbf-1dc0-4653-8ec5-5d0877feab2f | 03/04/2024, 12:29:59.999 pm | 2
705981a0-196c-4a25-a359-68a4b4af3db0 | 03/04/2024, 12:15:00.003 pm | 49
c56d9763-0b09-4382-bd5e-f9577c014ec5 | 03/04/2024, 12:00:00.004 pm | 49
2cdc4533-cf41-4716-8d38-868832d23c1b | 03/04/2024, 11:45:00.006 am | 49
1664e1ed-3ef8-4327-ac9a-1246d3df96a6 | 03/04/2024, 11:30:00.008 am | 2
d1fccdab-666f-47b3-8dfe-2b9636ba40c0 | 03/04/2024, 11:15:00.004 am | 2
f154b39c-6a36-46ea-a765-c868478a07fc | 03/04/2024, 11:00:00.001 am | 49
4440ef96-46b2-4a02-b80f-658ed84595b2 | 03/04/2024, 10:45:00.002 am | 2

Where the count of 2 means we just got the host logs. A count of 49 means we got the logs from both host and worker.

**Comment by andrew-flatters-bliss** [comment]
Check that within Application Insights you haven't got sampling turned on (Should be "All Data 100%" or some info maybe not put into the long term store of App Insights. 

https://learn.microsoft.com/en-us/azure/azure-monitor/app/sampling-classic-api

**Comment by jeffw-wherethebitsroam** [comment]
There is no sampling applied within application insights:

<img width="433" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/754824/ae327291-6265-4cc6-93e4-c738bdcc7b4b">

But following the information below that, I see that adaptive sampling is applied in the SDK by default. I am now testing with that disabled via:
```csharp
        services.AddApplicationInsightsTelemetryWorkerService(options =>
        {
            options.EnableAdaptiveSampling = false;
        });
```

This particular function runs every 15min, so it will take a little while to see the effect.

However, I did find this: https://stackoverflow.com/questions/68026094/how-to-tell-if-my-missing-logs-are-due-to-adaptive-sampling-in-application-insig

Running the query:
```
union requests,dependencies,pageViews,browserTimings,exceptions,traces
| where timestamp > ago(1d)
| summarize RetainedPercentage = 100/avg(itemCount) by bin(timestamp, 1h), itemType
```
| timestamp | itemType | RetainedPercentage |
|------------|----------|---------------------|
04/04/2024, 9:00:00.000 am | dependency | 100
04/04/2024, 9:00:00.000 am | request | 100
04/04/2024, 9:00:00.000 am | trace | 100
04/04/2024, 8:00:00.000 am | dependency | 54.638447971781304
04/04/2024, 8:00:00.000 am | request | 100
04/04/2024, 8:00:00.000 am | trace | 71.00042211903757
04/04/2024, 7:00:00.000 am | dependency | 76.91187181354697
04/04/2024, 7:00:00.000 am | request | 100
04/04/2024, 7:00:00.000 am | trace | 86.00804649083594
04/04/2024, 6:00:00.000 am | dependency | 68.74506708760852
04/04/2024, 6:00:00.000 am | request | 100
04/04/2024, 6:00:00.000 am | trace | 79.65249199817102

Which suggests that I have been losing logs due to adaptive sampling and that _maybe_ disabling it resolves the issue (need to wait a while yet).

All of this is a bit of a rabbit hole since it all _just worked_ when running in-process. Maybe it needs to be mentioned in the migration guide?

**Comment by jeffw-wherethebitsroam** [comment]
Ah, I see that in the `host.json` for this fn app there is:

```json
{
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": false,
                "maxTelemetryItemsPerSecond": 100
            }
        }
    }
}
```

Which of course no longer applies to the worker, but is still used in all of the samples: https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-sampling

**Comment by jeffw-wherethebitsroam** [comment]
I can now confirm that all of my logs are arriving. So this serves as a reminder that _all_ `applicationInsights` settings from `host.json` need to migrated over to the worker configuration.

Also, I was able to add back the log type field by using the following `ITelemetryInitializer`:

```csharp
using Microsoft.ApplicationInsights.Channel;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;

namespace FnApp;

public class LogLevelTelemetryInitializer : ITelemetryInitializer
{
    private const string LogLevelKey = "LogLevel";

    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry is not TraceTelemetry traceTelemetry)
        {
            return;
        }

        if (!traceTelemetry.Properties.ContainsKey(LogLevelKey))
        {
            var level = traceTelemetry.SeverityLevel switch
            {
                SeverityLevel.Verbose => "Verbose",
                SeverityLevel.Information => "Information",
                SeverityLevel.Warning => "Warning",
                SeverityLevel.Error => "Error",
                SeverityLevel.Critical => "Critical",
                _ => "Unknown",
            };

            traceTelemetry.Properties[LogLevelKey] = level;
        }
    }
}
```

And initializing it in `Program.cs` via:
```csharp
services.AddSingleton<ITelemetryInitializer, LogLevelTelemetryInitializer>();
```

**Comment by LockTar** [comment]
@jeffw-wherethebitsroam I see you have all your logging working?
You can log all levels (debug, info, warning etc) in Application Insights and console???

At this moment, I'm creating a new .NET 8 Isolated function app and again I'm stuck on the logging. My issue #1182 is now open since 2022 without any progress. Could you share your setup?
Maybe create a PR in my [sample repository](https://github.com/devops-circle/Azure-Functions-Logging-Tests)?

**Comment by jeffw-wherethebitsroam** [comment]
@LockTar, I have the application insights logging as I want it, but I haven't tested with console logging. This is a timer function talking to other Azure services which we test in a dev function app. So console logging has not been a priority.

That said, I might have a look when I get some time. Your issue has a huge number of comments, but it seems like your resolved some of the problems. What are your remaining issues?

**Comment by LockTar** [comment]
Well my issue is Azure functions and logging in general but that's a different topic :-)

What I try to do for years now is to create a simple Isolated function app with Application insights and that configuring log levels work in Azure and locally. I thought you had a solution/setup that was different than mine (and others).
I have everything working except locally debug loglevel in de console.

**Comment by spplante** [comment]
> I can now confirm that all of my logs are arriving. So this serves as a reminder that _all_ `applicationInsights` settings from `host.json` need to migrated over to the worker configuration.
> 
> Also, I was able to add back the log type field by using the following `ITelemetryInitializer`:
> 
> ```cs
> using Microsoft.ApplicationInsights.Channel;
> using Microsoft.ApplicationInsights.DataContracts;
> using Microsoft.ApplicationInsights.Extensibility;
> 
> namespace FnApp;
> 
> public class LogLevelTelemetryInitializer : ITelemetryInitializer
> {
>     private const string LogLevelKey = "LogLevel";
> 
>     public void Initialize(ITelemetry telemetry)
>     {
>         if (telemetry is not TraceTelemetry traceTelemetry)
>         {
>             return;
>         }
> 
>         if (!traceTelemetry.Properties.ContainsKey(LogLevelKey))
>         {
>             var level = traceTelemetry.SeverityLevel switch
>             {
>                 SeverityLevel.Verbose => "Verbose",
>                 SeverityLevel.Information => "Information",
>                 SeverityLevel.Warning => "Warning",
>                 SeverityLevel.Error => "Error",
>                 SeverityLevel.Critical => "Critical",
>                 _ => "Unknown",
>             };
> 
>             traceTelemetry.Properties[LogLevelKey] = level;
>         }
>     }
> }
> ```
> 
> And initializing it in `Program.cs` via:
> 
> ```cs
> services.AddSingleton<ITelemetryInitializer, LogLevelTelemetryInitializer>();
> ```

@jeffw-wherethebitsroam 

That code for the log levels is great, but why do we have to do this?

Is it the expected behavior to lose the log levels/type with isolated Function Apps? Or is this code a workaround for an official bug?

All my logging works as expected except I also don't have any log type/level in the "Monitor" interface or in Azure Insight's custom dimensions. Your code snippet fixed the problem but it doesn't look normal to have to do this, it should definetely be handled natively by the framework, did I miss something?

**Comment by jeffw-wherethebitsroam** [comment]
@spplante as far as I understand (since I don't work at Microsoft/Azure) is that the host logging was magically transforming the logs by adding the `LogLevel` field and a few other fields, which are then used in the Azure UI. In an isolated app, we are now logging directly from the worker app to Application Insights and this process no longer does this magic.

So now we end up with 2 different log formats depending on whether things are logged by the host or the worker. And the UI only handles one of them. This is also painful if you want to process logs in application insights using the function name for example, since this is also different between the formats.

It would be good if the functions team offered some way of getting compatibility between the 2, either:
- An option for `AddApplicationInsightsTelemetryWorkerService` to enable host compatible logs
- Make the host logs compatible with the normal application insights logs and update the UI to use these fields

But I don't know if either of these thing is going to happen.

**Comment by spplante** [comment]
@jeffw-wherethebitsroam Ok gotcha, yeah doesn't make much sens that using the default ILogger doens't play well with the UI hehe

**Comment by sopya88** [comment]
Use below code in Program.cs, it will start working, Also do proper DI in function class for ILogger,

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        
    })
    .ConfigureLogging(logging =>
    {
        logging.Services.Configure<LoggerFilterOptions>(options =>
        {
            LoggerFilterRule defaultRule = options.Rules.FirstOrDefault(rule => rule.ProviderName
                == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
            if (defaultRule is not null)
            {
                options.Rules.Remove(defaultRule);
            }
        });
    })
    .Build();

host.Run();

**Comment by Biptor** [comment]
this is an interesting issue related to the migration to .Net 8 or maybe just to the migration to isolated worker

But, something that works for me is to define the log level in Program.cs inside of the ConfigureServices pipe

`services.AddLogging(loggingBuilder =>
    loggingBuilder.AddFilter<ApplicationInsightsLoggerProvider>(string.Empty, LogLevel.Information)
);`
