### ISSUE TITLE
This [guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net8%2Cazure-cli%2Cwindows&pivots=programming-language-csharp#migrate-your-local-project) says to add references such as

### ISSUE THREAD

**Issue by stevendarby** [Azure/azure-functions-dotnet-worker#2369]
This [guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net8%2Cazure-cli%2Cwindows&pivots=programming-language-csharp#migrate-your-local-project) says to add references such as
`<FrameworkReference Include="Microsoft.AspNetCore.App" />`
and
`<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />`

There is a bit more detail about ASP.NET Core integration [here](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration) -- under an HTTP Trigger section.

My question is: do the suggestions for ASP.NET Core integration apply if you're not using HTTP Triggers? For example, if your function app only has triggers such as `[EventGridEvent]`, `[TimerTrigger]` or `[QueueTrigger]`. Although the HTTP types might not be used directly, there may still be some underlying HTTP communication under the hood, which is why I'm not sure.

Perhaps the general upgrade guide (in the first link) could be a bit more specific about why and when the ASP.NET Core references are needed. I am wary that there is an assumption HTTP triggers are always used directly, but I'm not sure.

_Originally posted by @stevendarby in https://github.com/Azure/azure-functions-dotnet-worker/discussions/2341_

**Comment by mattchenderson** [comment]
Hi @stevendarby - you can absolutely omit the package reference if it's not relevant to you, but the framework reference is generally beneficial from a performance perspective, even if you're not using HTTP triggers yourself.

For Event Grid specifically, you are correct in assuming that an HTTP transport is used. In that sense, I believe you might still see some of the behind-the-scenes improvements that come from ASP.NET Core integration, but that impact might vary based on the event message size, volume of requests, etc.

Ultimately, inclusion of the ASP.NET Core integration package is not required for an app, but we do lead with it in the migration as HTTP triggers are a common enough scenario, and this makes things significantly better for any app that does need it.

I've gone ahead and pushed an update to the docs to try and reflect this a bit better. Thank you for the feedback and questions!
