### ISSUE TITLE
Worker.Extensions.CosmosDB is using old Azure.Identity package (v1.4) with vulnerabilities

### ISSUE THREAD

**Issue by Astral100** [Azure/azure-functions-dotnet-worker#2373]
### Description

This is similar to this issue (https://github.com/Azure/azure-functions-durable-extension/issues/2759), just for a different package.

When using the latest `Microsoft.Azure.Functions.Worker.Extensions.CosmosDB` package Version="4.7.0", in the .Net 8.0 project, it pulls the old `Azure.Identity` package version 1.4 into `.azurefunctions` folder, which is then being reported by our vulnerability scanning tool Wiz:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/26874956/8bf44249-cf73-4e46-924f-4cc8cb670c27)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/26874956/7ada1cd3-c692-44d4-a421-88159a6cf3e5)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/26874956/5b4b77a6-dfcf-4894-af3d-4ea629be6658)

Is it possible to update `Worker.Extensions.CosmosDB` package to use the latest identity library please?

### Steps to reproduce

Install `Microsoft.Azure.Functions.Worker.Extensions.CosmosDB` package Version="4.7.0", in the .Net 8.0 Azure Functions project and check the  `Azure.Identity` package version in the `.azurefunctions` folder

**Comment by Astral100** [comment]
@fabiocav Wonderful, thank you very much for the fast fix!

**Comment by Mjinx** [comment]
Sorry for posting on this closed issue, but we had the same problem and after updating the packages, the content of the .azurefunctions are still the same with azure.identity sticking to v1.10.4

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/5731115/f60c2c03-bcb9-4800-9988-56c470ea80d2)

``` xml
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.8.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
```
