### ISSUE TITLE
Question: extend deserialization of objects on bindings

### ISSUE THREAD

**Issue by eriklieben** [Azure/azure-functions-dotnet-worker#240]
Hi,

I was looking for ways to enrich the serialized data object or provide custom deserialization for a given object. Is extending this through providing custom json converters the preferred way for this?

So for example, I get the following data:

```json
{ 
   "name": "my first book",
   "id": "4d0f280f-9212-4b25-96be-cd0fd83ebe5a"
}
```` 

I would like to turn that into an object that looks like:
```csharp
public class Project: Aggregate {

  public Project(IEventStream stream) : base(stream) {}

  public string Name { get; private set; }

  public string Id { get; private set; }
}
```

It looks like I could potentially do that by creating a custom ```IConverter```, but this interface isn't part of the public API.

https://github.com/Azure/azure-functions-dotnet-worker/blob/4f988d34da628001b04d46873d1d74f241a1fa3f/src/DotNetWorker/Converters/Converter/IConverter.cs#L6

I currently do it by registering a custom JSON converter, which than will be used by the ```JsonPocoConverter```, but before I build my things on top of this I was wondering if there are any other/better ways to accomplish this?

**Comment by brettsam** [comment]
The plan is to expose the model binding (`IConverter`, etc) APIs very soon. It's not a goal for 1.0, but it was built with the intention of exposing it for extensibility. At this point, it needs a thorough API review and then it'll be ready. It's one of our first priorities post-1.0 (so, 1.1 or 1.2, depending on what else comes up).

Are you registering your own `ObjectSerializer`  in `WorkerOptions` to accomplish this today? Let us know if you bump into issues with that -- it could affect our prioritization.

**Comment by fabiocav** [comment]
One thing to mention is that your approach is perfectly valid, and there’s no problem if you invest in that model going forward.

**Comment by eriklieben** [comment]
> Are you registering your own ObjectSerializer in WorkerOptions to accomplish this today? Let us know if you bump into issues with that -- it could affect our prioritization.

Yes, works perfect, no issues.

```csharp
var host = new HostBuilder()
    .ConfigureAppConfiguration(c =>
    {
        c.AddCommandLine(args);
    })
    .ConfigureFunctionsWorker((c, b) =>
    {
        b.UseDefaultWorkerMiddleware();
    },
    options =>
    {
        options.Serializer = new JsonObjectSerializer(new JsonSerializerOptions
        {
            Converters = { new MyValueConverter() }
        });
    })
    .Build();
```

I just noticed I need to wrap my head around the idea a bit. I am, in my current solution (running on dotnet core functions) not really using the plain object input/ plain object output behavior, but more or less use it to 'inject' a complex object into my function, and perform actions directly on it expecting them to execute/apply directly, instead of when the function 'ends' and the output bindings activate. Little bit like, for example, the ```CloudBlobContainer``` object that you can set to a blob input binding, and use to upload multiple files in a certain order and get the etags of the files. Which feels like it allows me to control the flow in which things execution a bit better compared to output bindings which would save in a unknown order I assume.

What I would in a simple example is the following:

```csharp
public class Project : Aggregate
{

    public Project(IEventStream stream) : base(stream) { }

    public string Name { get; private set; }

    public string Id { get; private set; }

    public async Task CorrectFistName(string name)
    {
        await stream.Session(session =>
        {
            session.Append(new FirstNameCorrected
            {
                CorrectedName = name
            },
            constraint: Constraint.Existing);
        });
    }
}
```

class for http message
```csharp
public class CorrectNameMessage {
  public string Id { get; set; }
  public string Name { get; set; }
}
```

Azure function code
```csharp
[FunctionName(nameof(CorrectName))]
public async Task<IActionResult> CorrectName(
[HttpTrigger(AuthorizationLevel.Function, "POST", Route = null)] CorrectNameMessage message,
[EventStream(StreamId = "{Id}")] Project project,
ILogger log)
{
    log.LogInformation($"Correcting name for project {message.Id}");
    await project.CorrectName(message.Name); 

    return new JsonResult(client);
}
```

I think I could figure out how to make this work with input/output bindings, by creating a light implementation of IEventStream that simply collects events, and perform the actual actions in the output binding. That would also mean that if I use something like JavaScript/ TypeScript I could re-use the logic in the output binding, and require less duplicated code for other languages. 

It just feels a bit, like, what I actually want to do is have an open communication channel with the host, and basically just sent it messages with payload, like perform this action. So that all my C# logic is reusable over all, because it is running as plugin in the host, but I can talk to it from the executing language  .NET5/Java/JS/TS/etc. Not sure if that makes any sense.


In some cases I would perform actions directly on the ```IEventStream``` object. This interface gives me access to my stored events in table storage, blob storage, or another storage mechanism that is implemented. I am still trying to wrap my head around how that would be logic for a json converter, maybe, if the json contains some settings related to the event stream this makes sense, it did not make sense in my head if this was transforming from the latest state of Project. So maybe the ```IConverter``` makes more sense here, although it is still 'converting' not 'initializing'.

```csharp
[FunctionName(nameof(CorrectName))]
public async Task<IActionResult> CorrectName(
[HttpTrigger(AuthorizationLevel.Function, "POST", Route = null)] CorrectNameMessage message,
[EventStream(StreamName = "project", StreamId = "{Id}")] IEventStream stream,
ILogger log)
{
  var events = stream.GetEvents();
  // perform logic
  return new OkResult();
}
```

Anyway, gonna try out some different things and see what sticks, sorry for rambling a bit :-)
