### ISSUE TITLE
Azure Functions - Logging not working correctly in local

### ISSUE THREAD

**Issue by rahulsingii** [Azure/azure-functions-dotnet-worker#2406]
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

I have recently migrated my azure function app from .Net 6(In-Process) to .Net 8 (Isolated) and while testing I found that my custom logging is not working when debugging locally. I created another new `.Net 8 Isolated` function app to test this which has 1 Http trigger function. I have a custom database logger which is added to this function to enable database logging.

When I am executing the function, none of the Microsoft related logging are getting filtered and it's logging hundreds of entries in my database. I have already tested my custom logger with a simple console application where the logging filtering works correctly. What's interesteing is apart from my own custom logger, the console logs are also not getting filtered.

This is how my Program.cs looks:-

```
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureAppConfiguration((context, builder) =>
    {
        builder.SetBasePath(Directory.GetCurrentDirectory())
               .AddJsonFile("local.settings.json", optional: true);
    })
           .ConfigureLogging((builder, logging) =>
               {
                   logging.AddConsole();
                   logging.AddDbLogger(options =>
                     {
                       builder.Configuration.GetSection("Database")
                              .GetSection("Options").Bind(options);
                           });
                       })
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();
```

I have added the resp. logging in `host.json` file:-

```
{
    "version": "2.0",
    "logging": {
      "applicationInsights": {
        "samplingSettings": {
          "isEnabled": true,
          "excludedTypes": "Request"
        },
        "enableLiveMetricsFilters": true
      },
      "logLevel": {
        "default": "Information",
        "Microsoft": "Error"
      },
      "Database": {
        "logLevel": {
          "default": "Error"
        }
      },
      "console": {
        "logLevel": {
          "default": "Error"
        }
      }
    }
}
```

Still it shows Log entries in Console and Database.

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/14792498/1a128c6f-6636-4ada-a93e-ba5181a4a1b5)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/14792498/43fc57f0-dfc3-4066-9eb1-756670394885)

Also, when I debug I see no Rules:-

<img width="596" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/14792498/8155bcb1-3f27-47cd-a290-3c6577591f21">

**Comment by jviau** [comment]
`host.json` only applies to the host process. You need to configure log levels for your worker process separately. How you configure it is up to you: you are in full control of `IConfiguration` and what you load into there.
