### ISSUE TITLE
Enhance converter exception log to identify the converter

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#2410]
### Description

When a converter error occurs, such as the following, we should also log the name of the converter that is failing.

> Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'MyTimerTrigger': Cannot convert input parameter 'myTimer' to type 'Microsoft.Azure.Functions.Worker.TimerInfo' from type 'System.String'.

**Comment by liliankasem** [comment]
Design

1. (Linked PR) Introducing an optional "name" parameter to ConversionResult. Modify `DefaultInputConversionFeature` to create a new result with the converter name provided. We have the name of the converter here and don't have to rely on every extension updating their converters with the converter name. This feels like the least effort and least amount of changes approach to me. But, I worry about the cost of creating a new ConversionResult for every invocation result - this seems excessive, but maybe the cost isn't so bad?

2. Introducing an optional "name" parameter to ConversionResult. Instead of setting the converter name for every result ourselves as part of the conversion pipeline, we can update all the converters to include the converter name in the conversion result (see liliankasem/converter-name where is design is implemented).  This means not having to recreate the ConversionResult every time, but we depend on all converters being updated to provide the name. Doable, tedious - probably the cleanest way to go.

3. Not updating `ConversionResult`, we can find a way to bubble up the converter name from `DefaultInputConversionFeature` to `DefaultFunctionInputBindingFeature. BindFunctionInputAsync`.  I like this idea, but I can't find a clean way to do this that makes sense.

4. Not updating `ConversionResult`, we can pull the converter name from the ConversionResult.Error (exception) call stack - I hate this.

**Comment by jviau** [comment]
@liliankasem for the example error message you provided, was there not also a call stack with it? Does it include the error converter in that stack and is this not sufficient for identifying the source of the error?

**Comment by liliankasem** [comment]
> @liliankasem for the example error message you provided, was there not also a call stack with it? Does it include the error converter in that stack and is this not sufficient for identifying the source of the error?

@jviau Yeah, I considered grabbing this from the call stack using regex (#4 I think?) but that felt icky to me - or are you suggesting another way to grab this value?

**Comment by jviau** [comment]
No, not suggesting to grab it from the callstack. I am asking why we need an explicit name in the message _at all_? If we have a callstack with the log, is the necessary information to identify the failing converter not already present?

**Comment by liliankasem** [comment]
Oh I seeee, yes I think the idea here is to make this a lot more clear than having to search the full call stack to know which converter, if we have this info we can should share it as part of the initial error message for a better experience. I think this is more of a nice to have than a must have.

**Comment by liliankasem** [comment]
Discussed with Jacob offline and given the converter name being available in the call stack, this change is not really required.

Upon investigation of this issue, I found that we do not have the converter name readily available to log and it would potentially require making a public API change.

If this issue becomes more important for any reason, we can revisit this later and attempt an approach that requires minimal changes (i.e. design point # 3).
