### ISSUE TITLE
Implement converter for TimerInfo that does not use customer provided serializers

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#2411]
### Description

Today, if a customer provides their own serializer and set a value such as  `UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow`, it breaks our converter. To fix this, for known POCOs that we provide, we should not use custom serializers.

### Task

- [ ] Create a converter for TimerInfo that does not use customer provided serializers.

**Comment by kshyju** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Timer/4.3.1 is published with this change.
