### ISSUE TITLE
Unexpected TaskCancelledException caused by pre-cancelled CancellationToken

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#2415]
### Problem Statement

When we send a cancelled invocation to the worker (i.e. invoke a function and the cancellation
token is cancelled) the CancellationToken being used through the pipeline in the dotnet-isolated
worker (via FunctionContext) is already cancelled **before** we get to the customer function. This leads
to a `TaskCancelledException` being thrown and a 500 error. The cause of this error is this:

`await _semaphoreSlim.WaitAsync(WaitTimeInMilliSeconds, context.CancellationToken);`

[code](https://github.com/Azure/azure-functions-dotnet-worker/blob/f694329065d20acbe3eacf48506f56e029f4cc87/src/DotNetWorker.Core/Context/Features/DefaultFunctionInputBindingFeature.cs#L32)

This is a problem because the customer function is not able to handle the cancellation token
as it never gets invoked.

### Investigation

- [ ] What does ASP.NET do?
- [ ] Attempt to repro with cancelling cts right before function invocation to understand if this is a race or not

### Design

We need to discuss the right behaviour for dotnet-isolated functions in this scenario.

- (a) We can leave the current behaviour as is and allow the pipeline to use the
  cancellation token to handle cancellation. Here, the customer function would not get invoked.
  We will still need to discuss how, if at all, we handle the `TaskCancelledException` exception.
- (b) We can change the behaviour so that items in the pipeline are not using a cancellation
  token and instead we use `CancellationToken.None`. This would mean that we continue and invoke
  the customer function where they are then able to handle the cancellation token.
- (c) Are there any other ways we could handle this scenario?

**Comment by bed007** [comment]
Hi,

We are severely impacted by this issue. We are serving MapBox tiles using AzureFunctions and Mapbox JS client is cancelling tiles loading when panning the map around and tiles are no longer needed. This is creating a lot of exceptions in our Application Insight.

We've migrated last week to .net 8.0 so that's why we just discovered this issue.
