### ISSUE TITLE
.azurefunctions folder is missing after updating Microsoft.Azure.Functions.Worker.Sdk from 1.17.1 to 1.17.2

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-dotnet-worker#2423]
### Description

I have a .NET Isolated Azure Functions Project and also another Tests project that references the Azure Functions Project.

When using `Microsoft.Azure.Functions.Worker.Sdk 1.17.1`, when the **Tests project is built, it's output contains the `.azurefunctions` folder**.

![1](https://github.com/Azure/azure-functions-dotnet-worker/assets/5653381/30f4a526-f669-49a3-9bdb-104ec64cc52b)

When using `Microsoft.Azure.Functions.Worker.Sdk 1.17.2`, when the **Tests project is built, it's output NO LONGER contains the `.azurefunctions` folder**.

![2](https://github.com/Azure/azure-functions-dotnet-worker/assets/5653381/d76b3d11-d10a-425c-b851-dde13790eff7)

### Steps to reproduce

I am attaching 2 fresh solutions:

FunctionApp1: Uses `Microsoft.Azure.Functions.Worker.Sdk 1.17.1`
[FunctionApp1.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/15047123/FunctionApp1.zip)

FunctionApp2: Uses `Microsoft.Azure.Functions.Worker.Sdk 1.17.2`
[FunctionApp2.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/15047124/FunctionApp2.zip)

**Comment by jaliyaudagedara** [comment]
Seems this is caused by changes in [#2313](https://github.com/Azure/azure-functions-dotnet-worker/pull/2313)

@kshyju @jviau

**Comment by jviau** [comment]
@jaliyaudagedara are you able to provide a repro for 1.17.2?

**Comment by jaliyaudagedara** [comment]
@jviau, of course.

Added an example under `Steps to reproduce` above.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/5653381/a8d72526-122d-4849-91e3-415387d95783)

**Comment by jviau** [comment]
@jaliyaudagedara the test project is not expected to have `.azurefunctions` folder in it, it is not a function app. Only projects that directly reference the Function SDK should have it.

**Comment by jaliyaudagedara** [comment]
@jviau,

Thanks for the message.

Ah I see. The use case is I have a bunch of integration tests that spin up a function and run against it.

Example: [https://github.com/jaliyaudagedara/azure-functions-integration-tests/blob/main/tests/HelloAzureFunctions.Tests.Integration/Fixtures/AzureFunctionFixture.cs](https://github.com/jaliyaudagedara/azure-functions-integration-tests/blob/main/tests/HelloAzureFunctions.Tests.Integration/Fixtures/AzureFunctionFixture.cs)

**Comment by jviau** [comment]
> If .azurefunctions project isn't going to be there, I am going to be in trouble 😢.

You can always manually copy the contents over via msbuild targets. Or you can get the output directory of the functions project and directly launch it from there.

> But when you think about it, especially in a test project, when you reference a project, SUTs executables should be in the output, isn't it?

Possibly, but there are also cases you may not want this. Consider a function app referencing another. Having 2 `.azurefunctions` folders attempting to copy to the output may be problematic. I'd rather air on the side of _not_ copying it, and let those that do want it copy it over themselves.

**Comment by jviau** [comment]
With all that said, the current preview version `1.17.3-preview1` will copy that folder. I think I will block that copying before GA'ing this version.

**Comment by jaliyaudagedara** [comment]
yes please. If it's not supposed to be there, then we shouldn't have it. Otherwise people like me can depend on that

**Comment by jviau** [comment]
@jaliyaudagedara after further thinking, I am going to leave the copying behavior in - it will be available in `1.17.3-preview1` on. If you decide to _not_ want the copying behavior, you can mark the project with `Private="false"` metadata in the ProjectReference.

**Comment by jviau** [comment]
Resolved by #2347

**Comment by jaliyaudagedara** [comment]
@jviau, 

Perfect, thank you!
