### ISSUE TITLE
Deserialization issue in Microsoft.Azure.Functions.Worker.Extensions.CosmosDB from version 4.4.1 to 4.8.0

### ISSUE THREAD

**Issue by danielfreitas662** [Azure/azure-functions-dotnet-worker#2429]
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

Hi everyone,
We are going through an issue when upgrading Microsoft.Azure.Functions.Worker.Extensions.CosmosDB from version 4.4.1 to 4.8.0.

The record retrieved from cosmos db is not deserializing correctly to our data model.
We use JsonProperty from Newtonsoft as attributes to define the property names, and when the model is populated the values are all null when we upgrade the package version as described here.

Is there any change between those versions that could be causing this issue?

**Comment by jviau** [comment]
CosmosDB extension uses `System.Text.Json` for serialization - inheriting the same serializer the rest of the function app uses by default.

This is the serializer that is used: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Hosting/WorkerOptions.cs#L20

**Comment by liliankasem** [comment]
You should be able to configure your worker options to use Newtonsoft; this worker options serializer is used for the cosmos serializer:

- https://github.com/Azure/azure-functions-dotnet-worker/blob/43cd370e3da6ae841024d1fa0ec233cc70369be6/samples/Configuration/Program.cs#L30-L72
- https://github.com/Azure/azure-functions-dotnet-worker/blob/43cd370e3da6ae841024d1fa0ec233cc70369be6/extensions/Worker.Extensions.CosmosDB/src/Config/CosmosDBBindingOptionsSetup.cs#L59
