### ISSUE TITLE
dotnet restore Azure Function (isolated) doesn't respect the RID specified in the csproj file.

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-functions-dotnet-worker#2432]
### Description

Hi team,

We are trying to upgrade our functions to .Net 8. And since .Net 8 will no longer produce a self-contained app by default, we added the self-contain flag when doing the publish.

But now the dotnet publish is failing with:
NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'.
NETSDK1112: The runtime pack for Microsoft.AspNetCore.App.Runtime.win-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'win-x64'.

Note that the RID is already specified in the function csproj with:
	  `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`

If I then explicitly do a dotnet restore with the RID specified, the publish would succeed - this seems to indicate that the dotnet restore for azure function would not respect the RID specified in the csproj.

In .Net6, there seems to be no problem, the only difference is we didn't have to explicitly publish as self-contained as that was the default behavior when RID is specified.

You might find it hard to reproduce the issue locally as restoring the proj / sln with VS somehow seems to download the missing runtime pack. I was able to get a steady repro with ADO CI pipeline doing simple dotnet restore, build then publish.

FYR, I tried both Microsoft.Azure.Functions.Worker.Sdk 1.17.0 & 1.17.3-preview1, and they all have the same problem.

### Steps to reproduce

You might find it hard to reproduce the issue locally as restoring the proj / sln with VS somehow seems to download the missing runtime pack. I was able to get a steady repro with ADO CI pipeline doing simple dotnet restore, build then publish.

**Comment by jviau** [comment]
@dxynnez this issue is from the `Microsoft.NET.Sdk` - Azure functions SDK is not involved in restore (except for inner-build restore, but that is unrelated) or self-contained behavior. The repo you would want is https://github.com/dotnet/sdk

**Comment by jviau** [comment]
Closing as external to us.
