### ISSUE TITLE
Add support for IHostApplicationBuilder

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-functions-dotnet-worker#2438]
### Description

This is a new interface introduced in Microsoft.Extensions.Hosting 8.x that makes host startup wire up. .NET 8 worker service template switched to this, and `WebApplicationBuilder` also implement this interface. It'll also make aspire components possible to use in function apps.

**Comment by jviau** [comment]
@davidfowl curious what your suggestion on our approach would be: should purely extend off an existing `IHostApplicationBuilder`, or should we be deriving our own implementation? The former would make it flexible and work with both the generic host and `WebApplicationBuilder`. But the later lets us configure host configuration - which we do today via `.ConfigureHostConfiguration`.

**Comment by davidfowl** [comment]
> Should purely extend off an existing IHostApplicationBuilder

An existing `IHostApplicationBuilder`. 

> But the later lets us configure host configuration - which we do today via .ConfigureHostConfiguration.

Why do you need to?

**Comment by jviau** [comment]
> > But the later lets us configure host configuration - which we do today via .ConfigureHostConfiguration.
> 
> Why do you need to?

We add `AZURE_FUNCTIONS_` environment variable prefix to host configuration.

https://github.com/Azure/azure-functions-dotnet-worker/blob/2ece46d8dc04b6b9135c3fd6aef816d6ea4eab8f/src/DotNetWorker/Hosting/WorkerHostBuilderExtensions.cs#L156

**Comment by davidfowl** [comment]
Is the host vs app split relevant?

**Comment by jviau** [comment]
I believe it is primarily to allow `AZURE_FUNCTIONS_ENVIRONMENT` variable. Or any other of those early environment variables.

**Comment by jviau** [comment]
This work will depend on adding a reference to `Microsoft.Extensions.Hosting/8.0.0` (and potentially other 8.0.0 packages), which is a breaking change.

**Comment by fabiocav** [comment]
@davidfowl some of what @jviau is sharing above align with the breaking change concerns we've discussed. We've been playing with this and will be reviewing the options so we can both, implement this safely **_and_** make it available as soon as possible.

**Comment by frasermclean** [comment]
I am implementing .NET Aspire in my distributed application and this would should be a help if this can be implemented 💖

**Comment by fabiocav** [comment]
Initial work tracked by this completed in #2674 

Updates to the model will be tracked by different issues.
