### ISSUE TITLE
Null reference exception when running TimerTrigger sample app

### ISSUE THREAD

**Issue by louisoftokyo** [Azure/azure-functions-dotnet-worker#244]
`timerInfo.ScheduleStatus` on line 17 of TimerFunction.cs of the sample app is null.

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

SampleApp.MyInfo.ScheduleStatus.get returned null.
```

**Comment by ankitkumarr** [comment]
What version of the packages are you referencing? I tried with the packages below, and it seems to be working fine --
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1-preview1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1-preview5" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0-preview5" />
```

I see these logs as expected --
```
Function Ran. Next timer schedule = 3/8/2021 3:35:00 PM
```

**Comment by louisoftokyo** [comment]
I'm using those same versions.

I had to set `AzureWebJobsStorage` to `UseDevelopmentStorage=true` in the local.settings.json to get it to work - could that be the cause?

**Comment by brettsam** [comment]
@louisoftokyo -- yes, that's likely the issue. In order to track the past schedules, we need a storage connection string. We can update the sample so this is set up by default.

It's also possible to get a null `ScheduleStatus` (for example, if the CRON expression is shorter than 1 minute, we do not store status). We should update the sample to use `timerInfo.ScheduleStatus?.Next`

**Comment by louisoftokyo** [comment]
> It's also possible to get a null `ScheduleStatus` (for example, if the CRON expression is shorter than 1 minute, we do not store status).

That was it. Thanks for your assistance. I have to say that is quite surprising behaviour; I would not have expected that whether a time trigger schedule information property is null or not would depend on the next invocation being greater than 1 minute away.

**Comment by brettsam** [comment]
Yes, I'm noticing that the docs don't reflect this anywhere even though it's been this way for 5 years as far as I can tell (I did some investigating):
- https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs#L81-L86
- https://github.com/Azure/azure-webjobs-sdk-extensions/commit/10d7d4c2b14dc555b81ff4059c656cca94163c86

We'll use this issue to track cleaning up the sample and docs to make this clearer.

Thanks for the report!

**Comment by kinetiq** [comment]
@brettsam On this topic, I'm a little confused by what I see in the docs, where you appear to define your own class to manage the parameters of the timer trigger:

        [Function("TimerFunction")]
        public static void Run([TimerTrigger("0 */5 * * * *")] MyInfo timerInfo,
            FunctionContext context)
        {
            var logger = context.GetLogger("TimerFunction");
            logger.LogInformation($"Function Ran. Next timer schedule = {timerInfo.ScheduleStatus.Next}");
        }
        
    public class MyInfo
    {
        public MyScheduleStatus ScheduleStatus { get; set; }

        public bool IsPastDue { get; set; }
    }

    public class MyScheduleStatus
    {
        public DateTime Last { get; set; }

        public DateTime Next { get; set; }

        public DateTime LastUpdated { get; set; }
    }
    
   I don't really understand what's going on here, but I'm guessing there's some kind of mapping mechanism. Is there somewhere I could learn more about that? Also: I don't actually need any of those fields, so will I have an easier time if I just do something like this? 
   
     public class TimerInfo
    {
    }
    
    Thanks :)

**Comment by brettsam** [comment]
Good question.

`TimerInfo` and `MyTimerInfo` are really "just" POCOs (plain-old-CLR-objects) and there's nothing special about them. For timers, the host will send a JSON payload with a TimerTrigger that looks like our `MyInfo` class declared in the sample. By default, the worker has a "model binding" step that will try to deserialize a JSON string into a parameter type. The sample is taking advantage of that.

It's causing enough confusion that we're adding an official `TimerInfo` to the Timer package so you don't have to declare it yourself -- but either way will work today. There's nothing "special" about this type, other than that it'll be pre-defined for you in the next release of the TImer package.

If you don't need any of the properties, feel free to stick whatever type you want there and just ignore it (you could use `string`, for example).

As for the "model binding" step -- that is currently internal. We plan on exposing all of this publicly in a (near-)future release once we've done a thorough API review. That will show you a little more about what happens behind-the-scenes and let you plug into it if you wish.

Side note -- I suspect that a lot of people don't care about the `TimerInfo` parameter. I've filed an issue that we'll use to investigate whether we should require you to have a parameter for a trigger at all: #314

**Comment by kinetiq** [comment]
Thanks, that's very helpful.

Defining a trigger at the function level is interesting... I have some thoughts, I will respond over there. :)

**Comment by aishwaryabh** [comment]
This should be resolved with the template update
