### ISSUE TITLE
Registering ServerlessHub after migrating to isolated model

### ISSUE THREAD

**Issue by masakomazec** [Azure/azure-functions-dotnet-worker#2445]
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

Hi, we recently migrated from .NET 6 in-process to .NET 8 isolated worker model, and been having an issue with SignalR ever since the migration.
![image (3)](https://github.com/Azure/azure-functions-dotnet-worker/assets/97876461/ee424dca-ec05-4fe3-8a80-d6b657e564c2)

This is the hub class in question - the error is with registering ServerlessHub in Program.cs:

`System.ArgumentException: 'Implementation type cannot be 'Microsoft.Extensions.Hosting.IHostedService' because it is indistinguishable from other services registered for 'Microsoft.Extensions.Hosting.IHostedService'. (Parameter 'descriptor')'
`
Program.cs:  
![image (4)](https://github.com/Azure/azure-functions-dotnet-worker/assets/97876461/784d6445-851b-4dd0-ab4e-9747c0bdba23)

Is there something we are missing?

**Comment by varogonz95** [comment]
Im having the exact same issue. Followed these docs https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config?tabs=isolated-process

**Comment by steelcityrkp** [comment]
Facing similiar issue... Found this comment helpful:
https://github.com/MicrosoftDocs/azure-docs/issues/121723#issuecomment-2124729772
