### ISSUE TITLE
Http-triggered function app isolated worker with CosmosDBInput binding doesn't work with Newtonsoft.Json serializer

### ISSUE THREAD

**Issue by Camios** [Azure/azure-functions-dotnet-worker#2446]
### Description

Tried following the [sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/16a995deb65b44873cd3a56b5e6d4d3c22d64b7d/samples/Configuration/Program.cs) to use Newtonsoft.Json for deserializing POCO input binding, but it prevents the function app body from being called.

### Steps to reproduce

If I put ConfigureFunctionsWorkerDefaults before ConfigureFunctionsWebApplication, then the worker will return 200 without reaching the actual function body.
If I swap the order, then the worker deadlocks (again before hitting the actual function body).

```
[Function("ListEditors")]
public static Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    [CosmosDBInput(databaseName: "EditorList", containerName: "Items", Connection = "CosmosDbReadOnlyConnectionString")] IEnumerable<Editor> documents)
```

**Comment by liliankasem** [comment]
There is a bug with ConfigureFunctionsWebApplication where we are not properly registering customer provided serializers.

Please track the issue here: https://github.com/Azure/azure-functions-dotnet-worker/issues/2131

Closing as dupe.

**Comment by Camios** [comment]
Was it supposed to be closed as "duplicate" instead of "not planned"?

**Comment by liliankasem** [comment]
Not planned includes "duplicate"

![Screenshot 2024-05-08 at 5 25 39 PM](https://github.com/Azure/azure-functions-dotnet-worker/assets/2198905/17483559-409c-4588-9054-d80fba8dc0cf)
