### ISSUE TITLE
OpenTelemetry worker generating duplicated rows

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-functions-dotnet-worker#2474]
### Description

Hello,

I'm trying to use the new package to leverage AzFunction V4 .NET8 isolated with OpenTelemetry:
https://github.com/Azure/azure-functions-dotnet-worker/pull/2395

I was able to quickly integrate with the new package and emit telemetry:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16199012/8e4e9d2b-a06d-4963-974d-659bded48346)

And, with the environment variable set, I started testing.
Observed that duplicated rows are being logged:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16199012/8ff373e6-fcb0-45ae-a7f5-dbe14a4f7e8c)

As you can see in the image, I have two rows regarding a file upload, some of the columns are filled in one row, some not. The customDimensions has only a guid in the customDimensions, for the other, seems complete (bunch of other properties).

I also tried to do this:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16199012/886620ce-36c0-418e-b5fc-4d0242fb3c9f)

But then, I see three rows:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16199012/c5ab5da3-f009-4aad-94b2-ecaa7f4ee08c)

How can I properly de-duplicate this?
Am I doing something wrong?

Thanks!

### Steps to reproduce

Create an AzFunction .NET 8, V4, isolated.
Use the following packages:
```
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.OpenTelemetry" Version="1.0.0-preview1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.3" />
    <PackageReference Include="OpenTelemetry" Version="1.8.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.8.0" />
```

Use the following snippets:
```cs
    private static void Main(string[] args)
    {
        ResourceBuilder openTelemetryResourceBuilder = ResourceBuilder.CreateDefault().AddService("Test");

#pragma warning disable AZFW0014 // Missing expected registration of ASP.NET Core Integration services
        var host = new HostBuilder()
            //.ConfigureLogging(loggingBuilder =>
            //{
            //    loggingBuilder.AddOpenTelemetry(o =>
            //    {
            //        o.SetResourceBuilder(openTelemetryResourceBuilder);
            //        o.IncludeScopes = true;
            //        o.IncludeFormattedMessage = true;
            //        o.AddAzureMonitorLogExporter();
            //        o.AddGenevaLogExporter(options =>
            //        {
            //            options.ConnectionString = "EtwSession=OpenTelemetry";
            //        });
            //    });
            //    loggingBuilder.AddFilter<OpenTelemetryLoggerProvider>("*", LogLevel.Information);
            //})
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureServices((context, services) =>
            {
                services.AddOpenTelemetry()
                    .UseFunctionsWorkerDefaults()
                    .UseAzureMonitor()
                    .WithTracing(t =>
                    {
                        t.SetResourceBuilder(openTelemetryResourceBuilder);
                        t.AddAzureMonitorTraceExporter();
                        t.AddGenevaTraceExporter(g =>
                        {
                            g.ConnectionString = "EtwSession=OpenTelemetry";
                        });
                    });
            })
            .Build();
#pragma warning restore AZFW0014 // Missing expected registration of ASP.NET Core Integration services

        host.Run();
    }
```

Call the default function and see in application insights how many rows are written

**Comment by eddynaka** [comment]
I did one more test and removed `UseAzureMonitor` and left the trace exporter part only.
With that, I can see this:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/16199012/2bfcaeda-36ac-4b54-b876-6a529e4d3015)

So, no more duplicated rows, but the client data is empty.

**Comment by RohitRanjanMS** [comment]
Hi @eddynaka can you confirm if you have "telemetryMode": "openTelemetry" in host.json?

**Comment by eddynaka** [comment]
Hello @RohitRanjanMS ,

Can you share an example of this new host.json file?
I'm not aware of the format you are talking about.

**Comment by RohitRanjanMS** [comment]
{
    "version": "2.0",
    "telemetryMode": "OpenTelemetry"    
}

**Comment by RohitRanjanMS** [comment]
Core tools is not updated yet.

https://learn.microsoft.com/en-us/azure/azure-functions/opentelemetry-howto?tabs=app-insights&pivots=programming-language-csharp#:~:text=You%20can%27t%20currently%20run%20your%20app%20project%20locally%20using%20Core%20Tools%20when%20you%20have%20OpenTelemetry%20enabled%20in%20the%20host.%20You%20currently%20need%20to%20deploy%20your%20code%20to%20Azure%20to%20validate%20your%20OpenTelemetry%2Drelated%20updates.

**Comment by vmcbaptista** [comment]
I decided to play with this as well, but with the dockerized version of the azure functions host, and faced the duplication issue, even though telemetryMode is set to openTelemetry. I've realized that this is not supported by the latest host base image. I've created an issue on the host repo to track this: https://github.com/Azure/azure-functions-host/issues/10258
