### ISSUE TITLE
Support keyed services dependency injection

### ISSUE THREAD

**Issue by wilsjame** [Azure/azure-functions-dotnet-worker#2478]
#### What problem would the feature you're requesting solve? Please describe.

[Keyed services dependency injection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#keyed-services) was [introduced in .NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-7/#keyed-services-support-in-microsoft-extensions-dependencyinjection). It appears to be unavailable when configuring services for Azure Functions. Including this feature would be great to have!

#### Describe the solution you'd like

Add support for keyed services dependency injection (`AddKeyedSingleton`, `AddKeyedScoped`, and `AddKeyedTransient`). 

For example, `services.AddKeyedSingleton` would be available with the following project file and Program.cs

```xml
<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
</PropertyGroup>
```

```csharp
new HostBuilder()
 .ConfigureFunctionsWorkerDefaults()
 .ConfigureServices(services =>
 {
   // Currently unavailable
   services.AddKeyedSingleton<ICache, BigCache>("big")
   services.AddKeyedSingleton<ICache, SmallCache>("small")
 }
``` 

#### Describe alternatives you've considered

Injecting multiple instances of the same class and accessing them through an `IEnumerable<>`. Implementing a factory pattern.

**Comment by jviau** [comment]
@wilsjame are you referencing `Microsoft.Extensions.DependencyInjection/8.0.0`?

**Comment by wilsjame** [comment]
> @wilsjame are you referencing `Microsoft.Extensions.DependencyInjection/8.0.0`?

Working now. Was not aware it was a transitive package and NuGet was installing 6.0.0 instead. Thank you!

**Comment by sksains** [comment]
Hi @wilsjame Could you please post the snippet that how you are using it? I'm getting error as "Microsoft.Extensions.DependencyInjection/8.0.0" assembly not loaded in Function Start-up

**Comment by OmarBazaraa** [comment]
I'm getting the following even though I'm using AzFunc v4.0 with .NET 8.0 and I'm having `Microsoft.Extensions.DependencyInjection` v8.0.1 as a dependency...

`Microsoft.Extensions.DependencyInjection.Abstractions: This service provider doesn't support keyed services.`
