### ISSUE TITLE
OnStarting cannot be set because the response has already started

### ISSUE THREAD

**Issue by tfierens** [Azure/azure-functions-dotnet-worker#2487]
### Description

When creating a response within the body of the function using the following:

                this.logger.LogError(responseMessage.ToString());
                var badRequestResponse = request.CreateResponse(HttpStatusCode.BadRequest);
                await badRequestResponse.WriteStringAsync(responseMessage.ToString());
                return badRequestResponse;

I'm getting the error "OnStarting cannot be set because the response has already started". It took me hours to resolve this issue as I thought it was an issue with our code but as it happens, I updated to the latest version (1.3.0) of "Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" and the minute I went back to version 1.2.1, the problem got resolved.

### Steps to reproduce

1) Create a .net azure function project using .NET 8 and make sure it is set to use isolated process.

2) Add the following packages:

        <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk.Analyzers" Version="1.2.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />

and make sure that it is using 1.3.0 for "Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore"

3. Change the function to return an HttpResponseData and use the HttpRequestData and return a basic response as follows:

                this.logger.LogError(responseMessage.ToString());
                var badRequestResponse = request.CreateResponse(HttpStatusCode.BadRequest);
                await badRequestResponse.WriteStringAsync(responseMessage.ToString());
                return badRequestResponse;

**Comment by satvu** [comment]
I think this should be fixed in `1.3.1` but feel free to reopen this and we can investigate further, thanks!
