### ISSUE TITLE
Support for Azure Cosmos DB for MongoDB Bindings

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-dotnet-worker#2494]
### Description

Azure Functions In-Process has support for `Azure Cosmos DB for MongoDB Bindings`.
https://github.com/Azure/azure-functions-cosmosdb-extension/tree/main

It would be great if we can have this functionality in Azure Functions Isolated.

I am making an attempt here:
https://github.com/Azure/azure-functions-dotnet-worker/pull/2493

Managed to get a simple function app to start without any errors (after a lot of bumps along the way), and it's creating the `leases` collection in the Mongo database. But unfortunately trigger isn't working for some reason (I am expecting it to error out since I have NotImplementedExceptions) 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/5653381/19cb9b8d-8973-4b7f-b465-d3d4fb431966)

And I am kind of scratching my head to figure out how to debug the functionality so I can see what's happening. Once the function app is running, the database seem to be getting locked as well.

Can I get some help to keep this moving please.

Very much appreciated.

**Comment by jviau** [comment]
Going to close this per the discussion in the PR: #2493

**Comment by jaliyaudagedara** [comment]
yes please, thank you!
