### ISSUE TITLE
.Net 8 in Azure China Region

### ISSUE THREAD

**Issue by RussSmi** [Azure/azure-functions-dotnet-worker#2495]
### What version of .NET does your existing project use?

.NET Framework 4.8

### What version of .NET are you attempting to target?

.NET 8

### Description

My customer has a function app using  .NET 7 deployed across many regions including Azure China.  They are unable to migrate to .NET 8 until its rolled out to China.  Customer needs to know when this will happen and also what is on the roadmap for China for the upcoming .NET 9 release

**Comment by kshyju** [comment]
.NET8 should be available in China regions. If it isn't working, please open a support ticket for assistance.
