### ISSUE TITLE
CORS error in Azure Func with Linux Flex Consumption

### ISSUE THREAD

**Issue by ymurshed** [Azure/azure-functions-dotnet-worker#2524]
### Description

I have developed an Azure Function with the following configuration:

**Operating System: Linux
Plan Type: Flex Consumption
Instance Memory: 2048 MB
Runtime Stack: Dotnet-isolated - 8.0
Publishing Model: Code**

The function responds correctly when called from Postman. However, when I call it from a browser or any other frontend application, I encounter a CORS error. The error message is:

**_Access to XMLHttpRequest at 'my-azure-func' from origin 'my-angular-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource._**

In the Azure Function settings, under API -> CORS, I have already added '*' to allow all hosts.
I have tried several approaches to fix this issue within the Azure Function code (e.g., implementing custom middleware to inject 'Access-Control-Allow-Origin' in the response header), but these attempts have not resolved the issue.

### Steps to reproduce

1) Create and deploy an Azure Function with the following setup:

Operating System: Linux
Plan Type: Flex Consumption
Instance Memory: 2048 MB
Runtime Stack: Dotnet-isolated - 8.0
Publishing Model: Code

2) Invoke the function from a browser or any front-end application. 
3) Using developer mode in the browser, observe the CORS error in the network/console tab.

**Comment by kshyju** [comment]
Wonder this is only happening when using [ConfigureFunctionsWebApplication ](https://github.com/Azure/azure-functions-dotnet-worker/blob/bb33b54b03d64194d3db273ef2441012fa71af8c/samples/AspNetIntegration/Program.cs#L11C10-L11C42)method. What is the behavior when using [ConfigureFunctionsWorkerDefaults](https://github.com/Azure/azure-functions-dotnet-worker/blob/bb33b54b03d64194d3db273ef2441012fa71af8c/samples/FunctionApp/Program.cs#L23) ?

**Comment by georgeOsdDev** [comment]
I can repro with Node.js Function App using Flex Consumption SKU.
Response does not contains `Access-Control-Allow-Origin` header even though CORS setting was done.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1381907/259f61fd-c659-48eb-8e13-e1281b5f35a2)

**Comment by georgeOsdDev** [comment]
I found this limitation
> CORS: CORS settings are currently not supported. Exceptions might occur if CORS is configured for Flex Consumption apps.

https://learn.microsoft.com/en-us/azure/azure-functions/flex-consumption-plan#considerations
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1381907/03176945-5478-4d86-b706-42a70d8ce7af)

**Comment by kshyju** [comment]
Glad you found the docs. Let us know if you experience any other issues with dotnet-isolated model.
