### ISSUE TITLE
Any way to pull TimerTrigger CRON from configuration? 

### ISSUE THREAD

**Issue by jamyspex** [Azure/azure-functions-dotnet-worker#255]
Hey

I love the direction this out-of-process refactor is taking the Azure functions SDK! It makes it much easier to utilise other parts of the .NET ecosystem, great work!

The only problem I had after updating my project's `TimerTrigger` functions to use the new hosting model, is I couldn't get pulling the timer CRON from config to work like it used to. For now I have had to hard code the CRON I want to use in the attribute. I've included an example of the old style below:

```csharp
[Function("TimerFunction")]
public static void Run([TimerTrigger("%MyTimerCronConfigSetting%")] MyInfo timerInfo,
    FunctionContext context)
{
    var logger = context.GetLogger("TimerFunction");
    logger.LogInformation($"Function Ran. Next timer schedule = {timerInfo.ScheduleStatus.Next}");
}
```

I'm not sure if this functionality is just not available yet or has been updated in the new release and I'm not using it correctly. Either way let me know! 

Cheers, James.

**Comment by brettsam** [comment]
Thanks for the nice note @jamyspex!

We will add `TimerInfo` to our `Extensions.Timer` package shortly, but it will be a pretty simple POCO helper. You can do that today if you don't want to wait. Create a couple classes like this, then use this `TimerInfo` as your parameter (you can call the class whatever you want), and it should bind to it with the timer details: https://gist.github.com/brettsam/a8fd670807c07159164b83de57909f45

**Comment by brettsam** [comment]
Thanks for the nice note @jamyspex!
 
I just tried using `%MyTimerCronConfigSetting%` (and added this to `local.settings.json`) and it seems to work locally. Are you seeing issues when running locally or when deploying to Azure?

Could you throw together a minimal example and stick it in a gist (or even in a comment here) and I can try to repro? Ideally I could see project file, Program.cs, and the Function class.

**Comment by jamyspex** [comment]
Hi @brettsam, thanks for the quick response! 

I have prepared the following repo - https://github.com/jamyspex/FuncsTimerIssueMRE to demonstrate the problem.

I can confirm that placing the CRON expression as a value in `local.settings.json` leads to it being picked up as expected. As you will see in the example I am using an `appsettings.json` file as an example configuration source as it shows the problematic behaviour. In the real world we wish to set a value in Azure App Config and have it picked by the functions, this is the setup we used with the old runtime. 

I'll just point out the package versions that I am using in this example are not the most recent pre-releases:
```xml
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.0-preview3" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0-preview3" />
```

When I update them to the most recent versions I receive the following start up error:  `Microsoft.Azure.WebJobs.Script: WorkerCofig for runtime: dotnet-isolated not found.
Value cannot be null. (Parameter 'provider')`. I just mention this in case I'm sending you on a wild goose chase and if I just solve the start up error my config problems go away. 

Cheers, James.

**Comment by brettsam** [comment]
Ahh yes. Good point. Right now those configs live in "separate worlds" where the config you set up in your worker does not translate to the Functions host, so the it doesn't know about anything like this. 

As for the `dotnet-isolated not found` issue -- would you mind creating a separate issue with a small repro that shows this? We can track that separately and use this to track the "handling config across worker and host" issue.

**Comment by tanveerbadar** [comment]
The only way I found to be working is if you provide the schedule through environment when running locally.

Going to give it a shot in function app deployment once I am done with development.

**Comment by fabiocav** [comment]
Closing as answered. Please let us know if you need any additional information.
