### ISSUE TITLE
Windows placeholder pools and templates for .NET 9

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#2567]

**Comment by fabiocav** [comment]
This is currently in 103.

Need to investigate whether we have the ability to enable this outside of an ANT deployment.

**Comment by kshyju** [comment]
I was told that "src/Hosting/Azure/tools/src/RDTools/Deploy/Templates/Antares_CreatePlaceholderTemplateSites.xml" deployment template can be used to achieve this.
