### ISSUE TITLE
How to turn off Asp.Net Core Integration on Isolated runtime on v4 with .NET 8

### ISSUE THREAD

**Issue by varkey98** [Azure/azure-functions-dotnet-worker#2594]
### Description

I'm trying to use the default template created by vs code on Mac. this is the code in my Program.cs
```
var host = new HostBuilder()
    // .ConfigureFunctionsWebApplication(app => {
    //     app.UseMiddleware<MyMiddleware>();
    // })
    .ConfigureFunctionsWorkerDefaults((app) => {
        app.UseMiddleware<MyMiddleware>();
    })
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();
```
With the above code, it throws the following error:
```
/Users/test/Projects/dotnetserver/IsolatedFunction/Program.cs(10,6): error AZFW0014: The registration for method 'ConfigureFunctionsWebApplication' is expected for ASP.NET Core Integration. (https://aka.ms/azfw-rules?ruleid=AZFW0014) [/Users/test/Projects/dotnetserver/IsolatedFunction/IsolatedFunction.csproj]

```
I understand this is because its trying to build an Asp.Net Core based function, but how to turn that behavior off?

### Steps to reproduce

Use the default template provided by vs code for HTTP Trigger functions on .NET 8 isolated runtime. Update the program.cs code as mentioned above

**Comment by kshyju** [comment]
If you choose not to use ASP.NET Core integration, remove the package reference to `Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore`.

If this package is referenced in your dotnet-isolated function app, you should use `ConfigureFunctionsWebApplication`.

https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration

**Comment by varkey98** [comment]
Thanks let me try that

**Comment by varkey98** [comment]
Yes. it worked, closing this issue, thanks. But I think it should be a more straightforward configuration than removing a project reference. Also I couldn't find this in any docs, that also needs an update
