### ISSUE TITLE
Dotnet build fails because in bin folder WorkerExtensions.csproj

### ISSUE THREAD

**Issue by drweb86** [Azure/azure-functions-dotnet-worker#2605]
### Description

In debug folder of a project WorkerExtensions.csproj is placed. Its broken since 1.20
Please release new version without this.

### Steps to reproduce

During dotnet restore - in debug folder of a project WorkerExtensions.csproj is placed. Its bug.
During dotnet build --no-restore - it tries to restore in bin folder everything including WorkerExtensions.csproj (which references .Net 6 etc) and fails when private azure nuget fields are used.

Builds for Azure Pipelines, and Builds for Docker use separate dotnet restore and dotnet build. So both are broken now.

**Comment by kshyju** [comment]
@drweb86 Can you share which version of `Microsoft.Azure.Functions.Worker.Sdk` package you are using?

**Comment by jviau** [comment]
@drweb86 - `WorkerExtensions.csproj` is placed into a sub-folder of `IntermediateOutputPath`, this is expected. If you are seeing this csproj in your final output location, that means you have your intermediate output path pointing to the same location as output, which is not a good idea with msbuild.

**Comment by drweb86** [comment]
With 1.14 it works. But with latest versions - it breaks compilation. If to use private nuget packages repository and doing builds in 2 stages
dotnet restore - works
dotnet build --no-restore - it fails because it detects in obj directory WorkerExtensions.csproj and .Net 6 and tries to restore them and fails to do so because of authentication to private repositories which are not part of the WorkerExtensions.csproj.

**Comment by jviau** [comment]
The latest version places the `WorkerExtensions.csproj` in the `IntermediateOutputPath`, which is `obj` by default. If you are seeing this file appear in `bin`, then you have reassigned that MSBuild property. It is not recommended to have intermediate and final output go to the same directory.
