### ISSUE TITLE
update Microsoft.Azure.Functions.Worker.Extensions.ServiceBus to latest Microsoft.Azure.WebJobs.Extensions.ServiceBus once available to fix dependencies to fix Azure.Core vulnerability

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-functions-dotnet-worker#2630]
### Description

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus v5.2.0 
-> Microsoft.Azure.WebJobs.Extensions.ServiceBus v5.16.1 
-> Azure.Messaging.ServiceBus v7.17.5
-> Azure.Core v1.38.0 which has the vulnerability (needs to be 1.41.0 or higher to get the fix)

the update for Microsoft.Azure.WebJobs.Extensions.ServiceBus is tracked here: https://github.com/Azure/azure-sdk-for-net/issues/45238

### Steps to reproduce

any usage update Microsoft.Azure.Functions.Worker.Extensions.ServiceBus v5.20.0 results in the vulnerable dependency being used

**Comment by surgupta-msft** [comment]
The issue has been fixed in the latest version - https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ServiceBus/5.21.0
