### ISSUE TITLE
Azure Function (InternalServerError)

### ISSUE THREAD

**Issue by sapachecon** [Azure/azure-functions-dotnet-worker#2631]
### Description

Estoy generando una Function en mi Azure Function pero no me deja crearlas... lo extraño es que tengo este problema de manera aleatoria ya que en ocasión si me las crea, lo ultimo que me sucedió fue que tenia creada 2 y al crear una tercera me arrijo error y me elimino as 2 function que tenia creada y quede sin ninguna.

En este momento estoy creando una function **HTTP trigger**:

![Captura desde 2024-07-29 16-20-02](https://github.com/user-attachments/assets/e481fe63-57d3-4d0a-96d9-2c9084bb5cbf)

y le doy estas características:
![Captura desde 2024-07-29 16-22-23](https://github.com/user-attachments/assets/81531c18-26e6-469e-b227-3a25a2f5ffca)

Al momento de darle "Crear" comienza el proceso y me arroja error:

![Captura desde 2024-07-29 16-23-11](https://github.com/user-attachments/assets/cd5783bf-1a0b-4a85-9e84-95a7defc3a6a)

La estoy creando desde el portal:
![Captura desde 2024-07-29 16-23-49](https://github.com/user-attachments/assets/260640ff-29f7-4211-bf91-34934191e43a)

En este mismo espacio anteriormente tenia 2 funciones y cuando creé la tercera salio el error y luego ya no tenia ninguna.

Me parece extraño que me haya podido crear function y luego ya no y quizás en un rato mas me deje otra vez, ya que no es primera vez que me sucede.... y me parece mucho mas extraño que esto me elimine mis function ya creadas.

Por ejemplo, ahora al crear no me arrojo error inmediatamente, pero una vez creada me lleva a esta imagen:

![Captura desde 2024-07-29 18-55-02](https://github.com/user-attachments/assets/a81f5feb-d76e-4a77-b164-edaf12a99322)

soy nuevo en esto, si alguno me podría ayudar en como lograr dar con el problema?

Gracias.

Mas info:

Después de varios intentos me dejo, pero no se porque tira esos errores o si en algún momento al crear otra funcion me elimine todo nuevamente.

![Captura desde 2024-07-29 19-23-19](https://github.com/user-attachments/assets/7c94249b-a94f-4e46-a7d3-df3bc00b9506)

Si ejecuto el comando:
az functionapp function list --resource-group rg-function-prod --name function-prod --output table

`https://xxxxxxxx.azurewebsites.net/admin/functions/crear_nodos    https://xxxxxxx.azurewebsites.net/api/crear_nodos    False         python      East US     function-prod/crear_nodos rg-function-prod  https://xxxxxxx.azurewebsites.net/admin/vfs/home/site/wwwroot/function_app.py  https://xxxxxxx.azurewebsites.net/admin/vfs/home/site/wwwroot/crear_nodos/              https://xxxxxxx.azurewebsites.net/admin/vfs/tmp/FunctionsData/crear_nodos.dat
https://xxxxxxx.azurewebsites.net/admin/functions/http_trigger1  https://xxxxxxx.azurewebsites.net/api/http_trigger1  False         python      East US     function-prod/http_trigger1  rg-function-prod  https://xxxxxxx.azurewebsites.net/admin/vfs/home/site/wwwroot/function_app.py                                                                                                    https://xxxxxxx.azurewebsites.net/admin/vfs/tmp/FunctionsData/http_trigger1.dat`

y ahora trato de eliminar alguno de los 2:
az functionapp function delete --resource-group rg-function-prod --name function-prod --function-name crear_nodo

`NotFound) Error deleting function.
Code: NotFound
Message: Error deleting function.`

**Comment by surgupta-msft** [comment]
@sapachecon Could you please open a new issue in English so that we will be able to investigate and provide guidance on that?

**Comment by sapachecon** [comment]
Hello!! Sorry I said it in Spanish, but it was easier for me to explain the problem xD

In summary, what I did was create the functions locally with vscode and then publish them in azure function and that solved the problems, before generating the functions directly in azure (portal) caused them to be created "wrongly"? I don't know exactly what was happening, but I didn't look into the problem any further.
