### ISSUE TITLE
Update Microsoft.Azure.Functions.Worker.Sdk so the auto-generated WorkerExtensions.csproj file contains an up-to-date Azure.Core

### ISSUE THREAD

**Issue by bryanmju** [Azure/azure-functions-dotnet-worker#2635]
### Description

The latest version of Microsoft.Azure.Functions.Worker.Sdk (1.17.4) auto-generates obj/Release/net8.0/WorkerExtensions/WorkerExtensions.csproj which contains Microsoft.Azure.WebJobs.Extensions.* libraries, in our case EventHubs and ServiceBus, which have an outdated dependency on Azure.Core (1.40.0). Any Azure.Core version <= 1.40.0 was flagged as having a vulnerability. 
Is there any way to manually change library versions for the generated WorkerExtensions.csproj? If not, then Microsoft.Azure.Webjobs.Extensions.EventHubs and Microsoft.Azure.WebJobs.Extensions.ServiceBus need to be updated such that their dependencies of Azure.Core >= 1.41.0, and Microsoft.Azure.Functions.Worker.Sdk needs to use these updated Microsoft.Azure.WebJobs.Extensions.* libraries.

### Steps to reproduce

The latest version of Microsoft.Azure.Functions.Worker.Sdk (1.17.4) auto-generates WorkerExtensions.csproj that contain Azure.Core 1.40.0, which has a vulnerability.

**Comment by surgupta-msft** [comment]
Can you share what is flagging Azure.Core for vulnerability and for what reason?

**Comment by bryanmju** [comment]
Yes, our repo got flagged and the description of the vulnerability is: 
This package contains a serious bug that can cause a potential production outage, or decreased user experience due to bearer token requests getting stuck and timing out. Upgrade to version 1.41.0 or later.

**Comment by surgupta-msft** [comment]
The issue has been fixed in the latest versions -
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ServiceBus/5.21.0
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs/6.3.5

**Comment by briandunnington** [comment]
The EventGrid package (https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventGrid) has the same issue. The referenced `Microsoft.Azure.WebJobs.Extensions.EventGrid` has a fixed version (3.4.3) so the EventGrid extension just needs to be updated to reference it (here: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.EventGrid/src/Worker.Extensions.EventGrid.csproj)
