### ISSUE TITLE
NU1102: Unable to find package Microsoft.Azure.Functions.Worker.Core with version (>= 1.19.0)

### ISSUE THREAD

**Issue by pregress** [Azure/azure-functions-dotnet-worker#2650]
### Description

This PR introduces an error after a nuget update:

https://github.com/Azure/azure-functions-dotnet-worker/pull/2638#issue-2441034995

Nuget currently doesn't have version  >=1.19 of https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Core/ 

Hence builds fail with: 

> error NU1102: Unable to find package Microsoft.Azure.Functions.Worker.Core with version (>= 1.19.0)

After a package upgrade of [Microsoft.Azure.Functions.Worker.ApplicationInsights](https://github.com/Azure/azure-functions-dotnet-worker) 1.2.0 -> 1.3.0

The fact that PR's can be merged in this repo without any pipeline verifying changes stuns me. 

### Steps to reproduce

Build a function with the latest version of Microsoft.Azure.Functions.Worker.ApplicationInsights (1.3.0)

Our references
```(xml)
<FrameworkReference Include="Microsoft.AspNetCore.App" />
<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.3.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.3.3" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
<PackageReference Include="AspNetCore.HealthChecks.Azure.Data.Tables" Version="8.0.1" />
<PackageReference Include="AspNetCore.HealthChecks.Publisher.ApplicationInsights" Version="8.0.1" />
<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
<PackageReference Include="Azure.Data.Tables" Version="12.9.0" />
<PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.4" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
<PackageReference Include="System.Linq.Async" Version="6.0.1" />
```

**Comment by snvector** [comment]
I am experiencing the same issue. After updating to the latest version of Microsoft.Azure.Functions.Worker.ApplicationInsights (1.3.0). `error NU1102: Unable to find package Microsoft.Azure.Functions.Worker.Core with version (>= 1.19.0)`
Could it be that someone forgot to deploy the dependent package? 😂

**Comment by Luke-Johnson-CB-Kaseya** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Core/ published version 19 a few minutes ago, I was able to get it working again after running `nuget locals http-cache -clear`

**Comment by kshyju** [comment]
[Microsoft.Azure.Functions.Worker.Core version 1.19.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Core/1.19.0) is now available on NuGet Gallery. If you encounter any further issues, please let us know. Thank you for your patience.

**Comment by pregress** [comment]
@kshyju Whats steps are taken to prevent this in the future?

**Comment by RohitRanjanMS** [comment]
We were in the process of releasing it, and it was awaiting signing.
