### ISSUE TITLE
Internal Microsoft Component Governance scanning is identifying a vulnerability in Azure.Core which is a transitive referenced package by Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.2

### ISSUE THREAD

**Issue by ethanyhou** [Azure/azure-functions-dotnet-worker#2658]
### Description

Internal Microsoft Component Governance scanning is identifying a vulnerability in Azure.Core package which is a transitive 
 dependency of Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.2. The dependencies are from the generated WorkerExtensions.csproj.

CG alert: This package (Azure.Core 1.40) contains a serious bug that can cause a potential production outage, or decreased user experience due to bearer token requests getting stuck and timing out. Upgrade to version 1.41.0 or later.

### Steps to reproduce

Include Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.2 and create a function with a queue trigger.
Build and inspect the generated WorkerExtensions.csproj dependencies and verify the build in Azure Devops/Compliance/Component Governance

**Comment by fabiocav** [comment]
Removing this as it goes against the security policy guidance shared [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/21ce5a7b653a26fe55c1e9d0bfa4a614426e1ac9/SECURITY.md). 

Packages will be updated and released with updated dependencies.
