### ISSUE TITLE
Pass in grpc "RpcType" type data for converters

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#266]
It will be more efficient and accurate (often) to use the RpcType type instead of going through each converter. Another place where this would be really useful is in poco deserialization, where if an exception is thrown during deserialization AND the incoming data was a json type, we should show the deserialization exception instead of a generic "could not convert type string to type poco"

**Comment by fabiocav** [comment]
This can (and should) be done by gRPC specific converters. The gRPC worker implementation has the ability to augment the converters collection and pass additional state to provide what is required to efficiently perform conversions.

**Comment by fabiocav** [comment]
Closing this as the work being done to support SDK type bindings and to enhance the converter probing/usage logic will address the concern.
