### ISSUE TITLE
Add User secrets by default in development environment

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#2661]
### Description

The worker does not process user secrets out of the box today. This stands in contrast to the host behavior. This can be seen most easily by moving AzureWebJobsStorage to user secrets and including a blob-triggered function, binding to a Stream. Everything will work up until the point that the worker attempts to leveraged the deferred binding and use the connection itself.

We should update our defaults to follow the [same behavior as exists in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-8.0&tabs=windows#register-the-user-secrets-configuration-source):
> The initialized WebApplicationBuilder (builder) provides default configuration and calls [AddUserSecrets](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) when the [EnvironmentName](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.environmentname#microsoft-extensions-hosting-ihostenvironment-environmentname) is [Development](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.environmentname.development#microsoft-extensions-hosting-environmentname-development)

CC @bradygaster

**Comment by SeanFeldman** [comment]
Ideally, I'd love to eliminate [`local.settings.json`](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=linux%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-csharp) and leverage user secrets.
Not sure if it's entirely possible, but hopefully, this issue will bring it one step closer.

**Comment by liliankasem** [comment]
This investigation finds that the worker does not load UserSecrets by default. However, CoreTools does try to configure UserSecrets when bootstrapping the host.

The following worker extensions were tested with varying results:

- Queue = PASS
- EventHubs = PASS
- ServiceBus = PASS
- Blob = FAIL
- Cosmos = FAIL
- Table = FAIL

The scenarios that worked with UserSecrets were all extensions where any client handling is done on the host side.
And for those that failed, they all depend on the client being created on the worker side.

The reason that UserSecrets works with Queue/EH/SB extensions is because the host is the place where UserSecrets are loaded (via CoreTools), and that is also where the client connection is made for those bindings, not the worker.

Fabio and I agree that we should configure `UserSecrets` by default for dev environments in 2.0. 

local.settings.json is out of scope for this issue and is more of a core tools requirement/change; something we will consider as we make changes to the functions cli.

**Comment by jviau** [comment]
Could we update samples and our templates to advise using `Host.CreateDefaultBuilder()`? Or we wait until we GA 2.0 and then update to advise using `Host.CreateApplicationBuilder()`. This will include user secrets as well as other defaults.

**Comment by liliankasem** [comment]
I don't think there's any issue in updating guidance/templates/samples; but I think part of making this change is to have parity with what the host does today (i.e. user secrets "enabled" by default). If that is not a huge concern, I can scrap the PR and we could open a doc updates issue instead

**Comment by jviau** [comment]
Parity of user secrets between worker and host would require further discussion anyways.

Is the host and worker expected to point to the same secrets? How does the user specify user secrets ID for the host? It is an embedded assembly attribute, do we flow this back to the host? Does the host get its own user secrets ID?

**Comment by ggirard07** [comment]
Closing that issue as completed is confusing. My understanding is that user secrets are still not supported in the worker out of the box, right?
If someone need them, we should be back to manually configure them on the host like prior 2.0.

**Comment by liliankasem** [comment]
Complete is not correct, I should have used "not planned". 

> My understanding is that user secrets are still not supported in the worker out of the box, right?

Our guidance is to use `Host.CreateDefaultBuilder()` or `Host.CreateApplicationBuilder()` which will bring it in by default

**Comment by ggirard07** [comment]
@liliankasem That guidance seems to directly conflict [with the documented Aspire constraints](https://learn.microsoft.com/en-us/dotnet/aspire/serverless/functions?tabs=dotnet-cli&pivots=visual-studio#azure-function-project-constraints), that (if I interpret that doc correctly) requires the usage of `FunctionsApplicationBuilder`.

**Comment by liliankasem** [comment]
You can still use the FunctionsApplicationBuilder, `FunctionsApplication.CreateBuilder(args);` also configures [defaults](https://github.com/Azure/azure-functions-dotnet-worker/blob/1aa40a940e369003b98d636a29b7aa0a367b8463/src/DotNetWorker/Builder/FunctionsApplicationBuilder.cs#L46)

```csharp
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.Hosting;

var builder = FunctionsApplication.CreateBuilder(args);

builder.ConfigureFunctionsWebApplication();

Console.WriteLine(builder.Configuration["LilianTestSecret"]);

builder.Build().Run();
```

^ The above works for me (and is aspire compatible), just make sure `"DOTNET_ENVIRONMENT": "Development"` is set.

**Comment by liliankasem** [comment]
Yes that's fine, you don't need `ConfigureFunctionsWebApplication`

`var builder = FunctionsApplication.CreateBuilder(args);` is what is bringing in the defaults here.

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.0" />
  </ItemGroup>
```

```csharp
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.Hosting;

var builder = FunctionsApplication.CreateBuilder(args);

Console.WriteLine(builder.Configuration["LilianTestSecret"]);

builder.Build().Run();
```
