### ISSUE TITLE
Migration to Isolated Worker - Issue with CosmosDB Continuation Token

### ISSUE THREAD

**Issue by agravityio** [Azure/azure-functions-dotnet-worker#2703]
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

I already successfully converted my project from in-proc to isolated model and I could execute simple queries. But the continuation token makes some problems.

Until now I used (.NET 6):
```
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.4" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="4.3.1" />
```

with following code:
```
QueryRequestOptions options = new QueryRequestOptions() { MaxBufferedItemCount = limit, MaxConcurrency = -1, MaxItemCount = limit, ResponseContinuationTokenLimitInKb = 1 }; 

using (FeedIterator<Asset> resultSetIterator = dbContainer.GetItemQueryIterator<Asset>(
        query,
        continuationToken: continuation,
        options))
{
    var response = await resultSetIterator.ReadNextAsync();
    assetList.AddRange(response.Resource);
    continuation = response.ContinuationToken;
}
```
Which returned following token:
`
[{"compositeToken":{"token":"+RID:~Jh1UAOn7tzJxCgAAAAAAAA==#RT:1#TRC:100#RTD:sGUSwHiS8luZGxMMf05NBTMxMzUuMTUuMzVVMzE7MjE7MzovNTgyNjI4M1sA#ISV:2#IEO:65567#QCF:8","range":{"min":"","max":"FF"}},"orderByItems":[{"item":"2024-04-24T20:10:29.4715172Z"}],"rid":"Jh1UAOn7tzJxCgAAAAAAAA==","skipCount":0,"filter":"true"}]
`

But after I changed to following package (in .NET8 and isolated model):
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.11.0" />
```
and same code which resulted first in:
`
{"OptimisticDirectExecutionToken":{"token":" RID:~Jh1UAOn7tzIqAQAAAAAAAA==#RT:1#TRC:100#RTD:sGUSwHiS8luZGxMMf05NBTMxMzUuMTUuMzVVMzE7MjE7MTcvNDoyNzM2NlsA#ISV:2#IEO:65567#QCF:8","range":{"min":"","max":"FF"}}}
`

and after setting `EnableOptimisticDirectExecution = false` (or including Microsoft.Azure.Cosmos version 3.43.0 sets OptimisticDirectExecution to false per default? [#4432](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4432) ) the result of the token looks like this:

`
[{"compositeToken":{"token":"+RID:~Jh1UAOn7tzIqAQAAAAAAAA==#RT:1#TRC:100#RTD:sGUSwHiS8luZGxMMf05NBTMxMzUuMTUuMzVVMzE7MjE7MTcvNDoyNzM2NlsA#ISV:2#IEO:65567#QCF:8","range":{"min":"","max":"FF"}},"resumeValues":["2024-04-24T20:10:06.3916255Z"],"rid":"Jh1UAOn7tzIqAQAAAAAAAA==","skipCount":0}]
`

So the differences are the `orderByItems` vs `resumeValues` and the missing `"filter":"true"`.

And adding the "new" token results in following error message:
```
Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 2b1b0144-c013-4789-be3b-19d15b7d4cb4; Reason: (Message: {"Errors":["The continuation token specified in the request is malformed. Re-run the query without it and iterate."]}
ActivityId: 2b1b0144-c013-4789-be3b-19d15b7d4cb4, Request URI: /apps/c9ae2c91-e403-4bc3-9db8-891d0379aa85/services/10b8fd45-8556-4d1a-bc91-d9b184920a14/partitions/c26bc865-ba92-47b0-ae49-dd6e77cf9c89/replicas/133702830036393052s/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.35.0);
```

Any ideas would be very helpful!

### Project configuration and dependencies

<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="4.11.0" />

**Comment by agravity-philipp** [comment]
@adityasa may I ask you to give your opinion on that?

**Comment by agravityio** [comment]
Finally I found the issue:

`{"OptimisticDirectExecutionToken":{"token":" RID:~Jh1UAOn7tzIqAQAAAAAAAA==#RT:1#TRC:100#RTD:sGUSwHiS8luZGxMMf05NBTMxMzUuMTUuMzVVMzE7MjE7MTcvNDoyNzM2NlsA#ISV:2#IEO:65567#QCF:8","range":{"min":"","max":"FF"}}}` 
was URL decoded which removed the "+" contained before the `RID` section.

After removing this, the continuation token was working again.
