### ISSUE TITLE
Missing sample function app to real test of current state of SDK

### ISSUE THREAD

**Issue by KondzioSSJ4** [Azure/azure-functions-dotnet-worker#2704]
### Description

Hi

I made a source generator to use dependency injection for `IFunctionActivator`
I made a few tests, but I would like to test it in real function if that works 

is there any way a have sample app that will use current version of the Sdk.Generator and Analyzers?
I tried to make it, but I ends up with a list of the issues
like...
I removed reference:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.4" />
```
and add:
```
<ProjectReference Include="..\..\sdk\Sdk\Sdk.csproj" />
```
but it ends up with error:
```
System.InvalidOperationException: 'The gRPC channel URI 'http://:' could not be parsed.'
```
in `GrpcServiceCollectionExtensions.cs` from `DotNetWorker.Grpc.csproj`

Related branch: 
https://github.com/KondzioSSJ4/azure-functions-dotnet-worker/tree/kondziossj4/new-incremental-function-executor

**Comment by kshyju** [comment]
> but it ends up with error:

    System.InvalidOperationException: 'The gRPC channel URI 'http://:' could not be parsed.'
    
Can you be more specific about what action are you performing which is leading to this error?

**Comment by KondzioSSJ4** [comment]
Steps to reproduce:
- I pull `main` branch
- in project called `AspNetIntegration`:
-- remove `<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.4" />`
-- add `<ProjectReference Include="..\..\sdk\Sdk\Sdk.csproj" />`
-- run app

On the startup it will shown error `System.InvalidOperationException: 'The gRPC channel URI 'http://:' could not be parsed.'`
in GrpcServiceCollectionExtensions.cs from DotNetWorker.Grpc.csproj

**Comment by KondzioSSJ4** [comment]
I get it how it can be possible...
So I can test and debug current SDK state

I made small PowerShell script to attach current SDK version if somebody would like test it as I like 😄 
```PowerShell
$localNugetDir = "G:\GIT\LocalNuget"

dotnet nuget add source $localNugetDir -n LocalNuget

### Remove bin obj
#Get-ChildItem ..\..\ -include bin,obj -Recurse | ForEach-Object ($_) { Remove-Item $_.FullName -Force -Recurse }

### PACK PROJECT
dotnet pack ..\..\sdk\Sdk\Sdk.csproj --output $localNugetDir -p:PackageVersion="50.0.0" -c Release
dotnet pack ..\..\sdk\Sdk.Analyzers\Sdk.Analyzers.csproj --output $localNugetDir -p:PackageVersion="50.0.0" -c Release
dotnet pack ..\..\sdk\Sdk.Generators\Sdk.Generators.csproj --output $localNugetDir -p:PackageVersion="50.0.0" -c Release

### Attach packed SDKs to project
dotnet add package Microsoft.Azure.Functions.Worker.Sdk -v 50.0.0 -s $localNugetDir
dotnet add package Microsoft.Azure.Functions.Worker.Sdk.Analyzers -v 50.0.0 -s $localNugetDir
dotnet add package Microsoft.Azure.Functions.Worker.Sdk.Generators -v 50.0.0 -s $localNugetDir
```
