### ISSUE TITLE
Improve .NET isolated templates

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#271]
Some areas of interest:
- ILogger nameof improvmenets
- EventHubs trigger when no data
- Program.cs and all templates "using" statement cleanups
- HttpTrigger consistent with other samples -- Use name query param, and return "Hello, <name>"

**Comment by prabh-62** [comment]
Also, if `static` keyword should be part of triggers by default? https://github.com/Azure/azure-functions-templates/issues/1034

And nullable mode by default https://github.com/Azure/azure-functions-templates/issues/1035

**Comment by fabiocav** [comment]
Closing stale issue. Templates have been iterated on a few times since this has been opened, most recently with updates to take advantage of new features like SDK type bindings.
