### ISSUE TITLE
Microsoft.Azure.WebJobs.Script: WorkerCofig for runtime: dotnet-isolated not found. Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by jamyspex** [Azure/azure-functions-dotnet-worker#273]
Start up error `Microsoft.Azure.WebJobs.Script: WorkerCofig for runtime: dotnet-isolated not found.
Value cannot be null. (Parameter 'provider')` occurs when using the following versions of the core nugets: 

```xml
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
```

MRE example here: https://github.com/jamyspex/WorkerConfigNotFoundMRE

**Comment by brettsam** [comment]
Thanks @jamyspex!

I see the issues:
- In one of the previews, we moved away from using packages everywhere. So you need to:
```
replace this:
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />

with this:
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1" />

and you can also remove this:
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.1" />
```
- After that, your project won't build b/c of some minor API changes, so in your function class:
```
change this:
using Microsoft.Azure.WebJobs;

to this:
using Microsoft.Azure.Functions.Worker;

and change this:
[FunctionName("Test")]

to this:
[Function("Test")]
```
- You can also simplify your hostbuilder to this now:
```
return new HostBuilder()
    .ConfigureFunctionsWorkerDefaults();
```

And I think that'll get it running after you uncomment the line in local.settings.json.

**Comment by jamyspex** [comment]
Cheers @brettsam! After making those changes and upgrading to the latest version of the core tools (3.0.3331) I've got the example working!
