### ISSUE TITLE
WriteAsJsonAsync throws exception when using NewtonsoftJson serializer

### ISSUE THREAD

**Issue by CSharpBender** [Azure/azure-functions-dotnet-worker#2735]
### Description

In Azure Functions isolated model an exception is thrown when overriding the serializer from ConfigureFunctionsWebApplication() and `response.WriteAsJsonAsync()` is used: `System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.`
I followed [the Microsoft guide](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#customizing-json-serialization) for migrating an in-process Azure function to the isolated model which clearly states that I need to override the Json serializer in ConfigureFunctionsWebApplication and use `services.AddMvc().AddNewtonsoftJson().`
While searching for a fix to my issue I found [issue1 ](https://github.com/Azure/azure-functions-dotnet-worker/issues/2131) and [issue2](https://github.com/Azure/azure-functions-openapi-extension/issues/649)

### Steps to reproduce

1) Create an Azure Function
```
 [Function("MyIsolatedFunction")]
        public async Task<HttpResponseData> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequestData request)
        { 
            var response = request.CreateResponse(HttpStatusCode.OK);
            await response.WriteAsJsonAsync(new { Name="Error"});
            return response;
 }
```

2) Override Json serializer in Program.cs
```
public static class Program
{
    public static void Main(string[] args)
    {
        var host = new HostBuilder()
                .ConfigureFunctionsWebApplication((IFunctionsWorkerApplicationBuilder builder) =>
                {
                    builder.Services.Configure<WorkerOptions>(workerOptions =>
                    {
                        //<PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="1.0.0" />
                        var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
                        settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                        settings.NullValueHandling = NullValueHandling.Ignore;

                        workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
                    });
                })
                .ConfigureServices(services =>
                {
                    services.AddApplicationInsightsTelemetryWorkerService();
                    services.ConfigureFunctionsApplicationInsights();
                    services.ConfigureSerializer();
                })
                .Build();

        host.Run();
    }
    public static IServiceCollection ConfigureSerializer(this IServiceCollection services)
    {
        services.AddMvc().AddNewtonsoftJson();
        return services;
    }
}
```

3) Exception is thrown: `System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.`

4) If I remove this line the exception disappears but the serialization is wrong because I'm using NewtonsoftJson attributes.
`workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);` also this breaks the swagger definition.
Another workaround is to serialize the object myself and use the `WriteAsync` method instead of `WriteAsJsonAsync`

**Comment by snerte** [comment]
I'm having thesame exception when using:

``` csharp
        public async Task<HttpResponseData> HttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
        HttpRequestData reqData,
        [DurableClient] DurableTaskClient client)
        {
            var request = await reqData.ReadFromJsonAsync<MyModel>();
```

A bug for sure.

**Comment by liliankasem** [comment]
Hi, I wasn't able to repro the issue you reported. Could you try again with all the latest packages?

Here is what I tried which ended up working without issues (v1 of the worker):

#### csproj (functions version v4 | .net8)

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" />
  </ItemGroup>
```

#### Program.cs

```csharp
    public static void Main(string[] args)
    {
        var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults((IFunctionsWorkerApplicationBuilder builder) =>
                {
                    builder.Services.Configure<WorkerOptions>(workerOptions =>
                    {
                        var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
                        settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                        settings.NullValueHandling = NullValueHandling.Ignore;

                        workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
                    });
                })
                .Build();

        host.Run();
    }
```

#### MyHttpFunction.cs

```csharp
        [Function("MyIsolatedFunction")]
        public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequestData request)
        {
            var response = request.CreateResponse(HttpStatusCode.OK);
            await response.WriteAsJsonAsync(new { Name="Error"});
            return response;
        }
```

#### Core Tools

```log
Azure Functions Core Tools
Core Tools Version:       4.0.6610 Commit hash: N/A +0d55b5d7efe83d85d2b5c6e0b0a9c1b213e96256 (64-bit)
Function Runtime Version: 4.1036.1.23224

[2024-11-14T22:17:04.539Z] Found /Users/likasem/source/repros/dni-newtonsoft-exception-repro/dni-newtonsoft-exception-repro.csproj. Using for user secrets file configuration.
[2024-11-14T22:17:08.219Z] Worker process started and initialized.

Functions:

        MyIsolatedFunction: [GET,POST] http://localhost:7071/api/MyIsolatedFunction

For detailed output, run func with --verbose flag.
[2024-11-14T22:17:11.409Z] Executing 'Functions.MyIsolatedFunction' (Reason='This function was programmatically called via the host APIs.', Id=7cf54d0c-a0a9-4599-a546-7cde2d241c0c)
[2024-11-14T22:17:11.934Z] Executed 'Functions.MyIsolatedFunction' (Succeeded, Id=7cf54d0c-a0a9-4599-a546-7cde2d241c0c, Duration=551ms)
[2024-11-14T22:17:13.356Z] Host lock lease acquired by instance ID '000000000000000000000000303B82C0'.
```

---

# New Model

It's also worth noting we have a new model we suggest folks update to:

#### csproj (functions version v4 | .net8)

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.0" />
  </ItemGroup>
```

#### Program.cs

```
using Azure.Core.Serialization;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

var builder = FunctionsApplication.CreateBuilder(args);

builder.ConfigureFunctionsWebApplication();

builder.Services.Configure<WorkerOptions>(workerOptions =>
{
    var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
    settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    settings.NullValueHandling = NullValueHandling.Ignore;

    workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
});

builder.Build().Run();
```

#### MyHttpFunction.cs

```csharp
        [Function("MyHttpFunction")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult(new { Name="Error"});
        }
```

**Comment by CSharpBender** [comment]
@liliankasem thank you for the response, unfortunately it doesn't work for me.
**First version**, doesn't even compile because there is a missing package: HostBuilder doesn't contain a definition for ConfigureFunctionsWorkerDefaults.
```<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.0" />```

If I use the packages from the `New Model` then I get the exception: `System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.`
Can you attach the full project?

The **New Model** version doesn't use the Newtonsoft.Json serializer.
If I override the property name from the response it's ignored: `name` instead of `responseType`
```
      public class ResponseDto
      {
          [JsonProperty("responseType")]
          public string Name { get; set; }
      }
        [Function("MyHttpFunction")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult(new ResponseDto { Name = "Error" });
        }
```
What should I change?

**Comment by liliankasem** [comment]
Can you compare your project with this sample and see what is different?

https://github.com/liliankasem/dni-function-newtonsoft-sample/tree/main

**Comment by CSharpBender** [comment]
@liliankasem your sample project proves that my previous statement was right.

I've made a few changes to your project: https://github.com/CSharpBender/dni-function-newtonsoft-sample
1.  Added a function that uses `HttpRequestData` and `WriteAsJsonAsync` (throws exception)
2. Fixed `Newtonsoft.Json` serializer by adding `services.AddMvc().AddNewtonsoftJson();` in `Program.cs`

**Comment by jviau** [comment]
When using AspNetCore integration, the default is to disallow synchronous IO. This default comes from AspNetCore, not functions. It also so happens the [NewtonsoftJsonObjectSerializer](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Microsoft.Azure.Core.NewtonsoftJson/src/NewtonsoftJsonObjectSerializer.cs) is completely synchronous, meaning these are not compatible by default.

To enable synchronous IO, please add the following to your startup. This will enable Newtonsoft.Json usage:

``` csharp
services.Configure<KestrelServerOptions>(options => options.AllowSynchronousIO = true);
```

**Comment by CSharpBender** [comment]
@jviau I'm not satisfied with your response because this is not mentioned in the [Microsoft Guide](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#customizing-json-serialization)
I appreciate your suggestion, but this approach is widely discussed online, and I was already aware of it. However, it didn't feel right to me, perhaps because I had too much faith in Microsoft to document such a significant issue properly.

**Comment by jviau** [comment]
@CSharpBender thank you pointing out the gap in the docs, we will add this information ASAP.

**Comment by ewillman** [comment]
Wait, how is this considered closed? the method is literally called WriteAsJsonAsync, and is essentially exactly what the error message is saying to do to resolve itself, but the solution to making WriteAsJsonAsync work without errors is to AllowSynchronousIO?  That may be considered a workaround, but is certainly not a resolution.

**Comment by jviau** [comment]
@ewillman we do not own the `NewtonsoftJsonObjectSerializer` - if you have an issue with it writing synchronously, please open an issue with team/repo that owns it: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Microsoft.Azure.Core.NewtonsoftJson/src/NewtonsoftJsonObjectSerializer.cs

**Comment by jviau** [comment]
The synchronous issue also only applies to `HttpRequestData` and `HttpResponseData`. If using AspNetCore and sticking to aspnetcore bindings (using `IActionResult` and `[FromBody]` attributes, etc), then you can get Newtonsoft in an asynchronous compatible fashion via:

``` CSharp
// need <PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="2.0.0" /> for this
services.AddMvc().AddNewtonsoftJson();
```
