### ISSUE TITLE
Is it compatiable with .net core 3.1?

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-functions-dotnet-worker#275]
Hello,

Could you please tell me - can I use new azure fuctions sdk for .net core 3.1 app or I should use it only with .net 5 ?

Thank you!

**Comment by brettsam** [comment]
Today only with .NET 5 -- see this issue for some more details: https://github.com/Azure/azure-functions-dotnet-worker/issues/184.

**Comment by brettsam** [comment]
Closed as duplicate.
