### ISSUE TITLE
ILogger custom categories not working on Application Insights

### ISSUE THREAD

**Issue by erionpc** [Azure/azure-functions-dotnet-worker#2752]
### Description

I've found that log message categories which should be created automatically based on the managed code class names are overwritten in ApplicationInsights for Azure Functions running on a .NET8 isolated-process. 

### Steps to reproduce

The code below creates a function which logs an info message (ILogger<T>.LogInformation) and a debug message (ILogger<T>.LogDebug).  
The default log level in the host file is set to "information" and the namespace-specific one is set to "debug".   
In ApplicationInsights, the info messages are shown, but the debug ones aren't. All the Trace messages are logged under the category "Host.Function.Console".  
This makes me suspect that for isolated-process functions the logging is handled internally and it ignores categories that come from the managed code. 
I tried specifying the log level within the "applicationInsights" element in the host file, but it didn't make a difference. I also tried creating a logging filter with the class name, and that didn't work either. 

### Program.cs
```c#
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
        logging.AddApplicationInsights();
    })
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();
```

### MyFunction.cs
```c#
namespace MyNamespace.Functions
{
    public class MyFunction(ILogger<MyFunction> logger)
    {
        private readonly ILogger<MyFunction> _logger = logger;

        [Function("MyFunction")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequest req)
        {
            _logger.LogInformation("some info message");
            _logger.LogDebug("some debug message");
            return new OkResult();
        }
    }
}
```

### host.json
```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Information",
      "Microsoft": "Warning",
      "MyNamespace.Functions": "Debug"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      },
      "enableLiveMetricsFilters": true
    }
  }
}
```

**Comment by erionpc** [comment]
The only way in which I managed to make this work as intended was to use ILoggerFactory instead of ILogger on the function declaration:
```c#
public class EchoFunction(ILoggerFactory loggerFactory)
{
    private readonly ILogger<EchoFunction> _logger = loggerFactory.CreateLogger<EchoFunction>();
```
The rest of the configuration is the same as above.  
On ApplicationInsights the logs still appear under the category "Host.Function.Console" with LogLevel "Information", but they're the debug level messages from my code.

**Comment by RohitRanjanMS** [comment]
The Application Insights SDK adds a default logging filter that instructs ILogger to capture only Warning and more severe logs. Application Insights requires an explicit override. `services.AddApplicationInsightsTelemetryWorkerService();` won't log anything under `warning` to AppInsights unless you remove the [default ](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#:~:text=options.Rules.Remove(toRemove)%3B)rule. 

The log that you see in the AppInsights is forwarded to the AppInsights by the runtime as we listen to anything written to the console. `logging.AddConsole();` will write the log to the console, which will be picked by the host/runtime and forwarded to AppInsights with the category `Host.Function.Console`.

Consider not writing to the console and please don't configure AppInsights twice.

**Comment by erionpc** [comment]
@RohitRanjanMS thanks for clarifying that. I managed to configure the log level correctly.
Just one thing to add. The debug level messages aren't going to make it to application insights, unless the minimum log level is set to include them on application start-up. I learnt this from this other issue https://github.com/Azure/azure-functions-host/issues/8901. 
It would be great if Intellisense could pick up redundant configurations (i.e. _ConfigureLogging -> AddApplicationInsights_ + _ConfigureServices -> AddApplicationInsightsTelemetryWorkerService_ in my previous comment)

Here's my updated code, for anyone else's benefit:

### Program.cs
```c#
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        services.Configure<LoggerFilterOptions>(loggerFilterOptions => 
        {
            Type loggerProvider = typeof(Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider);
            var applicationInsightsFilteringRuleToRemove = loggerFilterOptions.Rules.FirstOrDefault(rule => rule.ProviderName
                == loggerProvider.FullName);
        
            if (applicationInsightsFilteringRuleToRemove is not null)
            {
                loggerFilterOptions.Rules.Remove(applicationInsightsFilteringRuleToRemove);
            }
            // need to do this otherwise it's set to "Information" by default, see https://github.com/Azure/azure-functions-host/issues/8901
            loggerFilterOptions.MinLevel = LogLevel.Trace;  
        });
    })
    .Build();

host.Run();
```

### MyFunction.cs
```c#
namespace MyNamespace.Functions
{
    public class MyFunction(ILogger<MyFunction> logger)
    {
        private readonly ILogger<MyFunction> _logger = logger;

        [Function("MyFunction")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequest req)
        {
            _logger.LogInformation("some info message");
            _logger.LogDebug("some debug message");
            return new OkResult();
        }
    }
}
```

### host.json
```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Information",
      "Microsoft": "Warning",
      "MyNamespace.Functions": "Debug"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      },
      "enableLiveMetricsFilters": true
    }
  }
}
```

**Comment by springcomp** [comment]
@erionpc I think your code is missing two critical pieces which are to actually :
- Register either `host.json` or a separate `appSettings.json` configuration file as a source for configurations, and…
- Load the `Logging/LogLevel` section from that configuration.

FYI, in #1182, I illustrate how to [reliably have full control]((https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-2503764412)) on your logging experience. This also aligns with both the latest practices and versions of the NuGet packages. This is almost exactly the same code as you ended up with.
