### ISSUE TITLE
Document binding environment variables to configuration (for local.settings.json and app settings)

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#277]
I'm not seeing any documentation for how to actually bind to values in the local.settings.json file.

In normal dotnet azure functions, values in local.settings.json are accessible as IOptions, but they are showing up as null in dotnet-isolated functions.

```json
{
  "IsEncrypted": false,
  "Values": {
      "AzureWebJobsStorage": "...",
      "SectionName:ValueName": "something"
  }
}
```

For example config.GetSection("SectionName").GetValue("ValueName")

**Comment by fabiocav** [comment]
@onionhammer you should be able to add the following to your host builder configuration in `program.cs` to bind to the environment variables in configuration:

``` csharp
               .ConfigureAppConfiguration(c =>
                {
                    c.AddEnvironmentVariables();
                })
```

**Comment by onionhammer** [comment]
@fabiocav  that worked, thanks. Just FYI though, I searched the entire repo for "local.settings.json" and found no mention of it in any of the documentation/readme or even the code to see what looked at it, the only references are a few issues.

IMO local.settings.json should be bound by `ConfigureAppConfiguration` if `AZURE_FUNCTIONS_ENVIRONMENT` is `Development`.

**Comment by mhoeger** [comment]
Re-opening to track documentation update. Thanks!

**Comment by mhoeger** [comment]
Actually sorry - tracking here :) https://github.com/Azure/azure-functions-dotnet-worker/issues/288

**Comment by Janus88** [comment]
Can anyone help me out, please? I try to configure the dbcontext in the Main(). The debugger shows my ConnectionString from local.settings.json. But as you can see, in the console output it is empty. AddDBContext fails also :-(

![image](https://user-images.githubusercontent.com/8038120/111189590-882b1900-85b6-11eb-82ad-1f3b6495f7ff.png)

**Comment by fabiocav** [comment]
@Janus88 can you please open a separate issue with the details of what you're seeing and a repro? 

We've also just added an Entity Framework sample here: https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/EntityFramework
