### ISSUE TITLE
func start fails with Can't determine Project to build

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/azure-functions-dotnet-worker#2778]
### Description

Since version `1.17`, running `func start` fails to start a project after `dotnet build`.
It actually find `obj/Debug/net8.0/WorkerExtensions/WorkerExtensions.csproj`. This file was not present in `1.16.4`.

### Steps to reproduce

1. Create a func project with `Microsoft.Azure.Functions.Worker.Sdk` version `1.16.4`.
2. Run `func start` multiple times without issue
3. Upgrade to version `1.18.1` (or any version after `1.16.4`)
4. Run `func start` two times. The second time, it fails with `Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2`

**Comment by Mike-Becatti** [comment]
To add more information, after this assembly is updated it puts a WorkerExtensions.csproj in the obj\Debug\net8.0\WorkerExtensions folder.  That is where the conflict lies.

**Comment by scrocquesel-ml150** [comment]
> What version of core tools do you have? It will be emitted when you run `func start`. Please upgrade to latest if not already there and try again.

Hi, closing this as updating the `azure-functions-core-tools-4` package to the latest version fixed the issue.

```
Azure Functions Core Tools
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875
```
