### ISSUE TITLE
Wrong content-type header when returning a POCO (as JSON) on a isolated http triggered function

### ISSUE THREAD

**Issue by Tealons** [Azure/azure-functions-dotnet-worker#2794]
### Description

The workaround in [this issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/666) still seems needed, even though the last comment indicates otherwise. 

I checked the minimal example and I still get the plain/text content-type header in the response:

![Image](https://github.com/user-attachments/assets/e296ef77-5e29-4ba6-b3c2-8a3701893ac8)

### Steps to reproduce

Just like the original issue:

Please consider following function:

```
 public class FooDto
    {
        public string Bar { get; set; }
    }
    public static class Function1
    {
        [Function("Function1")]
        public static FooDto Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            FunctionContext executionContext)
        {
            return new FooDto() {Bar = "FooBar"};
        }
    }

```
When sending the request:

```
GET  http://localhost:7071/api/Function1
Accept: application/json
```

the response is following:

```
HTTP/1.1 200 OK
Connection: close
Date: Fri, 08 Oct 2021 08:29:00 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{
  "Bar": "FooBar"
}

```
Note the text/plain on the response.

**Comment by liliankasem** [comment]
@Tealons - can you share the csproj file and program file used for this function?

cc: @kshyju - an issue you originally resolved last year in case you had insight
