### ISSUE TITLE
IotHubTrigger and EventData binding

### ISSUE THREAD

**Issue by alsami** [Azure/azure-functions-dotnet-worker#283]
Hey there!

Previously we were able to use something like this:

```csharp
public Task Run([IoTHubTrigger(EventHubName, Connection = IotHubConnectionKey, ConsumerGroup = EventHubConsumerGroup)] EventData eventDataMessage)
{
    if (eventDataMessage is null)
    {
        throw new ArgumentNullException(nameof(eventDataMessage));
    }

    return this._messageHandler.HandleAsync(new DeviceMessage(eventDataMessage.Body.Array, eventDataMessage.SystemProperties));
}
 ```
 
 As far as I understood without knowing the code the attribute `IotHubTriggerAttribute` is just an alias for `EventHubTriggerAttribute` which would be then part of the new-package `Microsoft.Azure.Functions.Worker.Extensions.EventHubs`. 
 
One question remains is how can I get `EventData` now? 

I couldn't find a solution for that so far. I'd be happy to send a PR describing the solution for this problem once I got it working. (if desired).

Thanks in advance!

**Comment by fabiocav** [comment]
`EventData` is not (yet) supported by the extension, but all of the properties coming with the event are available in the `FunctionContext.BindingData` property. While `EventData` is not supported, you should be able to construct an instance of it, or just get the desired properties from the context.

**Comment by alsami** [comment]
Will give it a try tommorow and get back to you.

**Comment by twentytwokhz** [comment]
@fabiocav  @alsami 
I mistakenly created a duplicate here: #458 
Clearly this approach is less than ideal

```
public class DeviceTwin_EventHubTrigger
    {
        [Function("DeviceTwin_EventHubTrigger")]
        public async Task<DeviceTwinOutput> Run(
            [EventHubTrigger("twin-events",
                Connection = "ConnectionString",
                ConsumerGroup = "%DeviceTwinConsumerGroup%")] string[] messages,
                FunctionContext context)
        {
            var data = context.BindingContext.BindingData;
            var times = JsonSerializer.Deserialize<List<DateTime>>(data["EnqueuedTimeUtcArray"].ToString());

            for (int i = 0; i < messages.Length; i++)
            {
                var msgEvent = JsonDocument.Parse(messages[i]);
                var item = msgEvent.RootElement;
                var enqueuedTimeUtc = times[i];//corresponding event enqueue time for message
            }

            return new DeviceTwinOutput();
        }
    }
```

**Comment by alsami** [comment]
I agree also that this way is not as ideal as the binding that has been provided before. But it works that way.
Are there plans to directly support the binding of `EventData`?

Anyway, this can be closed  since the question is answered. Thanks a lot!
