### ISSUE TITLE
QueueTrigger cannot bind to Guid type

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#285]
QueueTrigger binds to string and POCOs, but cannot deserialize Guid, or presumably other primitive (easily deserializable) types

**Comment by fabiocav** [comment]
Our extensions project what is supported by the underlying bindings, and although `Guid` is not explicitly documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp#usage), if properly formatted, it should still fall back to deserialization. 

Though, adding the ability to bind to a Guid directly would also be pretty simple.

**Comment by backerman** [comment]
The same issue applies to `HttpTrigger`. Would it be reasonable to do a converter that looks for a constructor of arity 1 on the target type, accepting a string, and then use it if it exists? And if so would it be better to include in `TypeConverter` (does what you'd think it would from looking at the name) or a new converter?

**Comment by kshyju** [comment]
This issue was fixed in #582 

Could you please try to use the [version 1.6.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.6.0) of worker package? Let us know if you are still seeing any issues.

**Comment by onionhammer** [comment]
Will test when I'm back from vacation

**Comment by onionhammer** [comment]
Confirmed this is working now
