### ISSUE TITLE
Release notes are missing

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#2864]
### Description

Version 2.0 packages are available or nuger. But no release notes/changelog. Is not it a good practice to put release notes/changelog up online _before_ publishing the new packages to nuget?

### Steps to reproduce

1. Go to the project page.
2. No release notes

**Comment by lasyan3** [comment]
Yesterday we have v2.0 pushed and today I realized my functions has no invocation logs anymore since yesterday around 6pm... Coincidence ?
![Image](https://github.com/user-attachments/assets/067a436b-6271-425f-9225-5275a3dd9c7a)

**Comment by fabiocav** [comment]
@lasyan3 can you please open a separate issue with the information requested in the template? We'll be in a better position to investigate and engage with those details. Thanks!

**Comment by fabiocav** [comment]
Branches have been updated and the releases are out with notes. Doc changes are also in progress. 

Thank you!
