### ISSUE TITLE
.NET 9 Azure Functions Isolated: Visual Studio Publish to Azure, no functions

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-dotnet-worker#2865]
### Description

I have a simple Azure Function App that was using .NET Isolated.

Decided to update to `.NET 9` and after everything is updated deployed through existing GitHub pipeline. My functions are not displayed in Azure Portal and all I can see was `WarmupTrigger`.

So started simple.
1. Created Azure Function App with a HTTP trigger targeting .NET 9 Isolated
Confirmed it's running locally:
![Image](https://github.com/user-attachments/assets/7f00bba7-a382-4cb2-b55b-bca6f0b28711)

3. Visual Studio Publish
4. Created necessary resources via Visual Studio (Linux/Consumption)
5. Published

My function doesn't come up.
![Image](https://github.com/user-attachments/assets/fb3314fb-3865-4ed2-b52e-8781c42af1f4)

![Image](https://github.com/user-attachments/assets/5a2f44a7-c32a-4f03-8968-c3f1f073befc)

CSPROJ,
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <!-- Application Insights isn't enabled by default. See https://aka.ms/AAt8mw4. -->
    <!-- <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" /> -->
    <!-- <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" /> -->
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

App Settings,
```json
[
  {
    "name": "AzureWebJobsStorage",
    "value": "<REDACTED>",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~4",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet-isolated",
    "slotSetting": false
  },
  {
    "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
    "value": "0",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED",
    "value": "1",
    "slotSetting": false
  }
]
```
Confirmed it Uses `64bit`.
![Image](https://github.com/user-attachments/assets/7915e47b-be8e-4354-91e8-128993408ab9)

Shouldn't this be working without any issues, I mean this is the very basic.

**Comment by jaliyaudagedara** [comment]
Sometimes I am seeing the `WarmUp` trigger, not always though. (that's a separate issue I guess)
![Image](https://github.com/user-attachments/assets/1cce7e0e-9bf7-4a39-a6ef-d1ca2785af8a)

**Comment by fabiocav** [comment]
@jaliyaudagedara Linux Consumption .NET 9 support is still rolling. Have you tried different SKUs? 

You can track progress here: https://github.com/Azure/azure-functions-dotnet-worker/issues/2817
And here: https://github.com/Azure/azure-functions-host/issues/10602

Thank you!

**Comment by jaliyaudagedara** [comment]
ah, Thanks @fabiocav, I wasn't aware it's still rolling.

**Comment by fabiocav** [comment]
No worries, we're working through the deployments in those environments as fast, and safely, as possible.

**Comment by milen-denev** [comment]
Same issue, rollbacked to .net 8 until MS rolls out .net 9 to Azure Functions Consumption tier.

**Comment by jaliyaudagedara** [comment]
Deployed as a container to be on the safe side, all good.

**Comment by codemasta** [comment]
I also had to roll back to .NET 8 on Azure Function Consumption.

**Comment by GilShalit** [comment]
Is there a target date for Azure consumption .net9 isolated support? This also goes to the Visual Studio project template support.
