### ISSUE TITLE
Event Grid trigger function: internal server error when subscribing to a topic

### ISSUE THREAD

**Issue by KaiEkkrin** [Azure/azure-functions-dotnet-worker#287]
I deployed a new .NET 5 function app using the newly released 1.0.0 functions worker. It has two functions, one with an Event Grid trigger and one with a HTTP trigger. I want to consume events from an Event Grid topic.

I can successfully subscribe the HTTP function to my topic with `az eventgrid event-subscription create --event-type webhook ...`. (The function includes an implementation of the Event Grid handshake, of course.)

However, if I try to subscribe the Event Grid function with `az eventgrid event-subscription create --event-type azurefunction ...`, I instead get an error like this at the Azure console

```
Deployment failed. Correlation ID: 9c0e3d2f-9591-46f0-9581-adf3f00877d9. The operation failed due to an internal server error. The initial state of the impacted resources (if any) are restored. Please try again in few minutes. If error still persists, report 1b81e514-92f6-4b5e-a36c-ab5fbb44a861:3/11/2021 4:25:26 PM (UTC) to our forums for assistance or raise a support ticket .
```

There are no invocations logged of the function and no messages in its event stream so it looks like it doesn't get that far. However, I do notice that in the Functions section of my Function App in the Azure Portal, whilst my functions are shown in the table, the Trigger column is blank (unlike in some Function Apps using .NET Core 3 in-process functions, where the Trigger column is correctly populated.)

I tried to follow the sample closely and both triggers work fine in local debugging.

**Comment by fabiocav** [comment]
This might be somewhat unrelated to the worker, but it would be good to have access to the logs for closer investigation. Would you be able to share the app name?

For the portal issue, this is one of the known problems we're tracking with UX and a deployment is currently rolling out to address that. We hope to have that addressed soon.

@mhoeger and @ankitkumarr ; I know you've spent time going through the EG flows, so I'm tagging you here just in case I missed something obvious above.

**Comment by KaiEkkrin** [comment]
@fabiocav Thanks for the quick reply. The app is "softools-staging-workflow-service".

**Comment by KaiEkkrin** [comment]
@haeberle The `az` command I described above started working for me as of a few weeks ago, so something has been fixed somewhere. Try that 😄 

At the time when that command started working, I tried Azure Portal as you describe and that still didn't work for me. I automated my deployment with the CLI, so I haven't needed to try Azure Portal again.

**Comment by haeberle** [comment]
> @haeberle The `az` command I described above started working for me as of a few weeks ago, so something has been fixed somewhere. Try that 😄
> 
> At the time when that command started working, I tried Azure Portal as you describe and that still didn't work for me. I automated my deployment with the CLI, so I haven't needed to try Azure Portal again.

Thanks a lot, works well with your workaround!

**Comment by craigomatic** [comment]
> -opened my IoTHub in the azure portal
> 
> * want to add a new Event Subscription
> * select Azure Function as end point
> * Select my function as function app
> * no function is selectable

This still seems to be an issue in the Azure portal, in my case I'm trying to bind an event from Azure Media Services to my isolated process function and the function trigger that I'm expecting to see for EventGrid does not show up:

![image](https://user-images.githubusercontent.com/146438/134355543-347fbf89-4223-4ae5-95a2-d39b62b72bc1.png)
