### ISSUE TITLE
ConfigureFunctionsWorkerDefaults should also call AddEnvironmentVariables

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#288]
Env. variables is default means by which a function receives it's parameters when run on Azure, aren't they? Things like connection strings, various secrets and stuff. One would expect those are loaded to IConfiguration by default. And that seem to be the in-proc worker behavior everyone is used to. Am I correct?

**Comment by fabiocav** [comment]
This is reasonable. Technically a breaking change, but in practice, unlikely it would impact anyone at this point. 

One thing that differs from the in-proc mode is that all binding configuration is ultimately applied at the host level, so this primarily impacts custom config/options, and things like that within the scope of the worker, but might become a bigger issue in the future, so it's worth considering at this stage.
