### ISSUE TITLE
Controllers vs static methods syntax

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-functions-dotnet-worker#289]
Hello,

What do you think about stop using static methods for "triggers" and staring using more aspnetcore like syntax:

Example:
```
public class TestController : Controller
{
 private MyServiceWithScopeContext service1;

 public TestController(MyServiceWithScopeContext service1) {}

 [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]
 public HttpResponseData Test(HttpRequestData request)
 {
  return request.CreateResponse(HttpStatusCode.OK);
 }
}
```

Let's duscuss :)

**Comment by SeanFeldman** [comment]
That's already possible. And you don't have to inherit from a base class.

**Comment by Romfos** [comment]
@SeanFeldman could you please provide some example?

**Comment by SeanFeldman** [comment]
Absolutely. Have a look at the samples. Specifically: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/FunctionApp/Function5/Function5.cs

**Comment by Romfos** [comment]
@SeanFeldman ok, thank you!

**Comment by godefroi** [comment]
@Romfos @SeanFeldman the `[HttpTrigger]` attribute is only for parameters, right? Not on the method as is written above?

**Comment by SeanFeldman** [comment]
@godefroi correct. That's the actual trigger type.

**Comment by kshyju** [comment]
Thanks @SeanFeldman ☺️

Closing as answered.
