### ISSUE TITLE
Cannot run functions any more in VisualStudio 17.12.1

### ISSUE THREAD

**Issue by rwb196884** [Azure/azure-functions-dotnet-worker#2892]
### Description

I have an Azure Functions project that was working.

I updated VisualStudio to get .net9 and now it won't run any more when I click the 'play' button.

It says: `System.InvalidOperationException: 'Configuration is missing the 'HostEndpoint' information. Please ensure an entry with the key 'Functions:Worker:HostEndpoint' is present in your configuration.'`

Is there a fix for this?

### Steps to reproduce

Open previously working Azure Functions solution.
Click play.

**Comment by kshyju** [comment]
I downloaded your sample project and successfully ran it in F5 debug mode after adding a `local.settings.json` file to the project root. For reference, I'm using Visual Studio version 17.12.3.

**Comment by rwb196884** [comment]
/bot not-stale

There is already a `local.settings.json` in the zip.

I downloaded it and it does not run ![Image](https://github.com/user-attachments/assets/44db951d-856b-4368-8f8d-ac133c05acb7)

What are you doing different?
(VisualStudio 17.12.1.)

```
> > dotnet --info
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [android]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    35.0.7/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.android\35.0.7\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maui\9.0.0\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    18.0.9617/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maccatalyst\18.0.9617\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    18.0.9617/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.ios\18.0.9617\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
A terminal window opens but it does not contain anything.

**Comment by lukeawyatt** [comment]
I'm seeing this issue with my own function once deployed to Azure.  It runs locally, however.

**Comment by GrimRob** [comment]
> I'm seeing exactly the same issue

me too after VS upgrade. Rebooted and everything worked!

**Comment by crperez5** [comment]
same issue here

**Comment by Arch-Stalker** [comment]
For me the solution was to install Microsoft.Azure.Functions.Worker.Sdk package as top level. I originally had it as a transitive and the solution did not recognize the project as a function project (the solution explorer did not show the project symbol as that azure function lightning). Once I installed the package as top level, it stopped complaining about the host endpoint, I suspect the project did not know to look for the local settings file when it was "of the wrong type".

**Comment by WitnessMee** [comment]
I had the same  `Configuration is missing the 'HostEndpoint'`  issue. None of the suggested solutions worked for me.
I fixed it by installing the latest version of Azure Functions Core Tools.

Some more info:

I started testing by creating a new Azure Function App with CLI, Visual Studio Code and Visual Studio.

When I created a project with the CLI `func init LocalFunctionProj --worker-runtime dotnet-isolated --target-framework net8.0`, it didn't have that error but it was using an old version of `Microsoft.Azure.Functions.Worker` and `Microsoft.Azure.Functions.Worker.Sdk`. When you update those to 2.0 you get the error.

In Visual Studio Code you can use `Azure Functions: Create New Project....` and that uses versions 2.0 of `Microsoft.Azure.Functions.Worker` and you get the error when you start the function.

Create Azure Functions project in Visual Studio did not give any errors when starting it with F5.

So then I found out that Azure Functions Core Tools on my command line had version **4.0.5382**
`func --version`

Visual Studio was using version **4.0.6821**. So it's not using PATH but using a func that is included with Visual Studio. I don't know where it is.

The easiest way to fix it is to download the latest Azure Functions Core Tools version here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-csharp#install-the-azure-functions-core-tools

Everything was working for me after that.

**Comment by DGempler** [comment]
I was banging my head against the wall on this for a while after upgrading `Microsoft.Azure.Functions.Worker` until I happened to try moving `ConfigureFunctionsWorkerDefaults` (or depending on your use case, `ConfigureFunctionsWorkerDefaults`) up before any other configuration methods:

Example:
```cs
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureAppConfiguration((hostContext, configBuilder) =>
            { ...
```

**Comment by JosXa** [comment]
A project that ran fine a few weeks ago now fails with `Configuration is missing the 'HostEndpoint'`. I don't remember updating anything. How can this happen?

**Comment by rwb196884** [comment]
Started working again here. I have no idea why. So: maybe just leave it and go and do something else for a few months and hope for the best?
This is so shit it could be JavaScript.

**Comment by Stefan-Grant-Personal** [comment]
I also hit this issue today when migrating from the .NET 8 in-process model to .NET 8 isolated worker model for Azure Functions. None of the suggested ideas / workarounds above worked for me, however I managed to find a solution thanks to the comment by @WitnessMee: by downgrading all of the `Microsoft.Azure.Functions.Worker` packages to versions lower than 2.0.0, the error I got changed to `The gRPC channel URI 'http://:' could not be parsed`.

This led me to find this comment, which ultimately fixed the issue for me: https://github.com/Azure/azure-functions-dotnet-worker/issues/2121#issuecomment-1905832988.

In my case, this issue was caused by dependency injecting an instance of IConfiguration in my Program.cs file, just like the comment above. Removing `services.AddSingleton(config)` fixed this issue, and moreover, everything also worked after I upgraded back to the latest `Microsoft.Azure.Functions.Worker` packages.

**Comment by sopelt** [comment]
@Stefan-Grant-Personal  .. did you find any indicator (e.g. logs) that would hint towards this being related to IConfiguration besides the comments in #2121 ?
In another scenario I wasn't registering IConfiguration but it was used in some configuration similar to 
`s.AddOptions<NotificationSettings>().Configure<IConfiguration>((settings, configuration) => configuration.GetSection("Notification").Bind(settings));` so just the request to inject IConfiguration seems to break something (only deployed .. works without complaint in func tools/VS).

**Comment by Stefan-Grant-Personal** [comment]
@sopelt I'm afraid not. I purely managed to find the solution by following the steps I outlined above, and ultimately finding that comment in issue #2121.

**Comment by matshalf-telia** [comment]
In my case we had upgraded a durable Az-function set from .net6 and got the error. We solved the problem by removing section by section in the host.json file until the function run again. We had a bad section "customHandler" left from the old version.

**Comment by remcogroen11** [comment]
I made some progress with the Azure Function not working when deployed to a Function App. Locally is runs fine.

By adding Functions__Worker__HostEndpoint as an environment variable and setting the value to the default domain URL of the function app, the error changed to 'Unhandled exception. System.InvalidOperationException: Channel is configured with insecure channel credentials and can't use a HttpClient with a 'https' scheme.'

Then I changed https to http, but this resulted in 'Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')' specifically 'at Program.<Main>$(String[] args) in D:\a\1\s\Field.ExactOnlineImportApp\AzureFunctions\Program.cs:line 28'. Sadly this refers to the line 'builder.Build().Run();' in my program.cs, so no clue to what 'value' is null.

**Comment by pevnyk** [comment]
> For me the solution was to install Microsoft.Azure.Functions.Worker.Sdk package as top level. I originally had it as a transitive and the solution did not recognize the project as a function project (the solution explorer did not show the project symbol as that azure function lightning). Once I installed the package as top level, it stopped complaining about the host endpoint, I suspect the project did not know to look for the local settings file when it was "of the wrong type".

This comment helped me.
The Azure function lightning symbol was missing -> project not recognized as Azure Function.

However, I only needed a restart of VS (no extra install) and the lightning symbol was back -> exception gone.

**Comment by avnet78** [comment]
Reinstalling Visual Studio Azure Development Toolkit fixed the issue for me

**Comment by lrsperanza** [comment]
I opened Visual Studio Installer and modified it. After installing Visual Studio Azure Development Toolkit, it worked. I just didn't have it installed.

**Comment by nstratton-srx** [comment]
For me I use Kudu to run manually if the config isn't right and I need to see startup errors. (It's the only way to see errors in program.cs)
Once they run right I get this message in kudu, which is basically saying "This isn't the right environment for me." but at least my startup testing is complete.

**Comment by PuppyGummy** [comment]
For me, deleting `%localappdata%\AzureFunctionsTools` folder worked
