### ISSUE TITLE
AOT/Trimming support for Azure.Functions.Worker

### ISSUE THREAD

**Issue by jamescrosswell** [Azure/azure-functions-dotnet-worker#2899]
I'm trying to enable trimming for a library that integrates with `Microsoft.Azure.Functions.Worker`. That library makes a call to `IFunctionsWorkerApplicationBuilder.UseMiddleware<T>` [here](https://github.com/getsentry/sentry-dotnet/blob/bd62cf0421cc7a5d7b7804f8461fae00d47d43b8/src/Sentry.Azure.Functions.Worker/SentryFunctionsWorkerApplicationBuilderExtensions.cs#L37).

When I try to test for trim compatibility, I'm getting the following warning/error:
> D:\a\_work\1\s\src\DotNetWorker.Core\Hosting\WorkerMiddlewareWorkerApplicationBuilderExtensions.cs(99,13): Trim analysis error IL2091: Microsoft.Extensions.Hosting.MiddlewareWorkerApplicationBuilderExtensions.UseMiddleware<T>(IFunctionsWorkerApplicationBuilder): 'TService' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<TService>(IServiceCollection)'. The generic parameter 'T' of 'Microsoft.Extensions.Hosting.MiddlewareWorkerApplicationBuilderExtensions.UseMiddleware<T>(IFunctionsWorkerApplicationBuilder)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Which appears to come from here:
https://github.com/Azure/azure-functions-dotnet-worker/blob/8ea4ffc6f9e0d7d9319734faa5486cd64db30e42/src/DotNetWorker.Core/Hosting/WorkerMiddlewareWorkerApplicationBuilderExtensions.cs#L99

I assume the solution would be to change the signature for the method so that the generic type parameter is decorated appropriately. Something like:
```diff
-       public static IFunctionsWorkerApplicationBuilder UseMiddleware<T>(this IFunctionsWorkerApplicationBuilder builder)
+       public static IFunctionsWorkerApplicationBuilder UseMiddleware<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>(this IFunctionsWorkerApplicationBuilder builder)
            where T : class, IFunctionsWorkerMiddleware
        {
            builder.Services.AddSingleton<T>();
```

Is this an oversight or has trimming support for `Microsoft.Azure.Functions.Worker` not yet been considered/implemented?

**Comment by kshyju** [comment]
The `Microsoft.Azure.Functions.Worker` package is not currently optimized for trimming or AOT compilation. While we plan to address this in the future, it is currently a lower priority compared to other ongoing work.

**Comment by jamescrosswell** [comment]
> The `Microsoft.Azure.Functions.Worker` package is not currently optimized for trimming or AOT compilation. While we plan to address this in the future, it is currently a lower priority compared to other ongoing work.

OK thanks @kshyju - I'll make it note in our library to that effect. 

btw: this is somewhat surprising. Serverless applications would seem (intuitively) to be at the top of the list of places where AOT might offer the biggest benefits...

**Comment by kshyju** [comment]
One challenge we noticed previously was the size of the payload (native executable) generated by AOT compilation. For HTTP cold start scenarios, this leads to longer download and unzip times. We plan to revisit and reevaluate this next year to explore potential improvements.

**Comment by kshyju** [comment]
Closing as answered. Happy Holidays!
