### ISSUE TITLE
Registering a function class in .ConfigureServices(...) doesn't work.

### ISSUE THREAD

**Issue by Mithras** [Azure/azure-functions-dotnet-worker#290]
This
```
.ConfigureServices((context, services) =>
{
    services.TryAddTransient(x => new MyFunction(...));
})
```
doesn't work. I can't find a way to provide my own functions factory. It makes it impossible to use third party containers like Autofac, for example.
I found [IFunctionActivator.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/IFunctionActivator.cs) but whatever `IServiceProvider` it uses is not the one I have any control over. And I can't provide my own `IFunctionActivator` either because it's `internal`.

**Comment by Mithras** [comment]
I'm really confused what's going on inside. So `myFunction ` here is resolved using my factory as expected but `next()` creates a new one which is not from the `functionContext.InstanceServices`.
```
public class TestMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext functionContext, FunctionExecutionDelegate next)
    {
        var myFunction = functionContext.InstanceServices.GetService<MyFunction>();
        await next(functionContext);
    }
}
```

**Comment by fabiocav** [comment]
Thanks for opening this!

Yes, `IFunctionActivator` is the mechanism that will be surfaced to control function instantiation. Those APIs will be made public as we continue reviews and ensure they're stable. This particular API is a pretty straight forward one that I would expect to have reviewed in the next round and made public in the next drop.

**Comment by godefroi** [comment]
Will this API allow us to get the function instance from middleware? Or, at least, the function `Type` from middleware?
