### ISSUE TITLE
update Microsoft.Azure.Functions.Worker.Extensions.EventGrid to fix Azure.Core dependency

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-functions-dotnet-worker#2905]
### Description

similar to issue #2635 (which fixed EventHubs and ServiceBus), the EventGrid extension also needs to be updated to use the latest Microsoft.Azure.WebJobs.Extensions.EventGrid package which has a fixed reference to Azure.Core

Microsoft.Azure.WebJobs.Extensions.EventGrid version needs to be updated to 3.4.3 here: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.EventGrid/src/Worker.Extensions.EventGrid.csproj

### Steps to reproduce

reference v3.4.2 in your isolated function project and it will flag Azure.Core v1.40

**Comment by satvu** [comment]
Closing as this has been released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventGrid/3.4.3

**Comment by briandunnington** [comment]
The underlying dependency was updated, but the Worker Extension still references the old 3.4.2 version: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventGrid

**Comment by briandunnington** [comment]
looks like v3.4.3 was published and then delisted due to a bug.

![Image](https://github.com/user-attachments/assets/19d601e4-2d3d-47d8-ac33-a3d1aabf66ee)

**Comment by iprashantp** [comment]
@satvu whats the plan for v3.4.3, its still being flagged as vulnerability.

**Comment by njmicrosoft** [comment]
@satvu Can you please address this as it has been flagging for all our services
