### ISSUE TITLE
SignalR extension not working with Groups

### ISSUE THREAD

**Issue by danielegiallonardo** [Azure/azure-functions-dotnet-worker#294]
Hi, I was trying to migrate our functions to net5 worker, but I didn't manage to make the SignalR "groups" feature work.

Following is the function I use to register a user to a group.

Before:
```csharp
        [FunctionName("Notifications_AddToGroup")]
        public async Task<IActionResult> AddToGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "addToGroup")]HttpRequest req,
            [SignalR(HubName = "notifications")] IAsyncCollector<SignalRGroupAction> signalRGroupActions)
        {
                var userId = req.Query["userId"];
                var groupName = req.Query["groupName"];

                await signalRGroupActions.AddAsync(
                    new SignalRGroupAction
                    {
                        UserId = userId,
                        GroupName = groupName,
                        Action = GroupAction.Add
                    });
                return new OkResult();
        }
```

After:
```csharp
        [Function("Notifications_AddToGroup")]
        public static async Task<NotificationOutput> AddToGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "addToGroup")] HttpRequestData req,
            FunctionContext executionContext)
        {
            var output = new NotificationOutput();
                var query = HttpUtility.ParseQueryString(req.Url.Query);
                var userId = query["userId"];
                var groupName = query["groupName"];

                output.Notifications.Add(
                    new
                    {
                        userId = userId,
                        groupName = groupName,
                        action = "add"
                    });
                output.Response = req.CreateResponse(HttpStatusCode.OK);
            return output;
        }
```

The functions returns 200, no errors in the console (verbose).

Following is the function I used to send a message to a group.

Before:
```csharp
        [FunctionName("Notifications_SendMessage")]
        public async Task<IActionResult> SendMessage(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "sendMessage")]HttpRequest req,
            [SignalR(HubName = "notifications")]IAsyncCollector<SignalRMessage> signalRMessages)
        {
                string userId = req.Query["userId"];
                string groupName = req.Query["groupName"];

                using var sr = new StreamReader(req.Body);
                using var jsonTextReader = new JsonTextReader(sr);
                var data = JObject.Load(jsonTextReader);

                await signalRMessages.AddAsync(new SignalRMessage()
                {
                    UserId = userId,
                    GroupName = groupName,
                    Target = "SendMessage",
                    Arguments = new[] { data }
                });
                return new OkResult();
        }
```

After:
```csharp
        [Function("Notifications_SendMessage")]
        public static async Task<NotificationOutput> SendMessage(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "sendMessage")] HttpRequestData req,
            FunctionContext executionContext)
        {
                var output = new NotificationOutput();
                var query = HttpUtility.ParseQueryString(req.Url.Query);
                var userId = query["userId"];
                string groupName = query["groupName"];

                using var sr = new StreamReader(req.Body);
                using var jsonTextReader = new JsonTextReader(sr);
                var data = JObject.Load(jsonTextReader);

                output.Notifications.Add(new
                {
                    userId = userId,
                    groupName = groupName,
                    target = "SendMessage",
                    arguments = new[] { data }
                });
                output.Response = req.CreateResponse(HttpStatusCode.OK);
                return output;
        }
    }
```
The functions returns 200, no errors in the console, BUT no message is received on the client side. 
The code on the client side works with the former version. And I managed to send messages without the "groups" feature.

The output object used for this sample is

```csharp
    public class NotificationOutput
    {
        [SignalROutput(HubName = "notifications")]
        public List<object> Notifications { get; set; } = new List<object>();
        public HttpResponseData Response { get; set; }
    }
```

Is the SignalR groups feature supported?

**Comment by fabiocav** [comment]
This should work, so it requires some investigation (thank you for the repro code).

@anthonychu is this something you've tried?

**Comment by anthonychu** [comment]
Hard to tell what could be wrong here. I’d try the following:

- Test that you can send and receive broadcast messages (no group or user id)
- Confirm that the client is connecting using a user id (you might need to log the token that is returned and inspect it using something like https://jwt.ms
- It’s not clear what your clients are. Recommend using JavaScript in the browser to test and check the browser dev tools to see if the negotiation and connection are done correctly and the http requests are made correctly to add user to group. Also check websocket traffic to see if there are any frames that are received.

**Comment by danielegiallonardo** [comment]
Ok, it turned out it was partially my bad :-D
It seems you changed the internal default json serialization library in the SignalR extension, from Newtonsoft to System.Text.Json.
So, I've changed a few lines, from this

```csharp
using var sr = new StreamReader(req.Body);
using var jsonTextReader = new JsonTextReader(sr);
var data = JObject.Load(jsonTextReader);
```

to this

```csharp
var data = await req.ReadFromJsonAsync<object>();
```

and now it works again.

I know you shouldn't use JObject directly, but anyway this seems like a breaking change that should be documented.
Thank you for your support, I think you can close the issue.

**Comment by Arash-Sabet** [comment]
@fabiocav is there a document to explain clearly what needs to be done to send a message to a group or a specific user in the group? We have employed the approach quite similar to @danielegiallonardo's to create a group of users to send out a message but no messages were received on the client side.

Also, the following code is supposed to send out a message to all connected users and it does but the message is `null`  on the client side:

```cs
	[Function("SendMessageToAllUsers")]
	[SignalROutput(HubName = "myhub")]
	public static async Task<object> SendMessageToUserAsync(
					[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
					FunctionContext executionContext)
	{
		var logger = executionContext.GetLogger("Messages");
		logger.LogInformation("C# HTTP trigger function processed a request.");
		var message = await req.ReadFromJsonAsync<object>();
		return new
		{
			target = "newMessage",
			Arguments = new[] { message }
		};
	}
``` 

This is the client's code after a successful negotiation which receives `null` message from the function above while we are happy to see that "newMessage" was raised:

```cs
connection.On<object>("newMessage", message =>
{
	Console.WriteLine($"{DateTime.Now} - Received the following message: {message}");
});
```

Also, the following function never sends out a message to the group's user because the client code is not raised:

```cs
	[Function("SendMessageToUserInGroup")]
	[SignalROutput(HubName = "myhub")]
	public static async Task<MessageOutput> SendMessageToUserInGroupAsync(
		[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "sendMessagetoUser/{group}/{userId}")] HttpRequestData req,
		string group,
		string userId,
		FunctionContext executionContext)
	{
		var output = new MessageOutput();
		var message = await req.ReadFromJsonAsync<object>();
		output.Notifications.Add(new()
		{
			userId = userId,
			groupName = group,
			target = "sendMessage",
			arguments = new[] { message }
		});
		output.Response = req.CreateResponse(HttpStatusCode.OK);
		return output;
	}
```

It is really frustrating to see that the entire signalR application used to work in the function app v3 in .net core 3.1 flawlessly but it cannot simply back to normal after migrating to dotnet-isolated functions> Following different posts on github and days of attempts did not get us anywhere.

**Comment by jviau** [comment]
@Y-Sindo can you follow up on this issue? Is this now supported, or soon to be supported?

**Comment by Y-Sindo** [comment]
@jviau SignalR extensions feature with Groups is now supported. For the case from [Arash-Sabet](https://github.com/Arash-Sabet), I believe it is because the `Argument` is `PascalCase` while only the `camelCase` is recognized.  Now we recommend using built-in types from SignalR extensions suh as `SignalRMessageAction` to avoid such kinds of problem. The build-in types guarantee to work for the default serialization settings. For more detail about `SignalRMessageAction`, see https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-output?tabs=isolated-process&pivots=programming-language-csharp#send-to-a-user .

**Comment by satvu** [comment]
Closing as the original case is now supported.
