### ISSUE TITLE
"Test/Run" option not available in portal

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#295]
![image](https://user-images.githubusercontent.com/969938/110983698-b2b77080-832f-11eb-9f61-fcbc91c56a81.png)

Even though the tooltip says "Only available for HTTP triggered functions" the test/run button is still disabled even for HTTP triggered functions

**Comment by fabiocav** [comment]
We are tracking a portal update/fix to address an issue with this.

Will keep this open so we can track the deployment completion.

@ankitkumarr to confirm this is indeed the issue that is being addressed with the deployment.

**Comment by kshyju** [comment]
@takyyon Could you help with this issue? I can still repro. The "fucntion-editor-file-selector" dropdown is empty in the case of a dotnet oop function app. When I check a node js app, the dropdown lists the files (ex: index.js) and the test/run option is enabled.

**Comment by kshyju** [comment]
@cloudmelon

**Comment by fabiocav** [comment]
Thanks for reporting. 

This is being tracked by the portal team. Closing this here as there are no actions required in this repo.
