### ISSUE TITLE
HttpResponseData missing writeBytesAsync method

### ISSUE THREAD

**Issue by allanlw** [Azure/azure-functions-dotnet-worker#300]
`HttpResponseData` has a `writeString` and `writeStringAsync`, and it has `writeBytes` but not `writeByteAsync`.

Workaround is to call to `response.Body.writeAsync` instead, but this seems like an oversight.

**Comment by oscarvantol** [comment]
@fabiocav Would you consider/appreciate a PR for something like this?

**Comment by fabiocav** [comment]
Sure! I was planning on taking this, but if you want to submit a PR, that would be more than welcome!
