### ISSUE TITLE
[Critical] Why new azure functions sdk for .NET 5 has dependencies on .NET core 3.1 sdk?

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-functions-dotnet-worker#301]
Hello, I have following error during build my application in .net 5 sdk docker container:
```
  WorkerExtensions -> /tmp/o0t5oyty.vjl/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App] [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64 [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]

/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/tmp/o0t5oyty.vjl/WorkerExtensions.csproj]
```

Why it depends on .net core 3.1 sdk?
It blocks our build process :)

**Comment by eriklieben** [comment]
Might be related to last point of release notes:
https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/1.0.0

- Fix issue with referencing extensions that have native dependencies:
  - To address this, a default dependency on .NET Core 3.1 SDK was added when targeting Azure Functions 3.0. Note: This dependency can be overridden by setting a build property ```<_FunctionsExtensionTargetFramework>netstandard2.0<_FunctionsExtensionTargetFramework/>``` but this is only recommended if only using bindings without native dependencies.

**Comment by Romfos** [comment]
@eriklieben Thank you for link, but how ca I understand do I use native dependencies or not? I'm using http + time triggers

**Comment by dngache** [comment]
@Romfos Yes there is still a dependency on .netcore 3.1. I logged the same issue a few days ago and the ticket was closed and I was directed to the workaround here https://github.com/Azure/azure-functions-dotnet-worker/wiki/Known-issues#net-core-31-dependency. I tried it and it did not work unfortunately. https://github.com/Azure/azure-functions-dotnet-worker/issues/297.

**Comment by fabiocav** [comment]
@Romfos while targeting Azure Functons V3, that will be requirement with the details/workaround mentioned in the wiki. 

Can you also help us understand why you believe this is a critical issue? Helping understand the impact also helps us prioritize work.

@dngache I'll look at your follow up there.

**Comment by Romfos** [comment]
we are using official .net sdk docker image for building our big app

@fabiocav
I think it could be closed as duplicate of https://github.com/Azure/azure-functions-dotnet-worker/issues/297
