### ISSUE TITLE
IHttpContextAccessor fails to resolve dependency after upgrade

### ISSUE THREAD

**Issue by miantosca** [Azure/azure-functions-dotnet-worker#306]
One of my functions was resolving dependencies (**IHttpContextAccessor, IHostingEnvironment**) that were being registered automatically in the pre-isolated process function host.

Is there a way to inject dependencies that were registered in the old host automatically?

**Comment by fabiocav** [comment]
The DI behavior is the same, but the set of services you'd have here is different, and mostly impacted by what you register as part of your application bootstrap.

For the specific dependencies you've mentioned; `IHttpConextAccessor` is an ASP.NET Core service, and not automatically added by the Worker (as the ASP.NET Core types are not yet supported here). `IHostingEnvironment` should be replaced with `IHostEnvironment`

**Comment by miantosca** [comment]
@fabiocav thank you that worked!
