### ISSUE TITLE
Functions does not work when Azure Functions Proxy is added

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-dotnet-worker#309]
### Repro steps

1. `func init ProxyTest --worker-runtime dotnetisolated`
2. `cd ProxyTest`
3. Create `proxies.json` and add csproj

**proxies.json**

```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "proxytest": {
      "matchCondition": {
        "route": "hello"
      },
      "responseOverrides": {
        "response.body": "hello, world"
      }
    }
  }
}

```

### Actual log

>[2021-03-16T17:31:15.530Z] Worker process started and initialized.
>[2021-03-16T17:31:15.536Z] Exception encountered while listening to EventStream
>[2021-03-16T17:31:15.537Z] Microsoft.Azure.WebJobs.Script.Grpc: Object reference not set to an instance of an object.

### Additional info

Core Tools Version:       3.0.3388 Commit hash: fb42a4e0b7fdc85fbd0bcfc8d743ff7d509122ae
Function Runtime Version: 3.0.15371.0

**Comment by mhoeger** [comment]
I think we need to add a "success" status for this gRPC message:
https://github.com/Azure/azure-functions-dotnet-worker/blob/19e4121de74234a617e3d1467bd78fdb5f5e4176/src/DotNetWorker.Grpc/GrpcWorker.cs#L237

**Comment by Romfos** [comment]
Hello, I can confirm that proxies aren't working. 

It is critical for my application. Please, fix it asap

**Comment by WhyDoYouDoThis** [comment]
I'll add my name to the list of CRITICAL HELP <insert icon of hair pulling out>

**Comment by WhyDoYouDoThis** [comment]
I pulled the branch from @fabiocav and, with appropriate package references, re-ran my proxy Functions and it worked!!  THanks @fabiocav for such quick work on the fix!
