### ISSUE TITLE
Developer and debugging experience

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-functions-dotnet-worker#311]
Are there any plans to support "Start debugging (F5)" for debugging?

**Comment by fabiocav** [comment]
Absolutely! This work is in progress and should be landing in VS soon. We'll post an announcement here when that happens (as well as usual channels like Twitter, announcements repo, etc.)

**Comment by vu-pb** [comment]
@faiocav, are there any ETAs on when this feature will be released?

**Comment by fabiocav** [comment]
This will be coming out with VS 16.10, which should be released soon.

**Comment by RichMercer** [comment]
How about Visual Studio Mac support? Is that also planned?

**Comment by marisks** [comment]
With VS 16.10.1 it starts the function app but fails to attach a debugger - just loads and never stops.
![image](https://user-images.githubusercontent.com/646298/122047726-22cf0a00-cde9-11eb-9525-3919436c4af0.png)
And in the console you get:
```
[2021-06-15T11:50:32.618Z] Starting worker process failed
[2021-06-15T11:50:32.620Z] The operation has timed out.
```

Maybe it is related to debugging failing also from the command line in the latest version. I was running `func host start --dotnet-isolated-debug` and it worked once and I could attach a debugger. All later calls just didn't show a PID of the process and failed with exception:

**Comment by jasonhill** [comment]
We get the same timeout issues when trying to debug a function app using .Net 5 and isolated worker. The IDE hangs and we get the same timeout errors outlined above. It only seems to happen when RunOnStartup=true on a TimerTrigger though. If we remove that, then debugging starts OK and we can issue a post request against the worker to manually fire the function and debug it normally.

**Comment by jasonhill** [comment]
Actually, it seems that this issue happens whenever a function attempts to run when the process first starts up, i.e. if RunOnStartup=true or if the timer trigger is past due.

**Comment by stevieray8450** [comment]
> With VS 16.10.1 it starts the function app but fails to attach a debugger - just loads and never stops.

Also seeing the same issue

**Comment by michel-weber** [comment]
@fabiocav With VS 16.11.3 & VS 17.0.0 Preview 4.1, debugging (F5) does not work if a TimerTrigger is used and RunOnStartup=true or if the timer trigger is past due. Please fix.

**Comment by soninaren** [comment]
This should be working now.
