### ISSUE TITLE
[Disable] attribute

### ISSUE THREAD

**Issue by jsheetzati** [Azure/azure-functions-dotnet-worker#312]
Is the [Disable] attribute supported with the new azure-functions-dotnet-worker? Not seeing the attribute available.

https://docs.microsoft.com/en-us/azure/azure-functions/disable-function#c-class-libraries

**Comment by brettsam** [comment]
Good catch -- this is not currently supported with an attribute (but the other methods in that topic continue to work).

**Comment by jsheetzati** [comment]
Any idea when this might be added? We run our azure functions in a multi region scenario and use an app setting on our backup region to disable all our timer functions. Our timers aren't written in a way to support active/active.

**Comment by amikapoor** [comment]
@brettsam Similarly, the `[Singleton]` attribute does not seem to work either. Is there any work around or fix planned for this?

**Comment by fabiocav** [comment]
We've reviewed this and do not have a plan to bring this support at the moment. 

The recommendation is to use the approaches documented here: https://learn.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=portal
