### ISSUE TITLE
ICollector<Message> on service bus trigger

### ISSUE THREAD

**Issue by froghramar** [Azure/azure-functions-dotnet-worker#317]
We have quite a few azure functions using .Net core version 3.1. I was checking the code samples for service bus provided here as we are planning to migrate them to .NET 5. Here is how our sample azure function looks like -

```
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.ServiceBus;

namespace IGB2B.Essential.Functions.EventPublisher
{
    public class TestFunction
    {
        [FunctionName("TestFunction")]
        public void Run(
            [ServiceBus(
                "topicName",
                Connection = "ServiceBusConnectionString",
                EntityType = EntityType.Topic)]
            ICollector<Message> topicCollector)
        {
            foreach (...)
            {
                topicCollector.Add(new Message
                {
                    ...
                });
            }
        }
    }
}
```

Can you please provide more code samples for the use cases supported in the older versions?

**Comment by djjlewis** [comment]
I ran into exactly this issue last night and also could not find any information or docs on how to this. The closest I could find was a reference in issue #179  to use `OutputBinding` for returning multiple SignalR messages, but this was removed in the recent PR #158.

I managed to get it working by using an array of string as the return type for the function and returning an array of serialisaed JSON strings e.g.

```csharp
[Function("ServiceBusFunction")]
[ServiceBusOutput("queue-name", EntityType.Queue, Connection = "ServiceBus")]
public static string[] Run([TimerTrigger("0 */5 * * * *", RunOnStartup = true)] MyInfo myInfo, FunctionContext context)
{
    var sendNotificationMessages = new List<string>();
    foreach (var message in myMessages)
    {
      sendNotificationMessages.Add(JsonConvert.SerializeObject(message));
    }
    return sendNotificationMessages.ToArray();
}
```

Not sure if that is the recommended approach, but initial tests indicate it is doing what I would expect it to.

I am wondering though if it's possible to return an Azure Service Bus `Message` type so we could set `MessageId` etc for corrlelation and de-duplication?

**Comment by fabiocav** [comment]
@frogrammer as you found, `ICollector` is not supported in the OOP model, in order to add multiple messages, you can work with your output binding using an `IEnumerable`/`IEnumerable<T>` type (e.g. `List<T>`, arrays, etc.)

@djjlewis has a good example.

Here's another using queues and multiple outputs:

``` csharp

public class HttpToQueue
{
    private readonly ILogger<HttpToQueue> _logger;
    public HttpToQueue(ILogger<HttpToQueue> logger)
    {
        _logger = logger;
    }
    [Function("HttpToQueue")]
    public HttpToQueueReturn Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
    {
        _logger.LogInformation("C# HTTP trigger function processed a request.");
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
        response.WriteString("Welcome to Azure Functions!");
        return new HttpToQueueReturn
        {
            Response = response,
            QueueMessages = Enumerable.Range(0, 10)
        };
    }
    public class HttpToQueueReturn
    {
        public HttpResponseData Response { get; set; }
        [QueueOutput("http-to-queue")]
        public IEnumerable<int> QueueMessages { get; set; }
    }
}
```

**Comment by froghramar** [comment]
Thanks @djjlewis and @fabiocav .

Your examples have answered well to my query.

**Comment by fabiocav** [comment]
Great to hear. Closing as answered.
