### ISSUE TITLE
DI injected IConfiguration cannot get any custom settings from local.settings.json

### ISSUE THREAD

**Issue by felinepc** [Azure/azure-functions-dotnet-worker#318]
I'm using the just released  .NET 5 isolated process Azure Function project template for Visual Studio 2019, following[ this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-developer-howtos?tabs=browser&pivots=development-environment-vs).

I created a project using the `EventHubTrigger` template.

Per [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection), DI is available, and namely `Microsoft.Extensions.Configuration.IConfiguration` is available by default and safe to take as a dependency.

However, my injected `IConfiguration` instance fails to obtain any values in `local.settings.json`.

Contents of `local.settings.json`:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "EvhConnectionString": "omitted",
    "MyTestOption": "test:"
  }
}
```
Contents of Azure function:
```
public class MyAzureFunction
{
    private readonly IConfiguration _config;

    public MyAzureFunction(IConfiguration config)
    {
        _config = config;
    }

    [Function("MyAzureFunction")]
    public void Run([EventHubTrigger("myeventhub", Connection = "EvhConnectionString")] string[] input, FunctionContext context)
    {
        Console.WriteLine($"Testing options :{_config.GetValue<string>("MyTestOption")}");

        var logger = context.GetLogger("MyAzureFunction");
        logger.LogInformation($"First Event Hubs triggered message: {input[0]}");
    }
}
```
I proceeded to run the function locally via `func start`. The value obtained by `IConfiguration` is always null.

**Comment by kinetiq** [comment]
@v-anvari Any word on this? It's causing me some problems.

**Comment by mhoeger** [comment]
@kinetiq - I think you are running into this https://github.com/Azure/azure-functions-dotnet-worker/issues/288, you should be able to add the following to your host builder configuration in program.cs to bind to the environment variables in configuration:
```
.ConfigureAppConfiguration(c =>
{
    c.AddEnvironmentVariables();
})
```

Note that in the next release, this will be done by default.

@ggailey777 - I wonder if this doc on [dependency injection](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) needs to be moved or rewritten since it's currently more about in-proc dotnet?

**Comment by ggailey777** [comment]
@mhoeger I'm currently working on adding a note to that DI article to indicate that it only applies to in-proc (i.e. C# class library) functions. Is it sufficient to point folks off to the [ASP.NET Core DI article](https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0), or should we have a more comprehensive DI reference sample in this repo too?

**Comment by felinepc** [comment]
@mhoeger Thanks this does work.

**Comment by kinetiq** [comment]
@mhoeger @felinepc That's very helpful, thanks to both of you!
