### ISSUE TITLE
Apparently unable to get signalR negotiation going in azure functions .net 5.0

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#324]
I am trying to gradually transform the scaffolded code to be able to use it for singalR negotiation per the method below:

```
[Function("HttpExample")]
		public static HttpResponseData Run(
			[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] 
			HttpRequestData req,
			[SignalRConnectionInfo(HubName = Negotitate.HubName, UserId = "{headers.x-ms-signalr-userid}")]
			SignalRConnectionInfo connectionInfo,
			FunctionContext executionContext)
		{
			var logger = executionContext.GetLogger("HttpExample");
			logger.LogInformation("C# HTTP trigger function processed a request.");

			var response = req.CreateResponse(HttpStatusCode.OK);
			response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

			response.WriteString("Welcome to Azure Functions!");

			return response;
		}
```
But I started getting the following compile error message:

>  error AZFW0001: The attribute 'SignalRConnectionInfoAttribute' is a WebJobs attribute and not supported in the .NET Worker (Isolated Process).

So, is this error imlying that we cannot use signalR in .NET 5.0? Or there's a solution that I am unaware of it?

**Comment by fabiocav** [comment]
As documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#extension-packages), you need to use the Worker packages for the extensions. For SignalR, you must use https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.SignalRService/

**Comment by fabiocav** [comment]
One thing I'm curios about as the build error (primarily as we can continue to enhance usability). The help link from the build error should take you to the page that describes the problem and the solution, with instructions on how to fix it. Was that insufficient?

**Comment by arashcomsense** [comment]
@fabiocav Frankly, I cannot remember whether or not there was a link. I found a sample repo in Anthony Chu's Github repos and that gave me the right the direction.

**Comment by arashcomsense** [comment]
@fabiocav @anthonychu are there any examples related to adding a user to signalR group and also sending a message to a group, I opened an issue here: https://github.com/anthonychu/azure-functions-dotnet5-signalr-sample/issues/1
