### ISSUE TITLE
NU3028 and NU3037 Nuget errors trying to build on Arch Linux

### ISSUE THREAD

**Issue by djjlewis** [Azure/azure-functions-dotnet-worker#327]
I'm trying to build a new isolated functions project on Arch Linux. I have all the pre-requisites installed from the [starter guide](https://docs.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-process-developer-howtos?pivots=development-environment-vscode&tabs=browser)

I appreciate Arch is not currently listed as a supported version of Linux, but I have been developing .NET Core / .NET apps full-time on Arch for over a year now with no other problems.

I'm guessing it might be to do with with how root certificates are being handled from looking at similar problems where these errors surfaced, so any help would be appreciated.

```sh
Determining projects to restore...
/tmp/xc2s20g1.nf2/WorkerExtensions.csproj : error NU3028: Package 'Microsoft.NETCore.Targets 3.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/tmp/xc2s20g1.nf2/WorkerExtensions.csproj : error NU3037: Package 'Microsoft.NETCore.Targets 3.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/tmp/xc2s20g1.nf2/WorkerExtensions.csproj : error NU3028: Package 'Microsoft.NETCore.Targets 3.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
  Failed to restore /tmp/xc2s20g1.nf2/WorkerExtensions.csproj (in 1.48 sec).
```

`dotnet --version`: `5.0.201`
`func --version`: `3.0.3388`
`az --version`: `azure-cli 2.20.0`

```
 dotnet --list-sdks
2.1.814 [/usr/share/dotnet/sdk]
2.2.207 [/usr/share/dotnet/sdk]
3.0.103 [/usr/share/dotnet/sdk]
3.1.113 [/usr/share/dotnet/sdk]
5.0.201 [/usr/share/dotnet/sdk]
```

**Comment by fabiocav** [comment]
Thank you for reporting this. Will follow up with the team that owns the package and see what action, if any, is required.

In the meantime, have you tried following the suggestion documented here (please also look at the warning :) ): https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode-481

**Comment by djjlewis** [comment]
Thanks @fabiocav, I tried the suggestion of setting the environment variable in that link but unfortunately has not made any difference.

**Comment by djjlewis** [comment]
It seems this is related to a NuGet certificate error which also affected Debian installs earlier in the year:

https://bbs.archlinux.org/viewtopic.php?id=264684
https://bugs.archlinux.org/task/70095
https://github.com/NuGet/Announcements/issues/49

By downgrading the `ca-certificates-mozilla` package to `3.62-1` as advised in one of those links, the projects are building again and functions are running locally.

For reference to anyone else, here is the command I ran, as I still had the old package in cache:

`$ sudo  pacman -U /var/cache/pacman/pkg/ca-certificates-mozilla-3.62-1-x86_64.pkg.tar.zst`

**Comment by martynas-m** [comment]
any updates? still not working. Not sure if I would like to downgrade certificate packages for my pc

**Comment by djjlewis** [comment]
I believe this is the main issue tracking this https://github.com/dotnet/announcements/issues/180 

apparently build 5.0.202 of the .NET SDK should have disabled package verification so I'd check to see if you have that version installed and try.

I've kept my ca-certificates at 3.62-1 for now as don't want to risk breaking my main dev machine for now, but perhaps will try at the weekend.

**Comment by fabiocav** [comment]
@djjlewis going through stale issues and this was still in the backlog. Did you get this to work as expected or are you still experiencing issues?

Thanks!
