### ISSUE TITLE
Getting error "Starting worker process failed"

### ISSUE THREAD

**Issue by harisbotic** [Azure/azure-functions-dotnet-worker#339]
I tried running a function with HttpTrigger and got printed this error in the console:

[2021-03-20T21:18:37.916Z] Executing 'Functions.GenMetrics' (Reason='This function was programmatically called via the host APIs.', Id=86487f93-0fe2-4622-b38d-1c06d6fd8346)
**[2021-03-20T21:19:32.943Z] Starting worker process failed**
[2021-03-20T21:19:32.944Z] The operation has timed out.
**[2021-03-20T21:20:32.979Z] Starting worker process failed**
[2021-03-20T21:20:32.979Z] The operation has timed out.
**[2021-03-20T21:21:32.985Z] Starting worker process failed**
[2021-03-20T21:21:32.986Z] The operation has timed out.
[2021-03-20T21:21:32.989Z] Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover

Turns out all of this was caused just by having an extra `;` in the using statements like this
`using System.IO;;` which I had put by accident...

👀

**Comment by fabiocav** [comment]
@harisbotic can you please detail your steps? You had a project that failed compilation, correct?

**Comment by harisbotic** [comment]
Just put double ; in any file that is in Az functions project, can be Program.cs or random SomeHelper.cs, and you can recreate the issue.

It compiles and runs normally, but once you trigger a function, it will give the mentioned error. (I used HttpTrigger only)

Its super strange, and I tested it enough times before making this issue. If you can't recreate it I can share the project with you.

P.S I am reporting this for dotnet-isolated runtime

**Comment by oscarvantol** [comment]
Double ; in a using statement _(that is not the last using statement)_ is something that does not compile at all in .NET 5 for me, it will raise a  **CS1529**.

If you would do this (just plain .NET5):
```
using System; ;
using System.Text;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
It will error with: **A using clause must precede all other elements defined in the namespace except extern alias declarations**
I am guessing this is a side effect of cs9's top level statements.

_@harisbotic if your issue is different, can you send me your repro so I can try it here?_

**Comment by fabiocav** [comment]
Indeed. `;;` in those scenarios would be a syntax issue, hence the ask for a proper repro as this may just be a quick answer.

If you're relying on running `func host start` to trigger the build for you, you may be missing instances where the build is failing.

@harisbotic can you please point to your repro? Thanks!

**Comment by harisbotic** [comment]
Core Tools Version:       3.0.3388 Commit hash: fb42a4e0b7fdc85fbd0bcfc8d743ff7d509122ae
Function Runtime Version: 3.0.15371.0
OS: Mac Catalina

FILES:
https://github.com/harisbotic/azfunc-worker-bug

I have put `;;` in SayHello.cs file (and true, it actually has to be on last using statement to compile, which maybe than it doesn't even have to do anything the using statements, but that's just how I found out about this bug in the first place.

HOW TO REPRO:
Just fire a GET request to **`http://localhost:7071/api/SayHello`** and it will fail.

If we would remove one **;** from there, it would work normally.

Just tested it.

**Comment by oscarvantol** [comment]
Thank you, I confirm the behavior with your example.

The extra ```; ``` is generating an extra entry point in the app, but it is not raising an error for that on build time. With sharplab.io you can see it will add this code right after the using statement:

```
[CompilerGenerated]
internal static class <Program>$
{
    private static void <Main>$(string[] args)
    {
    }
}
````

I would think the compiler should warn/error on the extra entry point and this is not so much an AF issue. This can be a serious time waster for devs.

**Comment by fabiocav** [comment]
Suspected this would be the case, but wanted to look at the repro first. Essentially what happens here is that the compiler is going down the path of enabling top level statements and creating the default top level entry point. You should get a compilation warning when this happens (CS7022), so there is some feedback and it would cause a compilation failure in environments where you set warnings to errors, but in a real application, this would also lead to a broken app (none of the logic in your `Main` method would be executed.

I agree that this is not an Azure Functions issue, so I'll close this as there will be no action here. Thanks all for sharing and looking at the details.
