### ISSUE TITLE
Can middleware access/alter what was returned from the function?

### ISSUE THREAD

**Issue by godefroi** [Azure/azure-functions-dotnet-worker#340]
I'm putting together a global exception-handling middleware, and I'd like to be able to alter what will be returned for the output binding. The example middleware only puts data into the `Items` collection; I'm wondering if there's an example anywhere for accessing or manipulating the output binding data?

**Comment by fabiocav** [comment]
@godefroi that's the goal, but some of that information is not yet exposed in the context that flows with the invocation. We have upcoming API reviews to cover items like binding data (which will be accessible in the binding context), function activation and other items are included in that list as well.

**Comment by godefroi** [comment]
Thanks, I appreciate the answer. It's looking good, and while we're clearly not at a final product yet, I like the direction.

**Comment by fabiocav** [comment]
Thank you! We'll definitely be lighting a lot these things up as we go, and feedback like like helps us prioritize what should come first.

**Comment by Jooraz** [comment]
> @godefroi that's the goal, but some of that information is not yet exposed in the context that flows with the invocation. We have upcoming API reviews to cover items like binding data (which will be accessible in the binding context), function activation and other items are included in that list as well.

It's a shame that modification of output was possible in the preview4 and is not in the 1.0.0, I've prepared a code which does that in the preview. And that is rendered completely useless since it's not even a matter or rewriting it, rather than inability to perform such action at all.

Unless there's some kind of way of doing so by any chance after the middleware was called, even via (ugh) reflection? (want to solve this at least for a now) As I was not able to detect one as such.
Ok, well I was able to change the return data object on the HttpTrigger but then I was not able to change StatusCode nor Content-type on the response, which is not good enough for my needs. 
I guess that **complete** change of the output will be possible in the future?

**Comment by josere** [comment]
It will be good if we can also access the input parameters from the middleware.

**Comment by fabiocav** [comment]
@josere that is part of the plan. The goal is to enable scenarios where middleware can inspect and modify input and output data associated with the context.

**Comment by jasonshsoftware** [comment]
+1 on this one! I had the same use case of global error handling, etc.

**Comment by david-peden-q2** [comment]
I was super excited to update to the new out-of-process model simply for the sake of being able to run middlewares. We largely use(d) `FunctionInvocationFilterAttribute` to handle cross-cutting concerns but those appear to be doa. When I started to port our filters to middlewares, I quickly realized it was impossible to do because we don't have access to the `HttpRequestData` (https://github.com/Azure/azure-functions-dotnet-worker/issues/414) nor are we able to short circuit the pipeline and terminate early.

Another use-case I was hoping to convert was the addition of a `/health` endpoint. Currently, we implement this by copying/pasting the same function to each function project:

```csharp
[Function(nameof(Health))]
public async Task<HttpResponseData> Health
(
    [HttpTrigger(AuthorizationLevel.Anonymous, nameof(HttpMethods.Get), Route = "health")]
    HttpRequestData request
)
{
    HttpResponseData response = request.CreateResponse(HttpStatusCode.OK);
    await response.WriteAsJsonAsync(new {DateTime.UtcNow});
    return response;
}
```

This is perfect for a middleware so we can eliminate the code redundancy but, alas, we can't terminate the pipeline.

Please prioritize gaining access to `HttpRequestData` and `HttpResponseData` asap. Middlewares are largely useless without such features.

**Comment by defunky** [comment]
Has there been any movement for this, or is there any workaround for this?

**Comment by lohithgn** [comment]
@defunky there is work around to read the HttpResponseData returned from the Fx in middleware. check this out [https://github.com/Azure/azure-functions-dotnet-worker/issues/414#issuecomment-828810635](https://github.com/Azure/azure-functions-dotnet-worker/issues/414#issuecomment-828810635)

**Comment by defunky** [comment]
@lohithgn that seems to be related to HttpRequestData not HttpResponseData

**Comment by rhollamby** [comment]
> @lohithgn that seems to be related to HttpRequestData not HttpResponseData.
> 
> Edit: although you can do a similar thing and set the InvocationResult via reflection and it seems to work. Thanks for the heads up

Any idea how to do this? I can only see the incoming http headers, not the out going.

**Comment by defunky** [comment]
@rhollamby 
My use-case is a little different as I wanted to modify the response data so in the case of GlobalExceptionHandler I wanted to set the status code to be internal server error. It something like this:

```
// Use reflection to grab HttpRequestData
var keyValuePair = context.Features.SingleOrDefault(f => f.Key.Name == "IFunctionBindingsFeature");
var functionBindingsFeature = keyValuePair.Value;
var type = functionBindingsFeature.GetType();
var inputData = type.GetProperties().Single(p => p.Name == "InputData").GetValue(functionBindingsFeature) as IReadOnlyDictionary<string, object>;
var httpreq = inputData?.Values.SingleOrDefault(o => o is HttpRequestData) as HttpRequestData;

// Create response from the request
var res = httpreq.CreateResponse(HttpStatusCode.InternalServerError);

// Use reflection to set InvocationResult
var result = type.GetProperties().Single(p => p.Name == "InvocationResult");
result.SetValue(functionBindingsFeature, res);
```

You can probably to similar thing but instead of setting InvocationResult you can try retrieving it with reflection if you want to see what the result was.

**Comment by BrandonSchreck** [comment]
It's a bit hacky until these 

> > @lohithgn that seems to be related to HttpRequestData not HttpResponseData.
> > Edit: although you can do a similar thing and set the InvocationResult via reflection and it seems to work. Thanks for the heads up
> 
> Any idea how to do this? I can only see the incoming http headers, not the out going.

https://github.com/Azure/azure-functions-dotnet-worker/issues/530#issuecomment-918473952

**Comment by RomanAlberdaSoftserveInc** [comment]
Is this still in progress >?

**Comment by kshyju** [comment]
Yes, we are currently working on this item. The new APIs to support reading & altering input and output data from middleware will be available in the next few weeks. I will share an update to this thread as we make progress. Thanks!

**Comment by godefroi** [comment]
@kshyju So, your last comment was more than two months ago, do you have a status update?

**Comment by stephanruhland** [comment]
Couldn't you change the HttpResponse with the IFunctionFilters?

e.g. https://github.com/Azure/azure-webjobs-sdk/issues/2546

**Comment by SeanFeldman** [comment]
And, not all funcitons are HttpResponse. So the semantics have to work with triggers other than HTTP.

**Comment by kshyju** [comment]
[Version 1.8.0-preview1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) of `Microsoft.Azure.Functions.Worker` package introduces a few new APIs which can be used to read & update input binding, output binding and invocation result data. Please give it a try and let us know what you think.

````
public static ValueTask<InputBindingData<T>> BindInputAsync<T>(BindingMetadata bindingMetadata);
public static InvocationResult<T> GetInvocationResult<T>();;
public static InvocationResult GetInvocationResult();
public static IEnumerable<OutputBindingData<T>> GetOutputBindings<T>();

// Http trigger specific
public static ValueTask<HttpRequestData?> GetHttpRequestDataAsync();
public static HttpResponseData? GetHttpResponseData();
````

### Usage samples:

1) Global exception handling middleware for http functions. This example uses the API to read HttpRequestData and updating the invocation result.
````
public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
{
    try
    {
        await next(context);
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Error processing invocation");

        var httpReqData = await context.GetHttpRequestDataAsync();

        if (httpReqData != null)
        {
            var newResponse = httpReqData.CreateResponse();
            await newResponse.WriteAsJsonAsync(new { Status = "Failed" });

            // Update invocation result.
             context.GetInvocationResult();.Value = newResponse;
        }
    }
}
````

2) To get input data inside a middleware for a specific input binding entry.

````
BindingMetadata blobBindingMetaData = context.FunctionDefinition
                                             .InputBindings.Values
                                             .Where(a => a.Type == "blob")
                                             .FirstOrDefault();

if (blobBindingMetaData != null)
{
    var bindingResult = await context.BindInputAsync<MyBlob>(blobBindingMetaData);
    // Update a property value. 
    // This will be reflected in the function parameter value.
    bindingResult.Value.Name = "Edited name";
   
   // or you could even replace the entire object
   bindingResult.Value = new MyBlob { Name = "Totally different object" };
}

````

3) Middleware using these APIs to update HttpResponseData. Below sample code stamps an http header to the response.

````
public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
{
    var logger = context.GetLogger<StampHttpHeadersMiddleware>();
    var requestId = "azf-" + Guid.NewGuid();

    using (logger.BeginScope("azfunc-requestid:{requestId}", requestId))
    {
        await next(context);
    }

    var httpRequestData = await context.GetHttpRequestDataAsync();
    if (httpRequestData != null)
    {
        var httpResponseData = context.GetHttpResponseData();
        if (httpResponseData != null)
        {
            httpResponseData.Headers.Add("x-azfunc-requestid", requestId);
        }
    }
}
````

Hope this helps. Let us know if you have any questions.

**Comment by beukerz** [comment]
If I test the first sample I get this response back from the HTTP trigger:

{
    "method": "",
    "query": {},
    "statusCode": "200",
    "headers": {
        "Content-Type": "application/json; charset=utf-8"
    },
    "enableContentNegotiation": false,
    "cookies": [],
    "body": "eyJTdGF0dXMiOiJGYWlsZWQifQ=="
}

The HTTP status code is also 200. Trying to set the status code on the newResponse has only an affect on the body. Not on the status code of the http response.

`public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        var httpReqData = await context.GetHttpRequestDataAsync();
        
        if (httpReqData != null)
        {
            var newResponse = httpReqData.CreateResponse();
            await newResponse.WriteAsJsonAsync(new { Status = "Failed" });
            newResponse.StatusCode = HttpStatusCode.Unauthorized;
            
            // Update invocation result.
            context.GetInvocationResult().Value = newResponse;
            return;
        }`
