### ISSUE TITLE
Custom Binding

### ISSUE THREAD

**Issue by eriklieben** [Azure/azure-functions-dotnet-worker#341]
Hi,

Is there any sample code for how to get a custom binding working?
I tried to get it to work, but I am unable to make it detect my custom binding.

Everything seems to work fine in the dotnet core azure functions, but in the dotnet5isolated project it is not working.
https://github.com/eriklieben/how_azfunc_net5_custom_bindings

Also tried to get it to work with javascript, assuming that would work simular, but can't get my custom binding to work their either so I assume I am doing at least something wrong :-)

Thanks,

Erik

**Comment by fabiocav** [comment]
@eriklieben I took a quick look at the repo you've share and, while you do have the WebJobs extension implementation, you also need to have the binding that will work with the OOP model (that essentially projects the appropriate properties, surface and behaviors for the worker model, including relevant services).

You can see examples of that in the binding implementations here: https://github.com/Azure/azure-functions-dotnet-worker/tree/main/extensions

This is not heavily documented today as it isn't one of the core GA scenarios, but we'll be documenting this flow as we go through API reviews and new releases.
