### ISSUE TITLE
Deployment using github action

### ISSUE THREAD

**Issue by jculverwell** [Azure/azure-functions-dotnet-worker#342]
Hi folks,

I'm trying to deploy my .net 5 function using Github actions and have bumped into an issue.  My Github action is below and also the error I am getting when the github action runs.

The error is 'It was not possible to find any compatible framework version`

If I try and deloy via the tooling `func azure functionapp publish azurefunctionsbrowserextension` it works fine but obviously I'd love to get CI/CD working again.

`  
name: Deploy Function BrowserExtension

on:
  push:
    branches:
      - master
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: myfunctionname
  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './source/azurefunctions.browserextension' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.201' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet clean --configuration Release && dotnet nuget locals all --clear
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BROWSEREXT }}
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples`

Github action log

`
Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.201

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/22/2021 9:38:39 AM.
     1>Project "D:\a\source\azurefunctions.browserextension\azurefunctions.browserextension.csproj" on node 1 (Clean target(s)).
     1>CoreClean:
         Creating directory "obj\Release\net5.0\".
     1>Done Building Project "D:\a\source\azurefunctions.browserextension\azurefunctions.browserextension.csproj" (Clean target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.80
Clearing NuGet HTTP cache: C:\Users\runneradmin\AppData\Local\NuGet\v3-cache
Clearing NuGet global packages folder: C:\Users\runneradmin\.nuget\packages\
Clearing NuGet Temp cache: C:\Users\runneradmin\AppData\Local\Temp\NuGetScratch
Clearing NuGet plugins cache: C:\Users\runneradmin\AppData\Local\NuGet\plugins-cache
Local resources cleared.
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\a\source\azurefunctions.browserextension\azurefunctions.browserextension.csproj (in 1.46 min).
  azurefunctions.browserextension -> D:\a\source\azurefunctions.browserextension\output\azurefunctions.browserextension.dll
  Determining projects to restore...
  Restored C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj (in 13.49 sec).
  WorkerExtensions -> C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.4 at [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App] [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64 [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]

Build FAILED.

C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.4 at [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App] [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64 [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
C:\Users\runneradmin\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [C:\Users\runneradmin\AppData\Local\Temp\rvf51gzl.wwy\WorkerExtensions.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:01:46.85
Error: Process completed with exit code 1.
`

CS Proj

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
    <PackageReference Include="Dapper" Version="2.0.78" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.2" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="5.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.0.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json.bak">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

localsettings.

`
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "FUNCTIONS_EXTENSION_VERSION": "~3",
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  }
}

`

**Comment by fabiocav** [comment]
@jculverwell at the moment, the build environment must also have .NET Core 3.1 installed, that will address the issue you're running into above. Thanks!
