### ISSUE TITLE
How do I know what's the time budget for a function?

### ISSUE THREAD

**Issue by josere** [Azure/azure-functions-dotnet-worker#343]
How do I know when the function is going to timeout? Is there a way to get this value at runtime?

Regards,
Jose.

**Comment by fabiocav** [comment]
@josere for OOP, this is currently based on the timeout you have configured for your function (more information [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout) ).

We're working on host enhancements to support the same experience we have with in-proc, having the ability to pass a cancellation token into the function.
