### ISSUE TITLE
ServiceBusTrigger not auto-completing messages?

### ISSUE THREAD

**Issue by ChrisFulstow** [Azure/azure-functions-dotnet-worker#352]
Hi, I've migrated this Azure Function to .NET 5.0 isolated worker, but having some issues with the `ServiceBusTrigger` binding. The binding to a [Message](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message?view=azure-dotnet) didn't seem supported yet, so I tried binding the message body to a string, and the metadata to a dictionary, and that worked fine.

However, the message doesn't seem to be auto-completing. When the function completes successfully the message isn't deleted from the Service Bus queue. Another option would be to add a binding for `IMessageReceiver`, and complete/abandon the message manually, but not sure that's supported yet (#293).

```csharp
[Function("MyFunction")]
public async Task MyFunction(
    [ServiceBusTrigger(
        queueName: "%MyQueueName%",
        Connection = "MyConnectionString")]
    string message,
    IDictionary<string, object> userProperties,
    string messageId)
{
    // processes the message
}
```

**Comment by SeanFeldman** [comment]
Unfortunately, SDK types such as `Message` and `IMessageReceiver` are not there.

@fabiocav the message should be completed by the SDK or else there's no way to use the trigger, right?

**Comment by fabiocav** [comment]
That's correct. Messages will be completed by the binding itself. 

@ChrisFulstow would you mind sharing your function app name and/or your host.json file? Thanks!

**Comment by ChrisFulstow** [comment]
Thanks @fabiocav not much going on in host.json, not setting `"messageHandlerOptions": { "autoComplete": false }` or anything like that:
```
{
    "version": "2.0"
}
```
Happy to email of DM the function app name, unfortunately can't share here.

Interestingly the auto-complete seems to work if the trigger listens on a topic subscription, but not listening on the queue. The same code was working in-proc .NET Core 3.1, the only thing that's changed in the bindings, before it was binding to a `Message`, and the Service Bus queue is exactly the same.

I'm not sure the expected behaviour when binding the message to a string, would it normally auto-complete like with a `Message`, or need to be completed manually with an `IMessageReceiver`?

**Comment by ChrisFulstow** [comment]
After some more investigating and debugging, good news: there doesn't seem to be any problem with `ServiceBusTrigger` auto-completing messages.

However, we determined the issue was being caused by an injected service that implemented `IAsyncDisposable`. It was blocking the function from ever completing execution, so it probably wasn't able to reach the SDK code that completed the Service Bus message. Removing the `IAsyncDisposable` interface from the service fixed the issue, and auto-completion worked fine.

If the DI container is intended to support `IAsyncDisposable` services then could this be a bug?

**Comment by fabiocav** [comment]
Thank you for the update! This is something we definitely want to look at.

Before I open an issue to track that, can you share more details about what your service was doing in the `DisposeAsync` call?

Thanks!
