### ISSUE TITLE
Debugging the Isolated Host Azure Function in .net5 locally

### ISSUE THREAD

**Issue by WhyDoYouDoThis** [Azure/azure-functions-dotnet-worker#360]
I have a simple Azure Function hosted by the new isolated host written in .net 5.0  I start the function locally from the command prompt _**func start --dotnet-isolated-debug --port 8081 --cors * --verbose**_.  There is no security, the function runs under anonymous authentication.  

Once running, I have attached the debugger through the _attach to process_ option, selected the running PID as stated in the host, and then watch the break point turn from an empty circle to solid red.  All seems good except the break point is never hit.

I have tried adding the **_Debugger.Launch()_** command to the **_Program.Main()_** I have also tried launching the host with the **_--nodeDebugPort 5860_** option.  However nothing seems to trigger the break point.

There is an Exception thrown concerning the gRPC steam - which I have opened a different issue about.  Not sure if that is affecting this as well given I am unsure what information is coming over that stream.

The Project file:
![image](https://user-images.githubusercontent.com/42220748/112516222-0df05680-8d65-11eb-9ac3-5c440ce5f971.png)

The Program.cs:
```csharp
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace this.is.me
{
    class Program
    {
        static void  Main(string[] args)
        {
            Debugger.Launch();
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .Build();

            host.Run();
        }
    }
}
```

The Function:
```csharp
public class RouteMessage
    {
        [Function("RouteMessage")]
        public static async Task<HttpResponseData> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req, FunctionContext executionContext)
        {
            var msgAsString = req.GetMessageBodyAsString();
            var response = HttpResponseData.CreateResponse(req);
            var log = executionContext.GetLogger< RouteMessage>();
            try
            {
                log.LogInformation($"Message {msgAsString} was received and is being routed");

                var routableMsg = msgAsString.GetAs<RoutableMessage>();
                HttpResponseMessage data = default;

                Uri processorUrl = routableMsg.ExtractProcessorEndpoint(req);
                try
                {
                    log.LogInformation(Routing Message {routableMsg.CorrelationId} is being re-routed to {processorUrl}");

                    var client = new HttpClient();
                    if (req.Method == "GET")
                    {
                        log.LogInformation($"Using the GET Method to forward to {processorUrl}");
                        data = await client.GetAsync(processorUrl);
                    }

                    if (req.Method == "POST")
                    {
                        log.LogInformation($"Using the POST Method to forward to {processorUrl}");
                        var content = await req.Body.ReadAllAsStringAsync();
                        data = await client.PostAsync(processorUrl, new StreamContent(req.Body));
                    }
                    await response.WriteStringAsync(await data.Content.ReadAsStringAsync());
                    return response;
                }
                catch (Exception e)
                {
                    var errorMsg = $"Message {routableMsg.CorrelationId} was not processed!\nException:\t{e.ToString()}";
                    log.LogError(e, errorMsg);
                    await response.WriteStringAsync(errorMsg);
                    return response;
                }
            }
            catch (Exception parsingException)
            {
                var errorMsg = $"Failed to extract data from Message:\n\t{msgAsString}";
                log.LogError(parsingException, errorMsg);
                await response.WriteStringAsync(errorMsg);
                response.StatusCode = HttpStatusCode.InternalServerError;
                return response;
            }
        }
    }
```

**Comment by SeanFeldman** [comment]
I have tried it with the latest Functions Core tools and it worked with VS2019 using `Debugger.Launch();`
@WhyDoYouDoThis what IDE are you using?

**Comment by fabiocav** [comment]
@SeanFeldman to clarify, if you're using `Debugger.Launch()`, I'm assuming you're not passing in the `--dotnet-isolated-debug` argument, correct? That argument would (should) prevent your `Debugger.Launch()` code from being hit.

@WhyDoYouDoThis I'm noticing a lot of WebJobs packages still referenced in your project, and while that isn't necessarily an issue for the extensions (thought their attributes wouldn't work there), the `MetadataGenerator` reference is a build time dependency that may impact your worker build, so you should not have that. (`_FunctionsSkipCleanOutput` is also not applicable here)

**Comment by SeanFeldman** [comment]
> if you're using Debugger.Launch(), I'm assuming you're not passing in the --dotnet-isolated-debug argument, correct? That argument would (should) prevent your Debugger.Launch() code from being hit.

Correct @fabiocav. I did not know about the ` --dotnet-isolated-debug` argument until today 😊

**Comment by WhyDoYouDoThis** [comment]
Thanks gents - I am stuck in meetings most of the day, but wanted to at least post back that I am grateful for the feedback and have updated my toolchain ( Visual Studio 2019 Enterprise ).  I will be looking to re-test later this afternoon or over the weekend.  I will post the results along with a celebratory thanks or more questions!

**Comment by WhyDoYouDoThis** [comment]
So update to latest did nothing to help.  Wondering if @SeanFeldman  might post the simple project as a zip file that I can run locally and verify there isn't something off on my machine.

**Comment by WhyDoYouDoThis** [comment]
So after trying everything I could, I decided to simply download the massive sample repo and start trimming things off until I got to a simple HELLO WORLD.  As it is, the code in the sample includes "preview" libraries even though it is built against real bits.  It is perfectly okay to update those libraries to the released version.  Aside from all the configuration, emulation and what not that is required to get that behemoth "Sample" to work, I have paired it down, updated the libraries and built a working, debuggable "Health Check 200 Ok" sample and made it available here to anyone who wants a boilerplate solution to build from.  It is a single project, and only a few nuget packages.

https://drive.google.com/file/d/1-zXQrlxLENAAZ0Fxk0R9s1XCTNxM8p0D/view?usp=sharing

**Comment by Jlopean** [comment]
Ok i got the visual studio 2019 debugging working with azure functions and .net5 framework .. its not great but it will do for now

Note: no preview libraries, all the latest.
Note: I am using service bus triggers
Side Note: got error "No job functions found". fix: rename function declaration from, [FunctionNAME("??")] to,  [Function("??")]

Key debugging points:
- when you press F5 it should start the "Azure Function Core Tool Emulator". (i did install the latest version,)
- there should be no errors, and it should indicate how many triggers it picked up
- The key to debugging is placing `#if DEBUG  Debugger.Launch();  #endif` ; **IN THE METHOD** you are trying to debug
- fyi.. i placed code this in my trigger declaration and i was able to hit breakpoints, and even step into other dlls.


It's not great but it works, just remember to comment the debugger.launch code when you are finished troubleshooting
