### ISSUE TITLE
Support for query and form data in `HttpRequestData`

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-dotnet-worker#362]
It seems that query parameters, form-data (including files), and route parameters are not easily handled.

https://github.com/Azure/azure-functions-dotnet-worker/blob/6556367645aa1e843a41ecde41de38ad95e98fbf/src/DotNetWorker.Core/Http/HttpRequestData.cs

Other languages worker provide these properties so that they are easier to handle go.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#request-object

**Comment by fabiocav** [comment]
@shibayan the full URL (with query strings, segments and all other details) is exposed here: https://github.com/Azure/azure-functions-dotnet-worker/blob/6556367645aa1e843a41ecde41de38ad95e98fbf/src/DotNetWorker.Core/Http/HttpRequestData.cs#L43 (and here is the API Reference documentation: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata?view=azure-dotnet#properties)

All other binding data, which includes route parameters and other trigger provided data, is available in the context, in a way that is consistent across all triggers: https://github.com/Azure/azure-functions-dotnet-worker/blob/6556367645aa1e843a41ecde41de38ad95e98fbf/src/DotNetWorker.Core/Context/FunctionContext.cs#L34 (more details [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.functioncontext.bindingcontext?view=azure-dotnet#Microsoft_Azure_Functions_Worker_FunctionContext_BindingContext) )

Does that provide what you're looking for?

**Comment by shibayan** [comment]
In the current version, it looks like you need to use something like `QueryHelpers.ParseQuery` to parse the query parameters to use them.

In .NET Core 3.1, I could easily get the value from the `Query` property, so that was the part I found most difficult with. Since the `BindingContext` seems to contain the query values in JSON, I think it would help a lot of people if `HttpRequestData` had a `Query` property for short-hand.

For reference, the following is a modified version of the HttpTrigger generated by the .NET Core 3.1 template for .NET 5.

```csharp
[Function(nameof(HttpTrigger1))]
public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req,
    FunctionContext executionContext)
{
    var logger = executionContext.GetLogger<HttpTrigger1>();

    logger.LogInformation("C# HTTP trigger function processed a request.");

    // Use QueryHelpers version
    QueryHelpers.ParseQuery(req.Url.Query).TryGetValue("name", out var name);

    // Use BindingData version
    //var query = JsonSerializer.Deserialize<IDictionary<string, string>>((string)executionContext.BindingContext.BindingData["Query"]);
    //var name = query["name"];

    string responseMessage = string.IsNullOrEmpty(name)
        ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
        : $"Hello, {name}. This HTTP triggered function executed successfully.";

    var response = req.CreateResponse(HttpStatusCode.OK);
    response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

    response.WriteString(responseMessage);

    return response;
}
```

**Comment by fabiocav** [comment]
A few comments:
 - There's no need to install an additional package if you're not using ASP.NET Core just to use `QueryHelpers`, you can instead use `HttpUlitity.ParseQueryString` instead.
 - Query string is also available in expanded form in binding data. If you have a query string named `foo` , there will also be a binding data key named `foo`, with the value set to the query string value. 
 - You only need to work with the Query JSON in binding data if:
   - You don't wan to work with the URI
   - You must work with binding data AND you want to get all queries (as the expanded values don't carry source information).

So, with the current implementation of `HttpRequestData`, your code to retrieve queries as a dictionary would be:

``` csharp
HttpUtility.ParseQueryString(req.Url.Query); // work with the dictionary 
``` 
Or

``` csharp
context.BindingContext.BindingData["myquery"]; // direct access to the dictionary.
```

Expanding the query string in the current HTTP request doesn't come for free. And though we can optimize it or provide additional APIs to handle some of what I've described above, but:
 - Working with `Uri` is very well established in .NET, and its APIs are familiar, well documented and with a healthy number of samples. 
 - Working with the binding data gives you very easy access to that information as well

With all that, I'm inclined to say that, unless we have sufficient evidence that not having this API is causing significant enough pain, we should keep the API as-is.

We can, of course, reevaluate this periodically to see if this would indeed have an impact.

**Comment by shibayan** [comment]
I have some doubts because I consider query strings to be a fundamental element of HTTP, and languages other than .NET 5 Worker (JavaScript / Java / Python) provide easy access to query strings dictionary, but I'll deal with it by implementing my own extension methods for now.
