### ISSUE TITLE
All Exceptions are RPCExceptions in Application Insights

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-dotnet-worker#370]
Semi-Dupe of https://github.com/Azure/azure-functions-powershell-worker/issues/244

The gRPC interface types all exceptions from a worker as RPCException. when an unhandled exception is thrown in the NET5 Worker, when it reaches the logs/Application Insights, its innermost type is RpcException, meaning the exception type got lost in translation on the gRPC interface. This should pass through so that clear exceptions (InvalidOperationException, etc.) can be seen in application insights so issues can be triaged more quickly.

Workaround
Use the telemetry client to throw the "original" exception in a try/catch, this however leads to the dilemma of having "duplicate" exceptions for the failure, or forcing the function to succeed so as to avoid duplication (but then the consequences of that in terms of discovery, queue retry, etc.)

## Simple Example
Made a C# function that throws FileNotFoundException
![image](https://user-images.githubusercontent.com/15258962/112790279-e07d0480-9013-11eb-88ac-7bcb0c602836.png)

![image](https://user-images.githubusercontent.com/15258962/112790346-00142d00-9014-11eb-97fa-79e7881e9fbd.png)

## Potential Remedation
Strip the RPCException wrapper off after it comes from the worker to the host (maybe as a configurable appsetting) before sending to appinsights so it gets classified at the ".NET" level

**Comment by JustinGrote** [comment]
@fabiocav 2 month follow up, can you tell me what discussion is required?

**Comment by eluchsinger** [comment]
Would be nice to have an update here @fabiocav.

**Comment by JustinGrote** [comment]
Now six months without any mention of what discussion is needed @fabiocav.

@anthonychu @jeffhollan maybe you can weigh in?

**Comment by fabiocav** [comment]
Apologies for the delay here. Some additional work is required in the host, as this impacts the OOP layer for every language.

We have, unfortunately, not had the ability to prioritize this work compared to the other work happening in the worker, but we're heading into some additional planning with a number of Worker enhancements.

**Comment by fabiocav** [comment]
@anthonychu flagging this for planning/discussion.

**Comment by JustinGrote** [comment]
@fabiocav appreciate the update!

**Comment by fabiocav** [comment]
@JustinGrote closing this issue as we'll use https://github.com/Azure/azure-functions-host/issues/6284 moving forward to track the progress on this.
