### ISSUE TITLE
Empty body when POSTing data to function using C#'s HttpClient

### ISSUE THREAD

**Issue by rstropek** [Azure/azure-functions-dotnet-worker#374]
I have the following very simple function:

```cs
public static class HandlePost
{
    [Function("HandlePost")]
    public static async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequestData req,
        FunctionContext executionContext)
    {
        using var reader = new StreamReader(req.Body);
        var bodyContent = await reader.ReadToEndAsync();

        System.Console.WriteLine(bodyContent);

        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
        response.WriteString(bodyContent);
        return response;
    }
}
```

I run it using HTTPS with a self-signed certificate that is registered on my dev machine as a trusted root cert. So HTTPS works fine.

I use VSCode's *REST Client* to send a POST request to this function:

```txt
POST https://localhost:7071/api/HandlePost
Content-Type: application/json

"asdf"
```

As a result, the function outputs `"asdf"` and the POST response body contains `"asdf"`. Everything as expected so far.

Next, I write the following very simple C# client:

```cs
using System;
using System.Net.Http;
using System.Net.Http.Json;

using var client = new HttpClient();
var response = await client.PostAsJsonAsync("https://localhost:7071/api/HandlePost", "asdf");
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

To make sure that the client works, I test it by sending the POST request to *requestbin.net*. The POST request is correctly sent. The request body contains `"asdf"` as expected.

**Expected behavior** when running the client against the function: Same behavior as with VSCode's *REST Client*. I should see a console output of the function and receive `"asdf"` in the response body.

**Actual behavior**: `HttpRequestData.Body` is empty in the function. Therefore, no output on the console, no response in the HTTP response body.

Is this an error in the runtime or am I doing something wrong?

**Comment by rstropek** [comment]
Seems to be an issue with `PostAsJsonAsync`. The following client code works as expected:

```cs
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;

using var client = new HttpClient();
var request = new HttpRequestMessage()
{
    Method = HttpMethod.Post,
    RequestUri = new Uri("https://localhost:7071/api/HandlePost")
};
request.Content = new StringContent("\"asdf\"", Encoding.UTF8, "application/json");
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

**Comment by waynedavisactivu** [comment]
I was having the same issue you were until I changed the following:

-Before: 
```csharp
var response = await client.PostAsync("api/wh/link", JsonContent.Create(request));

///Azure Function HttpRequestData.Body is null
///Azure Function is using .Net 5.0
```

-After: 
```csharp
var content = new StringContent(JsonSerializer.Serialize(request), Encoding.UTF8, "application/json");
var response = await client.PostAsync("api/wh/link", content);

///Azure Function HttpRequestData.Body contains data
///Azure Function is using .Net 5.0
```

**Comment by christianarg** [comment]
I'm having the exact same problem with PatchAsync

Aspnet5 Web application executes:

`httpClient.PatchAsync("",JsonContent.Create(data)`

On the Net5 function I recieve a NullStream in the HttpRequestData.Body property

using @waynedavisactivu workarround works correctly

**Comment by markolbert** [comment]
I'm running into the same problem. From looking at the source code it seems like the media type is not being specified when JsonContent.Create() is called.

**Comment by jihadkhawaja** [comment]
Same here, using .NET 6 minimal API, It works on postman when using params query but not with Json raw body.

![image](https://user-images.githubusercontent.com/47315122/172631641-5cc41dfe-6c0b-4988-be6c-0b0b49c7fe47.png)
![image](https://user-images.githubusercontent.com/47315122/172631881-3037b2fe-786d-4e88-8dd3-6bed76eb9e51.png)

Client side:
![image](https://user-images.githubusercontent.com/47315122/172632149-60146094-3e28-488f-b18a-fc6358c0ff9e.png)

tried to use HttpClient PostAsync instead of PostAsJsonAsync still no luck.

**Comment by VBobCat** [comment]
I have the same problem and I don't want to believe it's not fixed yet.

**Comment by savagemonitor** [comment]
I hit this issue as well in .NET Core code but not in PowerShell Core when using Invoke-RestMethod.

**Comment by kshyju** [comment]
Closing as answered by @rstropek with the updated client code. Please open a new issue if you run into issues.
