### ISSUE TITLE
Azure Static Web Apps support?

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#380]
Azure static websites are still in preview but they say that they use the azure functions back end, are .net isolated processes supported today? If not when will they be supported?

**Comment by godefroi** [comment]
Not a contributor, but to clarify; when you say "supported", what do you mean? Are you asking if you can call an Azure function from a static website? If so, the answer is definitely "yes".

**Comment by onionhammer** [comment]
I'm asking about the built in API functionality, not about calling a different api from your client

**Comment by anthonychu** [comment]
Thanks for the feedback. This issue is being tracked here https://github.com/Azure/static-web-apps/issues/319. It's on the roadmap to support additional language version. There's no ETA yet. Closing this one but please follow the other one for updates.
