### ISSUE TITLE
Dead letter queue

### ISSUE THREAD

**Issue by nichovski** [Azure/azure-functions-dotnet-worker#381]
Hello,

How I can send a message to dead letter Queue in .NET 5 (dotnet-isolated), I'm not able to inject MessageRecevier and call messageRecevier .DeadLetterAsync()?

Thanks

**Comment by SeanFeldman** [comment]
The worker SDK is de-coupled from other SDK types. The `MessageReceiver` used to receive the triggering message is not passed in as an object but rather as a serialized JSON string. I don't think with the current release it's possible to dead-letter the incoming message. @fabiocav would be able to confirm and elaborate on the future direction.

**Comment by SeanFeldman** [comment]
A potential solution is similar to what was proposed in https://github.com/Azure/azure-functions-dotnet-worker/issues/293 - dead-letter the message using a newly constructed `MessageReceiver`, passing the `LockToken` of the incoming message.

**Comment by fabiocav** [comment]
Flagging this as answered as the information shared by @SeanFeldman above should help, but please let us know if you need anything else.
