### ISSUE TITLE
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.

### ISSUE THREAD

**Issue by JamieMagee** [Azure/azure-functions-dotnet-worker#383]
When running [this function](https://github.com/JamieMagee/reddit2kindle/tree/v2/src/Reddit2Kindle.Functions) on a Linux-based Azure Functions App (running in West US 2), I receive the following error:

```
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - No frameworks were found.
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=debian.10-x64
Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Ho
```

If you need additional information you can also reach me on Teams.

**Comment by imaji** [comment]
I've hit a very similar issue, but mine ends up with a time out.

I moved exactly the same deployment to a Windows function, and it worked absolutely fine. Moved it back to a Linux function, and Bomb! Can't find Microsoft.AspNetCore.App version 5.0.0.

Looks like something screwy is going on with the Linux hosts at the moment.

**Comment by eugene-cp** [comment]
I have the same issue and it seems like during build/publish the runtimeconfig.json generate this

```
{
"runtimeOptions": {
  "tfm": "net5.0",
  "framework": {
    "name": "Microsoft.AspNetCore.App",
    "version": "5.0.0"
   }
  }
}
```

the templates/samples when built have the name value as Microsoft.NETCore.App.  

when i add references to some packages like: 
PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.5"
PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.2.1"

then the generated runtimeconfig.json is similar to the one above.

**Comment by fabiocav** [comment]
@JamieMagee apologies for the delayed response here, this issue was, unfortunately, opened before the bot was properly configured and slipped through our triage process.

Can you confirm you're still experiencing the same issue?

**Comment by JamieMagee** [comment]
No worries, this is for a personal project. I ended up deploying to a Windows-based Azure function. I'll give it a go later and see if it works now.

**Comment by eugene-cp** [comment]
@fabiocav was this resolved already?  Same as @JamieMagee I ended up deploying to Function App for Windows which also required me to create a new resource group.

I can test deploying the same functions on Linux if this has been address.

**Comment by brettsam** [comment]
There may be an issue here with the Linux images we're using -- we will investigate and follow-up on this.

**Comment by agutierrezcu** [comment]
My team is facing exactly the same error. 

Our application depends on 

```
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.7" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.Core" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="5.0.7" />
```

We are starting the development phase and we decided to deploy on based-Windows Function app for the moment.

We really looking forward to be able making the application runs on Linux so, if you need any detailed insight please let me know.

**Comment by agutierrezcu** [comment]
Hi @brettsam, any update on this?🙏 
Thanks in advanced!

**Comment by eugene-cp** [comment]
Hi @brettsam , @fabiocav ,

I just tried it again just now and this still is not resolved, a little bit frustrating.

**Comment by brettsam** [comment]
@eugene-cp -- thanks! Do any of the other projects you reference have that `<FrameworkReference>`?

**Comment by sanjaydebnath** [comment]
Same problem here on AKS hosted function (linux) but with 'Microsoft.AspNetCore.App', version '6.0.0'. I dont have any reference to <FrameworkReference> but I do have dependencies on a few nugets related to asp.net.

```
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.0" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.6.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />
    <PackageReference Include="Polly" Version="7.2.2" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.EventGrid" Version="3.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="3.0.9" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
  </ItemGroup>
```

**Comment by kshyju** [comment]
@JamieMagee Are you still experiencing this issue? I believe this should be fixed by now.
