### ISSUE TITLE
HttpRequestData probably should not validate headers

### ISSUE THREAD

**Issue by DavidZidar** [Azure/azure-functions-dotnet-worker#386]
I have a HTTP trigger which reads request headers and sometimes it throws an exception like this one:

```
 System.FormatException: The format of value 'AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN' is invalid.
   at object System.Net.Http.Headers.HttpHeaderParser.ParseValue(string value, object storeValue, ref int index)
   at void System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, string value)
   at new Microsoft.Azure.Functions.Worker.Http.HttpHeadersCollection(IEnumerable<KeyValuePair<string, string>> headers) in D:/a/1/s/src/DotNetWorker.Core/Http/HttpHeadersCollection.cs:line 41
   at HttpHeadersCollection Microsoft.Azure.Functions.Worker.GrpcHttpRequestData.get_Headers() in D:/a/1/s/src/DotNetWorker.Grpc/Http/GrpcHttpRequestData.cs:line 67
```

In this case a bot is sending a user agent which the header validation does not like and thus I am completely prevented from reading the headers because merely accessing the `Headers` property causes this exception to be thrown.

The problem seems to be that you call `Add` on `HttpHeaders` here:
https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Core/Http/HttpHeadersCollection.cs#L39-L45

Maybe you should be calling `TryAddWithoutValidation` instead when dealing with request headers?

I have tried making similar requests to a ASP.NET Core site and can read headers just fine even with the user agent above.

**Comment by fabiocav** [comment]
Sounds reasonable. Tracking that as part of the work for the current sprint.

**Comment by chtay1** [comment]
I think this may apply to the "From" header, Google and Bing for instance like to send "googlebot(at)googlebot.com" and "bingbot(at)microsoft.com" in the the "From" header which as soon as you try to access the Headers collection fails. 

I thought I might be able to strip out the "From" header with middleware but you can't override details of the BindingContext.BindingData as it's a IReadOnlyDictionary.

**Comment by liamehenderson** [comment]
We also are seeing this issue when duplicate headers are sent through. With something like duplicate Content-Type headers getting set to "application/json, application/json" we would normally handle this and return a HttpResponseData object with a duplicate header error message but cannot generate a HttpResponseData object due to the parent HttpRequestData object being invalid.

**Comment by ak37165** [comment]
+1. Calling from a browser such as Edge or Chrome on localhost causes this exception too.

**Comment by DavidZidar** [comment]
@fabiocav Any update on this?

**Comment by fabiocav** [comment]
@DavidZidar validating some of this work, PR should be in soon, aiming  to have it done as part of the current sprint for a release in approximately 2 weeks

**Comment by fabiocav** [comment]
Updated the sprint to reflect that

**Comment by DavidZidar** [comment]
@fabiocav Excellent, thanks for the update!

**Comment by chtay1** [comment]
> Argh! I've just hit this after updating a Function App to .NET 5 in `dotnet-isolated` mode, with a Docker Registry instance calling my function app:
> 
> ```cs
>  ---> System.FormatException: The format of value 'UpstreamClient(Docker-Client/20.10.6 \(linux\))' is invalid.
>    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
>    at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
>    at Microsoft.Azure.Functions.Worker.Http.HttpHeadersCollection..ctor(IEnumerable`1 headers) in D:\a\1\s\src\DotNetWorker.Core\Http\HttpHeadersCollection.cs:line 41
>    at Microsoft.Azure.Functions.Worker.GrpcHttpRequestData.get_Headers() in D:\a\1\s\src\DotNetWorker.Grpc\Http\GrpcHttpRequestData.cs:line 67
> ```
> 
> All I want to do it read the `Authorization` header, but `TryGetValues` or even just enumerating the header values, results in that exception above. I obviously cannot control the `User-Agent` header that the official Docker Registry image sends - is there some workaround that would allow me to simply _read the header values_ without `HttpHeadersCollection.cs` throwing?! 😠

I

> Argh! I've just hit this after updating a Function App to .NET 5 in `dotnet-isolated` mode, with a Docker Registry instance calling my function app:
> 
> ```cs
>  ---> System.FormatException: The format of value 'UpstreamClient(Docker-Client/20.10.6 \(linux\))' is invalid.
>    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
>    at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
>    at Microsoft.Azure.Functions.Worker.Http.HttpHeadersCollection..ctor(IEnumerable`1 headers) in D:\a\1\s\src\DotNetWorker.Core\Http\HttpHeadersCollection.cs:line 41
>    at Microsoft.Azure.Functions.Worker.GrpcHttpRequestData.get_Headers() in D:\a\1\s\src\DotNetWorker.Grpc\Http\GrpcHttpRequestData.cs:line 67
> ```
> 
> All I want to do it read the `Authorization` header, but `TryGetValues` or even just enumerating the header values, results in that exception above. I obviously cannot control the `User-Agent` header that the official Docker Registry image sends - is there some workaround that would allow me to simply _read the header values_ without `HttpHeadersCollection.cs` throwing?! 😠

In the short term I got around the issue by using middleware and deserializing the headers from the binding context binding data and passing  what I need back via the function context items.

**Comment by cocowalla** [comment]
@chtay1 thank you, that worked! 👏

**Comment by DavidZidar** [comment]
@fabiocav Any update on when a new version will be released with this bug fix?
