### ISSUE TITLE
ServiceBusTrigger with Topics/Subscription throws 404

### ISSUE THREAD

**Issue by ModernRonin** [Azure/azure-functions-dotnet-worker#388]
Hi,

I have a trigger function defined as
```csharp
 [Function("OnBusNotification")]
 public Task OnTriggerAsync([ServiceBusTrigger("sharedcontracts~somenotification", "my-subscription")] 
                            byte[] rawMessage, FunctionContext context)
{
   // ...
}
```

In the Azure portal, I got the topic and subscription set up as `deonmark/sharedcontracts~somenotification/my-subscription`.

I've sent a message to the topic with a test-client. If I peek at the message using [ServiceBusExplorer](https://github.com/paolosalvatori/ServiceBusExplorer), I see this:
```json
{
  "messageId": "72760000-6422-d45d-0a60-08d8fc18f272",
  "conversationId": "72760000-6422-d45d-dc1a-08d8fc18f273",
  "sourceAddress": "sb://deonmark.servicebus.windows.net/VARIANT13_TestClient_bus_qj5yyydrrmkf586ibdcxag8cd4?autodelete=300",
  "destinationAddress": "sb://deonmark.servicebus.windows.net/SharedContracts/SomeNotification",
  "messageType": [
    "urn:message:SharedContracts:SomeNotification"
  ],
  "message": {
    "info": "zulu"
  },
  "sentTime": "2021-04-10T12:05:34.9899872Z",
  "headers": {},
  "host": {
    "machineName": "VARIANT13",
    "processName": "TestClient",
    "processId": 7108,
    "assembly": "TestClient",
    "assemblyVersion": "1.0.0.0",
    "frameworkVersion": "5.0.5",
    "massTransitVersion": "7.1.7.0",
    "operatingSystemVersion": "Microsoft Windows NT 10.0.19042.0"
  }
}
```

Note that  `destinationAddress` is `sb://deonmark.servicebus.windows.net/SharedContracts/SomeNotification`.

Now when I start the function app with 
```shell
func start --dotnet-isolated-debug
```

I never even break into my function, but get the following error messages:
```
Message processing error 
(
  Action=Receive, 
  ClientId=MessageReceiver1sharedcontracts~somenotification/Subscriptions/my-subscription, 
  EntityPath=sharedcontracts~somenotification/Subscriptions/my-subscription,
  Endpoint=deonmark.servicebus.windows.net
)

Microsoft.Azure.ServiceBus: Put token failed. status-code: 404, status-description: The messaging entity 
'sb://deonmark.servicebus.windows.net/sharedcontracts~somenotification/Subscriptions/my-subscription' could not be found. 
To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:8b0bad71-6d4d-45e3-b86e-dec50c0da7b7_G28, SystemTracker:deonmark.servicebus.windows.net:sharedcontracts~somenotification/Subscriptions/my-subscription, Timestamp:2021-04-10T12:23:45.
```

Any idea why this is happening? 

The one thing catching my eye is that the error message talks about
`sb://deonmark.servicebus.windows.net/sharedcontracts~somenotification/Subscriptions/my-subscription` 
while the address in the Azure portal doesn't have the `Subscriptions` between the topic and the subscription name, neither does the `destinationAddress` field shown in ServiceBusExplorer.

Am I doing something wrong? Or is this a bug in the SDK?

Many thanks,
MR

**Comment by CasperWSchmidt** [comment]
I think you should change "~" to "/" in your topic name?

**Comment by ModernRonin** [comment]
Before switching to net5, the tilde was what it wanted.

Anyway, to be on the safe side, I just tried replacing it with a slash, but the error message stays the same.

**Comment by CasperWSchmidt** [comment]
Then I don't know. We use `/` as a delimiter in topic names and it works just fine, except for the Azure Portal, which has a warning in the top of the page saying that `/` can't be displayed so it's using `~` instead.

**Comment by ModernRonin** [comment]
And you are running on net5 and your code looks like mine, except for the tilde vs slash question?
If yes, would you mind trying to replace the slash with a tilde on your system and seeing whether this has any impact?

**Comment by CasperWSchmidt** [comment]
No we're running netcoreapp3.1

**Comment by ankitkumarr** [comment]
@ModernRonin, I apologize for the delay here. I was able to reproduce this using `~`. The error comes from Azure Service Bus itself.

But when I changed my function definition to something like `sharedcontracts/somenotification`, it seemed to work fine for me. Please note that, I put `/` only in my `ServiceBusTrigger` definition. The topic in Service Bus still has `~`, something like `sharedcontracts~somenotification`.

Does changing it to `/` in your function definition not work for you?

**Comment by ModernRonin** [comment]
I was trying to check this, but for some reason my storage emulator doesn't want to start anymore, it hangs. This wouldn't be a problem, I can just run Azurite, but even if Azurite is running, when trying to start the function from within VS, VS tries to start the emulator - is there any way I can disable that and make it use Azurite (which is running on the same ports as the emulator)?

**Comment by ModernRonin** [comment]
however, I can say that at least on April 15th, the following did not work:
```csharp
const string QueueName = "sharedcontracts/somenotification";
/// ...
[Function("OnBusNotification")]
public Task OnTriggerAsync([ServiceBusTrigger(QueueName, "my-subscription")] byte[] rawMessage,  FunctionContext context)
```

**Comment by fabiocav** [comment]
If you can validate and share any exceptions you see if the error persists, we'll take a closer look.

When running with Azurite, are you updating the connection string defined in `local.settings.json` to point to that?
