### ISSUE TITLE
Access UserProperties on ServiceBusTrigger when IsBatched is true

### ISSUE THREAD

**Issue by tommymonk** [Azure/azure-functions-dotnet-worker#390]
I'm using the `ServiceBusTrigger` on a function with Azure Functions 5, I've therefor had to use a string due to the binding limitations and my binding looks like this;

`public async Task RunAsync([ServiceBusTrigger(SERVICE_BUS_QUEUE_NAME, Connection = "ServiceBusConnectionString")] string message, IDictionary<string, object> userProperties)`

I want to take advantage of batching so I also pass `IsBatched = true` and changed `string message` to `string[] messages` but I'm unsure from reading source code how I'm meant to get the userProperties for each of the messages ?

**Comment by ankitkumarr** [comment]
@tommymonk, I apologize for the delay here.

You should be able to access all metadata including userProperties using `FunctionContext.BindingData` such as --
```csharp
public static void Run([ServiceBusTrigger("<topic>", "<sub>", IsBatched = true)] string[] mySbMsg, FunctionContext context)
{
    string userPropertiesArraySerialized = context.BindingContext.BindingData["userPropertiesArray"];
}
```
Note that, at the moment, it will be a serialized string of array with all the properties.

Please let us know if this solves your issue. Thanks!

**Comment by tommymonk** [comment]
@ankitkumarr your proposal seems to work, strange though that I seem to get drips and drabs, infrequent batches with less than 5 items usually event though there are plenty in the queue and `MaxMessageCount` is set to `1000`
