### ISSUE TITLE
Exceptions do not cause a requeue of a message to a QueueTrigger

### ISSUE THREAD

**Issue by alanokelly** [Azure/azure-functions-dotnet-worker#391]
My .NET 5 (dotnet-isolated) QueueTrigger function does not requeue a message when the function ends in an exception. It doesn't go to a poison queue, it just disappears

here's my host file: 
```
{
  "version": "2.0",
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "visibilityTimeout": "00:00:10",
      "maxDequeueCount": 5
    }
  },
  "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 5,
    "delayInterval": "00:00:05"
  },
  "logging": {
    "logLevel": {
      "default": "Information"
    }
  }
}
```
Here's my function lead-in

```
        [Function("DispatchProcessor")]
        public async void Run([QueueTrigger("%AppSettings:ProcessingMessageQueueName%", Connection = "AzureWebJobsStorage")] string myQueueItem)
        { 
```

**Comment by alanokelly** [comment]
This worked great on .NET Core 3.1. Not sure why it's not working after the upgrade

**Comment by fabiocav** [comment]
@alanokelly queues have built-in retries and don't require the retry configuration (which is currently in preview). Do you have the same issue if you remove that?

**Comment by fabiocav** [comment]
@alanokelly could you please look at the question above? Thanks!
