### ISSUE TITLE
TimerInfo is missing because you haven't released a new version of the Timer NuGet package

### ISSUE THREAD

**Issue by DavidZidar** [Azure/azure-functions-dotnet-worker#392]
Your release notes for version 1.1 mention the following:

> Added TimerInfo definition allowing for binding information with a built-in type

Which is great! But the `TimerInfo` definition is supposed to live in the `Microsoft.Azure.Functions.Worker.Extensions.Timer` NuGet package which needs to be updated.

**Comment by fabiocav** [comment]
Yes, yes :)

We're in the process of releasing that and will be live soon. Apologies. We'll close the issue as soon as the package is live.

**Comment by DavidZidar** [comment]
I'm closing this because the package has finally been updated, thanks.

**Comment by fabiocav** [comment]
Indeed. Actually had an item to follow up on this issue, but you've beat me to it :)

**Comment by DavidZidar** [comment]
I guess I like cleaning up after myself, haha. Thanks again!
