### ISSUE TITLE
Docker image updates

### ISSUE THREAD

**Issue by brazierdavid** [Azure/azure-functions-dotnet-worker#394]
Hi, the images at [https://hub.docker.com/_/microsoft-azure-functions-dotnet-isolated](https://hub.docker.com/_/microsoft-azure-functions-dotnet-isolated) aren't updated nightly with Linux patches like the standard .NET ones at [https://hub.docker.com/_/microsoft-dotnet-aspnet](https://hub.docker.com/_/microsoft-dotnet-aspnet) are, and Azure Security Center is complaining our function app image has vulnerabilities - what's the plan for this long term, should we expect these to be updated more regularly, or should we base our image on the standard .NET ones and build the functions worker on top of that?

**Comment by fabiocav** [comment]
@ahmelsayed have you seen similar requests for our images before? What's the approach? Do we have any plans for something like this?

**Comment by balag0** [comment]
We build and release new functions images every N weeks as part of regular deployment cadence. At that time latest sources would be pulled along with any security fixes available as part of the latest versions. For critical high impact issues impacting Functions scenarios we can do out of band deployments.
We don't have any additional mechanism to incorporate updates to upstream sources more frequently than that.

This is case with other AppService images as well.

**Comment by fabiocav** [comment]
@brazierdavid does the answer help? Might not be ideal, but I hope at least the guidance/information is helpful.

**Comment by brazierdavid** [comment]
> @brazierdavid does the answer help? Might not be ideal, but I hope at least the guidance/information is helpful.

Yes it's useful info thanks.
