### ISSUE TITLE
".NET5 Azure Function" + Azure Key Value = "Visual Studio Connected Services"

### ISSUE THREAD

**Issue by p-bojkowski** [Azure/azure-functions-dotnet-worker#396]
Hi!

when you create the new .NET5 function (https://dev.to/kenakamu/azure-functions-and-net-5-dependency-injection-5ed4)
you can than add "Visual Studio Connected Services" with VS 16.10.0 Preview 1.0.

How can we use .NET5 Azure Function isolated with Azure Key Value?
What is the current best practices to use Azure Key Value in .NET5 Azure Function isolated mode?

**Comment by fabiocav** [comment]
@p-bojkowski are you referring to Azure Key Vault? If so, you have a couple of options, number 1 is to directly use the Key Vault SDK as you would from other .NET apps,  number 2 is to use the Key Vault references support in app service (https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references)

**Comment by p-bojkowski** [comment]
thx @fabiocav

**Comment by v-anvari** [comment]
Closing issue as resolved
