### ISSUE TITLE
Debug NET5 Azure Function with dotnet-isolated should be attached automatically

### ISSUE THREAD

**Issue by renatoeufe** [Azure/azure-functions-dotnet-worker#397]
Actually, in order to make the break points work (while debugging) we have two options:

1. Add a new line `#if DEBUG Debugger.Launch(); #endif` inside every function;
2. Attach the debugger to the spawned worker process manually.

I would like to suggest a small change:
To make the debugger automatically attached to the spawned worker process when we hit F5.

![image](https://user-images.githubusercontent.com/1012457/115097969-b2e4f600-9f03-11eb-9c6f-fb7f1b91455d.png)

--
Microsoft Visual Studio Community 2019 16.9.4
FUNCTIONS_WORKER_RUNTIME = dotnet-isolated
func 3.0.3442

**Comment by fabiocav** [comment]
Thanks! this is tracked and mostly implemented at this point. This will be available with VS release 16.10

**Comment by WinInsider** [comment]
@fabiocav running on VS 16.10... in the project I have number of timer functions; is there a way to tell Visual Studio, that when debugging (F5), which timer function I want to debug, and for VS to trigger that timer function imminently? .. and to ignore other functions (not trigger them)

**Comment by distantcam** [comment]
@WinInsider There's currently a bug that causes debugging to fail if a timer function tries to start before the debugger is attached to the process. 

https://github.com/Azure/azure-functions-dotnet-worker/issues/471

Once the debugger is attached you can manually trigger timer functions using a HTTP call.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http
