### ISSUE TITLE
Add pipeline examples to documentation

### ISSUE THREAD

**Issue by ErikApption** [Azure/azure-functions-dotnet-worker#401]
From the current documentation, the deployment process depends on installing the function tools which doesn't seem to be too pipeline friendly. Also it looks like to deploy the function, we would need scripts and cannot rely on the pipeline function tools. Any chances you can provide guidance/clarification on deploying a .net 5 function to azure using a devops pipeline?

**Comment by ErikApption** [comment]
So using the standard .net core function deployment, we were able to deploy a function that is using this new worker. No change was required. However, you have to use the command line to create the function app otherwise it will not be using the right runtime and it looks like existing functions cannot be converted.

**Comment by brettsam** [comment]
Sorry for the slow response @ErikApption -- are you referring to a DevOps pipeline? Would you mind sharing what you ended up using that worked? 

I agree that we should get some pipeline documentation for this.

**Comment by mattchenderson** [comment]
Closing old issue that it sounds like was resolved. Documentation should have the right coverage for deployment options, but if there's still something missing, we can reopen / create a new issue.
