### ISSUE TITLE
[BlobOutput] always sets Content Type to "application/octet-stream"

### ISSUE THREAD

**Issue by sahgilbert** [Azure/azure-functions-dotnet-worker#402]
When using a BlobTrigger function which takes an input parameter of byte[] and simply returns it via a BlobOutput, the Content Type on the Block Blob in Azure Storage is always set to application/octet-stream (please see attached image).

Is there a way to set the Content Type by amending the properties, so to preserve the original image type?

Currently when trying to access the url of the newly copied blob, it is simply downloaded instead of being displayed in the browser.

### Tech Stack:
- Visual Studio for Mac 8.9.6 (build 6)
- .Net 5.0
- Core Tools Version: 3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
- Function Runtime Version: 3.0.15417.0

### Example Code:
```
    public static class BlobTriggerFunction
    {
        [Function("BlobTriggerFunction")]
        [BlobOutput(
            "exampleimages/resized_{name}",
            Connection = "AzureWebJobsStorage")]
        public static byte[] Run(
            [BlobTrigger(
            "exampleimages/{name}",
            Connection = "AzureWebJobsStorage")]
            byte[] inputBlobByteArray,
            string name,
            FunctionContext functionContext)
        {
            var logger = functionContext.GetLogger("BlobTriggerFunction");

            logger.LogInformation($"BlobTriggerFunction Processed blob \n Name: {name} \n Size: {inputBlobByteArray.Length} Bytes");

            // Return the input byte[] without amending it.
            return inputBlobByteArray;
        }
    }
```

### Result:
<img width="936" alt="Screenshot 2021-04-20 at 16 42 31" src="https://user-images.githubusercontent.com/13452745/115426831-cc828800-a1f8-11eb-8f20-09db9ceea412.png">

**Comment by ankitkumarr** [comment]
Unfortunately, I don't think this is supported in the out of proc ([differences in the model](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions)) right now.

The Blob extension in this model doesn't allow modifying such properties. The request is for making this available over all languages is tracked here -- https://github.com/Azure/azure-functions-host/issues/364

cc: @fabiocav
