### ISSUE TITLE
Missing Table Binding

### ISSUE THREAD

**Issue by asparrowhawk** [Azure/azure-functions-dotnet-worker#404]
There doesn't seem to be a way to bind to a table. Previously there was the TableAttribute in the Microsoft.Azure.WebJobs.Extensions.Storage assembly that allowed direct access to an Azure Table.

Is there another way to achieve this? When using the TableInputAttribute in the following way

```
[Function("Bands")]
 public async Task<HttpResponseData> Execute(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req,
            [TableInput("Requests", Connection = "AzureWebJobsStorage")] CloudTable table,
            FunctionContext executionContext)
        {
            var tableEntity = new PayloadTableEntity(req.ReadAsString());

            await table.ExecuteAsync(TableOperation.InsertOrMerge(tableEntity));
...
        }
```

This exception is thrown:

```
System.Private.CoreLib: Exception while executing function: Functions.Bands. System.Private.CoreLib: Result: 
Failure
Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters 
for Function 'Bands': Cannot convert input parameter 'table' to type 'Microsoft.Azure.Cosmos.Table.CloudTable' from type 'System.String'.
[2021-04-21T07:11:43.727Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
[2021-04-21T07:11:43.729Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-04-21T07:11:43.731Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-04-21T07:11:43.733Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in 
D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
[2021-04-21T07:11:43.736Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-04-21T07:11:43.737Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-04-21T07:11:43.740Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
```

**Comment by oscarvantol** [comment]
Hi @asparrowhawk, you tried using [TableInput] but [TableOutput] might help you in this scenario. The following example shows how this would work, it has multi output so it is a bit bloated.

Another option if you would need to directly interact with the table, would be to use DI to inject some helper in your functions class.

```
    public class TableFunction
    {
        [Function(nameof(HttpToTableFunction))]
        public async Task<MyOutput> HttpToTableFunction([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test-table-output")] HttpRequestData req)
        {
            var tableEntity = new MyTableData { PartitionKey = "test-table-output", RowKey = Guid.NewGuid().ToString(), Text = "some text" };

            var httpResponse = req.CreateResponse();
            await httpResponse.WriteStringAsync("Success");

            return new() { HttpResponse = httpResponse, MyTableData = tableEntity };
        }

        public class MyOutput
        {
            public HttpResponseData? HttpResponse { get; set; }

            [TableOutput("TestTable", Connection = "AzureWebJobsStorage")]
            public MyTableData? MyTableData { get; set; }
        }

        public class MyTableData
        {
            public string? PartitionKey { get; set; }
            public string? RowKey { get; set; }
            public string? Text { get; set; }
        }
    }

//from: https://github.com/oscarvantol/azure-functions-dotnet5-examples/blob/main/ExampleFunction/TableFunction.cs
```

**Comment by asparrowhawk** [comment]
@oscarvantol Many thanks for the response. That was very useful with my scenario. Lets hope the documentation for these bindings improves.

**Comment by brettsam** [comment]
`[TableInput]` is supported -- but you cannot use `CloudTable` as an parameter type. Language workers are not able to use "rich SDK types" like the in-proc .NET model was able to. We're looking to improve this in the future.

I believe that when you specify the table name only, the binding will retrieve the entire table and return it to you in this parameter (so you could use an array as your input here).

We need docs and analyzers to help with this -- it's not entirely clear what's supported just by using the attribute itself.

**Comment by aistvan** [comment]
What is the way if I would like to manipulate the binded output (or input) CloudTable's data?
Currently I got "row exist" exception if I want to "owerwrite" a row's value.
I couldn't find any example how can I remove the old one or update an existing one.

**Comment by twentytwokhz** [comment]
@brettsam Can we control what kind of operation is performed when sending the data to the output?
Such as InsertOrMerge, InsertOrReplace etc

**Comment by MarGraz** [comment]
@brettsam Same problem here. 

I'm using the ".NET 5 isolated functions", "Azure Functions Core Tools v. 3", and `Microsoft.Azure.Functions.Worker.Extensions.Storage` v. 4.0.4. I have added the `ETag` column and I have set it to `*`, but I can't update the Table Storage row, I get the error:

```
System.Private.CoreLib: Exception while executing function: Functions.AddCustomer.
Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. 
Microsoft.Azure.WebJobs.Extensions.Storage: 0: The specified entity already exists.
Time:2021-09-29T17:40:46.9093149Z (HTTP status code 409: EntityAlreadyExists. 0:The specified entity already exists.
```

Can we update or delete row using function bindings?

**Comment by cleferman** [comment]
Following up on this the Table attributes are missing from `Microsoft.Azure.Functions.Worker.Extensions.Storage` version `5.0.0-beta.4`. Are there plans to add them back? And will they make use of managed identity auth?
Meanwhile I believe I can use `TableServiceClient` from  `Azure.Data.Tables`.

**Comment by longtimedeveloper** [comment]
@asparrowhawk @MarGraz @cleferman I wrote up a bug to get this fixed.  https://github.com/Azure/azure-sdk-for-net/issues/25694  

This is nuts with an unannounced, unplanned massive breaking change.  Really frustrating with non-sense like this.

I just tried the `Microsoft.Azure.Functions.Worker.Extensions.Storage` stable version `5.0.0` and it's gone.

**Comment by vincentbitter** [comment]
Is there any possibility TableOutput and TableInput are going to be supported again in the future? If not, we have to change all our functions like @longtimedeveloper proposed.  

Why was it even dropped? The whole idea of Functions is to only focus on business logic and outsource the data retrieval/storage stuff as much as possible, right?

**Comment by stap123** [comment]
@brettsam Is there anywhere that the removal of these attributes was announced with reasons why? 

I can't find anything anywhere warning of the removal or release notes for the new version. It's not a great experience for users, any idea what's going on?

**Comment by anthonychu** [comment]
Tables was initially missing in the v5 extension. It's being added here: https://github.com/Azure/azure-sdk-for-net/issues/25342

Once the preview is on NuGet, we can ship a corresponding worker package.

**Comment by vincentbitter** [comment]
Hi @anthonychu,

It seems the previes is on NuGet:
> Microsoft.Azure.WebJobs.Extensions.Tables 1.0.0-beta.1 is out on NuGet
> https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables/1.0.0-beta.1

https://github.com/Azure/azure-sdk-for-net/issues/25342#issuecomment-1013301396

**Comment by Hipster74** [comment]
Hmm, still missing the TableOutput attribute in `Microsoft.Azure.Functions.Worker.Extensions.Storage`?

What is the preferred  workaround at the moment? 

Would be great to have it back.

Would it be possible to use CosmosDb workerextension and target table storage some way maybe?

**Comment by longtimedeveloper** [comment]
@Hipster74 see my above comments.  It's very easy to change the code to use the APIs without the input binding.  Hope this helps.

**Comment by Hipster74** [comment]
Ok, thanks @longtimedeveloper , yes, I have already injected a TableService client in DI for other purposes so should be an easy fix to use it for function output as well.

Just feels a bit backwards since it is available in the samples :-)

**Comment by mattchenderson** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables/1.0.0 is now a GA version, and we should have a similar package here, too. It should not be housed under Microsoft.Azure.Functions.Worker.Extensions.Storage, but rather something like Microsoft.Azure.Functions.Worker.Extensions.Tables. The readme for the Storage package (5.x version) on nuget.org should be updated to help redirect.

**Comment by source-studio** [comment]
@mattchenderson - may I ask when the expected GA is for `Microsoft.Azure.Functions.Worker.Extensions.Tables`?
