### ISSUE TITLE
Isolated Functions don't like my big blobs 

### ISSUE THREAD

**Issue by GusGusGusGus** [Azure/azure-functions-dotnet-worker#405]
We have a big Blob stored in Azure storage (testing with smaller blobs of a few Kb, with 50mb, and up to about 100mb). 
**Our ultimate goal** is _to react to a relatively big blob upload in Azure Storage and send it to an Azure Function I'm running as an out-of-process function with a BlobTrigger_. As mentioned in the official [Isolated Process Guide](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) the binding support is scarcer in isolated functions, and "rich types like (...) and  CloudBlockBlobs are not supported", so when refactoring towards an isolated function, I tried to receive the Blob as string and as byte[], both working fine for smaller blobs. But!... the trigger doesn't pick up bigger blobs (50mb). The blob upload to storage is detected but doesn't trigger the function. Our function is using the correct worker dependencies also mentioned in the guide. 
Here's the code:
```
[Function("Shipper")]
        [BlobOutput("clean/{name}", Connection = "AzureWebJobsStorage")]
        public async Task<List<ConstituentPatchRequestDto>> Run(
        [Microsoft.Azure.Functions.Worker.BlobTrigger("dirty/{name}", Connection = "AzureWebJobsStorage")] 
        string inputBlob,
        string name = "")
        {
            Log.Information("New blob triggered function. Started processing blob with the following characteristics: \n Client: {name} \n Project GUID: {guid} ");

            var result = await _readService.Cleanse(inputBlob, name);

            Log.Information("Run successful!");

            return result;

        }
```

Does any one have any alternatives or possible solutions to achieve our goals stated above?

**Comment by GusGusGusGus** [comment]
Any follow up on this? I was forced in the meantime to use HttpTriggers because neither EventGrid nor BlobTrigger would support big blobs due to their lack of support for the input Stream binding (which is advised to be used instead of just shoving the blob in a string). But it would defeat the purpose of having Blobtriggers in the first place. Anyone was able to trigger a function with big blob, either through EventGrid or BlobTrigger? Thanks

**Comment by ilmax** [comment]
I have the same issues, with blob of approximately 4mb, the function never executes, I just get a tons of `Microsoft.Azure.WebJobs.Host.FunctionTimeoutException` and had to rollback to 3.1
