### ISSUE TITLE
"dotnet publish --no-build --no-restore" doest not work

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#409]
1. Create a new func app "func init"/"func new"
2. dotnet restore
3. dotnet build
4. dotnet publish --no-build --no-restore

Step 4 produces fails with following output:

Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  func-test -> d:\func-test\bin\Debug\net5.0\publish\
  Determining projects to restore...
  Restored C:\Users\Dmytro\AppData\Local\Temp\3p2rp01p.yqq\WorkerExtensions.csproj (in 760 ms).
C:\Program Files\dotnet\sdk\5.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(146,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. [C:\Users\Dmytro\AppData\Local\Temp\3p2rp01p.yqq\WorkerExtensions.csproj]

So, for some reason, it attempts to restore packages for project WorkerExtensions.csproj (what is it?) during the publish.

**Comment by ankitkumarr** [comment]
Hi @dmytro-gokun, we released a new `Microsoft.Azure.Functions.Worker.Sdk` version `1.0.3` earlier this week that includes a fix for this issue. Please try updating your SDK package and let us know if that solves it for you.

**Comment by dmytro-gokun** [comment]
@ankitkumarr Looks like it's been fixed. Thanks a lot!
