### ISSUE TITLE
TraceContext: TraceParent and TraceState properties are always empty.

### ISSUE THREAD

**Issue by rikbosch** [Azure/azure-functions-dotnet-worker#410]
I'm trying to setup distributed tracing in .NET 5 and as a minimum I would like to see the dependency calls of a .NET 5 worker function call in Application Insights.

I expected the worker to set `System.Diagnostics.Activity.Current` when processing a function invocation, but that is not the case.
So I wrote a middleware which extracts the `TraceParent` and `TraceState` properties into an `ActivitySource`:

![image](https://user-images.githubusercontent.com/549975/115739478-4009ce00-a38e-11eb-936a-e238557bfbae.png)

but the `TraceContext` properties are always empty. I don't know if this is an issue in de worker code, or an issue in the functions host.

**Comment by fabiocav** [comment]
This is currently a gap that @brettsam has been tracking. We'll have an issue created to track the work, link to it and close this once that is in place. 

Thank you!

**Comment by murthys** [comment]
I am waiting for the same, when will going to be supported?

**Comment by brettsam** [comment]
Today you need to have Application Insights enabled for this to work.

The host will eventually move to using the newer OpenTelemetry instrumentation so these traces flow without App Insights, but for now, App Insights is required.

**Comment by brettsam** [comment]
If you're trying to get this working with Application Insights, try the new preview packages: https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627

**Comment by brettsam** [comment]
I've filed https://github.com/Azure/azure-functions-host/issues/8846 to track removing the Application Insights requirement.
