### ISSUE TITLE
Cannot set application loglevel in isolated function "lower" than LogLevel.Information.  Exceptions: Exception encountered while listening to EventStream, Microsoft.Azure.WebJobs.Script.Grpc: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Chad-Ortho2** [Azure/azure-functions-dotnet-worker#417]
**Overview:**

I am struggling to determine how to set the log level for logs generated from a .Net 5 isolated function app to either `LogLevel.Debug` or `LogLevel.Trace`.  Setting the minimum log level in the `HostBuilder` will allow for the level to be increased but will result in an exception that prevents function execution when the level is decreased.

**Issue:**

Setting the default log level (`logging:logLevel:default`) in either an environment variable or `host.json` will impact the log level of the host and to a degree the application logs.  The log level setting defaults to `Information` and "raising" it to a higher level (`Warning`, `Error`, etc.) will filter application logs flowing through the host appropriately.  However, "lowering" the setting to `Debug` or `Trace` does not have the same impact on applications logs.

It appears a GRPC logging provider is created automatically when bootstrapping the function application and it's default log level is set to `Information`.  This log level can changed by using the same host configuration process as a traditional .Net web app (ex: `.ConfigureLogging(c => c.SetMinimumLevel(LogLevel.Error))`.  This setting does impact the logs flowing through the host if it is set to `Information` or higher, but results in a terminal exception when set to `Debug` or `Trace`.  

I haven't taken the time track the issue down further, but a blanket filter forcing all logs originating from `Microsoft` to `Information` or higher will work around the issue and allow a lower default setting.

Documentation surrounding this is sparse.  Is there a recommend method for setting the log level of an isolated function aside from the method I describe?

**Repo:**

- Scaffold a new dotnet-isolated function project
- Lower the default log level of the host (example `host.json` below) to allow all application logs to flow through.  **Note:**  Exception at the end will occur regardless of this step.
``` json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "default": "Trace"
    }
  }
}
```
- Create a sample function to demonstrate different log levels, trigger type is unimportant.  The test function I created is below
``` C#
public class TestFunction
{
    [Function(nameof(TestFunction))]
    public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test")] HttpRequestData req,
        FunctionContext executionContext)
    {
        var logger = executionContext.GetLogger<TestFunction>();

        Enum.GetValues<LogLevel>()
            .OfType<LogLevel>()
            .ToList()
            .ForEach(l=>logger.Log(l, "Log - {level}", l));

        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
        response.WriteString("Testing logging with HTTP trigger.");

        return response;
    }
}
```
- Execute function and notice the following output demonstrating that the default log level for application logs is `Information`
```
[2021-04-27T00:38:07.224Z] Log - Information
[2021-04-27T00:38:07.226Z] Log - Warning
[2021-04-27T00:38:07.233Z] Log - Error
[2021-04-27T00:38:07.235Z] Log - Critical
[2021-04-27T00:38:07.236Z] Log - None
```
- Change the default log level to a higher level (`Warning`, `Error`, etc.)
``` C#
public static void Main()
{
    var host = new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureLogging(c => c.SetMinimumLevel(LogLevel.Error))
        .Build();

    host.Run();
}
```
- Execute function and notice the following output demonstrating that the default log level for application logs has changed
```
[2021-04-27T00:36:57.610Z] Log - Error
[2021-04-27T00:36:57.613Z] Log - Critical
[2021-04-27T00:36:57.614Z] Log - None
```
- Change the default log level to a lower level (`Debug`, `Trace`)
``` C#
public static void Main()
{
    var host = new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureLogging(c => c.SetMinimumLevel(LogLevel.Debug))
        .Build();

    host.Run();
}
```
- Execute function and notice the following exceptions.  Function execution is no longer possible
```
[2021-04-27T00:41:50.911Z] Exception encountered while listening to EventStream
[2021-04-27T00:41:50.913Z] Microsoft.Azure.WebJobs.Script.Grpc: Object reference not set to an instance of an object. 
```
- Heavy-handed workaround.  Change default log level to a lower level but use a filter to keep `Microsoft` logs at or above `Information`
``` C#
public static void Main()
{
    var host = new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureLogging(c =>
        {
            c.SetMinimumLevel(LogLevel.Trace);
            c.AddFilter("Microsoft", LogLevel.Information);
        })
        .Build();

    host.Run();
}
```
- Execute function and notice the all levels are available for application logs
```
[2021-04-27T01:04:10.944Z] Log - Trace
[2021-04-27T01:04:10.946Z] Log - Debug
[2021-04-27T01:04:10.948Z] Log - Information
[2021-04-27T01:04:10.950Z] Log - Warning
[2021-04-27T01:04:10.955Z] Log - Error
[2021-04-27T01:04:10.957Z] Log - Critical
[2021-04-27T01:04:10.958Z] Log - None
```

**Comment by fabiocav** [comment]
@Chad-Ortho2 thank you for the detailed issue!

Also flagging @brettsam for awareness.

We need to make sure the guidance here is clear on configuration through `host.json` vs the worker (either programmatically or through config).

For the host level, there's some additional work we could perform in the host that would help, but there's a lot we can do in the meantime, particularly when it comes to the exception as that is flat out, a bug.

**Comment by fabiocav** [comment]
Leaving this open for further discussion/planning on this as there's a broader discussion for host changes that would impact all languages.

**Comment by palpet-icore** [comment]
Am I correct to understand that the only way to currently get Debug/Trace logs from the application is the (ugly) workaround above by setting it in code?

**Comment by Ogglas** [comment]
@brminnick Any indication when this will be released?

Affects the following code as well:

Program.cs

    public class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(services =>
                {
                    var connectionString = Environment.GetEnvironmentVariable("ConnectionStrings:DefaultConnection");
                    services.AddDbContext<ApplicationDbContext>(options =>
                            options.UseSqlServer(
                            connectionString,
                            sqlServerOptions => sqlServerOptions.CommandTimeout(600)));
                })
                .Build();
            //Enable when the following bug is fixed: https://github.com/Azure/azure-functions-dotnet-worker/issues/417
            //CreateDbIfNotExists(host);

            host.Run();
        }

        private static void CreateDbIfNotExists(IHost host)
        {
            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                var context = services.GetRequiredService<ApplicationDbContext>();
                context.Database.Migrate();
            }
        }
    }

ApplicationDbContext.cs

    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(
            DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<Blog> Blogs { get; set; }
    }

**Comment by brminnick** [comment]
I'll defer to @fabiocav for the release date.

I'm currently using the internal builds in my open source app, downloading the package from a temporary MyGet server: 
- Microsoft.Azure.Functions.Worker.Sdk v1.0.3-20210603.1
- Microsoft.Azure.Functions.Worker v1.2.0-20210603.1

https://github.com/brminnick/RedditStats/blob/5ca2ca534af24701ca956c54035f12b6182ebf26/Src/RedditStats.Functions/RedditStats.Functions.csproj#L11-L12

To access the MyGet server, you can just add this `NuGet.config` to the same folder as your `sln`:
https://github.com/brminnick/RedditStats/blob/main/Src/NuGet.config

**Comment by fabiocav** [comment]
The release is now out on NuGet (with Worker package version 1.3.0). Please let us know if you continue to have issues with that.

Thank you!
