### ISSUE TITLE
HttpTrigger not visible to API Management

### ISSUE THREAD

**Issue by mortware** [Azure/azure-functions-dotnet-worker#422]
I have created an Azure Function App, and I was hoping to see if I could hook it up to API Management. Sadly it seems that APIM can't see the functions I've created.

Will this ever be supported?

**Comment by david-peden-q2** [comment]
@mortware is your issue specifically related to an isolated azure function? I'm in the process of porting our stuff over to isolated and haven't attempted to deploy yet but we run in-process isolated functions with apim just fine. I can't imagine why being out-of-process would matter. it's just http between the two. can you supply more detail about your setup?

**Comment by fabiocav** [comment]
@mikebudzynski did you have some information that was potentially relevant to this issue?

**Comment by mikebudzynski** [comment]
@fabiocav, I would need more details and the reproduction steps.

**Comment by fabiocav** [comment]
@mortware was your issue with a simple HTTP function? Anything special about your setup? If not, I can provide a repro @mikebudzynski can use.

Can you also confirm this issue is still impacting your?

Thanks!
