### ISSUE TITLE
Using binding expressions with Multiple Output?

### ISSUE THREAD

**Issue by MikeBecatti** [Azure/azure-functions-dotnet-worker#430]
I've posted this question on SO but haven't received any responses.  I was wondering if you could provide some guidance.  I'm trying to use a binding expression with Multiple Outputs but haven't been able to get it to work.  Here is the link to the question on SO.  If you would rather I copy the body of that question and post it here please let me know.  

https://stackoverflow.com/questions/67288859/how-can-binding-expressions-named-parameters-be-used-when-following-the-multi-ou

**Comment by fabiocav** [comment]
@MikeBecatti thank you for reporting this. Flagging this for investigation as the behavior should be consistent, so I'm suspecting an issue with the function metadata generation process. 

Will provide updates here with our findings.

**Comment by fabiocav** [comment]
This helps. 

Since the information is not present in the JSON payload you're sending, that won't be available as part of binding data. The only information available in binding data with the payload you've shared above will be `FullImagePath` and `RemoveImage`

**Comment by fabiocav** [comment]
You can use a POCO, but the binding data processing is not the same for the out-of-process model (same applies to the other languages), and currently a limitation.

**Comment by MikeBecatti** [comment]
Ok, I understand the limitation but I tried using a POCO and I get this error: "Error converting 1 input parameters for Function 'ProfileImageUploaded': Cannot convert input parameter 'imageToProcess' to type 'ProfileImageProcessor.Models.ImageToProcess' from type 'System.String'."

Is there a Queue Trigger sample that uses a POCO?

**Comment by fabiocav** [comment]
Yes, [this sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/55e91c909597236d2adee45cc524464a6f548089/samples/Extensions/Queue/QueueFunction.cs#L15) uses a POCO for queue triggers. Does that work as expected for you?

**Comment by MikeBecatti** [comment]
I have essentially the same thing but get the exception I mentioned previously. 
```
public async Task Run([QueueTrigger("%ProfileImageQueueName%", Connection = "ProfileImageQueueConnectionString")] ImageToProcess imageToProcess,
            [BlobInput("%ProfileImageTmpBlobContainerName%/{FullImagePath}", Connection = "ProfileImageBlobConnectionString")] byte[] originalImageTmp,
                FunctionContext functionContext)
        {
```
```
public class ImageToProcess
    {
        public ImageToProcess(string fullImagePath, bool removeImage)
        {
            FullImagePath = fullImagePath;
            RemoveImage = removeImage;
        }
        public string FullImagePath { get; set; }

        public string RelativePath
        {
            get
            {
                return FullImagePath.Substring(0, FullImagePath.LastIndexOf("/") + 1);
            }
        }

        public bool RemoveImage { get; set; }
    }
```

**Comment by fabiocav** [comment]
@MikeBecatti we're still struggling to repro and fully understand the issue as the pattern above still has some of the issues we've pointed out.

Could you please provide the following:
 - A repository with a simple repro for your scenario
 - The sample payload being used to trigger the function.

Thank you for the help!

**Comment by MikeBecatti** [comment]
I'll get you a repo as soon as I can.
