### ISSUE TITLE
What is the correct way to get the caller IP

### ISSUE THREAD

**Issue by aistvan** [Azure/azure-functions-dotnet-worker#432]
Previously I can successfully read the caller's IP address from the HttpRequestMessage using this code:

```
private string GetClientIp(HttpRequestMessage request)
{
    if (request.Properties.ContainsKey("MS_HttpContext"))
    {
        return ((HttpContextWrapper)request.Properties["MS_HttpContext"]).Request.UserHostAddress;
    }

    if (request.Properties.ContainsKey(RemoteEndpointMessageProperty.Name))
    {
        RemoteEndpointMessageProperty prop;
        prop = (RemoteEndpointMessageProperty)request.Properties[RemoteEndpointMessageProperty.Name];
        return prop.Address;
    }

    return null;
}
```

With .Net 5 I couldn't figure out how can I do the same, as I see there is no supported way to do this.
Wouldn't I have noticed something?

**Comment by fabiocav** [comment]
You should be able to inspect the  `x-forwarded-for` header for that information. Can you give that a try?

**Comment by aistvan** [comment]
> You should be able to inspect the `x-forwarded-for` header for that information. Can you give that a try?

Thanks for the hint.
Looks like it works, I can see the information in **a.b.c.d:port** format.

**Comment by fabiocav** [comment]
Thank you for confirming! Closing as answered.

**Comment by aistvan** [comment]
What is the way if I would like to manipulate the binded output (or input) CloudTable's data?
Currently I got "row exist" exception if I want to "owerwrite" a row's value.
I couldn't find any example how can I remove the old one or update an existing one.
