### ISSUE TITLE
ServiceBusTrigger not executing (queue)

### ISSUE THREAD

**Issue by iloabn** [Azure/azure-functions-dotnet-worker#433]
I have two functions that listen to two different service bus queues.
Whenever I do a deploy, or go into the portal and take a closer look at the function, it starts to run and execute the function, taking messages of the service bus queue, but after a few minutes it stops.
I have about 5000+ messages in the queue, so I know it's not "done" with executing them, there's also 7000+ messages scheduled, if that could make a difference.

It seems a little similar to #337, #367 and #345.
But since I can see I have a higher runtime version which fixed it for the others, I assume I have some silly mistake on my side that I just can't figure out,

## What seems to work

- Going to the function app (in the portal) and pressing "refresh" on the app functions
- Going to the function app (in the portal) and looking at "things"
- A new deploy seems to trigger a few function executions

![image](https://user-images.githubusercontent.com/5629868/116815707-122b4300-ab5f-11eb-9ce1-7a1475309f8b.png)

## What I've tried
- Deploying the same code to linux versions of the application (this was however a few weeks ago, I could try it again, but I'd rather not)
- Making sure all NuGet packages are up to date
- Double check that `FUNCTIONS_WORKER_RUNTIME` is `dotnet-isolated`
- going to `functions -> monitor` to see if I can find any recent errors

## Original Context
- Runtime version: 3.0.15584.0
- Execution/invocation id: caf8c4d9-162e-4d9a-86bc-46df09e098d7
- Execution time: 2021-05-02T13:12:19.308
- Region: West Europe

## New context (2021-05-13)
- Runtime version: 3.0.15584.0
- Execution/invocation id: 3ddc99e4-5634-4112-b560-6c4a62951d8e
- Execution time: 2021-05-13 16:05:17.166
- Region: West Europe

## .csproj file (updated 2021-04-13)

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
    <PackageReference Include="Microsoft.Graph" Version="3.32.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Cosmos" Version="1.0.0-preview6" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.31.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.9.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project.Data\Project.Data.csproj" />
    <ProjectReference Include="..\Project.IntegratedCacheUtils\Project.IntegratedCacheUtils.csproj" />
    <ProjectReference Include="..\Project.Pixel\Project.Pixel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

## publish log (github action Azure/functions-action@v1)
```
Successfully parsed SCM credential from old publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Sucessfully acquired app settings from function app (with SCM credential)!
Will archive REDACTED into D:\a\_temp\temp_web_package_09752893422523634.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Setting SCM_DO_BUILD_DURING_DEPLOYMENT in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting SCM_DO_BUILD_DURING_DEPLOYMENT propagated to Kudu container
Setting ENABLE_ORYX_BUILD in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting ENABLE_ORYX_BUILD propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at REDACTED
Successfully deployed web package to App Service.
Successfully updated deployment History at REDACTED
Response with status code 204
Response with status code 204
Response with status code 204
```

Thanks for reading :)

**Comment by ankitkumarr** [comment]
Hi @iloabn, I took a look at your function app (through the execution ID you provided). I can confirm that your function app is indeed missing executions. It seems that the Scale Controller service in our platform is unable to find the Service Bus queues that you have configured your functions to run against. Because it is unable to find and monitor the queues, it doesn't allocate an instance for your app when you have messages arriving in the your queues. When you do access the portal which hits certain APIs on the function app, an instance is assigned, and your functions start running for a short period of time, until it's deallocated again.

How are you setting the connection strings and other service bus configuration values for your functions?
Is it possible that you are injecting these settings directly to your function app code by using `IConfiguration`? Please know that the App settings for connections strings / queue names, etc must come from Application Settings in Azure Function. This is required because the Scale Controller needs to be able to access the queues to monitor incoming messages.

Please let us know if that's not the case, and I will continue investigating :)

**Comment by iloabn** [comment]
Very interesting, thanks you for that investigation and explanation @ankitkumarr :)
For my function, I am setting the connection string using application settings, but the queue name is set directly in the function signature, like this:
```csharp
[Function("MyFunctionName")]
public async Task Run([ServiceBusTrigger("MyQueueName", Connection = "ServiceBusConnectionString", IsBatched = false)] CustomMessage input)
```
And another one looks like this:
```csharp
[Function("Updater")]
public async Task Run([ServiceBusTrigger("AnotherQueue", Connection = "ServiceBusConnectionString")] StatusMessage statusMessage)
```
*The example is a copy of the code, with the names of functions, queues, connectionstrings and models changed.*

Is the issue that the queue name has to be in application settings as well? 🤔

I am (in the first function) configuring a ServiceBusClient using IConfiguration, but that is **only** used so that I can add messages to queues and not to read them, so I hoped that wouldn't interfere. But that is also only used by the first example function app. The other one (which is running in it's own app service plan) is not having any integration with the service bus other than in the function signature, using the app settings connection string.

I also just confirmed that the connection string used is "just" added as an app setting in the "configuration" page, so it's not even connected to a keyvault or anything like that.

Is there anything else I could share or something you'd like me to try regarding this?

**Comment by ankitkumarr** [comment]
@iloabn, I am sorry I missed your update on this one.

What you have in the snippet looks fine and should work (with the queueName set however). It's a bit weird that the ScaleController wasn't finding your queue. Is there any difference in casing between your Application Setting and the way it's used in the Function definition attributes? Do you have perhaps any interesting access policies configured for your service bus?

Also I noticed, I don't see that log in ScaleContoller recently. Is this still an issue for you?

**Comment by fabiocav** [comment]
Moving this to `Triaged` until this is actionable.

**Comment by iloabn** [comment]
No worries with the update miss :)
I've now updated all NuGet packages and with that the function is running again, I'll comment again in two hours with an update if it has stopped before or if it works. And before that I'll try and fetch the data that you asked for.

**Comment by iloabn** [comment]
Noticing the Function is currently experiencing some other issues that seems to be because of my usage of Microsoft Graph. Until I've solved my current bugs I think this is going to be *very* hard to continue to investigate. I'll close this issue for now.
If I manage to fix my issues and this remains, I'll reopen it.

Have a lovely day.
