### ISSUE TITLE
Is it possible to register request-scoped dependencies?

### ISSUE THREAD

**Issue by david-peden-q2** [Azure/azure-functions-dotnet-worker#436]
Along those lines, do you plan to inject 'FunctionContext` or `HttpRequestData` into the container?

Obviously `FunctionContext` is available as a method level parameter but if the function itself is constructed per-request, why not inject it into the constructor instead?

If there is any existing documentation that discusses these topics, please point me at it. I was unable to find anything.

Thanks!

**Comment by david-peden-q2** [comment]
Not sure how I missed your response. I'd like to re-open this for discussion.

Under the old model, we had implemented our own method-level dependency injection solution using attributes. In some functions, we would inject a proprietary `ClaimsPrincipal`. Here's a simple example:

```csharp
[FunctionName(nameof(Claims))]
public static JsonResult Claims
(
    [HttpTrigger(AuthorizationLevel.Function, Route = "claims")]
    HttpRequestMessage request,
    [Dependency(typeof(CaasClaimsPrincipal))]
    CaasClaimsPrincipal caasClaimsPrincipal
)
{
    var claims = new Dictionary<string, string>();

    foreach (Claim claim in caasClaimsPrincipal.Claims)
    {
        if (claims.ContainsKey(claim.Type))
        {
            claims[claim.Type] += $",{claim.Value}";
        }
        else
        {
            claims.Add(claim.Type, claim.Value);
        }
    }

    return new JsonResult(claims);
}
```

The registration of `CaasClaimsPrincipal` looked like this:

```csharp
public static IServiceCollection UseCaasClaimsPrincipal(this IServiceCollection services)
{
    services.AddTransient(provider =>
    {
        var httpContextAccessor = provider.GetRequiredService<IHttpContextAccessor>();
        HttpRequest request = httpContextAccessor.HttpContext.Request;

        CaasClaimsPrincipal caasClaimsPrincipal;

        if
        (
            request.Headers.TryGetValue(RequestHeaders.Authorization, out StringValues authorizationHeader) &&
            AuthenticationHeaderValue.TryParse(authorizationHeader, out AuthenticationHeaderValue authenticationHeader)
        )
        {
            var jwt = new JwtSecurityToken(authenticationHeader.Parameter);
            caasClaimsPrincipal = new CaasClaimsPrincipal(jwt.Claims);
        }
        else
        {
            caasClaimsPrincipal = new CaasClaimsPrincipal(httpContextAccessor.HttpContext.User);
        }

        httpContextAccessor.HttpContext.User = caasClaimsPrincipal;

        return caasClaimsPrincipal;
    });

    return services;
}
```

In porting over to the new isolated model, we're (obviously) having to replace all usages of `IHttpContextAccessor`. And we've dumped our dependency injection solution in favor of the in-built one now that one exists.

I'd love to be able to do this:

```csharp
public static IServiceCollection UseCaasClaimsPrincipal(this IServiceCollection services)
{
    services.AddScoped(provider =>
    {
        var request = provider.GetRequiredService<HttpRequestData>();

        if (!request.Headers.TryCreateCaasClaimsPrincipal(out CaasClaimsPrincipal principal))
        {
            principal = new CaasClaimsPrincipal(request.Identities.Single());
        }

        return principal;
    });

    return services;
}
```

And then just inject the `CaasClaimsPrincipal` into the constructor of the function.

**Comment by david-peden-q2** [comment]
@fabiocav can you re-open this please?

**Comment by PeterRockstars** [comment]
I'd like to add that we have had a similar issue and are currently using a work-around where the first thing we do in every request is set the FunctionContext on a class we called FunctionCallContextProvider, which is registered in per-request scope. Gets the job done but obviously is not a very clean solution. 

So I'd like to second the request to re-open this.

**Comment by david-peden-q2** [comment]
Hey @fabiocav, I'd appreciate it if you would open this issue back up. Thanks.
