### ISSUE TITLE
Throw error when using Extension Bundles

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#44]
If `host.json` has extension bundle configured, everything works fine except no functions show up. It's really hard to tell the root cause. And this can happen if your app is missing `host.json` as even the default one has extension bundles.

We likely need to fix this in Host, but tracking here for .NET worker work.

**Comment by soninaren** [comment]
This work is completed here. (https://github.com/Azure/azure-functions-host/commit/927ffda9dde24b9175e65633de936bb530906025). We don't load extension bundle for dotnet isolated worker. However, there we do not log an error.
