### ISSUE TITLE
Validate URI for the gRPC channel prior to connection

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#442]
Today, if the worker is launched without a valid URI provided in configuration or command line argument, the failure is cryptic and not helpful. We should validate the URI and provide a clear error message if it isn't valid.

**Comment by jviau** [comment]
Looks like this is done now: https://github.com/Azure/azure-functions-dotnet-worker/blame/main/src/DotNetWorker.Grpc/GrpcWorkerClientFactory.cs#L110
