### ISSUE TITLE
Get Function Url not enabled in Az Portal

### ISSUE THREAD

**Issue by trailmax** [Azure/azure-functions-dotnet-worker#446]
After upgrading to .Net 5, I've noticed that none of my HTTP-triggered functions have "Get Function Url" enabled when I look on it in Azure Portal. The button is just greyed out:
![image](https://user-images.githubusercontent.com/3606356/118148354-65777e00-b408-11eb-990d-ffb8eba5cb1c.png)

Here is how it looks in code:
![image](https://user-images.githubusercontent.com/3606356/118148539-935cc280-b408-11eb-8ee5-7f52104b8ba4.png)

And I can trigger it locally, so the code executes no problem.

The issue might be connected to #422

**Comment by fabiocav** [comment]
@ehamai is this expected? Looks like the read-only logic might be disabling more than it should in the portal

**Comment by ehamai** [comment]
@takyyon, I think @fabiocav is right and we probably shouldn't disable that button if they're using run from package.  I'm guessing we disable it if you don't have write access on the app since you need that to get the key, but maybe we were a little too restrictive in the run-from-package case.  Can you confirm please?

**Comment by trailmax** [comment]
@ehamai yes, that button is active when working with .netcore 3.1, published from package, but goes inactive when the same func gets updated to .Net5, same publishing method. Kinda restrictive, as now I need to construct the url manually with keys.

**Comment by ehamai** [comment]
Oh I see.  This is more of a .Net 5 restriction than it is related to run-from-package.  @takyyon does that make sense?

**Comment by da1rren** [comment]
Any update this is impacting our upgrade efforts?

**Comment by twentytwokhz** [comment]
I was wondering what happened with the **Get Function Url** feature. Thought it was a problem with my http triggers..but now it makes sense

**Comment by trailmax** [comment]
@PavelRPavlov as far as I can see, it works now, the issue have been fixed a while ago and ticket should be closed.
