### ISSUE TITLE
gRPC: Ensure start stream is the first message sent

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#447]
More context in the PR comments -- https://github.com/Azure/azure-functions-dotnet-worker/pull/445. Specifically, [this comment](https://github.com/Azure/azure-functions-dotnet-worker/pull/445#pullrequestreview-659136374).

We want to make sure our gRPC setup doesn't send any messages until start stream is sent. We ordered the setup in a way that we send start stream first in the above PR. But Brett pointed out that we should tighten the setup to disallow sending anything else first.

**Comment by fabiocav** [comment]
After discussion, we're happy with the changes as they've gone in. Closing this as resolved.
