### ISSUE TITLE
Trigger type 'WarmupTrigger' is unrecognized

### ISSUE THREAD

**Issue by rinkeb** [Azure/azure-functions-dotnet-worker#448]
I'm trying to implement a warmup trigger, but the scale controller logs this warning: 

`Trigger type 'WarmupTrigger' is unrecognized or has an invalid/incomplete trigger configuration. The scale controller will not be able to directly activate or scale function 'Warmup'
`

The warmup trigger function has the same definition as the [sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/samples/Extensions/Warmup/Warmup.cs):

```
namespace MyApp.JobService
{
    public static class Warmup
    {
        [Function("Warmup")]
        public static void Run([WarmupTrigger] object _, FunctionContext context)
        {
		 ....
```

But also tried some variations (make it task based, remove the _ param, etc), without success.

The project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Warmup" Version="4.0.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.2" />
    ....

```

This occurs on an EP1 Premium plan (Linux) in westeurope.

Any idea what could be wrong? Thanks!

**Comment by fabiocav** [comment]
Can you confirm that you've **renamed** the discard (`_`) to something different (e.g. input) ?

**Comment by rinkeb** [comment]
Yep, just did another test to be sure, by renaming it to 'obj':

```
[Function("Warmup")]
public static void Run([WarmupTrigger] object obj, FunctionContext context)

```

That resolves the following Core Tools error locally:

`The 'Warmup' function is in error: The binding name _ is invalid. Please assign a valid name to the binding.
`

But the scale controller is still not happy after Azure deployment:

`5/19/2021, 3:42:23.716 PM,"Trigger type 'WarmupTrigger' is unrecognized or has an invalid/incomplete trigger configuration. The scale controller will not be able to directly activate or scale function 'Warmup'",2,trace,"{""Category"":""ScaleControllerLogs"",""TriggersHash"":""5127D9EE"",""FunctionName"":""Warmup"",""Timestamp"":""2021-05-19T13:42:23.7167774Z"",""SlotName"":""Production"",""AppName"":""<REMOVED>-prod-jobservice-func"",""Action"":""TriggerWarning""}",,,,,,,,,,,PC,,,"0.0.0.0",,,"United States",,,fe000000,"40efc63a-dc58-4262-aa09-8c6179410207","<REMOVED>-prod-jobservice-func","04776d1d-57d9-49f7-bf70-93e48f18d912","dotnet:2.8.1-22898","1835d613-b8a8-11eb-b1ac-893884afb8ad",1,"{""Category"":""ScaleControllerLogs"",""TriggersHash"":""5127D9EE"",""FunctionName"":""Warmup"",""Timestamp"":""2021-05-19T13:42:23.7167774Z"",""SlotName"":""Production"",""AppName"":""<REMOVED>-prod-jobservice-func"",""Action"":""TriggerWarning""}"
`

**Comment by fabiocav** [comment]
Thank you. Flagging this for investigation.

**Comment by ankitkumarr** [comment]
@rinkeb, I took a look at this and it turns out the warning is unharmful. Looks like scale controller doesn't recognize warmup triggers, but that's ok because it doesn't need to do anything with it. And this seems to be logged for all Function apps with warmup triggers (.NET or any other stack).

As for the discard character issue, I will update our samples shortly. Thanks for reporting that. :)

@glennamanns, do you think we can stop logging this from the Scale Controller (make Scale Controller aware of warmup triggers)?

**Comment by rinkeb** [comment]
@ankitkumarr Thanx for checking. Good to know the warmup sample is accurate now :-)

I found some log traces from my warmup function in app insights, so i can confirm that warmup function is indeed triggered just fine.

**Comment by fabiocav** [comment]
Closing as resolved.
