### ISSUE TITLE
error NU1202 Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50

### ISSUE THREAD

**Issue by prateekchawla** [Azure/azure-functions-dotnet-worker#449]
### Description

Building a .net project on a worker node.  with .net sdk 5 installed &  Azure Functions Core Tools installed 
### Configuration

**Error** 
`error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0`

> E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\ShiftRiskRelayFx\ShiftRiskRelayFx.csproj : error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0) [E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\Shift.sln]
 
 
 **Proj file looks like this**
 
```
 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.8.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
```

**Comment by SeanFeldman** [comment]
That doesn't seem to be right given the transitive [dependency of the package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.2.0)

![image](https://user-images.githubusercontent.com/1309622/118550892-80086a80-b71a-11eb-9780-5d18e1df6a60.png)

Notice the error message:

> error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with **net50 (.NETFramework,Version=v5.0)**. Package Microsoft.Azure.Functions.Worker 1.2.0 supports: **net5.0 (.NETCoreApp,Version=v5.0)**

.NET Framework 5.0 vs .NET 5.0. Is that some sort of local issue with the way .NET 5.0 installed?

**Comment by fabiocav** [comment]
It indeed sounds like a local environment issue. @prateekchawla can you validate that you have the same issue on different machines?

**Comment by prateekchawla** [comment]
Yeah looks like it built fine on other machine while we installed .Net 5.0 SDK using Jenkins plugin instead of installing it via installer(since the issue  was happening on a build machine)
