### ISSUE TITLE
Configure JSON ReferenceHandler

### ISSUE THREAD

**Issue by knnhcn** [Azure/azure-functions-dotnet-worker#451]
In an azure function I create an instance of a DbContext in order to access the database. My data model has many-to-many relations created with EntityFrameworkCore. The data can be loaded without any issues, but once trying to send a JSON response with `response.WriteAsJsonAsync(data)` I receive the following error:

```
System.Private.CoreLib: Exception while executing function: Functions.Function1.
System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. 
Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.)

at System.Text.Json.ThrowHelper.ThrowJsonException_SerializerCycleDetected(Int32 maxDepth)
...
```

So far I tried to configure the azure function in `Program.cs` with following lines but without any success:

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Text.Json.Serialization;
            
            var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults(opt =>
            {
                opt.Services.AddMvcCore().AddJsonOptions(o =>
                {
                    o.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
                });
            })
            .Build();

            host.Run();
```

Is there a way to configure any JSON serialization with Azure Functions and .NET 5?

`func --version 3.0.3477
dotnet --version 5.0.203`

**Comment by brettsam** [comment]
Your example is specifially setting the serializer options for MVC, which is not being used in your Functions app. I've just created a PR to include samples that show how to configure JSON serialization in the worker -- see this for details: #453. 

In your case, you'll want to do:

```
opt.Services.Configure<JsonSerializerOptions>(jsonSerializerOptions =>
{
    jsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
});
```
