### ISSUE TITLE
Suggestion for .NET 6 - Support Host.CreateDefaultBuilder()

### ISSUE THREAD

**Issue by rgylesbedford** [Azure/azure-functions-dotnet-worker#457]
I'm suggesting this for .NET 6 as it is probably a breaking change for .NET 5.0 isolated process functions.

Please use/recommend `Host.CreateDefaultBuilder(args)` similar to how [ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0) and [Console apps](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host) work.

This would provide automatic support for populating IConfiguration using the same default providers (appsettings.json, cmd line, env vars, user secrets, etc)

It also provides automatic validation of any registered services on the ServiceProvider (when env is Development).

If the defaults need to be overridden or removed, the call to ConfigureFunctionsWorkerDefaults() should be able to handle that (e.g. override set the Environment based on `AZURE_FUNCTIONS_ENVIRONMENT`).

This would also allow the removal of the local.settings.json file for .NET isolated process function apps.

Example of ideal Program.cs

``` csharp
using Microsoft.Extensions.Hosting;

namespace Contoso.Functions
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureAppConfiguration((hostBuilderContext, configurationBuilders) =>
                {
                    // Register non-default configuration providers
                })
                .ConfigureServices(services =>
                {
                    // Register services
                });
    }
}
```

**Comment by fabiocav** [comment]
@rgylesbedford want to make sure I'm not missing what you're trying to convey, but this would be a simple template change. The code you've shared above should work with the worker packages as-is, today. This would also not completely eliminate the dependency on `local.settings.json` as that applies to host level configuration as well.

Did you have a problem when you tried to use the code you've shared?
