### ISSUE TITLE
CosmosDbTrigger: Cant deserialize strings to enums

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#463]
Following the example found here:

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/CosmosDB/CosmosDBFunction.cs

I'm receiving 
Cannot convert input parameter 'leadData' to type 'System.Collections.Gen.Functions.LeadDuplicates+ChangeFeedLead, C2C.Functions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' from type 'System.String'.

where ChangeFeedLead is a simple POCO

**Comment by onionhammer** [comment]
I was able to work around this; apparently the deserializer used does not support deserializing strings as enums, and the error doesnt give any detailed error except the top level error.

**Comment by SeanFeldman** [comment]
What was your workaround?

**Comment by onionhammer** [comment]
@SeanFeldman adding an attribute:

```C#
[JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
public MyEnum MyProperty { get; set }
```

**Comment by fabiocav** [comment]
Thanks for sharing. Based on the exception and the POCO, I don't think we need any further action on this. Are you OK to close?
