### ISSUE TITLE
HttpRequestData always returns 200 as status code

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-functions-dotnet-worker#465]
I have created a function that returns an error using the following code:

```fsharp
[<Function("myfunc")>]
let run ([<HttpTrigger(AuthorizationLevel.Function, "get")>]req: HttpRequestData) =
    async {
        let response = req.CreateResponse(HttpStatusCode.BadRequest)
        do! response.WriteAsJsonAsync("error message")
        return response
    } |> Async.StartAsTask
```

The message gets propagated correctly and the function returns "error message", but the status code returned is `200` instead of `400`

`.NET 5.0.300`
```
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0
```

Context: https://github.com/UnoSD/UnoCash.Fable/blob/net5-azure-function/UnoCash.Api/GetExpenses.fs

I also tried getting rid of the `Task<HttpResponseData>` with `.Result` to make sure it wasn't an unwrapping issue, same results.

Thank you.

**Comment by stagep** [comment]
The WriteAsJsonAsync method sets the status code to 200. This is already submitted as issue # 344

https://github.com/Azure/azure-functions-dotnet-worker/issues/344

**Comment by UnoSD** [comment]
@stagep Thank you for the confirmation, I can close this issue then and follow the other.
