### ISSUE TITLE
How to get the metadata of queue messages or service bus messages in Azure Functions for Net 5

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-dotnet-worker#467]
Hello

I'm migrating Azure functions from Net Core 3.1 to Net 5.
For Net Core 3.1 I have a parameter of CloudQueueMessage type (Microsoft.WindowsAzure.Storage.Queue) where I receive all the [trigger metadata](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#trigger-metadata) : ExpirationTime, InsertionTime, etc...

I don't use annotations in my code. I have the function.json file with the "configurationSource": "config" entry, like this

{
  "configurationSource": "config",
  "bindings": [
    {
      "type": "queueTrigger",
      "connection": "AzureWebJobsStorage",
      "queueName": "prueba",
      "name": "myQueueItem"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/QueueHandler.dll",
  "entryPoint": "QueueTriggerHandler.Run"
}

That works perfect.

Now for Net 5, I read that we cannot use CloudQueueMessage any more ([here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#bindings)), but only POCOs are supported.

My question is, how should I get the metadata of the queue message (or service bus message) ?

I also tried passing the elements of the metadata as parameters of the function, but it doesn't work:

 public static void Run( string myQueueItem, Int32 deliveryCount, DateTime enqueuedTimeUtc, string messageId, ILogger log)
 {}

So the question is:

1. How to get the metadata of the messages sent to service bus or queue storage.
2. Not having annotations in the code and having  "configurationSource": "config" is still supported? Or it's a must to have the code annotated?

Thanks
Sabrina

**Comment by SeanFeldman** [comment]
Metadata is likely on the context object. That's how it's accessed for Service Bus trigger (see [issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/384) for details). Try property names for storage queue type from SDK v12.

**Comment by sjuarezgx** [comment]
Thank you for your reply. It worked OK. 
The only data I still can't get is the SessionId. Do you know any issue related to this?

**Comment by fabiocav** [comment]
@sjuarezgx session ID should be present in the same collection. Is it present but showing an unexpected value? Or missing altogether? Are you using sessions?

**Comment by sjuarezgx** [comment]
The SessionId is not present.
I'm doing this:

if (context.BindingContext.BindingData.TryGetValue("SessionId", out var SessionIdObj) && SessionIdObj != null)
				{
					message.SessionId = SessionIdObj.ToString();
                                }

I have sessions enabled, as it's explained [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/enable-message-sessions).

Thanks

**Comment by sjuarezgx** [comment]
I've already found the Session Id at MessageSessionObject.

Thank you.
