### ISSUE TITLE
How do I configure the initialVisibilityDelay for QueueOutputs?

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-dotnet-worker#470]
Hello,
we are moving our Azure Functions from 3.1 to 5.0 and are using queues extensively. In our application we have to delay the trigger of some message by a couple of minutes. 

In 3.1 we referenced the queue and use the [AddMessageAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueue.addmessageasync?view=azure-dotnet-legacy#:~:text=AddMessageAsync%20%28CloudQueueMessage%29%20Initiates%20an%20asynchronous%20operation,to%20add%20a%20message%20to%20the%20queue.) method to specify a custom initialVisibilityDelay.

Do you have some recommendations how to achieve this task using a "QueueOutput" or some other sorts of techniques? 

Thank you for your feedback

**Comment by fabiocav** [comment]
This is, unfortunately, not currently supported with bindings.

In order to do this with the out-of-proc model you'd need to work directly with the SDK.

**Comment by plamber** [comment]
Hi @fabiocav,
thank you for the feedback. Are there any plans to support this in future?

Any suggestions what is the most elegant and easy way to get a reference to a queue in a function?

Cheers
