### ISSUE TITLE
Application stops running during debugging with a TimerTrigger

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-dotnet-worker#471]
Hi,
we are using Visual Studio 16.11.0 Preview 1.0 to debug the Azure Functions. The project has following packages referenced:
- Microsoft.Azure.Functions.Worker 1.2.0
- Microsoft.Azure.Functions.Worker.Extensions.Abstractions 1.0.0
- Microsoft.Azure.Functions.Worker.Extensions.Storage 4.0.4
- Microsoft.Azure.Functions.Worker.Extensions.Http 3.0.13
- Microsoft.Azure.Functions.Worker.Extensions.Timer 4.1.0
- Microsoft.Azure.Functions.Worker.Sdk 1.0.3

During debugging the application stops working if you have a TimerTrigger.

You can reproduce this by creating a project with a simple TimerTrigger and HttpTrigger. In Visual Studio 16.11.0 Preview debug the solution and try to call the HTTPTrigger. The application will stop working. 

The same project works without issues when using "func host start" in the console. The TimerTrigger runs without exceptions and the HttpTrigger can be called in the browser.

Cheers

**Comment by fabiocav** [comment]
@plamber are you seeing an error when that happens? Or does the process just exits?

**Comment by distantcam** [comment]
I've been having a similar issue after first running the timer function.

Something to do with the monitoring is causing the debugger to not attach properly. I added `UseMonitor = false` to the timer attribute and the debugger started working again.

**Comment by plamber** [comment]
@fabiocav: Visual Studio freezes and after a while it throws this exception
![image](https://user-images.githubusercontent.com/18241305/120586597-1b485200-c434-11eb-9135-755da5daa9d4.png)

I tried to remove RunOnStartup as @distantcam suggested, but I am sill having the same issue. 

It fails once I perform one of these combinations
- Have two timer functions created with the "func new" command
- Have a timer function without static decorators
- Have a timer function with dependency injection
- Have a timer function with dependency injection and an async method

**Comment by distantcam** [comment]
@plamber I also had to add `UseMonitor = false`. Does that work?

**Comment by plamber** [comment]
Hi @distantcam,
adding UseMonitor = false to each function solved the problem. 

I misread your initial suggestion.

Cheers

**Comment by brettsam** [comment]
Tracking this in #434
