### ISSUE TITLE
OpenAPI support for .NET 5

### ISSUE THREAD

**Issue by mabvanaartrijk** [Azure/azure-functions-dotnet-worker#473]
Azure Functions in .NET Core 3.1 has OpenAPI support: https://docs.microsoft.com/en-us/azure/azure-functions/openapi-apim-integrate-visual-studio. Is OpenAPI support on the roadmap for .NET 5? Thanks!

**Comment by cosminstirbu** [comment]
I'm also interested in this functionality.

**Comment by h3x4d3c1m4l** [comment]
Maybe this can be helpful: https://github.com/hajekj/azure-functions-openapi-demo

**Comment by cosminstirbu** [comment]
It does, only that it uses `<PackageReference Include="Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration" Version="2.0.0-beta02" />` which hasn't been updated in 2 years and it doesn't look like it's [actively maintained](https://github.com/microsoft/OpenAPI.NET.CSharpAnnotations).

**Comment by h3x4d3c1m4l** [comment]
Mmm haven't paid attention to that. It does work though, just implemented it for a few of our http triggers.

**Comment by fabiocav** [comment]
We're discussing this with the team working on the OpenAPI extension. Will keep this open for tracking, but this work is not currently prioritized/planned, so I can't provide an ETA.

/cc @bradygaster @justinyoo @spboyer

**Comment by bradygaster** [comment]
I do think it would be good for @justinyoo and @spboyer and I to triage and understand what would be needed to support it. I also think with 6 being right around the corner, it would be better for us to pivot to just making sure that works. Frankly, that's probably the best investment choice atm.

**Comment by spboyer** [comment]
@justinyoo - Can you look into the .NET 5/6 story and provide some feedback here?

related issue in extension repo: https://github.com/Azure/azure-functions-openapi-extension/issues/22

**Comment by justinyoo** [comment]
@spboyer I’ve been on it. My challenge is that I have to decouple some WebJobs packages.

**Comment by justinyoo** [comment]
Related: https://github.com/Azure/azure-functions-openapi-extension/pull/142

**Comment by pnda489** [comment]
Maybe
https://github.com/Azure/azure-functions-openapi-extension/tree/main/samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.V3Net5
is what you are Looking for?

**Comment by soninaren** [comment]
Net 5 is no longer a supported version. OpenAPI does work with isolated worker. You can use this extension here https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/1.5.1.
