### ISSUE TITLE
Accessing Event metadata in EventHub triggered Function 

### ISSUE THREAD

**Issue by ijagberg** [Azure/azure-functions-dotnet-worker#477]
I have a Function with the following signature:

`public async Task Run([EventHubTrigger("", Connection = "...", ConsumerGroup = "...")] string[] messages)`

This works fine for reading the body of events.

For each incoming message, I want to access Event metadata (such as EnqueuedTimeUtc, or the Properties dictionary).

In the .NET Core runtime, I would change `string` into `EventData` as such:

`public async Task Run([EventHubTrigger("", Connection = "...", ConsumerGroup = "...")] EventData[] messages)`

But doing so while using the isolated runtime and the following NuGet packages (running locally):

```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.2.1" />
<PackageReference Include="Azure.Messaging.EventHubs" Version="5.4.1" />
```

I get the following error: 
```
System.Private.CoreLib: Exception while executing function: Functions.ExampleFunction. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'ExampleFunction': Cannot convert input parameter 'messages' to type 'Azure.Messaging.EventHubs.EventData[]' from type 'System.String'.
at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
```

**Comment by ijagberg** [comment]
All documentation I've been able to find regarding EventHub triggers in .NET 5 (including the examples in this repository) use the `string[]` syntax, so I can't tell if this is no longer supported or I am missing something.

**Comment by RikkoE** [comment]
I am also interested in this issue, I need the Enqueued time for monitoring of our apps but cannot find it in the .NET 5 versions.

**Comment by fabiocav** [comment]
All this information will be available in the `FunctionContext`. 

I'm leaving this open and assigned to myself to update the Event Hubs sample to demonstrate that.

**Comment by ijagberg** [comment]
Excellent, thank you for the answer. Managed to get it to work but I definitely think it would be good to have some concrete examples.

**Comment by matthieuklotz** [comment]
Hi,

@ijagberg : I will be very interesting by your solution for using EventData[] instead of string[] (I have the same use case than you).
Currently I solve the issue by reading the "PropertiesArray" in the bindingContext , but it's really not clean as using the EventData class.

Regards,

**Comment by ijagberg** [comment]
@matthieuklotz Sorry, I meant I managed to get access to the metadata, but I still had to use the `string[]` syntax. Probably did it similar to you, by deserializing the `BindingData` dictionary.

**Comment by brettsam** [comment]
I've submitted a PR with a sample of how you can retrieve this data -- https://github.com/Azure/azure-functions-dotnet-worker/pull/508.

It's not as clean as `EventData`, but the structure of the data sent to the worker is different than it is for in-proc. We may be able to improve this with some converters, but the samples should help for now.

**Comment by ijagberg** [comment]
Well, the example with parameters is still a lot nicer than what I came up with, so that's great! Thank you!
