### ISSUE TITLE
Remove .NET Core 3.1 SDK requirement to build project

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-dotnet-worker#480]
This is a common cause of confusion, particularly in setting up CI/CD. Also requires special treatment in order to support it in Azure Static Web Apps. https://github.com/microsoft/Oryx/issues/1032

**Comment by forki** [comment]
Yes this one is really really annoying - we can't build net5 functions without 3.1 installed on CI

**Comment by qianz2** [comment]
Oryx recently added .NET Core 3.1 SDK to the image, it will soon be available in Oryx upcoming release.

**Comment by anthonychu** [comment]
Thanks @qianz2. Can you confirm that .NET Core 3.1 is available by default in all versions of Oryx (not just the Static Web Apps (Jamstack)) image?

Keeping this issue open as this still affects builds that are not using Oryx.

**Comment by Romfos** [comment]
@fabiocav Could you please tell us why do we have such kind of limitation? Thank you!

**Comment by soninaren** [comment]
This is no longer a requirement for supported versions of azure functions.
