### ISSUE TITLE
item not removed from queue

### ISSUE THREAD

**Issue by GPedroxd** [Azure/azure-functions-dotnet-worker#481]
I have a function with servicebustrigger, and when the function receives the message it does not remove it from the queue, but when the run method is static, it removes. how do i get the run async method to remove the item from the queue? I have a function with servicebustrigger, and when the function receives the message it does not remove it from the queue, but when the run method is static, it removes. how do i get the run async method to remove the item from the queue? 

![Untitled](https://user-images.githubusercontent.com/53350928/121075225-4ff93800-c7ab-11eb-9410-e6d3f16e3f6a.png)

**Comment by brettsam** [comment]
Is the function execution throwing an error?
What if you change your method to just `await Task.CompletedTask`? Does it work as expected then?
