### ISSUE TITLE
Why are the interfaces internal?

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-dotnet-worker#485]
I'm trying to do something similar to this issue: https://github.com/Azure/azure-functions-dotnet-worker/issues/340

It would be easy to temporarily fix this ourselves if we could replace some of the required types with our own. For instance, register a custom IWorker or IFunctionExecutor. But these interfaces are all internal, making that impossible. 

It would be great if at least the interfaces, if not the classes, could be made public.

**Comment by brettsam** [comment]
That's the plan, but we're trying to be very deliberate about what the public interfaces look like when they go public. Once they're public, we can't revise them without another major version bump.

No ETA, but we'll be doing some work soon to open up some more functionality.

Closing this as we'll be tracking this work elsewhere (such as in the linked issue above).
