### ISSUE TITLE
Unexpected high memory usage when deployed

### ISSUE THREAD

**Issue by dev-jla** [Azure/azure-functions-dotnet-worker#486]
I'm seeing an unexpectedly high Private Bytes values for a deployed functions app- now this is a simple app that is happy to run at 30-50MB but when I check analytics the process consumes around 700MB.

**Comment by dev-jla** [comment]
the real concern I think is if it affects billing or this is something we're seeing with isolated process?

**Comment by brettsam** [comment]
This does seem high -- if you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

Is this repeatable? If so, do you have a sample that we could try to run?

**Comment by dev-jla** [comment]
Thanks for responding, the details are below. If you locate the app and the url you can try any uk postcode eg. https://<functionappname>/postcode/E20%202ST

It is repeatable the app private bytes hover around 680-720 mark.
2021-06-10T21:44:08Z   (Succeeded, Id=f3dcb1d3-c636-4813-88fe-87b633cd2dc6, Duration=348ms) uksouth

**Comment by dev-jla** [comment]
It turns our this only happens when using Linux OS 3.0.15885.0, however Windows is further along at 3.1.3.0 redeploying to that instance solved it. Not sure why Linux is so far behind.
