### ISSUE TITLE
Cannot debug in VS 2019 when TimerTrigger invokes due to IsPastDue UnscheduledInvocationReason

### ISSUE THREAD

**Issue by DavidGodbold** [Azure/azure-functions-dotnet-worker#488]
I ran the debugger by pressing Debug in VS and also alternatively followed the guidance at [here](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Debugging) to debug locally. 

On both occasions I receive the same timeout error when a TimerTrigger is invoked due to a CRON expression (see TimerTrigger C# declaration in image below) which means it runs to catch up on a missed invocation. 

![image](https://user-images.githubusercontent.com/40599276/121356734-0a627980-c929-11eb-9736-19f2fc1adbc9.png)

If I just run the functions using func host start command then the trigger runs successfully. 

See image below for error messages when running Functions from CLI. 

![AzureFunctionsIsolatedTimerTriggerDebuggingError](https://user-images.githubusercontent.com/40599276/121356468-c8393800-c928-11eb-9817-a81b2a90a990.png)

My version of VS 2019 is as follows.
![image](https://user-images.githubusercontent.com/40599276/121358837-d2f4cc80-c92a-11eb-84aa-3f543b45923c.png)

**Comment by DavidGodbold** [comment]
I have since deployed application to Azure (Windows, Consumption plan) and it even fails there. Any timer trigger times out after 5 minutes.

![image](https://user-images.githubusercontent.com/40599276/121378609-43a3e500-c93b-11eb-886f-7ac2603d7e00.png)

**Comment by DavidGodbold** [comment]
If I create a new Function project using latest version of VS 2019 at time of writing (16.10.1) with a TimerTrigger using the VS template, with a CRON expression of 0 */10 * * * *, I get the same issue so I feel that rules out the issue being within my codebase.

![image](https://user-images.githubusercontent.com/40599276/121379092-a0070480-c93b-11eb-9965-a803c99e89d0.png)

**Comment by brettsam** [comment]
Thanks @DavidGodbold! Tracking these debugging timeout issues in #434.
