### ISSUE TITLE
When running via Visual Studio integration, timer-triggered function causes host to hang

### ISSUE THREAD

**Issue by RyanMarcotte** [Azure/azure-functions-dotnet-worker#492]
I am debugging a [NET 5 Azure Function app using Visual Studio](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/dotnet-isolated-process-developer-howtos.md#run-the-function-locally).  I have two HTTP-triggered functions and a timer-triggered function.  The function app host appears to hang upon startup as no breakpoints are hit (a set one at the first line in `Main`).

![image](https://user-images.githubusercontent.com/1458084/121268823-ebf27480-c87b-11eb-865d-871a077ffe22.png)

The function app boots up and debugs properly through Visual Studio if I comment out / delete the timer-triggered function.

Everything works fine (HTTP-triggered + timer-triggered functions) if I use `func host start` from the command line though.

![image](https://user-images.githubusercontent.com/1458084/121269225-ac785800-c87c-11eb-863e-714b93a54b92.png)

**Comment by brettsam** [comment]
Thanks @RyanMarcotte -- we're tracking this in #434
