### ISSUE TITLE
dotnet-isolated fx - unit testing support/guidelines

### ISSUE THREAD

**Issue by lohithgn** [Azure/azure-functions-dotnet-worker#501]
Hi. Lohith here. I work in the capacity of Technology Lead for a consulting firm in Singapore. We are early adopters of everything & anything of Azure :). We like to play with the latest & greatest tech. We jumped on the band wagon of .NET5 based dotnet-isolated function recently. We moved functions in one our projects to .NET5 isolated model. 

One thing we noticed was the lack of direction/guideline on unit testing the functions in isolated model. Meaning the docs dont yet have any items on this front. Well everybody may ask its a regular TDD so its nothing different. Yes but what we faced is - its hard to mock things now at this stage of isolated fx model.  I looked at the dotnet worker repo, scouted through your unit tests. In order to mock a simole HttpRequestData & HttpResponseData - i had to create test double for FunctionContext. I just couldnt mock FunctionContext - as it lacks certain things from a mocking perspective. So at this point of time - we have the following bare minimum test doubles or handwritten mocked classes (hijacked from your unit tests):
![image](https://user-images.githubusercontent.com/2450336/121839537-de6e3c00-cd0c-11eb-922a-c73928219d48.png)

We have many projects where we want to go full guns on isolated model. We writing a custom lib to house the mocked test doubles on our org level and consuming in each project is making us think twice. 

Is there anything the team can do to make the unit testing experience a better experience.

thoughts ??

**Comment by anthonychu** [comment]
@fabiocav @brettsam @ankitkumarr Thoughts on how to make these more testable?

**Comment by lohithgn** [comment]
@fabiocav @brettsam @ankitkumarr Hello. Would appreciate if you guys have any update on this front. It will help us too to understand what is Microsofts stand on this matter. Thanks.

**Comment by fabiocav** [comment]
Our plan is to provide a full test framework, which would provide all of the functionality required for unit/integration tests. You can find more details about that here: https://github.com/Azure/azure-functions-dotnet-worker/issues/281

**Comment by newbazz** [comment]
hello all,
I am stuck while testing, I need to set Query for a mock object, the code snippet is given below.
```var request = new Mock<HttpRequestData>(context.Object);
request.Object.Query = new QueryString("?returnUrl=value");```
But this is giving error, can someone help me

**Comment by WestDiscGolf** [comment]
I'm coming up against the same issues @lohithgn experienced with the mocking of all the requirements and setting up the service provider etc. Is there an update on when the official testing strategy will be released? Thanks.

@lohithgn Are your test doubles in a public repo anywhere? Thanks

**Comment by lohithgn** [comment]
@WestDiscGolf nope. I did it for a project of ours. I will see if I can create a repo with what I have and post it here.... Thanks.

**Comment by lohithgn** [comment]
@WestDiscGolf did you check this... 

https://github.com/Azure/azure-functions-dotnet-worker/issues/281#issuecomment-1004945439

**Comment by WestDiscGolf** [comment]
@lohithgn Thanks for replying. I did see the other issue but I think with that and the setting up test doubles my project has got in a bit of a mess 😢 Using that method I got to the service provider setup and thought the test double way *may be* easier. Think I will have to delete and start again 😆 Thanks again for replying!

**Comment by lohithgn** [comment]
@WestDiscGolf  I put together a small repo with test doubles. You can check it out here:  https://github.com/lohithgn/az-fx-isolated-unittest.

Hope this helps.

**Comment by WestDiscGolf** [comment]
@lohithgn thanks for sharing, will take a look!

**Comment by kosalanuwan** [comment]
> @WestDiscGolf I put together a small repo with test doubles. You can check it out here: https://github.com/lohithgn/az-fx-isolated-unittest.
> 
> Hope this helps.

Thanks for sharing this, @lohithgn, can you verify if this works for functions middleware using mstests and moq for azure functions v4 .net6 isolated functions apps?

**Comment by WestDiscGolf** [comment]
@kosalanuwan Looking at the testing code I don't see there would be an issue with using mstest as your test runner of choice instead of xunit.

**Comment by shubhamverma247** [comment]
> @WestDiscGolf I put together a small repo with test doubles. You can check it out here: https://github.com/lohithgn/az-fx-isolated-unittest.
> 
> Hope this helps.

hello sir, in your repo you commented some code in FunctionContext can you please give me some idea how to add Features and BindingContext

**Comment by mattchenderson** [comment]
Closing as this is a component of #281
