### ISSUE TITLE
How to use IOptions pattern for configuration?

### ISSUE THREAD

**Issue by Elip-tdlr** [Azure/azure-functions-dotnet-worker#503]
I'm attempting to port an existing Functions app from core3.1 v3 to net5.0 I but can't figure out how to get the IOptions configuration pattern to work.

My local.settings.json contains the following:
```
    "GraphApi:AuthenticationEndPoint": "https://login.microsoftonline.com/",
     "GraphApi:ClientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "GraphApi:ClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "GraphApi:EndPoint": "https://graph.microsoft.com/",
    "GraphApi:TenantId": "xxxxxxxxx.onmicrosoft.com",
```

I can get to it using GetEnvironmentVariable. Still, the following does not bind the values to the IOptions configuration like it used to.
```
.Services.AddOptions<GraphApiOptions>()
    .Configure<IConfiguration>((settings, configuration) => configuration.GetSection("GraphApi").Bind(settings))
```

The problem appears to be with `GetSection`, it does not return any values.
This seems to have been mentioned in [this](https://github.com/Azure/azure-functions-dotnet-worker/issues/277#issuecomment-799573914) issue but I'm not able to find any further information.

Is this still supported? What am I missing?

**Comment by oscarvantol** [comment]
Hi @Elip-tdlr,

Are your settings in the  `"Values": { }` property? 

I created a working IOptions implementation example for you in:
https://github.com/oscarvantol/azure-functions-dotnet5-examples/blob/main/ExampleFunction/HttpFunction.cs

I hope it helps you.

PS: in your config example you pasted some secrets, I hope they are not still working.

**Comment by Elip-tdlr** [comment]
Hi  @oscarvantol ,

Thank you for the example. This does indeed work. I'm still trying to figure out why my implementation isn't working but it's clearly a self-inflicted issue.

Also, thanks for pointing out the secrets in my original post. They were for my private development environment. Regardless I removed them.

**Comment by KalyanChanumolu-MSFT** [comment]
@Elip-tdlr I ran into the same issue today while reading from AzureAppConfiguration.
It is most probably because you are not building it before using in Configure services.
After this i can use IOptions configuration values.

 ```cs
var host = new HostBuilder()
                        .ConfigureFunctionsWorkerDefaults()
                        .ConfigureAppConfiguration((hostingcontext, configurationBuilder) =>
                        {
                            _configuration = configurationBuilder.Build();

                            // Reading configuration and secrets from AzureAppConfiguration and KeyVault using Managed Identity
                            configurationBuilder.AddAzureAppConfiguration(options =>
                            {
                                var credentials = new DefaultAzureCredential();
                                options.Connect(new Uri(_configuration["AzureAppConfigurationEndpoint"]), credentials)
                                .ConfigureRefresh(refresh =>
                                {
                                    refresh.Register(key: "SubscriptionManagement:IsConfigurationUpdated", label: LabelFilter.Null, refreshAll: true)
                                           .SetCacheExpiration(TimeSpan.FromMinutes(5));
                                })
                                .ConfigureKeyVault(kv =>
                                {
                                    kv.SetCredential(credentials);
                                });
                            });

             // BUILD After you read from AzureAppConfiguration
                            _configuration = configurationBuilder.Build();  

                        })
                        .ConfigureServices(services =>
                        {
                            services.AddScoped<MicrosoftGraphService>();
                            services.AddScoped<MicrosoftGraphRepository>();
                            services.Configure<MicrosoftGraphOptions>(_configuration.GetSection(MicrosoftGraphOptions.Configuration));

```

**Comment by fabiocav** [comment]
@Elip-tdlr can you please share your options (GraphApiOptions) and the full setup? If you can share your repro in a GitHub repo, that would be ideal. 

The Options setup and usage with the worker should be identical to what you'd typically do in .NET, but we can provide feedback if you can share more details about your scenario.
