### ISSUE TITLE
Persistence of state in Azure functions Net 5

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-dotnet-worker#505]
Hi

I'm developing an azure function (http trigger) using Net 5.

I know that the azure functions are stateless and the Durable Functions are not supported in Net 5. But I need to have a web session accesible to the functions (it can be using Redis for example or any other way for session handling).

Is it possible to do it? How can I reference the web session from my Azure function?

Thanks

**Comment by fabiocav** [comment]
Yes. You can leverage services like Redis and other persistence services. There's nothing in the worker today that will manage sessions for you, so this is something you'd also need to handle as well, but you can consume any of those services from Functions running out-of-proc as well.

**Comment by fabiocav** [comment]
Closing as answered, but let us know if you have any additional questions.
