### ISSUE TITLE
HttpRequestData.WriteAsJsonAsync only serializes properties declared on interface

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-dotnet-worker#506]
Given these types:

```
    interface IResult
    {
        public string InterfaceProperty { get; set; }
    }

    class ResultImplementation : IResult
    {
        public string InterfaceProperty { get; set; } = "InterfaceProperty";

        public string ClassProperty { get; set; } = "ClassProperty";
    }
```

and this function: 
```
        [Function(nameof(Run))]
        public async Task<HttpResponseData> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "GET")]
            HttpRequestData req)
        {
            IResult result;

            result = new ResultImplementation();

            var response = req.CreateResponse();
            await response.WriteAsJsonAsync(result);

            return response;
        }
```

I would expect to see:

> {"interfaceProperty":"InterfaceProperty", "classProperty":"ClassProperty"}

 but the response I see is:

> {"interfaceProperty":"InterfaceProperty"}

Currently we fix this by doing: 

```
await response.WriteStringAsync(JsonConvert.SerializeObject(result));
```

but that seems like a workaround and not the intended use.

Is this intended behaviour?

**Comment by fabiocav** [comment]
This is by design with the current implementation, but we could expose non-generic overloads that take a type of derive the type from the provided argument as well. 

Leaving this open for consideration.

**Comment by anthonychu** [comment]
This is also the behavior of ASP.NET Core as well:

```cs
[HttpGet]
public async Task GetAsync()
{
    IThing thing = new Thing
    {
        Foo = "Hello",
        Bar = "World"
    };
    await this.Response.WriteAsJsonAsync(thing, typeof(Thing));
    // only includes Foo
}

public interface IThing
{
    string Foo { get; set; }
}
public class Thing : IThing
{
    public string Foo { get; set; }
    public string Bar { get; set; }
}
```

Its version of `WriteAsJsonAsync` includes a [non-generic version](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponsejsonextensions.writeasjsonasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Http_HttpResponseJsonExtensions_WriteAsJsonAsync_Microsoft_AspNetCore_Http_HttpResponse_System_Object_System_Type_System_Threading_CancellationToken_) that allows you to pass the type. We should consider exposing the same here.

**Comment by PehrGit** [comment]
> This is by design with the current implementation, but we could expose non-generic overloads that take a type of derive the type from the provided argument as well.
> 
> Leaving this open for consideration.

That's good to know, thanks for the info :)
