### ISSUE TITLE
HttpTrigger timed out when uploading file with 5mb size or larger

### ISSUE THREAD

**Issue by edmundtkl** [Azure/azure-functions-dotnet-worker#515]
I'm using Postman to make a post request to the function with a file of 5mb size in the form-data. The console show executing until it hit the timed out error with the message initializing cancellation after 30 minutes. The break point in the code were never hit.

**Comment by fabiocav** [comment]
Can you verify the version Core Tools and .NET Worker references you were using when you ran into this? Thanks!

**Comment by edmundtkl** [comment]
We have contacted Microsoft support and they have identified the issue is due to the grpc message length. 

https://github.com/Azure/azure-functions-dotnet-worker/commit/704de76b5693bc24bdf6a9836ba8a109517c6a41

Thanks.
