### ISSUE TITLE
Worker SDK's tooling suffix property needs to be dependent on TFM

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#517]
Instead of setting [this](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/sdk/Sdk/Targets/Microsoft.Azure.Functions.Worker.Sdk.props#L160) to `net5-isolated` for all versions, we need to make `FunctionsToolingSuffix` property dependent on target framework to reflect the right value (eg- "net6-isolated" for net6.0).

cc: @phil-allen-msft

**Comment by fabiocav** [comment]
Moving this to 110 for completion
