### ISSUE TITLE
fix docker template in core tools

### ISSUE THREAD

**Issue by madhugilla** [Azure/azure-functions-dotnet-worker#519]
Hi,

we are planning to use .net 5 isolated worker function runtime in a docker container, is this supported oob ?  if yes can you please point to any documentation/howtos ?

Thanks -GM

**Comment by madhugilla** [comment]
Hi @brettsam, 

our design depends on this decision, when you get a moment can you please respond ?

Thanks -GM

**Comment by brettsam** [comment]
@ankitkumarr -- is our docker file template incorrect? https://github.com/Azure/azure-functions-core-tools/blob/v3.x/src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnetIsolated. I do believe that 3.1 is required to build, and I know for the v4 preview I had to include things like: https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/StaticResources/Dockerfile.dotnet#L3-L4

@madhugilla -- can you try adding those two lines and trying again?

**Comment by madhugilla** [comment]
@brettsam  that did the trick. thank you,

**Comment by brettsam** [comment]
Going to leave this open as we need to fix it in our template. But the workaround above should work for anyone else running into this.

**Comment by Michael-D-Pine-dorsavi** [comment]
Just going to jump in here as I am looking to containerize a .net5 isolated function that is pretty ready to go, the docker build is a little bit confusing as I must admit I am no docker expert.

From the samples I have seen the confusing bit is what CMD or ENTRYPOINT do I need to put in, do I still do a restore if I need packages pulled down in the usual location ?

I have nuget packages and I know previously how to configure NuGet with a PAT as a build argument.

I'm a little unsure as how to finish the Docker file i.e CMD or ENTRYPOINT.

**Comment by Michael-D-Pine** [comment]
Wait sorry let me get this straight you can't use .Net 5 isolated on a linux docker image ?

So if I have a .Net 5 function isolated it just has to be deployed to a Function without using docker ?

**Comment by fabiocav** [comment]
Fixed by https://github.com/Azure/azure-functions-core-tools/pull/2687
