### ISSUE TITLE
.NET 5 Isolated HttpTrigger Path Variable Binding

### ISSUE THREAD

**Issue by dasbdavis** [Azure/azure-functions-dotnet-worker#521]
Hello, just trying to figure out how to do something in .NET 5 that worked in 3.1 and before.

**In 3.1, the variable in the route binds correctly to the Guid parameter of the same name:**
```
[FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "records/{clientId:Guid}")] HttpRequest req,
            Guid clientId,
            ILogger log)
        {
            return new OkObjectResult(clientId);
        }
```

**In .NET 5, this fails:**
```
[Function("Function1")]
        public static HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", Route = "records/{clientId:Guid}")] HttpRequestData req,
            Guid clientId,
            FunctionContext executionContext)
        {
            var response = req.CreateResponse(HttpStatusCode.OK);
            response.WriteString(clientId.ToString());
            return response;
        }
```
The error that is thrown is as follows:

> Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'Function1': Cannot convert input parameter 'clientId' to type 'System.Guid' from type 'System.String'.

I can change the type of the parameter to string and then parse it into a Guid after the fact, of course, but I'd like to know if it's still possible to do it this way.

Thanks!

**Comment by fabiocav** [comment]
This is a limitation at the moment, but something we'll flag as an enhancement request.

**Comment by martijnlentink** [comment]
I'm also running into this issue. One solution would be exposing `IConverter` interface as public such that others will be able to create converters of their own.

**Comment by fabiocav** [comment]
Assigning to sprint 107 as a stretch goal.

**Comment by tyson-benson** [comment]
This would be very useful, I was also thinking about how to support case-insensitive string to enum converter for path parameters that map to enum types.
