### ISSUE TITLE
Azure Functions in class library triggers error: MSB4113: Specified condition "$(SelfContained)" evaluates to "" instead of a boolean.

### ISSUE THREAD

**Issue by ThomasBleijendaal** [Azure/azure-functions-dotnet-worker#522]
I'm running into an issue where the Microsoft.Azure.Functions.Worker.Sdk (Microsoft.Azure.Functions.Worker.Sdk.targets) throws an error when building an Azure Functions class library. I've found a work around which is to make the class library also a console application, but that will be confusing.

To reproduce:

Create a class library that has the following references:

```
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
```

Also create an Azure Function application that references that class library next to the references stated above.

If the class library is setup with `<OutputType>Library</OutputType>` the error "MSB4113: Specified condition "$(SelfContained)" evaluates to "" instead of a boolean." is thrown during build. If the package `Microsoft.Azure.Functions.Worker.Sdk` is removed, the error is not thrown anymore, but the functions in the class library are not recognized anymore by the Azure Functions application.

If the output type of the class library is set to `<OutputType>Exe</OutputType>` and still used as a class library, the projects build and the Azure Function application recognizes the class library functions and everything works.

**Comment by fabiocav** [comment]
Do you still have the same issue if you don't reference the SDK package? That shouldn't be needed for a class library (you only need that for the application that references the library, i.e. the worker)

**Comment by ThomasBleijendaal** [comment]
When I tried that the first time the function worker stated that no functions were found. I've tried it again and it has no problem recognizing the functions in the class library. So that's good.

I was updating my setup from a preview version to the 1.3.0 release, so I think I still had some other issues that I fixed along the way. Thanks for the reply and I'll be closing this issue.
