### ISSUE TITLE
EventHub event as binary

### ISSUE THREAD

**Issue by Peter-Juhasz** [Azure/azure-functions-dotnet-worker#525]
If only `string` representation is supported for Event Hubs, how can we access the message body as binary?

**Comment by smokedlinq** [comment]
Also you can't get the EventData class as a binding which means you don't have visibility to the event properties.

**Comment by Peter-Juhasz** [comment]
Do you guys have any update on this one with the new .NET 6/Functions Runtime 4 release? Thanks.

**Comment by pihai** [comment]
I just changed the type of the input binding to `byte[][] inputs` and it seems to work just fine.

However, the migration story from EventData is terrible. Would have expected a smoother transition.

**Comment by benjamin-brady** [comment]
The documentation for in-process dotnet functions is missing an example for processing binary messages. The Azure documentation should have an example of a `byte[][]` parameter example on this page: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=isolated-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#example

**Comment by xaviergxf** [comment]
How about the message key as binary?
Please Az Function team, don't forget about other types of serialization and high-performance scenarios (span, etc) that this approach does not allow.

**Comment by liliankasem** [comment]
You should be able to bind an EventHub trigger to `string`, `bytes[]` and `BinaryData`; we also recently added support for `EventData` ([release](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/eventhubs-extension-5.5.0)).

Updated docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cisolated-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#usage

If there are any issues binding to these types or if there are any feature requests, please open a new GitHub issue so we can properly triage. Would like to avoid having 1 issue to track multiple topics. Thanks!
