### ISSUE TITLE
Fix Functions Host's "/function" APIs and "sync triggers"

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#53]
All ARM calls related to "/function(s)" API are missing binding information for .NET 5 worker. These API uses the payload created by the Functions Host during a sync triggers call.

When a sync triggers call is made, Functions Host somewhat relies on the physical `function.json` files to create the config portion of the request. This causes binding information to be missing in Functions that come outside of `function.json`. [Here's the code](https://github.com/Azure/azure-functions-host/blob/88bc4d6c7578f86bf4e14d017484f91a9c1d5f47/src/WebJobs.Script.WebHost/Extensions/FunctionMetadataExtensions.cs#L36) that relies on `function.json`.

We need to decouple the call from the physical file and use the `FunctionMetadata`. All this work needs to happen in the Functions Host, but tracking here because they are crucial for .NET 5 support.

**Comment by fabiocav** [comment]
Closed as resolved.
