### ISSUE TITLE
Options Builder Extension doesn't appear to work

### ISSUE THREAD

**Issue by mrsquish** [Azure/azure-functions-dotnet-worker#531]
Hi there, I'm trying to use the services.AddOptions extension method to register typed configuration, but it would appear not to register the type. I get missing dependency errors when trying to resolve services where that configuration is injected. 

```
// This doesn't appear to work
services.AddOptions<MessageConfiguration>()
  .Configure<IConfiguration>((settings, configuration) =>
  {
      configuration.GetSection(nameof(MessageConfiguration)).Bind(settings);
  });
```
            
```
// This does work
services.AddSingleton<MessageConfiguration>(provider =>
{
    var messageConfig = new MessageConfiguration();
    var config = (IConfiguration) provider.GetService(typeof(IConfiguration));
    var section = config.GetSection(nameof(MessageConfiguration));
    section.Bind(messageConfig);
    return messageConfig;
});

```

**Comment by ErikPhilips** [comment]
It seems like the configuration from `AddOptions().Configure` isn't the same as `context.Configuration`. 

I've registered my configurations as:

```
var host = new HostBuilder()
  .ConfigureFunctionsWorkerDefaults((ctx, ab) =>
  {
    var config = ctx.Configuration;
    var section = config.GetSection("whatever");

    ab.Services.Configure<MyConfigurationClass>(section);
    ....
```

`Configure<>()` runs `AddOptions()` automatically..

Configure from Microsoft.Extensions.Options

**Comment by mrsquish** [comment]
Hey Erik, 

Thanks mate, I'll give that a shot.

**Comment by mrsquish** [comment]
Hey Eric, and all. Sorry my bad, I didn't realise I needed to inject IOptions<T> instead of T.
