### ISSUE TITLE
EventGrid output binding: sending multiple events exceeds maximum size

### ISSUE THREAD

**Issue by davidgruar** [Azure/azure-functions-dotnet-worker#538]
When using the EventGrid output binding and returning multiple events from a single function run, I have occasionally encountered the following error when the number of events is too high:

> Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:.
> Microsoft.Azure.EventGrid: The maximum size (1536000) has been exceeded.

If I was sending events programmatically I could send them in batches, but that option doesn't seem to be available when using output bindings in the isolated process model. It's not really feasible for me to split this function run into multiple runs that return a smaller number of events each. Is there any way round this issue?

**Comment by brettsam** [comment]
Can you share an example of how you're using the output binding? It seems as though the output binding should be taking care of this for you and we'd like to check it out.

Another alternative you always have is to use the EventGrid SDK directly from your function code, where you can control the batching yourself.

**Comment by davidgruar** [comment]
My function looks something like this:

```c#
[Function("GetData")]
[EventGridOutput(TopicEndpointUri = "EventGrid:Endpoint", TopicKeySetting = "EventGrid:TopicKey")]
public static async Task<IEnumerable<EventGridEvent>> RunAsync(
    // eventTrigger originally comes from a 3rd party service telling us that new data is available
    [QueueTrigger("eventqueue", Connection = "AzureWebJobsStorage")] DataUpdateEventTrigger eventTrigger,
    FunctionContext context)
{
    List<DataPoint> data = await GetDataFromService(eventTrigger);
    var events = data.Select(CreateEvent).ToList();
    return events;
}

private static EventGridEvent CreateEvent(DataPoint dataPoint)
{
    var id = Guid.NewGuid().ToString();
    var eventType = dataPoint.GetType().Name;
    return new EventGridEvent
    {
        Id = id,
        Subject = $"{dataPoint.TenantId}/{dataPoint.MemberId}/{eventType}/{dataPoint.Code}/{DateTime.UtcNow:yyyy-MM-dd}/{id}",
        EventType = eventType,
        DataVersion = "1",
        Data = dataPoint,
    };
}
```

**Comment by davidgruar** [comment]
I also made a minimal repro:

```c#
[Function("sendEvent")]
[EventGridOutput(TopicEndpointUri = "EventGrid:Endpoint", TopicKeySetting = "EventGrid:TopicKey")]
public static IEnumerable<EventGridEvent> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req, int eventCount, int stringLength)
{
    var eventGridEvents = Enumerable.Range(0, eventCount)
        .Select(i => new EventGridEvent
        {
            Subject = $"Test/{i}",
            EventType = "string",
            DataVersion = "1",
            Data = new string('a', stringLength)
        });

    return eventGridEvents;
}
```

This succeeds if I call `http://localhost:7071/api/sendEvent?eventCount=1024&stringLength=1291`, but fails if I increment either parameter by 1.

**Comment by brettsam** [comment]
And in the in-proc world, I assume that you call Add/Flush in order to create your batches? It does seem like the binding should be handling that internally, but it isn't today (https://github.com/Azure/azure-functions-eventgrid-extension/blob/dev/src/EventGridExtension/OutputBinding/EventGridAsyncCollector.cs#L40). I've filed https://github.com/Azure/azure-functions-eventgrid-extension/issues/94 to add that functionality.

To get the behavior you want for now, I think you'll need to use the EventGrid SDK directly: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid

**Comment by fabiocav** [comment]
Closing this as answered, but please let us know if you have any additional questions
