### ISSUE TITLE
Access remote ip address on HTTP triggered functions

### ISSUE THREAD

**Issue by pkenterlis** [Azure/azure-functions-dotnet-worker#539]
I have implemented many Azure Functions under .NET Core 3.1 and I want to migrate my entire codebase to .NET 5.0. 

Is there a way to access the remote client's IP address when running isolated process .NET 5 Azure Functions on a local docker image?

 The HttpRequestData object carries no such information. I suppose that when running on Azure, the remote address will be available through the X-Forwarded-For request header due to the presence of a proxy. 

Am I correct? Is the use of a proxy in any case the only way of getting the remote IP?

Thank you for your time.

**Comment by brettsam** [comment]
You should be able to use `X-Forwarded-For` -- see this issue for more info: https://github.com/Azure/azure-functions-dotnet-worker/issues/432.
