### ISSUE TITLE
ServiceBusTrigger IsBatched examples.

### ISSUE THREAD

**Issue by walkerrandolphsmith** [Azure/azure-functions-dotnet-worker#540]
I am trying to leverage the [IsBatched](https://github.com/Azure/azure-functions-dotnet-worker/blob/3e65d91314fc0920349ecd5eaadc36162be868f3/extensions/Worker.Extensions.ServiceBus/ServiceBusTriggerAttribute.cs#L76) configuration of the Service Bus Trigger Attribute. I am not seeing batches of messages and am struggling to know where I have failed.

```cs
[Function("MyFunction")]
public static void Run(
    [ServiceBusTrigger("queueName", Connection = "connection", IsSessionsEnabled = true, IsBatched = true)]
    string messages
) {}
````

I reviewed open and closed issues and saw issue https://github.com/Azure/azure-functions-dotnet-worker/issues/455 which seems potentially related.

Should I expect to be able to receive multiple message  from the service bus trigger?

Thanks,

**Comment by brettsam** [comment]
Try using `IEnumerable<string>` as a parameter to your function. I believe that should work for batching.

**Comment by walkerrandolphsmith** [comment]
I realize now my code block in the original post should have read `string[] messages`. However, using both `IEnumerable<string> messages` and `string[] messages` work as expected. I am unsure what other factors may have changed in my experiment. Thanks for taking the time to review this!

**Comment by razzkoirala** [comment]
Hello Smith, 

Can you share your azure function code in git? Please share your working code. 
I am very new to azure functions and service bus and I am struggling to figure out how Azure function will be triggered by Service Bus Queue and pick up the batch message.

**Comment by fabiocav** [comment]
Closing this as answered. 

@razzkoirala if you have questions or issues, please feel free to open a new issue with the details and we can follow up there.
