### ISSUE TITLE
Integrations tests in .net core 5

### ISSUE THREAD

**Issue by PaulWattsHgem** [Azure/azure-functions-dotnet-worker#541]
I built an http triggered Azure function using .net core 2.2 and was able to write integration tests and all worked great

I am migrating to .net core 5 and its a massive pain, I am trying to follow pattern in https://github.com/Azure/azure-functions-dotnet-worker/tree/main/test/E2ETests/E2ETests to create some tests

Would really appreciate some assistance with the following

1) I want to return and post multiple file stream(s) return req.CreateResponse(HttpStatusCode.OK); (seems to support Body, Cookies, Heads and response code)
2) I want to be able to change some of dependencies and hence use my own startup, I haven't found a way to do this. 
3) Also in the example it seems to want to install the Azure Functions Core Tool and the uses a CLI to run the test Azure function, concerned running this on a build/deployment server makes this complex.

**Comment by davidsteelebrady** [comment]
Hi @fabiocav, We are also experiencing the same issues described here by @PaulWattsHgem.  Is there any update or timeline when we could expect capabilities around IOC dependencies override?  I note issue #281 but seems to have gone cold.

**Comment by fabiocav** [comment]
@PaulWattsHgem adding some comments/questions:

1 - Can you expand on what you're trying to do? What is the actual scenario you're trying to validate?
2 - You have full control over the dependencies and the startup process, can you share more details on the dependencies you're trying to replace/override?
3 - For a full end-to-end test, our validation process does have a dependency on Core Tools and installs that as part of our build. For simpler integration tests, this wouldn't be a requirement depending on what you're trying to validate, but the tests you're looking at perform full end-to-end validation and uses the actual triggers, goring through the host.

@davidsteelebrady can you expand on the dependencies you're trying to override? The test framework work has not stopped, but a number of other features currently take precedence, so we don't have an ETA we can provide. That shouldn't block test scenarios, though, so I'm curious to better understand what you're running into.

Thanks!

**Comment by PaulWattsHgem** [comment]
I think that the key thing is that when doing any integration tests everywhere else in .net core it uses a standard pattern, whatever the hosting environment is.

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps

With this we get back everything we need..

And my first point, is to do with doing multiple file streams, this we did using MVC in .net core 2.2 which worked great. This doesn't now see possible.

**Comment by anthonychu** [comment]
@PaulWattsHgem Do you have a sample app in a repo that we can look at?
