### ISSUE TITLE
IAsyncCollector<T> usage when posting to output binding *during* processing

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-dotnet-worker#542]
We've got a use case where **as** the Function processes we want to be sending messages to the output binding. Previously, calling `AddAsync` on an `IAsyncCollector` at the point where we want to send the message did this work.

However, in the OOP model, I'm only seeing the capability to "send a batch" as part of Function **completion** ( #317 ) which isn't equivalent to what we had previously.

Is there a way to accomplish this in OOP? If not, do we have any guidance here?

**Comment by fabiocav** [comment]
There's no support for something like this with the OOP model today. This is the same limitation we have with other OOP languages as it is currently a host limitation. 

The only guidance we can provide at this point is to make direct use of the SDKs, but this is something we're tracking as a future enhancement in the host.

**Comment by fabiocav** [comment]
Closing as answered.
