### ISSUE TITLE
Missing Documentation?

### ISSUE THREAD

**Issue by stap123** [Azure/azure-functions-dotnet-worker#546]
With .NET 6 fast approaching and the plans to move to the isolated model from .NET 7 is there an ETA on docs relating to isolated being created and existing docs updated to include isolated examples? 

Currently trying to find anything official about the isolated model apart from [this](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) (which doesn't really cover everything in the same depth as the in-proc one) is very difficult and involves a lot of trial and error. 

We want to move to .NET 5/.NET 6 but upgrading functions is currently the biggest blocker due to needing to find out everything from scratch with a lot not readily available. It feels like there wasn't a concerted effort to update the docs with anything relating to the new model.

**Comment by fabiocav** [comment]
This has some details about the roadmap/plans: https://techcommunity.microsoft.com/t5/apps-on-azure/net-on-azure-functions-roadmap/ba-p/2197916

Preview, documentation and guidance  for .NET 6 should be landing very soon, but simply updating your target to .NET 6 and deploying should work today. You can follow the early guidance here: https://github.com/Azure/Azure-Functions/wiki/V4-early-preview
