### ISSUE TITLE
Need to fix AssemblyInformationalVersion

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#547]
Current releases have `AssemblyInformationalVersion` looking like:  `1.3.0-local Commit hash: N/A+fd673155eca2c7654ea69c61e4fa8ee862cda1a8`. The `local` and `N/A` should not be there.

**Comment by soninaren** [comment]
@brettsam Can you add more information on how this is generated? Is there a specific build step or code path you could point to?

**Comment by brettsam** [comment]
I think that we need to pass the same `-p:BuildNumber=$(buildNumber) -p:CommitHash=$(Build.SourceVersion) -p:IsLocalBuild=False` arguments here:
- https://github.com/Azure/azure-functions-dotnet-worker/blob/main/azure-pipelines.yml#L223

To the build command here:
- https://github.com/Azure/azure-functions-dotnet-worker/blob/main/azure-pipelines.yml#L36
