### ISSUE TITLE
Need TelemetryConfiguration added to DI Services

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-dotnet-worker#549]
Current guidance for utilizing custom telemetry w/ AppInsights is to [get the `TelemetryConfiguration` object from the DI container and create a `TelemetryClient` instance from it](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions). However, currently we aren't adding the config to the DI container.

I've worked around this locally by putting the following in `Program.cs`

```csharp
public static void Main()
{
    var host = new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureServices(b =>
        {
            var appInsightsInstrumentationKey = Environment.GetEnvironmentVariable(@"APPINSIGHTS_INSTRUMENTATIONKEY");
            if (!string.IsNullOrWhiteSpace(appInsightsInstrumentationKey))
            {
                b.AddSingleton(new TelemetryConfiguration(appInsightsInstrumentationKey));
            }
        })
        .Build();

    host.Run();
}
```

but we should probably bake this in so docs still flow

**Comment by brandonh-msft** [comment]
Related: #350 , #308

**Comment by stap123** [comment]
We used to use `TelemetryClient` injected automatically via DI in .NET 3.1 functions. Is there a particular reason that this doesn't propose adding that back to the DI container as well? Is it a fundamentally different thing? (We have just upgraded and are now creating it ourselves using the `TelemtryConfiguration` as above in each function but it's additional duplicated code per function)

**Comment by brandonh-msft** [comment]
> We used to use `TelemetryClient` injected automatically via DI in .NET 3.1 functions. Is there a particular reason that this doesn't propose adding that back to the DI container as well? Is it a fundamentally different thing? (We have just upgraded and are now creating it ourselves using the `TelemtryConfiguration` as above in each function but it's additional duplicated code per function)

@stap123 in general for .net 3.1 you should be following [this guidance](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions). This issue is around that guidance not being possible in its current form due to the lack of `TelemetryConfiguration` in the DI container. You definitely shouldn't be re-creating TC every time a function launches.

**Comment by stap123** [comment]
Thank you for the clarification, we are doing that now anyway so all good 😃

**Comment by fabiocav** [comment]
Related to #619

**Comment by brettsam** [comment]
We don't want the worker to be tied to any one logging solution so I don't think we'll ever do this directly in the host. Ideally, supporting something like [`AddApplicationInsightsTelemetryWorkerService()`](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#using-application-insights-sdk-for-worker-services). This may "just work" well enough today -- we'll need to look through exactly what it does.

But we may have to introduce some similar API from a separate package that lets customers add this support to the worker (if the above API doesn't work as we'd like).

**Comment by brandonh-msft** [comment]
Totally fair as I know the ability to plumb in _other_ logging/telemetry solutions has been an ask for a while.
That said, though, if this won't be supported we need to make sure our docs are steering people this way, so updates are needed there at a minimum.

**Comment by oatsoda** [comment]
This documentation for Isolated Process functions needs updating:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services

"Don't register your own TelemetryConfiguration or TelemetryClient if you are using the built-in Application Insights functionality. If you need to configure your own TelemetryClient instance, create one via the injected TelemetryConfiguration as shown in [Log custom telemetry in C# functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2,cmd#log-custom-telemetry-in-c-functions)."

**Comment by brettsam** [comment]
I'm going to close this out as we've got a solution for Application Insights in the worker now (currently in preview) that minimally wraps the ApplicationInisghtsWorkerServiceTelemetry. All configuration, etc, should be exactly the same as any other console application using this package.
