### ISSUE TITLE
Restore using custom nuget.config for the worker host project

### ISSUE THREAD

**Issue by CameronAavik** [Azure/azure-functions-dotnet-worker#550]
When building a .NET worker functions project, the build will create a folder in the Temp directory and place in that folder WorkerExtensions.csproj which I believe is used to build the worker host project. Because this build is being done in a separate folder it won't use my preferred nuget package sources and will instead use the global nuget.config that is installed on the system.

It would be good if instead that the build could be forced to use the same nuget.config that the functions project is using so we can have full control over where the packages being installed are coming from. This will also help make it easier when writing custom bindings and ensuring that the local folder that contains the nuget package is being used when restoring the worker host project.

In the meantime I am working around this by adding a CI build step which edits the global nuget.config to my desired packages sources, but I believe this should really be addressed here so everyone doesn't need to make the same workarounds.

**Comment by cgillum** [comment]
+1, running into this issue as well, which makes it harder for extension authors to provide users with nuget package dependencies that aren't hosted on nuget.org (FYI @anthonychu and @fabiocav)

**Comment by jviau** [comment]
#1749 moved the inner-build to be in the intermediate output directory. This is not yet released, but it will address it when it is released.

**Comment by Phiph** [comment]
Hey @jviau are you any closer for a release for this change  👍

**Comment by jviau** [comment]
Fix is released in https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0-preview3
