### ISSUE TITLE
Did not find any initialized language workers

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-dotnet-worker#559]
Hello

I'm having this issue, in an Azure Function App (Consumption plan), Linux Environment.

The error is thrown for HTTP Azure functions.

TargetFramework : .Net 5
Language : dotnet-isolated
AzureFunctionsVersion V3
Microsoft.Azure.Functions.Worker.Extensions.Http Version="3.0.13"
Microsoft.Azure.Functions.Worker.Sdk Version="1.0.3

The same deploy works in a Windows Environment, as well as locally, in my machine.

I've seen several issues about this topic but could not find any final solution.

Could you give me a hint to fix the problem?

Thanks.

**Comment by bojanmisic** [comment]
Same as #556.

**Comment by brettsam** [comment]
Closing as a duplicate of #556
