### ISSUE TITLE
No errors reported when functions fail to start

### ISSUE THREAD

**Issue by Mithras** [Azure/azure-functions-dotnet-worker#560]
Some context: I'm trying to containerize Functions to run them in Kubernetes. I'm using `mcr.microsoft.com/azure-functions/dotnet-isolated:3.1.3-dotnet-isolated5.0-slim` image to do so.
The problem is our Functions have dependency on ASP.NET Core Runtime which is not installed in the image. And it wouldn't be a big deal if I got a clear error message what exactly is missing. I wasted like half a day trying to figure it out and after adding
![image](https://user-images.githubusercontent.com/2098029/127693264-e2edec6d-520e-491c-ad32-d32d2a6729ce.png)
finally made it work.

**Expected behavior** 
When user code fails to start for whatever reason (e.g. missing ASP.NET Core Runtime) show/throw exception to make it clear what's wrong.

**Actual behavior** 
No errors is thrown, no reason is given. Process just hangs for 5 minutes and when shuts down with "Did not find any initialized language workers" exception.

**Repo steps**
1. `func init MyFunctionProj --docker --worker-runtime dotnetIsolated`
2. Add any Nuget package that depends on ASP.NET Core Runtime (e.g. `GraphQL.Server.Transports.AspNetCore.SystemTextJson`)
3. Try to run in container. It'll hang for 5 mins and exit with useless "Did not find any initialized language workers" error.

**Comment by kshyju** [comment]
net6 images and later has Microsoft.AspNetCore.App shared framework included. .NET5 is out of support. So this won't be fixed for net5. Please let us know if you run into issues with the latest stable version of images.
