### ISSUE TITLE
Isolated functions on linux consumption slow 

### ISSUE THREAD

**Issue by assaf-grth** [Azure/azure-functions-dotnet-worker#563]
Executing an isolated function on a linux consumption based app, as recommended at the [known issues](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Known-issues) article doesn't seem to improve performance,

When using windows consumption plan with response times of up to a minute, we got to response times of 2-4 minutes on the linux.

Are there any recommendations on how to troubleshoot such behavior?

**Comment by balag0** [comment]
could you share the app name using 
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2

**Comment by assaf-grth** [comment]
Unfortunately I can't get customer's approval to share the function details so far
In case I get them I will send an update here
