### ISSUE TITLE
Check for .NET Core 3.1 SDK before generating WorkerExtensions.csproj

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-dotnet-worker#564]
Currently the build fails when .NET Core 3.1 SDK is not installed, but it’s not clear to the user how to fix it. It might be better to fail with a meaningful error message before/while generating the extensions csproj file.

**Comment by bagrupe** [comment]
When running "func init --worker-runtime dotnetIsolated --docker-only" in my function project, the following Dockerfile is created:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0-appservice
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```

This will fail due to the problem you described, it tries to build the worker extensions with 3.1 after building the app with 5.0:

`/root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/gy35gmou.bur/WorkerExtensions.csproj]`

I didn't find any quick solution for this. I don't see official MSFT docker images including both 3.1 and 5.0.

Are there any workarounds available to enable building with Docker directly?

**Comment by JeroenvdBurg** [comment]
might it not be better to remove the dependency on .NET core 3.1 SDK ?

**Comment by anthonychu** [comment]
If you are building a v4 .NET 6 app, you don’t need .NET Core 3.1.

v3 (.NET 5 isolated) apps still require .NET Core 3.1.

**Comment by JeroenvdBurg** [comment]
@anthonychu  thnx for the reply.  Great to hear that the required 3.1 dependency is not needed anymore for .NET 6 function apps. When building a v4 .NET 6 function app (isolated) my devops pipeline still gives the error it needs 3.1

 FunctionApp3 -> /home/vsts/work/1/s/publish_output/FunctionApp3.dll
  Determining projects to restore...
  Restored /tmp/z0qlojya.fid/WorkerExtensions.csproj (in 7.96 sec).
  WorkerExtensions -> /tmp/z0qlojya.fid/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
##[error]/home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error : It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (x64) was not found.

Am I doing something wrong? I have made the devops project public: https://dev.azure.com/signatoryrocket/Azure%20Functions%20DotNet%206/_build

**Comment by anthonychu** [comment]
Update this and other dependencies in your app to the latest: https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.0.1

**Comment by esimkowitz** [comment]
@anthonychu I am still seeing this issue with Microsoft.Azure.Functions.Worker.Sdk version 1.3.0, could it be an issue with the Microsoft.Azure.Functions.Worker.Extensions.Http package? I see that this package is 7 months old, has it been updated to .NET 6?

**Comment by jviau** [comment]
Going to close this as netcoreapp3.1 is out of support.
