### ISSUE TITLE
Dockerized .NET 5 (dotnet-isolated) function does not run when triggered

### ISSUE THREAD

**Issue by nachiappannk** [Azure/azure-functions-dotnet-worker#568]
- .NET 5 (dotnet-isolated) function with Http Trigger (and Service Bus also) when dockerized and deployed Azure, the function is not run when triggered.
 - The issue is observed when using `Microsoft.Azure.Functions.Worker` version `1.4.0`
 - The issue is resolved when downgrading the package `Microsoft.Azure.Functions.Worker` version `1.0.0`

# Steps to reproduce the issue
### Prerequisites
 - Azure Cli is installed
 - Docker is installed
 - Docker Login is completed to a public registry (docker login)
 - Azure cli login is completed (az login)
 - Adjust the names to avoid conflict in the below commands
 - Clone the repository https://github.com/nachiappannk/azure-function-bug

### Run the below commands from root of repo after logging in to azure (az login) and docker (docker login)
 - `docker build -t nachiappan/function-issue-demo:bug .`
 - `docker push nachiappan/function-issue-demo:bug`
 - `az group create --name NachiFuncDemo --location westeurope`
 - `az storage account create --name nachistoragedemoforfunc --location westeurope --resource-group NachiFuncDemo --sku Standard_LRS`
 - `az functionapp plan create -g NachiFuncDemo -n FunctionAppPlan --sku EP1 --is-linux true`
 - `az functionapp create --name nachifunctionissuedemo --storage-account nachistoragedemoforfunc --resource-group NachiFuncDemo -p FunctionAppPlan --functions-version 3 --runtime dotnet-isolated  --deployment-container-image-name docker.io/nachiappan/function-issue-demo:bug`
 
### Reach the URL
 - Hit the url in a browser `https://nachifunctionissuedemo.azurewebsites.net/api/HttpTriggeredFunction?`
 
 
# Expected
 - The page loads with message "Welcome to Azure Functions!"
 
# Actual
 - The page does not load
 
# Work around
 - In the file `func-tool-bug.csproj` downgrade the version of `Microsoft.Azure.Functions.Worker` to `1.0.0`
 - docker build with `docker build -t nachiappan/function-issue-demo:nobug .`
 - docker push with `docker push nachiappan/function-issue-demo:nobug`
 - update the docker image with `az functionapp create --name nachifunctionissuedemo --storage-account nachistoragedemoforfunc --resource-group NachiFuncDemo -p FunctionAppPlan --functions-version 3 --runtime dotnet-isolated  --deployment-container-image-name docker.io/nachiappan/function-issue-demo:nobug`
 
# Other Observation
 - Functions build with 1.4.0 of Microsoft.Azure.Functions.Worker
   - works with locally running docker
   - works deploying to azure with out docker
   - works locally running as a console application
   - DOES NOT WORK when dockerized and deployed to azure function
 - [Kudu logs](https://github.com/nachiappannk/azure-function-bug/blob/master/log.PNG) indicate there is a problem with HTTP protocol when trying to make a GRPC call
 
![log](https://user-images.githubusercontent.com/25709644/128562202-471bdc99-e63e-43a7-a922-df4000d5e906.PNG)

**Comment by brettsam** [comment]
I believe you're hitting the same issue as https://github.com/Azure/azure-functions-dotnet-worker/issues/524. Can you try the workaround there and see if that fixes it?
