### ISSUE TITLE
Need HttpContext in Http Trigger

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-functions-dotnet-worker#572]
Hi

I need to access the HttpContext for HttpTriggers in both middleware and services, i know there is a hackie work around to access the HttpRequest and respone in middleware, but it makes it really difficult in services.

(I primarily need to access headers and cookies at present)

Is there an plans for the HttpContextAccessor to be introduced?and possible eta?

**Comment by EnenDaveyBoy** [comment]
i have no idea what that means in regards to my issue

**Comment by MikesGlitch** [comment]
I'm in a similar situation to the OP.  

Should we be able to access HttpContext via IHttpContextAccessor in functions .net 5?  

I'm in the middle of upgrading and I can't seem to access it.  I have some sample code in a repo here:

https://github.com/MikesGlitch/azure-functions-dotnet5-http-context-accessor/blob/master/HttpContextAccessor/Function1.cs

I'm just accessing it as I would normally - it stopped working when I upgraded.

I don't really know what to do here, we use it in conjunction with MediatR pipeline behaviours so we need to be able to inject it somehow.

**Comment by StefanSchoof** [comment]
I would also welcome any info, if this is something that should be possible or something I need to start to refactor my code, to no longer depend on ´IHttpContextAccessor`.

**Comment by EnenDaveyBoy** [comment]
i have work my problem out in a different way, but it would be easier if I could inject HttpRequestData into my other services,I can't find any documentation to be able to do it,and I have a null exception in my constructors.

**Comment by anthonychu** [comment]
This needs some discussion. Potentially can expose a way to access the functions context, including http request where applicable.

**Comment by EnenDaveyBoy** [comment]
exposing the functions context would be one option, but it would also mean that my services are then hard coded to Azure functions, and would dilute them with services they don't need.

I can access ILogger without issue using dependency injection, it seems odd I can't access the http request class in a http request, when its clearly been accessable iin other applications like MVC.

**Comment by vzalamea** [comment]
Just found this issue while trying to convert my in-process Http trigger Functions app to isolated so I can add middleware.  It would be nice to .AddHttpContextAccessor() in ConfigureServices.

**Comment by CarlosGomesMarel** [comment]
I need a way to a **route parameter value** from within a **configured service**.  I was using the `IHttpContextAccessor.HttpContext` however that is null in .net 6.  Is there an alternative?  I looked into the middleware approach, but I don't see how I can access the `FunctionContext` from within a service after the middleware runs.

**Comment by EnenDaveyBoy** [comment]
one options is use a scoped service, set the parameter using middleware into the service, then you'll have it in the service, or use a context class in the same way.

**Comment by CarlosGomesMarel** [comment]
Hot familiar with this approach can you point me on an example of a scope service using parameter set by middleware

**Comment by EnenDaveyBoy** [comment]
in your program.cs file add a dependency

///
s.AddScoped<IMyService, MyService>();
///

then build your middleware

///
public class MyServiceMiddleware : IFunctionsWorkerMiddleware
    {
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
           HttpRequestData httpRequest = context.GetHttpRequestData();

            var myService= context.InstanceServices.GetService(typeof(IMyService)) as IMyService;
            var urlParam = httpRequest.Url.SomeExtensionTothePartRequired()

            myService.AddUrlPAram(urlParam)

      
            await next(context);


        }
    }
///

then add the middle way to the program.cs

///
builder.UseMiddleware<MyServiceMiddleware>();
///

Sorry for the really bad example but hopefully you can figure it out from there

**Comment by CarlosGomesMarel** [comment]
Thanks, got it.

```
.ConfigureFunctionsWorkerDefaults(worker =>
    {
        worker.UseMiddleware<FunctionContextMiddleware>();
    })


services.AddScoped<ParameterProvider>();

// Classes

public class FunctionContextMiddleware : IFunctionsWorkerMiddleware
{
    public FunctionContextMiddleware()
    {
    }

    public Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        var provider = context.InstanceServices.GetService(typeof(ParameterProvider));
        if (provider is ParameterProvider parameterProvider)
        {
            var bindingData = context.BindingContext?.BindingData;
            if (bindingData == null)
            {
                return null;
            }

            parameterProvider.BindingData = bindingData;
        }

        return next(context);
    }
}


public class ParameterProvider
{
    public ParameterProvider()
    {
    }

    public IReadOnlyDictionary<string, object> BindingData { get; set; }

    public string GetParameterValue(string parameterName)
    {
        if (this.BindingData == null)
        {
            return null;
        }

        if (this.BindingData.TryGetValue(parameterName, out var parameterValue))
        {
            var urlParameterValue = parameterValue as string;
            return urlParameterValue;
        }

        return null;
    }
}

```

**Comment by kshyju** [comment]
@EnenDaveyBoy 

You can use the `GetHttpRequestDataAsync` extension method to get the `HttpRequestData` instance, from which you can access cookies and headers. This API is available from [Version 1.8.0-preview1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) onwards.

````
HttpRequestData requestData = await functionContext.GetHttpRequestDataAsync();
````

Please refer the ` StampHttpHeaderMiddleware` middleware in the[ sample app](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/StampHttpHeaderMiddleware.cs#L15) for usage of this API in a middleware.

Thanks for your patience. Please let us know if you have questions.

**Comment by EnenDaveyBoy** [comment]
Interesting thanks for the information, I will look into it soon.

However when is this likely to come out of preview?

**Comment by kshyju** [comment]
The package should be out of preview in the next few weeks. This gives us enough time to consider the feedback from users about the preview version.

**Comment by kshyju** [comment]
Closing as answered.
