### ISSUE TITLE
Storage queue message encoding support

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-functions-dotnet-worker#576]
How can we enable the newer extensions support on the host? For instance the latest Microsoft.Azure.WebJobs.Extensions.Storage.Queues beta provides support for queue messages that don't use the base64 string encoding, such as queue messages from Azure Event Grid.

I'm looking to get this same setup / support in the isolated worker but so far, adding the package and modifying the host.json as was required in netcoreapp3.1 isn't working. I'm using the latest dotnet worker packages:

`<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />`
`<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />`
`<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.4.0" />`
    

Repo steps:

1. Add package reference: `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.0.0-beta.5" />`
2. Set host.json `extensions.queues.messageEncoding` property to `none`
3. Use a `QueueTrigger` against the storage queue and append string content from Storage Explorer as `String` encoding instead of the `Base64` encoding.

Error:

`System.Private.CoreLib: Exception while executing function: Functions.ProcessStorageQueueMessage. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'message'. System.Private.CoreLib: 
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

**Comment by brettsam** [comment]
Can you try to use the `Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues` package? It looks like right now you're referencing the WebJobs one...

**Comment by smokedlinq** [comment]
@brettsam had to upgrade the `Microsoft.Azure.Functions.Worker.Extensions.Storage` to 5.0.0-beta.4 ... and that appears to work... the 4.0.4 version does not.

**Comment by brettsam** [comment]
Great!
