### ISSUE TITLE
dotnet worker on linux consumption apps not starting (Central US outage)

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#579]
I have an open ticket with Microsoft support ( 2108140040000370 ) over this ongoing issue (has been happening since Saturday 8am central on CentralUS at least), but I just wanted to try to raise this here, since I literally just followed the instructions pasted in your README with a brand new 'func init'ed function and reproduced with only a single function of my own code added to the func init C# dotnet-worker template;

Steps:
1. func init a new C# dotnet-worker application
2. Add Healthcheck.cs with this content:
```C#
using System;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;

namespace C2C.Functions
{
    public class Healthcheck
    {
        [Function("Healthcheck")]
        public async Task<HttpResponseData> OnHttpGet(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData req)
        {
            var result = new
            {
                Built = "Now",
                Notifications = false
            };

            var response = req.CreateResponse(System.Net.HttpStatusCode.OK);
            await response.WriteAsJsonAsync(result);
            return response;
        }
    }
}
```
3. Follow steps from readme:
```sh
az group create --name my-test-func --location centralus
az storage account create --name mytestfuncx --location centralus -g my-test-func --sku Standard_LRS
az functionapp create -g my-test-func --consumption-plan-location centralus --runtime dotnet-isolated --functions-version 3 --name my-test-funcx --storage-account mytestfuncx --os-type Linux 

# Deploy
func azure functionapp publish my-test-funcx
```

4. Navigate to link outputted by the func azure functionapp publish:
```sh
Syncing triggers...
Functions in my-test-funcx:
    Healthcheck - [HttpTrigger]
        Invoke url: https://my-test-funcx.azurewebsites.net/api/healthcheck
```

URL simply spins for 5 minutes before timing out
![image](https://user-images.githubusercontent.com/969938/129741482-26520a05-7537-4195-bb6e-8189fb5bd665.png)

![image](https://user-images.githubusercontent.com/969938/129742396-1b4e8f26-a55b-4586-ae1b-affd8302f365.png)

![image](https://user-images.githubusercontent.com/969938/129742544-8396b5d5-0dbf-4da3-9446-0bfc35f5390c.png)

This suddenly started happening on Saturday morning on my production instance, and I opened a support ticket but the support techs dont appear to have any clue. I haven't seen much movement from them in the past few days. I have since moved my code to a premium azure function instance and it works fine there, but all my non-production environments are still out due to this issue (on Central US anyway).

# NOTE

I JUST tested this on East US (RG, storage, and Function), and it works perfectly. This is an **OUTAGE** as I have been trying to tell the support techs for days.

**Comment by kzryzstof** [comment]
I have a similar issue but my Function Apps are deployed in Canada East. Is it possible that the outage affects more than Central US?

**Comment by onionhammer** [comment]
@kzryzstof completely possible, I only tested 2 regions

**Comment by kzryzstof** [comment]
@onionhammer Should we expect to see something on the [Azure Status page](https://status.azure.com/en-us/status)?

**Comment by onionhammer** [comment]
@kzryzstof It seems to me that Azure Functions is missing some service-level tooling/health checks; Microsoft appears to be completely unaware of this outage (their tech support is occupied trying to gaslight me into thinking its an issue on my end).

The outage not only needs to be fixed, they need an RCA on WHY they arent aware of these outages.

**Comment by kzryzstof** [comment]
Looks like it is working again: no changes happened over night on my side.

**Comment by balag0** [comment]
Looking at the logs for my-test-funcx, the region had a deployment in the last day which could explain the recovery.
As for the underlying issue, @yojagad could dotnet isolated apps also be impacted by https://github.com/Azure/azure-functions-host/issues/7590 (Did not find any initialized language workers)

**Comment by yojagad** [comment]
> Looking at the logs for my-test-funcx, the region had a deployment in the last day which could explain the recovery.
> As for the underlying issue, @yojagad could dotnet isolated apps also be impacted by [Azure/azure-functions-host#7590](https://github.com/Azure/azure-functions-host/issues/7590) (Did not find any initialized language workers)

This issue is a little different.. dotnet worker seems to have exited with the below error

```
Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : dotnet exited with code 150
```

The current runtime's behavior is generally to accept one request before throwing `Did not find any initialized language workers` and then shutting down (which is happening in the case of `my-test-funcx`). In the other issues, the runtime wouldn't shut down and would keep accepting invocations and throwing the error (`Did not find any initialized language workers`).

I think the main thing to focus on here is to find out why the above `WorkerProcessExitException` happened.

**Comment by onionhammer** [comment]
According to Azure support, this is related to #7469

**Comment by balag0** [comment]
@onionhammer Thanks for the update. The fix for the linked issue should be deployed now. Are you still seeing these issues?

**Comment by onionhammer** [comment]
@balag0 Not actively, the larger issue here is having to convince azure support that there was an outage in the first place - none of your tooling indicated there was a regional outage

**Comment by balag0** [comment]
Got it. Looks like the issue was specific to the state of the function apps which are always tricky since it is not clear if there is an issue with the config or platform.

**Comment by brettsam** [comment]
Closing as it looks like it is related to an issue in the host (https://github.com/Azure/azure-functions-host/pull/7469).
