### ISSUE TITLE
HTTP trigger binding data only has first query parameter keyed

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-functions-dotnet-worker#580]
@fabiocav, per your suggestion in https://github.com/Azure/azure-functions-dotnet-worker/issues/362#issuecomment-807960346:

> context.BindingContext.BindingData["myquery"]; // direct access to the dictionary.

it seems to only key the first query parameter in the url:

![image](https://user-images.githubusercontent.com/2124254/129770411-834b4ff0-a25b-472f-950b-a8e4f305a9ec.png)

Is it designed to only key the first query parameter? If yes, please close this issue.

**Comment by kshyju** [comment]
BindingData dictionary will have entries for all the query parameters from the request URL.  Here is a screenshot of `BindingData ` dictionary content for my request URL `/api/hello?lastname=Watts&state=WA&zip=98052` which has 3 query parameters.

![binding-context-values](https://user-images.githubusercontent.com/144469/129835417-2d4650c1-6b6b-478c-9be8-ec75155a240a.PNG)

Can you share the request URL you tried where this behavior is not happening ?

**Comment by HMoen** [comment]
@kshyju , the URL with [code] query param truncated:

> http://localhost/api/auth/code?state=d874cc387a2c46b0939d7e9e68cbd93e&code=eyJraWQiOiI3SzVIeFUzc0ViTjBGR3dHLTBCMi03Q1huNmdYclBv... 

![image](https://user-images.githubusercontent.com/2124254/129922697-8414a3ce-b1ed-458a-a209-f9455111b5d6.png)

**Comment by kshyju** [comment]
@HMoen  Thanks for sharing the URL.

In the context of http trigger azure functions, the `code` query parameter has a special meaning. It is used for specifying an API key which is used for authorization. See the [API key authorization](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#api-key-authorization) section of the official documentation.

If you rename it to another name (ex: `apicode`), the binding will work and you will see it in the binding dictionary.
