### ISSUE TITLE
Apply equivalent of class Startup : FunctionsStartup with .NET 5 

### ISSUE THREAD

**Issue by Ofer-Gal** [Azure/azure-functions-dotnet-worker#585]
I am novice in  .NET 5 Azure functions
I created HTTP Azure function from the template and it starts from the Program.CS file.
Now I now want to use code from a sample that was written to use Core 3.1 using  Startup.CS

It is decorated with:`[assembly: FunctionsStartup(typeof(AceAzureFunctions.Startup))]`
and the class inherits from FunctionsStartup 
```
public class Startup : FunctionsStartup 
{
public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = builder.GetContext().Configuration;
            var azureFunctionSettings = new AzureFunctionSettings();
            config.Bind(azureFunctionSettings);

            builder.Services.AddPnPCore(options =>
            { //and so on
```
How should I implement the config in the .NET 5 project?
Thank you

**Comment by brettsam** [comment]
Hi @Ofer-Gal -- the `FunctionsStartup` class that we added for in-proc .NET functions is using the [.NET Core generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0) behind-the scenes.

You can use methods like `ConfigureAppConfiguration()` and `ConfigureServices()` on the `HostBuilder` in your `Program.cs` to do everything you can do (and more!) in a `FunctionsStartup`. We have some examples of registering services in the Samples section of this repo (for example -- https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/FunctionApp/Program.cs).

Let us know if there's anything specific that you're getting from `FunctionsStartup` that you need in the isolated worker.

**Comment by Ofer-Gal** [comment]
Got it! Thank you
