### ISSUE TITLE
Performance and cost impact

### ISSUE THREAD

**Issue by Terricide** [Azure/azure-functions-dotnet-worker#591]
I had an azure function that was inprocess running on dotnet 3.1. I upgraded to dotnet 5 and dotnet-isolated and performance dropped quite a bit and my cost went from a couple of dollars of a month to hundreds of dollars on the consumption plan.

Does this sound normal to anyone? I've since downgraded back and it's only been a day but the cost and performance looks like it back to normal.

**Comment by Terricide** [comment]
Yup it for sure looked like it fixed the issue.

![image](https://user-images.githubusercontent.com/1705108/130451851-85b0d978-c6be-4c6a-a766-51ddb7e83656.png)

**Comment by jedjohan** [comment]
Good find, was just about to start an upgrade of a 3.1 EventHubTrigger (that takes a lot of load) to 5.0 isolated, maybe I should just wait 😄

**Comment by brettsam** [comment]
@Terricide -- it's not expected that you'd see such a large change in cost when switching to the out-of-proc model. Do you have any kind of breakdown as to where these costs were coming from?

If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

**Comment by Terricide** [comment]
Is this enough information?

2021-08-24T22:57:13.360 [Information] Executing 'KeepAlive' (Reason='This function was programmatically called via the host APIs.', Id=58c58db1-e60b-44b9-a314-1a41880f4bbc)
2021-08-24T22:57:13.368 [Information] Executed 'KeepAlive' (Succeeded, Id=58c58db1-e60b-44b9-a314-1a41880f4bbc, Duration=154ms)

**Comment by Terricide** [comment]
The problem appeared mid-july after I did the change but I didn't notice it until the 20th and reverted back the 21st. I think it racked up $1,000 when previously it had only been a couple of bucks a month.

**Comment by brettsam** [comment]
Hi @Terricide -- I took a look at your logs and nothing jumped out at me as problematic from what I could see. I'd recommend filing a support ticket to see if we can do a deeper investigation with all of your details.

**Comment by fabiocav** [comment]
Closing as answered. @Terricide please follow up using a support channel so we can take a look at this specific issue, but if you need any assistance, please let us know.
