### ISSUE TITLE
Azure Function App Deploy task doesn't work with .NET 5 isolated process

### ISSUE THREAD

**Issue by stackboss** [Azure/azure-functions-dotnet-worker#595]
I am attempting to deploy an isolated process .NET 5 function app with a middleware wrapper using azure DevOps pipeline 'Azure Function App Deploy' task. Function deploys but does not run as an isolated process. If "FUNCTIONS_WORKER_RUNTIME" is set to "dotnet-isolated" it logs this error:

> Microsoft.Azure.WebJobs.Script: Did not find functions with language [dotnet-isolated].

If I set it to [dotnet] the function runs when triggered, but it does not run out-of-process (missing the middleware log statements).

If I deploy the function from my local az CLI with func tools it works:

`func azure functionapp publish nsm-eus-dev-fa-behive-functions`

When I trigger the function I see the middleware logging statements in the logs. However nothing I tried so far allows me to deploy the function as an isolated process via DevOps pipeline.

This is the task I am using:

![image](https://user-images.githubusercontent.com/53962814/130467457-22aa4aac-936d-422e-850e-e716a861b1cb.png)

And the code for the function setup:

```
public class Program
{
  public static void Main()
  {
	  var host = new HostBuilder()
		  .ConfigureFunctionsWorkerDefaults(builder =>
		  {
			  builder.UseMiddleware<LoggingMiddleware>();
		  }
	  )
	  .Build();
	  host.Run();
  }
}


public class LoggingMiddleware : IFunctionsWorkerMiddleware
{
	public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
	{
		var log = context.GetLogger<LoggingMiddleware>();
		try
		{
			log.LogInformation($"~~~{context.FunctionDefinition.Name}~~~{context.FunctionId}~~~");
			await next(context);
			log.LogInformation($"^^^{context.FunctionDefinition.Name}^^^{context.FunctionId}^^^");
		}
		catch (Exception ex)
		{
			log.LogError(ex, string.Empty);
		}
	}
}

[Function("MyFunctionName")]
public async Task MyFunction([ServiceBusTrigger("%MyTopicName%", "%MySubscriptionName%", Connection = "ServiceBus")] MyMessage msg)
{
	;
}
```

**Comment by brettsam** [comment]
@stackboss -- could you share your deployment config (can you get the yaml?) for this setup? We'll investigate whether dotnet-isolated needs any fixes here....
