### ISSUE TITLE
Testing HttpRequestData.Identities locally using valid bearer token throws exception

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-functions-dotnet-worker#596]
Looking at the [E2ETests](https://github.com/Azure/azure-functions-dotnet-worker/tree/ddeab28e520cd69a1b338b095683ede628e01570/test/E2ETests), I don't see any examples to test HttpRequestData.Identities with a HTTP trigger. 

Running local tests throws an exception at GrpcHttpRequestData.Identities due to id.AuthenticationType being null when a valid bearer token is provided:
![image](https://user-images.githubusercontent.com/2124254/130509825-35341ff3-6cac-4605-ba25-c2be2f6ca7b2.png)

What would be the appropriate way of testing locally? I can upload to Azure for EasyAuth testing which works fine, but was hoping for a local alternative.

**Comment by brettsam** [comment]
@HMoen -- can you share an repro for us? i.e. -- how are you making the request and what payload are you using?

**Comment by HMoen** [comment]
@brettsam , can't repro the exception in GrpcHttpRequestData.Identities anymore. I will add the SDK version next time; not sure if I have updated it since then.

Aside from the exception, can the AF core tools parse a bearer token into a ClaimsIdentity item in GrpcHttpRequestData.Identities as occurs with EasyAuth in Azure? The following assimilates this behavior, but is hacky:

![image](https://user-images.githubusercontent.com/2124254/131721772-6bed7ee5-7ffe-43f5-b790-9dcb4f69e6c5.png)


Locally what shows up in GrpcHttpRequestData.Identities with a valid bearer token provided is:

![image](https://user-images.githubusercontent.com/2124254/131722407-58a2010c-d4d6-4662-8c29-bd3300a5ed16.png)

**Comment by fabiocav** [comment]
@HMoen there are some scenarios that will handle different token types for you (in the host, not Core Tools), like JWTs and SWTs ,  but that doesn't support the same set of features as what Easy Auth provides. We're currently tracking local development scenarios for Easy Auth, so that is something we expect to support in the future

**Comment by HMoen** [comment]
@fabiocav thanks, will keep an eye out for it.
