### ISSUE TITLE
Make diagnosing input converter errors easier

### ISSUE THREAD

**Issue by FiniteReality** [Azure/azure-functions-dotnet-worker#601]
I'm currently getting a FunctionInputConverterException trying to deserialize JSON to a POCO:
```
Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'OrderCreated': Cannot convert input parameter 'message' to type 'My.Project.OrderCreatedEvent' from type 'System.String'.
```
From tracing through the code here, I've determined that to be caused by [JsonPocoConverter](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Converters/JsonPocoConverter.cs) swallowing all serialization exceptions, meaning that I have no way of diagnosing what is wrong with my JSON, and only ending up with [DefaultModelBindingFeature](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Context/Features/DefaultModelBindingFeature.cs) throwing a FunctionInputConverterException since all of the other converters have failed.

To solve this, I was hoping I could write my own [IConverter](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Converters/Converter/IConverter.cs) to effectively duplicate JsonPocoConverter's behaviour, but with some extra logging to help diagnose these errors. However, this type is internal, meaning the only way I can ever hope to diagnose this is by making my function accept a `string` and manually deserializing there.

I think there should be a way for JsonPocoConverter to either log its errors, (it could just inject an ILogger, for example) or IConverter should be public to allow developers to define their own converters to add the logging themselves.

**Comment by brettsam** [comment]
The work to make `IConverter` public is under way (still requires a formal API review), but your comment about better exception logging is a good one.

**Comment by liliankasem** [comment]
I believe this was addressed by the changes made to return the exception as part of the conversion result:

https://github.com/Azure/azure-functions-dotnet-worker/blob/fe02835ff13d3e403e1d90a5d6c8ba54e9d8b076/src/DotNetWorker.Core/Converters/JsonPocoConverter.cs#L70-L73
