### ISSUE TITLE
Log messages below level stated are still emitted in application insights

### ISSUE THREAD

**Issue by dev-jla** [Azure/azure-functions-dotnet-worker#602]
"logLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "Function": "Warning"
      
      does nothing to stop messages of info debug to show up in app insights

**Comment by brettsam** [comment]
@dev-jla -- are you adding this in host.json? Or in a separate appsettings.json file?

**Comment by dev-jla** [comment]
indeed it is, I have tried many variations allow/disallow patterns etc nothing worked

**Comment by Socolin** [comment]
Hello,

We encounters the same problem, the logging is done in the host and not the worker so we have no control over it (I cannot inject a TelemetryProcessor to filter them manually)

The host is logging a lot of useless stuff and this is flooding or logs and costing us too much money for nothing.

**Comment by dev-jla** [comment]
So it looks like its either all or nothing at the moment. Will have to turn them off for now.

**Comment by dev-jla** [comment]
No change in version 4...

**Comment by dev-jla** [comment]
is this being looked at?

**Comment by kelps** [comment]
Anything on this?

It seems we can't control a lot regarding logs.

- no support for structured logs in isolated mode
- no control over log levels (seems to be fixed at Information)
- no configurable control of log providers (we can't prevent some logs going to a specific provider, for example)
- structured logs in process add a prefix to the custom properties defined

This just to list a few....

Not all need to be done at once. If the configuration worked now on host, it would be possible to disable function logs from going to insights and configure insights in the worker process. But the way it is now, doing so generates duplicated logs with and without our custom dimensions.

It looks like this bugs are not getting the attention they should and nothing moves. We understand resources are limited, but that is what the community is here for. Many similar issues with comments saying "there are plans" and "soon", but nothing happens and no updates at all on what is happening and/or roadmaps. How could we, the community, help? Could we investigate and create pull requests to try and fix those things, or at least help elaborating on what needs to be done, to better understand if and when it'll be available?

**Comment by brettsam** [comment]
I just did some testing on this and things seemed to be filtered as expected.

@dev-jla -- I know this issue is from a while back, but do you know exactly how you were logging? Were you using `ILogger` or using `TelemetryClient` directly?

@kelps -- maybe you have a sample? 

For reference, I wrote a function like this and tried adjusting my host.json, then checking in App Insights:

```csharp
public class Function1
{
    private readonly ILogger _logger;

    public Function1(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<Function1>();
    }

    [Function("Function1")]
    public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req, FunctionContext context)
    {
        var contextLogger = context.GetLogger<Function1>();
        contextLogger.LogTrace("context: Trace");
        contextLogger.LogDebug("context: Debug");
        contextLogger.LogInformation("context: Information");
        contextLogger.LogWarning("context: Warning");
        contextLogger.LogError("context: Error");

        _logger.LogTrace("Trace");
        _logger.LogDebug("Debug");
        _logger.LogInformation("Information");
        _logger.LogWarning("Warning");
        _logger.LogError("Error");

        var response = req.CreateResponse(HttpStatusCode.OK);

        return response;
    }
}
```

**Comment by dev-jla** [comment]
@brettsam I was using ILogger

**Comment by aggieben** [comment]
@brettsam please see the issue I posted here: https://github.com/Azure/azure-functions-dotnet-worker/issues/729.  I included a minimal repro.  My issue was closed in favor of this one.

**Comment by dev-jla** [comment]
@brettsam 
So I've had a look at this again and it seems to almost work
setting logLevel as follows:
      "Default": "Warning",
      "Microsoft": "Warning",
      "Function": "Warning"

produces the following in App Insights - note the Information was till pushed.
Is there a way to filter the rest of the "noise"  (Sending Invocation and Posting Invocation etc ) really if there was just the info messages? 
 I should note I'm using .net6 isolated 
![image](https://user-images.githubusercontent.com/10004905/156756155-8714d51b-791c-4972-b1e9-b63936d0be33.png)

**Comment by dev-jla** [comment]
@brettsam many thanks for getting back to me, I've tried again (.net 7 isolated) and its still logging everything - livemetrics shows everything (Trace) - do you have to specifically set every single category? I have  set "default": "None",Microsoft": "Error", "Function": "Error"

**Comment by brettsam** [comment]
In Functions, Live Metrics is not representative of what will actually end up being stored in your logs. App Insights will send logs to Live Metrics and *then* filter them before they go on to be stored. 

I'd recommend looking at queries directly against your Logs tables in App Insights to see what ends up there. If you have an example of a Log that you expected to be filtered, but it ended up in the Logs table, let me know here (with the exact host.json config as well) and I can help.

**Comment by jviau** [comment]
I may have missed it reading the comments but @dev-jla I don't think you fully answered @brettsam's original question:

Are your original log level settings configured in `host.json` or appsettings.json`?

For `host.json`: this is **not** worker configuration and only applies to the host process. So it does not work.
For `appsettings.json`: the default samples and `ConfigureFunctionsWorkerDefaults` does **not** load `appsettings.json` by default. Make sure you are loading this json config file. Either manually via `ConfigureAppConfiguration`, or using `Host.CreateDefaultBuilder(args)` to get all the defaults.
