### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by kimschurmann** [Azure/azure-functions-dotnet-worker#605]
Hi

I have created an azure function on .net 5 and followed the current guide lines and it works as intended locally when running it. When I deploy it to my hosted azure function it fails to start and presents the following error message:

Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

I have set FUNCTIONS_WORKER_RUNTIME=dotnet-isolated

My csproj looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <LangVersion>9.0</LangVersion>
        <AzureFunctionsVersion>V3</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
        <NoWarn>$(NoWarn);NU1605</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
        <PackageReference Include="Azure.Identity" Version="1.4.1" />
        <PackageReference Include="Microsoft.Graph" Version="4.3.0" />
        <PackageReference Include="Microsoft.Identity.Client" Version="4.35.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="4.0.0" />
        <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.6.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
```

There are several packages that depend on Microsoft.Extensions.Configuration.Abstractions and I have tried deploying a version where it is explicitely included - which didn't help. 

Any pointers? 

Thanks in advance!

Best regards
Kim

**Comment by brettsam** [comment]
@kimschurmann -- If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

**Comment by rosidigital** [comment]
I ended up creating a new azure function and deploy my code to that and it worked.

**Comment by kimschurmann** [comment]
I ended up creating a new azure function and deploy my code to that and i worked...

**Comment by fabiocav** [comment]
Thanks for the update. Closing as resolved.
