### ISSUE TITLE
Dependency Injection does not enable ValidateScopes for development environment

### ISSUE THREAD

**Issue by Arjan321** [Azure/azure-functions-dotnet-worker#606]
Hi,

When using dependency injection, one can register a singleton that depends on a scoped service.

```csharp
public class MyScopedClass { }
public class MySingletonClass { MySingletonClass (MyScopedClass scoped) { } }
<....>
services.AddSingleton<MySingletonClass>();
services.AddScoped<MyScopedClass>();
```

From AspNetCore, one assumes that this will throw an exception when used. [From the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0#scope-validation):
> CreateDefaultBuilder sets ServiceProviderOptions.ValidateScopes to true if the app's environment is Development.

However, this is not the case in the isolated functions.

One can work around it by manually do this:
```csharp
.UseDefaultServiceProvider((context, options) =>
{
  options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
})
``` 

Can this be enabled by default to minimize surprises?

**Comment by brettsam** [comment]
Good point -- we'll discuss whether it's possible to add this without it being considered a breaking change.

**Comment by Arjan321** [comment]
Great :)

For sure non breaking would be to add the `options.ValidateScopes = context.HostingEnvironment.IsDevelopment()` to some of the samples available in this repo.
