### ISSUE TITLE
Azure Function app targeting net5.0 (​`dotnet-isolated​`)  doesn't work with `<FrameworkReference Include="Microsoft.AspNetCore.App" />`

### ISSUE THREAD

**Issue by McKabue** [Azure/azure-functions-dotnet-worker#608]
I noticed that when [Microsoft.AspNetCore.App](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-5.0) is specified, the Azure Function app targeting net5.0 (​`dotnet-isolated​`)  doesn't work. 
`<FrameworkReference Include="Microsoft.AspNetCore.App" />` or `<PackageReference Include="Microsoft.AspNetCore.App" />`

However, after removing the meta-package and adding the specific packages I wanted to use, the app works.
```
+    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
+    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.2.0" />
+    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="5.0.9" />
+    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
+    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
+    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="5.0.9" />
+    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
+    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="5.0.9" />
+    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="5.0.9" />
+    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
+    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
```
Is there any documentation for this?

> NB: It is worth noting that this fails to work when deployed to Azure, but works locally in the dev machine.

**Comment by brettsam** [comment]
@McKabue -- is this Linux or Windows? On Linux I don't believe we include that shared package...

**Comment by McKabue** [comment]
It is on Linux.

**Comment by fabiocav** [comment]
This is currently a known issue and we're actively working on this for Linux. In the meantime, the workaround you're using or running on Windows are viable options for now.

**Comment by kshyju** [comment]
Hi @McKabue May I ask what specific API/classes from the `Microsoft.AspNetCore.App` package you are using in you function app?. As part of verifying fix, I would like to include your use case as well in my validation. Thanks!

**Comment by McKabue** [comment]
Am using classes in the following packages:
```
<PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="5.0.9" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="5.0.9" />
<PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
<PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="5.0.9" />
<PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="5.0.9" />
<PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
```

Examples of the classes/interfaces I use include, but are not limited to:
```
IDataProtectionProvider
ITimeLimitedDataProtector
IViewLocationExpander
ViewLocationExpanderContext
ContentResult
Controller
KeyDerivation
KeyDerivationPrf
IRazorViewEngine
ITempDataProvider
ActionContext
ViewEngineResult
ViewDataDictionary
HtmlHelperOptions
RewriteContext
IRule
RouteValueDictionary
RouteTemplate
TemplatePart
```

Most of these are part of a Common Library that I use for utility helper methods for Web app and Azure functions.

I hope this helps.

**Comment by fabiocav** [comment]
@kshyju is actively working on this and validating scenarios shared here. 

Moving to 114 as some validation is still pending.
