### ISSUE TITLE
Restrict middleware execution to function type

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-functions-dotnet-worker#611]
Is there a way to restrict middleware to just execute for certain types of functions? For example, only execute authentication middleware (add tenant and user ids to FunctionContext.Items, etc.) for inbound HTTP triggers. If not, what be the proper way to get the function type within the middleware to filter out the middleware's functionality? CosmosDB trigger would not need the authentication middleware, for example.

We are using the method below, but if there's a correct/better way, please advise. If below is sufficient, please close the issue. Thanks.

![131744753-aa15a356-7106-488c-8abc-502bd36fdad0](https://user-images.githubusercontent.com/2124254/131849293-b991951b-aba2-491b-8fce-c9eeefabf157.png)

**Comment by kshyju** [comment]
We now have the `UseWhen` extension method which allows you to register the middleware with a predicate.

https://github.com/Azure/azure-functions-dotnet-worker/blob/e358ca5b804dc282e1c98b48ab6097caca0fc0fb/samples/CustomMiddleware/Program.cs#L23-L28
