### ISSUE TITLE
Add support for wiring up custom IConverter implementations

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#612]
Add support for wiring up custom `IConverter` implementations. We currently ships 7 built-in converters to handle majority of parameter binding use cases. With this change, users will be able to write their own `IConverter` implementations as needed. 

Currently `IConverter` is an internal type. We will expose this as public along with other related types to support this feature.

**Comment by fabiocav** [comment]
This is currently in progress. Design is being reviewed and implementation will likely start in Sprint 111

**Comment by fabiocav** [comment]
Work in progress, pending additional reviews. Moving to sprint 111
