### ISSUE TITLE
Wire up function ILogger to logging system

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#62]
Today we explicitly pass an ILogger to the ExecutionContext.
- We need to wire this up as an ILoggerProvider, which allows ILoggers used in customer DI services to log back to the host.
- Investigate how we handle categories, etc, from these loggers as they pass back through the host. For example, does the host respect the category on the RpcLog type and use it for its own logs?

**Comment by fabiocav** [comment]
@brettsam should this be linked to your PR?

**Comment by brettsam** [comment]
Yes, taken care of with #123
