### ISSUE TITLE
Azure Function succeeded prematurely preventing subsequent logging output

### ISSUE THREAD

**Issue by rich-mond** [Azure/azure-functions-dotnet-worker#624]
I am observing an Azure Function (queue triggered async .NET 5 isolated) reporting a success state **before** the function has fully executed; any subsequent calls to add to the log (such as LogInformation) fail to produce any output to the console/log stream/app insights/filesystem log.

Theres a predictable point where this occurs, the Function calls an async private method (making a call to sql to return data). 
Once that has executed, the success state is reported for the whole function in the log and any new log lines are not recorded.

**Comment by kshyju** [comment]
> _reporting a success state_

How are you determining this ? by seeing the removal of the message from the queue?

You should be able to mix and match multiple log statements and calling other private asynchronous methods inside a function. Here is a quick working example.

    [Function("Function1")]
    public async Task Run([QueueTrigger("myqueue-items", Connection = "MyConnStringSettingName")] string myQueueItem,
        FunctionContext context)
    {
        var logger = context.GetLogger("Function1");
        logger.LogInformation($"C# Queue trigger function processed: {myQueueItem}");

        var product = await GetProductAsync(myQueueItem);
            
        logger.LogInformation($"Product:{product?.Name}, Price:{product?.Price}");           
        logger.LogInformation($"Another log entry.");
    }
    
where `GetProductAsync` is another async private method. I can see all the log entries in console when I test this code locally.

If you are still running into the issue, could you share the relevant code/minimal repro of the issue where you are seeing the behavior ? That will help us investigate further.

**Comment by dvdgutzmann** [comment]
@rich-mond you might want to check your method signature and make sure it is `async Task` not `async void`. We were seeing the very problems you describe before fixing the return type.

**Comment by rich-mond** [comment]
> 
> 
> @rich-mond you might want to check your method signature and make sure it is `async Task` not `async void`. We were seeing the very problems you describe before fixing the return type.

That will be it, thanks @dvdgutzmann
