### ISSUE TITLE
Azure Function running .NET 5 (dotnet-isolated) can't connect to blob storage using user-assigned managed identity

### ISSUE THREAD

**Issue by dvdgutzmann** [Azure/azure-functions-dotnet-worker#625]
Hi *

We are running a dotnet-isolated  .NET 5 windows function app with latest dependencies (no prereleases). When utilizing system assigned managed identity (via ` new DefaultAzureCredential()`) to connect to a storage account everything works great and the app is able to download a blob. However, when switching to a user-assigned managed identity the app throws exceptions ("ManagedIdentityCredential authentication failed: Service request failed.Status: 400 (Bad Request)").

Locally everything runs smoothly using authentication via Azure CLI. 

Both identities have the `Storage Blob Data Contributor` role assigned for the storage account in question.

Package references from csproj:
```xml
   <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.4.1" />
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.3.0" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.10.0" />
        <PackageReference Include="Dapper" Version="2.0.90" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
        <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
    </ItemGroup>
```
Any ideas? Happy to provide any data or information to sort this out.

Thank you!

David

**Comment by BrianVallelunga** [comment]
Are you specifying the `ManagedUserClientIdentity` like the following?

    var options = new DefaultAzureCredentialOptions { ManagedIdentityClientId = "CLIENT ID FROM ENVIRONMENT" };
    var credentials = new DefaultAzureCredential(options);

**Comment by dvdgutzmann** [comment]
Initially the code was 
```c#
var credential = new ChainedTokenCredential(
    new ManagedIdentityCredential("CLIENT ID FROM ENVIRONMENT"),
    new AzureCliCredential()
);
```

However, with this
> ```
> var options = new DefaultAzureCredentialOptions { ManagedIdentityClientId = "CLIENT ID FROM ENVIRONMENT" };
> var credentials = new DefaultAzureCredential(options);
> ```
the error I get is different:

DefaultAzureCredential failed to retrieve a token from the included credentials.- EnvironmentCredential authentication unavailable. Environment variables are not fully configured.- **ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.**- Visual Studio Token provider can't be accessed at D:\DWASFiles\Sites\xxx-fn-westeurope-pool-incoming__6731\LocalAppData\.IdentityService\AzureServiceAuth\tokenprovider.json- Stored credentials not found. Need to authenticate user in VSCode Azure Account.- Azure CLI not installed- PowerShell is not installed.)---> 

@brettsam just to make sure, are user-assigned managed identities something you would expect to work at this time?

Thanks! David

**Comment by dvdgutzmann** [comment]
OK, this is kind of weird - today it works flawlessly without any code change. I'm closing this issue for now.
