### ISSUE TITLE
How to control function invocation status in middleware?

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-functions-dotnet-worker#626]
Following guidance in #530 , I am using reflection in a dotnet-isolated middleware to control the content of `HttpResponseData` when functions throw. This result in the function invocation status always being `Succeeded` even when the function invocation failed (HTTP 500 server error). How can I control the function status in my middleware?

- Repro functions (first one simulates a client error, second one a server error):

```
[Function("throw1")]
public static HttpResponseData Throw1([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "throw/1")] HttpRequestData request)
{
    throw new ArgumentException("Invalid input", "accountName");
}

[Function("throw2")]
public static HttpResponseData Throw2([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "throw/2")] HttpRequestData request)
{
    throw new Exception("Server crash");
}
```

- Function logs (expected: first Failed, second Succeeded; actual: both Succeeded)

```
[2021-09-16T16:56:42.077Z] Executing 'Functions.throw1' (Reason='This function was programmatically called via the host APIs.', Id=14cecde4-12d6-482c-b3c7-52ca2993f14c)
[2021-09-16T16:56:42.326Z] Executed 'Functions.throw1' (Succeeded, Id=14cecde4-12d6-482c-b3c7-52ca2993f14c, Duration=289ms)
[2021-09-16T16:56:46.416Z] Executing 'Functions.throw2' (Reason='This function was programmatically called via the host APIs.', Id=2444f176-7888-466f-92ef-b4d3aa72e94c)
[2021-09-16T16:56:46.425Z] Executed 'Functions.throw2' (Succeeded, Id=2444f176-7888-466f-92ef-b4d3aa72e94c, Duration=10ms)
```

- Middleware

```
public class ExceptionHandlingMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        try
        {
            await next(context);
        }
        catch (ArgumentException ex) when (HandleHttpError(context, HttpStatusCode.BadRequest, ex))
        {
        }
        catch (Exception ex) when (HandleHttpError(context, HttpStatusCode.InternalServerError, ex))
        {
        }
    }

    private static bool HandleHttpError(FunctionContext context, HttpStatusCode status, Exception ex)
    {
        var binding = context.Features.First(f => f.Key.Name is "IFunctionBindingsFeature").Value;
        var properties = binding.GetType().GetProperties();

        var input = (IReadOnlyDictionary<string, object>)properties.First(p => p.Name is "InputData").GetValue(binding);
        var request = (HttpRequestData)input.Values.FirstOrDefault(o => o is HttpRequestData);
        if (request == null)
        {
            return false;
        }

        var response = request.CreateResponse(status);
        response.Headers.Add("Content-Type", "application/json; charset=utf-8");
        response.WriteString(new JObject { { "message", ex.Message }, { "requestId", context.InvocationId } }.ToString());

        properties.First(p => p.Name is "InvocationResult").SetValue(binding, response);

        return true;
    }
}
```

**Comment by fabiocav** [comment]
@mmaitre314 it would be good to better understand your goal here; when a function throws, the result will be automatically set to a 500, but setting the HTTP status to a 500 range response does not indicate an invocation failure/function failure (e.g. a function can execute successfully and indicate to the client that there was a server side error by setting the status code).

In your case above, you're caching the exception thrown by the function, so the worker implementation interprets that as a successful invocation and simply applies what has been set in the HTTP response data. If you let those exceptions bubble up, the invocations will be flagged as failed.

**Comment by mmaitre314** [comment]
The goal is to control the content of the HTTP response returned when an invocation fails so it is more actionable. This includes adding things like correlation headers, or content of exception. Adding that extra info should not change the fact that the invocation did fail and should be logged as such.

**Comment by fabiocav** [comment]
We're working on enhancements that will make this possible/easier. 

One of the issues tracking that work is https://github.com/Azure/azure-functions-dotnet-worker/issues/340, so I'll close this one in favor of that. 

Thanks!
