### ISSUE TITLE
Pooling Connections Host thresholds exceeded: Connections

### ISSUE THREAD

**Issue by eluchsinger** [Azure/azure-functions-dotnet-worker#628]
We have been running Azure Functions with .NET 5 and in isolated mode. The function works as an integration service and thus calls many other API's frequently.

Now the function runs into a `Host thresholds exceeded: Connections` error.

The thing is that we are pooling the connections using the `HttpClientFactory`, which is [registered over DI](https://github.com/eluchsinger/azure-functions-out-of-connections/blob/8a0cd37b6ecb0d6968d077d89dbadcbcdefa2309/Program.cs#L18). We have also tried to use a `static` `HttpClient` with the same result. This would mean that it is not a Dependency Injection / Scope issue. There are many issues from at least 2019 pointing out that something is wrong there (https://github.com/Azure/azure-functions-host/issues/5098, https://github.com/Azure/azure-functions-host/issues/4914, https://github.com/Azure/azure-functions-host/issues/5851).

I have created a [minimal reproduction](https://github.com/eluchsinger/azure-functions-out-of-connections). In this repro, we send 1250 requests (to be sure that we are over the threshold) to an endpoint. Instead of reusing the connection, the function is probably either:

- Creating a new connection for each request.
- The connection count is broken or connections are not really connections (?)

Apparently, there is an `HttpClient` already [registered](https://github.com/Azure/azure-functions-host/blob/8452121321434f10b3436e323da67fe1e3fc32fa/src/WebJobs.Script.WebHost/WebHostServiceCollectionExtensions.cs#L124) with DI behind the scenes. It seems like this is not the case for `isolated-process`, because the `HttpClient` was not found until I registered the Factory using `AddHttpClient<Connector>`. In issue https://github.com/Azure/Azure-Functions/issues/1911 they are working/discussing to remove that registration for Azure Functions v4.

### Interesting Sources

- [Minimal Reproduction](https://github.com/eluchsinger/azure-functions-out-of-connections)
- [Microsoft Docs suggesting to use static HttpClient](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp#static-clients)
- https://github.com/Azure/Azure-Functions/issues/1911

**Comment by eluchsinger** [comment]
I have added a second minimal reproduction to the repo. This time it is an in-process .NET Core 3.1 Function displaying the same behavior.

@brettsam for my project this behavior is a show-stopper. Hope to see a solution, workaround or at least a status update on this one soon. Please let me know if I can further assist somehow.

**Comment by eluchsinger** [comment]
Hi @fabiocav I am already a step further. @brettsam was so quick to answer that he already [gave me a hint in 2017](https://github.com/Azure/azure-functions-host/issues/2085).

Apparently the host already sets the `ServicePointManager.DefaultConnectionLimit` limit, but that's for the old .NET Framework. I had to set the `MaxConnectionsPerServer` of the `SocketsHttpHandler` ([custom registered in the HttpFactory](https://github.com/eluchsinger/azure-functions-out-of-connections/blob/aa9a2486cdafd3c5ee4fda7a6bf59d50967dd809/isolated/Program.cs#L20)).

Anyways - in the repro, I can not reproduce the behavior anymore. In the productive Azure Function, I still have the problem. It's very complicated because it now behaves differently when throwing the `Host thresholds exceeded: Connections`. Usually it failed after calling it twice (each one creating 300 requests). Now it fails after the first time already reaching the connection threshold. So setting the `MaxConnectionsPerServer` actually made it worse.

For me it looks like the [docs](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp#static-clients) are not correct in two ways.

1. Shouldn't we use the `HttpClientFactory` instead of `static HttpClient`?
2. The `HttpClient` creates a new connection for every request, unless the `SocketsHttpHandler` has an open connection already in the pool. This means that creating a `static HttpClient` does not prevent from running out of connections. You have to somehow limit the connections to a maximum.

I have worked around the issue now by wrapping the requests in a Semaphore and limiting the amount of concurrent requests to something lower than the maximum connection threshold.

**Comment by fabiocav** [comment]
@eluchsinger I'm glad to hear you were able to at least mitigate the issue. One thing that would be helpful to look at is a memory dump of both, the worker and the host processes when this problem is happening. If you have access to support, that would be the ideal way to engage to look at those details. 

It's also worth mentioning that in different plan types (e.g. elastic premium), you'll have higher limits for some of those metrics.
