### ISSUE TITLE
Isolated Process Interface Spec

### ISSUE THREAD

**Issue by bgribaudo** [Azure/azure-functions-dotnet-worker#632]
Thank you for making isolated process Azure Functions/.Net 5 support possible!

Is there formal or informal documentation out there describing the interface between the Azure Functions host process and an isolated process? 

Normally, setting up the isolated process with the correct interface mechanisms is handled automatically by the SDK (nice!)--but let's imagine that I wanted to implement my own isolated process from scratch (i.e. without using the SDK). Are there some formal/informal docs out there summarizing the requirements (like 'your process must return a list of functions it offers when localhost:9999/list' is called so that the host knows what's available)?

Thanks,
Ben

**Comment by fabiocav** [comment]
@bgribaudo we don't have public documentation on how to write your own worker, but we do have a public feature to support something similar: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers

**Comment by bgribaudo** [comment]
@fabiocav, thank you! The linked article is very interesting.
