### ISSUE TITLE
What is the Azure Functions Team's Plan with regards to .NET 6?

### ISSUE THREAD

**Issue by david-peden-q2** [Azure/azure-functions-dotnet-worker#633]
I saw a reference to Azure Functions 4.0 in [another issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/617). Will AF 4.0 coincide with .NET 6? If so, where does that leave the .NET 5.0 work present in this repo?

**Comment by SeanFeldman** [comment]
Unless the [roadmap](https://techcommunity.microsoft.com/t5/apps-on-azure/net-on-azure-functions-roadmap/ba-p/2197916) published a while ago has changed, I believe that was the plan.

**Comment by anthonychu** [comment]
Yes. Public preview for v4 will be announced very very soon. It'll have preview support for .NET 6. You have the option of both in-process and isolated process for .NET 6 on v4.

V4 is expected to be GA at the same time as .NET 6 LTS GA.

The isolated model provided by the SDK in this repo can be used with .NET 5 (in v3) and .NET 6 (v4). It'll also be the path forward for .NET 7 and beyond.

**Comment by david-peden-q2** [comment]
Awesome, thank you.

**Comment by fabiocav** [comment]
Closing as answered. Please let us know if you need any additional information.
