### ISSUE TITLE
RequestTelemetry not being passed to registered ITelemetryProcessor

### ISSUE THREAD

**Issue by peterlentine** [Azure/azure-functions-dotnet-worker#634]
**Overview**
I would like to filter RequestTelemetry using an implementation of ITelemetryProcessor with Azure Functions .NET 5. There seems to be a bug preventing RequestTelemetry from being passed to registered TelemetryProcessors. The `HealthProbeTelemetryProcessor` below does not receive RequestTelemetry while it does receive MetricTelemetry and DependencyTelemetry. 

**Sample code**
Program.cs
```
.ConfigureServices((context, services) =>
{
    services.AddApplicationInsightsTelemetryWorkerService();
    services.AddApplicationInsightsTelemetryProcessor<HealthProbeTelemetryProcessor>();
	
```
	
HealthProbeTelemetryProcessor.cs
```
public class HealthProbeTelemetryProcessor : ITelemetryProcessor
{
	private readonly ITelemetryProcessor _next;

	public HealthProbeTelemetryProcessor(ITelemetryProcessor next)
		=> _next = next ?? throw new ArgumentNullException(nameof(next));

	public void Process(ITelemetry item)
	{
		...
	}
}
```

**Comment by fabiocav** [comment]
@peterlentine I would expect this to be the case. For the worker, the ASP.NET components are not wired up, there's no actual request flowing, so AI will not be processing/providing information about requests. It's a limitation of the current model.
