### ISSUE TITLE
Did not find any initialized language workers

### ISSUE THREAD

**Issue by NimaRayyan** [Azure/azure-functions-dotnet-worker#653]
i have azure function that works on .net-isolated , its working fine locally but when deploy it on azure portal and try to call the function i get error (Did not find any initialized language workers) 

i have this on solution
  <PropertyGroup>
	<TargetFramework>net5.0</TargetFramework>
	<AzureFunctionsVersion>v3</AzureFunctionsVersion>
	<OutputType>Exe</OutputType>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.11.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.NotificationHubs" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Bot.Configuration" Version="4.14.1" />
    <PackageReference Include="ServiceStack.Server" Version="5.10.4" />
</ItemGroup>

**Comment by fabiocav** [comment]
``<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` shouldn't be required.

Would you be able to share your function app name and a timeframe we can use to look at more detailed logging information?

Thanks.
