### ISSUE TITLE
Not possible to set cloud_RoleName

### ISSUE THREAD

**Issue by maciejo-nordcloud** [Azure/azure-functions-dotnet-worker#655]
Hi,

I tried to set the cloud_RoleName using ITelemetryInitializer but it doesn't work. In App Insights it is still being set as the name of the app service which is hosting it.

`public class TelemetryInitializer : ITelemetryInitializer
    {
        private static string RoleName = "Modernised.Responses";
        public void Initialize(ITelemetry telemetry)
        {
            // set custom role name here
            telemetry.Context.Cloud.RoleName = "Name";
        }
    }`

`services.AddSingleton<ITelemetryInitializer, TelemetryInitializer>();`

Is there any other way to do it?

**Comment by fabiocav** [comment]
Flagging this for discussion/design.

For clarity, the difference here is not between v3 and v4, but instead, between in-proc and out-of-proc models. One of the potential solutions is to expose a configuration we could use for any of the supported languages, but we need to discuss.

**Comment by brettsam** [comment]
I think we'll need to look at OpenTelemetry concepts here and see if there's a more general, non-AppInsights, solution. I don't really want to expose some ApplicationInsights-specific setting value only to move onto OpenTelemetry soon.

For now, this value cannot be changed from the host side unless you register your own `ITelemetryInitializer` in the host via an extension, which isn't a great experience. You'd also have to register one via the worker (if using the new AppInsights worker package: https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627) in order for the two sets of logs to match.

**Comment by jviau** [comment]
We will be working on improving observability from the host side. Following OTel semantics, which should cover `cloud_RoleName` for application insights will be included.

Closing this against that issue: https://github.com/Azure/azure-functions-host/issues/9273
