### ISSUE TITLE
Full URL not available with hashtag

### ISSUE THREAD

**Issue by sccrgoalie1** [Azure/azure-functions-dotnet-worker#658]
I am getting a request back from MSAL to an HttpFunction, but the URL sent back with a #.  Looking at all the available properties on the HttpRequestData and FunctionContext, I don't see any way to obtain this information.

Example URL:
http://localhost:7071/api/AuthRedirect/#state=test&client_info=test2

The URL in HttpRequestData:
http://localhost:7071/api/AuthRedirect/

Is there any way to get the full URI, or is this a known limitation?

**Comment by kshyju** [comment]
Hi @sccrgoalie1 

No. On server side, you will not be able to access anything after the `#` in the request URL.

The URL fragment identifier is meant to be used by the client(user-agent/browser). They are used for navigating to a specific sub section of the HTML document or other client-side user experience enhancements. If you try the URL `https://www.bing.com/#state=test&client_info=test2` and observe the network traffic from the browser, you can see that anything after the fragment identifier (`#`) is not being sent to the server. 

If you want to access some additional information on server side, consider sending them as query strings.  Ex: `https://www.bing.com?state=test&client_info=test2`
