### ISSUE TITLE
CosmosDBTrigger doesn't produce App Insights telmetry

### ISSUE THREAD

**Issue by maciejo-nordcloud** [Azure/azure-functions-dotnet-worker#660]
Within our project we use App Insights and Application map extensively nad we have an issue. We're using input and output bindings and we discovered  that for **CosmosDb output** and **FileStore input** telemetry is generated automatically but for **CosmosDB input** it doesn't' work (no traces, no visible on Application Map).

Application Insights is configured just by passing the Instrumentation Key.

**Comment by ealsur** [comment]
Yesterday I went ahead and did a test locally and deploying the Function App with a `host.json` enabling traces and I was able to see the traces appear in App Insights with the `AcquireLease` events:

![image](https://user-images.githubusercontent.com/1633401/137334779-b060ad1d-da1f-4029-b031-22b795c836c6.png)

Not sure what could be the cause of not working in your case though, I started a Function App from scratch and just set this as my `host.json` file:

```
{
    "version": "2.0",
    "logging": {
      "fileLoggingMode": "always",
      "logLevel": {
        "Host.Triggers.CosmosDB": "Trace"
      }
    }
}
```

**Comment by maciejo-nordcloud** [comment]
@ealsur sorry for delay, I can see `AcquireLease` events in traces but I cannot see ComsosDB as a node on Application Map and this is the main goal. For CosmosDB output binding and BlobTrigger it works out of the box but not for CosmosDBTrigger so the behavior seems somewhat inconsistent.

**Comment by ealsur** [comment]
@maciejo-nordcloud I honestly have no clue how that Application Map is built or what it detects. The Cosmos DB bindings and trigger code has no code at all that is explicitly calling or interacting with AppInsights libraries. The Trigger uses the [Change Feed Processor](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor) which will consume the Change Feed through requests in the background (like the Event Hub Trigger) and inform whenever there are new changes to the Functions runtime. The only thing I can think of is, AppInsights / ApplicationMap only detects requests made by the user thread, which in the case of event triggers, the requests happen in the background.
