### ISSUE TITLE
Add dotnet-isolated tests to the integration suite

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#664]
We currently have no e2e validation in the integration tests so we've caught some issues very late -- we need to get these added.

**Comment by fabiocav** [comment]
@Francisco-Gamino I believe you have a PR for this change, correct? Could you please link the PR here and we'll close the issue once that is merged. Thanks!

**Comment by Francisco-Gamino** [comment]
This issue has been fixed. For more info, please see https://github.com/Azure/azure-functions-dotnet-worker/pull/711.
