### ISSUE TITLE
Returning POCO: result is JSON but content-type is text/plain

### ISSUE THREAD

**Issue by migajek** [Azure/azure-functions-dotnet-worker#666]
Tl;DR version:
When returning POCO objects from HTTP-triggered function, the data is serialized to JSON, as expected. The content-type response header is however invalid: `text/plain` instead of `application/json`

---

Please consider following function:
```c#
 public class FooDto
    {
        public string Bar { get; set; }
    }
    public static class Function1
    {
        [Function("Function1")]
        public static FooDto Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            FunctionContext executionContext)
        {
            return new FooDto() {Bar = "FooBar"};
        }
    }
```

When sending the request:
```
GET  http://localhost:7071/api/Function1
Accept: application/json
```

the response is following:
```
HTTP/1.1 200 OK
Connection: close
Date: Fri, 08 Oct 2021 08:29:00 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{
  "Bar": "FooBar"
}
```

Note the text/plain on the response.

Package versions:
```
Microsoft.Azure.Functions.Worker.Extensions.Http = 3.0.13
Microsoft.Azure.Functions.Worker.Sdk = 1.0.4
Microsoft.Azure.Functions.Worker = 1.5.1
```

**Comment by Manthazar** [comment]
I just came across this enhancement and would like to call out a _problem_ with the workaround. Say, you have an internal business service method which doesn't require any argument on itself:
```
public interface IImportantService 
{
   Task<IEnumerable<Book>> GetSomeAsync();
}
```
If this service is now triggered by an http call, we were to return `HttpResponseData `by the workaround. This in turn needs to be built from the HttpRequestData. So, for formal reasons one of the following becomes mandatory:
1. Add `HttpRequestData `to the service method and change its return value to `HttpRequestData`. This gives the false impression that http request data is actually used by the service (which is not).
2. Write wrapper/ boilerplate code around the service code to create the response and call `WriteJsonAsync`
(if you wanted the content type properly set)

**Comment by kshyju** [comment]
We now support richer http model which will allow you to handle this case. 

https://azure.microsoft.com/en-us/updates/public-preview-aspnet-core-integration-in-azure-functions-net-isolated-model/

Please let us know if you run into issues.
