### ISSUE TITLE
NullReferenceException in generated lambda when method argument is a struct

### ISSUE THREAD

**Issue by manio143** [Azure/azure-functions-dotnet-worker#672]
_Using Microsoft.Azure.Functions.Worker 1.5.2_
I'm migrating a Functions project from .NET Core 3.1 to .NET 5 and switching to the isolated process model. We had a method that took a `CancellationToken` as a parameter:

```csharp
public async Task ExecuteFuncAsync([TimerTrigger("%X%")]TimerInfo timer, CancellationToken cancellationToken)
```

I see that getting a cancellation token like that is no longer supported. But rather than getting some sort of validation exception, the framework attempted to invoke my function and for each argument that had no binding it just passes `null`. If it was a reference type that would be fine, however, casting `null` onto a value type results in an exception with a very unhelpful stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
    at lambda_method1(Closure , MyClass , Object[] )
    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
```

You can either add validation to the method arguments before creating the expression in the `DefaultMethodInvokerFactory` or in the factory extend the local assignment to be `T argumentN = arguemnts[index] != null ? (T)arguments[index] : default;`

**Comment by andrewboudreau** [comment]
Thanks @manio143 I spent a few hours trying to track down what's happening here. Your report provided some help and a really easy way to fix this once I understood what was happening.

**Comment by Manthazar** [comment]
Is there a workaround to get a cancellation token (in absence of the HttpContext as well)?

**Comment by kshyju** [comment]
Cancellation tokens are supported now. See https://github.com/Azure/azure-functions-dotnet-worker/issues/180#issuecomment-1260090174

Let us know if you have trouble using it. Thanks!
