### ISSUE TITLE
Allow CosmosDbTrigger connection to be specified in named ConnectionString

### ISSUE THREAD

**Issue by andrew-tevent** [Azure/azure-functions-dotnet-worker#675]
At the moment, it appears that the only choice for setting the connection string is to give the name of a top-level app setting (inside `Values` collection in `local.settings.json`).

It would be very useful if there were a setting to say that the connection string values are stored within the "ConnectionStrings" section.

(It does appear that there [might be a way](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/0d91c644c683e17869124aa9c43ea05f8370edc3/src/WebJobs.Extensions.CosmosDB/Config/CosmosDBWebJobsBuilderExtensions.cs#L31) to use a specific "CosmosDb" named value in "ConnectionsStrings" but it looks like it has now been removed - and besides, I am unsure as to the relationship between these dotnet isolated functions extensions and the existing webjob extensions)

**Comment by andrew-tevent** [comment]
@Morreed Interesting, thought a bit weird. I'd be concerned that an update could break that.

For the moment I have just duplicated the Connection String in the Values collection in `local.settings.json` and my ARM deployment.

**Comment by fabiocav** [comment]
Hierarchical configuration settings are supported and you do have support for configuration sections.

In addition to the local.settings.json, you could have a JSON configuration source with the hierarchy you want (including a connection strings section), as long as the reference you have in the attribute matches that hierarchy (like you have in the example above).

I hope that helps, but let us know if you need an example here.

**Comment by andrew-tevent** [comment]
@fabiocav Thanks for the reply!

What I have is a shared piece of startup code which loads my Cosmos ConnectionString like this:

`configuration.GetConnectionString("CosmosDb");`

So my appsettings.json has

```
"ConnectionStrings": {
    "CosmosDb": "<etc>"
}
```

In my functions app startup, I actually am adding a JSON source to the HostBuilder (and deploy this file with my Functions into Azure):

```
var host = new HostBuilder()
     .ConfigureFunctionsWorkerDefault( ... )
     .ConfigureAppConfiguration((context, builder) =>
          { 
                builder..AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, "appsettings.json"));
          })
      . // snip
      .Build();
```

and I can use Cosmos within my code no matter if it is a Functions project.

But then I come to add a CosmosDbTrigger and I cannot re-use that app settings value I have with the connection string.  I can just about get on board with having to add it to `local.settings.json` for local debug (but it would be nice not to have to) - but I really don't want to have to go back and restructure my appsettings and startup logic just because the CosmosDbTrigger requires the setting in a specific place.

Unless you can enlighten me and tell me what I should be putting in the `ConnectionStringSetting` which will work with my existing configuration?

**Comment by fabiocav** [comment]
@andrew-tevent for the OOP model, this wouldn't be recommended or work as expected. The recommended approach would be to define that in app settings (which could continue to follow the hierarchy you have defined above) and would be automatically picked up by the host. 

That also keeps secrets out of configuration files.

Would that approach work for you?

**Comment by andrew-tevent** [comment]
@fabiocav Can you expand on what you mean?  I am defining it in app settings.

>That also keeps secrets out of configuration files.

I handle my secrets with ARM Templates / KeyVault at deploy-time.

**Comment by fabiocav** [comment]
@andrew-tevent can you clarify what `ConnectionStrings` section you're referring to? Is that what is in the portal?

**Comment by andrew-tevent** [comment]
@fabiocav I'm talking about these - configured in `appSettings.json`

![image](https://user-images.githubusercontent.com/78795042/143211852-a5aa1db1-deb4-44b0-a1b2-d44024fd187c.png)

Which are accessible using `IConfiguration`:

![image](https://user-images.githubusercontent.com/78795042/143212014-435b4fcd-ef06-43b7-ade4-aa59417ecaf1.png)

Which can then be overridden in ARM Templates:

![image](https://user-images.githubusercontent.com/78795042/143212431-89447bdc-6f41-4ce4-8660-c703dfd0d21a.png)

(Which also then appear in the Azure Portal:)

![image](https://user-images.githubusercontent.com/78795042/143212916-646f37f6-ae6c-45b8-8f79-61a046aff01b.png)

**Comment by fabiocav** [comment]
My previous comment applies, but only for input and output bindings. Setting that from a file configuration source for triggers has limitations. 

Setting those using App Settings and Key Vault references is the recommended approach.

**Comment by twentytwokhz** [comment]
Related question for @fabiocav
Is it possible to reference the app configuration service settings via the Input Bindings and Triggers?
I tried doing that and expected to have the functions execute correctly - but instead they failed to start with exception

" A host error has occurred during startup operation 'aabc18d9-dc39-4f13-81cd-04388f44269e'.
[2021-12-08T16:09:33.499Z] Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'ServiceBusV2-ConnectionString' is missing or empty."

PS: running .NET 6 isolated function app with app configuration service integration via managed user identity

Should I open another issue?
