### ISSUE TITLE
Adding the Microsoft.Azure.SignalR package will break .net 5 isolated worker

### ISSUE THREAD

**Issue by dvdvorle** [Azure/azure-functions-dotnet-worker#678]
**Short description**
I'm trying to call into the Azure SignalR management API without using the Az Fx bindings (they fall short for my use case). While doing local development everything looks fine on both Windows and WSL. When publishing the function to Azure however, it all breaks down with:

> [Error]   Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down

Meaning none of my HttpTriggers respond. 

**Steps to reproduce**
This can easily be reproduced by creating a new .net 5 Function App, and adding the `Microsoft.Azure.SignalR` package to it (current latest is 1.11.0).

**What I've tried**
Linux host -> doesn't work
Windows host -> doesn't work
Adding all the transitive dependencies of `Microsoft.Azure.SignalR`, but _not_ `Microsoft.Azure.SignalR` itself -> Everything works

I don't know of a workaround and am currently stuck, please help :-)

**Comment by fabiocav** [comment]
Would you mind sharing the basic repro project on a repo here? We want to make sure we have the correct details to investigate the issue.

Thanks!

**Comment by dvdvorle** [comment]
Well.. Color me surprised, I don't seem to be able to reproduce this any longer. Neither in a basic repro project, nor in the actual project I was trying this in... Haven't got a clue what's changed.

I'll retry and fully implement what I was doing next week. Will post an update then.

**Comment by fabiocav** [comment]
@dvdvorle closing this as resolved, but please reopen if you continue to run into issues.
