### ISSUE TITLE
ServiceBusOutput to queue with sessions enabled

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-functions-dotnet-worker#681]
Anyone have tips/docs for sending output to a queue that has sessions turned on?

`Microsoft.Azure.ServiceBus: The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value.`

**Comment by fabiocav** [comment]
@alrod is this supported with OOP languages in general? I'm want to rule this out as a limitation to OOP before looking at the worker. If supported, do you have documentation on the use from different languages?
Thanks!

**Comment by alrod** [comment]
SB output is supported for OOP, see examples:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#example

@smokedlinq,  did you try to set the Sessionid for output Message?
`var message = new Message(bytes) { SessionId = sessionId };`

**Comment by smokedlinq** [comment]
@alrod I did try to return a ServiceBusMessage and a json payload that looks like ServiceBusMessage but get the error stated above.

**Comment by fabiocav** [comment]
@alrod need to clarify here; can you confirm that sessions are supported for OOP, meaning, there is a mechanism to express properties and other metadata, including sessions (e.g. there's a payload format supported by the extension).

This means it would also be supported by something like JavaScript, Java, etc.

If so, can you please share the sample here? The one you've linked to is in-proc.

**Comment by kshyju** [comment]
@alrod I tried to write to a service bus queue from an out of process dotnet app using `ServiceBusMessage` type which allows you to specify meta properties like `MessageId` and `Subject`. When I check the message in azure portal service bus explorer, I do not see the meta properties under the "broker properties" section. Instead all of those goes inside the JSON string for message content. This behavior is different than what we see in an in-proc app. For an in-proc app it works as expected (I can see `MessageId` and `Subject` under broker properties)

[Here ](https://github.com/kshyju/FunctionsServiceBusWriter)is a minimal repro. 
To reproduce this behavior: 
1) Create a queue named "myqueue" 
2) Set the `MyServiceBusConn` connection string in your app. I also included some screenshots in the README of that repo.
3) Run the project and hit the http endpoint (which has code to write to service bus)
4) Check the message in service bus explorer.

**Comment by ayayalar** [comment]
I am experiencing the same problem here. This minimal OOP session enabled function (using .net v6, function v4) fails with the following error:

```csharp        
        [Function("Search")]
        [ServiceBusOutput(queueOrTopicName: "response", Connection = "response")]
        public ServiceBusMessage Run([ServiceBusTrigger("request", Connection = "request")] string myQueueItem)
        {
            var serviceBus = ServiceBusProvider.Instance;

            var serviceBusMessage = new ServiceBusMessage("pong")
            {
                SessionId = "1234"
            };

            return serviceBusMessage;
        }
```

**Error:**
System.Private.CoreLib: Exception while executing function: Functions.Search. Microsoft.Azure.ServiceBus: **_The SessionId was not set on a message_**, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value

ps: it works if I use the ServiceBusClient directly instead of SB extension.

**Comment by alrod** [comment]
> @alrod is this supported with OOP languages in general? I'm want to rule this out as a limitation to OOP before looking at the worker. If supported, do you have documentation on the use from different languages? Thanks!

Output bindings currently does not support setting message properties other poco or primitive types.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#data-type-support

**Comment by fabiocav** [comment]
Closing this in favor of https://github.com/Azure/azure-sdk-for-net/issues/21884
