### ISSUE TITLE
No Logs in azure function .NET 6 dotnet-isolated Linux Consumption

### ISSUE THREAD

**Issue by rosenkolev** [Azure/azure-functions-dotnet-worker#682]
# No logs log-stream and application insight data in azure functions

## Functions is working, but no logs

* Environment - Linux
* Plan - Linux Consumption Apps
* Version - Azure Function ~v4
* Framework - .NET 6 - dotnet-isolated
* Microsoft.Azure.Functions.Worker - 1.5.2
* Project - [GitHub MentorBot](https://github.com/MentorMate/mentorbot/blob/main/src/MentorBot.Functions/App/Program.cs)

Created with 
```bash
az functionapp create --resource-group group-name --consumption-plan-location westeurope --runtime dotnet-isolated --functions-version 3 --name app-name --storage-account storage-name --os-type Linux
az functionapp config appsettings set --settings FUNCTIONS_EXTENSION_VERSION=~4 -n app-name -g group-name
az functionapp deployment source config-zip -n app-name -g group-name --src app.zip --subscription sub-name
```

## Issue
Functions are working as expected (HTTP and Timers), but logs are missing:
* No Logs in the functions
* No Invocations
* No log-stream
* No data in Application Insights
* [Azure function invokations](https://prnt.sc/1wd4yuu)
* [Azure live stream](https://prnt.sc/1whtk0l)

Note that:
* Functions are executing and result is returned
* Timer functions are executing and result is visible

### Bash Log Stream

```bash
func azure functionapp logstream mentorbot-app
#REM Log stream is not currently supported in Linux Consumption Apps. Please use --browser to open Azure Application Insights Live Stream in the Azure portal.
```

**Comment by fabiocav** [comment]
@rosenkolev with the current runtime on Linux, Application Insights must be explicitly added as a dependency for that to work. This is changing this week and, at that point, we expect the behavior to return to what you had with 3.0.

**Comment by fabiocav** [comment]
That is documented [here](https://github.com/Azure/app-service-announcements/issues/349)

**Comment by rosenkolev** [comment]
I have tried installing it, but it didn't work. 
Later I have seen this Update: 

> This release is currently on Windows. Linux deployment is still pending.

So I hope this will be resolved soon.

**Comment by fabiocav** [comment]
Thank you for the update. Closing this as the deployment is completed, but please feel free to open an issue and reference this if you continue to run into problems.

Thanks!
