### ISSUE TITLE
Missing release notes for Microsoft.Azure.Functions.Worker.Sdk 1.2.0

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#683]
I can see a new version https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.2.0, but where can I see what's changed in it compared to the previous stable version 1.0.4?

**Comment by fabiocav** [comment]
This hasn't been prioritized as it doesn't expose a public API surface, but we'll updated the release flow to make sure those are added moving forward.

**Comment by fabiocav** [comment]
Hope this helps, closing the issue, but let us know if you have any questions.

**Comment by dmytro-gokun** [comment]
@fabiocav Thanks for the answer, but i still have some questions:
1) Is it safe (or even advised) to simply upgrade 1.0.4 => 1.2.0 or should I be aware of something?
2) In the meantime, version 1.3.0 is available now. Still now release notes. The same question applies to this version.
