### ISSUE TITLE
EventGridOutput binding with CloudEvent error

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-functions-dotnet-worker#685]
Need to return one or more CloudEvent objects, even serializing to json returns the same error. I verified all the properties have data ...

```csharp
[Function(nameof(PublishChangeFeedEvents))]
[EventGridOutput(TopicEndpointUri = "TopicEndpointUri", TopicKeySetting = "TopicKeySetting")]
public static string Run([CosmosDBTrigger(
    databaseName: CosmosEventStoreOptions.DefaultDatabaseId,
    collectionName: CosmosEventStoreOptions.DefaultContainerId,
    ConnectionStringSetting = "CosmosEventStore",
    LeaseCollectionName = "leases",
    CreateLeaseCollectionIfNotExists = true,
    StartFromBeginning = true)] string json)
{
    var events = CosmosEventStoreChangeFeed.ParseEvents(json).Select(x => new CloudEvent("https://localhost", x.Type, x.Data, MediaTypeNames.Application.Json, CloudEventDataFormat.Json)
    {
        Subject = x.StreamId.Value
    });

    var outputJson = JsonSerializer.Serialize(events);

    return outputJson;
}
```

Produces error: `Exception while executing function: Functions.PublishChangeFeedEvents. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Microsoft.Azure.EventGrid: 'EventType' cannot be null.`

**Comment by fabiocav** [comment]
@smokedlinq can you confirm you were using version 2.x of the extension? Version 3.x supports Cloud Events and will be available once this is completed: #707

**Comment by smokedlinq** [comment]
@fabiocav I was using the 3.x version ...

<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventGrid" Version="3.0.0-beta.3" />

**Comment by fabiocav** [comment]
Thank you. It does look like there's an issue with this and we'll take a closer look.

In the meantime, it would be good to validate the serializer you're using, and we can't tell what that is because the namespaces aren't visible. Can you please share your usings or confirm the `JsonSerializer` type you're using?

**Comment by fabiocav** [comment]
@smokedlinq if possible, it would be great to get a repro on this, as we're seeing different results when following what you've described above. Would you be able to share a link to a repo showing a minimal repro? Thanks!

**Comment by fabiocav** [comment]
Some additional context; @kshyju setup a repro [here](https://github.com/kshyju/EventGrid-685)

**Comment by StargazerNC** [comment]
I have this issue also, isolated mode, version 4, .NET 6. I have an issue of using a POCO or using EventGridEvent as suggested by @kshyju .
`   [Function(nameof(Processor))]
        [EventGridOutput(TopicEndpointUri = "EventGridTopic", TopicKeySetting = "EventGridKey")]
        public async Task<EventGridEvent> Run([ServiceBusTrigger("%QueueName%", Connection = "ServiceBus-ConnectionString")] SigningRequest signingRequest)`

If I use my own POCO, it complains about the property names not being lowercase. So I add the JsonPropertyName attribute. Then it screams with this issue nonetheless.

I'll resort to using the SDK, but I would prefer using an output binding.

**Comment by aishwaryabh** [comment]
Closing as this is supported today
