### ISSUE TITLE
TimeoutAttribute support is missing

### ISSUE THREAD

**Issue by rhythmnewt** [Azure/azure-functions-dotnet-worker#686]
Are there any plans to add the TimeoutAttribute support in .net 5 functions like there was in Microsoft.Azure.WebJobs?

![image](https://user-images.githubusercontent.com/1319322/138785918-c1bec15a-c2be-44dd-8112-f5a10832429a.png)

**Comment by fabiocav** [comment]
The recommendation is to use `host.json` for that configuration in OOP scenarios. Would that work for you? If not, can you share more details about your scenario?

Here's the documentation on that setting: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout
