### ISSUE TITLE
Improve function metadata generation

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#69]
Today we use Source Generators... but this won't work for non-C# or if the assembly has been AOT compiled. Need to come up with alternative or fallback...

**Comment by kshyju** [comment]
@brettsam Is this still a valid case to address? @satvu is working on bringing back source gen for indexing.

**Comment by brettsam** [comment]
We punted source generators -- this was originally created for our initial preview so going to close this. The effort to bring back source generators will include a fallback.
