### ISSUE TITLE
Publish new version of Worker.Extensions.RabbitMQ consuming 6.1.X+ version of RabbitMQ.Client

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#691]
Publish a new version of `Microsoft.Azure.Functions.Worker.Extensions.RabbitMQ` which maps to a new version of `WebJobs.Extensions.RabbitMQ` which is consuming 6.1.X+ version of `RabbitMQ.Client`

**Comment by fabiocav** [comment]
This is currently blocked until https://github.com/Azure/azure-functions-rabbitmq-extension/issues/173 is completed.
