### ISSUE TITLE
locking dependencies for WorkerExtensions.csproj

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-functions-dotnet-worker#692]
Our CI separates out restore and build. The build does not have access to nuget repos. The issue is that WorkerExtensions.csproj is generated on the fly during build. It currently generates:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Configuration>Release</Configuration>
        <AssemblyName>Microsoft.Azure.Functions.Worker.Extensions</AssemblyName>
        <RootNamespace>Microsoft.Azure.Functions.Worker.Extensions</RootNamespace>
        <MajorMinorProductVersion>1.0</MajorMinorProductVersion>
        <Version>$(MajorMinorProductVersion).0</Version>
        <AssemblyVersion>$(MajorMinorProductVersion).0.0</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NETCore.Targets" Version="3.0.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />

    </ItemGroup>
</Project>
```

I can ensure those dependencies are restored by copying the csproj and making a packages.lock.json. The build then fails to find Microsoft.Azure.WebJobs 3.0.23 and 3.0.22. I worked around the problem by creating separate proj files and locking them.

``` xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.23" />
    </ItemGroup>
</Project>
```

``` xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.22" />
    </ItemGroup>
</Project>
```

Is there a better way to lock dependencies for WorkerExtensions.csproj?

**Comment by fabiocav** [comment]
We may need to get more context to better understand what you're running into. Are you only seeing failures with those packages? Can you also share your main project?

Would a command that generates and persists the extensions csproj help you here?

**Comment by cataggar** [comment]
I shared my main project with you via Teams. Is there a way to use a persisted csproj and avoid the dynamically generated one today?

**Comment by fabiocav** [comment]
@cataggar thank you for sharing the details. We're adding this to the backlog as an enhancement item, but for now, the approach you have in place is a valid workaround.

**Comment by cataggar** [comment]
With .NET 6, I've switched us back to in-process for now.

**Comment by sonic1981** [comment]
We also have this issue. to elaborate on our use case we use a third party vulnerability scanning tool. It builds the sln but it does not have access to our company wide nuget feed. So I have to restore then send the whole solution to this tool to build

**Comment by riteshirisidc** [comment]
I am also facing this issue. In our case, Network access during build time is not allowed. All the restore needs to happen before build actually starts

**Comment by manchenkoff** [comment]
Any update on this issue? It is still impossible to build the project with private feed access due to network isolation.

```
WorkerExtensions.csproj : error NU1301: Unable to load the service index for source
```

**Comment by jviau** [comment]
Tracking the work to address no-network inner restore here: #1888
