### ISSUE TITLE
Deserialization of function input POCO objects fails silently

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-dotnet-worker#695]
If I try to bind a function input to a POCO and the deserialization fails with an exception, the exception gets swallowed without emitting any logs, making it really hard to debug.

The code in question is here (`JsonPocoConverter.TryDeserialize()`): https://github.com/Azure/azure-functions-dotnet-worker/blob/66c6380a311b800bb301323693b4ce1cf69dd682/src/DotNetWorker.Core/Converters/JsonPocoConverter.cs#L63-L75

Please consider adding logs of some kind to make parameter binding issues easier for developers to debug.

**Comment by fabiocav** [comment]
Need to discuss this as we should probably avoid anything with a level of warning or higher as it would create a lot of noise, but we still want to make this discoverable.

**Comment by liliankasem** [comment]
I believe this has been resolved with the addition of conversion results i.e. https://github.com/Azure/azure-functions-dotnet-worker/blob/fe02835ff13d3e403e1d90a5d6c8ba54e9d8b076/src/DotNetWorker.Core/Converters/JsonPocoConverter.cs#L72
