### ISSUE TITLE
Logging using an `ILogger<T>` instance does not work when it is not part of a function execution

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#702]
Logging using a [constructor injected](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#logging) `ILogger<T>` instance does not work when it is not part of a function execution. This means logging does not work inside an implementation of `IHostedService` or `BackgroundService` which is registered as a hosted service in worker.

````
internal class CacheRefreshService : BackgroundService
{
    private readonly ILogger<CacheRefreshService> _logger;
    public CacheRefreshService(ILogger<CacheRefreshService> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // Below logging does not work.
        _logger.LogInformation("Inside ExecuteAsync");
        // code to refresh cache.
        await Task.Delay(5000);
    }
}
````
In this case, the code executed in the background service has no invocation id associated with it. So I believe [this line in host](https://github.com/Azure/azure-functions-host/blob/dcfd7fc1458da020de2c3f49b1d9672b1e1bc229/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs#L696) is dropping the log messages sent from worker to host.

**Comment by SeanFeldman** [comment]
@kshyju I might be missing some context/knowledge here, but a function has to be triggered. And a `BackgroundService` would not be executed if there's no trigger.

**Comment by ayrton97** [comment]
@SeanFeldman Can you please explain why the function has to be triggered? 
In my case I just register a service and background service.
The service is going to consume some data which will be periodically retrieved by the background service which is added as a hosted service and doesn't require any invocation.

**Comment by SeanFeldman** [comment]
@ayrton97, my question is based on understanding how Functions operate. Take a consumption plan where a Function is constrained in the [execution time](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout). That means b/g service or not, the function will be shut down and the background service won't be able to run.

**Comment by ayrton97** [comment]
I'm not talking about the consumption plan, I'm talking about the way function is initialized.
For references: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio
AFAIU Azure Function brought a lot of stuff from ASP.Net Core, so my understanding that this should work the same way it works for ASP.Net.

services.AddSingleton<MonitorLoop>();
services.AddHostedService<QueuedHostedService>();
services.AddSingleton<IBackgroundTaskQueue>(ctx => {
    if (!int.TryParse(hostContext.Configuration["QueueCapacity"], out var queueCapacity))
        queueCapacity = 100;
    return new BackgroundTaskQueue(queueCapacity);
});

So I've tried using the same approach to implement BackgroundService and inject logger similar to :
public QueuedHostedService(IBackgroundTaskQueue taskQueue, 
        ILogger<QueuedHostedService> logger)
    {
        TaskQueue = taskQueue;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation(
            $"Queued Hosted Service is running.{Environment.NewLine}" +
            $"{Environment.NewLine}Tap W to add a work item to the " +
            $"background queue.{Environment.NewLine}");

        await BackgroundProcessing(stoppingToken);
    }

What I observe is that the BackgroundProcessing stuff is working as expected and I can do periodic update from the BackgroundService **even** if there is not function invocation, but logger just doesn't work.
@SeanFeldman , it's not consistent with what you are saying that function requires a trigger - in this case there is no explicit trigger such as HTTP call, timer or queue, etc. The only trigger is the function initialization and that's sufficient to trigger the first run which will take care of the subsequent ones.

**Comment by SeanFeldman** [comment]
@ayrton97 and your b/g service is consistently involved? @fabiocav is that a supported scenario? As it sure goes against the documentation and the invocation model for Functions.

**Comment by ayrton97** [comment]
@SeanFeldman, 
Please elaborate on what you mean by "continuously involved"? 
The BG service periodically updates another service with the data retrieved by the BG service. The update happens every minute. so I'd say it's consistently involved.

**Comment by SeanFeldman** [comment]
It was a typo. I meant to write "continuously invoked", which is the case when your b/g service is invoked every minute.
That's why I'm so confused that it's even working, given that it's not how functions are supposed to work. Hence the ping for clarification from Fabio, who's assigned to this issue.

**Comment by ayrton97** [comment]
Do you have any ETA for triage?

**Comment by fabiocav** [comment]
This will be discussed in the next design sync (week of the 29th) as it may require host changes.

**Comment by fabiocav** [comment]
@kshyju assigning this to make sure someone is on point to drive the design discussion.

**Comment by fabiocav** [comment]
This is being discussed in the context of logging improvements. Will continue to move this forward until we have the broader logging issue details.

**Comment by fabiocav** [comment]
FYI @brettsam @kshyju

**Comment by fabiocav** [comment]
Assigning to @brettsam as part of the logging enhancements.

**Comment by fabiocav** [comment]
@brettsam was this one of the issues we planned on closing, sharing the guidance to use the new Application Insights package?

**Comment by jviau** [comment]
Closing as I believe this should be addressed by using Application Insights or OTel support
