### ISSUE TITLE
Unable to compile Azure Function v4 out-of-process in VS 2022 Enterprise Version 17.0.0

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#704]
The Azure Function's `.csproj` definition is per the following snippet:

```xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	 <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
  </ItemGroup>
```
The Program.cs file's initialization is like the following code snippet:

```cs
var host = new HostBuilder()
	.ConfigureFunctionsWorkerDefaults()
	.ConfigureAppConfiguration((context, configure) =>
	{
		configure
		.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
		.AddJsonFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true)
		.AddEnvironmentVariables();
	})
	.ConfigureServices((context, services) =>
	{
          services.AddMyServices();
	})
	.Build();

```

The compiler issues the following error message:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4062	The "GenerateFunctionMetadata" task could not be loaded from the assembly C:\Users\myusername\.nuget\packages\microsoft.net.sdk.functions\4.0.1\build\..\tools\net6.0\\Microsoft.NET.Sdk.Functions.MSBuild.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	MyApp.Functions	C:\Users\myusername\.nuget\packages\microsoft.azure.functions.worker.sdk\1.3.0\build\Microsoft.Azure.Functions.Worker.Sdk.targets	60	

Would you please give a direction on fixing this problem?

**Comment by kshyju** [comment]
@arashcomsense Why do you have the reference to the `Microsoft.NET.Sdk.Functions` package? If you remove that entry and try to build, what happens?

**Comment by arashcomsense** [comment]
@kshyju Worked! thanks for the help!
