### ISSUE TITLE
Configuring custom routes

### ISSUE THREAD

**Issue by aggieben** [Azure/azure-functions-dotnet-worker#705]
I have a function defined like this (F♯, obviously):

```
module Cxe.Sabine.Web.Functions
open Microsoft.Azure.Functions.Worker
open Microsoft.Extensions.Logging
open Microsoft.Azure.Functions.Worker.Http


[<Function("Index")>]
let run ([<HttpTrigger(AuthorizationLevel.Function, "get", Route = null)>]req: HttpRequestData) 
        (executionContext:FunctionContext) =
    async {
        let log = executionContext.GetLogger("Index")
        log.LogInformation("F# HTTP trigger function processed a request.")

        let responseMessage =  "This HTTP triggered function executed successfully."

        let resp = req.CreateResponse(HttpStatusCode.OK);
        do! resp.WriteStringAsync(responseMessage) |> Async.AwaitTask

        return resp
    } |> Async.StartAsTask
```

When I test this locally, it matches to the url `http://localhost:{port}/api/Index`.  How can routing be customized to give more control over the url structure?  I see that there is the `HttpTriggerAttribute.Route` property, but it doesn't seem to be able to affect whether or not the `/api` part of the path appears.

**Comment by fabiocav** [comment]
For the `/api` base route, you can use `host.json` to modify that. 

Documentation for that is available [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-output#hostjson-settings)
