### ISSUE TITLE
Storage account connection string for 'AzureWebJobsStorage' is invalid

### ISSUE THREAD

**Issue by aggieben** [Azure/azure-functions-dotnet-worker#706]
I have a simple F♯ worker function:

```
[<Function("Index")>]
let run ([<HttpTrigger(AuthorizationLevel.Function, "get", Route = "")>]req: HttpRequestData)
        (executionContext:FunctionContext)
        ([<BlobInput("sabine-content")>] containerClient:BlobContainerClient)
        =
    async {
        let log = executionContext.GetLogger("Index")
        log.LogInformation("F# HTTP trigger function processed a request.")

        let responseMessage =  "This HTTP triggered function executed successfully."

        let resp = req.CreateResponse(HttpStatusCode.OK);
        do! resp.WriteStringAsync(responseMessage) |> Async.AwaitTask

        return resp
    } |> Async.StartAsTask
```

However, when I run it in the debugger or with `func start`,  any request fails like this (essential error message is in the title):

```
For detailed output, run func with --verbose flag.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:1745/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2021-11-09T14:55:25.706Z] Worker process started and initialized.
[2021-11-09T14:55:30.432Z] Host lock lease acquired by instance ID '000000000000000000000000449BC4F9'.
[2021-11-09T14:55:35.943Z] Executing 'Functions.Index' (Reason='This function was programmatically called via the host APIs.', Id=8e0b2761-3730-44de-b1a1-f3bcc74d9d6b)
[2021-11-09T14:55:36.037Z] Executed 'Functions.Index' (Failed, Id=8e0b2761-3730-44de-b1a1-f3bcc74d9d6b, Duration=114ms)
[2021-11-09T14:55:36.038Z] System.Private.CoreLib: Exception while executing function: Functions.Index. Microsoft.Azure.WebJobs.Host: Storage account connection string for 'AzureWebJobsStorage' is invalid.
```

I'm trying to connect to the local storage emulator, so my `local.settings.json` is as follows:
```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=True",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}
```

I also confirmed that this file is copied into the `output` folder.

Something similar happens in VS Code, the only difference being that it shows me this error dialog almost right away:
![image](https://user-images.githubusercontent.com/1321/141147366-8b79a2e9-aaab-4fe7-89ef-87aa034d2a21.png)

I'm at a bit of a loss as to why this is failing.  

*Update*: I did find this [explanation that the Azure Storage Emulator is deprecated](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator).  I stopped the legacy emulator, installed and started Azurite instead, and the result is the same - it still says the connection can't be validated.

**Comment by aggieben** [comment]
After digging around on this for a while, I think this issue should probably be moved to the Azure/azure-webjobs-sdk repository.  The error seems to be occurring here: https://github.com/Azure/azure-webjobs-sdk/blob/f3f78bab110503515a08c4440e06c900ca6e3cb4/src/Microsoft.Azure.WebJobs.Extensions.Storage/StorageAccountProvider.cs#L58

**Comment by brettsam** [comment]
Could the string be case-sensitive? Can you try `UseDevelopmentStorage=true`?

**Comment by aggieben** [comment]
Yep, discovered this and updated my ticket in the sdk repo: https://github.com/Azure/azure-webjobs-sdk/issues/2783#issuecomment-970622883

**Comment by fabiocav** [comment]
Closing as there was a follow up in the WebJobs repo
