### ISSUE TITLE
Correct usage of ServiceBusOutput in isolated mode

### ISSUE THREAD

**Issue by przemyslaw-serwicki** [Azure/azure-functions-dotnet-worker#712]
Hi guys!

I've tried to publish message back to service bus, where duplicate detection is supported.

As this is out-of-process function, I am using the appropriate return type.

```
        [ServiceBusOutput("%ServiceBusTopic%")]
        public async Task<Azure.Messaging.ServiceBus.ServiceBusMessage> Run(...
        {
            ...
            var returnMessage = new Azure.Messaging.ServiceBus.ServiceBusMessage()
            {
                MessageId = Guid.NewGuid().ToString(),
                PartitionKey = "SomeKey",
                Body = new BinaryData(Encoding.UTF8.GetBytes("Test payload"))
            };
            
             ...
            
            return returnMessage;
```

Unfortunately when publishing, I've received an error:
`Message to a partitioned entity with duplicate detection enabled must have either PartitionKey or MessageId set`

I've also checked the case where I publish on a topic without partitioning/duplicate detection.
Message arrived, but it looks like a whole ServiceBusMessage object being serialized.

```
{
  "Body": {},
  "MessageId": "a317207b-012e-43d1-b844-531a47b780dd",
  "PartitionKey": "e7baf459-f33f-4ab2-a7c4-3bb174548430",
  "TransactionPartitionKey": null,
  "SessionId": null,
  "ReplyToSessionId": null,
  "TimeToLive": "10675199.02:48:05.4775807",
  "CorrelationId": "",
  "Subject": null,
  "To": "",
  "ContentType": null,
  "ReplyTo": "",
  "ScheduledEnqueueTime": "0001-01-01T00:00:00+00:00",
  "ApplicationProperties": {}
}
```

I am wondering if this feature should be working already in isolated functions or it's something still under development?

Those are my project settings:
```
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
```
and packages:
```
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.4.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.0.0-beta.6" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights" Version="1.0.0-preview4" />
```

Looking foward for some tips :)

**Comment by brettsam** [comment]
This looks like the same issue we're seeing in #681, where the message returned isn't properly setting the message-level properties. We may require a change in the SB extension to get this working. In the meantime, you should be able to use the SB client directly to insert your messages, which should give you all the control you need.

I'm going to close this as a duplicate -- if you read that issue and don't think they're related, let me know and we can re-activate this one.
