### ISSUE TITLE
.NET 6 Isolated: An error occurred while loading required library hostpolicy.dll

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-dotnet-worker#714]
I am trying out Azure Functions 4.0 with .NET 6 **Isolated (Out-of-process)** and I am getting the following error.
```
Failed to load the dll from [...\AppData\Local\AzureFunctionsTools\Releases\4.10.1\cli_x64\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [...\AppData\Local\AzureFunctionsTools\Releases\4.10.1\cli_x64\]
```
![image](https://user-images.githubusercontent.com/5653381/141203841-9057ffa6-0367-4e24-af21-788ad65ecc3a.png)

I am using Visual Studio 2022 / Version 17.1.0 Preview 1.0.

I have tried with **.NET 5 Isolated (Out-of-process)**, it's a similar error.

However Azure Functions 4.0 with .NET 6, **In-Process** works just fine.

**Comment by NimbleKelly** [comment]
I was experiencing the same problem that you're describing, but managed to solve it by editing my system environment variables. My environment had a PATH set up with C:\Program Files (x86)\dotnet\ appearing before C:\Program Files\dotnet\.  When I moved the 64-bit dotnet folder up so it appeared before the 32-bit version, then debugging started working again. 

I arrived at this solution after attempting to create a new function app project using dotnet new on the command prompt.  I found that the dotnet.exe that the terminal was picking up was not one associated with the SDK.  Once I adjusted the path I was able to run dotnet new and also able to start debugging from Visual Studio.

**Comment by jaliyaudagedara** [comment]
@NimbleKelly, Thanks for the input. I just tried,
```
dotnet new
```
It doesn't even work.

Checked environment variables,
![image](https://user-images.githubusercontent.com/5653381/141400114-d110b0e3-b026-494b-8152-2fc709792878.png)

And yes, it's out of order. Moved the 64-bit dotnet before 32-bit version, and all is good now.

Thanks again.

**Comment by brettsam** [comment]
We've seen this in a few other places as well -- I think something with the ordering of the .NET SDK installation put things into a bad state. I'm glad you have figured this out and hopefully it helps others!

**Comment by brettsam** [comment]
For anyone else coming here -- this is noted in the .NET 6 known issues page now: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows
