### ISSUE TITLE
Activate Functions as Services instead of using DefaultFunctionActivator (.NET 6 Isolated Process)

### ISSUE THREAD

**Issue by WestDiscGolf** [Azure/azure-functions-dotnet-worker#716]
As part of the invocation of each Azure Function a new instance is created through the [DefaultFunctionActivator](https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Core/Invocation/DefaultFunctionActivator.cs) and this under the hood uses the `ActivatorUtilities.CreateInstance` method of instantiation. This works fine for most scenarios. However when you want to do something a bit more advanced with a different Ioc container, eg AutoFac, the Functions aren't created as the dependencies can't be resolved properly through the `ActivatorUtilities.CreateInstance` processing as it doesn't know about this concept and/or container involved.

ASP.NET Core also has this issue however it has the concept of registering the [Controller activator with the DI system](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreMvcBuilderExtensions.cs#L155) and using a different Activator ([ServiceBasedControllerActivator](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Mvc/Mvc.Core/src/Controllers/ServiceBasedControllerActivator.cs)) to instantiate the controllers instead. This allows for more complex scenarios with the Ioc container to work with the controller and not just a dependency the controller has.

It feels like this type of scenario is a potential as currently the DefaultFunctionActivator implements the [IFunctionActivator](https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Core/Invocation/IFunctionActivator.cs#L19).

Is there a potential for a `ServiceBasedFunctionActivator` and associated plumb in the future to allow for this scenario?

---

Done some initial digging to see if it's plausible and I believe it is.

To reduce the noise while I tried and work it through I have changed the `DefaultFunctionActivator` to resolve dependencies through the context IServiceProvider property instead of ActiviatorUtilities.

```C#
    internal class DefaultFunctionActivator : IFunctionActivator
    {
        public object? CreateInstance(Type instanceType, FunctionContext context)
        {
            if (instanceType is null)
            {
                throw new ArgumentNullException(nameof(instanceType));
            }

            if (context is null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            //return ActivatorUtilities.CreateInstance(context.InstanceServices, instanceType, Array.Empty<object>());
            return context.InstanceServices.GetService(instanceType);
        }
    }
```
And then manually registered the function in the sample FunctionApp

```C#
class Program
    {
        static async Task Main(string[] args)
        {
// #if DEBUG
//          Debugger.Launch();
// #endif
            //<docsnippet_startup>
            var host = new HostBuilder()
                //<docsnippet_configure_defaults>
                .ConfigureFunctionsWorkerDefaults()
                //</docsnippet_configure_defaults>
                //<docsnippet_dependency_injection>
                .ConfigureServices(s =>
                {
                    s.AddSingleton<IHttpResponderService, DefaultHttpResponderService>();


                    s.AddTransient<Function5>();

                })
                //</docsnippet_dependency_injection>
                .Build();
            //</docsnippet_startup>

            //<docsnippet_host_run>
            await host.RunAsync();
            //</docsnippet_host_run>
        }
    }
```

And this resolves Function5 when the request is made.

I was struggling to determine how I can work out all the functions at start up so they can be registered with the DI system. ASP.NET Core setup uses the ControllerFeature processing and then registers the controller types into the IServiceCollection.

```C#
        var feature = new ControllerFeature();
        builder.PartManager.PopulateFeature(feature);

        foreach (var controller in feature.Controllers.Select(c => c.AsType()))
        {
            builder.Services.TryAddTransient(controller, controller);
        }
```
My initial thought was to investigate when the `FunctionDefinition` is added to the `IFunctionsApplication` through the LoadFunction method but no access to the DI as I believe that would be too late in the processing (maybe?).

Thoughts?

**Comment by WestDiscGolf** [comment]
Added an example of how to do it manually with registering a ServiceBasedFunctionActivator with the DI system and registering the Function, GetWelcome in this example, with the AutoFac container builder to allow for named dependencies inside the function directly.

It appears to work, with the limited testing, really well however still feels a bit of a work around at the moment.

https://github.com/WestDiscGolf/AutofacAndAzureFunctions/commit/59ca0d134948732c94b5d7eb35cd721b46460bee

**Comment by fabiocav** [comment]
An easier/more appropriate approach is to implement your own `IFunctionActivator` and register that at startup. This is the intent of that API, giving you the ability to customize activation of those types.

Closing as answered, but let us know if you have any additional questions.
