### ISSUE TITLE
Investigate test failure E2ETests.HttpEndToEndTests.HttpProxy in Functions V4

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-dotnet-worker#717]
The test case `Microsoft.Azure.Functions.Tests.E2ETests.HttpEndToEndTests.HttpProxy` fails consistently when running the language worker end to end tests targeting Functions `V4` via the Core Tools. Please take a look. 

See build for more details: https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=41374&view=ms.vss-test-web.build-test-results-tab

**Comment by fabiocav** [comment]
That's expected in 4.0, as proxies no longer exist.

We should have [this test](https://github.com/Azure/azure-functions-dotnet-worker/blob/021fcb868981527587b74b7bfd2fe4062a144bef/test/E2ETests/E2ETests/HttpEndToEndTests.cs#L67) conditional and, if running against 4.0, skip it.

**Comment by Francisco-Gamino** [comment]
Thank you @fabiocav for the update. Could you please find a owner for this work item in your team? 

The worker is now onboarded for integration testing for V4 and the `$env:FUNCTIONSRUNTIMEVERSION` environment variable could be used to skip the test. E.g., https://github.com/Azure/azure-functions-dotnet-worker/blob/main/azure-pipelines.yml#L46. 
For  V4 integration testing, the value is set to `'4'`.

**Comment by brettsam** [comment]
v4 re-added proxies so I believe this is now all running as expected
