### ISSUE TITLE
Docker fails to build .NET 6.0 Azure Functions v4 

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#718]
The key areas of the docker file are per below which was scaffolded by VS 2022 Current:

```
FROM mcr.microsoft.com/azure-functions/dotnet:4.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
```

This is how the loca.settings.json file looks like:

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
  },
  "Host": {
    "LocalHttpPort": 7071
  }
}
```

I have had a perfectly-working `docker-compose` file used for .net core 3.1 but it starts showing the following failure when using .NET 6.0:

> [+] Building 0.4s (4/4) FINISHED
>  [internal] load build definition from Dockerfile                                                                                                                                                > 0.1s 
>  transferring dockerfile: 1.03kB                                                                                                                                                                > 0.0s 
> [internal] load .dockerignore                                                                                                                                                                     > 0.1s 
>  transferring context: 35B                                                                                                                                                                      > 0.0s 
> [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                                                                                                                     > 0.2s 
> ERROR [internal] load metadata for mcr.microsoft.com/azure-functions/dotnet:4.0                                                                                                                   > 0.2s 
> 
>  [internal] load metadata for mcr.microsoft.com/azure-functions/dotnet:4.0:
> 
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: mcr.microsoft.com/azure-functions/dotnet:4.0: not found

Any idea how to address this issue?

**Comment by arashcomsense** [comment]
@brettsam just wondering, is there a workaround or solution for this issue?

**Comment by brettsam** [comment]
The v4 image tags do not have ".0" at the end -- as we'll be incrementing the minor version (i.e 4.1, 4.2, 4.3) so using ".0" no longer made sense. So if you're migrating something from `3.0`, change it to just `4`.

**Comment by arashcomsense** [comment]
@brettsam Thanks, using just `4` addressed the issue but I started getting the following error despite docker's environment file has `FUNCTIONS_WORKER_RUNTIME=dotnet-isolated`:

> fail: Host.Startup[515]
> myv4func         |       A host error has occurred during startup operation '6bf62a71-09c8-453f-b0f1-c42f2f9d273a'.
> myv4func         |       Microsoft.Azure.WebJobs.Script.HostInitializationException: Did not find functions with language [dotnet].
> myv4func         |          at Microsoft.Azure.WebJobs.Script.Utility.VerifyFunctionsMatchSpecifiedLanguage(IEnumerable`1 functions, String workerRuntime, Boolean isPlaceholderMode, Boolean isHttpWorker, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Utility.cs:line 586
> myv4func         |          at Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionDescriptorsAsync(IEnumerable`1 functions, IEnumerable`1 descriptorProviders, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 731
> myv4func         |          at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFunctionDescriptorsAsync(IEnumerable`1 functionMetadata, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 513
> myv4func         |          at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 315
> myv4func         |          at Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 
> 264
> myv4func         |          at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
> myv4func         |          at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 292
> myv4func         | info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
> myv4func         |       Stopping JobHost
> myv4func         | Hosting environment: Production
> myv4func         | Content root path: /home/site/wwwroot

The function's project definition is per the following snippet:

```xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	 <OutputType>Exe</OutputType>
</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
  </ItemGroup>
```

**Comment by kshyju** [comment]
@arashcomsense Just to confirm, are you using the [dotnet-isolated image](https://hubgw.docker.com/_/microsoft-azure-functions-dotnet-isolated)?

 `mcr.microsoft.com/azure-functions/dotnet-isolated:4`

**Comment by arashcomsense** [comment]
@kshyju I started using the dotnet-isolated:4 image but got the following error message when running`docker-compose up` after the build:

```
myv4func | Unhandled exception. fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
myv4func|       Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recovSystem.InvalidOperationException: No process is associated with this object.
```

**Comment by arashcomsense** [comment]
Closing this issue as [this answer](https://github.com/Azure/azure-functions-dotnet-worker/issues/718#issuecomment-967302439) addressed it.
