### ISSUE TITLE
.NET 6.0 Azure Function v4 dotnet-isolated fails to run in docker due to Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#719]
The docker file's using the following images:

```
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4 AS base2
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
```
The `.env` file has the following entry:

```
FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
```
And the mentioned environment variables is referenced in the `docker-compose` file per the following line:

```
environment: 
      - FUNCTIONS_WORKER_RUNTIME
 ```

I am able to build and run the docker image but when placing an HTTP request, I get the following failure message:

> MyHttpTriggeredV4FuncApp    | fail: Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker[0]
> MyHttpTriggeredV4FuncApp    |       Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down
> MyHttpTriggeredV4FuncApp    | fail: Function.GetUserData[3]
> MyHttpTriggeredV4FuncApp    |       Executed 'Functions.GetUserData' (Failed, Id=5228c19e-2f4b-4ee7-8efe-3f9ac4a95395, Duration=48064ms)
> MyHttpTriggeredV4FuncApp    |       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.GetUserData
> MyHttpTriggeredV4FuncApp    |        ---> System.InvalidOperationException: Did not find any initialized language workers
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 321
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 95
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 572
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 518
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
> MyHttpTriggeredV4FuncApp    |          --- End of inner exception stack trace ---
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
> MyHttpTriggeredV4FuncApp    | fail: Host.Results[0]
> MyHttpTriggeredV4FuncApp    |       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.GetUserData
> MyHttpTriggeredV4FuncApp    |        ---> System.InvalidOperationException: Did not find any initialized language workers
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 321
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 95
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 572
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 518
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
> MyHttpTriggeredV4FuncApp    |          --- End of inner exception stack trace ---
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
> MyHttpTriggeredV4FuncApp    |          at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105

This is how the `.csproj` targets the framework and runs flawlessly in **VS 2002 Current** while there is no reference to `Microsoft.Azure.WebJobs` NuGet packages:

```xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	<OutputType>Exe</OutputType>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>10.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
```

What is not working or missing in the docker configuration?!

**Comment by arashcomsense** [comment]
@brettsam @kshyju any ideas on why I'm getting this failure?

**Comment by kshyju** [comment]
@arashcomsense Please refer [this ](https://github.com/kshyju/DotNetIsolatedDockerApp/blob/main/DotNetIsolatedDockerApp/Dockerfile)sample docker file which works for .net 6 oop function app.

**Comment by arashcomsense** [comment]
@kshyju Thanks, I am going to give it a try.

**Comment by arashcomsense** [comment]
@kshyju I compared my docker file with yours and mine does pretty much the same things as yours with a bit of difference in naming, aliases, etc. So, I did not find a reason to make any changes in my docker file. I observed a kind of behavior earlier today explained below:

- My http-trigger function in the function app has two stages: the first stage verifies a key-value pair and once the verification passes the 2nd stage is executed which has more complex algorithms and deals with database. Sending an invalid key-value pair to the function raises an error message and the function reports it well in a json payload *(so far so good)*. However, sending a valid key-pair value enables the 2nd stage of the function's logic and that step causes the failure that I reported in this issue. This failure does not raise when the function app is run in VS 2002 Current. 

How can it be explained?

/cc @brettsam @fabiocav

**Comment by kshyju** [comment]
@arashcomsense Can you please share a minimal repro of this issue? Link to a GitHub repo would be great. 

I wonder if it is an issue where your code(from the container) is not able to connect to the database. Can you try swapping the real database with a mocked version/in-memory data store to see the issue still happens?

**Comment by arashcomsense** [comment]
@kshyju Quite frankly I don't know how to come up with a minimal repo to have it duplicate the issue. The reason is that our software is using a good number of other NuGet packages including Microsoft's. A minimal dockerized function app without those libraries works well for me.

**Comment by kshyju** [comment]
@arashcomsense If a minimal dockerized app is not reproducing the error, it is hard for us to debug the issue you are running into. Probably some of your dependencies are causing the issue. I suggest removing some of those dependencies and narrowing it down to figure out which dependency is causing it. 

Closing this issue as there is no action item needed from our side. Thanks!
