### ISSUE TITLE
NRE accessing FunctionContext.RetryContext

### ISSUE THREAD

**Issue by realSergiy** [Azure/azure-functions-dotnet-worker#720]
Hi, I am currently experiencing NRE trying to access the RetryContext. Please apply the defaults originally proposed.

_Originally posted by @fabiocav in https://github.com/Azure/azure-functions-dotnet-worker/pull/357#r602522856_

Kind Regards,
Sergiy

**Comment by fabiocav** [comment]
I'm assuming the null reference you're getting is with a scenario where the context is null (as opposed to somewhere else when the feature is enabled), is that correct? 

If so, what version of the host are you running against? This information should not be null coming from the host, so if this is happening in a recent version, we may need to take a look there as well.

If you can share your code, that would make this a little more clear. 

Thanks!

**Comment by kshyju** [comment]
@realSergiy Also, did you have a [retry policy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry) defined for your app?
