### ISSUE TITLE
Unable to update or manipulate the existing HttpResponseData object in out-of-process Azure Function V4's middleware

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#723]
I have an out-of-process .NET 6.0 HTTP-triggered Azure Function App v4 which needs to add a custom header to every single produced response. The best approach is to write a middleware to take care of it for us but I could not "update" the existing `HttpResponseData` object produced by the function. Apparently there is no way to access an existing `HttpResponseData` instance. 

This is how to access HttpRequestData from FunctionContext in a middlware:
```cs
public static HttpRequestData GetHttpRequestData(this FunctionContext funcContext)
{
    var kv = funcContext?.Features.SingleOrDefault(f => f.Key.Name == "IFunctionBindingsFeature");
    var funcBinding = kv?.Value;
    var type = funcBinding?.GetType();
    var inputData = type?.GetProperties().Single(p => p.Name == "InputData").GetValue(funcBinding) as IReadOnlyDictionary<string, object>;
    return inputData?.Values?.SingleOrDefault(obj => obj is HttpRequestData) as HttpRequestData;
}
```
I found [a code in this Github repo](https://github.com/elmahio/Elmah.Io.Functions.Isolated/blob/065090253ff62d9eda54d6a00204996bd5f94235/src/Elmah.Io.Functions.Isolated/FunctionContextExtensions.cs#L33-L51) that creates a new `HttpResponseData` object but it does not suggest a way to access the existing `HttpResponseData`. What is the solution for this problem or is it yet to be implemented?

**Comment by arashcomsense** [comment]
@fabiocav Just wondering, any updates or progress on this issue?

**Comment by fabiocav** [comment]
We're working through some of those details as part of https://github.com/Azure/azure-functions-dotnet-worker/issues/530, so I'll close this in favor of that issue.

Thanks!
