### ISSUE TITLE
Dependency injection doesn't work for static function implementations

### ISSUE THREAD

**Issue by aggieben** [Azure/azure-functions-dotnet-worker#725]
I used the `dotnet new` templates (for dotnet-isolated) to create a simple example to compare styles of functions - a plain class implementation vs a static class / static method implementation.  See the difference here:

![image](https://user-images.githubusercontent.com/1321/142494101-ee864c1a-9c79-4b22-9e4d-256199dcb187.png)

These should ostensibly be identical in behavior, but the injected parameters to the static function the left are null, while the constructor-injected parameters on the right work as expected.  What is the intended way of accomplishing dependency injection in a static method?  Is this a bug, or are we expected to use the service locator pattern?

I've attached a zip of my whole project folder here:

[di-test.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/7565880/di-test.zip)

**Comment by kshyju** [comment]
The behavior you are seeing is by design. If you want dependency injection in your dotnet isolated projects, use a non static class and use constructor injection. Is there a reason you prefer to not do that? 🤔

**Comment by aggieben** [comment]
Yep - I'm actually writing my function in F♯, and it seems a bit more idiomatic to me to just use a function rather than a non-static type.  I realize that's really just an aesthetic preference 🤷‍♂️

**Comment by fabiocav** [comment]
@aggieben we do intend to provide a binding that would resolve from services, but that isn't in place at the moment. In the meantime, the information shared above by @kshyju is the current behavior, but I hope this helps.
