### ISSUE TITLE
Question about out of process functions and custom QueueProcessor

### ISSUE THREAD

**Issue by ilmax** [Azure/azure-functions-dotnet-worker#726]
Hi, I have an azure function that uses a queue trigger and was trying to change the TTL of the messages inserted in the poison queue, since apparently this feature is not implemented by the framework, I went with a custom implementation of a `QueueProcessor` and a custom `IQueueProcessorFactory`, registered the latter in the DI container but my custom implementation is not picked up. I think that's because this is handled in the host (e.g. on the other side of the gRPC channel) Am I correct? 
If that's the case, is there an option to replace/customize that service without switching to an in-process function?

**Comment by fabiocav** [comment]
This is not an option with the OOP model and currently, we have no plans to expose this. The primary mechanism for this would be to expose additional configuration settings to control the behavior of the extensions as needed.
