### ISSUE TITLE
Question: Is it possible to change the loglevel for an Azure Function in isolated mode without new deploy?

### ISSUE THREAD

**Issue by kelps** [Azure/azure-functions-dotnet-worker#730]
Is it possible to change the loglevel for an Azure Function in isolated mode (running in .NET5 now, but soon in .NET6), without being forced to deploy a full new version just to change the host.json file? Everything I found so far says I have to change host.json.

**Comment by fabiocav** [comment]
Any configuration supported by host.json can also be specified using app settings, which would address your requirement.

In order to do that, you can follow the pattern documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurefunctionsjobhost__)

**Comment by kelps** [comment]
It did work, almost as expected. If I use the ILogger provided by the FunctionContext I can see all levels of log configured in the host.json file or app dashboard settings, even trace and debug. But if I use injected ILogger<T> in my inner code, I can only use up to Information, no matter what I configure either at host.json or the dashboard. 

By "see", I mean both in the stream and on Azure Insights. Am I missing something? I don't want to have to pass around my function's ILogger instance down the chain in every method as a parameter to be able to do debug and traces in my code....
