### ISSUE TITLE
Is there an ActivitySource or DiagnosticSource that can be listened to?

### ISSUE THREAD

**Issue by michielvoo** [Azure/azure-functions-dotnet-worker#731]
We are setting up distributed tracing across multiple applications, some of which are Azure Functions worker applications (the `dotnet-isolated` runtime v3 and targeting .NET 5). We do not use Application Insights. What, if any, diagnostic source should we listen to in order for the runtime to start and stop an activity for each function invocation?

For context, here's how one could listen to the activity start and stop diagnostics in an ASP.NET Core application. In practice we use the OpenTelemetry library to do this, which uses a more standards-compliant `ActivityListener`. This code snippet is just to illustrate how one would discover the name of any available diagnostic sources and the names of their diagnostics:

``` lang-cs
DiagnosticListener.AllListeners.Subscribe(listener =>
{
    if (listener.Name == "Microsoft.AspNetCore")
    {
        listener.Subscribe(diagnostic =>
        {
            if (diagnostic.Key == "Microsoft.AspNetCore.Hosting.HttpRequestIn.Start")
            {
                // ...
            }
            else if (diagnostic.Key == "Microsoft.AspNetCore.Hosting.HttpRequestIn.Stop")
            {
                // ...
            }
        });
    }
});
```

What is the listener name and what are the diagnostic names we should use in an Azure Functions worker app?

Edit: it seems that `DiagnosticListener.AllListeners` remains empty, so the Azure Functions worker runtime does not have any, is that correct?

Edit: adding a listener to `ActivitySource.AddActivityListener(ActivityListener)` does not result in any callbacks to the listener, so it seems the Azure Functions worker runtime also does not have any activity sources.

**Comment by michielvoo** [comment]
I have found that there are several OpenTelemetry contribution packages for .NET available in [the opentelemetry-dotnet-contrib repository here on GitHub](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src), including one for AWS Lambda. Will Microsoft publish a similar contribution there, or will OpenTelemetry support be part of a future runtime release?

**Comment by fabiocav** [comment]
@michielvoo there is work currently in progress for host instrumentation to do exactly what you're requesting. We'll also be tracking worker specific events you can listen to. 

Doesn't look like we have a specific issue tracking what you're looking for on the repo at the moment, so I'm leaving this one open. 

There will be a number of enhancements made in logging, and we're tracking them here https://github.com/Azure/azure-functions-dotnet-worker/labels/logging

**Comment by fabiocav** [comment]
@brettsam @kshyju for awareness.

**Comment by michielvoo** [comment]
@fabiocav I cannot find a specific issue to track the progress of the implementation of host instrumentation. Could you give an update about this?

**Comment by pihai** [comment]
any news on this?

**Comment by juantarquino-ssb** [comment]
Any news on this?

**Comment by jviau** [comment]
We now have an activity source you can listen to: `Microsoft.Azure.Functions.Worker`

https://github.com/Azure/azure-functions-dotnet-worker/blob/2d16152a9c9cad8ed71e8aae1f660d7025a9c498/src/DotNetWorker.Core/Diagnostics/FunctionActivitySourceFactory.cs#L14
