### ISSUE TITLE
EventSource FunctionsEventSource throws 'System.OutOfMemoryException'

### ISSUE THREAD

**Issue by alsami** [Azure/azure-functions-dotnet-worker#734]
Hello,

after upgrading some functions that consume event-hubs to the isolated variant with .NET 6 and Azure Functions 4, there is a strange behavior.

I keep on seeing this log entry in application-insights:
`AI (Internal): [FunctionsEventSource] ERROR: Exception in Command Processing for EventSource FunctionsEventSource: Exception of type 'System.OutOfMemoryException' was thrown.`

Interstingly, the function executions are not reported to Application-Insights anymore

![image](https://user-images.githubusercontent.com/2729205/143896440-4fdb2dd7-0e2e-4076-a6c5-ca3aed8db823.png)

 

When I navigate to the function app and press on monitor -> application insights, I can see that the function is being executed. 

![image](https://user-images.githubusercontent.com/2729205/143896220-a5283f6c-dec1-45fe-b88d-380b63c0409a.png)

I've found a similar issue ([#7393](https://github.com/Azure/azure-functions-host/issues/7393), #700) but the exceptions mentioned there are a little bit different. As far as I understood, there is no fix for it yet.

**Comment by fabiocav** [comment]
Can you share more information about the plan you're using and whether you have 64-bit enabled? Thanks.

**Comment by alsami** [comment]
Yes, certainly. 

I am running the functions with a serverless windows consumption plan and I have enabled 64-bit for the function.

Yesterday, for testing purposes, I've switched to Linux by recreating the function and there the executions have been reported but also only very sporadic with sometimes gaps of more than 7 minutes.

Please let me know if you need more information.

**Comment by fabiocav** [comment]
@alsami that does sound like a separate issue. So to confirm, you don't see this issue when running in Linux, correct? 

The information you've shared confirms our suspicion that you're impacted by an issue that is currently being addressed.

Could you add the following app setting to your app to see if that helps?

`COMPLUS_GCHeapHardLimit` = `1610612736`

Thanks!

**Comment by alsami** [comment]
> So to confirm, you don't see this issue when running in Linux, correct?

That's not completely the case. There are executions being reported, but not fully.

> Could you add the following app setting to your app to see if that helps?
> 
> `COMPLUS_GCHeapHardLimit` = `1610612736`

I'll try to do that and get back to you.

I can also tell you that I tried switching back to the in-process model, with linux using event-hubs. Same behavior regarding the execution count - the exception I reported is gone or at least I haven't seen it anymore.

**Comment by neyaki** [comment]
I have a similar issue with Azure Durable Function executions.  Happy to provide more details when needed.

Azure Runtime version: 4.0.1.16815
Stack: PowerShell Core
Platform: 64-bit

`Trace Properties
Event time	**12/7/2021, 6:00:01.085 PM (Local time)**	
Device type	**PC**	
Message	**AI (Internal): [FunctionsEventSource] ERROR: Exception in Command Processing for EventSource FunctionsEventSource: Exception of type 'System.OutOfMemoryException' was thrown.**	
Severity level	**Verbose**	
Telemetry type	**trace**	
Source of synthetic traffic	**SDKTelemetry**	
Client IP address	**0.0.0.0**	
Role name	**********
Role instance	**31a6662140fcb4e6b7c1c19c36343205a7192af19bbe1559083a700e1efd25d2**	
SDK version	**dotnetc:2.17.0-146**	
Sample rate	**1**`

**Comment by neyaki** [comment]
> @alsami that does sound like a separate issue. So to confirm, you don't see this issue when running in Linux, correct?
> 
> The information you've shared confirms our suspicion that you're impacted by an issue that is currently being addressed.
> 
> Could you add the following app setting to your app to see if that helps?
> 
> `COMPLUS_GCHeapHardLimit` = `1610612736`
> 
> Thanks!

I had the above added, but that resulted in total Function unavailability.

**Comment by neyaki** [comment]
@fabiocav any update?

**Comment by hkusulja** [comment]
I also have the same issue, workaround helps. Any update for fixing the issue permanently?

**Comment by ablyler** [comment]
I think this is related to https://github.com/Azure/azure-functions-host/issues/7881. Setting the app setting `COMPLUS_GCHeapHardLimit` to `0x60000000` fixed the issue for us.

**Comment by fabiocav** [comment]
@neyaki / @alsami  can you confirm whether setting the value in hex (`0x60000000`) as recommended by @ablyler above helps?

**Comment by alsami** [comment]
@fabiocav I've switched to linux and old model (in-process) again because the functions are business critical.

Hopefully @neyaki can shed some light on this.

**Comment by neyaki** [comment]
> @neyaki / @alsami can you confirm whether setting the value in hex (`0x60000000`) as recommended by @ablyler above helps?

I've made the setting, so far so good (whereas previously it borked the app straight away).  I will monitor it for a week, if that's alright.

**Comment by neyaki** [comment]
Hey everyone (@alsami and @fabiocav)

Since the implementation of the config setting, there were no more Out of Memory errors 👍

**Comment by hkusulja** [comment]
so, what is permanent resolution ?

**Comment by brettsam** [comment]
The permanent resolution is that `COMPLUS_GCHeapHardLimit ` will be set by the platform so you won't need to take any action. This rollout may already be complete; we will double-check and report back.

**Comment by fabiocav** [comment]
Closed as answered. Please let us know if you continue to run into issues.
