### ISSUE TITLE
Required .azurefunctions directory is not created when publishing in an Azure DevOps pipeline on the ubuntu-latest agent

### ISSUE THREAD

**Issue by michielvoo** [Azure/azure-functions-dotnet-worker#741]
Executing `dotnet publish` for a solution with an Azure Functions worker application targeting .NET 5 should generate an `.azurefunctions` directory in the output directory. This directory contains several assemblies, for example `Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.dll`.

Inside the publish directory there is a file named `extensions.json` which lists extensions' name, type, and hint path. The hint path points to the assemblies in the `.azurefunctions` directory, for example:

```
{
    "name": "Startup",
    "typeName": "Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.Startup, Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=551316b6919f366c",
    "hintPath": "./.azurefunctions/Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.dll"
}
```

Running `dotnet publish` in an Azure DevOps pipeline using the [`ubuntu-latest` agent](https://github.com/actions/virtual-environments/blob/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md) produces an artifact that does not contain the `.azurefunctions` directory. After deploying the artifact using `az functionapp deployment source config-zip` the application does not work (routes to HTTP-triggered functions return 404). Troubleshooting in the Azure Portal using the "Availability and Performance" diagnostics category helped me find this runtime error related to the extension mentioned above:

> Unable to load startup extension 'Startup' (Type: 'Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.Startup, Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=551316b6919f366c'). The type does not exist. Please validate the type and assembly names.

Switching to the [`windows-latest` agent](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) solves the problem (see also [this comment](https://github.com/Azure/azure-functions-dotnet-worker/issues/427#issuecomment-890276377) on #427).

What is missing on the Microsoft-hosted `ubuntu-latest` agent that causes this problem? 
([Link to a list of software available on the agent](https://github.com/actions/virtual-environments/blob/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md))

**Comment by michielvoo** [comment]
I noticed that the [Windows agent](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) contains these 2 Visual Studio components:

- Component.Microsoft.VisualStudio.Web.AzureFunctions
- Microsoft.VisualStudio.ComponentGroup.AzureFunctions

Is an installation of Visual Studio required to build Azure Functions worker applications?

**Comment by fabiocav** [comment]
We shouldn't have a dependency on either of those components.

Flagging this for investigation, but would it be possible to share the following information to make sure we have a valid repro?

1. The csproj file
2. If you have the ability to share a build log file, we can provide instructions on how to share that privately
3. Any output from your build process in DevOps (ideally, with higher verbosity levels)

Thanks!

**Comment by michielvoo** [comment]
The builds that produced an invalid artifact were not retained unfortunately. I tried to create a small project to reproduce this, but I cannot reproduce it anymore.
