### ISSUE TITLE
Debug Azure Functions V4 with .NET 5/6 in Visual Studio 2022 Preview

### ISSUE THREAD

**Issue by FahaoTang** [Azure/azure-functions-dotnet-worker#743]
Hi team,
I have created a function app using .NET 5 or .NET 6 in VS2022.
However, when I tried to debug, I hit the following error:
[Port 7071 is unavailable. Close the process using that port, or specify another port using --port [-p]
](https://kontext.tech/column/cloud-azure/791/port-7071-is-unavailable-close-the-process-using-that-port-or-specify-another-port-using-port-p)

I can resolve it if the project is a in-process app by changing the port number however I'm using dotnet worker isolated approach (as I want to utilize all the dependency injection benefits). Can you provide some guidance about how to fix this? I can obviously directly run the app through func SDK CLIs but I want to easily debug with VS2022. I tried to play around with VS 2022 DEBUG command line argument but it doesn't work.

**Comment by kshyju** [comment]
You should be able to customize the port number to be used via launchsettings.json file. I was able to verify this in a .NET 6 isolated function app and VS 2022 17.3.6 (latest stable as of today)

![image](https://user-images.githubusercontent.com/144469/196557305-7bc64558-65dc-4eba-a22e-640367001c91.png)


![image](https://user-images.githubusercontent.com/144469/196557193-f6e821a4-1fb7-44e9-96be-33e4fce5c8f3.png)

Let us know if you still run into issues.
