### ISSUE TITLE
Update to drive Portal UX

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#75]
- Plan update to stacks that allows us to specify the language, version, and "mode" (embedded or isolated) for .NET
- Talk with Elliot/Allison about whether we can update the UX to look more like Web Apps:

Functions:
![image](https://user-images.githubusercontent.com/1089915/105535576-dea96480-5ca3-11eb-92d1-a30a96784d7c.png)

	
Web Apps:
![image](https://user-images.githubusercontent.com/1089915/105535589-e406af00-5ca3-11eb-8ae7-0edbe7dd030e.png)

- This would remove the need for a third dropdown in the Function create flow and move everything to one selection. For example, we'd have ".NET Core 3.1 embedded", ".NET Core 3.1 isolated", and ".NET 5 isolated"

**Comment by fabiocav** [comment]
Closing as done.
