### ISSUE TITLE
Updating Microsoft.Azure.Functions.Worker.Extensions.Storage to 5.0.0 breaks BlobInputAttribute

### ISSUE THREAD

**Issue by KonKri** [Azure/azure-functions-dotnet-worker#762]
Upgrading in my .NET 6 isolated function app, the Microsoft.Azure.Functions.Worker.Extensions.Storage package to 5.0.0 from 4.0.4 breaks the Blob Input Binding in my function:
```
[BlobInput("container/file.xlsx", Connection = "StorageAccountConnStr")] byte[] fileBytes
```
```
A host error has occurred during startup operation '<guid>'.
[2021-12-20T17:08:50.997Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.
Value cannot be null. (Parameter 'provider')
```

and the VS 2022 freezes till I close the console window.

**Comment by kshyju** [comment]
Hi @KonKri What trigger are you using for the function? Could you share the full function signature you are using?

**Comment by fabiocav** [comment]
Can you also share more information about how you have your connection string setup for your app?

**Comment by fabiocav** [comment]
The exception above is also about the secret provider, which is not directly related to the extension. Have you validated that downgrading the extension reference fixes the problem when running on the same function app? Thanks!
