### ISSUE TITLE
Handling wildcard CORS in HttpTrigger function?

### ISSUE THREAD

**Issue by craigomatic** [Azure/azure-functions-dotnet-worker#764]
I'm building a SaaS solution that uses Azure Functions to host the APIs via HttpTriggers. 

For the most part this has worked well, however it seems not possible to support wildcard domains in the Azure portal (see https://github.com/Azure/azure-functions-host/issues/3948), and very annoying to programmatically add them in via the resource manager APIs, so I decided to try the middleware APIs to reuse some of the CORS code from a typical aspnet core project.

I have this in my Program.cs:

```csharp
.ConfigureServices(services =>
                {
                    services.AddCors(options =>
                    {
                        options.AddPolicy(name: "myorigins",
                            builder =>
                            {
                                builder.WithOrigins("https://*.mydomain.com")
                                    .SetIsOriginAllowedToAllowWildcardSubdomains();
                            });
                    });
)
```

In a typical aspnet core project I can then ```app.UseCors("myorigins")``` later in the bootstrap code - because I couldn't work out how to do this in the function, I've instead created middleware that reuses the [CorsService](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/CORS/src/Infrastructure/CorsService.cs) and incorporates [the workarounds](https://github.com/Azure/azure-functions-dotnet-worker/issues/414) to access the HttpRequestData/HttpResponseData.

You can see the gist over here: https://gist.github.com/craigomatic/32c24e06262da0d332294075c053298a

Is there a better way to do this? 

Ideally, I'd like to reuse the same code pattern as a typical aspnet core app.

**Comment by fabiocav** [comment]
This is not really supported today. The portal/ARM configuration are the only supported options at the moment.

Thanks!
