### ISSUE TITLE
Question: What does the extension name mean in AssemblyInfo?

### ISSUE THREAD

**Issue by WestDiscGolf** [Azure/azure-functions-dotnet-worker#766]
I have been working through an issue I have been experiencing with the Cosmos DB change feed trigger functionality in .NET 6 isolated Azure Function.

I couldn't work out why I was getting errors which referred to "*.Webjob.*" namespaces. I ended up adding a new stand alone project into this repo source code locally, referencing the Worker.Extensions.CosmosDB project and trying to get it to work. Which is did!

This got me thinking what is the difference between the source project and the published nuget package I am consuming?

First I noticed that the csproj is referencing version 4.0.0 preview 2 and the nuget package I am consuming is 3.0.9. Then in the AssemblyInfo I noticed that also have the version change - 
https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.CosmosDB/src/Properties/AssemblyInfo.cs#L6 - which

However the name of the extension information is still referencing the webjobs namespace, this doesn't feel right?

`[assembly: ExtensionInformation("Microsoft.Azure.WebJobs.Extensions.CosmosDB", "4.0.0-preview2")]`

Should the above not be ...

`[assembly: ExtensionInformation("Microsoft.Azure.Functions.Worker.Extensions.CosmosDB", "4.0.0-preview2")]`

?

**Comment by fabiocav** [comment]
@WestDiscGolf the extension there is the reference to the underlying binding extension that will be loaded by the host when the referenced extension is used by the Worker. Those are still WebJobs extensions (the same set of extensions used in the in-proc model), so that is correct.

Let us know if this helps or if you need more information. Thanks!

**Comment by WestDiscGolf** [comment]
@fabiocav Thanks for the update. Appreciate you taking the time to reply.
