### ISSUE TITLE
Release notes for 5.0.0

### ISSUE THREAD

**Issue by dfibuch** [Azure/azure-functions-dotnet-worker#768]
Is there a plan to provide release notes for what changed in 5.0.0? Currently on 4.0.4 and seeing as its major version change I'm expecting there to be breaking changes?

**Comment by stap123** [comment]
There's at least one, the `[TableOutput]` attribute is gone but no release notes to let us know why.

**Comment by fabiocav** [comment]
@dfibuch the relevant release notes are available [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/CHANGELOG.md), and the extension here is primarily a view of what is provided by the underlying extension, but we'll make sure we bring those notes to the releases here as well.

**Comment by dfibuch** [comment]
> @dfibuch the relevant release notes are available [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/CHANGELOG.md), and the extension here is primarily a view of what is provided by the underlying extension, but we'll make sure we bring those notes to the releases here as well.

Perfect, thank you for that. Closing issue.
