### ISSUE TITLE
Release schedule for Microsoft.Azure.Functions.Worker.Extensions.CosmosDB?

### ISSUE THREAD

**Issue by WestDiscGolf** [Azure/azure-functions-dotnet-worker#769]
Currently the cosmosdb trigger for change feed only works with the version 4.0.0-preview2 nuget package.

What is the schedule to release a GA version of the 4.x package for .NET 6 Isolated processing model?

Cheers

**Comment by fabiocav** [comment]
@WestDiscGolf I'm assigning this to the current sprint so we can get this out ASAP. Apologies for the delay.

**Comment by julealgon** [comment]
@fabiocav  do you have any updates on this? How long do your sprints usually take so we can get a sense for when this will be released?

**Comment by joshlang** [comment]
I'm super-glad to see this already in the works.  Just about to start a project that use a custom serializer and want to use azure functions to handle the change feed!

**Comment by DavidJFowler** [comment]
@fabiocav Any updates on this?

**Comment by fabiocav** [comment]
Apologies for the delayed response. Updating stale issues, but all releases are currently and we're working on process improvements to ensure they stay in sync. 

Thank you!

**Comment by WestDiscGolf** [comment]
If anyone else stumbles across this issue there is a now a newer release - https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.CosmosDB/4.3.0
