### ISSUE TITLE
function not being started on net6 & v4 functions

### ISSUE THREAD

**Issue by shrohilla** [Azure/azure-functions-dotnet-worker#772]
I created a function with Kafka trigger and I started facing the issue on Visual Studio :-
This exception was originally thrown at this call stack:
System.Uri.CreateThis(string, bool, System.UriKind, System.UriCreationOptions)
System.Uri.Uri(string)
Grpc.Net.Client.GrpcChannel.ForAddress(string, Grpc.Net.Client.GrpcChannelOptions)
Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.AddGrpc.AnonymousMethod__1_1(System.IServiceProvider) in GrpcServiceCollectionExtensions.cs
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, TArgument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, TArgument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
...
[Call Stack Truncated]

While trying with Core tools :-
[2022-01-06T20:15:32.195Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

I tried to find this function in hostbuilder it was not available there, could you suggest if we need to fix this how can we ?

Code available on repository -- https://github.com/shrohilla/dotnet-out-proc
following the documentation -- https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

cc @fabiocav @lpapudippu

**Comment by fabiocav** [comment]
@shrohilla how are you running the worker? The exception above indicates a failure parsing the host endpoint, which is automatically passed in by the host when running.

**Comment by fabiocav** [comment]
@shrohilla looking at the project in the repo, looks like the project was modified and is missing the SDK reference (that is currently commented out) and using an older version of the worker. 

Can you please update to the following?

```
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.2" />
```

**Comment by kshyju** [comment]
Without the Worker.Sdk package reference, VS will not recognize the project as a function app (See the below screenshot, function app icon missing). So, the command VS issues for your debug session may not be correct.

![image](https://user-images.githubusercontent.com/144469/148822325-1e9d2fcd-98dc-456c-a28a-ca8429634d0a.png)

Once you add a reference to `Microsoft.Azure.Functions.Worker.Sdk`, it will be detected as a function app and F5 debugging should work as expected. 


![image](https://user-images.githubusercontent.com/144469/148822643-30ab945c-1bb8-4d84-abff-212bcf7a0961.png)

Also, consider upgrading to the latest stable version of packages as suggested above.

**Comment by fabiocav** [comment]
Closing this as I got confirmation from @shrohilla that this was resolved.

**Comment by shrohilla** [comment]
Thanks alot @fabiocav this is resolved.
