### ISSUE TITLE
We need a worker SDK extension package for Tables

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#787]
Tables were removed from Microsoft.Azure.Functions.Worker.Extensions.Storage v5. This mirrors the removal from Microsoft.Azure.WebJobs.Extensions.Storage.

The table binding extensions are now in a new package: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables/

The SDK needs to mirror this as well.

**Comment by anthonychu** [comment]
Dupe of #404
