### ISSUE TITLE
Scaling out doenst seem to trigger

### ISSUE THREAD

**Issue by PBeckerr** [Azure/azure-functions-dotnet-worker#792]
This behavior was already described here but the bot closed it :/
_Originally posted by @snowke in https://github.com/Azure/azure-functions-dotnet-worker/issues/649#issuecomment-960114915_

Im running into the same issue and its really easy to reproduce that dotnet-isolated never scales beyond one, i can create 2 function apps one with dotnet and one with dotnet-isolated, deploy them and load test both, isolated stays at 1 instance vs inproc scales up to (in my case) 6 instance which is both reflected in application logs and in request/s in the load testing tool, isolated even begins to drop request exactly like @snowke described it

**Comment by snowke** [comment]
@PBeckerr I was eventually able to get a hold of Microsoft support and was told to do the following

> In order to correct this issue they have suggested that the site be updated to use version 1.2.0 of the Microsoft.Azure.Functions.Worker.Sdk package

I made that change and run the load tests again.  At first, it did not work as expected. I was 30 minutes into a load test without any new instances being created.  Then around the 30-minute mark, it shot up to 15+ instances.

The next day, it started autoscaling as expected.  I still don't know what happened on the first run, but just in case you didn't see anything at first I wanted you to know how it played out for me.

**Comment by PBeckerr** [comment]
@snowke You are absolutely right, updated nuget packages, redoployed and now its scaling up/down!
