### ISSUE TITLE
Time trigger function suddenly stops firing

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-dotnet-worker#793]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#26710](https://github.com/Azure/azure-sdk-for-net/issues/26710).

### Library name and version

Microsoft.Azure.Functions.Worker 1.5.1

### Describe the bug

I have an azure function (hosted on ASP P1v3) that has near 20 time trigger functions and near 20 service bus functions. From time to time timer trigger functions stops firing. 

What can I do? 

Option 'Always on' is set to 'On'

### Expected behavior

Timer trigger azure functions firing

### Actual behavior

Timer trigger azure functions not firing

### Reproduction Steps

I don't know how to reproduce. I just have azure functions with service bug trigger, timer trigger and http trigger
there are next schedules:
0 */15 * * * *
0 1 * * * *
0 */15 * * * *
0 */5 * * * *
0 */8 * * * *
0 */6 * * * *
0 0 * * * *
0 */1 * * * *
*/1 * * * *
*/1 * * * *
0 10 0 * * *
0 1 0 * * *
0 0 */2 * * *
0 0 6 * * *
0/40 * * * * *
0 */1 * * * *
0 0 1 * * *
0 */5 * * * *
0/5 * * * *
0 0 2 * * *

### Environment

App Service Plan P1v3: 1
OS Windows
Azure function runtime version: 3
.NET 5.0
Worker runtime: dotnet-isolated
Microsoft.Azure.Functions.Worker.Extensions.Time 4.1.0
Microsoft.Azure.Functions.Worker.Sdk 1.0.4
Microsoft.Azure.Functions.Worker 1.5.1

**Comment by brettsam** [comment]
This issue may be related to things like the ScaleController or Functions host -- it's highly recommended that issues like this are resolved via a support ticket as we'll need more in-depth information about timelines and resources.
