### ISSUE TITLE
Flood of HTTP related logging since upgrading to host v4

### ISSUE THREAD

**Issue by shelbaz** [Azure/azure-functions-dotnet-worker#796]
#### Is your question related to a specific version? If so, please specify:
Azure Function Core Tools v4 and Azure Functions .NET 6

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I just upgraded from Azure Functions .NET 5 to .NET 6 Preview (isolated). Whenever my function runs, both locally via Core Tools v4 and in Azure Function .NET 6 Preview, I see a flood of logs like this (multiple ones every second):

[2021-10-03T19:54:21.385Z] x-ms-lease-action:renew
[2021-10-03T19:54:21.386Z] x-ms-lease-id:53510324-35c0-47e9-b6e1-fd2f8ef8fb24
[2021-10-03T19:54:21.386Z] x-ms-version:2020-08-04
[2021-10-03T19:54:21.387Z] Accept:application/xml
[2021-10-03T19:54:21.388Z] x-ms-client-request-id:8902e6ea-1961-4ad9-8f87-bb0f6f099010
[2021-10-03T19:54:21.388Z] x-ms-return-client-request-id:true
[2021-10-03T19:54:21.389Z] User-Agent:azsdk-net-Storage.Blobs/12.9.0,(.NET 6.0.0-rc.1.21451.13; Microsoft Windows 10.0.19043)
[2021-10-03T19:54:21.389Z] x-ms-date:Sun, 03 Oct 2021 19:54:21 GMT
[2021-10-03T19:54:21.390Z] Authorization:REDACTED
[2021-10-03T19:54:21.390Z] client assembly: Azure.Storage.Blobs
[2021-10-03T19:54:21.394Z] Response [af72cd2f-b19c-4597-b217-d9a4d1aeea5c] 200 OK (00.0s)
[2021-10-03T19:54:21.396Z] Transfer-Encoding:chunked
[2021-10-03T19:54:21.396Z] ETag:"0x8D9869716532FD0"
[2021-10-03T19:54:21.397Z] Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
[2021-10-03T19:54:21.397Z] x-ms-request-id:5cb1884c-8736-4c95-b310-872c0063e5aa
[2021-10-03T19:54:21.398Z] x-ms-version:2020-08-04
[2021-10-03T19:54:21.399Z] x-ms-lease-id:2470eee6-d47a-4ac4-b9db-4f1967aa1165
[2021-10-03T19:54:21.399Z] Date:Sun, 03 Oct 2021 19:54:21 GMT
[2021-10-03T19:54:21.400Z] Last-Modified:Sun, 03 Oct 2021 17:56:12 GMT
[2021-10-03T19:54:21.401Z] Response [8902e6ea-1961-4ad9-8f87-bb0f6f099010] 200 OK (00.0s)
[2021-10-03T19:54:21.407Z]
[2021-10-03T19:54:21.407Z] Transfer-Encoding:chunked
[2021-10-03T19:54:21.408Z] ETag:"0x8D9869716D04F10"
[2021-10-03T19:54:21.409Z] Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
[2021-10-03T19:54:21.409Z] x-ms-request-id:72742bcb-343f-4112-a41f-b8c296ac8534
[2021-10-03T19:54:21.410Z] x-ms-version:2020-08-04
[2021-10-03T19:54:21.411Z] x-ms-lease-id:53510324-35c0-47e9-b6e1-fd2f8ef8fb24
[2021-10-03T19:54:21.411Z] Date:Sun, 03 Oct 2021 19:54:21 GMT
[2021-10-03T19:54:21.412Z] Last-Modified:Sun, 03 Oct 2021 17:56:13 GMT
[2021-10-03T19:54:21.412Z]
[2021-10-03T19:54:22.362Z] Request [976fd430-xxxx-xxxx-b0be-ebf5d4a10565] GET https://storeaccountxxx.queue.core.windows.net/xxx-queue/messages?sv=2020-02-

These logs appear to be related to function storage and queue/eventhub pooling/leases. But I can't figure out how to filter these out (what their sources are, tried System.Net.Http.HttpClient without luck). The only way to stop them for now is to set default logLevel to Warning but that will filter out other useful logs.

This did not happen with v3.

Any advice would be greatly appreciated.

*** This is a copy of issue: https://github.com/Azure/azure-functions-host/issues/7740 , which was closed and never resolved with the same issue. 

Hosts.Json: 

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true
      }},
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Information"
    }
  },
  "extensions": {
    "http": {
      "routePrefix": "aspire-sp-gateway"
    },
    "durableTask": {
      "hubName": "%TaskHubName%",
      "storageProvider": {
        "maxQueuePollingInterval": "00:00:01",
        "partitionCount": 4
      }
    },
    "tracing":
    {
      "consoleLevel": "verbose"
    }
  }
}
```

csproj: 

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <RootNamespace>SP_Gateway</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="3.7.7.16" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.10.0" />
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.5.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.31" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.6.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="4.0.1" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
        <PackageReference Include="System.Drawing.Common" Version="5.0.1" />
        <PackageReference Include="Twilio" Version="5.61.0" />
        <PackageReference Include="UAPI.Common" Version="1.0.0-CI-20211029-160214" />
    </ItemGroup>
    <ItemGroup>
      <None Update="host.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="local.settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
```

**Comment by tgrandgent** [comment]
@shelbaz I solved this by adding the following to the `logLevel` section of `host.json`:
```
"Azure.Core": "Error"
```
The category name `Azure.Core` is revealed when viewing the unwanted log entries in Application Insights.

It appears that these routine low-level errors are logged at the warning level for some reason.

**Comment by andrew-tevent** [comment]
I am seeing this too - though I am still on .net 5 and v3 of the runtime. 

But it started when upgrading the worker SDK packages:

![image](https://user-images.githubusercontent.com/78795042/154316948-cd56aa1c-77ac-4982-944e-771c664c2dfc.png)

@tgrandgent's log level seems to have now supressed it.

**Comment by mrhub** [comment]
Still an issue for me.
I have added the 
`"Azure.Core": "Error"`
in my host.json, updated to the latest packages.

**Comment by SeanFeldman** [comment]
@liliankasem yes, it is. I had to resolve to excluding Azure.Core for anything other than Error level to bring Azure bill to a sane level.

**Comment by liliankasem** [comment]
It looks like the fix still hasn't been released yet and should be in the next host version (4.7.0) - will keep the issue open to make sure the next release has the fix

**Comment by SeanFeldman** [comment]
Appreciate the update, @liliankasem. Note that this issue will cause clients with large deployments an excessive charge due to the exponentially large amount of logs shipped to AppInsights. While not something to address on this issue, the Functions team should consider how to avoid this sort of issue in the future. Or, alternatively, provide a way to alert and notify customers.

**Comment by RetYn** [comment]
@liliankasem  #1029 Does my issue also related to this issue?

**Comment by liliankasem** [comment]
> @liliankasem #1029 Does my issue also related to this issue? The difference is I cannot see the trace level log in local and application insights, but I can see the logs in log streams. Any updates on these kinds of issues? We are very concerned about it, because it will cause authorization in HTTP header leak in production.

Issue #1029 is not related to this one

**Comment by josemarfdc** [comment]
I'm facing a similar issue with a Python function

**Comment by EnemyArea** [comment]
It also floods the azure function log-stream. Please fix this :)

**Comment by gcostanzo** [comment]
I'm facing the same issue. The extra HTTP request and response logs are appearing in both the log stream and App Insights logs. I've tried adding `"Azure.Core": "Error"` to `logLevel`, to no avail. I've also tried `"Azure.Storage.Blobs": "Error"` (origin of the HTTP requests & responses).

Anyone have a any other workaround?

**Comment by EnemyArea** [comment]
I have added an new issue: https://github.com/Azure/azure-sdk-for-net/issues/31967

**Comment by pregress** [comment]
You can also disable it using an app setting
```
AzureFunctionsJobHost__logging__logLevel__Azure.Core=Error
```

**Comment by AJMcKane** [comment]
The appsettings / host.json settings aren't working for my apps, is there an update on this issue?

**Comment by LeszekKalibrate** [comment]
is this fixed yet?

**Comment by Tinathnath** [comment]
Hi !
I had the same issue and ended up here.
I also had a flood of logs coming from my various `HttpClient` implementations.
This is how I fixed both trigger and httpClient related logs, tweak you `host.json` like this in the `logging` section (adjust levels at your needs):

```json
"logging": {
    "logLevel": {
      "default": "Information",
      "Microsoft": "Warning",
      "Azure.Core": "Warning",
      "System.Net.Http.HttpClient": "Warning"
    }
```

I you want to hunt a certain type of log, plug an Application Insights to your Function app, and look for the log's Category : 
![image](https://user-images.githubusercontent.com/3273299/233097899-8c9ce19b-4c6f-4de4-af0d-e93880fc6136.png)
 Then, you can filter out this category in host.json.

**Comment by surgupta-msft** [comment]
The issue has been fixed. Please refer https://github.com/Azure/azure-functions-host/issues/8973#issuecomment-1636192111 and https://github.com/Azure/azure-functions-host/issues/9408 for more information.
