### ISSUE TITLE
Use source generators to create the definition factory

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#80]
The `DefaultFunctionDefinitionFactory` is a type that should be generated at build time

**Comment by kshyju** [comment]
@fabiocav  Is this still a valid issue? I do not see this type in the worker repo. Can we update the issue with relevant details if it is still valid?

**Comment by fabiocav** [comment]
This essentially covers the same things as issue #854 

Closing this in favor of the linked issue.
