### ISSUE TITLE
Created new .NET 6 Function with identity-based "Function host storage" gets `Microsoft.AspNetCore.Connections.ConnectionAbortedException`

### ISSUE THREAD

**Issue by Jandev** [Azure/azure-functions-dotnet-worker#801]
I'm in the process of creating multiple Azure Functions which only use identity-based connections.

While doing so, I also want to use the [Function Host Storage (preview) feature](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=azurewebjobsstorage&WT.mc_id=AZ-MVP-5003246#tabpanel_1_azurewebjobsstorage).
I'm also using the `RUN_FROM_PACKAGE` to a storage account, also identity-based.

However, this doesn't appear to work for me at the moment. The Functions don't
The Diagnostics blade tells me the following:
> Timestamp : 2/8/2022 8:16:35 AM
> Inner Exception Type: Microsoft.AspNetCore.Connections.ConnectionAbortedException
> Total Occurrences: 1
> Latest Exception Message: Exception encountered while listening to EventStream
> The HTTP/2 connection faulted.
> Full Exception :
```
 System.AggregateException : One or more errors occurred. (The request stream was aborted.) 
 The request stream was aborted. 
 The HTTP/2 connection faulted.
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at System.Threading.Tasks.Task`1.get_Result()
    at async Microsoft.Azure.WebJobs.Script.Grpc.FunctionRpcService.<>c__DisplayClass4_0.b__1(??) at /src/azure-functions-host/src/WebJobs.Script.Grpc/Server/FunctionRpcService.cs : 46
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.Grpc.FunctionRpcService.EventStream(IAsyncStreamReader`1 requestStream,IServerStreamWriter`1 responseStream,ServerCallContext context) at /src/azure-functions-host/src/WebJobs.Script.Grpc/Server/FunctionRpcService.cs : 93 
 (Inner Exception #0) System.IO.IOException : The request stream was aborted. 
 Microsoft.AspNetCore.Connections.ConnectionAbortedException : The HTTP/2 connection faulted.    End of inner exception
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
    at async Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16 token)
    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
    at async Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input,HttpContextServerCallContext serverCallContext,Func`2 deserializer,CancellationToken cancellationToken)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at async Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.g__MoveNextAsync|9_0[TRequest](??)<--- 
```

What I've done is the following:
* Create Function App - Consumption - Linux - with Managed Identity
* Running them from a package stored in a Storage Account
* Assigning the Blob Data Reader role to the Managed Identity for this Storage Account containing the Functions package
* Create Storage Account acting as the WebJobsStorage
* Assigning the Blob Data Owner & Queue Data Contributor roles to the Managed Identity for this Storage Account
* Also added the Reader role to the Managed Identity for the Resource Group (done manually, not in the Bicep templates)

My solution can be found over here: https://github.com/Jandev/minifier where the [build & deploy workflow sets everything up in Azure](https://github.com/Jandev/minifier/actions/workflows/release.yml).

There's also the error stating:
```
{
2/8/2022 8:09:40 PM
Function app does not contain any active triggers
Function app does not contain any active triggers. Creating a scale down activation task to ensure the app scales down or does not get assigned to a worker.
}
```
I guess this is due to the fact the Function Runtime isn't able to start.

Now, this could be a configuration/permission issue, but I **think** all authorization roles are set up correctly.

This is what I'm seeing in the portal.
![image of non-existing Functions in the Azure Portal](https://user-images.githubusercontent.com/462356/153073246-9ef9af4c-ae8f-4239-b7e1-a2233e0b1715.png)

**Comment by mattchenderson** [comment]
For AzureWebJobsStorage, you _may_ need the "Storage Account Contributor" role as well, as that has a management permission on the storage account itself, needed to check the general blob service configuration. This happens early in the host startup sequence and _could_ explain the early failure, but I would still expect you to be able to see the functions list. Also, this role need is missing from the docs - update coming. I believe it should only be needed in the context of a blobTrigger definition within the payload, but it might be needed more broadly.

I can also imagine that the app attempts and fails to resolve the package before the role assignment kicks in. I'm not sure what the retry logic is off-hand, and it could be that some change would be needed to the site, possibly even the package URL itself. You might consider having the config object depend on the role assignment, although that returns quickly and doesn't mean that access is granted yet. Alternatively, a user-assigned identity with the role pre-assigned could be used (along with the `WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID` setting) to ensure that when the app is created it can resolve the package. I expect that if we looked at your blob logs, you'd see unauthorized access attempts. Similarly, there should be a platform log on the App Service side about the package that would indicate a resolution failure, I think. But this kind of race condition for the role assignment would explain the issue.

**Comment by Jandev** [comment]
Thanks!

I've tried your first suggestion just now by adding the `Storage Account Contributor` role to [both of my managed identities to their corresponding Storage Accounts](https://github.com/Jandev/minifier/blob/d2a166e60e070da28ce2b6cd06e98b9b15c1e55d/deployment/infrastructure/application-infrastructure.bicep?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L91).

I've also turned on the Diagnostic Settings for all Storage Accounts & Azure Functions, to see if there's something useful in them. I'm not seeing any "unauthorized access"-attempts just yet
I am seeing some requests being made to the 3 storage accounts
![Requests to storage accounts](https://user-images.githubusercontent.com/462356/153150203-1c50436d-7bbd-4d12-8b54-2c20359aba3d.png)
The ones to the `deploy` accounts should/could be the Runtime retrieving the package.
The other ones could/should be some IO the Runtime is doing when starting up. 

They are using the `AccountKey` authentication type, which isn't something I'd expect, but the naming might throw me off over here.

I'll try your second suggestion later on today, using a user-managed-identity, as this requires a bit more work in the templates. This also gives AAD some time to sync all roles, which might or might not help.

**Comment by Jandev** [comment]
I have tested the setup using a User Assigned Identity also now, I think.
It was a bit unclear what value the `WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID` should get. I had expected it to be the Client Id or Object Id from the managed identity, but seeing the docs really state the 'resource id', I've configured the settings like the following (obfuscated some values):
```json
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "d7f76f2d-3a71-45cd-bece-e31d94175950",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__blobServiceUri",
    "value": "https://storageaccountforthisazurefunction.blob.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__queueServiceUri",
    "value": "https://storageaccountforthisazurefunction.queue.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~4",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet",
    "slotSetting": false
  },
  {
    "name": "RUN_FROM_PACKAGE",
    "value": "https://storageaccountcontainingdeployments.blob.core.windows.net/deployments/632b884c-7bb4-41da-88a6-03863b555697/frontend.zip",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
    "value": "DefaultEndpointsProtocol=https;AccountName=storageaccountforthisazurefunction;EndpointSuffix=core.windows.net;AccountKey=theKey",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTSHARE",
    "value": "azure-function",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID",
    "value": "/subscriptions/54b9020c-1ce9-4470-909f-555a07a1b6c0/resourcegroups/my-resourcegroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/the-new-user-managed-identity",
    "slotSetting": false
  }
]
```

I've also removed (turned off) the System assigned identity and added the new User assigned identity to the Function App.
![User assigned identity blade](https://user-images.githubusercontent.com/462356/153279916-0d6e90fe-0442-491e-b6c4-ce5bad329136.png)

Before doing so, I have added the following roles to this identity:
* `Reader` for the whole subscription
* `Storage Blob Data Reader` for the `storageaccountcontainingdeployments` Storage Account (which holds the zip-file)
* `Contributor` for the `storageaccountforthisazurefunction` which is the account configured in the `AzureWebJobsStorage` settings
* `Storage Account Contributor` for the `storageaccountforthisazurefunction` 
* `Storage Blob Data Owner` for the `storageaccountforthisazurefunction` 
* `Storage Queue Data Contributor` for the `storageaccountforthisazurefunction`
* `Storage Table Data Contributor` for the `storageaccountforthisazurefunction`

For the visual effect: 
![Assigned role assignments in Azure](https://user-images.githubusercontent.com/462356/153282088-ced971af-f1ec-47d5-ad4b-a4260ffdc073.png)

In the settings above I only have configured `AzureWebJobsStorage__blobServiceUri` and `AzureWebJobsStorage__queueServiceUri`. I've also tried adding `AzureWebJobsStorage` with the value `https://storageaccountforthisazurefunction.blob.core.windows.net`, but this didn't fix anything.

I've also tried using the Client ID and Object ID (Principal ID) for the `WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID` value, but this didn't help much either.

There is something new in the Log Stream & Live Metrics though:
```
Headers:
Date: Wed, 09 Feb 2022 20:15:21 GMT
Server: Kestrel
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
. Azure.Identity: Service request failed.
Status: 400 (Bad Request)

Content:
{"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"9c1f3cd9-8176-48be-a81f-b8c09f8b7926"}

Headers:
Date: Wed, 09 Feb 2022 20:15:21 GMT
Server: Kestrel
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
.
2022-02-09T20:15:27Z   [Verbose]   Host instance '0000000000000000000000005D42BD33' failed to acquire host lock lease: Azure.Identity: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)
```
This might be a misconfiguration for the configuration setting because the MI is right there in the Identity blade.

Any other ideas or pointing out my (obvious?) mistakes is appreciated!
I've heard from a friend he got this working on the Windows plan, so I'll try that also on another day since I'm working on the Linux Consumption plan at the moment.

**Comment by Jandev** [comment]
I've tried it on a Windows Consumption & Dedicated plan.

Same result, but after adding the `AZURE_CLIENT_ID` setting with the user-managed identity client id, I'm receiving at least some Informational messages on both Windows Function Apps and my Linux Consumption app
```
2022-02-10T20:18:48Z   [Information]   Host Status: {
  "id": "minifier-prod-weu-app",
  "state": "Running",
  "version": "4.1.3.3",
  "versionDetails": "4.1.3+3ed9ce8ebeef5b156badaf203a016a56e819a852",
  "platformVersion": "",
  "instanceId": "4A8D2640-637801201576779466",
  "computerName": "",
  "processUptime": 954957,
  "functionAppContentEditingState": "Allowed",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "2.8.3"
  }
}
```

And the Windows dedicated plan also has a nice Verbose message now, which happens about every minute
```
2022-02-10T20:14:11Z   [Verbose]   Request successfully matched the route with name '' and template 'admin/warmup'
```

Adding this value sure did something, the runtime still doesn't do anything it appears.

**Comment by Jandev** [comment]
Well, I hardly dare to admit it, but I found the issue and it was in my configuration.

The observant reader might have caught it already.
```json
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "1eb74289-a1d4-4b01-bfd0-50947ed437b6",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__blobServiceUri",
    "value": "https://mystorageaccountforthefunctionapp.blob.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__queueServiceUri",
    "value": "https://mystorageaccountforthefunctionapp.queue.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~4",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
    "value": "theComplateConnectionStringWhichIsNecessaryForSomeReason",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTSHARE",
    "value": "azure-function",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "https://mydeploymentstorageaccount.blob.core.windows.net/deployments/thepathtomy/functionapp.zip",
    "slotSetting": false
  }
]
```

Do you see it?
I had missed the `WEBSITE_`-prefix in my earlier configuration. After changing the settings to `WEBSITE_RUN_FROM_PACKAGE` all worked out well!

For completeness, I have set up the following roles on the storage account necessary for the Function App.
![IAM excerpt of the storage account](https://user-images.githubusercontent.com/462356/154345592-b220a461-d05b-4229-9b66-339e75e7f557.png)
