### ISSUE TITLE
Unable to turn off CORS

### ISSUE THREAD

**Issue by Traan** [Azure/azure-functions-dotnet-worker#804]
Hi,
I would like to turn off CORS for a Function App (v4) and instead handling it within the function code itself. I have left all the CORS settings blank in the portal. 
![image](https://user-images.githubusercontent.com/1763878/153751527-3040fb01-e6e9-4315-b6ae-b252c58b4dda.png)
![image](https://user-images.githubusercontent.com/1763878/153751551-dd5237bc-d8b8-4b87-8919-11a93634797e.png)

We are trying to upgrade our Function App, and this approach is working in runtime version 1, but not in version 4. This is also the approach for App Service (turn off App Service CORS to be able to use your own CORS).

**Comment by fabiocav** [comment]
@Traan can you clarify what you mean by `to be able to use your own CORS`? 

Can you also share the SKU used (primarily curious to know if this is on Linux or Windows), as the implementation is slightly different for those and it would be good to make sure there isn't anything OS specific going on.

Thanks!

**Comment by Traan** [comment]
@fabiocav @brettsam its actually coming from the documentation for App Service CORS (https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api#app-service-cors-vs-your-cors). "Own CORS" = setting CORS policy from the application code itself instead of using CORS settings in Azure Portal.

The function app is running on Windows.

**Comment by fabiocav** [comment]
This is not something that is exposed to the OOP model, so the option here would be to migrate to the in-proc model in V4 instead.
