### ISSUE TITLE
Ask for suggestions on debugging local in-process extensions for dotnet-isolated worker

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-dotnet-worker#806]
I am a Functions extensions developer and I want to test the local `Microsoft.Azure.WebJobs.Extensions.SignalRService` package with dotnet-isolated worker. I have two questions to ask:

1. Can we let the function host use a local version of the **in-process** extension package so that we don't need to push the package to Nuget? 
    For the in-process model, we just need to add a project reference to the local extension in the functions project as follows, but I don't know how to achieve this in dotnet-isolated runtime.
    ```csproj
    <ProjectReference Include="..\src\Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj" />
    ````

2. Is there a way to debug into the `Microsoft.Azure.WebJobs.Extensions.SignalRService` from startup when I'm running dotnet-isolated worker? I have tried a process as follows but it didn't work.
    * Start a dotnet-isolated function via `function start` without starting the local storage emulator, so that the function host process would be waiting for the storage emulator without loading extensions.
    * In the `Microsoft.Azure.WebJobs.Extensions.SignalRService` 1.2.2 (the version used by the current isolated SignalR extensions) Visual Studio project, attach to the function process above.
    * Start the storage emulator so that the function host will continue to load extensions. 
    * Unfortunately, after the SignalR extensions finish loading, the breakpoints in SignalR trigger binding provider are never hit. They would be hit in the JavaScript Functions runtime, which is also an isolated-process model.

**Comment by fabiocav** [comment]
@Y-Sindo the debugging target here would have to be the host, not the worker. 

You can point to a local build of the extension, but you'd need to set up a local NuGet source for that, using the version you're building locally (your Worker Extension would need to reference that version). This actually gives you the opportunity to force the debugger to attach in the host process by using something like [`Debugger.Launch`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.launch?view=net-6.0)

**Comment by fabiocav** [comment]
Closing as answered, but let us know if you need any additional information.

Thanks!
