### ISSUE TITLE
Middleware registration without gRPC

### ISSUE THREAD

**Issue by bbieniek** [Azure/azure-functions-dotnet-worker#808]
Hi,

Is there any other way to register middleware than by using ConfigureFunctionsWorkerDefaults?
Currently, when we want to add middleware, the function also adds support for gRPC.
In our case, we do not really want and need gRPC support.

I would propose to add an extension method that would allow for:
```
ConfigureFunctionsWorker(builder => {
builder.UseMiddleware<T>();
}
```

**Comment by fabiocav** [comment]
@bbieniek we already have this capability. The core implementation doesn't actually know anything about gRPC, and if you use the middleware registration APIs there, there will be no gRPC services setup.

I'm curious, though. Can you please share more about your scenario? To run on Functions, gRPC services will be required today. Can you please share more about what you're trying to do?

Thanks!

**Comment by fabiocav** [comment]
The default implementation [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/f6c139f1990b3b94fb61408aa09090bd668c927b/src/DotNetWorker/Hosting/WorkerHostBuilderExtensions.cs#L149-L176) adds all of the default services, including the gRPC based communication services.

You can bypass that by using [this instead](https://github.com/Azure/azure-functions-dotnet-worker/blob/f6c139f1990b3b94fb61408aa09090bd668c927b/src/DotNetWorker.Core/Hosting/CoreWorkerHostBuilderExtensions.cs#L25), but it would be your responsibility to add the implementations of the required [`IWorker`](https://github.com/Azure/azure-functions-dotnet-worker/blob/f6c139f1990b3b94fb61408aa09090bd668c927b/src/DotNetWorker.Core/IWorker.cs) implementation. You can look at the gRPC implementation as a reference [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Grpc/GrpcWorker.cs)

**Comment by bbieniek** [comment]
Thanks for the information.
