### ISSUE TITLE
Review entire public surface

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#81]
Minimize surface area for v1. Make sure that anything referencing GRPC or that couples us to System.Text.Json isn't exposed. Things like Converters can be all internal and exposed later to give us more time for API design.

**Comment by fabiocav** [comment]
First iteration done here: https://apiview.dev/Assemblies/Review/af54138c8aa0459c8e91df73dfa71e98

**Comment by brettsam** [comment]
Will do one final review pre-1.0

**Comment by fabiocav** [comment]
Last round or reviews completed. Added with #262
