### ISSUE TITLE
Middleware dependency injection does not use the same instance

### ISSUE THREAD

**Issue by bbieniek** [Azure/azure-functions-dotnet-worker#811]
Hi,

We are using the Middleware dependency injection like this:
`services.AddScoped<SomeClass>`
 and then in the Middleware:
`public XMiddleware(SomeClass someClass)`

further down the line, in a different class:
`public OtherClass(SomeClass someClass)`

What is surprising is that the instance of SomeClass in OtherClass is going to be different in the same request than in Middleware.
It looks like the dependency injection has two different service providers for middleware and for the 'normal' classes.
I know we can retrieve the instance in the Invoke method from:
`context.InstanceServices.GetRequiredService<SomeClass>();`
However, this is an unexpected behavior.

**Comment by kshyju** [comment]
Middleware has singleton lifetime. You should not inject a scoped dependency into a singleton constructor. If you do, your scoped dependency will behave as singleton.

In functions, currently there is no _out of the box_ strict [scope validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0#scope-validation) to prevent anyone from using this incorrect approach. But that is something we plan to add in the next major release. Until then, you can explicitly enable scope validation in your bootstrapping code by setting the [ServiceProviderOptions.ValidateScopes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=dotnet-plat-ext-6.0) property to `true`
````
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(f =>
    {
        f.UseMiddleware<MyMiddleware>();
    })
    .ConfigureServices(services =>
    {                    
        services.AddScoped<MyClass>();
    })
    .UseDefaultServiceProvider((context, options) =>
    {
        options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
    })
    .Build();

host.Run();
````
Hope this helps. Let us know if you run into any problems.

**Comment by fabiocav** [comment]
Closing as answered.
