### ISSUE TITLE
Unable to securely authenticate Azure Function with SPA  

### ISSUE THREAD

**Issue by ameyasubhedar** [Azure/azure-functions-dotnet-worker#813]
Public clients or SPA cannot store Function keys securely. We need a way for SPAs to securely call the Azure functions. We have OpenID connect code workflow, why is access_token based authorization not supported ? This seems critical !

For example:
The SPA can use OpenID connect and authorization code workflow to authenticate a user and then generate access token. Based on the user roles and permission the access token can be used to authorize the call to the Azure function but how do I pass an access_token from a client to an Azure function ?

**Comment by ameyasubhedar** [comment]
Specifically I want to call Azure Functions securely from standalone Blazor Web Assembly (SPA).

**Comment by ameyasubhedar** [comment]
@fabiocav , I did a quick prototype by making the Azure functions access level Anonymous and then using AAD to verify the signed JWT access_token passed with the authorization header.

`public async Task<HttpResponseData> RunCreate([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "microsoftsaas/b2btenants")] HttpRequestData req)` 

Sample code inside Azure function

```
// Sample code to check the access_token issued by MSAL for multi-tenant Azure AD. 
string accessToken = await req.GetAccessTokenAsync();
await accessTokenChecker.CheckAsync(accessToken, model.LoginTenantId, model.LoginObjectId, "tenants");
```

I can now call Azure functions from SPA and authorize the call via access_token.

Do you see any issues with this approach? I don't see any other way to achieve this right now?

**Comment by fabiocav** [comment]
@ameyasubhedar that's a reasonable approach. 

This is more of a host/service requirement, as opposed to the worker, but what you have above is absolutely fine.

**Comment by fabiocav** [comment]
Closing as resolved, but let us know if you need any additional information.
