### ISSUE TITLE
Azure functions with Net 6

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-dotnet-worker#816]
Hello

I need to use Net 6 for Azure Functions, using the isolated model. 

Is isolated model supported in the Azure Functions 4.0 preview?

Using VS 2022, the templates create only in-process functions. 
In case it's not supported, could you tell us when you'll have it? As Net 6 is being released in november.

Have you got any documentation in order to help us to develop Azure Functions using V4? 

Thank you

**Comment by satvu** [comment]
In response to the original issue, .NET 6 Isolated is available in the dropdown menu (last option) in VS 2022. 

<img width="763" alt="function-template-dropdown" src="https://user-images.githubusercontent.com/35204912/156622791-ac69ddb6-13b5-429c-a438-3223dce8aa81.png">

**Comment by sjuarezgx** [comment]
Thanks for your update.
Regards
