### ISSUE TITLE
[.Net 6 isolated] Function to return dynamic with MultiResponse

### ISSUE THREAD

**Issue by andersson09** [Azure/azure-functions-dotnet-worker#820]
I want to be able to return a dynamic type since my exception handling middleware is of type (HttpResponseData). However, with MultiResponse I receive `MultiResponse1[System.Object]` as the api result.

**Comment by kshyju** [comment]
@andersson09 Could you share the code you are trying?

**Comment by andersson09** [comment]
> @andersson09 Could you share the code you are trying?

```
public class FunctionBase
{
    [Function("Ping")]
    public dynamic Ping([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req)
    {
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.WriteString("test");
        //return response; //works
        return new MultiResponse{Name = "test", HttpResponse = response}; //doesn't work 
    }
}

public class MultiResponse
{
    [CosmosDBOutput("","")]
    public string Name { get; set; }
    public HttpResponseData? HttpResponse { get; set; }
}
```

**Comment by kshyju** [comment]
Thanks! Is there a reason you do not want to use `MultiResponse` as the return type? Don't you want to return the same type (or same schema) from your exception handling middleware as well?

**Comment by andersson09** [comment]
Because the exception handling middleware is a library that should be able to be used for any function, not just MultiResponse. So returning a simple HttpResponseData makes sense so it can be consumed by other functions.

**Comment by andersson09** [comment]
> 

If you have a way of finding the return time in the middleware via the Function Context, and converting to it, then that could work too. But I don't think this is possible?

**Comment by andersson09** [comment]
@kshyju I found a hack here https://github.com/Azure/azure-functions-dotnet-worker/issues/765. 

It would be nice to make this work without reflection though :).

**Comment by kshyju** [comment]
We are working on exposing some new APIs to update invocation results from middleware so you can use them instead of the reflection workaround. I will share an update in this this thread when it is available.

Closing this item as I feel no other action item is needed at this point. Thanks!
