### ISSUE TITLE
.NET 7.0 support isolated for AF v4

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-functions-dotnet-worker#823]
Adding tracking item for support .NET 7 in isolated mode:

.NET 7 Preview 5 support

1. Feed ( tooling feed,  extension bundle feed ) 
2. Stack API 
https://github.com/Azure/azure-functions-dotnet-worker/issues/926
4. Templates ( align the templates for isolated .NET 6/7, .NET framework 4.8 )
https://github.com/Azure/azure-functions-templates/issues/1225
6. Image prep - Linux 
7. Worker SDK update : https://github.com/Azure/azure-functions-dotnet-worker/issues/935
8. Backend dependencies
9. Testing

Ongoing : 
- Visual Studio 
- VS Code
- Core tools
- CSS 
- Perf

**Comment by fabiocav** [comment]
FYI @mattchenderson

**Comment by cloudmelon** [comment]
Adding tracking item for support .NET 7 in isolated mode:

1. Feed
2. Templates
3. Image prep
4. Backend dependencies
5. Testing


Ongoing : 
- Visual Studio 
- VS Code
- Core tools
- CSS 
- Perf

**Comment by fabiocav** [comment]
Closing issue as resolved.
