### ISSUE TITLE
Use of % % to store CRON expression in TimerTrigger not functional in Isolated Processes?

### ISSUE THREAD

**Issue by GCoding83** [Azure/azure-functions-dotnet-worker#827]
I am trying to upgrade my Azure Functions to .NET 6 from .NET Core 3.1, and I am no longer able to use a variable in my local settings for my TimerTrigger CRON expression. Instead of doing this:

public void Run([TimerTrigger("*/10 * * * * *")].....)

I want to do something like this:

**public void Run([TimerTrigger("%MyVariable%")]....)**

But it doesn't seem possible anymore. Is there another way to do this?

**Comment by fabiocav** [comment]
Flagging this for investigation so we can take a closer look at the user secrets wire up and make sure this is not missed with OOP.

**Comment by fabiocav** [comment]
Flagging @gzuber here as a point of contact if we need to get more information about the user secrets integration.

**Comment by surgupta-msft** [comment]
@GCoding83 Does adding AddUserSecrets() in your startup.cs help with the issue?

```csharp
public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
{
            if (System.Environment.GetEnvironmentVariable("AZURE_FUNCTIONS_ENVIRONMENT") == "Development")
            {
                builder.ConfigurationBuilder.AddUserSecrets<Startup>();
            }
```

**Comment by SeanFeldman** [comment]
@surgupta-msft, is this documented, or is a sample linked from the documentation demonstrating how to use the feature?
The linked PR is referring to user secrets, also something that'd be nice to have a reference to some documentation. Thank you.

**Comment by surgupta-msft** [comment]
@SeanFeldman These are the links I found useful demonstrating how to access secrets in code - 

1. https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#access-a-secret
2. https://github.com/Azure/azure-functions-core-tools/pull/2136#issuecomment-683162904
