### ISSUE TITLE
Did not find any initialized language workers

### ISSUE THREAD

**Issue by jkeeley2073** [Azure/azure-functions-dotnet-worker#828]
v4 Runtime
Dotnet 6
isolated
Same Code deployed to different App Service working as expected - Failing in dev, working in QA

System.InvalidOperationException at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel

Per - https://github.com/Azure/azure-functions-dotnet-worker/issues/556

Tried disabling Managed Identity, Re-enabling and re-adding keyvault permissions - no luck

**Comment by fabiocav** [comment]
@jkeeley2073 would you be able to share your Function App name so we can take a closer look at it? 

Thanks!
