### ISSUE TITLE
TimerTrigger timing out

### ISSUE THREAD

**Issue by elangelo** [Azure/azure-functions-dotnet-worker#829]
We recently upgraded our azure functions to dotnet-isolated. (We needed other versions of some of the azure sdks).
We host about 10 functions in a single 'instance' on a container on our AkS. All of the functions are TimerTriggered.
After the upgrade we see some of the functions failing with timeout:
Exception in Application Insights:
`Microsoft.Azure.WebJobs.Host.FunctionTimeoutException at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryHandleTimeoutAsync>d__35.MoveNext`

I also find the requests back:
![image](https://user-images.githubusercontent.com/1935881/158133204-e25fb011-5b05-45bb-a33c-4dc87b4417d7.png)

Other than that i can not find any information.

I only know that these functions normally runs in about 5 to 20 seconds and did still occasionally succeed.

I also noticed when upgrading to dotnet-isolated that the attribute [Timeout] that we could set no longer seems to be supported?

**Comment by fabiocav** [comment]
@elangelo since this is running in AKS, we don't really have a lot of visibility over the host behavior/logs. Do you happen to have Application Insights enabled for this? If so, are there any relevant logs you can share?

Do you have the function timeout explicitly configured for your app?

Thanks!

**Comment by elangelo** [comment]
@fabiocav Application Insights is enabled. Is there anything specific i should be looking for? 
I'm mostly concerned with your statement that because it is running in AKS we can't know what is going wrong. Isn't there a debug mode or a log gathering mode? There must be a reason why i'm hitting those timeouts without any trace of what is going wrong...

I have no timeouts configured explicitly. Previously I could add a `[Timeout]` attribute on all my functions but with this new runtime this no longer seems supported. That is a topic for another ticket though.

**Comment by fabiocav** [comment]
@elangelo what I meant is that we (as in the Azure Functions team) won't have access to the application logs we'd typically use to investigate those issues.

You should be able to find information about the offending function, duration and what lead to the timeout in Application Insights.

**Comment by elangelo** [comment]
Do you know what specifically i should be looking for? I have been digging through traces, customevents, exceptions and other things  and i have not found anything remotely related to any causes of this.

**Comment by fabiocav** [comment]
The typical approach when investigating those cases, if no logs are present, would be to inspect the processes, as a timeout could be triggered by the code hanging and never returning a result. Inspecting a dump of the worker process when in that state would be a good way to start.
