### ISSUE TITLE
Support for error handling and retries?

### ISSUE THREAD

**Issue by devJ0n** [Azure/azure-functions-dotnet-worker#832]
Hi,

We are currently planning upgrading/migrating Azure Functions to .NET6, Azure Function runtime v4 and the isolated (out-of-process) mode.

We are heavily relying on `CosmosDBTrigger` and need to make sure no changefeed documents/events are lost due to runtime exceptions.

Is the [Azure Functions - Retry policies (preview)](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview) supported?

The readon why I'm asking is the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#exponential-backoff-retry)  mentioning

> Retriess require NuGet package [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs) >= 3.0.23

Is the [host.json (retry)](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry) still supported? Instead of using the `ExponentialBackoffRetry` attribute on every Azure function.

Is host.json still the file to use when doing general configuration on the Azure Function App?

**Comment by kshyju** [comment]
Yes, retry policies are supported in isolated(out-of-process) function apps. You can enable it by adding the [retry section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry) to your host config. Here is an example host.json
````
{
  "version": "2.0",
  "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 2,
    "delayInterval": "00:00:03"
  }
}
````

> The reason why I'm asking is the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#exponential-backoff-retry) mentioning
   Retries require NuGet package [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs) >= 3.0.23

That documentation which refers the usage of `ExponentialBackoffRetry` attribute is for in-proc function apps.

Please give it a try and let us know if you run into any problems.

**Comment by fabiocav** [comment]
Closing as answered, but please let us know if you have any additional questions/issues.
