### ISSUE TITLE
useconsolelifetime does not invoke StopApplication when running in Console

### ISSUE THREAD

**Issue by hseidel** [Azure/azure-functions-dotnet-worker#834]
I am trying to understand the pattern for a graceful shutdown of an azure function and its host. Following the documentation for UseConsoleLifeTime, I tried the below (simplest of many variations and attempts).

The documentation for UseConsoleLifeTime explicitly states that it "Listens for Ctrl+C or SIGTERM and calls [StopApplication() to start the shutdown process. This will unblock extensions like RunAsync and WaitForShutdownAsync."  

However, in the below, StopApplication never gets called (in the VS 2022 Debugger) when I hit Ctrl+C in the console.

`using Microsoft.Extensions.Hosting;

public partial class Program:IHostApplicationLifetime
{

    CancellationToken IHostApplicationLifetime.ApplicationStarted => throw new NotImplementedException();
    CancellationToken IHostApplicationLifetime.ApplicationStopping => throw new NotImplementedException();
    CancellationToken IHostApplicationLifetime.ApplicationStopped => throw new NotImplementedException();

    public static void Main()
    {
        var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .UseConsoleLifetime()
            .Build();

        host.Run();
    }

    void IHostApplicationLifetime.StopApplication()
    {
        var test = "Got to here";
        throw new NotImplementedException();
    }

 }`

**Comment by fabiocav** [comment]
@hseidel can you please share the documentation you're referencing? The pattern you're using is not actually registering the `IHostApplicationLifetime` implementation doesn't seem to be correctly used.

**Comment by hseidel** [comment]
@Fabio ***@***.***>

Thanks for this response. The documentation I was referring to is located here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostinghostbuilderextensions.useconsolelifetime?view=dotnet-plat-ext-6.0 .

I think your response is correct, as I was able to register the functions correctly using asp.net host running under an Azure app service.  My goal is to implement the desired functionality using an Azure Function, but I think I need to better understand how underlying asp.net hosting capabilities are surfaced in azure functions.  I am fine letting this issue close.

**Comment by fabiocav** [comment]
Thank you for the update, @hseidel !
