### ISSUE TITLE
The KafkaTrigger input parameter doesn't expose the (consumeResult.Message.)Key property 

### ISSUE THREAD

**Issue by dezedan** [Azure/azure-functions-dotnet-worker#848]
I tried to dive into the package but honestly couldn't make (too much) sense of it. This package references Microsoft.Azure.WebJobs.Extensions.Kafka v3.3.2 to expose the kafka message properties. 

Looks like it returns a serialised KafkaEventData<TValue> object rather than KafkaEventData<TKey, TValue>.

**Comment by fabiocav** [comment]
@shrohilla could you please provide some feedback here and share the plans/guidance?
Thanks!

**Comment by benjaminrhope** [comment]
Ran into this issue as well. The input string seems to be missing the Key-property: `{"Offset":5,"Partition":0,"Topic":"test_input","Timestamp":"2022-04-28T11:24:28.961Z","Value":"\"test string\"","Headers":[]}`

Furthermore, I could not find a way to set the Key (or Header) property in the output binding. Is it supported? The provided example will set the value only: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/Kafka/KafkaFunction.cs.

**Comment by shrohilla** [comment]
> I tried to dive into the package but honestly couldn't make (too much) sense of it. This package references Microsoft.Azure.WebJobs.Extensions.Kafka v3.3.2 to expose the kafka message properties.
> 
> Looks like it returns a serialised KafkaEventData object rather than KafkaEventData<TKey, TValue>.

@fabiocav does dotnet language worker supports parsing of string serialized into object ??

**Comment by shrohilla** [comment]
@marstran we are fixing the 2nd part raised by banjamin, 1st part we are not solving for now
