### ISSUE TITLE
Scale controller does not support .NET config sections on connection settings

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-functions-dotnet-worker#849]
I'm not sure this is specific to QueueTrigger, but that's where I noticed the failure to scale out was driven by the connection using a config section. We do this because we use configuration management to bind other configuration section values that drive behaviors in the code. Would be nice if the scaler controller supported .NET configuration sections when used like this, or maybe an analyzer that warns about this as you wouldn't notice this without the scaler controller logging.

```csharp
    [Function("Function1")]
    public async Task RunAsync([QueueTrigger("my-queue", Connection = "MyQueue:ConnectionString")] string message)
    {
    }
```

Setting this value in the Function App appsettings, `MyQueue__ConnectionString` causes the scale controller to log an error and does not scale out the function as expected.

```
Specified connection string is null or empty for connection: MyQueue:ConnectionString. Invalid connection.
```

**Comment by fabiocav** [comment]
@smokedlinq this could be a defect in the scale controller parsing of the configuration path (the app setting reference). If this is on Windows, have you tried using a `:` when defining the connection instead? 

We'll leave this open for further investigation.

**Comment by fabiocav** [comment]
For now, the guidance is to use the same format, as the scale controller is performing a literal comparison when evaluating those references.

**Comment by fabiocav** [comment]
Closing as answered, but please let us know if you have any other questions/issues.
