### ISSUE TITLE
Add startup logger to log startup code failure

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#850]
Add proper error logging when the extension startup code crashes (during app startup/bootstrapping).

**Comment by fabiocav** [comment]
If you're using the prefix defined [here](https://github.com/Azure/azure-functions-host/blob/eebfec15d1e7df0d37fc28a6bb7943c04062647f/src/WebJobs.Script/Workers/WorkerConstants.cs#L35), you should be able to see those messages handled by the host.
