### ISSUE TITLE
Is gRPC supported by Azure Functions?

### ISSUE THREAD

**Issue by victormarante** [Azure/azure-functions-dotnet-worker#853]
Hi,

Is it possible to run gRPC with Azure Functions? Based on the code on this NuGet, I assume you can, but I don't see any instructions how to do so, if triggers for it have been implemented?

**Comment by fabiocav** [comment]
@victormarante are you referring to the ability to trigger over gRPC? If so, that isn't a supported Functions scenario today.

**Comment by victormarante** [comment]
> @victormarante are you referring to the ability to trigger over gRPC? If so, that isn't a supported Functions scenario today.

Hi, thanks for Quick reply. Yes, my question is if it is possible to use gRPC with functions?

My use case is to have multiple functions behind an API Management service, and rely on gRPC for inter-communication between functions. I assume then that this is not a supported scenario?

**Comment by fabiocav** [comment]
That's correct. This is not a supported scenario today and I, unfortunately, don't have anything to share on plans to support this in the near future.

**Comment by victormarante** [comment]
> That's correct. This is not a supported scenario today and I, unfortunately, don't have anything to share on plans to support this in the near future.

Hi. Thanks for the replies. Feel free to close.
