### ISSUE TITLE
Generate source for function indexing

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#854]
Once the work in #676 is merged, we should enhance the process with a source generator that will create the code that will be compiled into the worker with the metadata definition, bypassing the process that performs this work at runtime.

**Comment by fabiocav** [comment]
Work currently in progress. Moving to 122

**Comment by fabiocav** [comment]
Work here is in progress. Moving to sprint 125.

**Comment by fabiocav** [comment]
This is being iterated on. Reviews are coming in and @satvu is working on feedback.

**Comment by satvu** [comment]
closing as PR has been merged
