### ISSUE TITLE
Update stacks API to include isolated worker types

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#857]
Currently the stacks API does not include Isolated workers, and it probably should. There will be some naming that we need to resolve for the various versions, just for display purposes in consuming tooling. The primary tools which consume this are the portal and Azure CLI.

Within host v4, we'd want to add:
- .NET 6 Isolated
- .NET Framework Isolated - (not yet available, but we would want to make sure we can specify that this version would not support Linux as a valid target OS)

Work would take place here (that repo doesn't take issues): https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts

There are processes for us to validate these changes privately before pushing them out in full. This requires that we include the `hidden` flag in the initial changeset.

**Comment by fabiocav** [comment]
This has a dependency on improvements we need to make to the host behave as expected when the runtime is set to `dotnet-isolated` and no payload is deployed.

**Comment by mattchenderson** [comment]
Depends on https://github.com/Azure/azure-functions-host/issues/8311
