### ISSUE TITLE
Durable Functions in .NET Isolated worker should support .NET Standard 2.0

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#858]
Related to https://github.com/Azure/azure-functions-dotnet-worker/issues/767 but capturing an additional requirement that may be handled as a separate piece of work.

The worker SDK extension should be able to target .NET Standard 2.0 in addition to .NET 6. This would allow projects to specify a broader set of target frameworks.

**Comment by mattchenderson** [comment]
Possibly useful reference: https://github.com/Azure/azure-functions-dotnet-worker/pull/799

**Comment by cgillum** [comment]
Completed as part of https://github.com/Azure/azure-functions-durable-extension/pull/2185 (back in May).
