### ISSUE TITLE
GA versions of worker extensions for latest trigger and binding extension versions

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-dotnet-worker#863]
There is a batch of worker extensions that are still in preview and reference preview versions of the corresponding host extensions, but those host extensions are GA. These should be updated to GA versions, referencing the GA host extensions.

It may be appropriate to split these out into separate work items, but for brevity and getting it captured:

| Service | Worker Extension | Code link | Host Extension Specified | Latest Host Extension | Status | 
|-|-|-|-|-|-|
| Blobs | [5.0.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs/5.0.0) | [AssemblyInfo.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/aaf1cf7cd99fa075bc8700e988262f126eac61f1/extensions/Worker.Extensions.Storage.Blobs/src/Properties/AssemblyInfo.cs) | [5.0.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/5.0.0) | [latest](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs) - 5.0.0 at issue edit time| ✅ Aligned |
| Queues | [5.0.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues/5.0.0) | [AssemblyInfo.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/aaf1cf7cd99fa075bc8700e988262f126eac61f1/extensions/Worker.Extensions.Storage.Queues/src/Properties/AssemblyInfo.cs) | [5.0.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/5.0.0) | [latest](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Queues) - 5.0.0 at issue edit time | ✅ Aligned |
| Event Hubs | [5.0.0-beta6](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs/5.0.0-beta.6) | [AssemblyInfo.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/4b78a06fa34987769979bf4b2e335ce54482e455/extensions/Worker.Extensions.EventHubs/src/Properties/AssemblyInfo.cs) | [5.0.0-beta6](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/5.0.0-beta.6) | [latest](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs) - 5.1.0 at issue edit time| Needs GA worker extension and specified host extension version bump |
| Service Bus | [5.0.0-beta6](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ServiceBus/5.0.0-beta.6) | [AssemblyInfo.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/4b78a06fa34987769979bf4b2e335ce54482e455/extensions/Worker.Extensions.ServiceBus/src/Properties/AssemblyInfo.cs) | [5.0.0-beta6](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.0.0-beta.6) | [latest](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/) - 5.3.0 at issue edit time | Needs GA worker extension and specified host extension version bump |
| Event Grid | [3.0.0-beta3](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventGrid/3.0.0-beta.3) | [AssemblyInfo.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/24951c59af9182f58f96ad49356c4db69b3a44c3/extensions/Worker.Extensions.EventGrid/src/Properties/AssemblyInfo.cs) | [3.0.1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/3.0.1) | [latest](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/) - 3.2.0 at issue edit time | Needs GA worker extension and specified host extension version bump |

The Storage meta-package is in fact GA: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage/ - this just references Blobs and Queues, though.

For Azure Tables, see https://github.com/Azure/azure-functions-dotnet-worker/issues/404

Cosmos DB also has a new major version of its host extension that remains in preview. It could probably stand an update as well to pull in the latest preview.

We should discuss options for bringing these into better alignment and preventing drift going forward. CC @JoshLove-msft

**Comment by DavidJFowler** [comment]
> Cosmos DB also has a new major version of its host extension that remains in preview. It could probably stand an update as well to pull in the latest preview.

Any news on when Microsoft.Azure.Functions.Worker.Extensions.CosmosDB will move out of preview?
