### ISSUE TITLE
How to detect kind of trigger in middleware

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-functions-dotnet-worker#868]
Hi.

I would like to detect kind of trigger (e.g. http triggers or timer trigger) in middleware , and I have examined the FunctionContext object, but it does not seem to have any definitive attributes to detect the trigger.

How can I detect the type of trigger?

**Comment by kshyju** [comment]
Trigger is an input binding with the `Type` property value having the "**_Trigger_**" suffix. You can get this information as shown in the below example.

````
internal class MyMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        var triggerType = context.FunctionDefinition.InputBindings.Values.First(a => a.Type.EndsWith("Trigger")).Type;

        var logger = context.GetLogger<MyMiddleware>();
        logger.LogInformation($"TriggerType: {triggerType}");

        await next(context);
    }
}
````

**Comment by kshyju** [comment]
Closing as answered. Please let us know if you have any more questions.
