### ISSUE TITLE
How can I set the attributes of KafkaTrigger from environment variables?

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-functions-dotnet-worker#872]
I am unable to statically compile these attributes into the application, so how can I configure them to be pulled from environment variables? I'm assuming there is some pattern I can follow for configuration but I'm not sure how to predict that yet:

For example I am wanting something effectively like this:

```cs
[Function("hello_kafka")]
public async Task HelloKafka(
  [KafkaTrigger(
    "%Kafka:BootstrapServers%",
    "%Kafka:Topics:Hello:Name%",
    ConsumerGroup = "%Kafka:Topics:Hello:ConsumerGroup%"
  )]
  string input)
{
    Console.WriteLine(input);
    await Task.CompletedTask;
}
```

Here is my config:
```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
  },
  "Kafka": {
    "BootstrapServers": "localhost:9092",
    "Topics": {
      "Hello": {
        "Name": "hello",
        "ConsumerGroup": "providers"
      }
    }
  }
}
```

But this is giving me this error ` '%Kafka:BootstrapServers%' does not resolve to a value.`

> [func-6b6c4567b6-lzhsv]   [2022-05-10T18:03:39.325Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.hello_kafka'. Microsoft.Azure.WebJobs.Host: '%Kafka:BootstrapServers%' does not resolve to a value.
[func-6b6c4567b6-lzhsv]   [2022-05-10T18:03:39.423Z] Error indexing method 'Functions.hello_kafka'

**Comment by justinmchase** [comment]
annoyingly it seems like the only way is to put your settings into the `"Values"` section like this:

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "KafkaBootstrapServers": "localhost:9092",
    "KafkaTopicsHelloName": "hello",
    "KafkaTopicsHelloConsumerGroup": "providers"
  }
}
```

```cs
[Function("hello_kafka")]
public async Task HelloKafka(
  [KafkaTrigger(
    "%KafkaBootstrapServers%",
    "%KafkaTopicsHelloName%",
    ConsumerGroup = "%KafkaTopicsHelloConsumerGroup%"
  )]
  string input)
{
    Console.WriteLine(input);
    await Task.CompletedTask;
}
```

I hate it, but it does "work". I have no idea why I can't just resolve into any arbitrary section in the configuration but it does appear to be impossible.

**Comment by fabiocav** [comment]
@justinmchase indeed, as mentioned in the other issue, this is a broader limitation (beyond just the worker) and other components do have a dependency on those configuration settings. Closing this as answered at this point, as there are no current plans to change this behavior, but please let us know if you have any additional questions. 

Thanks!

**Comment by justinmchase** [comment]
My only additional question is if there is a different way of binding functions dynamically other than via statically compiled attributes?

It would be awfully nice to have a service I could implement which simply resolved the configuration settings how I need them then defined the bindings as the process starts up. Is there any such api?
