### ISSUE TITLE
How can I move where the app settings the configuration variables are stored?

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-functions-dotnet-worker#879]
For example this [example settings file](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/local.settings.json):
```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "AzureWebJobsStorage": "",
    "CosmosConnection": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
    "CosmosDb": "ItemDb",
    "CosmosCollIn": "ItemCollectionIn",
    "CosmosCollOut": "ItemCollectionOut"
  }
}
```

Suppose I want it to be this instead:
```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "AzureWebJobsStorage": ""
  },
  "Cosmos": {
    "Connection": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
    "Db": "ItemDb",
    "CollIn": "ItemCollectionIn",
    "CollOut": "ItemCollectionOut"
  }
}
```

How can I configure the function runtime, or the function itself to bind to those settings instead?

**Comment by fabiocav** [comment]
@justinmchase unfortunately, today, this is not something that is supported. There isn't a mechanism that would enable you to change the format to what you've described, principally for trigger and binding configuration, as they're read by the host.

Closing this as there isn't anything planned to address this at the moment, but please let us know if you have any additional questions.

**Comment by justinmchase** [comment]
Is there a way for me to programatically define the triggers other than through hard-coded attributes?

I see in other apps there is a `function.json` which doesn't seem to work for C#, is there a way I can essentially build my own bindings programmatically at startup?
