### ISSUE TITLE
BlobTrigger with trigger only option to avoid outofmemoryexceptions

### ISSUE THREAD

**Issue by wkosten1982** [Azure/azure-functions-dotnet-worker#884]
After migrating Azure Functions we are running into memory issues with the BlobTrigger (on AKS). It seems that Stream is no longer an option in isolated-mode and byte[]/string data is loading the entire file in memory we would like to stream the data for a more memory efficient approach.

Unfortunately I have not discovered any option to omit the byte[] or string. Even with the {name} string the data is loaded into memory.

Is there any option to have a trigger only to detect if any new file was added to the container without loading any data into memory?

**Comment by fabiocav** [comment]
Unfortunately, this is indeed a limitation of the current OOP model (impacting all workers). We have work in progress to change this behavior (in early stages, so no ETA at this point).

We'll keep this open and associate the issue with that effort.

**Comment by WestDiscGolf** [comment]
I've been trying to find a solution for BlobTrigger and to get a `Stream` of the input as per the in memory example. Is there an ETA on when this will be supported in isolated mode? Thanks

**Comment by wkosten1982** [comment]
As alternative solutions we decided to use system topics with a blob created event that sends the event to a storage queue. Having a queue trigger function picking up the event and process the data how we want.

**Comment by WestDiscGolf** [comment]
@wkosten1982 Interesting. Thanks for the reply. I'm assuming this can all be done locally as well using Azurite as it also is the queue emulator as well as the blob storage?

**Comment by jmrtnz94** [comment]
I ran into this issue recently. Same scenario, we were migrating our Function App from in-process to isolated (also hosted in AKS).

With Microsoft intending to move towards Isolated Function apps (https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-roadmap/ba-p/2197916). I'd say this should be pretty high in priority.

**Comment by wkosten1982** [comment]
> @wkosten1982 Interesting. Thanks for the reply. I'm assuming this can all be done locally as well using Azurite as it also is the queue emulator as well as the blob storage?

The filename is part of the queue message and  can be tested with azurite yes!

**Comment by liliankasem** [comment]
The SDK binding work that @fabiocav mentioned above has now been released in [public preview](https://azure.microsoft.com/en-us/updates/public-preview-sdk-type-bindings/). This will allow you to bind to a BlobClient or stream
