### ISSUE TITLE
Log categories are not honored any longer (as defined in host.json)

### ISSUE THREAD

**Issue by Manthazar** [Azure/azure-functions-dotnet-worker#895]
**Is your question related to a specific version? If so, please specify:**
- Azure Function Core Tools v4 and Azure Functions .NET 6 isolated
- Azure Function Worker 1.6

**What language does your question apply to? (e.g. C#, JavaScript, Java, All)**
C#

**Question:**
I was investigating a problem related to EF5 which started to spam our logs with a bazillion of log messages we haven't been asking for. Our host.json looks like this:
```
{
  "reference": "https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json",

  "version": "2.0",
  "logging": {
    "logLevel": {
      "Function": "Information",
      "Default": "Warning",

      "Microsoft.EntityFrameworkCore": "Warning",
      "MyCategory": "Warning",
   }
  }
}
```

However, after switching to .NET 6 isolated, log categories are not taken into account any longer. Everything sinks into the category "Function", so given above configuration would not log earlier (because loglevel is warning in host.json), but now it does:
```
 var exampleLogger = provider.GetRequiredService<ILogger<MyCategoryClass>>();
 loggerexamples.LogInformation("HIIIIIIYYYYYYAAAAA");
```
- I can confirm that the logger `exampleLogger` has the right category to it.
- I can confirm that the logger created through logger factory behaves in the same way
- I can confirm that the information 'HIIIIIIYYYYYYAAAAA' only disappears, if we change the category to warning, i.e. `"Function": "Warning"`, but then everything else goes away with it.

Is this an intended change which I have missed?

**Comment by Manthazar** [comment]
Is that actually linked to #619?

**Comment by fabiocav** [comment]
@Manthazar you haven't missed anything, this is indeed the current behavior of the worker.

One alternative we'd recommend exploring is to enable Application Insights in the worker. You can find more information in this issue: https://github.com/Azure/azure-functions-dotnet-worker/issues/822

Closing this as answered as we already have other issues tracking this, but please let us know if you have any additional questions.
