### ISSUE TITLE
[Feature Request] Support middleware adding new function parameters

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-dotnet-worker#898]
### Feature request

I would like middleware to be able to create new (optional) parameters in the function signature.

### Why is this needed?

I think this is useful generally, but I have a specific need for something like this in Durable Functions. Today we have to combine both the orchestration context object and the orchestration input as a single parameter. The user experience is something like the following:

```csharp
public static async Task<string> Run([OrchestrationTrigger] TaskOrchestrationContext ctx)
{
    string input = ctx.GetInput<string>();
   // ...
}
```

This is problematic because it's difficult to do any kind of static analysis on orchestrator functions to determine what kind of inputs are actually valid. It also creates asymmetry between inputs and outputs since I can express the output in terms of the function signature but not the input. There are also some other technical challenges it creates because of the design of the SDK that powers this extension.

### Proposed solution

I want to be able to separate my orchestrator function context and input into multiple parameters, like this:

```csharp
public static async Task<string> Run([OrchestrationTrigger] TaskOrchestrationContext ctx, string input)
{
   // ...
}
```

Looking at the extensibility primitives in Worker.Core, it seems like there's no way to do this because all data structures related to parameters are completely immutable. Ideally, the middleware used by the Durable extension (or any other extension) could inject new parameters that users could bind to via function signatures.

**Comment by fabiocav** [comment]
This makes sense. We do have plans to expose different binders that would enable you to bind to types/data coming from scoped services and invocation context, which I believe would meet your requirement.

**Comment by fabiocav** [comment]
Flagging for triage again so we can discuss assignment.

**Comment by jviau** [comment]
Going to close this as we were able to accomplish the goal with existing extensibility. However, we will still keep this in mind for improving input binding in the future.
