### ISSUE TITLE
--dotnet-isolated-debug does not emit process ID when logLevel.Host=Error

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-functions-dotnet-worker#900]
The `--dotnet-isolated-debug` argument does not emit process ID when `logLevel.Host=Error`.

## Repro steps

* Create a new Azure Functions project, V4, with the .NET Isolated Worker.
* Add one function, for example an HTTP trigger
* Add the following `host.json`: 

```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        },
        "logLevel": {
            "default": "Warning",
            "Host": "Error",
            "Function": "Information"
        }
    }
}
```

* Run `func.exe host start --pause-on-error --dotnet-isolated-debug` on the terminal

### Expected

The following output is written to console:

```
Azure Functions Core Tools
Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473

[2022-05-17T05:47:08.069Z] Azure Functions .NET Worker (PID: 19708) initialized in debug mode. Waiting for debugger to attach...
```

### Actual

No worker process id is written to console, and attaching a third-party debugger automatically is not possible.

## Extra information

Setting the environment variables `FUNCTIONS_ENABLE_DEBUGGER_WAIT=True` and `FUNCTIONS_ENABLE_JSON_OUTPUT=True` in addition does also not emit the PID.

**Comment by fabiocav** [comment]
Thanks @maartenba . We'll address this and ensure the message flows through in those cases.

One thing I wanted to share, if you're reading that information from a debugger, is that we may have an easier/more structured way (JSON Lines) to write the PID to be consumed by tools (which is what VS uses).

In order to use that, you can either set the environment variable `FUNCTIONS_ENABLE_JSON_OUTPUT` or pass the command line argument `--enable-json-output`. You can also pass a file path using the `--json-output-file` argument, and if you do, the JSON will be written to that file. I haven't validated, but this may actually provide a workaround for the level issue.

**Comment by maartenba** [comment]
Tried those too, and alas, no success there either. Thanks for looking into it!

**Comment by fabiocav** [comment]
@maartenba we're making some changes in other components to address how this is handled and expect the change to be in place in the sprint starting today (done within two weeks). We can provide information on how to validate this once the change is in.

**Comment by kshyju** [comment]
@maartenba Apologies for the delayed response. Could you try this again with the core tools version [4.0.4704](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools), which is the latest as of today ?

Writing the process id to the JSON is not relying on the host logging level anymore. I tried the below and can confirm that the JSON string is written to the file.

````
func host start --dotnet-isolated-debug --enable-json-output --json-output-file "C:\\Temp\rider.json"
````

Tooling should rely on this data than the Console message (_Azure Functions .NET Worker (PID: 19708) initialized in debug mode._ )

Let us know if you still run into issues.

**Comment by maartenba** [comment]
Thanks! Does seem to work indeed!

One question around tooling: is reading the JSON output from console reliable? The issue with emitting it to a file is that the user can theoretically pass in their own filename (which may have existing, wrong PID data in there)

**Comment by kshyju** [comment]
The entries will be appended to the file. So, as long as the latest/last entry is read & used by tooling, that will be the correct PID. Let me know if I am comprehending your point incorrectly. :)

**Comment by maartenba** [comment]
Thanks for the information about appending, that's really good to know 👍

**Comment by kshyju** [comment]
Closing. Let us know if you still run into issues.
