### ISSUE TITLE
dotnet-isolated function WEBSITE_TIME_ZONE GMT does not set UK date format

### ISSUE THREAD

**Issue by markhoratiowalmsley** [Azure/azure-functions-dotnet-worker#901]
Apologies if this isn't the right repo but we are running our functions as dotnet-isolated and have recently updated our functions to update to use WEBSITE_TIME_ZONE='GMT Standard Time'. This changed the time from UTC to UK time which accounts for BST and fixed our timstamps .However, it appears to have broken the date:

![image](https://user-images.githubusercontent.com/30492429/168814208-d7326176-c400-4f11-a12a-db5e476dcbef.png)

GMT Timezone should have a dd/MM/yyyy format.

This is a massive issue with our production code. Is there a fix for the specifc date format?

![image](https://user-images.githubusercontent.com/30492429/168814441-99a2e51f-a9e4-4b3b-a9a7-28e05ed3402c.png)

Net version:.net6 
Host: Consumption plan
OS: Windows

**Comment by kshyju** [comment]
@markhoratiowalmsley Could you provide a little mode details on what is broken? Are your functions not executing as expected? What is your expected behavior and what is actual/current behavior now?

**Comment by markhoratiowalmsley** [comment]
The GMT timezone gives an incorrect  datetime format. The console screenshot from above shows that the time is correct (BST is applied) but the date is formatted as MM/dd/yyyy. This means that unless DateTime.ParseExact is used, then parsing a UK date will fail if the date part is over 12 e.g. 15/06/1990. Unless I'm missing another setting WEBSITE_TIMEZONE is only being applied to the time, not the date.

**Comment by kshyju** [comment]
Where is the parsing failing? In your function code? Can you share your code which fails?

The [ToString()](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-6.0#system-datetime-tostring) method of DateTime uses the current culture. Can you point me to the documentation of `WEBSITE_TIME_ZONE` setting/env variable usage, you were following which indicates that the time zone will update the current culture as well?

If you want to know the culture used, you can print it inside your function code like this

````
var culture = Thread.CurrentThread.CurrentCulture;
var str = $"CurrentCulture: {culture.Name}, FullDateTimePattern:{culture.DateTimeFormat.FullDateTimePattern}";
// to do: print/log str for verification.
````

If you want to set a specific culture, you can do something like this.

````
Thread.CurrentThread.CurrentCulture =  new CultureInfo("en-gb");
````
