### ISSUE TITLE
Remote Debugging for Isolated mode

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-functions-dotnet-worker#905]
The goal is to enable VS to supprto remote debugging for isolated apps

cc: @fabiocav @soninaren

**Comment by cloudmelon** [comment]
Once all changes are deployed, we can close this item and follow up with VS. I will validate the feature and work on the documentation.

**Comment by mattchenderson** [comment]
The API work for this was all done. We need to confirm a few final things with the VS folks. This may already be done.

**Comment by fabiocav** [comment]
Closing this as the worker/host work has been completed.

**Comment by AngelosP** [comment]
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/8742622/0c2a0297-0a9a-4bdd-af10-818d6d34fc2d)

**Comment by AngelosP** [comment]
Confirmed it's working in latest version of VS and a .NET 7 isolated function.
