### ISSUE TITLE
Isolated process timer function incorrectly triggering with IsPastDue

### ISSUE THREAD

**Issue by drmathias** [Azure/azure-functions-dotnet-worker#909]
One of our timer functions is on a schedule to trigger every 4 hours, at the beginning of the hour `0 0 */4 * * *`. For example, it is scheduled to trigger at 00:00 then at 04:00. In reality, it is triggering twice every time, at 00:00 then around 00:01, and at 04:00 then around 04:01.

When monitoring the function on Azure, it shows the function as failing because of `Microsoft.Azure.WebJobs.Host.FunctionTimeoutException` with the message:

> Timeout value of 00:05:00 was exceeded by function: ...

However, each time it triggers, it appears to run through to completion and this is the case debugging locally with matching configuration.

Upon investigation, the function seems to get executed for a second time with `IsPastDue` set true. Order of events is below. There's another timer function executing at the same time, which completes execution and doesn't time out.

> 00:00:00 AM:  Executing 'Functions.MyFailingFunction' (Reason='Timer fired at 2022-05-21T23:59:59.9977591+00:00', Id=7d818241-15e4-49e3-b648-67f04a5b14b9)
> 00:00:00 AM: Executing 'Functions.MySucceedingFunction' (Reason='Timer fired at 2022-05-21T23:59:59.9977587+00:00', Id=2d545b08-442f-44b3-96b9-b6a3056d1cb4)
> 00:00:01 AM: Executed 'Functions.MySucceedingFunction' (Succeeded, Id=2d545b08-442f-44b3-96b9-b6a3056d1cb4, Duration=1094ms)
> 00:00:02 AM: Hosting stopping
> 00:00:02 AM: Stopping file watchers.
> 00:00:02 AM: Waiting for RpcFunctionInvocationDispatcher to shutdown
> 00:00:46 AM:  The 'MyFailingFunction' timer is using the schedule 'Cron: '0 0 0,4,8,12,16,20 * * *'' and the local time zone: '(UTC) Coordinated Universal Time'
> 00:00:46 AM:  Timer for 'MyFailingFunction' started with interval '00:00:00.0010000'.
> 00:00:46 AM:  Function 'MyFailingFunction' is past due on startup. Executing now.
> 00:00:46 AM:  Executing 'Functions.MyFailingFunction' (Reason='Timer fired at 2022-05-22T00:00:46.4951116+00:00', Id=1c176a90-a8fa-41c2-ad52-688d18e6c43d)
> 00:00:46 AM: Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2022-05-22T00:00:00.0000000+00:00
> 00:00:46 AM:  MyFunction monitor trigger executed at: 05/22/2022 00:00:46
> 00:05:46 AM: Timeout value of 00:05:00 was exceeded by function: Functions.MyFailingFunction
> 00:05:59 AM: Timer for 'MyFailingFunction' started with interval '03:54:00.5967529'.

Invocation ids:

* 7d818241-15e4-49e3-b648-67f04a5b14b9
* 2d545b08-442f-44b3-96b9-b6a3056d1cb4
* 1c176a90-a8fa-41c2-ad52-688d18e6c43d

**Comment by fabiocav** [comment]
@drmathias this looks like an issue related to the host and timer behavior, looking at the application information here would help. We should be able to locate your app with the information you've shared, but the "diagnose and solve problems" functionality in the portal would also give you access to timer troubleshooting detectors. Have you had a chance to look at that?

**Comment by drmathias** [comment]
> @drmathias this looks like an issue related to the host and timer behavior, looking at the application information here would help. We should be able to locate your app with the information you've shared, but the "diagnose and solve problems" functionality in the portal would also give you access to timer troubleshooting detectors. Have you had a chance to look at that?

I've looked at that and the recommendations are all things that we've tried.

We did change the execution time of our function that was succeeding, to be staggered 30 mins before and after the one that is failing, which has resolved the issue of the second execution with `IsPastDue`. There is no documentation I have come across which suggests that two separate timer functions under the same function app cannot execute in parallel, so I'm wondering if this is a separate bug.

However despite no longer executing twice, our function is still failing and this appears to be a problem with the worker hanging. We've debugged this extensively and have concluded that our code within the function runs through to completion.

**Comment by fabiocav** [comment]
@drmathias given the fact this is impacting your application, do you have the option to engage support for immediate assistance? Otherwise, we might not have the ability to assign this to an engineer for investigation until ww go through sprint planning (and the SLA there will also not be the same).

If you can also share a repro, that would be helpful.

Thanks!
