### ISSUE TITLE
Error "Invalid character in extension attribute name: ..." in Microsoft.Azure.Functions.Worker.Extensions.EventGrid version 3.2.0

### ISSUE THREAD

**Issue by CezaryKlus** [Azure/azure-functions-dotnet-worker#910]
I've just updated the package from 2.1.0 to 3.2.0 and experiencing following error on EventGridOutput

```System.Private.CoreLib: Exception while executing function: Functions.HandleCreateCollectionStorage. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Azure.Core: Invalid character in extension attribute name: 'I'. CloudEvent attribute names must consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. (Parameter 'name').```

The output Event Grid topic is created with schema = EventGridSchema. 

I am binding events to a class

```
public class EventGridEvent<T> where T : class, new()
{
    public string Id { get; set; } = Guid.NewGuid().ToString("D");
    public string Subject { get; set; } = typeof(T).Name;
    public string EventType { get; set; } = typeof(T).Name;
    public T Data { get; set; } = new T();
    public DateTime EventTime { get; set; } = DateTime.UtcNow;
    public string DataVersion { get; set; } = "1.0";
}
```

I guess Cloud Events binder is suddenly enabled for EventGridOutput

This was also reported [here](https://github.com/Azure/azure-webjobs-sdk/issues/2798)

**Comment by fabiocav** [comment]
@CezaryKlus to validate that this is not part of the expected behavior, can you please share a repro (basic code and the payload used) so we can take a closer look at understand if there's an issue with the way the worker is providing the metadata to the extension?

/cc @JoshLove-msft

**Comment by JoshLove-msft** [comment]
+1 to including a full repro, but I think what may be happening here is that the the event fails to be parsed as an EventGridEvent, so then we attempt CloudEvent as a fallback. I think this may be due to the fact that the parsing expects camel cased properties where your custom type is Pascal cased. Would you mind testing out changing to use camel-cased properties? This is still something that we should try to address in the extension, but this might fix your issue.

**Comment by stukalin** [comment]
Having the same issue.

**Comment by stukalin** [comment]
@JoshLove-msft you were right - the reason was that we had Pascal cased property names. Once renamed (or provided with `JsonProperyName` attributes) the issue is fixed. So, your minimum repro example might look like this

```
// Default URL for triggering event grid function in the local environment.
// http://localhost:7071/runtime/webhooks/EventGrid?functionName={functionname}
using System;
using System.Text.Json.Serialization;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace eventgridtest2
{
    public class TestEventGrid
    {
        private readonly ILogger _logger;

        public TestEventGrid(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<TestEventGrid>();
        }

        [Function("TestEventGrid")]
        [EventGridOutput(TopicEndpointUri = "TopicUri", TopicKeySetting = "TopicKey")]
        public async Task<MyEvent> Run([EventGridTrigger] MyEvent input)
        {
            _logger.LogInformation(input.Data.ToString());

            return await Task.FromResult(new MyEvent
            {
                Id = "123",
                Subject = "sub",
                EventType = "myevent",
                EventTime = DateTime.Now,
                Data = new TestData(),
                DataVersion = "1.0"
            });
        }
    }

    public class MyEvent
    {
        // [JsonPropertyName("id")]
        public string Id { get; set; }

        // [JsonPropertyName("topic")]
        public string Topic { get; set; }

        // [JsonPropertyName("subject")]
        public string Subject { get; set; }

        // [JsonPropertyName("eventType")]
        public string EventType { get; set; }

        // [JsonPropertyName("eventTime")]
        public DateTime EventTime { get; set; }

        // [JsonPropertyName("data")]
        public TestData Data { get; set; }
        // [JsonPropertyName("dataVersion")]
        public string DataVersion { get; set; }
    }
    
    public class TestData
    {
        public int Total { get; set; }
    }
}

```
It should reference the `Microsoft.Azure.Functions.Worker.Extensions.EventGrid` v3.2.0 nuget package
Uncomment the `JsonPropertyName` in order to make it work correctly.

cc @fabiocav
