### ISSUE TITLE
Make common services available to function method injectable into Function constructor (ILogger, DurableClientContext, etc.)

### ISSUE THREAD

**Issue by cmeyertons** [Azure/azure-functions-dotnet-worker#917]
We generally have multiple functions set up to invoke the same orchestration (Scheduled, Http, etc.)  and use private methods to encapsulate the shared logic (this might be pretty common?)

This leads to duplicative verbosity of injecting the DurableClientContext in each sub-method.  It would be a nice QOL improvement if the DurableClientContext could be injected at the constructor level.

This might stem from the same problem as https://github.com/Azure/azure-functions-dotnet-worker/issues/574

ILogger would benefit from this approach as well.

Before:
```csharp
public class TestFunction
{
    public TestFunction()
    { }

    [Function($"Test_Scheduled")]
    public async Task RunScheduled([TimerTrigger("* * * * *")] TimerInfo timer, [DurableClient] DurableClientContext ctx)
    {
        await OrchestrateAsync(ctx);
    }

    [Function("Test_Http")]
    public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function)] HttpRequestData req, [DurableClient] DurableClientContext ctx)
    {
        await OrchestrateAsync(ctx);
        return req.CreateResponse();
    }

    // more triggers possibly

    private async Task OrchestrateAsync(DurableClientContext ctx)
    {
        // do the orchestration stuff here
    }
}
```

After:
```csharp
public class TestFunctionAfter
{
    private readonly DurableClientContext _ctx;

    public TestFunctionAfter([DurableClient] DurableClientContext ctx)
    {
        _ctx = ctx;
    }

    [Function($"Test_Scheduled")]
    public async Task RunScheduled([TimerTrigger("* * * * *")] TimerInfo timer)
    {
        await OrchestrateAsync(ctx);
    }

    [Function("Test_Http")]
    public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function)] HttpRequestData req)
    {
        await OrchestrateAsync(ctx);
        return req.CreateResponse();
    }

    // more triggers possibly

    private async Task OrchestrateAsync()
    {
        // do the orchestration stuff here
    }
}
```

**Comment by mattchenderson** [comment]
It should be possible to do constructor injection with any of the DI services provided by Functions today. ILogger can be done, but it requires the generic: `ILogger<T>`

Can you confirm that this works for you for ILogger?

What isn't supported today is binding parameters coming from extensions, such as DurableClientContext. These are not DI services.

We'll treat this as a feature request for enablement of binding to constructor parameters.

**Comment by jviau** [comment]
Closing this as this is very broad and not something we can generically support. We support dependency injection for functions constructor, which is all we plan to support. We do not intend to go beyond regular DI in the functions constructor. It will be up to each individual extension to add what types they support to the DI container themselves.

Today you can inject `ILogger<T>` or `ILoggerFactory` to get an `ILogger`.

For `DurableClientContext`, we will eventually be supporting DI of `DurableTaskClient`, there is some work to be done for that though. https://github.com/microsoft/durabletask-dotnet/issues/154
