### ISSUE TITLE
Middleware HTTP sample uses un-released extension methods

### ISSUE THREAD

**Issue by victormarante** [Azure/azure-functions-dotnet-worker#919]
The following sample link, showing how to implement a HTTP header middleware, uses extension methods not yet released in NuGet packages.

[Sample file](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/StampHttpHeaderMiddleware.cs)

[Extension methods](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Context/FunctionContextHttpRequestExtensions.cs)

Maybe add a disclaimer to this?

**Comment by victormarante** [comment]
Perhaps my mistake. The merged PR that includes the needed code for the sample is present on the same branch, going to the tag 1.6.0 for instance, does not have it. So I will close this issue, sorry for the trouble.

**Comment by SeanFeldman** [comment]
@victormarante I think you should re-open this issue.

The documentation is for the stable releases unless noted otherwise. The latest stable in [1.6.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.6.0). It doesn't contain the extensions. This issue should be closed when either a stable version with the extensions is out or the documentation is updated to eliminate the confusion.

cc @fabiocav

**Comment by victormarante** [comment]
Re-opening based on @SeanFeldman comment.

**Comment by victormarante** [comment]
> @victormarante I think you should re-open this issue.
> 
> The documentation is for the stable releases unless noted otherwise. The latest stable in [1.6.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.6.0). It doesn't contain the extensions. This issue should be closed when either a stable version with the extensions is out or the documentation is updated to eliminate the confusion.
> 
> cc @fabiocav

I will re-open, and @fabiocav can way in. I don't know the process/how these things should work in reality. Should the main-branch documentation always be applicable to the latest, stable release?

**Comment by kshyju** [comment]
Apologies for the confusion. There was a timing sync issue between when the documentation went live and the package version became GA. As of today the documentation is correct as [1.8.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.8.0) is out for customers to consume. Please let us know if you still run into issues.
