### ISSUE TITLE
.NET Framework 4.8 isolated - GA

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#924]
Shipping list for .NET Framework 4.8 with Isolated worker tracking : 

- Templates - Visual Studio - UI experience
- Debugger - blocking issue 

Other related work : 
Update templates for isolated Azure functions  .NET framework 4.8
https://github.com/Azure/azure-functions-templates/issues/1225

CC. @fabiocav @mattchenderson

**Comment by satvu** [comment]
Dupe of https://github.com/Azure/azure-functions-host/issues/8245
