### ISSUE TITLE
.NET 7 support Stack API 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#926]
This item is a child Item of .NET 7 support  for Azure functions, 

Create a function app from the Azure portal,  choose runtime combo : 

- .NET 7 isolated 

The proper issue will be opened against the UX repo once we have confirmation that VS Code is using the UX endpoint. Keeping this open as a placeholder.

Sample PR with the required changes: https://github.com/Azure/azure-functions-ux/pull/6310/files

CC. @fabiocav @mattchenderson

**Comment by surgupta-msft** [comment]
Changes completed and merged in UX repo.
