### ISSUE TITLE
Stack API issue + worker not found

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#927]
By default, creating a .NET 6 Azure function is in-process.  There's no option today for .NET 6 isolated process. If we switch that to isolated manually by editing the ARM template. After the function app is deployed,  there's a 'worker not found' in portal as shown the following : 

![image](https://user-images.githubusercontent.com/4621560/173473947-d41e3bd8-0ad9-4f91-a069-54f9dee28b35.png)

This one is potentially related to another issue : (https://github.com/Azure/azure-functions-dotnet-worker/issues/926 )

**Comment by kshyju** [comment]
Related issue: [Host throws for .NET Isolated app if no payload deployed](https://github.com/Azure/azure-functions-host/issues/8311)

**Comment by fabiocav** [comment]
duplicate of https://github.com/Azure/azure-functions-host/issues/8311
