### ISSUE TITLE
Refactor GRPCWorker if-else ladder

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#930]
> Related to code cleanup and refactoring

There is a big if-else ladder in GRPCWorker which can be refactored into a neat switch statement (or we can discuss approaches here if needed).

https://github.com/Azure/azure-functions-dotnet-worker/blob/c522e7be238b5cc716f732f1ea8be3a857c742b3/src/DotNetWorker.Grpc/GrpcWorker.cs#L130-L145

**Comment by kshyju** [comment]
FWIW, There is no perf degradation by switching to switch statement or switch expression. [See the result ](https://gist.github.com/kshyju/d099eacc1dc1558c4382b6afd186d2bb)of a benchmark between the three.

VS also has a quick action which offers converting the **_if else_** block to switch statements or switch expression.

**Comment by victormarante** [comment]
Hi, I can with this issue if it's ok.

**Comment by kshyju** [comment]
Go for it @victormarante

**Comment by victormarante** [comment]
PR is up, please feel free to review. @kshyju
