### ISSUE TITLE
Configuration per out-of-process functions

### ISSUE THREAD

**Issue by kedzior-io** [Azure/azure-functions-dotnet-worker#931]
We are running out-of-process functions and have retry strategy set in `host.json`  as corresponding attribute configuration doesn't work for out-of-process functions. Like this one: `[ExponentialBackoffRetry(5, "00:00:04", "00:15:00")]`

Is there a way to exclude the retry strategy for certain functions? 

... or I simply need to move all those functions to a different function app with separate `host.json` configuration?

**Comment by victormarante** [comment]
Related to #923

**Comment by kedzior-io** [comment]
Looks like I need to separate functions to a different function app with separate `host.json` for which I don't want the retry policy for. That's if I want to keep all my functions isolated.

**Comment by victormarante** [comment]
> Looks like I need to separate functions to a different function app with separate `host.json` for which I don't want the retry policy for. That's if I want to keep all my functions isolated.

I think that is the only solution for now. Would perhaps work with some middleware, depending if we expose that behaviour.
