### ISSUE TITLE
Access Azure App Config Value via Output Binding expression

### ISSUE THREAD

**Issue by Pompeoar** [Azure/azure-functions-dotnet-worker#949]
I'm unable to get output bindings to work with an azure app config setting. Below is my code, simplified (but tested) to explain the point.

I have Azure App Config wired up. Break points show it successfully connects.
I've injected the config just for my own sanity. It has my provider and all my values. It's also able to inject a blob client using those same App Config endpoints (setup in the program.cs's configureservices). This is to triple illustrate that I'm connecting to Azure App Config successfully.

Everything works until I try to use an output binding expression. 

```%FooQueueName%``` works if I add it to my local settings file. The Expression itself is evaluated correctly. It just doesn't work when that value only exists in azure app config. 

Am I wiring this up incorrectly or is this a bug? 

```csharp
 var host = new HostBuilder()
      .ConfigureFunctionsWorkerDefaults()
      .ConfigureAppConfiguration(builder =>
      {
          builder.AddAzureAppConfiguration(appConfigOptions =>
          {
              appConfigOptions.Connect(new Uri(Environment.GetEnvironmentVariable("AzureAppConfigEndpoint")), new DefaultAzureCredential());
          });
      })
     .ConfigureServices((context, s) =>
      {
          s.AddAzureClients(azFactoryBuilder =>
          {
              azFactoryBuilder.UseCredential(new DefaultAzureCredential());
              azFactoryBuilder.AddBlobServiceClient(new Uri(context.Configuration.GetValue<string>("StorageBlobEndpoint")));
          });
       }
```
```csharp
public class SanityCheck
    {
        private readonly IConfiguration config;
        private readonly BlobServiceClient blobServiceClient;

        public SanityCheck(IConfiguration config, BlobServiceClient blobServiceClient)
        {
            this.config = config;
            this.blobServiceClient = blobServiceClient;
        }

        [Function(nameof(SanityCheck))]
        public FooResponse Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req) => 
        new()
        {
            Requests = new [] {"hi"},
            HttpResponse = req.CreateResponse(HttpStatusCode.OK)
        };        
    }
```

```csharp
   public class FooResponse
    {
        [QueueOutput("%FooQueueName%")]
        public string[] Requests { get; set; }
        public HttpResponseData HttpResponse { get; set; }
    }
```
```
[2022-06-24T21:12:30.751Z] Executing 'Functions.SanityCheck' (Reason='This function was programmatically called via the host APIs.', Id=81aa5ed3-1ca7-44af-8cd3-a1b9168ca2f4)
[2022-06-24T21:12:34.210Z] Host lock lease acquired by instance ID '000000000000000000000000E420BAAA'.
[2022-06-24T21:12:38.048Z] Worker process started and initialized.
[2022-06-24T21:12:38.308Z] Executed 'Functions.SanityCheck' (Failed, Id=81aa5ed3-1ca7-44af-8cd3-a1b9168ca2f4, Duration=7564ms)
[2022-06-24T21:12:38.308Z] System.Private.CoreLib: Exception while executing function: Functions.SanityCheck. Microsoft.Azure.WebJobs.Host: '%FooQueueName%' does not resolve to a value.
```

**Comment by fabiocav** [comment]
@Pompeoar can you please share the version of the storage queue extension you're using when you run into this issue? Thanks!

Flagging this for additional investigation against the underlying extension.

**Comment by Pompeoar** [comment]
```<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.0.0" />```

**Comment by jviau** [comment]
@Pompeoar Azure app config is not supported for bindings or triggers. This is because the host process needs to know about these config values, but with your sample code only the worker will know. You need to use `host.json` or environment variables.

Azure app config is something that would be nice to support, but we have no plans today due to the complexities with how dotnet isolated works.
