### ISSUE TITLE
Review OutputBinding<T>

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#95]
- Can we eliminate output binding parameters completely?
- Move Binding attributes to function method level.

**Comment by brettsam** [comment]
@fabiocav or @ankitkumarr -- do either of you want to share the thinking around this here? Or should we share all details in the PR?

**Comment by fabiocav** [comment]
Notes in https://apiview.dev/Assemblies/Review/af54138c8aa0459c8e91df73dfa71e98
