### ISSUE TITLE
The retry policy support in the runtime for triggers other than Timer and Event Hubs is being removed

### ISSUE THREAD

**Issue by kedzior-io** [Azure/azure-functions-dotnet-worker#955]
Today I have noticed a new message in my isolated process azure functions (with service bus triggers):

`Soon retries will not be supported for function 'Functions.MyFunction'. For more information, please visit http://aka.ms/func-retry-policies.`

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cisolated-process&pivots=programming-language-csharp#retry-policies-preview

I'm currently using it by setting up `host.json` with:
```
	"retry": {
		"strategy": "exponentialBackoff",
		"maxRetryCount": 3,
		"minimumInterval": "00:00:03",
		"maximumInterval": "00:00:10"
	},
```
It's a marvellous feature! 

Support for retries is being completely removed for isolated process azure functions? 
I'm understating this right?

**Comment by kbalakumar1** [comment]
We have also used the timer trigger retry functionality in our current application, and have been seeing this message where it mentions that retries will not be supported for the function. But, in the azure error handling document (for reference: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cisolated-process&pivots=programming-language-csharp#retry-policies-preview), it has this line in it which is kind of contradicting the earlier statement:

The retry policy support in the runtime for triggers other than Timer and Event Hubs is being removed after this feature becomes generally available (GA). Preview retry policy support for all triggers other than Timer and Event Hubs will be removed in October 2022.

Does it still mean that the retry functionality is supported for the timer triggers then?

**Comment by fabiocav** [comment]
This is not specific to the Isolated model. Retry support is limited to Timers and Event Hubs when the feature GAs, and that applies to all languages and models.

For triggers like Service Bus, there's built in support for retries provided by the service, and the recommendation is to use that instead. 

Closing this as answered, but please let us know if you have any additional questions.

Thanks!

**Comment by tareksharbak** [comment]
@fabiocav Thanks for the answer, but I was wondering what will happen to the retries of CosmosDB Change Feed trigger? We depend on the retry functionality extensively for that trigger and as far as I know, retries are not built in on the side of the service in this case (such is case for Service Bus). Any plans to have some sort of retry mechanism for the CosmosDB Change feed trigger after October 2022?

Thank you!

**Comment by kedzior-io** [comment]
@fabiocav Thanks for the answer as well. 

> For triggers like Service Bus, there's built in support for retries provided by the service, and the recommendation is to use that instead.

Well as far as I know Service Bus has `MaxDeliveryCount` which will basically send x times the same message without any delays. I suspect what most of us would like to have is `ExponentialBackoff` and sure `ServiceBusClient` has something like this available but I believe that applies to receiving messages using the SDK not `ServiceBusTrigger` as explained here:

https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus

Anyway, sad this feature is being removed from functions.
