### ISSUE TITLE
Ability to asynchronously stream binary results similarly to FileResult

### ISSUE THREAD

**Issue by CezaryKlus** [Azure/azure-functions-dotnet-worker#958]
It appears that with the current object model, specifically `HttpRequestData.Body` the result becomes buffered in memory before being sent to host?

Is there any plan to support asynchronous streaming support similar to `FileResult` in ASP.NET Core with the option to close the original stream?

#884 
[Out of proc languages stream support](https://github.com/Azure/azure-functions-host/issues/1361#)

**Comment by fabiocav** [comment]
That is not supported today, but something that we're already tracking as an enhancement for all OOP languages. I don't have an ETA at this point, but when the capability is made available, we'll have an announcement [here](https://github.com/Azure/azure-functions-dotnet-worker/discussions)
