### ISSUE TITLE
Can't set Console.Title for local development

### ISSUE THREAD

**Issue by YahtzeeJD** [Azure/azure-functions-dotnet-worker#960]
We create functions and test them locally before deployment to Azure. 

Under .Net Core 3.1 we were able to set the Console.Title to show which function was running in which console window. We're in a microservices architecture so we often run MANY functions at once when testing locally.

Under .Net 6, setting the Console.Title no longer names the function's console window.

Is there some alternate method to setting the title under .Net 6?

**Comment by SeanFeldman** [comment]
Where did you run the code to set the window title when using In-Process SDK?

**Comment by YahtzeeJD** [comment]
> Where did you run the code to set the window title when using In-Process SDK?

Thanks for the response Sean.

We used to run it in Startup.cs under .Net Core 3.1. For .Net 6, we put it in Program.cs since we don't use a Startup.cs anymore.

Is there a recommended place for placement of these lines of code?

**Comment by SeanFeldman** [comment]
I suspect that with in-process SDK, setting `Console.Title` was setting the title of the console window that hosted the FunctionApp. With Isolated SDK, FunctionApp is a separate process w/o a console and setting the title has no impact on the runner.

**Comment by YahtzeeJD** [comment]
I believe you are correct. One of our architects did some checking on Saturday and found we could set the window text of the **parent** process of the function through some seriously hacky code.

Hopefully there is a way that we will again be able to easily set a preferred title of the function process when launched locally by the functions team instead of just dotnet.exe. Otherwise, we will have to implement this hack in order to see which function is which.

Appreciate the replies Sean!

**Comment by fabiocav** [comment]
> I suspect that with in-process SDK, setting `Console.Title` was setting the title of the console window that hosted the FunctionApp. With Isolated SDK, FunctionApp is a separate process w/o a console and setting the title has no impact on the runner.

This is correct. The worker runs without a visible window, and in a separate process, different the the one running the host/Core Tools. 

The only mechanism I believe you would have available to you at the moment would be to create a custom extension and reference that from the worker, which would ultimately run in the host process, but honestly, that would be pretty convoluted and heavy handed for this. 

Wondering if there's something you'd be able to do with the launch configuration when debugging the project (assuming that is your flow)

**Comment by YahtzeeJD** [comment]
> Wondering if there's something you'd be able to do with the launch configuration when debugging the project (assuming that is your flow)

Hi. Can you explain this option a little more in detail, or was it just an off-the-cuff thought?
