### ISSUE TITLE
Add E2E testing for .NET 7

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#967]
Create E2E test app (probably [here](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/test/E2ETests/E2EApps)) for .NET 7 to validate builds/PRs as we develop this worker.

**Comment by mattchenderson** [comment]
Is this working? This looks like it's in a bad state just from looking at the code Fabio linked in the original post.

https://github.com/Azure/azure-functions-dotnet-worker/blob/9917849b11cc03da1c38e93160e4092d9b8a6150/test/E2ETests/E2EApps/E2EApp/E2EApp.csproj#L7-L8

It looks like https://github.com/Azure/azure-functions-dotnet-worker/pull/1203 updated a .NET 5 reference to .NET 7 as part of a broader changeset, but that is still preserving a condition of having a V3 runtime, which doesn't make sense.

We should make sure we are getting test results from V4 with .NET 7.

**Comment by liliankasem** [comment]
Ah good point, I didn't notice the condition there

**Comment by liliankasem** [comment]
@satvu did you work on this, was the condition there for v3 intentional?

**Comment by satvu** [comment]
https://github.com/Azure/azure-functions-dotnet-worker/pull/1147 - Here's the PR that added the condition for v3 - at the time it was merged, it was targeting net5.0 not net7.0. 

This was a change to fix the integration pipelines (can see more in PR notes).
