### ISSUE TITLE
Define retry policy attributes

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#971]
With the retry policy configuration move to the function level, we don't have a mechanism that enables policy definition in the worker today. We need to expose those attributes and ensure the metadata flows into the indexing process.

**Comment by fabiocav** [comment]
Effectively, we need support for the `FixedDelayRetry` and `ExponentialBackoffRetry` attributes.

Ultimately, in the context of the worker, those attributes need to emit the correct metadata for the function, for example:

``` json
"retry": {
        "strategy": "exponentialBackoff",
        "maxRetryCount": 5,
        "minimumInterval": "00:00:10",
        "maximumInterval": "00:15:00"
    }
```

**Comment by kshyju** [comment]
FYI Deprecation notice: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp

**Comment by fabiocav** [comment]
Closing as resolved
