### ISSUE TITLE
Release notes/changelog for 1.8.0 (and 1.7.0)

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#975]
The nuget package for 1.8.0 was released 11 days ago, but how do we know what's new/changed in that package?

**Comment by SeanFeldman** [comment]
A good practice is to have a CHANGELOG.md this repo could adopt, similar to Azure SDKs. Blob storage [example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md).

**Comment by fabiocav** [comment]
@SeanFeldman we do have the release notes in https://github.com/Azure/azure-functions-dotnet-worker/blob/main/release_notes.md

We're reviewing the release pipelines to understand what happened with those releases. We'll make sure those are correctly published with all the appropriate notes.

**Comment by fabiocav** [comment]
We're in the process of enhancing this flow to better deal with the various extensions/projects in the repo and ensure the process of publishing the release and capturing the release notes uses the same automation flow we have in the host to make sure this is not missed in the future.
