### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Extensions.SignalRService : Value cannot be null. (Parameter 'item')

### ISSUE THREAD

**Issue by tsansome** [Azure/azure-functions-dotnet-worker#980]
Hi,

I have a .net 6 isolated process Azure function running on V4. When attempting to use the SignalR output binding i get theerror below.

> System.Private.CoreLib: Exception while executing function: Functions.graphql. Microsoft.Azure.WebJobs.Extensions.SignalRService: Value cannot be null. (Parameter 'item').

The only code i've added was decorating my function like below.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/2570105/181496845-a062bde7-7739-4124-8b81-7f7e899b4090.png">

Am i doing something wrong? 

My full package versions:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/2570105/181496958-f65793aa-e1ca-45bd-a3b7-9ebbddbbb13b.png">

**Comment by kshyju** [comment]
@Y-Sindo Could you please take a look at this?

**Comment by tsansome** [comment]
Thanks @kshyju , @Y-Sindo let me know if you need anything from me.

**Comment by Y-Sindo** [comment]
Seems you don't return a valid object in your function. Please see https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/SignalR/SignalROutputBindingFunctions.cs for example.

**Comment by tsansome** [comment]
hmmm. My code looks very similar. is it something to do with how i use the multiple bindings? I'm trying to return an http response but also a signalR message.

I return

<img width="454" alt="image" src="https://user-images.githubusercontent.com/2570105/182137863-e5ac4b24-78f0-4585-9e05-9ae0653a8fa1.png">

Which is made up of these classes
<img width="323" alt="image" src="https://user-images.githubusercontent.com/2570105/182137709-0a211f19-a666-4c3c-aa51-e4fc1bd3cff8.png">

**Comment by Y-Sindo** [comment]
If you're using multiple output binding in a function, please remove the `SignalROutput` attribute targeting the function and only leave the one targeting the property in the return object.

**Comment by tsansome** [comment]
@Y-Sindo  that was the solution!! yes so i removed the SignalR Attribute from the function declaration and only to the return object.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/2570105/182745087-8c72d9dc-e536-4d3d-b2f7-582029f669b8.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/2570105/182745189-1b241204-0cb5-4708-96d3-147a37580095.png">
