### ISSUE TITLE
Visual studio 2022 debugger will not attach automatically, V4 .NET6 Isolated Function takes 60 seconds for worker to begin

### ISSUE THREAD

**Issue by zmerdev** [Azure/azure-functions-dotnet-worker#985]
I had a project that i have been developing for months and never had this issue before.  Something in my environment definitely got messed up on my local machine because other team members can run the same projects with no issue.

**The issues:**

Running Isolated Azure function v4 projects locally it takes 60 seconds for the worker process to start after trying to run it with debugging in visual studio 2022.  However if i run it without debugging the worker starts instantly.

The visual studio debugger will not auto attach, i just see a message in visual studio "Launching Local Functions Process..." and when i close the az func console i get a visual studio error "Failed to launch functions process A task was canceled."

**Steps I've taken:**

- Clean and rebuild.
- "super clean" by deleting all unnecessary files in repo folder (bin and obj).
- Create a sample minimal project from the visual studio template.
- Update azure tools to latest.
- Repair visual studio.
- Uninstall all .net sdks, frameworks, and runtimes.
- Uninstall and reinstall visual studio.

Any help appreciated, next steps etc. If you need more info let me know 

------------------------------------------------------------------------------------------------

Below is the console output when running the minimal project with and without debugging.

Visual Studio F5 (auto attach debugger)
```
Azure Functions Core Tools
Core Tools Version:       4.0.4670 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.7.2.18626

[2022-08-04T12:15:46.971Z] Found C:\[Redacted]\repos\IsolatedApp\IsolatedApp\IsolatedApp.csproj. Using for user secrets file configuration.

Functions:

        Function1: [GET,POST] http://localhost:7061/api/Function1

For detailed output, run func with --verbose flag.
[2022-08-04T12:15:47.886Z] Azure Functions .NET Worker (PID: 26140) initialized in debug mode. Waiting for debugger to attach...
[2022-08-04T12:16:49.862Z] A debugger was not attached within the expected time limit. The process will continue without a debugger.
[2022-08-04T12:16:50.128Z] Worker process started and initialized.
```

Run without debugging
```
Azure Functions Core Tools
Core Tools Version:       4.0.4670 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.7.2.18626

[2022-08-04T12:14:01.605Z] Found C:\[Redacted]\repos\IsolatedApp\IsolatedApp\IsolatedApp.csproj. Using for user secrets file configuration.

Functions:

        Function1: [GET,POST] http://localhost:7061/api/Function1

For detailed output, run func with --verbose flag.
[2022-08-04T12:14:02.862Z] Worker process started and initialized.
```

**.NET info**
```
C:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22330.6
 Commit:    da7c9ccceb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22330.6\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Visual studio version 17.3 (preview) but I had vs version 17.1 which I tried to repair.

**Comment by zmerdev** [comment]
I just tested and I can run without debugging and then manually attach the debugger, but having to do that every time I make a change is very cumbersome.

**Comment by kshyju** [comment]
This was caused by a regression introduced in the recent core-tools release.  See below issue for details.

https://github.com/Azure/azure-functions-core-tools/issues/3111

If you are still seeing issues with isolated function app debugging, please delete the below folder and restart visual studio instances.

````
C:\Users\{yourUserName}\AppData\Local\AzureFunctionsTools\Releases
````
Thanks, and sorry for the trouble. Let us know if you are still running into issues.

**Comment by zmerdev** [comment]
that fixed it thank you, i was pulling my hair out trying to figure it out.
