### ISSUE TITLE
Support for EventGrid blob trigger?

### ISSUE THREAD

**Issue by jamesSampica** [Azure/azure-functions-dotnet-worker#986]
The WebJobs sdk has support for sourcing a blob from EventGrid through the blob trigger attribute.

I know it's in preview but I was wondering if this is functionality that will come to this sdk.

code for comparison:
[WebJobs BlobTriggerAttribute](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/BlobTriggerAttribute.cs#L75)

[Worker BlobTriggerAttribute](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Storage.Blobs/src/BlobTriggerAttribute.cs)

**Comment by fabiocav** [comment]
Resolved by https://github.com/Azure/azure-functions-dotnet-worker/pull/1841
