### ISSUE TITLE
There is no functions runtime available that matches the version specified in the project with dotnet framework 4.8

### ISSUE THREAD

**Issue by ousecTic** [Azure/azure-functions-dotnet-worker#989]
So I was following along this guide : https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

And Repo : https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/NetFxWorker

To Create a .NET Framework 4.8 isolated Azure Function project however I keep getting this error 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/36502535/183315261-a31433e9-cc4d-4755-a5ca-0c462a4d00e0.png">

**CSProj**

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<TargetFramework>net48</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0-preview3" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.5.0-preview2" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
</Project>
```

**Program.cs**

```
using System;
using System.Diagnostics;
using Microsoft.Extensions.Hosting;
using Microsoft.Azure.Functions.Worker;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            FunctionsDebugger.Enable();

            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .Build();

            host.Run();
        }
    }
}
```

**local.settings.json**

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
  }
}
```

**host.json**

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}
```

It does start working when I change the target framework to .NET 6

**Comment by kshyju** [comment]
Do you see the 7X version of SDK/runtime present in your machine? You can verify that by checking the result of `dotnet --info` command. Also what version of visual studio are you using? (You can get this info from the dialog which appears when you click on Help->About Visual studio menu item)

**Comment by sccrgoalie1** [comment]
I'm having this same issue with .NET 4.8.  I installed the latest .NET 7.0 SDK (v7.0.100-preview.7) - Windows x64 Installer and Visual Studio 2022 17.3.0 and the issue still persists.

**Comment by pushkar14** [comment]
I am having the same issue. Have you guys figured it out yet?

**Comment by kshyju** [comment]
Hi @pushkar14 @sccrgoalie1 @ousecTic , Can you try the latest version of [Microsoft.Azure.Functions.Worker.Sdk package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/) ? 1.7.0-preview2

**Comment by kshyju** [comment]
Sorry! I got confused with Net7 support. You do not necessarily need Net 7 installed as this dotnet framework 4.8 as the TFM. Updated the original comment to prevent confusion for future readers.

**Comment by sccrgoalie1** [comment]
I am currently using [Microsoft.Azure.Functions.Worker.Sdk package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/) 1.7.0-preview2.  This is the version having issues.

**Comment by kshyju** [comment]
Just to confirm, You have .NET framework 4.8 installed ? You can confirm it trying to create a new Console App (.NET framework) and select ".NET framework 4.8" or above in the "Framework" dropdown in the new project dialog.

**Comment by sccrgoalie1** [comment]
Confirmed.  I am targeting .NET 4.8 and have the SDK and targeting pack installed.  When I create a new project for .NET Framework, 4.8 is the default.

**Comment by kshyju** [comment]
Sorry folks, you need VS 17.4 or above for working with dotnet-isolated projects targeting netfx. Please download it here https://visualstudio.microsoft.com/vs/preview/

We will update the documentation. Let us know if you still run into issues.

**Comment by sccrgoalie1** [comment]
I just installed the preview.  The same error still persists.

**Comment by mde23vil** [comment]
Same here. Installed Visual Studio preview. Version 17.4.0 Preview 3.0. 
Facing with the same error. Trying to debug 
```
   <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
```

**Comment by wyatt-troia-msft** [comment]
Getting the same error with Version 17.4.0 Preview 4.0 and 

```
   <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
```

**Comment by kshyju** [comment]
If you are still running into issues even after installing [preview 3 or later](https://visualstudio.microsoft.com/vs/preview/), It is possible that VS failed to automatically update the azure functions tools to latest version. You can manually update this using the Options dialog.

**Tools** -> **Options** -> **Projects & Solutions** -> **Azure functions** and click on the "**Check for updates**" button.

![image](https://user-images.githubusercontent.com/144469/196545654-a78b079e-f5fb-4641-af69-544288aa0a38.png)

Install the updates as needed. 

![updates-available](https://user-images.githubusercontent.com/144469/196546748-e8d896cb-db46-4889-b8e9-943a1b5d55b1.png)

Restart Visual Studio and try to create a new Azure functions project and you should see ".NET Framework Isolated" in the functions worker dropdown.

**Comment by amitjaura** [comment]
Thanks @kshyju , this resolved the issue.

**Comment by kshyju** [comment]
> @kshyju what is meant by "_you should see ".NET Framework Isolated" in the functions worker dropdown._"?

![net-framework-isolated-dropdown](https://user-images.githubusercontent.com/144469/199535503-24cf50f3-0a07-4d8b-86c8-c97d4ab10384.png)

 **I MEANT THIS** ^ @MMThornberg

**Comment by MMThornberg** [comment]
Oh now it's a lot better, thx @kshyju ! 🙌

**Comment by thomasgauvin** [comment]
Thanks @kshyju! This fixed it!

**Comment by girlpunk** [comment]
Trying the solution provided by kshyju, but the "Download & Update" button doesn't seem to work. Clicking "Check for updates" shows "There are toolset and template updates available" as expected, but trying to download changes that to "Azure Functions toolsets and templates are up to date". This is happening on both release (17.4.2) and preview (17.5.0 Preview 1.0) versions.

Is it possible to do the update manually without going through the Visual Studio UI?

**Comment by kshyju** [comment]
> Trying the solution provided by kshyju, but the "Download & Update" button doesn't seem to work. Clicking "Check for updates" shows "There are toolset and template updates available" as expected, but trying to download changes that to "Azure Functions toolsets and templates are up to date". This is happening on both release (17.4.2) and preview (17.5.0 Preview 1.0) versions.
> 
> Is it possible to do the update manually without going through the Visual Studio UI?

See [this](https://github.com/Azure/azure-functions-dotnet-worker/issues/1023#issuecomment-1240116591)
