### ISSUE TITLE
If the Azure Function is async, all exceptions caught in middleware are AggregateException

### ISSUE THREAD

**Issue by slogan3685** [Azure/azure-functions-dotnet-worker#993]
Based on the sample project I have the following middleware...
```
public class ExceptionHandlingMiddleware : IFunctionsWorkerMiddleware
    {
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            try
            {
                await next(context);
            }
            catch (Exception ex)
            {

            }
        }
    }
```
...function, and...
```
    public class Function1
    {
        [Function("Function1")]
        public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
        {
            throw new ApplicationException("from body");
        }
    }
```
...startup code

```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(workerApplication =>
    {
        // Register our custom middlewares with the worker
        workerApplication.UseMiddleware<ExceptionHandlingMiddleware>();
    })
    .Build();
```
When I run this, the middleware catches an AggregateException containing the ApplicationException that I threw. Is this the expected behaviour, meaning I need to inspect the exception(s) within and decide how to handle them? Fwiw, if the function is not async then it works as I expected - the middleware catches the ApplicationException directly.

**Comment by SeanFeldman** [comment]
Looks similar to #912

**Comment by kshyju** [comment]
The current design is to throw an aggregate exception which contains the other exception which was thrown. We plan on changing the behavior in the next major version change, so that it will throw the actual exception instead of an aggregate exception.

**Comment by SeanFeldman** [comment]
My current workaround for now:

```
static Exception GetSpecificException(AggregateException exception) => 
     exception.Flatten().InnerExceptions.FirstOrDefault()?.InnerException ?? exception;
```

**Comment by SeanFeldman** [comment]
With `Microsoft.Azure.Functions.Worker` 1.21.0, I am seeing user code exception thrown in a trigger caught in the middleware, as expected, and no longer need the [workaround](https://github.com/Azure/azure-functions-dotnet-worker/issues/993#issuecomment-1765562932). 

I've used HTTP and ASB triggers to validate this. cc @kshyju

**Comment by unfortunatelySo** [comment]
> Based on the sample project I have the following middleware...
> 
> ```
> public class ExceptionHandlingMiddleware : IFunctionsWorkerMiddleware
>     {
>         public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
>         {
>             try
>             {
>                 await next(context);
>             }
>             catch (Exception ex)
>             {
> 
>             }
>         }
>     }
> ```
> 
> ...function, and...
> 
> ```
>     public class Function1
>     {
>         [Function("Function1")]
>         public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
>         {
>             throw new ApplicationException("from body");
>         }
>     }
> ```
> 
> ...startup code
> 
> ```
> var host = new HostBuilder()
>     .ConfigureFunctionsWorkerDefaults(workerApplication =>
>     {
>         // Register our custom middlewares with the worker
>         workerApplication.UseMiddleware<ExceptionHandlingMiddleware>();
>     })
>     .Build();
> ```
> 
> When I run this, the middleware catches an AggregateException containing the ApplicationException that I threw. Is this the expected behaviour, meaning I need to inspect the exception(s) within and decide how to handle them? Fwiw, if the function is not async then it works as I expected - the middleware catches the ApplicationException directly.

blue cross blue shield has not my swords as prives and blue prints/made and marked values as to the dry or wet and active non active molecules yojre not to have as an auditioned nole on face for try some and sample supply. plastic hardpressed risen name on disc,samsonite, e-tin. what? stinosis? stinosys? the resisted entrys by a board or panel you broke on my arse s buttox and act corporals, as all given use as abusive abuser of my accounted for, as life is to be had and living is in progress? go to the fukn dirt! ho hotel at the dump rotted fukn food is where that fukn inhumane trying fir sedistic as if a centimeter ruler gets land on accrest moon as BATTERYS ionized lithium ARE in my FUKn teeth bitch. As DDS dipshit passes my fukn money to uou bookarelli:ANCe as if airport on my airporavionics! fukn trash! . skin tags, uhhh, peice tags. whore is not iron ore bitch!
