### ISSUE TITLE
.NET Framework 4.8 - Stack API update 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#994]
Add .NET Framework (isolated) to the portal Stack API

https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks

![image](https://user-images.githubusercontent.com/4621560/185263309-0e3cf974-705f-4351-b570-80fd571f4162.png)

Currently we can use .NET 6 ( in-proc app ), and to publish my net48 isolated app to Azure. There was a popup that helped me to update runtime automatically. 

![image](https://user-images.githubusercontent.com/4621560/185263385-fd14d133-6fd0-4420-95db-c18c500ee47a.png)

But the VS code publishing process is blocked because of the inconsistency of settings : 
![image](https://user-images.githubusercontent.com/4621560/185263447-1bd96a6a-46f4-4d7a-98d8-cbf6f3bf20c2.png)

**Comment by kshyju** [comment]
runtime version [4.10.1](https://github.com/Azure/azure-functions-host/releases/tag/v4.10.1) deployment is complete. I validated the creation of dotnet-isolated function app without payload and it does not throw an error anymore.

We should be good to move ahead with the portal changes.

**Comment by cloudmelon** [comment]
@kshyju any updates on this one ?

**Comment by kshyju** [comment]
> @kshyju any updates on this one ?

@cloudmelon  Did you mean the portal update? I am not working on that. I thought you were working with the portal team to get that done.

**Comment by cloudmelon** [comment]
> > @kshyju any updates on this one ?
> 
> @cloudmelon Did you mean the portal update? I am not working on that. I thought you were working with the portal team to get that done.

no I meant if the PR is in, and i can follow up with the portal team for the rest :

Can you send a PR for the same here and I can help review and merge - https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks

**Comment by fabiocav** [comment]
Link to a reference PR : https://github.com/Azure/azure-functions-ux/pull/6737
