### ISSUE TITLE
SignalR documentation feedback

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-dotnet-worker#995]
## Context

I needed to add SignalR to a project to enable notifications from Azure Functions to Blazor WebAssembly. This should have been an easy task, but I've spent a significant amount of time chasing what could have been resolved by up-to-date documentation and samples.

First, the documentation on SignalR with Azure Functions Isolated SDK lacks a [sample](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service?tabs=isolated-process&pivots=programming-language-csharp) for negotiation. 

Second, the [code snippet](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/SignalR/SignalRNegotiationFunctions.cs) provided in this repository to demonstrate how to implement the negotiation function is **not functional** as it produces invalid response the caller cannot process.

https://github.com/Azure/azure-functions-dotnet-worker/blob/0c808d7b990328920a078d86a4cf2b2be00ffe77/samples/Extensions/SignalR/SignalRNegotiationFunctions.cs#L8-L12

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1309622/185303870-b5d018a5-72fc-416e-89c5-3d02be2b1c0b.png">

The code that does work (huge thank you to @anthonychu, who's helped me to troubleshoot this):

```c#
[Function("Negotiate")]
public static HttpResponseData Run(
	[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
	[SignalRConnectionInfoInput(HubName = "chat")] string connectionInfo,
	FunctionContext executionContext)
{
	var response = req.CreateResponse(HttpStatusCode.OK);
	response.Headers.Add("Content-Type", "application/json");

	response.WriteString(connectionInfo);

	return response;
}
```

Generates correct response and enable clients to work.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/1309622/185304203-b1e73973-548c-464f-96c1-f0a600d43341.png">

## What's expected?

1. Update documentation to include the negotiation code required for the serverless scenario.
1. Review and update [sample code](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions/SignalR) for SignalR extension to ensure it's operational.
1. Provide a sample as a downloadable project instead of code snippets.

**Comment by fabiocav** [comment]
@Y-Sindo can you provide more information about who we'd be able to work with to make the documentation enhancements?

**Comment by SeanFeldman** [comment]
I think @cloudmelon was looking into this in parallel. I might be wrong.

**Comment by Y-Sindo** [comment]
@fabiocav for all things about SignalR Functions extensions you could contact me.

**Comment by Y-Sindo** [comment]
@SeanFeldman I'd like to add some comments on the 2nd and 3rd questions:

> 2. Review and update [sample code](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions/SignalR) for SignalR extension to ensure it's operational.

For the negotiation sample, we usually make an HTTP request to get the negotiation response, and then use the URL and access token in the negotiation response to build a `HubConnection` directly. And we have a [JavaScript SignalR client sample here](https://github.com/aspnet/AzureSignalR-samples/blob/main/samples/DotnetIsolated-BidirectionChat/content/index.html#L157-L183). Of course, it is a little more inconvenient than the tricky method which declares the `SignalRConnectionInfo` as a string. I intend to add a new class which contains camel case properties to mitigate the problem.

> 3. Provide a sample as a downloadable project instead of code snippets.

Currently we do have a complete sample whose link is provided [here](https://docs.microsoft.com/azure/azure-signalr/signalr-quickstart-azure-functions-csharp#next-steps). It's not easy to find the link. It would be better if we could add the link somewhere in the reference doc of SignalR bindings. @fabiocav @cloudmelon Do we have guidance on how to add a sample link to the function bindings docs? I am willing to work together with you to make our documents better.

**Comment by SeanFeldman** [comment]
@Y-Sindo thank you for the info. The link you've provided is for the In-Process SDK. And the code works. The issue I've raised is about the similar code for the Isolated Worker SDK, and it's not working because the response is not serialized as proper JSON value.

I'll add that if the Isolated Worker SDK is what Microsoft wants to see adopted as the first option, it needs to work and not lag behind the equivalent in In-Process SDK. I'm sure there's something planned, right @fabiocav ? 🙂

**Comment by liliankasem** [comment]
Resolving as samples were updated by @Y-Sindo
