### ISSUE TITLE
Dependency not tracking correctly in Application Insights

### ISSUE THREAD

**Issue by LenaVinogradov** [Azure/azure-functions-dotnet-worker#998]
@LenaVinogradov -- can you open a separate issue with exactly what you're seeing and what you expect to see? That'd help us narrow it down. Thanks!

_Originally posted by @brettsam in https://github.com/Azure/azure-functions-dotnet-worker/issues/760#issuecomment-1220962314_

I have used new preview package and the sample code from the quoted PR: 
"The preview "packages are now available: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights.

For usage and explanation, see the PR here (official docs will come when this is out of preview): https://github.com/Azure/azure-functions-dotnet-worker/pull/944."

Here is a code of our program.cs:
```csharp
public class Program
{
	public static async Task Main()
	{
		var host = new HostBuilder()
			.ConfigureFunctionsWorkerDefaults(builder =>
			{
				builder.UseNewtonsoftJson();
				builder.AddApplicationInsights().AddApplicationInsightsLogger();
			})
			.ConfigureOpenApi()
			.ConfigureAppConfiguration(builder => Startup.ConfigureAppConfiguration(builder))
			.ConfigureServices(collection => Startup.Configure(collection))
			.Build();

		await host.RunAsync();
	}
}
```
With this package we can see dependencies in appinsights (we moved from Functions v3.0 a couple of month ago, so we are very unhappy to loose the telemetry functionality that we were heavily relying on for years), but this dependencies are not properly linked to parent. The have the correct operationId set, so we can see them together with the rest of telemetry objects for the same operation, but hierarchy is still lost as the parentId of the dependencies do not point to any object in appinsights.

**Comment by LenaVinogradov** [comment]
![image](https://user-images.githubusercontent.com/1653359/185686069-9d0b8612-802b-462e-b660-abe548317a39.png)
here is an illustration. parent Id should be object id of the function request object, but it is not.

**Comment by brettsam** [comment]
Thank you for the report!
Some questions:
- Can you share what this looks like in 3.0 (if you have it?). I'm assuming the MICROSOFT.TABLES calls show up under that parent you've pointed to?
- Are you using output bindings for the Table entries? Or are you using the Storage SDK directly in your function?

**Comment by LenaVinogradov** [comment]
1. we moved away from using output bindings. Using storage clients from storage SDK
2. here is how it looked with Functions 3.1: 
![image](https://user-images.githubusercontent.com/1653359/185707716-ea57a3d2-54e6-4496-b4e6-93840402d264.png)
thank you!

**Comment by brettsam** [comment]
Thanks @LenaVinogradov -- I think I have an improvement here. It'll be included in the next preview of the AppInsights package. Thanks for the report!

**Comment by LenaVinogradov** [comment]
thank you for the good news!
I have one more issue to report though. We still see the multiple Trace messages logged for all dependencies (usually one for start request and one for stop)  in addition to the Dependency object in AppInsights. We were hoping the re-introducing the dependencies back in the preview package will eliminate the extra traces. Can you please advise how we can disable them? 
Here is a segment of just one execution : 
![image](https://user-images.githubusercontent.com/1653359/186307377-6f1216c5-ff36-47c5-9f6f-5858bfbd9646.png)

**Comment by brettsam** [comment]
FYI -- preview2 is now available: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview2

**Comment by mvacha** [comment]
@brettsam I can confirm that with preview2 the dependecies are correctly nested. 👍
